### ISSUE TITLE
Release 0.4: MWST-Satz-Null

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#10]
Im Changelog heißt es:
*MWST-Satz-Null: Dieser Betrag wurde fäschlicherweise zum Umsatzzähler addiert.*

… und im Beispielcode werden die mit 0% USt. versteuerten Umsätze nun tatsächlich nicht mehr zum Umsatzzähler addiert. Ist das wirklich so gefordert, und wenn ja, warum? Damit würden alle in §6 Abs. 1 UStG genannten Umsätze (also z.B. sämtliche Umsätze der Kleinunternehmer, aber auch alle anderen USt.-befreiten Umsätze, z.B. jene von Ärzten) nicht zum Umsatzzähler addiert werden.

Die Felder "Betrag-Satz-…" enthalten ja nicht die USt. selbst, sondern den *Bruttobetrag* (inkl. USt.) der Barzahlung. Die Summe aller "Betrag-Satz-…"-Felder muss meiner Meinung nach den zum Umsatzzähler zu addierenden Betrag ergeben, denn diese Felder stellen laut RKSV §11 Abs. 3 den "Betrag der Barzahlung getrennt nach Steuersätzen" dar. Wenn man die 0%-Umsätze nicht zum Umsatzzähler addierte, wäre dies aber nicht mehr der Fall.

**Comment by pteufl** [comment]
wird weitergeleitet. danke für die anfrage.

**Comment by pteufl** [comment]
Rücksprache mit BMF:
Wird bis nächste Woche geklärt. (Ihre Punkte sind natürlich sehr relevant, daher eher davon auszugehen, dass NULL-Satz zu Umsatzzähler addiert wird). Danke für das Feedback!

**Comment by pteufl** [comment]
Hinweis nun auch im README auf der Front-Page.

**Comment by pteufl** [comment]
Null-Satz ist für Umsatzzähler relevant. Issue wird in 0.5 behoben.
