### ISSUE TITLE
Unterschiedliche Nummernkreise im DEP

### ISSUE THREAD

**Issue by geraldsix** [a-sit-plus/at-registrierkassen-mustercode#100]
Gibt es ein Problem, wenn Rechnungszahlungen einen anderen Nummernkreis als die normalen Barverkäufe haben?
z.B. Reihenfolge in DEP:
Barverkauf BelNr 4711
Barverkauf BelNr 4712
Bezahlung einer Zielrechnung BelNr 815
Barverkauf BelNr 4713

**Comment by asitplus-pteufl** [comment]
Kann ich leider nicht beantworten, muss Sie leider auf die Standardantwort für organisatorische Themen verweisen. 

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
