### ISSUE TITLE
DEP Null transactions on start/end month question

### ISSUE THREAD

**Issue by dfens** [a-sit-plus/at-registrierkassen-mustercode#101]
Hello,

I have a question about closing period in DEP report.

It is required to close each month with null transaction and open new month with null transaction.

Please see this very simplified example
```
datetime/belegno/type
# June
2016-06-02 13:30:30 / 1 / null <-start month
2016-06-20 13:30:30 / 2 / normal
2016-06-28 13:30:30 / 3 / normal
2016-06-30 23:59:59 / 4 / null <- end month

# July, other way
2016-07-01 13:30:30 / 5 / null <-start month
2016-07-20 13:30:30 / 6 / normal
2016-08-01 01:59:59 / 7 / null <- end month, done in next month
```
My questions:
- must start month transaction be done every first day of a month?
- must end month transaction be done every last day of month? Is it supposed to be done like in last second of month? Can it be done next day ? (like in July example)

**Comment by ErichFreitag** [comment]
@dfens: there is no need for an end transaction. It is only required to make a null transaction before a new "normal" transaction in a new month

-> month start transaction is not required to be made on the first day of a month but before the first normal transaction in a month
-> no month end transaction

**Comment by dfens** [comment]
@ErichFreitag thank you. This is a big difference for me and much more easy to handle.. . So if month is without transactions at all - monthly DEP is just empty then
