### ISSUE TITLE
Technologiewechsel

### ISSUE THREAD

**Issue by maxmaxAT** [a-sit-plus/at-registrierkassen-mustercode#102]
Guten Tag,

lt. §23 Abs. 1 RKSV bedarf es eines neuen Gutachtens für geschlossene Gesamtsysteme, wenn eine umfassende Umstellung des geschlossenen Gesamtsystems (z.B. Technologiewechsel) geplant ist.
Ab wann trifft ein wesentlicher Technologiewechsel aus technischer Sicht gesehen zu?

1. Tausch eines Kassendruckers oder Displays?

2. Softwareänderungen im Netzwerk wie z.B. Änderung der Gerätefirmware, Konfigurationsänderungen von Netzwerkkomponenten?

3. Hardwareänderungen im Netzwerk wie z.B. Austausch von Netzwerkkomponenten, hinzufügen von Netzwerkkomponenten, hinzufügen von neuen Gerätetypen wie z.B. Access Point?

4. Handelt es sich um einen Technologiewechsel, falls sich der Weg zum Speicher der extern mitlaufendenden Ereignisprotokolldatei ändert?

Vielen Dank!

**Comment by ErichFreitag** [comment]
Hallo @maxmaxAT.

Der Fokus eines geschlossenen Gesamtsystems liegt ja darauf, dass die Signaturerstellung mittels Software erfolgt. Bei einem Gutachten fällt daher - neben der Prüfung der grundsätzlichen Funktionen des Kassensystems - das Hauptaugenmerk auf jene Komponente(n), welche die Signaturerstellung durchführen. Das umfasst neben technischen Aspekten auch organisatorische Untersuchungen und Beurteilungen. 

Daraus ergibt sich, dass ein Drucker oder ein Display und dergleichen keinerlei Einfluss auf einen Technologiewechsel in diesem Sinne haben, ebensowenig wie "der Weg zum Speicher". Mit Sicherheit würde aber ein Wechsel eines Betriebssystems einem gänzlichen Technologiewechsel entsprechen, ebenso ein Versionswechsel des gleichen Betriebssystems.

Hingegen kann (kann, nicht muss) alles andere Einfluss haben. Da die Software-Signaturerstellungseinheit lokal oder zentral betrieben werden kann, hat das Netzwerk einen Einfluss auf die Beurteilung - gerade in Hinsicht auf die technische und organisatorische Beurteilung. Konkret: wie ist der Zugriff auf die Signaturerstellungseinheit im Netzwerk geregelt? wie wird Manipulationssicherheit erreicht? wie können vor allem unerlaubte Zugriffe und Änderungen erkannt werden? kann die Funktion der Signaturerstellungseinheit auch umgangen werden? und dergleichen mehr.

Ein Gutachten für geschlossene Gesamtsysteme beurteilt und bewertet all diese Fragen und dokumentiert diese neben der Architektur des Systems. Wenn dies ordentlich und ausführlich genug erfolgt, dann wird es in Folge zunächst ohne Sachverständigen relativ einfach sein zu beurteilen, ob eine Änderung im System einen Einfluss haben kann oder nicht.

Wenn sie bereits wie oben angeführt konkrete Ideen für mögliche Änderungen haben, dann macht es ja vielleicht auch Sinn, diese Aspekte in einem Gutachten mit aufzunehmen. Ein Beispiel: sie planen, einen Acess Point hinzuzufügen. Dann kann man sich bereits im Vorfeld (bei der Gutachtenserstellung) überlegen, wie dieser in das Kassen-Netzwerk eingebunden wird, wer darüber worauf Zugriff haben soll und wie dabei sichergestellt wird, dass dadurch eben die Software-Signaturerstellungskomponente nicht manipuliarbar wird (sprich wie die Konfiguration erfolgen muss).


Ergänzend noch aus den aktuellen Erläuterungen zur RKSV:
"Neben der Prüfung der technischen Voraussetzungen für die Manipulationssicherheit des geschlossenen Gesamtsystems sind auch alle organisatorischen Maßnahmen und Verantwortlichkeiten, die die Manipulationssicherheit sicher stellen, zu prüfen und im Gutachten darzulegen"

sowie

"Für bloße Software-Updates ist eine neue Begutachtung, bzw. ein neuer Feststellungsbescheid nicht erforderlich, sondern nur bei einem gänzlichen Technologiewechsel und bei jeder Änderung der Softwarekomponenten der Sicherheitseinrichtung".

**Comment by ErichFreitag** [comment]
Ergänzend noch eine typische Prüfliste um ein Gefühl für Inhalt und Umfang zu bekommen:

[PQRST_RKSV_Gutachtenvorlage.docx](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/351712/PQRST_RKSV_Gutachtenvorlage.docx)

**Comment by asitplus-pteufl** [comment]
Aus A-SIT Plus Sicht kann ich hier leider nur die "Standard-Antwort" geben.

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.
