### ISSUE TITLE
Zertifikat-Seriennummer bei Ausfall der Sicherheitseinrichtung

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#103]
Wir lesen die Zertifikat-Seriennummer bei jedem Vorgang aus der RSK-Card aus.
Beim Ausfall des Kartenlesers ist dies ja nicht möglich, die Zertifikat-Seriennummer wird zum Erstellen des DEP-Satzes aber benötigt.
Ist es richtig, dann die zuletzt verwendete Zertifikat-Seriennummer dafür zu verwenden ?

**Comment by lebail** [comment]
Ja, das sollte so passen (falls es nicht eine weitere - funktionierende - Karte gibt). Siehe meine frühere Frage https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/42 zu diesem Thema.

**Comment by asitplus-pteufl** [comment]
@lebail danke für die Beantwortung. Schließe mich da an.
