### ISSUE TITLE
Source fuer Verifikationstool

### ISSUE THREAD

**Issue by rjungbeck** [a-sit-plus/at-registrierkassen-mustercode#104]
Gibt es das Verifikationstool auch irgendwo im Source?

Ich bekomme nur 

     java -jar regkassen-verification-depformat-0.6.jar -i dep-export.json - c cryptographicMaterialContainer.json
    Exception in thread "main" java.lang.NullPointerException
            at     at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule    .verify(DEPExportFormatVerificationModule.java:100)
            at     at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:85)

was nicht wirklich aussagefähig ist.

**Comment by asitplus-pteufl** [comment]
nein ist nicht geplant den Source Code zu veröffentlichen, allerdings (ist für august eine neu überarbeitete version des prüftools in planung, die detallierte Fehlermeldungen liefert und QS-gesichert ist. (im ersten Schritt für die QR-Code Einzelprüfungen, für die DEP-Prüfungen etwas später).
stimmt die seriennummer im Beleg mit der seriennummer im cryptographicMaterialContainer.json überein?

**Comment by rjungbeck** [comment]
Danke für die schnelle Antwort: Der Tipp mit der Seriennummer hat an dieser Stelle geholfen. 

Grundsätzlich müssten die Meldungen  des Tools aber sehr viel genauer sein (und es dürfte natürlich  überhaupt keine Abbrüche des Tools selbst geben), wenn der Sourcecode nicht veröffentlicht wird. Auch sind so die Zwischenergebnisse natürlich nicht mehr für die Fehlersuche verfügbar.

Bei der Nutzung sind mir noch folgende Dinge aufgefallen:

Kann es sein, dass das Tool einen 8 stelligen encrypteten Umsatzzähler fordert (obwohl auch ein 5 stelliger Umsatzzähler erlaubt ist)?

Die folgende Meldung ist so auch nicht sinvoll:
ÜBERPRÜFUNG: "Format: Anzahl Elemente": FEHLERHAFT
DETAILS: Es wurden 13 Elemente statt 13 im Maschinen-Code gefunden.

**Comment by asitplus-pteufl** [comment]
genau, diese punkte werden im Detail von Version 0.7 behandelt (für die einzelbelege), DEP Details folgend danach.
Annahme zum Umsatzzähler ist auch korrekt (auch bei Version 0.7 für Einzelbelege)

**Comment by samuel4711** [comment]
Hänge mich an der Stelle mal dran. 
Ich bekomme eben genau diese Fehlermeldung 
-----------Detailresultate fuer Paket-------------------
Überprüfung von Beleg 3

ÜBERPRÜFUNG: "Format: Anzahl Elemente": FEHLERHAFT
DETAILS: Es wurden 13 Elemente statt 13 im Maschinen-Code gefunden.

ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben.
STACKTRACE: java.lang.ArrayIndexOutOfBoundsException: 1
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.SignatureVerificationModuleJWSFormat.verify(SignatureVerificationModuleJWSFormat.java:76)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.SignatureVerificationModulePlainFormat.verify(SignatureVerificationModulePlainFormat.java:49)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.MachineCodeVerificationModulePlainFormat.verify(MachineCodeVerificationModulePlainFormat.java:68)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.QRCodeRepVerificationModule.verify(QRCodeRepVerificationModule.java:72)
        at at.asitplus.regkassen.verification.cmdline.CheckSingleReceipt.main(CheckSingleReceipt.java:94)

++++++++++++++++++++++++++++++




Wo könnte ich die notwendige Info bekommen,was da genau falsch läuft ?

**Comment by asitplus-pteufl** [comment]
Können Sie einen Beleg hier posten?

**Comment by samuel4711** [comment]
klar :-)
_R1-AT0_DEMO-CASH-BOX_130370_2015-12-17T11:23:44_0,00_0,00_0,00_26,05_0,00_+4gVbHiHGKr9ZCIzJ0yh8w==_1B469C_1DUkNhEeJKY=

**Comment by asitplus-pteufl** [comment]
noch ein "_" vorne dazu geben.... (Die Fehlermeldungen in 0.7 werden denen entsprechen die auch in FinOnline oder über das WebService zur Verfügung stehen).

**Comment by samuel4711** [comment]
ist ein _ davor. nur wurde es weggeschnitten als ich es eingefügt habe.

**Comment by asitplus-pteufl** [comment]
aber da ist weitere hinten auch noch ein Fehler. nach 0,00 ist kein "_", danach scheint aber auch noch ein Feld zu fehlen, da muss ja umsatzzähler, verkettung und signatur sein, ich seh da aber nur 2 felder

**Comment by samuel4711** [comment]
Das verstehe ich nicht ganz ...  da ist doch ein _ hinter der letzten 0,00
danach kommt 
+4gVbHiHGKr9ZCIzJ0yh8w== ( UmsatzZähler )
1B469C Seriennummer Zertifikat
1B469C_1DUkNhEeJKY= Verkettung

**Comment by areiter** [comment]
Ihnen fehlt hinter dem Verkettungswert `1DUkNhEeJKY=` noch die eigentliche Signatur dieses Belegs.

Schauen sie mal in die Detailspezifikation: Z12. Den ersten Punkt (Signierte Belegdaten) haben sie inkludiert, der 2. (Signaturwert) fehlt ihnen aber.

**Comment by samuel4711** [comment]
Großartig ... danke das war es. Nun hätte ich noch ein weitere frage ... Was könnte das noch sein :

ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen: Dekodierter Signaturwert: 0D☻ f~feÀ W?ü
☺V♂²Ã?ßcË?§Ô
?Ç8sÒ(è8ñ#☻ ♣ê5??♫?=C?ç?§î¦Ê◄?>‼a▲,èG©ÿÊ▬j?Å

++++++++++++++++++++++++++++++

`_R1-AT0_DEMO-CASH-BOX_130370_2015-12-17T11:23:44_0,00_0,00_0,00_0,00_0,00_+4gVbHiHGKr9ZCIzJ0yjaQ==_1B469C_sEvHZLAjsMc=_Zn5mZcAgV5L8AVYLssON32PLk6fUCpzHOHPSKOg48SMF6jWUmQ6MPUOH54Wn7qbKEZs+E2EeLOhHqf/KFmo/xQ==`

**Comment by asitplus-pteufl** [comment]
das sagt aus dass die signatur nicht korrekt ist. Details dazu kann man nicht ableiten. Überprüfen Sie  bitte die Belegaufbereitung und die Signaturerstellung. Bitte achten Sie auf die Korrekte Kodierung der Signatur (DER ist falsch). Da gab es hier schon unterschiedliche Issues, bitte mal da Lesen https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/111

**Comment by samuel4711** [comment]
Was ist den mit den Demo Belegen ? 
Überprüfung von Beleg 80

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": FEHLERHAFT
DETAILS: Ungültige BASE64 Zeichenkette: OZCSSBVEYFKGY===

ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": FEHLERHAFT
DETAILS: Ungültige BASE64 Zeichenkette: G4E2BSFHWI3GO===

ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": FEHLERHAFT
DETAILS: Base64 Decoding/Encoding nicht gleich: Orginal BASE64 String: OZCSSBVEYFKGY=== Reencoded String: OZCSSBVEYFKG

ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": FEHLERHAFT
DETAILS: Base64 Decoding/Encoding nicht gleich: Orginal BASE64 String: G4E2BSFHWI3GO=== Reencoded String: G4E2BSFHWI3G

ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen: Dekodierter Signaturwert: 0R☻' àp☺8s?,♦
 Ô¶ÞÅ♦´☺∟¶?DsÊ1d?DFP$T↨b:C½×ís☻' ?

++++++++++++++++++++++++++++++

**Comment by asitplus-pteufl** [comment]
Nicht ganz klar was hier passiert ist, die DEMO Belege müssten alle korrekt sein. Inzwischen wurde aber eine neue Version des Prüfools veröffentlicht. Bitte Ihre Implementierung dagegen prüfen.

**Comment by samuel4711** [comment]
Hallo,
leider kommen wir auch an der Stelle nicht wirklich weiter und ich weiß auch keinen den ich weiter fragen könnte. Habe hier mal alle relevanten Daten zusammen gepackt und per Zip File angehängt ...
Wäre für jeden Tip dankbar
[crypt.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/463861/crypt.zip)

**Comment by asitplus-pteufl** [comment]
Es lässt sich nur sagen dass die Signatur nicht korrekt ist. Das kann mehrere Gründe haben:
Der Hash-Wert für die Signatur wird über die falschen Daten gerechnet. Wenn der Hash-Wert korrekt ist, dann kann es sein, dass bei der Signatuerstellung selbst ein Fehler ist, oder dass das Signaturergebnis (von Karte oder Service) nicht nach dem JWS-Standard kodiert ist. Bitte noch im Detail die Punkte im Detaildokument bzw. im Muster-Code lesen.
Vielleicht noch ein trivialer Fehler: Ist sicher das richtige Zertifikat im Cryptocontainer?
