### ISSUE TITLE
PKCS#11 access auf das A-Trust RK Chip "Signaturzertifikat" und nicht das "Geheimhaltungszertifikat"?

### ISSUE THREAD

**Issue by erneu** [a-sit-plus/at-registrierkassen-mustercode#105]
Hallo,

Wir sind an der Implementation des Democodes und der Einbindung des A-Trust RK Chips.
https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-core/src/main/java/at/asitplus/regkassen/core/modules/signature/rawsignatureprovider/PKSC11SystemSignatureModule.java

Der A-Trust RK Chip hat 2 Zertifikate drauf
Im a.Sign Client (v1.3.2.29) benannt mit:  "Signaturzertifikat" und "Geheimhaltungszertifikat"

Das Signaturzertifikat (mit Elliptic Curve Keys) ist jenes, das verwendet werden müsste - im a.Sign Client kann ich es auch exportieren:

openssl x509 -in RKChipZertifikatA-Trust.cer -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: xxxxxxx (0xXXXXXX)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverke                                                                                                               hr GmbH, OU=A-Trust Registrierkasse.CA, CN=A-Trust Registrierkasse.CA
        Validity
            Not Before: Nov 30 14:50:21 2015 GMT
            Not After : Nov 30 13:50:21 2020 GMT
        Subject: C=AT, CN=UID ATUxxxxxxxx/serialNumber=xxxxxxxxxxxx
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
            EC Public Key:
                pub:
                    04:ff:51:6e:36:9e:4c:af:9d:cf:e9:27:d2:7c:e5:
                    21:ab:7d:87:01:e7:93:17:2b:b4:38:d9:2b:8b:66:
                    e8:e4:9a:56:3a:bc:23:fa:45:c0:63:96:f7:0d:92:
                    ce:6f:8e:ac:53:f1:da:ee:0e:f6:a7:33:7d:d2:45:
                    0c:1e:86:7d:6a
                ASN1 OID: prime256v1
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                4F:3C:99:BA:E1:FC:39:36
            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation
            1.2.40.0.10.1.11.1:
                ..UID ATUxxxxxxxx
            X509v3 Authority Key Identifier:
                keyid:40:47:9E:AE:E3:90:DF:B6

            X509v3 Basic Constraints:
                CA:FALSE
            Authority Information Access:
                CA Issuers - URI:http://www.a-trust.at/certs/A-Trust-Registrierk                                                                                                               asse-CA.cer

            X509v3 Certificate Policies:
                Policy: 1.2.40.0.17.1.24
                  CPS: http://www.a-trust.at/docs/cp/A-Trust-Registrierkasse

            X509v3 Subject Alternative Name:
                email:xxxxxx@xxxxxxxx.at
    Signature Algorithm: sha256WithRSAEncryption
        0e:54:68:1b:d4:7f:9f:3a:9e:df:9d:8f:f5:7b:a5:55:78:77:
        b6:7e:62:38:df:4a:03:d7:d9:81:00:db:ad:79:1c:0f:c6:80:
        12:b7:ab:92:1f:44:24:81:87:3f:c3:ea:da:29:09:27:52:b6:
        6c:e4:e8:6a:e8:54:4a:50:ad:53:48:42:96:72:e1:db:5b:38:
        39:0e:64:f7:d1:a3:74:53:de:fe:3e:f4:b4:38:66:64:bc:d4:
        34:51:f4:0c:85:c3:44:96:d0:a1:bf:ea:8e:9f:7b:51:7b:ce:
        24:cf:c7:4f:2f:24:dc:b6:ab:b5:1e:35:90:ce:ee:e5:8d:54:
        37:76:94:30:4c:09:2b:9f:0d:96:1c:1c:7c:05:b1:5a:c1:58:
        bc:3d:13:9c:f0:99:31:80:49:f0:86:ea:ef:29:b3:46:f7:33:
        c5:66:8e:96:9b:a1:0d:cc:12:4c:55:9f:c3:b4:ee:10:a8:bb:
        f4:5b:44:0e:be:c8:bd:ef:43:be:59:14:4a:47:ad:4f:30:24:
        1a:b2:b3:fd:7e:74:fd:73:e2:63:11:7f:63:c4:d1:e1:05:bc:
        18:48:40:57:ea:dc:3e:0d:e7:af:6b:14:47:79:4b:3f:2e:db:
        91:7d:4d:b7:1a:f1:7e:ce:eb:cd:47:08:a1:fe:ce:50:89:4e:
        c0:01:22:8b:ba:d0:1a:c5:9d:6f:d4:76:c0:bb:4b:83:ef:12:
        82:01:d9:69:cf:91:77:95:7d:61:d0:cc:14:5b:d1:85:6f:e2:
        ce:40:5d:07:6e:b4:95:f2:ff:3f:da:eb:c6:0e:b6:cd:a6:55:
        32:8b:4b:47:9a:f4:2c:a0:41:36:f2:15:42:1b:22:d7:83:2b:
        67:14:67:f9:d4:56:cf:f5:a9:e8:90:de:3a:0d:ca:05:a9:a8:
        92:4a:07:68:46:44:4f:29:5f:86:f1:6c:ae:73:b9:1f:67:4d:
        d8:1f:0c:80:bb:3b:df:d6:90:19:76:cc:6b:93:e5:e2:d4:e8:
        41:7e:23:d7:85:66:a8:c5:f2:8c:16:22:e1:77:dc:b3:97:03:
        0f:8b:6a:c6:58:91:f4:0e:85:1b:4a:fb:24:bc:31:40:30:b3:
        3a:a8:f6:fb:14:a7:46:c7:1a:7d:f1:11:3f:ac:9e:cd:7b:8a:
        b3:c8:1b:e1:25:d7:a3:c0:65:17:55:25:55:4a:b3:0d:ba:c1:
        fb:33:5e:b3:68:a3:91:d7:2a:fd:71:56:41:77:46:0d:93:6f:
        92:0f:e8:d6:6a:53:c4:e6:04:5e:96:c7:a8:66:5b:c5:e3:80:
        ec:22:e3:69:36:dc:3d:c7:0e:5e:93:d1:4e:58:5c:64:71:aa:
        3e:78:88:98:5f:19:69:cd

Das zweite "Geheimhaltungszertifikat" (mit RSA Keys) ist nicht von Interesse für die Signatur der RK Daten.
Soweit wäre alles klar.

Aber wenn wir per Java die PKCS#11 (asignp11.dll) einbinden, dann bekommen wir nur Zugriff auf das "Geheimaltungszertifikat"   siehe:

P:\Program Files\Java\jre1.8.0_92\bin>keytool -list -v -keystore NONE -storetype PKCS11 -providerClass sun.security.pkcs11.SunPKCS11 -providerArg P:\Temp\pkcs11.cfg
Keystore-Kennwort eingeben:

*****************  WARNING WARNING WARNING  *****************
* Die Integrität der Informationen, die in Ihrem Keystore gespeichert sind, *
* wurde NICHT geprüft. Um die Integrität zu prüfen, *
* müssen Sie Ihr Keystore-Kennwort angeben.                  *
*****************  WARNING WARNING WARNING  *****************

Keystore-Typ: PKCS11
Keystore-Provider: SunPKCS11-asign

Keystore enthält 1 Eintrag

Aliasname: C.CH.EKEY
Eintragstyp: PrivateKeyEntry
Zertifikatskettenlänge: 1
Zertifikat[1]:
Eigentümer: SERIALNUMBER=xxxxxxxxxxxx, C=AT
Aussteller: CN=A-Trust Registrierkasse.ENC, OU=A-Trust Registrierkasse.ENC, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, C=AT
Seriennummer: xxxxxx
Gültig von: Mon Nov 30 15:50:21 CET 2015 bis: Mon Nov 30 14:50:21 CET 2020
Zertifikat-Fingerprints:
         MD5:  74:3C:0E:78:8C:BA:49:A8:E0:B4:89:E8:F9:4E:8E:A4
         SHA1: 61:DD:33:06:62:68:80:03:32:66:DC:6D:71:12:DD:EE:8B:20:59:6A
         SHA256: 97:A0:F7:6B:F0:95:1B:DD:A7:99:8C:63:7F:81:AD:4C:1B:36:C4:08:C1:3C:4A:0B:58:4A:6B:C5:9F:D8:40:CE
         Signaturalgorithmusname: SHA256withRSA
         Version: 3

Erweiterungen:

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  []
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 41 F6 64 F2 23 B4 6E 20                            A.d.#.n
]
]

#3: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#4: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  DigitalSignature
  Key_Encipherment
  Data_Encipherment
]

#5: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  RFC822Name: xxxxxx@xxxxxxxx.at
]

#6: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 48 C7 2E 89 39 68 70 87                            H...9hp.
]
]

*******************************************
*******************************************

Auf A-Trust Dokumentationen finde ich keine Lösung für den Zugriff auf das Signaturzertifikat / das Signaturkeypair  - somit fehlt mir die Information für den richtigen KEY_ALIAS für den Mustercode:

"C.CH.EKEY" ist ja der Alias für das "falsche" Zertifikat
Wie lautet der richtige KEY_ALIAS für das "Signaturzertifikat"?
Oder gib es auf der Karte mehrere Keystores?
Bedarf es eines Keystore PINs - den ich nirgendwo habe/finde? 
(den benötige ich auch nicht um im a.Sign Client beide Zertifikate zu exportieren...was ja aus meiner Sicht passend ist für die öffentlichen Zertifikate)

Danke für jedwede Info diesbezüglich!
Es fehlt wohl nur ein winzig kleiner Schritt...zur Signatur...mit echtem Chip anstatt dem "NEVER_USE_IN_A_REAL_SYSTEM" Software Keypair/Zertifikats Beispiel.

Merci vorab!
Erich

**Comment by A-Trust** [comment]
Hallo Erich,

unser empfohlene Weg auf die Karte unter Java zuzugreifen sind direkte APDU Kommandos. Ein Beispiel dafür findest du unter http://labs.a-trust.at/developer/ShowSource.aspx?id=114.

Dadurch ist auch die Installation des a.sign Clients nicht mehr notwendig, sondern der Zugriff funktioniert allein mit Java Bordmittel.

**Comment by erneu** [comment]
Hallo A-Trust,

Danke für den Verweis auf das APDU Beispiel.

Hmmm...APDU ist auf exakt Eure Chipkarte im jetzigen Card OS gebunden - wenn einer unserer Endkunden sich für einen anderen Zertifikatsanbieter entscheiden möchte, oder sich etwas am CardOS einer zukünftigen SmartCard ändert,... dann geht es dann nicht mehr.

PKCS#11 wäre Zertifikatsanbieterneutral - das widerspricht aus kaufmännischer Sicht verständlicherweise dem A-Trust Interesse.


Im "BMF Detailfragendokument 1.1 11.3.2016 " (https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.1-DOK/2016-03-11-Detailfragen-RKSV-V1.1.pdf) unter Punkt 3.1 Erstellung der JWS-Signatur finden wir den Punkt "Referenzen - Muster-Code - Signatur via APDUs" -> noch nicht vorhanden.

- Wird es von der A-SIT im Mustercode eine Abstraktionsschicht für APDU geben od. eine auf Basis des angeführten Beispiels eine ("A-Trust") Version?

Wenn soetwas in Vorbereitung ist im nächsten Mustercode Release, dann wollen wir nicht parallel entwickeln.  Herr Teufel, gibt es da von Ihrer Seite Input?

Danke
Erich

**Comment by asitplus-pteufl** [comment]
Das muss noch mit dem BMF geklärt werden, generell wäre natürlich eine Demonstration im Muster-Code sicher von Vorteil.

**Comment by thritter** [comment]
Ich habe eine Frage zum Ergebnis der Signatur (apduExamples_0.5.zip):

Mit "byte[] doSignatur(byte[] sha256Hash, String pin)" kriege ich ja 
einen Byte block.

Leider finde ich in der API Beschreibung (APDU_API.pdf) keine 
Information wie dieser Blob "formatiert" ist

  - ist das Ergebnis schon DER kodiert ?
  - sind das die "RAW" ECDSA Koordinaten (little/big endian, size ?)
  - ....

Danke vorab,
Thomas

**Comment by A-Trust** [comment]
Hallo Thomas,

es werden die RAW ECDSA Koordinaten (x,y) zurückgeliefert. Für die RKSV Signatur diesen Wert einfach base64 bzw. base64url kodieren und direkt an  jws_header und jws_payload anhängen.

**Comment by scheffold** [comment]
Hallo @asitplus-pteufl ,

kann damit gerechnet werden dass in den "Detailfragen RKSV 1.2" der Mustercode "Punkt 3.1 Erstellung der JWS-Signatur finden wir den Punkt "Referenzen - Muster-Code - Signatur via APDUs" -> noch nicht vorhanden." nachgeliefert wird? Wann wird diese veröffentlicht? Laut Issue #107 anscheinend ja im August.

Besten dank mal für die Info,

Frank

**Comment by asitplus-pteufl** [comment]
Dies muss erst mit dem BMF abgestimmt werden. Kann ich daher leider nicht direkt beantworten. Aktuell kann ich Sie hier nur auf die Beispiele der ZDAs verweisen.

**Comment by scheffold** [comment]
Hallo @asitplus-pteufl ,

* gibt es diesbezüglich Infos wann das abgestimmt wird bzw ob da bereits was in Klärung ist?
* Kann damit gerechnet werden dass eine Implementierung nachgeliefert wird?

Die Implementierung über PKCS #11 ist ja quasi der Standard zur Ansteuerung von Cryptographischer Hardware, darum versteh ich es ehrlich gesagt auch nicht wieso man sich hierbei bezüglich einer Aussage bedeckt hält, bzw @A-Trust  eine Implementierung an diesem Standard vorbei direkt auf die Hardware empfiehlt.

Gruß Frank

**Comment by asitplus-pteufl** [comment]
Zu den beiden Punkten: bitte Anfrage an das BMF stellen.

Für den zweiten teil (PCKS11) bitte die Hersteller direkt kontaktieren. Dies ist hier nicht der richtige Platz.
