### ISSUE TITLE
Verifikationstool Bug - Kodierung Umsatzzähler

### ISSUE THREAD

**Issue by pq-scheipel** [a-sit-plus/at-registrierkassen-mustercode#106]
Hallo,

Ich habe einen DEP-Export unserer Applikation durch das Verifikationstool laufen lassen, welches mir einen erfolgreichen Export bescheinigt hat. Anschließend habe ich einen Beleg im Export dekodiert, einen der einen Betrag-Satz-Normal von 7800 besitzt, jedoch den Umsatzzähler nur um 78,00 erhöht, erstellt. Bei neuerlicher Verifikation bekomme ich immer noch ein gültiges Ergebnis. Wird die Aufsummierung der Beträge nicht geprüft?
Beziehungsweise in welchem Format wird der Umsatzzähler selbst geprüft? Wird dem ersten Beleg der Kette ein Umsatzzähler von 0 (sprich 16 '0'-Bytes, AES-verschlüsselt) vorausgesetzt?

Mit freundlichen Grüßen,
Tobias Scheipel

**Comment by asitplus-pteufl** [comment]
für August ist 0.7 geplant, da wird das Format des Umsatzzählers erweitert geprüft (im Moment nur 8 byte möglich).

**Comment by zal1** [comment]
wann kommt die 0.7er Version?

lg
Alex

**Comment by asitplus-pteufl** [comment]
die ist schon online (siehe Releases).
