### ISSUE TITLE
Maschinenlesbarer Code

### ISSUE THREAD

**Issue by maxmaxAT** [a-sit-plus/at-registrierkassen-mustercode#108]
Guten Tag!
In Bezug auf §3 Abs. 15 RKSV, besteht die Möglichkeit den PDF417 Barcode zu verwenden?
Vielen Dank.

**Comment by asitplus-pteufl** [comment]
Nein, bitte in der Verordnung suchen, dort ist unter Abkürzungen 
Barcode: Standard „Code 128“, definiert in ISO/IEC 15417:2007 definiert
