### ISSUE TITLE
Verifizierung Signatur in DEP

### ISSUE THREAD

**Issue by TomBlue68** [a-sit-plus/at-registrierkassen-mustercode#109]
Ich habe denke ich alle Issues zu dem Thema durch und komme nicht auf die Lösung meines Problems, ich hoffe Sie können mir helfen.

Die Prüfung des DEP (nur ein Startbeleg enthalten) schlägt mit dem Fehler "DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen: Dekodierter Signaturwert: 0D ¯¸?ã˜Nã°ùEDX…@ýZ^Ž¬‡‹"Ìy¹Í CÈØa’m‹©?@úc°¦Ð™±´ïFs‹ú@9çÈ“§" fehl.

Die cryptographicMaterialContainer.json habe ich beigelegt. Dazu aber noch eine Anmerkung: Sobald ich "U:ATU44364102" durch die Zertifikatsseriennummer ersetzte, was meiner Ansicht nach eigentlich richtig sein sollte, fliegt das Prüftool mit einer Exception. Die UID Nummer kann ich auch durch falsche bzw. die von A-Trust für dieses Zertifikat wahrscheinlich verwendete ATU12345678 ersetzen, das ändert nichts am Ergebnis.

Ich verwende die Testversion der A-Trust Registrierkasse mobile in der JWS Variante zum signieren (/asignrkonline/v2/{Benutzername }/Sign/JWS). Den String den ich der Funktion übergebe habe ich auch in der JWS-Payload.txt beigelegt.

Kann mir da jemand weiterhelfen?
Vielen Dank im Voraus!

[cryptographicMaterialContainer.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/390201/cryptographicMaterialContainer.json.txt)
[dep-export.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/390202/dep-export.json.txt)
[JWS-Payload.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/390203/JWS-Payload.txt)

**Comment by asitplus-pteufl** [comment]
ganz schnelle antwort, im cryptographicMaterialContainer.json.txt muss die ID zweimal eingetragen werden (auch beim Feld ID). Bitte probieren.

**Comment by TomBlue68** [comment]
Habe da schon jede Variante mit UID und S/N Zertifikat probiert. Aber OK, schau‘ ich mir nochmals an.

 
Danke jedenfalls für die ganz schnelle Antwort J

**Comment by TomBlue68** [comment]
Hallo nochmals!

 
Sorry, jetzt hat sich’s aufgelöst. Scheinbar gab es in der 0.6 nochmals Änderungen. Habe jetzt das Testtool erneut herunter geladen und die Zert. S/N korrekt eingetragen, Prüfung erfolgreich!

 
Danke vielmals jedenfalls für die wirklich prompte Antwort!

 
Mit herzlichen Grüßen

Thomas Blühmann
