### ISSUE TITLE
Release 0.4: Kennzeichnung von Trainingsbuchungen

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#11]
Dies hier ist eine Spitzfindigkeit, ich erwähne es aber dennoch. In der FAQ steht:
*"Statt dem Verschlüsselten Umsatzzähler wird im maschinenlesbaren Code der BASE64-Wert der Zeichenkette "TRAIN" gespeichert (entspricht "VFJBSU4")."*

Im Fall eines 5-Byte-Umsatzzählers könnte sich die Zeichenkette "TRAIN" aber zufällig auch als *echter* Wert des verschlüsselten Umsatzzählers ergeben – was Verwechslungen ermöglichen würde.

Die Wahrscheinlichkeit, dass der Umsatzzähler centgenau auf dem entsprechenden Betrag landet, ist zugegebenermaßen extrem gering; dennoch könnte man dieses Risiko einfach beseitigen, indem man anstatt "TRAIN" eine Zeichenkette verwendet, deren Länge kürzer als die geforderte Mindestlänge des Umsatzzählers (5 Byte) ist – oder indem man z.B. die Zeichenkette "TRAIN" *unkodiert* (also ohne BASE64) in den maschinenlesbaren Code schreibt (wodurch sie ebenfalls kürzer als der kürzestmögliche BASE64-kodierte verschlüsselte Umsatzzähler wäre).

**Comment by pteufl** [comment]
ja, sollte man noch bedenken (da eben nicht eindeutig). wichtig aber noch abstimmung bezüglich generellem verhalten.
kürzere Kette wäre besser als unkodiert, da bei unkodiert dann wieder die OCR Kodierung beachtet werden müsste (dort ist umkodierung auf BASE32 gefordert, aufgrund der besseren lesbarkeit). Details werden hier genannt. danke.

**Comment by pteufl** [comment]
Es wird die Kennzeichnung "TRA" BASE-64 kodiert verwendet. Entspricht der Zeichenkette "VFJB". Wird in 0.5 behoben,
