### ISSUE TITLE
Belegnummer

### ISSUE THREAD

**Issue by ct-graz** [a-sit-plus/at-registrierkassen-mustercode#110]
Muss die verwendete Belegnummer die offizielle Belegnummer auf dem Kassabon sein oder kann das eine eigene fortlaufende Nummer sein, die gar nicht in Klarschrift auf dem Beleg steht? Das geht aus der Beschreibung nicht hervor.

**Comment by ErichFreitag** [comment]
Hallo! Die Antwort ergibt sich aus:

RKSV § 9 (2) Signaturdaten:
In die Signaturerstellung sind folgende Daten einzubeziehen:
[…]
2. fortlaufende Nummer des Barumsatzes

BAO § 132a (3) Beleginhalt:
Die Belege haben mindestens folgende Angaben zu enthalten:
[…]
2. eine fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung des Geschäftsvorfalles einmalig vergeben wird,

Fazit: die Belegnummer muss eindeutig im Sinne von einmalig sein und eine fortlaufende Nummernfolge sein sowie am Beleg aufgedruckt werden. Oft wird das daher eine eigene Nummer anstelle bisher verwendeter Bonnummern o.ä. sein müssen.

**Comment by lebail** [comment]
Ich hänge mich hier auch an.

Hintergrund ist, dass mein System _Rechnungen_ erstellt - sowohl Barrechnungen (mit integriertem RKSV-Zahlungsbeleg) als auch (nicht signierte) Zielrechnungen. Die Rechnungen sind unabhängig von der Zahlungsart durchnummeriert.

Wenn ich nun (im maschinenlesbaren Code und im DEP) die _Rechnungsnummer_ verwende, dann ist diese nicht fortlaufend (weil ja Zielrechnungen dazwischen sein können, die nicht im DEP erfasst werden). Daher frage ich mich, ob ich diese Nummer dennoch verwenden darf/soll, oder ob es zulässig oder sogar nötig ist, für die zu signierenden (Bar-)Rechnungen einen eigenen Zähler zu benutzen.

Der Erlass-Entwurf ist hier leider widersprüchlich:

| 3.3.4. Signatur- bzw. Siegelerstellung
| …
| Bei den zu signierenden Daten handelt es sich um
| bestimmte Belegdaten gemäß § 132a Abs. 3 BAO (fortlaufende Nummer des
| _Barumsatzes_, Datum der Belegausstellung), …

| 4.6.2. Fortlaufende Nummer
|
| Die in § 132 Abs. 3 Z 2 BAO geforderte Angabe („eine fortlaufende
| Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung
| des _Geschäftsvorfalles_ einmalig vergeben wird“) entspricht wörtlich
| dem Rechnungserfordernis des § 11 Abs. 1 Z 3 lit h UStG 1994 (siehe
| Abschnitt 11.1.6.6.der UStR 2000).

Einmal heißt es "fortlaufende Nummer des _Barumsatzes_" und einmal "Nummer … zur Identifizierung des _Geschäftsfalles_".

Ich habe diesen Widerspruch bereits als Kommentar zum letzten Erlass-Entwurf an UBIT gemeldet.

**Comment by ErichFreitag** [comment]
Das ist halt dann auch eine Entscheidung der Umsetzung. Sie dürfen ja beispielsweise auch Zielrechnungen signieren und wenn sie dann die Rechnungsnummer als Belegnummer nehmen wäre diese wieder fortlaufend. Wenn nicht wird es wohl ein eigener Nummernkreis sein müssen.

**Comment by lebail** [comment]
Danke. 

Wenn man auch die Zielrechnungen signiert und mitnummeriert, dann stimmt es erst wieder nicht. Denn die RKSV sagt ja "fortlaufende Nummer des Barumsatzes", die Zielrechnungen sind aber keine Barumsätze, somit wäre die Nummer bezüglich der Barumsätze erst wieder nicht fortlaufend. D.h. das Signieren der Zielrechnungen ist zwar erlaubt, aber eigentlich nicht möglich, da man für die Nicht-Barumsätze keine konformen Belegnummern vergeben kann.

Es stellt sich mir aber immer noch die Frage, ob es sich bei den beiden in RKSV und BAO genannten Erfordernissen …

- fortlaufende Nummer des Barumsatzes
- fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung des Geschäftsvorfalles einmalig vergeben wird

… zwingend um ein- und dieselbe Nummer handeln muss. Denn eigentlich steht das nirgends, und mit einer zusätzlichen, von der Rechnungsnummer unabhängigen, Durchnummerierung der Barumsätze (die dann als RKSV-konforme Belegnummer im maschinenlesbaren Code und im DEP verwendet wird), ließe sich die Sache gut lösen.

Vor allem könnte man damit auch das beliebte Thema "nachträgliche Barzahlung einer Zielrechnung" recht elegant behandeln: Man erstellt ein (als solches gekennzeichnetes) Rechnungsduplikat mit integriertem Barzahlungsbeleg (was laut Erlass-Entwurf zulässig sein müsste, siehe Punkte 2.4.11 und 4.6.7) und kann dabei die ursprüngliche Rechnungsnummer beibehalten.

**Comment by ct-graz** [comment]
Bei uns werden die normalen Belegnummern nur für die Kassabelege fortlaufend, aber eventuell über mehrere Kassen. Dazu gibt es eine Bonnummer je Kassa. Eine neue Nummer bedeutet ein 3. Feld, das gespeichert und angedruckt werden muss. Bei Fiskaltrust werden je Kassa eigene fortlaufende Nummern vergeben, die mit der Belegnummer nichts zu tun haben. Dass das DEP fortlaufend nummeriert ist, ist klar, aber die eigentliche Belegnummer, die auch in die Buchhaltung geht, sollte doch wichtiger sein.

**Comment by ErichFreitag** [comment]
@ct-graz: achten sie darauf, dass das Tripel Kassen-ID - Belegnummer - AES-Schlüssel immer eindeutig ist. "Die Belegnummer eines Belegs ist innerhalb eines Unternehmens für Kassen-ID und AES-Schlüssel eindeutig".

@lebail: einverstanden, warten wir, wie das beantwortet wird.

Um nochmals genau zu sein, das zusammenzufassen und zu präzisieren:

§ 132a Abs. 3 BAO: ... 2. eine fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung des Geschäftsvorfalles einmalig vergeben wird

RKSV § 9 Abs. 2: In die Signaturerstellung sind folgende Daten einzubeziehen: ... 2. fortlaufende Nummer des Barumsatzes.

RKSV § 10 Abs. 2: Der maschinenlesbare Code hat folgende Daten zu enthalten: ... 2. fortlaufende Nummer des Barumsatzes.

Am Beleg nach RKSV § 11 sind die Belegdaten nach § 132a Abs. 3 BAO plus zusätzlichen Daten auszuweisen (Kassen-ID, Datum/Uhrzeit, Beträge, maschinenlesbarer Code).

Im Datenerfassungsprotokoll sind nach RKSV § 7 Abs. 1 zumindest die Belegdaten gemäß § 132a Abs. 3 BAO festzuhalten.

Fazit für mich:

- die RKSV-Belegnummer ist eine fortlaufende Nummer des Barumsatzes, der in der Signatur und damit im maschinenlesbaen Code (und in Folge im DEP) aufscheint

- das muss zwangsläufig auch pro Kasse laufend sein, da ja eine Kasse nach RKSV auch durch deren eigenes DEP definiert ist

- am Beleg ist eine fortlaufende Nummer zur Identifizierung des Geschäftsvorfalles anzugeben

- Das können, müssen aber nicht die selben Nummern sein. Aufgedruckt muss nur jene nach BAO werden

- durch die (eventuell gesonderte) fortlaufende Nummer des Barumsatzes nach RKSV ist die Belegverkettung nachvollziehbar

- durch die Nummer des Barumsatzes im maschinenlesbaren Code -> DEP und durch die BAO-Belegdaten im DEP ist auch die Verküpfung zwischen den beiden Nummern gegeben.

Was meint ihr dazu?

**Comment by ct-graz** [comment]
Da unsere Belegnummer für die Buchhaltung ist, ist sie für sich allein schon eindeutig - über alle Kassaen.

Das Problem ist hier, dass nicht klar ist, ob RKSV § 9 die laufende Nummer aus BAO gemeint ist oder nicht. Für mich ist diese Nummer nicht zwangsläufig je Kassa fortlaufend.

Müsste die in der SIgnatur verwendete Nummer nicht auch am Beleg stehen, könnte ich zwei gleichwertige Belege hintereinander mit der selben Signatur ausdrucken, ohne dass es auffällt.

Damit die Prüfung eines Belegs für sich allein gar nicht möglich.

**Comment by ErichFreitag** [comment]
@lebail und @ct-graz: ich kann den aktuellen widerspruch zwischen 3.3.4 und 4.6.2 des Erlasses derzeit nicht auflösen oder schlüssig für das eine oder andere argumentieren, wir müssen wohl auf eine Präzisierung warten und das dann nochmals abschließend diskutieren.

Meinerseits danke für die Diskussion, ich bin dadurch betreff Belegnummern ein Stück klüger (oder besser gesagt sensibler) geworden.

**Comment by ErichFreitag** [comment]
So, @lebail und @ct-graz - jetzt ist er da, der Erlass. Und er macht uns bezüglich 3.3.4 (Belegdaten gemäß § 132a Abs. 3 BAO - fortlaufende Nummer des Barumsatzes) und 4.6.2 (Die in § 132 Abs. 3 Z 2 BAO geforderte Angabe („eine fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung des Geschäftsvorfalles einmalig vergeben wird“)) auch nicht klüger weil unverändert.

Wenn ich mir im Zusammenhang damit 3.6.1 (...laufende Nummern des ersten und letzten händisch
erstellten Belegs... sowie ...aus dem Beleg muss der Beginn und das Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit (zB: durch Angabe der jeweiligen laufenden Nummer) hervorgehen...) ansehe und den Gedanken der RKSV bezüglich Verkettung mit einbeziehe, dann wäre mir mit einer eigenen laufenden Belegnummer pro Kasse und pro Barumsatz und geschäftsfall-unabhängig wohler.

Beispielsweise sprechen auch 4.5.1 und 6.7.1.1 von einer "Durchnummerierung der ausgestellten Belege".

@ct-graz: siehe auch 3.10.1 "Die Belege der einzelnen Registrierkassen eines Registrierkassenverbundes müssen mit Belegnummern getrennter Nummernkreise erstellt werden" (ist hier zwar im Zusammenhang mit geschlossenen Gesamtsystemen angeführt, gilt aber denke ich sinngemäß) sowie 4.6 "Ab dem 1. April 2017 müssen die Belegnummern aus sicherheitstechnischen Gründen pro
Kassenidentifikationsnummer und AES-Schlüssel eindeutig sein".

Bezüglich "Müsste die in der Signatur verwendete Nummer nicht auch am Beleg stehen, könnte ich zwei gleichwertige Belege hintereinander mit der selben Signatur ausdrucken, ohne dass es auffällt. Damit ist die Prüfung eines Belegs für sich allein gar nicht möglich.": ja schon, nur im maschinenlesbaren Code ist die (RKSV-)Belegnummer ja enthalten. Und beim Export des DEP fällt es spätestens auf.

Wenn Geschäftsfälle vorkommen, die nicht signiert werden, aber gemäß BAO eine "laufende Nummer zur Identifizierung des Geschäftsfalls" haben, dann entspricht das nicht der RKSV "fortlaufende Nummer des Barumsatzes". Auf den Beleg gehört die Nummer laut BAO, in den maschinenlesbaren Code und in die Signatur jene nach RKSV. Ob das sie selbe ist oder nicht wird je nach Geschäftsfällen vom Unternehmen und von der Implementierung abhängen.

Bis ich eines besseren belehrt werde bleibe ich daher bei meiner obigen Meinung der Präzisierung.

Viele Grüße Erich Freitag

**Comment by ErichFreitag** [comment]
P.S. falls es in der Umsetzung noch etwas hilft hier ein Teil des Verweises aus 4.6.2 auf UStR 2000 11.11.6.6:

Im Rahmen der fortlaufenden Nummer sind auch Buchstaben zulässig, sofern das Erfordernis der fortlaufenden Bezeichnung gewährleistet ist. 

In die fortlaufende Nummerierung können auch die Kleinbetragsrechnungen einbezogen werden.

Der Zeitpunkt des Beginnes der laufenden Nummer kann frei gewählt werden, muss jedoch systematisch sein (auch täglicher Nummernbeginn ist zulässig).

Es sind verschiedene Rechnungskreise zulässig (zB Filialen, Betriebsstätten, Bestandobjekte, Registrierkassen), die Zuordnung muss jedoch eindeutig sein. Es können auch verschiedene Vertriebssysteme, Warengruppen oder Leistungsprozesse (zB Safe oder Depotleistungen bei Kreditinstituten) als eigene Rechnungskreise angesehen werden.
