### ISSUE TITLE
Signatur kryptographisch: FEHLERHAFT

### ISSUE THREAD

**Issue by aunterlu** [a-sit-plus/at-registrierkassen-mustercode#111]
Hallo,
bei der Überprüfung der Signatur tritt bei mir folgenden Fehler:
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber
 nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen:
»Sd?È1}Æ?Ü§►àþ?åI/Ü☻#p☻! ?¾¢    Ñ¾ P♂Ô9ND2?òÆ▲Ë!J©©?ç]ƒxÓ¶?

Ich hab mir die alten Issues zu diesem Thema durchgelesen, aber keine Lösung dafür gefunden. Der cryptographicMaterialContainer sollte ok sein. Alle anderen Überprüfungen sind auch ok. Die Überprüfung der Daten mit der Java-Funktion Signature.verify() liefert auch ok zurück. Das Problem tritt mit A-Trust und GlobalTrust Zertifikaten auf. 

Ich hab den Export des Startbelegs mit GlobalTrust-Zertifikat als Beispiel angehängt:
[dep.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/420188/dep.zip)

**Comment by asitplus-pteufl** [comment]
Können Sie bitte die Infos bezüglich Signatur-Kodierung aus https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/40 lesen und überprüfen ob das bei Ihnen korrekt ist?

**Comment by aunterlu** [comment]
Ich hab jetzt den Fehler gefunden. Das Problem war, dass ich das Ergebniss der SmartCard Signatur wie im Beispielcode von GlobalTrust DER encoded habe und dieses Ergebniss dann Base64URLSafe encoded als Signaturteil in jwsCompact abgelegt habe.

**Comment by asitplus-pteufl** [comment]
DER Encoding wird im JWS Standard nicht verwendet, bei der Karte kommt das auch schon so raus, in Java ist halt alles DER.
