### ISSUE TITLE
Sinn der Signatur

### ISSUE THREAD

**Issue by rjungbeck** [a-sit-plus/at-registrierkassen-mustercode#112]
Welchen Sinn hat eigentlich die mühsam erzeugte und gedruckte Signatur? 

Sie kann nur zusammen mit den Zertifikaten geprüft werden (sonst kann sie nicht von Zufallszahlen unterschieden werden) und diese sind zwingend nur im DEP Export enthalten (die Anmeldung der Signatureinheit kann auch nur mit der CertId erfolgen).

Wenn man aber ohnehin den DEP Export hat, kann man einfach (und ohne Signatur) prüfen, ob der fragliche Beleg auch drin ist.

Auch mit dem geheimen Schlüssel des Umsatzzählers und der Verkettung kann geprüft werden, ob der Beleg vom richtigen Aussteller stammt.

Wenn jemand betrügt und einen Beleg nicht verbucht, wird er ihn auch nicht signieren, sondern einfach Zufallszahlen in das Feld stellen. Also ist sie auch kein Beweis für den Betrug durch den Aussteller.

Wieso also der ganze Aufwand?
Oder mach ich da einen Denkfehler?

**Comment by asitplus-pteufl** [comment]
Am Beleg stehen alle Informationen für den Bezug des Zertifikats und damit der Prüfung der Signatur zur Verfügung.

**Comment by rjungbeck** [comment]
Woher?
Veröffentlichen die Zertifikateanbieter die Zertifikate (und sei es nur gegenüber der Finanz)?
Die Finanz dürfte sie jedenfalls  nach §18 der RKSV nicht speichern (sonst würde es keinen Sinn machen dort deren Seriennummer explizit zu nennen)

**Comment by ErichFreitag** [comment]
Die Zertifikate sind über die öffentlich zugänglichen Verzeichnisdienste einsichtig, damit kann eine Signatur überprüft werden. Siehe beispielsweise http://wiki.a-trust.at/wiki/Default.aspx?site=Verzeichnisdienst

**Comment by rjungbeck** [comment]
Danke für die Information über den Verzeichnisdienst. Hilft mir sehr, da der ja öffentlich ist, also auch beim DEP Export genutzt werden kann (und wir daher nicht zu jedem Beleg die Zertifikate speichern müssen).

**Comment by asitplus-pteufl** [comment]
möchte nur ergänzen dass ja auch im Detailfragendokument das exportieren der Zertifikate im DEP als optional definiert ist.
