### ISSUE TITLE
Gültigkeit der kryptographischen Kette nicht gegeben

### ISSUE THREAD

**Issue by fscherr** [a-sit-plus/at-registrierkassen-mustercode#113]
„Sehr geehrter Herr Teufl,

das Verifikationstool liefert mir immer ab dem 2. Beleg den Fehler „Gültigkeit der kryptographischen Kette nicht gegeben“. 
Nachdem die Überprüfung beim 1. Beleg erfolgreich verläuft, nehme ich an, dass die Kodierung des Verkettungswerts in meiner Funktion grundsätzlich funktioniert sollte. Für den Verkettungswert des nachfolgenden Beleges verwende ich die kompakte JWS-Repräsentation des vorigen Belegs. Im von mir angegeben Beispiel wird der Verkettungswert „zZuJZuy6sZw=“ vom 1. Beleg ermittelt und in den Payload des 2. Belegs verspeichert. 
Übersehe ich hier etwas? Könnten Sie sich das bitte ansehen? 

java -jar regkassen-verification-depformat-0.6.jar –I DEPExport.json –c cryptographicMaterialContainer.json

Anbei die Eingabe-Test-Files”

[TestFiles.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/436918/TestFiles.zip)

**Comment by asitplus-pteufl** [comment]
Wir können leider nicht auf Fehler getrennt eingehen. Wenn der Verkettungswert im Tool als nicht korrekt angegeben wird, dann wird dies so sein. Alle nötigen Informationen zur korrekten Berechnung finden Sie in V1.1. des Detaildokuments, und in der BSP-Implementierung.
