### ISSUE TITLE
Webservice

### ISSUE THREAD

**Issue by G-Pilat** [a-sit-plus/at-registrierkassen-mustercode#114]
Wann kann der Webservice für die Registrierkassen verwendet werden?

**Comment by areiter** [comment]
Ich glaube nicht dass sie etwas davon abhält dieses sofort zu verwenden.
Ohne sinnvolle Kommandos hinzuschicken bekommt man zumindest eine Antwort.

**Comment by asitplus-pteufl** [comment]
Ich kann hier leider keine Antwort geben (aus Sicht A-SIT Plus) und sie daher auf die Informationsquellen des BMF verweisen.
