### ISSUE TITLE
Testzugang FinanzOnline

### ISSUE THREAD

**Issue by rjungbeck** [a-sit-plus/at-registrierkassen-mustercode#115]
Nachdem der Web Service jetzt scheinbar aktiv ist (WSDL wird zurückgegeben), stellt sich für uns jetzt erneut die Frage, von wem wir als deutsches Softwarehaus die für FinanzOnline nötigen Anmeldeinformationen zum Test bekommen.

Ein Anruf der FinanzOnline Hotline (schon vor einigen Wochen), hab ich mich stark an den Buchbinder Wanninger erinnert, aber zu keinen Anmeldedaten geführt.

**Comment by Parmenidoxes** [comment]
Dafür gibt's zwei Möglichkeiten:
Selber einen FON Zugang beantragen: Das [zuständige Finanzamt ist Graz-Stadt](https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/umsatzsteuer/ust-kontakt-gs.html).
Nachteil: Die Zugangsdaten werden lt. Auskunft BMF nicht ins "Ausland" versandt, da der korrekte Empfänger da nicht verifizierbar sei. Dh. persönliche Abholung bzw. Stellvertretung notwendig (Details siehe Link).

Variante 2: Steuerberater machen lassen. Falls Sie keinen österreichischen haben, dürfte Ihr deutscher mit Sicherheit einen Partner in AT haben, der der das rechtsgültig abwicklen kann.

Abgesehen von der Abholerei sollten Sie aber keinerlei Probleme haben, hat es uns gegenüber geheißen.

**Comment by asu90** [comment]
#99 behandelt die gleiche Frage und dort ist die offizielle Antwort vom BMF, dass ab August Testzugänge zur Verfügung gestellt werden. 

Auf der dort angegebenen Seite https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/informationen-fuer-softwarehersteller.html kann ich allerdings keine Testzugänge finden.

**Comment by rjungbeck** [comment]
Grundsätzlich wollen wir ja eigentlich keine rechtsverbindlichen Transaktionen ausführen sondern genau das Gegenteil tun: Testen und dabei fiktive Daten (möglicherweise auch noch fehlerhaft) melden

Auch aus Compliancegründen halte ich es für problematisch, Tests mit produktiven Zugängen durchzuführen: Bei uns sind zumindest 3 verschiedene Firmen (davon 2 in Deutschland) an der Implementierung und den Tests beteiligt.  Sollen die jetzt alle ihre Firmen in Österreich bei der Finanz registrieren oder ihre Zugangsdaten teilen?

Weitere Frage: Wird bei den RKSV Funktionen (Anlegen von Signatureinrichtungen) geprüft, ob die auf das entsprechende Unternehmen ausgestellt wurden?

**Comment by ErichFreitag** [comment]
Bezüglich WKO und BMF kann zumindest ich hier nichts beitragen.

Zur letzten Frage von @rjungbeck: siehe RKSV § 16 (2): Erst nach Prüfung, ob für jede gemeldete Signaturerstellungseinheit unter der angegebenen Seriennummer des Signaturzertifikates und dem gültigen Ordnungsbegriff des Unternehmers der ZDA in der öffentlichen Trust-List und das Signaturzertifikat im Verzeichnis des ZDA vorhanden sind, werden diese Daten an die Datenbank über Sicherheitseinrichtungen in Registrierkassen (§ 18) übergeben.

**Comment by SchmidLukas** [comment]
Hallo,

Wir sind ein Niederländisches Softwarehaus und würden für den FinanzOnline Webservice ebenfalls einen Testzugang benötigen. Wir können aber selbst heute, 5 Jahre später, keine Informationen finden auf entsprechender Seite. Gibt es hier eventuell neue Informationen?

Beste Grüße

**Comment by TheBlackyy** [comment]
Hallo, 

Mir ergeht es leider genauso, man findet leider keinen Testzugang. Ich habe bereits die 2. E-Mail an das FinanzOnline-Team gesendet, leider ohne Erfolg. 

Bis heute hat sich noch niemand gemeldet, ich versuche es weiter.... Falls jemand diesbezüglich Informationen hätte, wäre ich sehr dankbar...

Mit freundlichen Grüßen

**Comment by rjungbeck** [comment]
Der Testzugang für FinanzOnline ist identisch mit dem Produktivzugang für FinanzOnline.

Die Requests haben eine Markierung Produktion/Test.

Ich hab also meinen normalen  FinanzOnline Zugang genutzt (und einen Subuser für die Tests angelegt).

Es gibt auch  irgendein Finanzamt (ich glaub in Linz) welches FinanzOnline Zugänge an ausländische Firmen vergibt. Hab ich  aber nicht gebraucht.
