### ISSUE TITLE
Fehlbuchungen aufgrund falschem Kassendatum

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#116]
Trotz aller erdenklichen Prüfungen und Hinweisen passiert es, dass eine Kasse kurzzeitig auf einem falschen Datum läuft und Belege erstellt. Bis das bemerkt wird, können bereits einige Buchungen an einem falschen Datum erfolgen. Verkettungsmäßig und anhand der Belegnummer im DEP sind sie "geschlossen". Exportiert man nun das DEP rein über einen Zeitraum, fallen die falschen Belege raus und es entstehen Lücken in der Kette.
Welche Maßnahmen sind diesbezüglich angedacht?
Eine Idee wäre, dass man die fehlenden Belege anhand der Belegreihenfolge erkennt und mit dem falschen datum in den DEP-Export einbezieht.

**Comment by asitplus-pteufl** [comment]
Schnell als Info: Aus RKSV-DEP Sicht ist es auf jeden Fall falsch wenn die Verkettung nicht korrekt abgebildet ist. D.h. das Nicht-Exportieren von Belegen, die zur Verkettung gehören ist auf jeden Fall nicht der korrekte Weg.

**Comment by ErichFreitag** [comment]
@michaelkorb - siehe RKSV Detailspezifikation Punkt 3 Export DEP:

Belege-kompakt: ... Die Reihenfolge der Belege stimmt mit der Ablagereihenfolge im DEP überein.

**Comment by asitplus-pteufl** [comment]
Ich schließe diesen Beitrag, auch nach Rückfrage beim BMF ist die Verkettung der Belege für die Reihenfolge im DEP relevant (also im Sinne meiner Antwort die auch oben technisch schon beantwortet wurde).
