### ISSUE TITLE
TestCases: typeOfReceipt fehlt bei Beleg 66

### ISSUE THREAD

**Issue by ErGo1180** [a-sit-plus/at-registrierkassen-mustercode#117]
Ist es Absicht, das beim Testbeleg 66 der typeOfReceipt fehlt und dieser dann beim Verarbeiten durch das JAVA-Testprogramm einfach unter den Tisch fällt? 

Ausschnitt aus der TESTSUITE_TEST_SZENARIO_1.json
```
    {
      "signatureDeviceDamaged": false,
      "receiptIdentifier": "CASHBOX-DEMO-1-Receipt-ID-66",
      "dateToUse": "2016-05-17T22:03:13",
      "usedSignatureDevice": 1,
      "simplifiedReceipt": {
        "taxSetNormal": 191.99,
        "taxSetErmaessigt1": 178.56,
        "taxSetErmaessigt2": -42.24,
        "taxSetNull": -27.58,
        "taxSetBesonders": 51.84
      }
    },
```

Ist es kein Problem, dass es dann eigentlich keine fortlaufende Nummerierung gibt? (in der Export-Datei qr-code-rep.json folgt auf ID65 gleich ID67)
```
  "_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-65_2016-08-16T10:38:09_-29,68_25,29_178,40_140,90_174,92_U1RP_8a9308520cf9b84c_Xbt8NGemu04=_b0AvRW61qKqDj9ukzHaVJydZubJ+Yru6P9YwUE3Bx4qBujZvq6bYTV7DvNOgiERAF4X8hgCD1vt82wUoPpaaig==",
  "_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-67_2016-08-16T10:38:09_116,09_-22,93_44,26_8,59_44,94_VFJB_b4412b8e87e7c06b_WKZUANE9/wc=_kUnBxlP994uaV8ebliWE6gJInM0Bnq6WQX/Iz2RNHhB5FtGL+fvNA5+HRv0H8kcw59rBx+nCoXPHN60Al8nWcA==",
```

**Comment by asitplus-pteufl** [comment]
Vielen Dank für den Hinweis! Dies wurde heute korrigiert und ist noch für Version 0.7 die heute veröffentlicht wurde integriert worden. Auch die Prüftools wurden aktualisiert und liefern nun die gleichen Informationen wie sie auch im FinanzOnline zur Verfügung stehen.
