### ISSUE TITLE
Typo in Detailfragen 1.1

### ISSUE THREAD

**Issue by marcsst** [a-sit-plus/at-registrierkassen-mustercode#118]
Seite 28:

> Der Verkettungswert für den Startbeleg wird bei einer Kasse mit der Kassen-ID A123**5**7 wie folgt
> berechnet:
> 
> - Eingabewert für Hashalgorithmus: Die Kassen-ID – in diesem Fall A123**4**7 ist im UTF8-
> Format gespeichert.

**Comment by asitplus-pteufl** [comment]
Danke für den Hinweis, wird in 1.2 berücksichtigt werden!
