### ISSUE TITLE
weitere fehlende typeOfReceipts bei Testcases

### ISSUE THREAD

**Issue by ErGo1180** [a-sit-plus/at-registrierkassen-mustercode#119]
Danke für das Ergänzen des fehlenden typeOfReceipt bei Beleg 66 in den Testfällen von Testcase1.

Allerdings fehlt der Typ auch bei den folgenden Testcases der Version 0.7:

TESTSUITE_TEST_SZENARIO_3.json:
CASHBOX-DEMO-1-Receipt-ID-228
CASHBOX-DEMO-1-Receipt-ID-234

TESTSUITE_TEST_SZENARIO_4.json:
CASHBOX-DEMO-1-Receipt-ID-293

TESTSUITE_TEST_SZENARIO_6.json
CASHBOX-DEMO-1-Receipt-ID-441

**Comment by asitplus-pteufl** [comment]
Vielen Dank für den weiteren Hinweis. Ist jetzt in 0.7.1. korrigiert (wurde am 07.09. hochgeladen).
