### ISSUE TITLE
Warum eigenes System?

### ISSUE THREAD

**Issue by michaelmair** [a-sit-plus/at-registrierkassen-mustercode#12]
Zuerstmal sorry, dass ich das hier her schreibe, weil es eigentlich eine Frage ist als ein konkretes Issue und zudem weiß ich nicht ob die Frage hier an die richtigen Personen gerichtet ist.

**ABER trotzdem**:
Warum wird nicht INSIKA (das deutsche Äquivalent: http://www.insika.de/de/faq) verwendet?
Es gibt nämlich eine gegenüberstellung der aktuellen österreichischen RKSV und dem INSIKA System: http://www.insika.de/images/stories/INSIKA/Analyse_RKSV_oesterreich.pdf

**Comment by argetherapie** [comment]
Weil das eine politische Entscheidung ist/war...
.. Deine Frage findet hier vielleicht eher Antwort:
https://www.xing.com/communities/groups/registrierkassenpflicht-oesterreich-323e-1078578

**Comment by michaelmair** [comment]
ah, danke für den Link!

**Comment by pteufl** [comment]
Dieses GitHub Projekt wird nur zur Klärung der technischen Aspekte genutzt. Anfragen die in diese oder ähnliche Richtungen gehen bitte an das BMF weiterleiten.
Ich bitte auch zu berücksichtigen dass die Antworten der anderen Teilnehmer wie z.B. argetherapie nicht korrekt sein müssen (und in diesem Fall auch nicht sind).
