### ISSUE TITLE
Umsatzzähler Fehlermeldung Prüftool

### ISSUE THREAD

**Issue by zal1** [a-sit-plus/at-registrierkassen-mustercode#120]
Hallo,

wir bekommen mit dem Prüftool(regkassen-verification-depformat-0.7.jar) für das DEP folgenden Fehler, wir verwenden 5 Byte für den Umsatzzähler:
```
        "verificationId" : "FORMAT_ENCRYPTED_TURN_OVER_VALUE_BASE64",
        "version" : 1,
        "verificationName" : "Formatprüfung: verschlüsselter Umsatzzähler (BASE64-Kodierung)",
        "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden unterschiedliche Prüfungen im Zusammenhang mit der BASE64-Kodierung (gültige Zeichen, Länge) des Umsatzzählers durchgeführt.",
        "verificationState" : "FAIL",
        "verificationTimestamp" : "2016-09-07T10:09:39.854+02:00",
        "verificationResultList" : [ {
          "verificationId" : "FORMAT_BASE64_DECODE_ENCODE",
          "version" : 1,
          "verificationName" : "Formatprüfung: BASE64 Dekodierung/Kodierung",
          "verificationTextualDescription" : "In diesem Modul wird überprüft ob die Dekodierung eines BASE64-Werts und die anschließende Kodierung wieder den Ausgangswert ergibt.",
          "verificationState" : "FAIL",
          "verificationTimestamp" : "2016-09-07T10:09:39.854+02:00",
          "verificationResultList" : [ {
            "verificationId" : "FORMAT_BASE64_CHARS",
            "version" : 1,
            "verificationName" : "Formatprüfung: Gültige BASE64-Zeichen",
            "verificationTextualDescription" : "Es wird in diesem Modul überprüft ob die gegebene Zeichenkette nur Zeichen beinhaltet die für die BASE64-Kodierung verwendet werden dürfen.",
            "verificationState" : "FAIL",
            "verificationTimestamp" : "2016-09-07T10:09:39.855+02:00"
```

Der Beleg sieht so aus, JWS-Signatur eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8xNDMwMzg2LVMwMV9SQ1AtMTQzMDM4Ni0yMDE2LTAwMDM3MzE3XzIwMTYtMDktMDFUMDk6MTY6MjBfMCwwMF8yLDU5XzAsMDBfMCwwMF8wLDAwX20vWFhNNGtfNEJDQTQzRjhfbHZ1MFlqR29FVHc9.OEksyxzd6tYRhJ3ZCVGUKGV3KznR07ziMEuWJURbYgVbO1tcjdmzNb/Eqt82Ep2Ir1WNX8idji+uAm7jKKMxrw

maschinenlesbarer Code: _R1-AT1_1430386-S01_RCP-1430386-2016-00037317_2016-09-01T09:16:20_0,00_2,59_0,00_0,00_0,00_m/XXM4k_4BCA43F8_lvu0YjGoETw=_OEksyxzd6tYRhJ3ZCVGUKGV3KznR07ziMEuWJURbYgVbO1tcjdmzNb/Eqt82Ep2Ir1WNX8idji+uAm7jKKMxrw==

lg
Alex

**Comment by asitplus-pteufl** [comment]
Das Prüfmodul sagt aus "Es wird in diesem Modul überprüft ob die gegebene Zeichenkette nur Zeichen beinhaltet die für die BASE64-Kodierung verwendet werden dürfen.".
Damit ergibt sich dass die BASE64-Kodierung des Umsatzzählers nicht korrekt ist. Bitte überprüfen Sie die verwendete BASE64-Bibliothek.

**Comment by zal1** [comment]
der Umsatzzähler hat hier die Zeichen: `m/XXM4k`
welches Zeichen ist hier nicht base64-konform oder muss hier base64url kodiert werden?

**Comment by csokay** [comment]
ich glaube das "/" kommt nicht in base64url vor.
siehe auch hier: https://tools.ietf.org/html/rfc4648#page-7

**Comment by asitplus-pteufl** [comment]
nein, BASE64-URL ist hier falsch (bitte die Spezifikation beachten). 
Es kann sein dass das Padding Zeichen = fehlt. Die Reg-Expression für korrekte BASE64 Kodierung ist  ^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$
