### ISSUE TITLE
Fehlermeldung verkürzter Umsatzzähler (8 Bytes)

### ISSUE THREAD

**Issue by wolfgangstiegler** [a-sit-plus/at-registrierkassen-mustercode#121]
Ich erhalte folgende Fehlermeldung wenn ich das DEP mit der Version 0.7.1 überprüfen lasse:

"verificationId" : "DEP_TURNOVER_COMPARE",
      "version" : 1,
      "verificationState" : "FAIL",
      "verificationResultDetailedMessage" : "Der berechnete Umsatzzähler entspricht nicht dem verschlüsselten Umsatzzähler (siehe Parameter DECRYPTED_TURNOVER_VALUE). Bitte überprüfen Sie die Kodierung des Umsatzzählers (BIG-Endian, two's complement), oder den verwendeten AES-Schlüssel.",
      "input" : {
        "DECRYPTED_TURNOVER_VALUE" : "0",
        "TURNOVER_SUM" : "0",
        "SUM_TAX_SET_ERMAESSIGT2" : "0,00",
        "SUM_TAX_SET_ERMAESSIGT1" : "0,00",
        "SUM_TAX_SET_NORMAL" : "100,00",
        "TYPE_RECEIPT" : "STANDARD_BELEG",
        "SUM_TAX_SET_NULL" : "0,00",
        "SUM_TAX_SET_BESONDERS" : "0,00"
      },
Aus der Fehlermeldung schließe ich dass das Entschlüsseln des Umsatzzählers 0 ergibt,obwohl dieser nach dem Beleg 100 sein müsste.

Wenn ich das gesamte ByteArray (16 Bytes) in das DEP übernehme, läuft die Überprüfung fehlerfrei durch. Daher muss es wohl an der Verkürzung des Umsatzzählers liegen.

Meine Vorgangsweise ist dabei folgende. Ich nehme das komplette ByteArray, extrahiere daraus die ersten 8 Bytes und kopiere diese in ein neues ByteArray. Das verwende ich dann weiter.

Ich nehme an diese Vorgangsweise ist nicht korrekt, oder ?

lg
Wolfgang

**Comment by asitplus-pteufl** [comment]
das hängt jetzt von Ihrer Implementierung und der Sprache ab die sie verwenden. Wichtig ist ob Ihre Sprache BIG/Litte Endian ist (laut Spez muss Big Endian kodiert werden). 
Schnell gedacht: Wenn sie von einem 16-Byte Array in Big Endian Format ausgehen, dann sollte das MSB an der niedrigsten Adresse sein (also Index 0). Das LSB müsste an der höchsten Adresse sein (also Index 15). Wenn Sie jetzt die ersten 8 Bytes extrahieren (also 0-7) dann nehmen Sie eigentlich nur die Nullen der höherwertigen Elemente (bei 100 ist ja maximal das erste Byte belegt, das dann an Stelle 15 steht).
Quickfix: Was ist wenn Sie einfach 8-15 extrahieren, stimmt dann das Ergebnis? (sie können dann auch einfach 11-15 extrahieren um einen 5-byte Zähler zu haben).

Bitte auch das 2er Komplement betrachten: Wenn Sie eine negative Zahl haben müssen Sie sicherstellen, dass Ihre Sprache die Zahl in 2er Komplement darstellt. Das Abschneiden ist dann aber gleich. Einfach die Bytes nehmen die Sie benötigen (die Prüfung berücksichtigt das). Negative Umsatzzähler sind zwar selten, kommen aber in Spezialfällen vor: z.B. Storno nach Ausstellen von Startbeleg.

Sonst bitte im Muster-Code im Detail anschauen. Mit 0.7 sind auch beliebige Umsatzzähler implementiert.

**Comment by wolfgangstiegler** [comment]
ich habe ihren Lösungsvorschlag probiert. Wenn ich die letzten Bytes (egal ob 5 oder 8) aus meinem ByteArray extrahiere (das ByteArray ist im BigEndianFormat kodiert), dann scheitert bereits die Prüfung des Startbelegs, da der Umsatzzähler > 0 ist.

Ich hab mir Ihre Implementierung angesehen. Ich bin zwar kein JAVA Profi, jedoch werden dort so weit ich das beurteilen kann auch die ersten Bytes des Arrays extrahiert.

Auszug aus der encryptCTR Methode:
// extract bytes that will be stored in the receipt (only bytes 0-7) 
// cryptographic NOTE: this is only possible due to the use of the CTR 
// mode, would not work for ECB/CBC etc. modes 

final byte[] encryptedTurnOverValue = new byte[turnOverCounterLengthInBytes]; // or 5 bytes if min. 
    // turnover length is 
    // used 
    System.arraycopy(encryptedTurnOverValueComplete, 0, encryptedTurnOverValue, 0, 
            turnOverCounterLengthInBytes); 
    // encode result as BASE64 

    return CashBoxUtils.base64Encode(encryptedTurnOverValue, false); 

Wäre es auch möglich den vollen 16 Byte Umsatzzaehler zu verwenden ?

**Comment by asitplus-pteufl** [comment]
Bitte den aktuellen Code anschauen (den gab es auch schon bei Ihrer Anfrage, ich denke Sie haben noch die alten Version...), schauen Sie die Methode get2ComplementRepForLong bei der Verschlüsselung an Zeile 465 in https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-common/src/main/java/at/asitplus/regkassen/common/util/CashBoxUtils.java#L465

16-Byte Umsatzzähler wird etwas mühsam bei der Länge des QR-Codes, daher max. 8 byte verwenden.

**Comment by asitplus-pteufl** [comment]
bitte auch beachten, dass nicht nur der startbeleg (Umsatzzähler ist 0) korrekt ist, sondern auch weitere Belege im DEP (beim Startbeleg würde nämlich eine falsche Kodierung, z.B. Little Endian nicht auffallen).

**Comment by wolfgangstiegler** [comment]
Nachdem ich mich jetzt durch den JAVA Code gequält habe, hab ich es jetzt doch hinbekommen :-)
Jedenfalls läuft die Überprüfung des DEP (Startbeleg und mehrere Standardbelege inkl. ausgefallener Sicherheitseinrichtung) ohne Fehler durch.

Vielen Dank für Ihre Hilfe.

lg
Wolfgang
