### ISSUE TITLE
Beispieldatei für cryptographicMaterialContainer.json / Verwendung eines Kartenlesers mit dem Mustercode

### ISSUE THREAD

**Issue by maxp1256** [a-sit-plus/at-registrierkassen-mustercode#122]
Gibt es ein Beispiel, wie die cryptographicMaterialContainer.json-Datei aussieht, wenn ein echtes Zertifikat von a.trust verwendet wird? Wenn man die Demo-Anwendung startet wird ja nur ein selbstgeneriertes Zertifikat verwendet, welches offensichtlich wesentlich "kürzer" ist, da es weniger Eigenschaften und keine Kette (?) enthält.

Alternativ wäre es auch interessant, ob das Musterprojekt mit einem Chipkartenleser betrieben werden kann?

**Comment by A-Trust** [comment]
Ein Beispiel einer cryptographicMaterialContainer.json-Datei mit A-Trust Zertifikaten kann ich ihnen erzeugen.

`{
  "base64AESKey": "GXVbS9G+rbEUGdN0uzTIkVR36/OrNlnMvP9k7h0DMMU=",
  "certificateOrPublicKeyMap": {
    "6edceb2b": {
      "id": "6edceb2b",
      "signatureDeviceType": "CERTIFICATE",
      "signatureCertificateOrPublicKey": "MIIE1jCCA76gAwIBAgIEbtzrKzANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBgwCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaYS1zaWduLVByZW1pdW0tVGVzdC1TaWctMDIxIzAhBgNVBAMMGmEtc2lnbi1QcmVtaXVtLVRlc3QtU2lnLTAyMB4XDTE2MDUwMjEzMDA0MloXDTIxMDUwMjExMDA0MlowYjELMAkGA1UEBgwCQVQxGDAWBgNVBAMMD1VJRCBBVFUxMjM0NTY3ODEUMBIGA1UEBAwLQVRVMTIzNDU2NzgxDDAKBgNVBCoMA1VJRDEVMBMGA1UEBQwMODcwNjgxMjIyMDM2MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9y6foVH0vOBu6bSVl1582vMYXDFHS7qb5BP9xUFVGtZzy9cIqxEkggZn9CvOjFmkeHJXqFM+AZ68lmWbN7ldTaOCAh0wggIZMIGEBggrBgEFBQcBAQR4MHYwRgYIKwYBBQUHMAKGOmh0dHA6Ly93d3cuYS10cnVzdC5hdC9jZXJ0cy9hLXNpZ24tUHJlbWl1bS1UZXN0LVNpZy0wMi5jcnQwLAYIKwYBBQUHMAGGIGh0dHA6Ly9vY3NwLXRlc3QuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQEAwIGwDAnBggrBgEFBQcBAwEB/wQYMBYwCAYGBACORgEBMAoGCCsGAQUFBwsBMIGuBgNVHR8EgaYwgaMwgaCggZ2ggZqGgZdsZGFwOi8vbGRhcC10ZXN0LmEtdHJ1c3QuYXQvb3U9YS1zaWduLVByZW1pdW0tVGVzdC1TaWctMDIgKFNIQS0yNTYpLG89QS1UcnVzdCxjPUFUP2NlcnRpZmljYXRlcmV2b2NhdGlvbmxpc3Q/YmFzZT9vYmplY3RjbGFzcz1laWRDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MAkGA1UdEwQCMAAwWQYDVR0gBFIwUDAIBgYEAIswAQEwRAYGKigAEQELMDowOAYIKwYBBQUHAgEWLGh0dHA6Ly93d3cuYS10cnVzdC5hdC9kb2NzL2NwL2Etc2lnbi1QcmVtaXVtMBMGA1UdIwQMMAqACEYGn45BjhW9MBEGA1UdDgQKBAhDL4FTl24k4zAYBgNVHREEETAPgQ10ZXN0QHRlc3QuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQA7bt9Gdv9lZrTewcRPUIMRirl3Bv/5/m/GPLtQzL+zKpt3k39XigUecKidLkM5V1Y/CZD5yAkasu0yDt6wrJj0s+ThrRD4s6hrE8EVPN8Bja4NIAnQiaKof9/8zbcnuZKqh/k8NyWIeS2bQetgKTTKPErpy/KI546l3VALBKj5+qSDRO942a+rhxMXCqIei0/rotT/xqWpDwBXfKowJNcA4tQPHR43Tgsn6sUCRHKISEhwEQvFYuXFhIgJp9Bc7kP0n7kPD6sw+BPoGvQqH1/NVjPADgkRk9acCwoNxBjQaS9/QUZ69Aefpf/laZemACrygVJwrpsV90m4B0x/UVVk" 
    }
  }
}
`

**Comment by erneu** [comment]
Hallo maxp1256!

Zur zweiten Frage: Musterprojekt mit einem Chipkartenleser

Diese Frage war und ist für uns auch offen...

Es gibt dazu folgende Statements:
( https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/105 )

Dokument "Detailfragen RKSV 1.2" der Mustercode "Punkt 3.1 Erstellung der JWS-Signatur finden wir den Punkt "Referenzen - Muster-Code - Signatur via APDUs" -> noch nicht vorhanden." ( https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.2-DOK/2016-09-05-Detailfragen-RKSV-V1.2.pdf )

A-SIT Input: 17.8.2016 (und 8.9.2016)
"Das muss noch mit dem BMF geklärt werden, generell wäre natürlich eine Demonstration im Muster-Code sicher von Vorteil."

A-Trust Input: am 15.7.2016 
"Unser empfohlener Weg auf die Karte unter Java zuzugreifen sind direkte APDU Kommandos. "  -> also kein PKCS#11 von Seiten A-Trust...

**Comment by asitplus-pteufl** [comment]
Sie können in die Container-Datei jedes Zertifikat ablegen (egal ob selbst signiert oder von einer CA, die Kette legen Sie eh in keinem Fall dazu ab, es wird nur die kryptographische Gültigkeit geprüft und nicht der Vertrauensstatus, das hat für die Überprüfung der Korrektheit der Implementierung keine Relevanz). Wenn Sie also mit Ihrer Implementierung/Kasse ein Echt-Zertifikat verwenden und damit Belege/DEP-Exports erstellen, dann einfach den AES-Schlüssel der Kasse und das Zertifikat BASE64-kodiert (Details siehe Detailfragen-Dokument) in der Datei ablegen. Das Prüftool kann dann die Korrektheit überprüfen.

Das Muster-Code Projekt können Sie mit PKCS11 betreiben. Für APDUs kann ich Sie nur auf die ZDA-Code Beispiele verweisen.
