### ISSUE TITLE
Mindestlänge des Maschinencodes: 150 Zeichen sind zu viel

### ISSUE THREAD

**Issue by MartinDomig** [a-sit-plus/at-registrierkassen-mustercode#123]
Ich bekomme mit dem Prüftool ab Version 0.7 bei einzelnen Belegen die Meldung, dass die Länge des maschinenlesbaren Codes nicht passt ("Es wird überprüft ob der maschinenlesbare Code eine Länge von minimal 150 bis maximal 1000 Zeichen hat." - details bitte dem Attachment entnehmen
[mindestlaenge.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/470088/mindestlaenge.zip)

)

Das kann ich zuverlässig reproduzieren, indem ich bei relativ kurzen Kassen- und Belegnummern mit einer ausgefallener Sicherheitseinrichtung einen Beleg über einen Euro storniere. So wie ich das interpretiere ist in diesem Fall der Maschinenlesbare code nämlich tatsächlich nur 147 bytes lang.

Base64 codiert:

`eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9NMDNfI00wMy0wMDAwN18yMDE2LTA5LTEzVDE2OjE1OjEzXzAsMDBfLTEsMDBfMCwwMF8wLDAwXzAsMDBfVTFSUF83RkM3Q0IwQl9kaTVvQkMzcXl4TT0=.U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==`

In lesbarer Form:

`{"alg":"ES256"}._R1-AT1_M03_#M03-00007_2016-09-13T16:15:13_0,00_-1,00_0,00_0,00_0,00_U1RP_7FC7CB0B_di5oBC3qyxM=.Sicherheitseinrichtung ausgefallen`

Da das Prüftool mit vielen anderen Fällen aber glücklich zu sein scheint (z.B. besteht der selbe Stornobeleg wenn die Sicherheitseinrichtung nicht ausgefallen ist alle Tests) bin ich geneigt einen Fehler meinerseits auszuschließen. Damit sie das überprüfen können habe ich den json export aus der Kasse sowie den output des Prüftools hier als Attachment angehängt.

Ist eventuell das Längenlimit des Maschinencodes mit 150 Zeichen zu hoch gesetzt?

**Comment by 01af** [comment]
@MartinDomig Es wurde kurz nach 0.7 die Version **0.7.1** nachgeschoben. Probier die mal aus.
Laut Changelog wurde die Minimallänge des Belegs auf 100 anstelle von 150 Zeichen geändert.

**Comment by MartinDomig** [comment]
Jep, mit 0.7.1 funktionierts. Danke!
