### ISSUE TITLE
DEP Export immer komplett

### ISSUE THREAD

**Issue by giemes** [a-sit-plus/at-registrierkassen-mustercode#124]
Da es im Gesetzestext nicht unbedingt eindeutig formuliert ist hier nun die Frage zur Klarstellung - unsere Interpretation:

Der DEP-Export (der spätestens jedes Quartal passieren soll/muss) muss für jede Kassa immer vom Startbeleg beginnend vollständig sein und kann nicht nur gewisse Zeiträume beinhalten. Dh: das DEP für eine Kassa wird immer größer und kann - im Falle von "großen Beleganzahlen" doch beachtliche Einzeldaten beinhalten.
Das DEP-Prüftool bringt auch einen Fehler, wenn das exportierte DEP nicht mit dem Startbeleg beginnt: "verificationState" : "FAIL", "verificationResultDetailedMessage" : "Am Beginn des DEPs befindet sich kein gültiger Startbeleg. Dies widerspricht der Spezifikation des DEPs."

Dh: kann der Prüfer ein gewisses "Zeitfenster" - zB: Q3 eines Jahres, ein bestimmtest Jahr, etc exportiert haben oder wird immer "bis zum Q3 des Jahres x" exportiert?

Warum "verunsichert" es uns - wegen:

> (3) Die Daten des Datenerfassungsprotokolls sind zumindest vierteljährlich auf einem elektronischen externen Medium unveränderbar zu sichern. Diese Sicherung ist gemäß § 132 BAO aufzubewahren.

Das würde ja inkrementell vergrößerte Daten mit immer einem Großteil der gleichen Inhaltsdaten bedeuten die revisionssicher abgelegt - dh: auch nicht ersetzt werden dürfen.
Oder ist es möglich den DEP-Export zB: Quartalsweise" durchzuführen.

Danke für die Info.

**Comment by asitplus-pteufl** [comment]
Kann als A-SIT Plus da nur folgendes im Moment sagen: Der Fokus des Prüftools ist die Überprüfung der Korrektheit der Implementierung der Kasse, dies ist auf jeden Fall auch mit der fixen Forderung dass der Startbeleg am Anfang vorhanden sein muss möglich.

Werde das Thema in Bezug auf den "ersten Beleg" im Export an das BMF weiterleiten.

**Comment by vejo** [comment]
Über längere Zeiträume gesehen würde das auch bedeuten, dass bei Versionsänderung des Kassensystems (wenn sich dabei das Aufzeichnungsformat ändert) die bisherigen historischen Daten für den DEP-Export verfügbar gehalten, d.h. bei der Umstellung möglicherweise konvertiert werden müssen.
Damit würde aber die Vergleichsmöglichkeit mit den revisionssicher verwahrten Sicherungen verloren gehen.

Genau genommen müssten Daten auch für mehr als 7 Jahre vorgehalten werden, was der BAO widerspricht.

Auf das Problem mit den anlaufenden Datenmengen wurde ja bereits hingewiesen.

-

In den Sitzungen der UBIT gemeinsam mit dem BMF wurde dieser Punkt folgendermaßen beantwortet:
Das BMF geht davon aus, dass eine Registrierkasse in der Lage ist, das Datenaufkommen von 3 Monaten lokal zu speichern.
Quartalsweise sind diese Daten extern zu sichern (Schutz gegen Untergang).
Das gesamte DEP ergibt sich aus der Kombination der Sicherungen und der lokal gespeicherten Daten.
Der DEP-Export an der Kasse hat damit zumindest die letzten 3 Monate zu enthalten.
Dieser beginnt dann logischerweise nicht zwingend mit dem Startbeleg.

**Comment by giemes** [comment]
@vejo Danke für die Zusatzinfos
@asitplus-pteufl wenn möglich bitte um kurze Bestätigung, dass der DEP-Export nicht immer beim Startbeleg beginnen muss (was ja Sinn macht)
Danke!

**Comment by AxelKutschera** [comment]
@vejo: "Genau genommen müssten Daten auch für mehr als 7 Jahre vorgehalten werden, was der BAO widerspricht."
So einfach ist das mit den 7 Jahren nicht: 
"§ 132. (1) Bücher und Aufzeichnungen sowie die zu den Büchern und Aufzeichnungen gehörigen Belege sind sieben Jahre aufzubewahren; darüber hinaus sind sie noch so lange aufzubewahren, als sie für die Abgabenerhebung betreffende anhängige Verfahren von Bedeutung sind, in denen diejenigen Parteistellung haben, ..."
--> Die Grenze der 7 Jahre gelten nicht immer absolut, es gibt auch noch andere Fälle, wo zB 22 Jahre definiert sind...
Zudem ist die BAO auch nicht das einzige Gesetz nach dem die Ordnungsmäßigkeit beurteilt wird.

**Comment by asitplus-pteufl** [comment]
Prüftool: Das Verhalten des Prüftool ist darauf ausgelegt die korrekte Implementierung zu prüfen. Daher werden dort auch nur DEPs mit Startbeleg akzeptiert. 

Zum Thema Export für Zeiträume:
Nach Rückfrage im BMF, ist Teilexport gemäß § 19 Abs. 2 RKSV grundsätzlich vorgesehen.

**Comment by ErichFreitag** [comment]
Aus aktuellem Anlass hier noch eine Ergänzung - diese stammt aus einer Antwort auf eine Frage anlässlich des letzten WKO-Arbeitskreises zu diesem Thema:

Die RKSV schreibt die Sicherung sämtlicher Daten des DEP (sämtlicher Daten der Geschäftsvorfälle) vor (§ 7 Abs. 3 RKSV). Damit müssen neben den DEP-Teilen mit Exportformat sämtliche Beleginhalte bzw. Belegdaten, so auch die „handelsübliche Bezeichnung“ und „Menge/Preis“ gesichert werden.

Wenn auch ein nachträgliches Einspielen von gesicherten DEP-Daten nicht die primäre Zielrichtung dieser Bestimmung ist, so muss über die Sicherung die Prüfbarkeit zumindest vom Startbeleg bis zur letzten Sicherung gewährleistet bleiben.

Sofern eine Komplettsicherung sichergestellt ist, so darf eine frühere Sicherung überschrieben werden d.h. es ist nicht zwingend erforderlich 7x4 (=28) Sicherungsdateien aufzubewahren.

Gemäß § 7 Abs. 3 RKSV sind (sämtliche) Daten des DEP zumindest vierteljährlich … zu sichern. Aus der Wortinterpretation kann abgeleitet werden, dass im Maximalfall nicht unbedingt 28 DEPs vhd. sein müssen, sondern dass auch neue Sicherungen alte Sicherungen überschreiben dürfen, solange der gesamte Datenbestand (vom Startbeleg bis zum zuletzt erstellten Beleg) vorhanden ist und exportiert werden kann.

Das Interesse liegt auf der Komplettsicherung, eine gestückelte Sicherung ist nicht erwünscht.

Wenn eine Registrierkasse z.B. 10 Jahre läuft dann hat auch das DEP über den gesamten Zeitraum zur Verfügung zu stehen. Die letzte Wegsicherung muss wieder 7 Jahre aufbewahrt werden.
