### ISSUE TITLE
regkassen-verification-common fehlt in Version 0.7.1

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#125]
Beim Bauen von "regkassen-democashbox" bekomme ich folgende Fehlermeldung:
"The POM for at.asitplus:regkassen-verification-common:jar:1.0.9 is missing, no dependency information available"
Was läuft das schief ?

**Comment by asitplus-pteufl** [comment]
Diese Bibliothek des Prüftools wird nicht als Source veröffentlicht. Das Muster-Code Projekt braucht aber ein paar Elemente davon. Sie können sich die Datei aus dem Prüftool extrahieren und in Ihrer IDE oder in ihr Maven Repository legen, um das Muster-Code Projekt bauen zu können.

**Comment by woko1754** [comment]
Danke, funktioniert.
