### ISSUE TITLE
Meldung an das Finanzamt: Signatureinrichtung und Kassa - Meldungszeitraum

### ISSUE THREAD

**Issue by giemes** [a-sit-plus/at-registrierkassen-mustercode#126]
Etwas verwirrend ist die Darstellung der Meldung der Signaturerstellungseinheit und Kassa im Bezug auf "den Meldungszeitraum" bzw. eventuell eine Reihenfolge an das Finanzamt:

1. Meldungszeitraum:

> §6 Abs 3: Wird eine Registrierung nach dem 31. Dezember 2016 vorgenommen, so hat die Inbetriebnahme binnen einer Woche nach Registrierung der Signaturerstellungseinheit (§ 16) zu erfolgen.

In den Detailfragen ist jedoch eine freie Zuordnung zwischen N Kassen und M Signatureinrichtungen beschrieben, eine Kasse kann frei aus den SE wählen. Welche Registrierung der Signatureinrichtung wird da dann für $6 Abs 3. herangezogen? Die letzte in Betrieb genommene?

Dh: Frage: ist bekannt, ob diese 7-Tagesregel noch immer Gültigkeit hat und wen ja wie wäre im folgenden Punkt vorzugehen:

Nun der Punkt:
Wenn ein Kunde nun eine Signatureinrichtung hat, eine neue Kasse innerhalb der 7 Tage in Betrieb nimmt und nun z.B. 2 Monate nachher eine weitere Kasse mit derselben Signatureinrichtung in Betrieb nehmen will, ist das dann verboten? Muss für jede neue Kasse eine neue Signatureinrichtung erworben werden, wenn die Registrierung der letzten SE bereits länger als 7 Tage her ist?

2. Reihenfolge der Meldungen:

> § 16. (1) Der Unternehmer oder sein bevollmächtigter Parteienvertreter hat über FinanzOnline den Erwerb seiner Signaturerstellungseinheiten zu melden. Dabei sind die Seriennummer des Signaturzertifikates, die Art der Signaturerstellungseinheit und die Kassenidentifikationsnummern der mit der Signaturerstellungseinheit zu verbindenden Registrierkassen bekannt zu geben.

Es gibt keine Option, innerhalb der Meldung einer neuen Signatureinrichtung über die FinanzOnline RKDB API auch daran gekoppelte Kassen zu melden. In der API sind die Meldung von Signatureinrichtungen und die Meldung von Kassen zwei völlig getrennte Operationen, laut dem §16 jedoch zu einer zusammenzufassen. Wie hat nun die Reihenfolge der Meldungen (Signaturerstellungseinheit vs. Kassa) zu geschehen und wie wie viel Zeit kann zwischen den Meldungen vergehen?

Ich hoffe um Auskunft ... Danke!

**Comment by ErichFreitag** [comment]
@giemes - das ist durchaus beim durchlesen verwirrend.

a) ja, es gilt immer noch, konkret mit der RKSV-Änderung BGBl. 210/2016:
"§ 6 (3) Wird die Inbetriebnahme der Sicherheitseinrichtung nach dem 31. März 2017 vorgenommen, muss die Registrierung (§ 16) spätestens binnen einer Woche nach Inbetriebnahme erfolgen".
Heißt: wenn sie eine neue Sicherheitseinrichtung nach dem 31.03.2017 in Betrieb nehmen -> spätestens nach einer Woche registrieren.

Davor "§ 6 (2) Vor dem 1. April 2017 kann die Inbetriebnahme der Sicherheitseinrichtung im Sinne Abs. 1 bereits vor der Registrierung (§ 16) vorgenommen werden. Die Registrierung muss bis zum 1. April 2017 erfolgt sein". 
Heißt: Installation vorher - bis 01.04.2017 registrieren (denn ab da muss ja alles "funktionieren").

Korrekt - in den Detailfragen ist die wahlfreie Zuordnung zwischen Kasse(n) und Signaturerstellungseinheit(en) beschrieben, diese ist ja sogar pro Transaktion möglich (was ja auch bei load balancing oder sonstigen Gründen notwendig ist und Sinn macht).

Im Erlass vom 04.08.2016 ist das auch präzisiert: "3.3.3.1 Signatur- bzw. Siegelzertifikate und Registrierkassen sind unabhängig voneinander zu registrieren, ihre Verbindung ist nicht zu dokumentieren".

Technisch ist es durch die FON-Schnittstelle gegeben, da werden ja Kassen und Zertifikate getrennt registriert.

Und am Ende spiegelt sich das im DEP-Export wieder, weil sie dort auch keine unmittelbare Zuordnung zwischen Einträgen und Zertifikaten haben.

Im § 16 (1) RKSV ist das anders formuliert. Kann man nichts machen. Die umgesetzte Realität mit Schnittstelle etc. trennt die beiden Registrierungen und das macht so auch Sinn. Es würde z.B. auch mit einem zentralen HSM gar nicht anders gehen.

Damit ist wohl auch ihre Frage schon beantwortet: wenn sie eine Kasse dazu bekommen und die selbe (besser: eine der vorhandenen und dem Unternehmen zugeordneten) Signaturerstellungseinheiten benutzen müssen sie nur die Kasse registrieren. Wenn sie einen neuen Standort eröffnen und dort eine neue Kasse hinstellen und eine neue Signaturerstellungseinheit anstecken müssen sie beides getrennt registrieren.

Detail am Rande: die Kasse geht ja mit einem Startbeleg in Betrieb. Sie werden also die Kasse im Normalfall davor registrieren, damit z.B. die Prüfung des Startbelegs über FON automatisch erfolgen kann. Damit der Startbeleg geprüft und signiert werden kann muss/müssen vorher die Signaturerstellungseinheit(en) registriert sein.

**Comment by MartinDomig** [comment]
Ich habe eine dazu thematisch passende, wenn auch etwas andere Frage:

Angenommen sei eine zentrale Signaturerstellungseinheit und mehrere mobile Kasssen, die über eine Funkverbindung mit der zentralen SE kommunizieren. Eine der mobilen Kassen bewegt sich jetzt in ein Funkloch, d.h. sie kann nicht mehr mit der SE kommunizieren, muss aber weiterhin Belege ausstellen können. Diese Belege werden mit dem Vermerk "Signaturerstellungseinheit ausgefallen" versehen.

Ausfälle länger als 48 Stunden sind ohne unnötigen Aufschub über FinanzOnline zu melden. Nur... was meldet man in diesem Fall? Melden kann man nur den Ausfall einer Kasse oder einer Signaturerstellungseinheit, aber beide funktionieren - lediglich die Verbindung zwischen einer dieser Kassen zur SE ist betroffen. Ist das überhaupt ein meldungspflichtiger Ausfall?

**Comment by ErichFreitag** [comment]
Gute Frage, @MartinDomig. Wohl auch nicht eindeutig zu beantworten.

_Am Rande vermerkt: ich finde es besser, für ein neues Thema ein neues Issue zu eröffnen, dann ist die thematische Verfolgung einfacher._

Ich habe folgenden Zugang zu diesem Thema:

Wenn man die RKSV rein formal betrachtet - keine Meldung, weil ja weder das eine noch das andere ausgefallen ist.

Wenn man es pragmatisch betrachtet - die Kasse wird ja irgendwann wieder Zugang zur Signaturerstellungseinheit haben. Der Betreiber ist ja auch angehalten, Fehlerbehebungsmaßnahmen zu setzen.

Aus Sicht des Erlasses: zwar auf den Startbeleg bezogen, jedoch auch später referenziert 3.5.3.3 - Fehlerursache raschest möglich beheben und solange als Kasse mit ausgefallener Sicherheitseinrichtung betreiben, der Betrieb kann fortgesetzt werden. Der Fall, dass die Kasse oder die Sicherheitseinrichtung defekt ist tritt ja hier nicht unmittelbar ein.

Erlass 3.6.1 - Fehlerbehebung gemäß 3.5.3.3 durchführen. Nach Fehlerbehebung (in diesem Fall) Sammelbeleg erstellen - erledigt.

Erlass 3.6 - "Lässt sich nicht konkret feststellen, ob die Registrierkasse oder die Signatur- bzw. Siegelerstellungseinheit defekt ist, kann allgemein der Ausfall der Registrierkasse gemeldet
werden". Das sehe ich als Möglichkeit vor allem für länger dauernde und nicht unmittelbar zu behebende Fälle, weil sie in der Begründung angeben könnten "Verbindung zur Sicherheitseinrichtung unterbrochen". Allerdings müssen sie eine Wiederverfügbarkeit der Kasse dann wohl (auch) händisch auslösen.

Als wesentlich erachte ich am Ende gemäß 3.5.3.3 "die Fehlerursache und das Vorgehen bei der
Fehlerbehebung sind im Sinne des § 132 BAO zu dokumentieren". Wenn sie nachvollziehbar dokumentiert haben, was genau passiert ist und was sie wann und wie dagegen unternommen haben wird das wohl im Sinne der RKSV sein (weil ja auch durch den Ausfall der Verbindung keine Belege verloren gehen).

**Comment by norbert2** [comment]
![anmeldungfaonline](https://cloud.githubusercontent.com/assets/22190305/18527015/4618a5f8-7ac3-11e6-9c1b-71e24245e87c.png)

Von A-Trust wurde mir ein Screenshot von der Zertifikatsanmeldung zugeschickt.
Gibt's schon die Möglichkeit, auch Kassa-Nummern und AES-Schlüssel zu melden?
Mich würde davon ebenfalls Screenshots interessieren, wie sich das wirklich darstellt und zu handhaben ist. Ist zwar natürlich Sache des Kunden selbst, aber ich möchte ihn dabei so gut wie möglich unterstützen und Bescheid wissen.

**Comment by asitplus-pteufl** [comment]
@norbert2  Themen mit Bezug zu FinanzOnline können auf dieser Plattform nicht beantwortet werden. Aber kurz gesagt, Sie können alle notwendigen Meldungen durchführen, Startbelegprüfung über App ist auch möglich.

**Comment by giemes** [comment]
@norbert2 - einfach mit einem FinanzOnline Zugang anmelden und dort beim Submenüpunkt "Registrierkassa" hinschauen - da gibts alle Listen, Eingabeformular, etc. Als Unternehmer hat man das automatisch drinnen.
lGG

**Comment by SEHellFire** [comment]
Das komplette Handbuch inkl. Screenshots für FinanzOnline befindet sich hier:

https://finanzonline.bmf.gv.at/eLearning/BMF_Handbuch_Registrierkassen.pdf

**Comment by norbert2** [comment]
Perfekt. Genau das habe ich gesucht. Danke.
Übrigens:
Ich dachte, nur die Programmierer haben mit der RKSV was zu arbeiten.
Aber diese "Anmelderei" und "Prüferei" bei Finanzonline: Da dürfen hunderte Steuerberater die FO-Meldungen durchführen für tausende von Kassen.
Ob das gut geht.....
