### ISSUE TITLE
Fahrverkauf

### ISSUE THREAD

**Issue by norbert2** [a-sit-plus/at-registrierkassen-mustercode#127]
Ein Kunde von mir betreibt einen Fahrverkauf von Obst und Gemüse. Täglich sind ca. 5 LKW unterwegs, die mit  Laptop und Drucker ausgestattet sind. Damit werden die BV-Rechnungen gedruckt.
Der Laptop ist NICHT online mit der Hauptdatenbank verbunden. Daten werden nach Rückkehr eingespielt.
Die Einnahmen laufen zur Zeit in EIN Kassabuch.

Wie gehe ich das am besten an:
Wenn ich jeden Laptop mit Signierungseinheit ausstatte, muss ich wohl aus den 5 Laptops 5 Kassen machen mit 5 Kassabüchern.  Das möchte mein Kunde sicher nicht.
Außerdem ist anzunehmen, dass die Signierungseinheiten wegen Hitze, Kälte, Staub eher öfters nicht funktionieren werden und das doch erheblichen Supportaufwand nötig machen wird.

Oder ich signiere die Belege nicht vor Ort, sondern drucke im Zuge der Dateneinspielung bei Rückkehr die signierten Belege im Büro aus, mit EINER Signierungseinheit für EIN Kassabuch und EINEM KassaDEP.
Wäre das rechtlich zulässig?
Hat da wer vielleicht Erfahrung?

**Comment by ErichFreitag** [comment]
@norbert2 - Erfahrung nein, aber sie werden wahrscheinlich im Erlass vom 04.08.2016 darauf eine Antwort finden. Da sind Beispiele für solche oder ähnliche Umstände angeführt.

**Comment by norbert2** [comment]
Habe die Information erhalten, dass das Nachsignieren im Büro ist zulässig.
Hier die neue Frage:
Muss im Zuge der Nachsignierung der Beleg  in Papierform erstellt und mit dem unsignierten Beleg abgelegt werden?
Oder genügt es, wenn diese Belege nur als PDF gespeichert werden und somit auch einsehbar sind?

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
