### ISSUE TITLE
Nicht signierte Belege

### ISSUE THREAD

**Issue by ct-graz** [a-sit-plus/at-registrierkassen-mustercode#129]
Nachdem Geschäftsfälle, die kein Barumsatz sind, nicht signiert werden müssen/sollen:
Was macht man mit denen, man muss sie ja trotzdem drucken?
Soll man sie einfach mit Umsatz 0 signieren?
Oder im DEP auslassen und beim Druck einen Hinweis drucken?
Es sieht dann ja verdächtig aus, wenn der Beleg dann ohne QR-Code ausgehändigt wird.

**Comment by ErichFreitag** [comment]
Meine Sicht der Dinge:

a) drucken hat ja mit signieren nichts zu tun.
b) mit Umsatz 0 wäre wohl falsch; wenn signiert dann mit Betrag im 0%-USt.-Satz. Das erhöht auch korrekt den Umsatzzähler
c) signieren = DEP, somit nicht im DEP auslassen wenn signiert (es würde ja auch die Kette unterbrochen werden)
d) verdächtig - warum? ohne Signierung gibt es keinen maschinenlesbaren Code.
e) schaden kann ein Hinweis nichts, erforderlich ist er nicht
f) nicht signiert werden sollen stimmt so auch nicht - lediglich nicht signiert werden müssen. Im Erlass ist beispielsweise mehrfach erwähnt, dass eine Signierung auch für nicht-barumsatzpflichtige Vorgänge durchaus Sinn macht (und auch erlaubt ist).

In meinen Projekten sind wir mittlerweile durchgängig zur Ansicht gekommen, grundsätzlich alles zu signieren - es spricht auch nichts dagegen und vermindert das Risiko von Fehlinterpretationen. Eine wie auch immer geartete Entscheidungslogik für derartige Umsätze brauchen sie ohnedies - es ist dann auch egal, ob die Logik ausgibt "nicht signieren" oder "in den 0 %-USt.-Satz schreiben".

**Comment by 01af** [comment]
@ct-graz 
So wie ich das verstanden habe ist die Erfassung freiwillig. 
Um bei einer freiwilligen Erfassung die Einträge im DEP 
von tatsächlichen Barumsätzen zu unterscheiden zu können, 
wird der Betrag als NULL% Umsatz eingespeichert.

@ErichFreitag ist mir da jetzt schon zuvorgekommen, deshalb
nur noch kurz als Ergänzung, in der FAQ-Sammlung vom  [WKO](https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/FAQ-Arbeitskreis-Kassensoftware.pdf) und
in dem Erlass zur "Einzelaufzeichnungs-, Registrierkassen -und Belegerteilungspflicht"
vom 4.8.2016 wird steht dazu etwas.

**Comment by ct-graz** [comment]
Wenn ein Kunde einen Beleg ohne Signierung bekommt, kann er sich schon wundern. Er muss ja keine Ahnung haben, ob das richtig ist.

Wenn ich auch alle Kassaausgangsbelege (z.B. Bargeldentnahmen, Ausbuchen der bankomatzahlungen) normal verarbeite, wird sich der Umsatzzähler über die Zeit nicht erhöhen und immer nur den Kassastand enthalten. Das ist wohl nicht im Sinn des Erfinders.

**Comment by ErichFreitag** [comment]
@ct-graz: in ein Protokoll - ja, aber das (bisher schon vorhandene) Kassen-Protokoll hat zunächst mit dem RKSV-DEP nichts zu tun. Wenn sie alles signieren werden sich die beiden am Ende sehr ähnlich sehen. Und sie müssen ja auch das Kassen-Protokoll = Journal unabhängig vom DEP exportieren können (RKSV § 19 (2)).

Beleg ohne Signierung - mag sein, aber nicht erforderlich. Siehe Erlass 4.6, 2. Absatz.

Bei dem Thema "was soll signiert werden, was nicht signiert werden muss" geht es ja eher um Vorgänge, die kundenbeleg-relevant sind. Also beispielsweise um Wertgutscheine, die bei der Ausgabe nicht signierpflichtig wären.

Wenn sie z.B. vorsehen, auch Bargeldentnahmen zu signieren, verringert sich der Umsatzzähler (siehe z.B. Erlass 3.2.4). Die Entscheidung, wie mit solchen Fällen umgegangen werden soll, wird letzten Endes auch branchenabhängig und eine der jeweiligen Kassenbetreiber sein.

**Comment by asitplus-pteufl** [comment]
Der Vollständigkeit halber möchte ich hier als A-SIT Plus folgendes anmerken (siehe auch README auf der Startseite).

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html).

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
