### ISSUE TITLE
Export DEP

### ISSUE THREAD

**Issue by norbert2** [a-sit-plus/at-registrierkassen-mustercode#130]
Für Betriebskantinen werden PCs samt Drucker als Kassen verwendet. 
Die Daten der Kassa werden mit Kassaabschluss an die Hauptdatenbank übertragen.
Das heißt, die Kassa selbst funktioniert auch offline. Was gewünscht ist, weil wenn 1000 Leute zu Mittag essen wollen, sollen die nicht warten müssen, weil die Verbindung zum Server gerade nicht funktioniert.
Der Export des DEP kann NICHT an der Kassa selbst durchgeführt werden. Erst mit Kassaabschluss werden die Daten in die Hauptdatenbank übertragen. Von einer Back-Office-Anwendung aus kann dann der Export des DEP gestartet werden.

Meine Frage nun:
Kann ein Prüfer das beanstanden, dass vor Ausgabe des DEP zuerst der Kassenabschluss  der jeweiligen Kassa durchgeführt werden muss? 
Der Kassaabschluss selbst kann allerdings eh jederzeit durchgeführt werden. Das DEP kann also innerhalb von 5 Minuten  ausgegeben werden.

Aufgrund des Auszuges aus dem Erlass hoffe ich doch, dass das zulässig ist:

3.2.1.3. Export der DEP-Daten 

.....  Die Bereitstellung der Daten, bzw. Zugangsdaten hat ohne unnötigen Aufschub, d.h. unmittelbar, wenn eine Person mit Zugriffsberechtigung anwesend ist bzw. **längstens innerhalb von zwei Werktagen nach vorheriger Verständigung der Abgabenbehörde** zu erfolgen. Bei Glaubhaftmachung der Unzumutbarkeit der Einhaltung dieser Frist, kann diese in der Einzelfallbetrachtung auch verlängert werden.

Bitte um Beurteilung.

**Comment by norbert2** [comment]
Zur Präzisierung:
Der Kassaabschluss erfolgt zumindest einmal täglich am Ende des Tages.
Das DEP kann also von der zentralen Anwendung mit Daten älter als dem aktuellen Tag jederzeit ausgegeben werden. 
Das abklärungsbedürftige Szenario tritt also nur dann auf, wenn der Prüfer die Daten des aktuellen Tages im DEP prüfen will.

**Comment by lebail** [comment]
Im Erlass steht unter "3.1.3. Sonstiges elektronisches Aufzeichnungssystem":

> Darunter können auch serverbasierte Aufzeichnungssysteme verstanden werden, bei denen
> die Erfassung des Barumsatzes und die Ausfertigung des Zahlungsbelegs in Form einer
> Eingabestation örtlich getrennt von der Erstellung der Signatur bzw. des Siegels und der
> Aktualisierung des Datenerfassungsprotokolls auf einem Server durchgeführt werden.
> […]
> Als Prinzip gilt, dass das elektronische Aufzeichnungssystem die Erstellung der Signatur, die
> Aktualisierung des Datenerfassungsprotokolls und die Belegerstellung nach der Erfassung
> eines Barumsatzes vor der Erfassung des nächsten Barumsatzes sicherstellen muss.

Daraus würde meiner Meinung nach folgen, dass das nachträgliche Erstellen des DEP (auf dem Server) nicht zulässig ist. Wobei sich bei Ihrer Beschreibung ja auch die Frage stellt, wann und wo Sie die Signaturen erstellen. Wenn Sie diese auf den einzelnen Kassen erstellen, braucht ohnehin jede Kasse ein eigenes DEP. Wenn Sie sie hingegen auf dem Server erstellen (und Ihre "Kassen" nur "Eingabestationen" im Sinne der RKSV sind), muss dies jeweils *sofort* erfolgen (samt Erfassung im zentralen DEP), weil Sie ja die Signatur auf den Beleg drucken müssen.

Achtung: Ich bin kein A-SIT-Mitarbeiter und gebe nur meine persönliche Meinung wieder.

**Comment by norbert2** [comment]
Danke für Ihre Nachricht.

Zum Ablauf:
Es wird jeder PC als Kassa  betrachtet, ist ausgestattet mit einer Signierungseinheit. Der Beleg wird sofort signiert gedruckt.

Ich habe von A-Trust Seite die Auskunft, dass die Grunddaten des DEP MIT der Signatur schon z.B. in einer SQL-Server-Tabelle gespeichert werden können.  Natürlich mit der Kassa-Nr  versehen für die entsprechende getrennte Ausgabe des DEP pro Kassa.
Und eben von dieser Basistabelle aus erfolgt dann der Export in das eigentlich DEP im Json-Format.

Ich kann mir nicht vorstellen, dass mit JEDEM Beleg SOFORT das DEP im Jason-Format abhol- und prüfbereit in einer ASCII-Datei (das ist ja im Grunde die Json-Datei) bereitstehen muss.
Ich habe Betriebskantinen-Kassen, da komme ich locker auf 400.000 Belege pro Jahr. Schon nach einem halben Jahr wäre das sofortige Erstellen des DEP im richtigen Json-Format zeitlich pro Beleg zu aufwändig.

**Comment by lebail** [comment]
Danke!

Wenn jede Kasse ihr eigenes DEP hat und dieses einem Prüfer innerhalb weniger Minuten bereitgestellt werden kann, müsste das passen. Natürlich wird man das DEP nicht von Anfang an im JSON-Format führen, sondern erst nach Bedarf in diesem Format (z.B. aus einer Datenbank) exportieren.

Welche Zeitspanne ein Prüfer jetzt genau unter "unmittelbar" versteht, kann man wohl nur beim BMF erfragen. In der Kantine wird aber vielleicht ohnehin keine Person mit Zugriffsberechtigung anwesend sein, sodass es zwei Werktage dauern darf …

**Comment by norbert2** [comment]
Freut mich, dass Sie das auch so sehen. 
Dann habe ich doch noch einen ruhigen Sonntag.
