### ISSUE TITLE
RKObjectMapper fehlt

### ISSUE THREAD

**Issue by adaent** [a-sit-plus/at-registrierkassen-mustercode#131]
Hallo,

nach dem Clonen der Repository wurde dieser Import (siehe unten) nicht gefunden!

import at.asitplus.regkassen.verification.common.rpc.RKObjectMapper;

Könnt Ihr mir sagen wo ich es finden kann?

DANKE im vorraus

**Comment by asitplus-pteufl** [comment]
Ich verweise Sie da auf dieses Issue: https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/125 
Bitte überprüfen, danke!
