### ISSUE TITLE
Pool von Signatureinheiten beim Export

### ISSUE THREAD

**Issue by maxp1256** [a-sit-plus/at-registrierkassen-mustercode#132]
Hallo,

sofern eine Kasse mehrere Signatureinheiten hat, welche in einem Pool betrieben werden, könnte es durchaus vorkommen, dass bei jeder Buchung ein anderes Zertifikat verwendet wird.

Muss hier im JSON-Export dann pro "Zertifikatswechsel" ein neuer "Kopf" mit Signaturzertifikat und Zertifizierungsstellen erzeugt werden, nachdem die Belegzeilen ja in Erfassungsreihenfolge ausgegeben werden müssen?

**Comment by ErichFreitag** [comment]
Nein - siehe
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/84
RKSV Detailspezifikation Punkt 11
RKSV Detailfragen Punkt 5

**Comment by asitplus-pteufl** [comment]
@ErichFreitag, danke für die Antwort! damit Sie die Antwort auch von A-SIT Plus haben: Zertifikate im DEP-Export sind optional, also in Ihrem Fall macht es wohl keinen Sinn diese zu exportieren.
