### ISSUE TITLE
Auswertung der Ergebnisse des Prüftools.

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#134]
In der vom Prüftool (0.7.1) erzeugten Datei 'N_cashbox_full.json' sind Abschnitte mit '"verificationState" : "FAIL"' enthalten, auch wenn die 'N_cashbox.json' als Gesamtergebnis 'PASS' liefert.
Können diese ignoriert werden ?

**Comment by asitplus-pteufl** [comment]
Das wird vermutlich durch den Belegtyp verursacht, es kann ja nur einen Belegtyp mit PASS geben. Wenn ganz oben PASS herauskommt passt das Prüfergebnis auf jeden Fall.

**Comment by asitplus-pteufl** [comment]
wurde damit alles geklärt, oder gibt es noch offene Punkte?
