### ISSUE TITLE
DEP Verification unsignierte Belege

### ISSUE THREAD

**Issue by christianPett** [a-sit-plus/at-registrierkassen-mustercode#135]
Falls die Signatureinheit ausgefallen ist, so muss ein Nullbeleg / Sammelbeleg mit gültiger Signatur erstellt werden. OK. Aber wie schaut die Sache mit 2 Signatureinheiten und einem zentralen DEP aus?
Folgende Situation:
Startbeleg gültige Sig: OK
Beleg 1 mit Seriennummer A und gültiger Sig: OK
Beleg 2 mit Seriennummer B und gültiger Sig:  OK
Beleg 3 mit Seriennummer A und ausgefallener Sig: OK
Beleg 4 mit Seriennummer B und gültiger Sig:  FAIL   

Das kann ja wohl nicht richtig sein. Ich verstehe es, dass Sig.Einheit mit SNr. A zuerst einen Nullbeleg machen muss, aber wieso darf Sig.Einheit mit SNr. B nicht normal weiterarbeiten.

lg,
    Christian

**Comment by ErichFreitag** [comment]
Der Sammelbeleg dient letzten Endes dazu, um Start und Ende des Ausfalls der Sicherheitseinrichtung festzuhalten. Während eines SE-Ausfalls sind ja dennoch alle (zu signierenden) Belege im DEP enthalten und sie können den Ausfall damit leicht nachvollziehen.

Wenn eine von zwei SE-Einheiten ausfällt können sie ja mit der zweiten weiterarbeiten - damit kommt es aus Sicht der Kasse (= zentrales DEP) auch zu keinem SE-Ausfall, somit auch zu keinem Sammelbeleg. Unabhängig davon braucht es Mechanismen für die Ausfallserkennung zwecks Behebung und ggf. FON-Meldung, aber nicht, weil keine Belege mehr signiert werden konnten.

**Comment by christianPett** [comment]
Ich sehe das ein wenig anders: Mit dem Wechsel der SE ist es so eine Sache. Ich spreche von einer Registrierkasse (Serverlösung) mit mehreren Eingabestationen. Jeder der Eingabestationen hat einen Kartenleser. Stellen Sie sich einen gleichzeitigen Betrieb der Eingabestationen vor. Genau in diesem Moment wir der Kartenleser ausgesteckt oder auf einer Kasse bricht die Internet - Verbindung ab (Online - Signierung über A-Trust). Das bekommt die andere Eingabestation nicht mit und verkauft munter weiter.
Das Problem liegt nun in der Reihenfolge der Belegeausgabe im DEP, da die Belegevergabe unabhängig von der SE ist.

>>Der Sammelbeleg dient letzten Endes dazu, um Start und Ende des Ausfalls der >>Sicherheitseinrichtung festzuhalten.
Richtig, aber diese Validierung sollte nur mit genau dieser SE notwendig sein. D.h. ein Ausfall einer SE sollte keinen Einfluss auf die anderen SEs haben.

**Comment by ErichFreitag** [comment]
OK, schauen wir ob ich sie richtig verstanden habe:

Wenn sie SE-Einheiten haben/hätten, die zentral ansprechbar sind, können sie ja beliebig wechseln und es passiert nichts.

Wenn Sie SE-Einheiten pro Eingabestation haben/hätten und die nicht gegenseitig verwendet werden können und sie ein zentrales DEP haben dann haben sie wohl ein Problem mit den Belegreihenfolgen und mit dem Zusammenhang in einem Sammelbeleg, ja.

Wenn ich das salopp formulieren darf: da entsteht durch die Architektur ein Problem. Das was kritisch ist (nämlich das DEP = Kasse plus Belegnummern-Verwaltung) liegt zentral (womit bei Verbindungsausfall die Kassen/Eingabestationen nicht mehr verwendet werden können), das was unkritisch ist (die SE-Einheiten) liegen lokal (wo bei Ausfall weitergearbeitet werden kann).

Mögliche Auswege können z.B. sein:
- sie führen ein DEP pro Eingabestation (also mit je einer eigener Kassen-ID - spricht ja nichts dagegen)
- sie zentralisieren die SE-Einheiten (damit erreichen sie Ausfallsicherheit und eventuell load balancing etc.)
- sie führen pro Eingabestation eigene Belegnummernkreise

**Comment by christianPett** [comment]
Sie haben das Problem richtig erkannt.
Unsere Software ist eine klassische Client - Server Installation für CRM, die nun auch als Registrierkasse dienen soll. Wir wollten eigentlich auf jeder Eingabestation einen Kartenleser installieren (Grund: Ausfallssicherheit). Was wir nicht wollen sind dezentrale DEPs bzw. verschiedenen Belegnummernkreise. Wahrscheinlich kommen wir nicht an einer zentralen SE-Einheit herum (wäre dann ein Dienst-Applikation auf dem Server). 
Obwohl mir eigentlich immer noch nicht der verplichtende Nullbeleg / Sammelbeleg für unterschiedliche SE-Einheiten in den Kopf will :-) .

**Comment by ErichFreitag** [comment]
Dezentrale DEPs - OK - wie gesagt ist das halt der kritische Punkt bei einem Ausfall, z.B. bei Verbindungsausfall. Andere machen lokale DEPs und synchronisieren diese mit einem zentralen DEP.

Verschiedene Belegnummernkreise - auch OK, wenngleich es z.B. genügen würde, eine ID der Eingabestation mit einem Bindestrich o.ä. voranzustellen (und diese auch entsprechend zu verwalten, klar) - freie Entscheidung.

Was ihnen noch bleibt ist ein zwar zentrales DEP, das sie aber - wie soll ich sagen - virtuell für mehrere Kassen (= Eingabestationen in diesem Fall) führen - also wie beispielsweise in Issue https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/81 beschrieben. Dann könnten sie auch Einzelausfälle von SEs korrekt in einem zugeordneten Sammelbeleg abbilden.

Ich kenne jetzt ihre Details nicht, aber eine SE pro Eingabestation zu verwenden erhöht nicht zwangsläufig die Ausfallsicherheit, weil sie am Ende mehr Komponenten haben und sich die MTBF (mean time between failure) dadurch nicht verbessert. Die wird nur besser, wenn die SEs redundant sind, also wahlweise angesprochen werden können. Also wie von ihnen beschrieben z.B. als Dienst am Server.

Oder sie überlegen (je nach Qualität der Internet-Verbindung, ...) ernsthaft eine Online-Signierung (z.B. zentrales HSM) - die Preise kommen langsam in attraktive Größenordnungen und sie haben eine garantierte Verfügbarkeit. Wie erwähnt - die SE ist nicht die kritische Komponente für einen Kassen-Weiterbetrieb bei einem Ausfall.

**Comment by lonelypbdev** [comment]
Guten Tag,
nachdem die Frage in diesem Issue ja noch nicht gekärt ist und ich mich momentan mit der selben Thematik konfrontiert sehe, hänge ich mich hier einfach mal an.

Auch bei mir sieht das Standard-Installationsszenario so wie bei christianPett aus. 
Ich fasse zusammen:
- Client-Server-Lösung
- Eine Registrierkasse (= 1 DEP, 1 Kassen-ID) in Datenbank am Server
- 2 Eingabestationen mit je einer lokalen Signaturkarte.
- Es werden gleichzeitig / wechselseitig Belege erstellt und plötzlich fällt eine Signaturkarte aus

In der beiliegenden Excel-Tabelle habe ich versucht dies beispielhaft darzustellen.

Die Kernfrage ist ja, wann der Nullbeleg nach Wiederinbetriebnahme der ausgefallenen Signaturkarte erstellt wird.

Meiner Meinung nach gibt es 2 Möglichkeiten:

Möglichkeit 1: Sobald eine Signatur (egal von welcher Signaturkarte) erfolgreich erstellt werden kann, wird ein Nullbeleg erstellt der den Ausfall aufhebt.

Möglichkeit 2: Sobald die ausgefallene Signaturkarte wieder funktionsfähig ist, löst diese den Nullbeleg aus und hebt somit den Ausfall GENAU DIESER Signaturkarte auf. 
Sprich jede Signaturkarte arbeitet für sich autonom, in Bezug auf die Wiederaufnahme.

Ich denke, dass nur Möglichkeit 2 Sinn macht (sonst würden Nullbelege mehrfach erstellt werden (sh. Excel-Tabelle Beispiel 3)

Jedoch meldet dass Prüftool folgende Meldung, wenn eben ein "normaler" Beleg auf einen Beleg mit "Sicherheitseinrichtung ausgefallen" folgt.
Hinweis: dieses Beispiel habe ich mit nur einer Signaturkarte erstellt (da ich momentan keine zweite habe). Da wäre die Meldung ja richtig ...

"verificationResultDetailedMessage" : "Ein signierter Beleg, bei dem es sich nicht um einen Nullbeleg handelt, folgt auf einen unsignierten Beleg. P
er Definition muss nach dem Ausfall der Signatureinrichtung ein signierter Nullbeleg als Sammelbeleg folgen und damit die Wiederinbetriebnahme markier
en."

Danke an alle, die sich die Mühe machen, meinen Ausführungen hier zu folgen!

[Nullbeleg nach Ausfall SEE.xlsx](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/515732/Nullbeleg.nach.Ausfall.SEE.xlsx)

**Comment by areiter** [comment]
@lonelypbdev Vl. übersehe ich etwas, aber aus meiner Sicht, der einzige Grund warum ich mehrere "Signaturkarten" parallel auf ein DEP loslasse ist, dass ich bei Ausfall auf eine andere wechseln kann. 
Argumente wie "load-balancing" zählen da bei lokalen Sicherheitseinrichtungen nicht. Ich muss ohnedies warten bis die Signatur abgeschlossen ist.
Wenn also nur eine Karte ausfällt, was sprich dagegen den Beleg sofort mit der anderen, noch intakten Karte zu erstellen?

Außerdem ist es meiner Ansicht nach  im Erlass durchaus geregelt:

> Bei einer Zuordnung mehrerer Signatur- bzw. Siegelerstellungseinheiten zu einer oder mehreren  Registrierkassen kann dies auch zu einem späteren Zeitpunkt (nach einem der folgenden Belege und dem Erkennen der wiederhergestellten  Funktionsfähigkeit der Signatur- bzw. Siegelerstellungseinheit) erfolgen. Aus dem Beleg muss der Beginn und das Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit (zB: durch Angabe der jeweiligen laufenden Nummer) hervorgehen.

**Comment by lonelypbdev** [comment]
Vielen Dank für die schnelle Antwort!

Bezüglich Anzahl der Signaturkarten stimme ich nicht zu. Im von mir beschriebenen Szenario hat einfach der Arbeitsplatz (physischer PC) eine lokale Karte, weil das die - banal ausgedrückt - billigste und einfachste Lösung ist als ein Server-seitiger Signaturkarten-Pool. 
Ich beabsichtige auch kein Load Balancing, Failover oder ähnliches. 

Und für 1 DEP spricht eben auch die Einfachheit (1 Inbetriebnahme, 1 Nummernkreis, 1 DEP-Export, 1 Buchhaltungsübergabe, ...).

Aus der Stelle im Erlass werde ich auch nach dem dritten Mal lesen nicht schlau. Das würde ja bedeuten, dass der Nullbeleg entweder nach dem letzten "ausgefallenen" Beleg ODER nach dem ersten "wieder signierten" Beleg erstellt werden kann. - Das Prüftool duldet das aber nicht. 
Und was mit "auch zu einem späteren Zeitpunkt ..." gemeint ist verstehe ich leider auch nicht.

**Comment by areiter** [comment]
Ich gebe ihnen Recht, kommt sicher auf die Software Architektur bzw. Struktur an.

Würde das so interpretieren dass der Sammelbeleg, im Fall von mehreren Signatureinrichtungen, von der vormals ausgefallenen Signatureinrichtung signiert werden muss sobald diese wieder verfügbar ist. Dazu wäre es nur logisch die selben Regeln wie bei nur einer vorhandenen Signatureinrichtung anzuwenden. Also entweder der erste oder zweite (mit vormals ausgefallener Sicherheitseinrichtung) signierte Beleg nach dem Ausfall muss signiert sein.

**Comment by ErichFreitag** [comment]
@lonelypbdev - sie handeln sich damit wie oben ein Problem ein, das aus der Architektur entsteht.

Wenn sie kein Failover verwenden und alles in einem DEP speichern können sie die geschriebene Anforderungen nicht erfüllen, weil sie den Ausfall einer von zwei Sicherheitseinrichtungen und den zugeordneten Sammelbeleg in nur einem DEP nicht abbilden können.

Auch bei der Inbetriebnahme der Kasse und beim Jahresbeleg werden sie ein Problem bekommen, weil sie die Prüfungen des Zertifikats beim Startbeleg und beim Jahresbeleg nur mit einer Sicherheitseinrichtung durchführen (können). 

Als Ausweg ohne zentrale SE-Einheit(en) könnte dienen, dass sie zwei virtuelle Kassen führen, wo sie pro Datensatz noch die ID der Eingabestation hinzufügen. Das sollte einfach möglich sein und löst alle (?) Probleme.

Betreff Sammelbeleg: die RKSV § 17 Abs. 4 sagt aus "Nach Wiederinbetriebnahme der Signatur- bzw. Siegelerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern". 

Ein Zeitpunkt dafür ist präzise nicht herauszulesen. Sinnvollerweise würde entsprechend der Sammelbeleg VOR dem ersten Beleg nach Wiederverfügbarkeit erzeugt werden, weil damit die Reihenfolge eindeutig ist.

Der Erlass vom 04.08.2016 ergänzt: "Der nach dem Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit gemäß § 17 Abs. 4 RKSV erforderliche Sammelbeleg ist unmittelbar nach dem letzten Beleg bei ausgefallener Signatur- bzw. Siegelerstellungseinheit bzw. nach dem ersten Beleg bei
wieder hergestellter Signatur- bzw. Siegelerstellungseinheit zu erstellen".

Also auch hier unmittelbar nach dem letzten Beleg bei Ausfall, aber jetzt auch "bzw. (im Sinne von oder) nach dem ersten Beleg bei Wiederverfügbarkeit" (das ist ablauftechnisch ein wenig einfacher).

Mit "Bei einer Zuordnung mehrerer Signatur- bzw. Siegelerstellungseinheiten zu einer oder mehreren Registrierkassen kann dies auch zu einem späteren Zeitpunkt (nach einem der folgenden Belege und dem Erkennen der wiederhergestellten Funktionsfähigkeit der Signatur- bzw. Siegelerstellungseinheit) erfolgen" ist wohl wie von @areiter angeführt gemeint, dass sie zwischenzeitlich mit einer anderen SE-Einrichtung (mehrere) arbeiten und irgendwann erkennen, dass die ausgefallene SE-Einheit wieder funktioniert. 

Welche der Möglichkeiten das Prüftool erlaubt mögen bitte @pteufl o.a. präzisieren.

**Comment by lonelypbdev** [comment]
Danke für die ausführliche Antwort!

Ich glaube (hoffe!) nicht das die Inbetriebnahme bei diesem Fall ein Problem ist, denn das läuft ja so:

1) Registrierung Signatureinrichtung 1 bei FOn
2) Registrierung Signatureinrichtung 2 bei FOn
3) Registrierung Registrierkasse 1 bei FOn
4) Startbeleg erzeugen, mit einer der beiden Signatureinrichtungen signieren und Beleg bei FOn prüfen.

Damit ist die Registrierkasse betriebsbereit. 

Dabei ist es ja unerheblich, ob die beiden Sig.einrichtungen nun per USB an 2 Rechnern oder als Pool an einem Server hängen. FOn kriegt davon nichts mit und beide Sig. sind verwendbar.
Beim Jahresbeleg verhält es sich ähnlich.

Wenigstens ist mir jetzt klar, warum der Nullbeleg vor oder nach dem ersten Beleg nach Wiederaufnahme erstellt werden darf. (Wurde nachträglich im Erlass geändert, weil sonst die Prüfung ob eine Signatureinrichtung funktioniert vor dem Beleg gemacht werden müsste und dies ablauftechnisch aufwändiger wäre).

Nur das Prüftool arbeitet halt momentan anders. Hier hoffe ich ebenfalls auf Antworten von @pteufel.

Ich werde den Test mit 2 Signatureinrichtungen durchführen, und von den Ergebnissen hier berichten.

Schönes Wochenende!

**Comment by ErichFreitag** [comment]
@lonelypbdev - was halt bleibt ist, dass mit nur einer Kasse und nur einem Beleg nicht geprüft werden kann, ob die zweite SE-Einheit korrekt registriert und zugeordnet ist. Was da bei der Prüfung in Finanz-Online passieren wird ist vielleicht auch noch ein Thema - beispielsweise wenn sie den Startbeleg mit der einen und den Jahresbeleg mit der zweiten SE-Einheit erzeugen. 

Auch - wie und wo erzeugen sie denn Monats- und Jahresbelege - automatisch? Wenn ja wo und wie? Auf einer "Master"-Eingabestation? Oder zentral, wobei die SE-Einheiten aber dezentral sitzen?

Ich kenne das Detailverhalten der FON-Prüfung nicht, ich gebe es nur zu bedenken. Vielleicht wollen sie das in die Tests mit einbeziehen.

Ebenso ein schönes Wochenende!

**Comment by asitplus-pteufl** [comment]
Das Prüftool wird mit 1.0 die Sammelbelegprüfung nach dem Ausfall einer Signatureinrichtung genau so behandelt wie es im Erlass definiert ist (siehe 3.6.1). 

Auszug aus dem Erlass:
Bei Ausfall der Signatur- bzw. Siegelerstellungseinheit ist gemäß §§ 17 Abs. 4 und 7 RKSV vorzugehen. Der nach dem Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit gemäß § 17 Abs. 4 RKSV erforderliche Sammelbeleg ist unmittelbar nach dem letzten Beleg bei ausgefallener Signatur- bzw. Siegelerstellungseinheit bzw. nach dem ersten Beleg bei wieder hergestellter Signatur- bzw. Siegelerstellungseinheit zu erstellen. Bei einer Zuordnung mehrerer Signatur- bzw. Siegelerstellungseinheiten zu einer oder mehreren Registrierkassen kann dies auch zu einem späteren Zeitpunkt (nach einem der folgenden Belege und dem Erkennen der wiederhergestellten Funktionsfähigkeit der Signatur- bzw. Siegelerstellungseinheit) erfolgen. Aus dem Beleg muss der Beginn und das Ende des
© Bundesministerium für Finanzen Seite 40
40 von 95
Ausfalles der Signatur- bzw. Siegelerstellungseinheit (zB: durch Angabe der jeweiligen laufenden Nummer) hervorgehen.

**Comment by asitplus-pteufl** [comment]
Als Ergänzung: Die aktuelle Version des Prüftools setzt nur eine der Varianten um (Sammelbeleg muss unmittelbar nach Beleg mit ausgefallener Sicherheitseinrichtung kommen). D.h. DEPs die jetzt schon korrekt angezeigt werden, bleiben natürlich korrekt. Es werden nur die beiden weiteren Varianten die im Erlass definiert sind akzeptiert werden.

**Comment by lonelypbdev** [comment]
Ich möchte von meinen neuesten Erkenntnissen berichten:

Ich habe 2 Signaturkarten in Betrieb genommen und damit den oben beschriebenen Fall getestet und komme zu 
folgenden Schlüssen:

1) Der Beleg, der dem letzen ausgefallen signierten Beleg unmittelbar folgt, muss ein signierter Nullbeleg sein. 
2) Dabei ist es UNERHEBLICH, mit welcher Signaturkarte der Nullbeleg signiert wird.

Meine Schlussfolgerung: Ein signierter Nullbeleg hebt sozusagen nicht den Ausfall einer bestimmten Signaturkarte auf sondern vielmehr die Signierfähigkeit der gesamten Registrierkasse!

Ich habe meine Testreihe angehängt, da sieht man sehr schön, dass wenn eine Signaturkarte (auf einem Arbeitsplatz) ausfällt, und beide
Arbeitsplätze munter weiter Belege erstellen, dass laufend Nullbelege entstehen.

Ob dass im Sinne des Erfinders ist wage ich zu bezweifeln, aber genau so nimmt das Prüftool das DEP-Journal anstandslos an!

Vielleicht können diese "Erfinder" noch mal über diese Problematik nachdenken und eventuell etwas dazu sagen. 

Bekräftigt sehe ich mein Installationsszenario auch durch die Relationendarstellung (RKSV-Detailfragendokument Kapitel 1.2. Relationen / Abbildung 1).
![nullbeleg nach ausfall](https://cloud.githubusercontent.com/assets/20300542/19311295/0a6e9554-908e-11e6-85ad-cb5cfa54729c.jpg)

[ks_dep_3_1 _mod.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/524577/ks_dep_3_1._mod.json.txt)
[ks_qr_3_1.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/524576/ks_qr_3_1.json.txt)

**Comment by asitplus-pteufl** [comment]
Die Sicherheitseinrichtung bezieht sich nicht nur auf die Signatureinrichtung. Im Prinzip sagt der Sammelbeleg am Ende aus, dass jetzt wieder normal gearbeitet werden kann. Hier ist es unerlässlich mit welcher Sig-Einrichtung signiert wurde. Damit ist ihr Log technisch vollkommen richtig.
Zu organisatorischen Themen (z.B. wird so etwas bei einer Prüfung akzeptiert) kann A-SIT Plus keine Aussagen machen. Ich kann das Thema aber ans BMF weiterleiten.
