### ISSUE TITLE
Welche Zertifikats-Seriennummer bei Signatureinheitausfall

### ISSUE THREAD

**Issue by hfrueh** [a-sit-plus/at-registrierkassen-mustercode#136]
Folgendes Szenario:
Es existieren 2 Signatureinheiten mit unterschiedlichen Zertifikatsseriennummern, die beide für eine Registrierkasse arbeiten. Es fallen beiden Signatureinheiten aus. Die Belege werden dann mit dem Hinweis "Sicherheitseinrichtung ausgefallen" signiert.

Welche Zertifikatsseriennummer ist in diesem Fall zu hinterlegen? Ist das egal? Oder sollte diese dann evtl. sogar leer sein?

**Comment by ErichFreitag** [comment]
Siehe Issue https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/103 und weitere.

**Comment by hfrueh** [comment]
Danke!
