### ISSUE TITLE
Verwendung des Prüftools

### ISSUE THREAD

**Issue by euroCIS** [a-sit-plus/at-registrierkassen-mustercode#137]
Das regkassendemo lässt sich ausführen: java -jar regkassen-demo-0.7.1.jar -o OUTPUT_DIR -v -l 8

dann werden die files qr-code-rep-file.json und  cryptographicMaterialContainer.json in das Hauptverzeichnis kopiert in dem auch die files regkassen-demo-0.7.1.jar und regkassen-verification-receipts-0.7.1.jar liegen.

dann wird ausgeführt: java -jar regkassen-verification-receipts-0.7.1.jar -i qr-code-rep-file.json cryptographicMaterialContainer.json -o OUTPUT_DIR

dies ergibt die Fehlermeldung "no crypto material container file provided"
auch der explizite Pfad "C:\Temp\regkassen-demo-0.7.1\cryptographicMaterialContainer.json" ändert daran nichts. Wo liegt der Fehler?

**Comment by ErichFreitag** [comment]
Da fehlt wohl das "-c" vor der Pfadangabe.

**Comment by euroCIS** [comment]
ja mit -c läuft das tool. Im file cryptographicMaterialContainer.json gibt es den wert "signatureCertificateOrPublicKey" was ist das? woher bekomme ich den richtigen wert?

**Comment by asitplus-pteufl** [comment]
Bitte lesen Sie da README. Es wird dort auf alle relevanten Informationen verwiesen.

Readme, Starseite: https://github.com/a-sit-plus/at-registrierkassen-mustercode/

bzw. das im README verlinkte Dokument: https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.2-DOK/2016-09-05-Detailfragen-RKSV-V1.2.pdf

**Comment by smtm** [comment]
Sehe ich das richtig:  Im File in /example-output-1.0.0/closed system/TESTSUITE_TEST_SZENARIO_1/dep_export.json im Feld   "Belege-kompakt" : [ "eyJhbGciOiJFUzI1N.... ist der verschlüsselte Inhalt aus der Datei TESTSUITE_TEST_SZENARIO_1.json?

Wenn ja, kann man das Prüftool auch verwenden um die DEP Inhalte auch ohne Verschlüsselung einzuspielen. Mir geht es in diesem Schritt darum um sicherzustellen dass Feldnamen und die Struktur korrekt ist?

**Comment by areiter** [comment]
`TESTSUITE_TEST_SZENARIO_1.json` definiert ein Testszenario. Im Wesentlichen eine Belegabfolge.

Sofern von ihrer Software unterstützt liefern sie ihrer Software `TESTSUITE_TEST_SZENARIO_1.json` und die entsprechenden Belege werden erzeugt. Am Schluss sollte dann ein DEP export rauskommen.
Im DEP ist (außer dem Umsatzzähler) nichts verschlüsselt. Die von ihnen angesprochenen Werte sind die signierten Belege in kompakter JWS Repräsentation. Die 3 Teile (getrennt durch einen Punkt) sind jeweils Base64URL kodiert, hat aber nichts mit Verschlüsselung zu tun.

Für neue FRagen bitte neue Issues aufmachen, sonst leidet die Übersichtlichkeit schon sehr.

**Comment by smtm** [comment]
Danke für die Pointers. Mir war der Fluss der Daten in das Prüftool und was zurückkommt noch nicht ganz klar.
