### ISSUE TITLE
Protokollierung Änderungen am Kassensystem

### ISSUE THREAD

**Issue by giemes** [a-sit-plus/at-registrierkassen-mustercode#138]
Eine generelle Frage: es ist ja vorgeschrieben alle Änderungen an der Kassensoftware (Updates der Software oder Änderungen von Einstellungen an der Kassa) auch zu protokollieren und exportieren.

Wie/Wo ist denn der export gemeint?
a) Ins DEP integrieren in einen eigenen "Hauptblock" (so wie "Belege-Gruppe" oder innerhalb der Belege-Gruppe)
b) generell als eigene zB: txt-Datei exportieren
c) andere Lösung?

Danke!

lGG

**Comment by ErichFreitag** [comment]
Aus RKSV-Sicht ist das nur erforderlich, wenn sie ein geschlossenes Gesamtsystem betreiben. Was meinen sie mit exportieren?

**Comment by giemes** [comment]
Nein kein geschlossenes Gesamtsystem (wenn auch eine Integration in Buchhaltung oder vorgelagerte Faktura besteht).

Sorry - hab das verwechselt mit der KRL 2012, Kassenrichtlinie 2012 - hat nix mit DEP zu tun.
