### ISSUE TITLE
Sammelbeleg nach Erlass vom 4. Aug.

### ISSUE THREAD

**Issue by aunterlu** [a-sit-plus/at-registrierkassen-mustercode#139]
Im Erlass vom 4. Aug. steht im Kapitel 3.6.1 (Seite 40) zum Sammelbeleg folgendes:
"Aus dem Beleg muss der Beginn und das Ende des Ausfalls der Signatur- bzw. Siegelerstellungseinheit (zB: durch Angabe der jeweiligen laufenden Nummer) hervorgehen."

Ist das jetzt so zu verstehen, dass nicht mehr alle Belegnummern mit dem jeweiligen maschinenlesbaren Code aufgelistet werden müssen (was ja beim Ausdruck auf einem Bondrucker sehr lang werden kann)?

**Comment by ErichFreitag** [comment]
Ja, das heißt es - abgesehen davon, dass der Sammelbeleg ja nicht ausgedruckt werden muss und dass nur die Inhalte des maschinenlesbaren Codes enthalten sein mussten (und nicht der maschinenlesbare Code selbst).

**Comment by aunterlu** [comment]
Hallo Freitag, danke für dein Kommentar. Dann sind wir zumindest zu zweit mit der Interpretation ;)

PS: Im RKSV § 17 steht: "... als handelsübliche Bezeichnung der maschinenlesbare Code des jeweiligen Barumsatzes ... einzutragen sind"

**Comment by ErichFreitag** [comment]
Ja, das eine ist Gesetz und das andere ist ein Erlass, der das Gesetz ohne rechtsverbindliche Wirkung interpretiert und präzisiert, nachdem sich aber die Behörden und viele andere orientieren (werden). Sie müssen da immer ein vernünftiges Mass an Pragmatismums, Vernunft und Sinn der RKSV walten lassen.

Es macht ja auch Sinn, nur den Beginn und das Ende des Ausfalls im Sammelbeleg zu dokumentieren, da die Belege dazwischen ohnedies auch im DEP enthalten sind. 

Alternativ - beispielsweise bei unübersichtlichen Belegnummernkreisen und Mischungen von fiskalen und non-fiskalen Belegen - können auch die betroffenen Belegnummern (= signierpflichtigen Barumsätze) während des Ausfalls eingetragen werden - es heißt ja nur "z.B. durch Angabe der jeweiligen laufenden Nummer". Die Umsetzung ist also so zu entscheiden, dass der Sammelbeleg einen Ausfall der Sicherheitseinrichtung vernünftig und leicht nachvollziehbar dokumentiert.
