### ISSUE TITLE
Rechtschreibfehler im SimpleDemo.java :-)

### ISSUE THREAD

**Issue by DFeckter** [a-sit-plus/at-registrierkassen-mustercode#14]
deactivateTraningReceipts  das "i" fehlt beim Training. 

Sorry für meine Überkorrektheit. :-P
(Normalerweise bin ich derjenige der sehr viele Rechtschreibfehler macht...)

**Comment by pteufl** [comment]
vielen dank, 
Mit 0.5 sind alle Features im Großen und Ganzen vorhanden. Die weiteren Versionen bis 1.0 werden sich dann ganz auf QS konzentrieren (eben auch auf die im Readme genannten Testfälle etc.)
