### ISSUE TITLE
Stornobeleg _U1RP

### ISSUE THREAD

**Issue by DrBGM** [a-sit-plus/at-registrierkassen-mustercode#141]
**Stand-Umsatz-Zaehler-AES256-ICM:** 

Beim Stornobeleg wird der Umsatzzähler in der Kasse adaptiert, der verschlüsselter Wert wird aber nicht im Beleg gespeichert. Stattdessen wird der Wert U1RP (Ergebnis BASE64-Kodierung STO) im Feld gespeichert.

Das heißt der Umsatzzähler ist leer, obwohl eine Veränderung im Umsatz stattfindet?

Dann ergibt sich eine Umsatzveränderung erst auf dem nächsten "normalen Beleg".

Angenommen:

Kassastand "1" : 1000,-
Stornobuchung: 70,-
neuer Kassastand "2" : 930,- (wird nicht mitgeschrieben, sondern "U1RP")

normale Buchung: 30,-
neuer Kassastand "3": 960,- (wird wieder mitgeschrieben)

Kassastand 3 < Kassastand 1

aber laut Anleitung wäre alles OK?

**Comment by ErichFreitag** [comment]
Ja, so ist das.

Der Umsatzzähler ist ja nicht leer. Intern wird er weitergeführt, im maschinenlesbaren Code steht U1RP. Und über die Einzelbeträge lässt er sich ja bei Bedarf nachvollziehen. Sie könnten sonst beispielsweise Gutschriften nicht von Stornos unterscheiden.

**Comment by DrBGM** [comment]
Vielen Dank für die schnelle Antwort. Das ist jetzt klar :-)

Sind Gutschriften (unbar) - also wenn der Kunde Ware retourniert und eine Gutschrift erhält, die er beim nächsten Einkauf gegenrechnen kann - denn überhaupt registrierkassenpflichtig? Es erfolgt ja keine Geldbewegung?

(Stornos sind ja einfach nur Rechnungen mit verkehrtem Vorzeichen, also einer minus Geldbewegung in der Registrierkassa.)

**Comment by ErichFreitag** [comment]
Das kommt darauf an :-) Die Geldbewegung alleine ist nicht das Kriterium (z.B. sind Bareingänge oder Barentnahmen keine Barumsätze).

Auf den ersten Blick unterscheiden sich Gutschrift und Storno nicht, auf den zweiten Blick schon.

Ein Storno macht einen durchgeführten Geschäftsfall (oder Teile davon oder mehrere gleichzeitig) rückgängig. Das wird meist bei einer Fehlbuchung oder bei eine Falschausstellung der Fall sein. In diesem Fall dürfen nur stornierte Positionen auf einem Beleg sein. Bei einem Storno ist es auch von Relevanz, dass sie nachvollziehen können, was storniert wurde.

Zwei Beispiele dazu aus dem Erlass vom 04.08.2016:
4.4. und 6.7.1.2 sie können Belege für mobil getätigte Umsätze vorab ausstellen und nicht getätigte Barumsätze danach stornieren.

2.4.7 Becherpfand: Wenn der Becher zurückkommt können sie einen negativen Umsatz erfassen (Rückerstattung des Pfands) oder - wenn sie einen Bezug zum Verkauf herstellen können - den ursprünglichen Umsatz stornieren.


Eine Gutschrift wird z.B. in Folge eines Mangels an einem Produkt oder an einer Lieferung nachträglich ausgestellt. Soll eine Preisminderung unmittelbar im Zuge des Geschäftsfalles zum Tragen kommen wird eher ein günstigerer Preis oder ein Rabatt verwendet werden.

Wenn die Gutschrift als Wertgutschein ausgestellt wird, der bei einem nächsten Einkauf eingelöst werden kann, ist sie nicht RKSV-pflichtig, da sie keinen Barumsatz darstellt und den Umsatz zunächst nicht verändert. Man darf es aber signieren (was zwecks Nachvollziehbarkeit durchaus Sinn macht).

Wird die Gutschrift hingegen bar ausbezahlt ist es ein Barumsatz und RKSV-pflichtig. Es wird ja der Umsatz in diesem Moment vermindert, der Geschäftsfall an sich bleibt aber bestehen.

Wird die Wertgutschein-Gutschrift eingelöst ist es ein (negativer) RKSV-pflichtiger Barumsatz ähnlich einem Rabatt - ein Beispiel dazu sehen sie im A-SIT-Dokument Detailfragen unter 2.5.1.

**Comment by DrBGM** [comment]
Vielen Dank für die schnelle Antwort! 

Sehr aufschlussreich :-)

Danke auch für die Idee der Signierung von Wertgutscheinen zwecks Nachvollziehbarkeit.

**Comment by aunterlu** [comment]
"Gutschrift als Wertgutschein" ist schon RKSV-pflichtig. Ein Wertgutschein ist wie Bargeld zu betrachten. Eine (negative) Leistung wird mit Herausgabe von Bargeld (oder Wertgutschein) bezalt. 
Nur wenn Bargeld gegen Wertgutschein (Verkauf eines Gutscheins) oder Wertgutschein gegen Bargeld getauscht werden, dann ist es kein Barumsatz (Verbindlichkeitentausch). 

Ich merke es mir am leichtesten indem ich daraus zwei Vorgänge mache. 
1. ich zahle die Gutschrift dem Kunden bar aus (RKSV-pflichtig)
2. der Kunde tauscht dann sein Bargeld gegen einen Wertgutschein.
--> ich zahle die Gutschrift mit Wertgutscheinen aus, ist auch RKSV-pflichtig

Einlösen eines Wertgutscheins:
1. ich tausch dem Kunden den Wertgutschein in Bargeld um
2. der Kunde zahlt mit Bargeld die Ware 
--> RKSV-pflichtig

Kunde kauft einen Wertgutschein
1. Bargeld gegen Gutschein (Verbindlichkeitentausch --> nicht RKSV-pflichtig)

**Comment by DrBGM** [comment]
Hallo aunterlu,

Danke für die detaillierten Ausführungen.

ErichFreitag stellt jedoch das Gegenteil dar : 

> Wenn die Gutschrift als Wertgutschein ausgestellt wird, der bei einem nächsten Einkauf eingelöst werden kann, ist sie nicht RKSV-pflichtig, da sie keinen Barumsatz darstellt und den Umsatz zunächst nicht verändert. Man darf es aber signieren (was zwecks Nachvollziehbarkeit durchaus Sinn macht).

Sie schreiben:

> Ich merke es mir am leichtesten indem ich daraus zwei Vorgänge mache. 
> 1. ich zahle die Gutschrift dem Kunden bar aus (RKSV-pflichtig)

=> Das wäre ja dann auch ein normales Storno (also eine Rechnung mit verkehrtem Vorzeichen, also einer minus Geldbewegung in der Registrierkassa.)

> 2. der Kunde tauscht dann sein Bargeld gegen einen Wertgutschein.

=> Das wäre dann in meinen Augen zwar in weitesten Sinne ein Tausch, aber eigentlich ein "Kauf", der ganz normal wieder RKSV pflichtig ist. 

Sie schreiben auch:

> Kunde  kauft einen Wertgutschein
> 1. Bargeld gegen Gutschein (Verbindlichkeitentausch --> nicht RKSV-pflichtig)

Das sehe ich etwas anders. Der Kauf eines Wertgutscheines ist in meinen Augen schon RKSV pflichtig. Weil ja auch der Kassabestand sich verändert. Der Kunde hat ja einen "normalen Kauf" getätigt.

Oder irre ich mich jetzt ganz gewaltig?

Freue mich über jedwede Kommentare zu Klärung :-)

**Comment by asitplus-pteufl** [comment]
Der Vollständigkeit halber möchte ich hier als A-SIT Plus folgendes anmerken (siehe auch README auf der Startseite).

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html).

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.

**Comment by ErichFreitag** [comment]
@DrBGM - bitte ggf. neues Issue erstellen.

Der Verkauf eines Wertgutscheins ist nicht RKSV-pflichtig, siehe Erlass Punkt 2.4.10.1, weil lediglich ein Verbindlichkeitsnachweis.

**Comment by Flanelli** [comment]
Kein Ahnung ob ein Eintrag in ein geschlossenes Thema erlaubt ist aber ich schreib halt mal....
@DrBGM
wie schon ErichFreitag erläutert hat - ein WERTGUTSCHEIN ist nicht RKSV-pflichtig da der durch den Verkauf eines Gutscheines der eingenomme Betrag lediglich eine Verbindlichkeit dem Käufer bzw. dem Einlösenden darstellt und erst bei einem Einlöse der entsprechende Betrag eine Bareinnahme im Sinne des RKSV darstellt.

@ErichFreitag
Es gibt allerdings im Falle einer Refundierung von Warenrücknahmen nicht nur die Möglichkeit einer Bargeldlauszahlung oder einer Gutscheinausstellung sonden eben auch noch die Ausstellung einer GUTSCHRIFT und diese wäre dann wohl ebenso RKSV-pflichtig. 

Wie auch immer, ob Bargeld,, Gutschein oder Gutschrift "refundiert wird - es verringert den Gesamtumsatz in JEDEM Fall.

**Comment by ErichFreitag** [comment]
Danke - darum habe ich mich mit den meisten Unternehmen dahingehend verständigt, dass alles Richtung Kunde signiert wird. Das erspart die Gefahren der Komplexität und ändert an der Sache nichts. Was dann derzeit übrig bleibt (z.B. Wertgutschein Verkauf 0%, Einlösung xy%) ist noch komplex genug.

Übrigens wird gerade diskutiert, ob nicht doch alles in die Steuersätze kommen darf - siehe https://www.xing.com/communities/posts/steuerbetraege-laut-beispiel-aus-erlass-punkt-4-punkt-6-6-1012080196?comment=34679833 gegen Ende des Beitrags.
