### ISSUE TITLE
Was, wenn ein Fehler im DEP-Journal existiert?

### ISSUE THREAD

**Issue by lonelypbdev** [a-sit-plus/at-registrierkassen-mustercode#143]
Ich habe eine allgemeine Frage.

Die Prüfung eines DEP-Journals erfolgt ja immer nur bis zum Auftreten eines Fehler und bricht dann ab.

Nun wage ich zu behaupten, dass in jedem Kassensystem einmal ein Fehler auftreten kann, sprich ein fehlerhafter Beleg abgespeichert wird.
Ich gehen einfach mal vom simplen Programmfehler aus, der zB unter seltenen Umständen passiert, sei es die Verkettung, der Umsatzzähler, die kryptografische Gültigkeit oder ein anderer Fehler. 
Wenn man sich dieses Forum durchliest, erkennt man dass die Möglichkeiten Fehler zu machen (und sei es nur durch falsche Interpretation) erheblich ist bzw. ob überhaupt schon alle Fehlermöglichkeiten bedacht wurden.

Das Problem ist ja, dass man Fehler erst bei der Prüfung bemerkt, im Echteinsatz beim Kunden überhaupt erst, wenn sich jemand das DEP-Journal ansieht. Das könnte
ja auch nach Jahren erst der Fall sein ...

Mich würde daher interessieren:

1) welche Vorkehrungen man treffen soll um Fehler möglichst bald zu erkennen. (zB automatischer Prüflauf täglich).  Eigentlich wäre nur eine Prüfung nach jedem Beleg zielführend (was praktisch natürlich nicht geht).
   
2) Was macht man, wenn so ein Fall auftritt. Ist dann das ganze DEP-Journal unbrauchbar? Dann bleibt ja nur noch eine neue Kasse anzufangen?  Man hätte ja nach einem Fehler nie mehr die Möglichkeit die Konsistenz der späteren Belege zu prüfen.

**Comment by asitplus-pteufl** [comment]
Ich möchte Sie da auf die Ankündigung des BMF für das Prüftool V1.0.0, die nach Ihrem Issue veröffentlicht wurde verweisen (hier nur ein Auszug, bitte das Readme auf der Startseite beachten).

Das gegenständliche, im Auftrag des BMF erstellte, Prüftool ab Version 1.0.0 überprüft Format und Inhalt sowie Abfolge von Einzelbelegen in einem exportierten RKSV-Datenerfassungsprotokoll (RKSV-DEP) einer Registrierkasse auf Übereinstimmung mit den ab 1.4.2017 gültigen Vorgaben der RKSV. Die Prüfalgorithmen, die dabei zur Anwendung kommen, stimmen im Wesentlichen mit jenen überein, die auch für Einzelbelegüberprüfungen und RKSV-DEP-Überprüfungen des BMF herangezogen werden (z.B.: BMF Belegcheck-App). Dadurch, dass das gegenständliche Prüftool primär auf die Überprüfung der korrekten Implementierung ausgerichtet ist, kann es dazu kommen, dass das Prüftool etwas als fehlerhaft ausgibt, das bei der Behördenprüfung als fehlerfrei angesehen wird (z.B. nicht vorhandener Startbeleg bei der Überprüfung eines DEP-Ausschnittes).
