### ISSUE TITLE
Plausibilitätschecks für DEP

### ISSUE THREAD

**Issue by twisted-pear** [a-sit-plus/at-registrierkassen-mustercode#144]
Mir sind einige Situationen aufgefallen in denen das aktuelle Prüftool keinen Fehler meldet obwohl das naheliegend wäre:
* Wenn der JWS-Header nicht `{"alg":"ES256"}` ist.
* Wenn sich die Kassen-ID ändert (also z.B. der 1. Beleg die Kassa-ID `Cashbox-1` und der 2. `Cashbox-2` hat).
* Wenn im DEP auf einmal statt Zertifikatsseriennummern Key IDs verwendet werden (oder umgekehrt, z.B. 1. Beleg: `DEADBEEF`, 2.Beleg: `U:ATU12345678-K0`)
* Wenn sich die Länge des Umsatzzählers ändert.
* Wenn das Rechnungsdatum nicht aufsteigend ist (z.B. 1. Beleg am 5.2., 2. Beleg am 4.2.)

Sind DEPs in denen solche Fälle vorkommen zulässig oder nicht?

**Comment by asitplus-pteufl** [comment]
Vielen Dank für die Hinweise, die Punkte "Änderung der Kassen-ID", "Mischung GGS mit normalen System ==> Key-ID vs. Seriennummer" waren schon in der Planung für 1.0.0 und sind nun in den Prüfungen inkludiert.
Diese Punkte sind auch klar in der RKSV geregelt und nicht zulässig (da der DEP-Export ja pro Kasse ist und GGS und offenes System sowieso nicht vermischt werden können).

JWS-Header ist nicht inkludiert, da dies mit der Einzelbelegprüfung überprüft wird, dort wird immer davon ausgegangen dass kein JWS-Header vorhanden ist. Ein etwaiger Fehler würde dort erkannt werden.

Gegen eine Änderung der Länge des Umsatzzählers spricht eigentlich nichts (ob es sinnvoll ist, ist eine andere Frage), daher ist diese Prüfung nicht inkludiert.

Aufsteigendes Rechnungsdatum wird auch nicht überprüft, da dies in manchen Fällen vorkommen kann, die Reihenfolge ist ohnehin durch die Verkettung und die geforderte fortlaufende Belegnummer definiert.

**Comment by twisted-pear** [comment]
Vielen Dank für die Antwort.

**Comment by tomw1808** [comment]
@asitplus-pteufl 

hält das noch, wenn man dem BMF ein DEP übergibt?

> Aufsteigendes Rechnungsdatum wird auch nicht überprüft, da dies in manchen Fällen vorkommen kann, die Reihenfolge ist ohnehin durch die Verkettung und die geforderte fortlaufende Belegnummer definiert.
