### ISSUE TITLE
Prüftool DEP

### ISSUE THREAD

**Issue by SLMaWi** [a-sit-plus/at-registrierkassen-mustercode#145]
Sehr geehrte Damen und Herren!

Wir haben die Registrierung der Signatureinheit und Registrierkasse in FinanzOnline samt Scan des Startbelegs erfolgreich durchgeführt.
Nun sind wir beim Testen unseres DEP-Exports mittels Prüftool. Hier bekommen wir leider eine Fehlermeldung. Laut dem Prüftool konnte dem erste Kassenbeleg (Startbeleg) kein „Belegtyp“ zugeordnet werden. "Dem vorliegenden maschinenlesbaren Code kann kein bekannter Beleg-Typ zugeordnet werden." Zusätzlich hat laut dem Prüftool der entschlüsselte Umsatzzähler hat einen Wert ungleich 0." "Der Startbeleg hat aber schon einen Umsatz von 100."

Das kann theoretisch nicht der Fall sein, da der Umsatzzähler des Startbelegs für eine erfolgreiche Prüfung mittels Belegcheck-App gleich 0 sein muss, damit der IST-Wert des Umsatzzählers mit dem SOLL-Wert laut Definition des Startbelegs (=0) verglichen werden kann.

Was allerdings irritirend ist, ist, dass die Gesamtsumme der Belege vor Aktivieren des Manipulationsschutzes genau einen Umsatz von 100 ergeben.

Nun ist die Frage ob der Umsatzzähler möglicherweise in ein zweites Feld geschrieben wird, dass bei der Startbelegsprüfung mittels APP ignioriert aber bei der DEP-Prüfung mittels Prüftool geprüft wird.

Bitte um Info

Vielen Dank
Matthias Wimmer

**Comment by asitplus-pteufl** [comment]
Was meinen Sie mit "Was allerdings irritirend ist, ist, dass die Gesamtsumme der Belege vor Aktivieren des Manipulationsschutzes genau einen Umsatz von 100 ergeben."
Befinden sich im RKSV-DEP andere Daten vor dem Startbeleg?
Können Sie die DEP-Export Datei posten?

**Comment by SLMaWi** [comment]
Sehr geehrter Herr Teufl!

Nein, in der Export-Datei befinden sich keine anderen Belege vor dem Startbeleg.
Es gibt nur ein Formular, wo das DEP angezeigt werden kann. Dort stehen vor dem Startbeleg andere Belege, die in Summe einen Umsatz von 100 ergeben.

Hier die Export-Datei:
[test.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/536600/test.txt)

**Comment by asitplus-pteufl** [comment]
Können Sie mich bitte direkt kontaktieren? peter.teufl@a-sit.at
