### ISSUE TITLE
Sammelbeleg nach "Sicherheitseinrichtung ausgefallen"

### ISSUE THREAD

**Issue by vejo** [a-sit-plus/at-registrierkassen-mustercode#146]
Im "Erlass zur Einzelaufzeichnungs-, Registrierkassen- und Belegerteilungspflicht" (auf findok.bmf.gv.at "Erlass des BMF vom 04.08.2016, BMF-010102/0029-IV/2/2016, BMF-AV Nr. 123/2016" gültig ab 04.08.2016) steht:
"Bei Ausfall der Signatur- bzw. Siegelerstellungseinheit ist gemäß §§ 17 Abs. 4 und 7 RKSV vorzugehen. Der nach dem Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit gemäß § 17 Abs. 4 RKSV erforderliche Sammelbeleg ist unmittelbar nach dem letzten Beleg bei ausgefallener Signatur- bzw. Siegelerstellungseinheit bzw. nach dem ersten Beleg bei wieder hergestellter Signatur- bzw. Siegelerstellungseinheit zu erstellen."

Ich bin sehr froh darüber, dass der Sammelbeleg auch NACH dem ersten wieder erfolgreich signierten Beleg erstellt werden darf.
Das ist praxisgerecht, zumal ja die Erstellung des Sammelbelegs (incl. Signatur) etwas dauern kann.
Außerdem müsste sonst der bereits fertig signierte aktuelle Beleg zwischengepuffert, nach dem Sammelbeleg nochmals signiert und erst dann ins DEP gespeichert werden.

Die aktuelle Version des Prüftools 0.7.1 lässt aber diese Reihenfolge nicht zu:
"verificationResultDetailedMessage" : "Ein signierter Beleg, bei dem es sich nicht um einen Nullbeleg handelt, folgt auf einen unsignierten Beleg. Per Definition muss nach dem Ausfall der Signatureinrichtung ein signierter Nullbeleg als Sammelbeleg folgen und damit die Wiederinbetriebnahme markieren."

Wird das im Prüftool noch geändert?

**Comment by asitplus-pteufl** [comment]
ja, wird bei 1.0 enthalten sein. Die Version wird gerade im Detail getestet bzw. werden gerade noch kleine Bugfixes, Features hinzugefügt.

**Comment by vejo** [comment]
Danke für die rasche (und gute) Nachricht.

**Comment by vejo** [comment]
Eine Frage noch.

Es ist durchaus möglich, dass vereinzelt eine Signatur erfolgreich ist, die nächste aber schon wieder nicht.
Denkbar bei z.B. Signatur über HSM und instabiler Netzwerkverbindung oder im Lastbereich.
In diesem Fall könnte eine Belegsignatur erfolgreich sein, die nachfolgende - für den Sammelbeleg - aber in ein Timeout laufen.

Wie ist dieses Verhalten - im Sinne des Prüftools - abzubilden?
a) Sammelbeleg mit "Sicherheitseinrichtung ausgefallen", aber verkettet mit dem (signierten) Vorbeleg
b) Keinen Sammelbeleg ins DEP buchen und damit den vorherigen Ausfall der Sicherheitseinrichtung formal nicht beenden
In diesem Fall müsste nach der nächsten erfolgreichen Signatur der Sammelbeleg 'von Anfang an', also ohne Rücksicht auf den einzelnen signierten Beleg, erstellt werden.

**Comment by asitplus-pteufl** [comment]
A kann nicht stimmen, da ein Nullbeleg eine gültige Signatur vorweisen muss. Wenn Sie natürlich umgekehrt draufkommen, dass die Signatur doch wieder funktioniert brauchen Sie den erstellten Beleg nicht zu verwerfen sondern können danach den Nullbeleg erstellen.

B wäre technisch der richtige Fall. In dem Zusammenhang bitte das Readme von Prüftool V1.0.0 auf der Startseite dieses Projekts im Detail lesen, ich betone da folgende Ankündigung des BMFs hervor:

Das gegenständliche, im Auftrag des BMF erstellte, Prüftool ab Version 1.0.0 überprüft Format und Inhalt sowie Abfolge von Einzelbelegen in einem exportierten RKSV-Datenerfassungsprotokoll (RKSV-DEP) einer Registrierkasse auf Übereinstimmung mit den ab 1.4.2017 gültigen Vorgaben der RKSV. Die Prüfalgorithmen, die dabei zur Anwendung kommen, stimmen im Wesentlichen mit jenen überein, die auch für Einzelbelegüberprüfungen und RKSV-DEP-Überprüfungen des BMF herangezogen werden (z.B.: BMF Belegcheck-App). Dadurch, dass das gegenständliche Prüftool primär auf die Überprüfung der korrekten Implementierung ausgerichtet ist, kann es dazu kommen, dass das Prüftool etwas als fehlerhaft ausgibt, das bei der Behördenprüfung als fehlerfrei angesehen wird (z.B. nicht vorhandener Startbeleg bei der Überprüfung eines DEP-Ausschnittes).

**Comment by Alex1130** [comment]
Wodurch unterscheidet sich ein Sammelbeleg von einem Nullbeleg und woraus setzt sich das payload zusammen?

Während des Ausfalls der Signatureinheit wird

- der Umsatzzähler weiter gezählt 
- das DEP der mit nicht signierten Belegen weitergeführt header.payload.signature

wobei im payload in jeder Zeile der letzte gültige Signaturwert steht
und signature durch BASE64URL("Sicherheitseinrichtung ausgefallen") ersetzt wird?

Wie schaut das dann für den Sammelbeleg aus? Oder bekommt dann jeder ausgefallene Beleg einen eigenen Nullbeleg?
