### ISSUE TITLE
Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.

### ISSUE THREAD

**Issue by TheSecondStefOnGithub** [a-sit-plus/at-registrierkassen-mustercode#147]
Hallo,

wir haben das oben genannte Problem beim Erstellen der Prüfung für den Startbeleg. Ich habe mich bereits durch alle Issues gelesen welche das oben benannte Problem ebenfalls beschreiben, konnte aber leider keine Lösung finden.

Im Anhang finden Sie die dazu erstellten JSON Dateien. Vielen Dank im Voraus für jegliche Unterstützung.

MFG

[json.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/541601/json.zip)

**Comment by lonelypbdev** [comment]
Auf den ersten Blick würde ich sagen, sie müssen das Zertifikat das bei der Signierung verwendet wurde im dep-export.json beim Tag 'Signaturzertifikat' angeben. - mfg

**Comment by ErichFreitag** [comment]
Wenn ich den Eintrag richtig decodiert habe steht dort

"_R1-AT2_47_Startbeleg_2016-10-20T10:00:00_0,00_0,00_0,00_0,00_0,00_oVP9APt+_01069F333E9DDE65236842D957_MUiQVuCRbVk="

drinnen. Da fehlt als letztes Element noch die Signatur selbst.

**Comment by areiter** [comment]
@lonelypbdev Zertifikat ist im DEP export nicht zwingend nötig. Es reicht wenn es im cryptographic material container enthalten ist.

Kann @ErichFreitag nicht zustimmen, Signatur befindet sich bei kompakter JWS darstellung in drittem durch Punkt getrenntem Element. Ist im DEP Export korrekt abgebildet.

Ich denke sie sollten nochmals überprüfen, ob sie tatsächlich die Signatur auf Basis der richtigen Daten erstellen:
Hash von `eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl80N19TdGFydGJlbGVnXzIwMTYtMTAtMjBUMTA6MDA6MDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX29WUDlBUHQrXzAxMDY5RjMzM0U5RERFNjUyMzY4NDJEOTU3X01VaVFWdUNSYlZrPQ` erstellen, damit dann Signaturvorgang auslösen

**Comment by ErichFreitag** [comment]
Danke @areiter, hatte mich verschaut und verzählt und ziehe meinen Kommentar zurück.

**Comment by TheSecondStefOnGithub** [comment]
Hallo,
danke für die bisherige Hilfe, leider konnten wir das Problem bisher nicht knacken.  

Es ist auch unklar ob der Fehler schon beim Erstellen des Startbeleges oder erst beim Signieren auftritt?

Aus dem Startbeleg
_R1-AT2_58_Startbeleg_2016-10-24T11:36:05_0,00_0,00_0,00_0,00_0,00_PnDv5xi3_01069F333E9DDE65236842D957_YgjvD3dQwRE=

wird ein SHA256 Hash erstellt. Dieser wird dann über eine Globaltrustkarte signiert. Das Ergebnis der Funktion liefert ein 64stelliges byte Array.  Dieses wird Base64 codiert an den Startbeleg angehängt.

Der erwähnte Startbeleg enhält die ersten 8 Byte des verschlüsselten Umsatzzählers und die ersten 8 Byte der verschlüsselten Registrierkassennummer (GUID).

Bin für jede Hilfe dankbar.

MFG

**Comment by areiter** [comment]
> Aus dem Startbeleg
_R1-AT2_58_Startbeleg_2016-10-24T11:36:05_0,00_0,00_0,00_0,00_0,00_PnDv5xi3_01069F333E9DDE65236842D957_YgjvD3dQwRE=

Wie ich oben geschrieben habe, dürfen sie nicht nur den Hash aus dem Maschinenlesbaren Code erzeugen sondern des gesamten JWS Header + JWS Payloads: `eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl80N19TdGFydGJlbGVnXzIwMTYtMTAtMjBUMTA6MDA6MDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX29WUDlBUHQrXzAxMDY5RjMzM0U5RERFNjUyMzY4NDJEOTU3X01VaVFWdUNSYlZrPQ`

> Der erwähnte Startbeleg enhält die ersten 8 Byte des verschlüsselten Umsatzzählers und die ersten 8 Byte der verschlüsselten Registrierkassennummer (GUID).

Könnten sie mir erläutern was sie unter einer verschlüsselte Registrierkassennummer verstehen?

**Comment by TheSecondStefOnGithub** [comment]
Hallo,
in der Dokumentation wird auf Seite 42 der JWS-Header angesprochen. Der Base64 codierte Wert (eyJhbGciOiJFUzI1NiJ9) sollte an den Beleg angehängt werden? Also

eyJhbGciOiJFUzI1NiJ9_R1-AT2_58_Startbeleg_2016-10-24T11:36:05_0,00_0,00_0,00_0,00_0,00_PnDv5xi3_01069F333E9DDE65236842D957_YgjvD3dQwRE=
?

Zu Ihrer Frage
Der Starbeleg wird folgendermaßen erstellt
_R1-AT2_
NummerdesDEP_
Startbeleg_
Datum_
0,00_
0,00_
0,00_
0,00_
0,00_
EncryptedTurnover_
CertificateSerialnumber_
da noch keine vorhergehende Signatur die ersten 8 Byte der SHA256 gehashten Kassen ID im GUID Format.

Dieser String wird in ein byte Array eingelese und SHA 256 gehashed. Danach wird die Globaltrust Sign Funktion aufgerufen welche wir aus dem Globaltrust Beispielcode übernommen haben. 

Das Ergebnis der Globaltrus Funktion liefert ein 64stelliges byte Array. Dieses wird Base64 codiert an den oben angegebenen Beleg angehängt.

MFG

**Comment by asitplus-pteufl** [comment]
Es wird im Dokument der JWS-Standard referenziert. Ihre Vorgehensweise entspricht NICHT dem JWS-Standard. Bitte auf die Hinweise der Vorposter achten und am besten die Doku im Detail lesen bzw. einfach den Muster-Code anschauen (ist überall referenziert): 
https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-core/src/main/java/at/asitplus/regkassen/core/modules/signature/jws/ManualJWSModule.java

Achtung im JWS-Standard wird immer BASE64-URL Kodierung verwendet (nicht BASE64).

**Comment by TheSecondStefOnGithub** [comment]
Hallo,

danke für die Infos, wir konnten das Problem lösen.

Das Problem lag am fehlenden Header und an am BASE64URL Coding da wir hier BASE64 verwendet hatten.

MFG

**Comment by onnlinetool** [comment]
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw
