### ISSUE TITLE
Belege mit einem zeitlich realistischen Belegausstellungsdatum

### ISSUE THREAD

**Issue by aunterlu** [a-sit-plus/at-registrierkassen-mustercode#148]
Zum Testen verschiedener Szenarien, wie Erstellung des Jahresbelegs, Jahreswechsel, Kassenverhalten ab dem 1.4.2017 (keine Bonierungen ohne Signatur) müssen wir bei unseren Tests das Datum in die Zukunft setzen. Derzeit wird die Überprüfung des danach erstellten Datenerfassungsprotokolls mit folgender Meldung abgebrochen:

 "verificationResultDetailedMessage" : "Eine Prüfung des Belegs war nicht möglich, da nur Belege mit einem zeitlich realistischen Belegausstellungsdatum geprüft werden können. Bitte passen Sie die Uhrzeit der Kasse an oder nehmen Sie Kontakt mit dem Kassenhersteller auf. Bundesministerium für Finanzen.",
 
Es wäre für diese Tests gut, wenn man, z.b. mit einer Option beim Aufrufen, diesen Check überspringen könnte.

**Comment by asitplus-pteufl** [comment]
Sie sind der Release von der Version 1.0.0 des Prüftools etwas zuvorgekommen. Dort gibt es nun den Parameter -f der genau diese Funktion ermöglicht.

**Comment by aunterlu** [comment]
sehr gut, danke!
