### ISSUE TITLE
Signaturzeritifikat und Zertifizierungsstellen?

### ISSUE THREAD

**Issue by twisted-pear** [a-sit-plus/at-registrierkassen-mustercode#149]
Ich hätte eine Verständnisfrage zu den Feldern Signaturzeritifikat und Zertifizierungsstellen im DEP.

Wenn im DEP ein Signaturzertifikat und eine Kette von Zertifizierungsstellen angegeben wurde, welches Zertifikat ist dann im cryptographicMaterialContainer bzw. in FON anzugeben? Für mein Verständnis müsste es dann genügen das "oberste" Zertifikat in der Kette anzugeben, da dann ja alle vom Signaturzertifikat aufwärts mit diesem geprüft werden können. Mit dem aktuellen Prüftool klappt das aber so nicht.

Was ist denn der korrekte Weg diese Felder auszufüllen bzw. Wofür gibt es die List mit Zeritifizierungsstellen, wenn man ohnehin das Zertifikat mit dem die Rechungen signiert werden direkt angeben muss?

**Comment by asitplus-pteufl** [comment]
Am einfachsten ist es wenn Sie diese ganz weglassen, dies Werte sind im Detailfragen-Dokument als optional markiert.

Der cryptographicMaterialContainer ist rein für das Prüftool, dort wird das Zertifikat abgelegt, das für die Signatur des Belegs verwendet wird. Wenn Sie im DEP-Export mehrere Signaturzertifikate verwenden, dann legen Sie einfach mehrere im cryptographicMaterialContainer ab.
Das Prüftool braucht für die Signaturprüfung den öffentlichen Schlüssel, der zu dem privaten Schlüssel gehört, mit dem der jeweilige Beleg signiert wurde. Dieser öffentliche Schlüssel ist im Signaturzertifikat enthalten. Aller darüberliegende Zertifikate sind jene der Zertifizierungsstellen (der CAs) die für die Ausstellung verwendet wurden. Zu diesen hat natürlich nur der ZDA die privaten Schlüssel.
FON erhält das jeweilige Signaturzertifikat bei der Registrierung (über FON, Web-Service etc.), und kann anhand der Seriennummer dieses einem Beleg zuordnen. Da das Prüftool keinen Zugriff auf FON hat, ist dort die zusätzliche Datei cryptographicMaterialContainer notwendig (gleiches gilt auch für den AES-Schlüssel).

Die Zertifizierungsstellen müssen weder im FON noch beim Prüftool angegeben werden und sind auch im DEP-Export optional.

Hilft Ihnen das?

**Comment by twisted-pear** [comment]
Ok, also sind die Zertifizierungsstellen komplett überflüssig? Ich hätte gedacht man kann dann eigene Zertifikats-Ketten bauen und muss im FON nur das oberste Zertifikat angeben um DEPs die von verschiedenen Sub-Zertifikaten signiert wurden zu prüfen. Aber wenn man das Signaturzertifikat direkt im FON angeben muss ist das natürlich unnötig.

**Comment by asitplus-pteufl** [comment]
Sie sind optional, wenn Sie sie für Ihre Zwecke benötigen (z.B. im Rahmen von automatisierten Tests der Exports, Belege) dann können Sie sie gerne ablegen.

Noch ein paar generelle Informationen:
Eine eigene Zertifikatskette können Sie nicht bauen, die ist ja durch die ausstellenden CAs des ZDAs vorgegeben. (das wäre nur beim geschlossenen Gesamtsystem denkbar).

Für die Signaturprüfung ist zudem immer der öffentliche Schlüssel des Zertifikats, das zum Signieren verwendet wurde nötig. Da das Zertifikat für den maschinenlesbaren Code viel zu groß wäre muss es im FinOnline registriert werden. Zuordnung über die Seriennummer und die ZDA-ID im Beleg.

**Comment by twisted-pear** [comment]
Alles klar, danke.

**Comment by twisted-pear** [comment]
Eine Frage hat sich diesbezüglich noch ergeben: Im Detailfragen-Dokument steht, dass das Feld "Signaturzeritifikat" leer gelassen werden kann und, dass "Zertifizierungsstellen" der leeren Liste entsprechen darf. So wie sich das liest, würde das heißen, dass diese Felder aber trotzdem vorhanden sein müssen. Momentan erlaubt das Prüftool auch das komplette weglassen der Felder. Müssen diese beiden Felder vorhanden sein, auch wenn sie "leer" sind?

**Comment by asitplus-pteufl** [comment]
nur einfügen damit lehre felder da sind macht jetzt nicht viel sinn, das prüftool berücksichtigt das schon. weglassen ist somit möglich.

**Comment by Flanelli** [comment]
Wenn Hr. Dr. Teufl das Weglassen der leeren Felder "Signaturzeritifikat" und  "Zertifizierungsstellen"
lediglich auf das Prüftool bezieht wäre das nachvollziehbar. Für das tatsächliche DEP gilt meiner bescheidenen Meinung nach aber zumindest zum jetzigen Zeitpunkt wohl noch der Passus lt.
dem letzten publizierten Dokument
FESTLEGUNGEN DES BMF ZU DETAILFRAGEN DER 
REGISTRIERKASSENSICHERHEITSVERORDNUNG (RKSV) 
BUNDESMINISTERIUM FÜR FINANZEN 
A-SIT PLUS GMBH 
VERSION 1.2  –  05.09.2016 

<Auszug>
 5  Export des Datenerfassungsprotokolls 

Beispiel – Export des DEPs wenn keine Signaturzertifikate vorhanden sind 
Im folgenden Beispiel wird davon ausgegangen, dass kein Signaturzertifikat vorhanden ist.
Alle Belege  –  auch  wenn  Sie  mit  unterschiedlichen  Zertifikaten  signiert  wurden
–  werden  in  einer Gruppe chronologisch abgelegt. 
{ 
  "Belege-Gruppe": [ 
    { 
      **"Signaturzertifikat": "", 
      "Zertifizierungsstellen": []**, 
      "Belege-kompakt": [ 
        "JWS-REP-BELEG", 

Wird das nun so bleiben oder erfolgt noch eine Übereinstimmung?
Irgendwie ist es mühsam links Äpfel und rechts Birnen vorzufinden :-)

**Comment by twisted-pear** [comment]
Ja, genau darauf habe ich mich bezogen. Natürlich würde es Sinn machen die leeren Elemente gleich ganz wegzulassen, aber so steht es nicht im Dokument.

**Comment by asitplus-pteufl** [comment]
dann geben sie sie wie im dokument beschrieben einfach dazu. dann sind sie definitiv komform zur spezifikation.
