### ISSUE TITLE
Auslandssteuern

### ISSUE THREAD

**Issue by MartinDomig** [a-sit-plus/at-registrierkassen-mustercode#15]
Folgendes Beispiel: ein Taxiunternehmen bietet zum Pauschalpreis eine Fahrt von Österreich ins benachbarte Ausland an. Nun wird ein Teil der Leistung naturgemäß in Österreich, der Rest davon im Ausland erbracht und anteilsmäßig auch dort versteuert, zu den dort jeweils geltenden Steuersätzen.

Wie sollte der zu signierende Beleg hierfür aussehen? Soweit ich sehe sieht die Referenzimplementierung jeweils nur einen Steuersatz je Artikel vor, im oben geschilderten Fall bräuchte ich aber mindestens 2, manchmal mehr. Alternativ könnte der selbe Artikel mehrfach auf dem Beleg mit den anteiligen Preisen angefüht werden - obwohl er aber nur ein mal verkauft wurde. Weiters stellt sich die Frage, ob und wenn ja wie ausländische Steuersätze (die unser Finanzamt ja nur marginal interessieren) auf dem Beleg überhaupt ausgewiesen werden müssen, oder ob hierfür der Steuersatz "Satz-Null" 0% ausgewiesen werden sollte - was wiederum unseren Taxifahrer bzw. das italienische Finanzministerium verwirren könnte, denn für Taxifahrten in Italien sind tatsächlich 0% Steuern zu entrichten.

Gibt es hierfür eine Richtlinie?

**Comment by pteufl** [comment]
danke für Ihre Anfrage. Ich leite diese an das BMF weiter, da dies über die technischen Aspekte des Mustercodes hinausgeht.
Nur so viel vorweg: Es gibt bereits Anfragen der WKO zu ähnlichen Beispielen. Hier ist gerade der Prozess in Gange diese zu beantworten. Ich werde Sie hier informieren wenn diese Antworten vorhanden sein werden.

**Comment by asitplus-pteufl** [comment]
Antwort des BMF:
Grundsätzlich sind mit der Registrierkasse nur Umsätze aufzuzeichnen, die in Österreich erwirtschaftet werden. Der Leistungsort bei innergemeinschaftlicher Personenbeförderung ist immer dort, wo er ausgeführt wird, auch bei Leistungen an Unternehmer. Bei Pauschalpreisen ist der Fahrpreis anteilig nach der Beförderungsstrecke aufzuteilen. Der nicht in Österreich erbrachte Teil der Leistung ist in Österreich nicht steuerbar. 
Wird dennoch der Gesamtpreis mit der Registrierkasse erfasst, ist der nicht steuerbare Teil in der 0 % Steuerklasse zu erfassen, da es lt. Registrierkassensicherheitsverordnung keine „Steuerklasse“ „nicht steuerbar“ gibt.
