### ISSUE TITLE
Belegnummern

### ISSUE THREAD

**Issue by norbert2** [a-sit-plus/at-registrierkassen-mustercode#150]
Ist folgende Beleg-Nr.-Vergabe zulässig?

Mehrere Fahrverkäufererstellen BV-Rechnungen. Pro Fahrverkäufer zur Zeit ein eigener Nummernkreis für die bisherigen BV-Rechnungen. Es erfolgt KEINE Signierung und Speicherung im DEP. ("Kalte Hände")
Im Büro sollen alle BV-Rechnungen  zum Zwecke der Signierung und Speicherung im DEP nochmals gedruckt wurden.
Ich hätte geplant, beim Nachdruck einfach eine laufende Beleg-Nr. zu verwenden. Am Ausdruck natürlich der Verweis auf die Original-BV-Rechnungsnummer. Im DEP die lfd. Beleg-Nr. 
Ist das zulässig?

Weiters werden auch direkt im Büro BV-Rechnungen erstellt, die natürlich schon Signiert und im DEP gespeichert werden. Um da doppelte Beleg-Nr. im DEP zu vermeiden wäre folgendes geplant:
BV-Re.Nr. andrucken, zusätzlich aber auch eine Beleg-Nr. (eben die lfd. Beleg-Nr., mit der auch die Nacherfassungen durchnummeriert werden) mit der dann auch die Signierung und Speicherung im DEP erfolgt.
Ist das zulässig?

Diese Lösung hat den großen Vorteil, dass der BV-Nr.Kreis vom User beliebig geändert werden kann,
ohne dass damit die lfd-Nr. (die er eben nicht ändern kann) beeinflusst wird.

**Comment by ErichFreitag** [comment]
Ich glaube, das ist im Erlass ganz gut beschrieben (Punkt 6.7ff):

"Die nachträgliche Erfassung der einzelnen Umsätze, die außerhalb der Betriebsstätte [...] erbracht werden [...] soll – unabhängig von einer bestehenden „händischen Belegerteilungspflicht“ vor Ort – ohne unnötigen Aufschub bei Rückkehr in die Betriebsstätte ermöglicht werden".
(Ja, händische Belege vor Ort ausstellen, zeitnah nacherfassen).

"Zur Nachvollziehbarkeit des einzelnen Geschäftsvorfalls ist eine Durchschrift des händischen
Belegs aufzubewahren und ein Zusammenhang zum nacherfassten Barumsatz herzustellen [...]".
(Original-Beleg aufbewahren, Zusammenhang herstellen).

"Für die Erstellung der händischen Belege können auch Registrierkassen ohne Sicherheitseinrichtung verwendet werden". (Belege aufbewahren und wie oben nacherfassen).

"[...] es muss über jede Barzahlung ein Beleg ausgestellt und diese auch einzeln in die Registrierkasse eingegeben werden, um eine Nachprüfbarkeit zu gewährleisten. Jedoch ist es zulässig, auf eine Paragondurchschrift bzw. -nummer zu verweisen, die Beleginhalte müssen nicht einzeln eingegeben werden". (keine Neueingabe, Verweis würde genügen).

"Der Rechnungskreis des Paragons kann von der Nummerierung in der Registrierkasse abweichen, es muss aber sichergestellt sein, dass aus der Zusammenschau des Paragons und der Eintragung in der Registrierkasse sich eindeutig ergibt, um welchen Umsatz es sich handelt.". (Zusammenhang muss nachvollziehbar sein).

Wenn ich ihr Vorhaben richtig verstanden habe ist das wohl in obigem Sinne zulässig, wenngleich wohl auch viel händische Arbeit (Belege aufbewahren, nacherfassen, Zusammenhang bei Bedarf klar herstellen, ...).

Wenn sie diesen Weg verfolgen - wie kann es dann bei Büro-Rechnungen zu doppelten Belegnummern kommen (wenn diese Richtung DEP laufend sind)?

**Comment by norbert2** [comment]
Danke für die prompte und ausführliche Antwort.

Meine erste Frage sehe ich positiv beantwortet. 
Zur Erläuterung: Die Belege werden nicht händisch nacherfasst, sondern werden - zur Zeit schon ohnehin - automatisch von den Laptops der Fahrverkäufer in die zentrale Bürodatenbank eingespielt.

Wenn auch Punkt zwei zulässig ist, dass ich die fortlaufende Beleg-Nr. zusätzlich zur BV-Rechnungs-Nummer verwenden kann, kann es natürlich nicht zu doppelten Beleg-Nummern im DEP kommen.

Für Punkt zwei zur Klarstellung:
Es wird eine BV-Rechnung im Büro erfasst. auf dieser BV-Rechnung steht die z.B. "BV-Re.Nr.  4711"
darunter "Beleg-Nr.: 1234" Signierung und Speicherung im DEP erfolgt mit der Beleg-Nr. 1234.
In der Datenbank mit den vollständigen Belegzeilen werden natürlich auch beide Nr. gespeichert.
Somit kann über die Beleg-Nr. ein Prüfer die Detaildaten finden.

**Comment by ErichFreitag** [comment]
Bitte gerne meinerseits.

Das Wort "zulässig" möchte ich noch kommentieren: ob das genauso "zulässig" ist kann ich nicht beurteilen. Ich bin Sachverständiger und kein Jurist - es steht mir also nicht zu, über Zulässigkeit zu urteilen; zweitens steht der Erlass ja nicht im Gesetzesrang, sondern nur die RKSV. 

Meine Beiträge hier können und sollen lediglich unterstützen, die für die jeweiligen Antworten zu den Fragen benötigten Quellen zu sammeln, zu interpretieren und daraus einen Lösungsvorschlag anzubieten. Die Endentscheidung der Umsetzung verbleibt ohnedies bei ihnen.

Gerade bei Fragen, die nicht eindeutig in der RKSV abgebildet sind, wird man halt mit Sachverstand, Interpretationen und Ergänzungen wie dem Erlass, Meinung und Wissen von anderen sowie unter Berücksichtigung des Sinnes der RKSV an die Lösung herangehen müssen. Das ist oft auch im Bereich von Normen nicht anders.

Das bitte in diesem Sinne zu verstehen - helfen werde ich gerne weiterhin wo ich kann.

**Comment by asitplus-pteufl** [comment]
Ich muss hier aus A-SIT Plus Sicht leider auf das Readme verweisen. Der wichtigste Auszug dazu:

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
