### ISSUE TITLE
Wie Umsattzähler mit openssl über Command line ohne Passworteingabe verschlüsseln?

### ISSUE THREAD

**Issue by hjgwenex** [a-sit-plus/at-registrierkassen-mustercode#151]
Es ist mir nicht gelungen, mit der OpenSSL command line (Version 1.1.0b vom 26.9.16 unter Windows) den Umsatzzähler wie spezifiziert (mit Initialisierungsvektor und AES-Schlüssel) im Batch – das heißt OHNE zwingende Passworteingabe - zu verschlüsseln.

Kassenstand 10345.30 EUR in Datei "Kassenstand.txt" im Verzeichnis ..\99_temp soll mit Ausgabe nach ..\99_temp\Kassenstand_en.txt verschlüsselt werden
Mit der Eingabe von
_"C:\OpenSSL-Win32\bin\openssl.exe" enc -aes-256-ctr -pass pass:y2!87HK45 -p -in ..\99_temp\Kassenstand.txt -out ..\99_temp\Kassenstand_en.txt -base64 -nopad_
in der Command Line ist es zwar möglich, ohne Passworteingabe zu verschlüsseln, aber ohne Vorgabe eines Initialisierungsvektors.

Gibt man einen Initialisierungsvektor mit –iv vor, wird er ignoriert
_"C:\OpenSSL-Win32\bin\openssl.exe" enc -aes-256-ctr -pass pass:y2!87HK45 -p -in ..\99_temp\Kassenstand.txt -out ..\99_temp\Kassenstand_en.txt -base64 –nopad –iv 000102030405060708090a0b0c0d0e0f_
=> Ausgabe
_salt=9CD2060B86C80CCF
key=401187444A15F146189CFA58C2B872D09E2148AC77A961D5FC0B283195D6F5AB
iv =4361121CC443A1D40B8D1B76A07F4814_
Wird _–pass pass:y2!87HK45_ weg gelassen, muss ein Passwort eingegeben werden (=> Nicht verwendbar im Aufruf aus einem Warenwirtschaftssystem), auch wenn mit -K ein Schlüssel (Hexadezimal) vorgegeben wird.

Es wäre extrem hilfreich, ein funktionsfähiges Beispiel für einen openssl command line Aufruf zur Verschlüsselung des Umsatzzählers (ohne Dialog / Passworteingabe) entsprechend Spezifikation zu haben.

Alternativ wäre auch die Spezifikation des Aufrufs einer entsprechenden C Funktion zur Verschlüsselung des Umsatzzählers aus einem DLL von openssl sehr hilfreich.

Besten Dank im Voraus - Hans-Jörg Grabner / WENEX IT Solutions

**Comment by asitplus-pteufl** [comment]
Kann Ihnen zur CMD-Line leider keine Hilfe anbieten. Aber folgende Hinweise: Das wird nicht so leicht, weil Sie müssen ja die 2er Komplement Darstellung für den KassenStand haben. Die TXT Datei kann Ihnen hier nicht helfen, da wären ja die ASCII Zeichen kodiert. Bitte auch beachten, dass der Umsatzzähler in €-Cent anzugeben ist.

Für die Verwendung aus C haben wir keine Muster-Bsps (war nicht Gegenstand dieses Projekts), ich verweise sie aber einerseits auf öffentliche Quellen (z.B. http://stackoverflow.com/questions/3141860/aes-ctr-256-encryption-mode-of-operation-on-openssl) und möchte Sie vielleicht auch für das CMD-Bsp wichtig darauf hinweisen, dass Sie den CTR-Modus jederzeit auch mit dem ECB, oder CFB Modus emulieren können. Wie das generell abläuft sehen Sie im Java-Mustercode in der Methode encryptTurnOverCounter  in der folgende Klasse: https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-core/src/main/java/at/asitplus/regkassen/core/DemoCashBox.java

**Comment by FriNagy** [comment]
Hallo!

also es sollte mit openssl schon funktionieren, ich starte zB:

`openssl enc -aes-256-ctr -nosalt -nopad -a -v -in in.txt -out out.txt  -K 48693334536f667445724869333446654c6445724869333446654c6445723132 -iv 4c7088375c015979127ce5e127187814`

steht in .\in.txt 8 mal (character(0))  wird in .\out.txt  "SMFaoW5nJC8=" zurückgeliefert

hth
Frigyes

**Comment by hjgwenex** [comment]
Hallo!

 

Vielen Dank für die Bemühungen!

 

Ich war mit dem openssl command line Aufruf auf dem „Holzweg“. Es ist aus Harbour möglich, openssl Verschlüsselungs-Funktionen direkt aufzurufen – gehe daher für das von mir entwickelte ERP System diesen Weg.

 

MfG

Grabner Jörg

 

 

Von: FriNagy [mailto:notifications@github.com] 
Gesendet: Freitag, 3. März 2017 00:56
An: a-sit-plus/at-registrierkassen-mustercode
Cc: hjgwenex; Author
Betreff: Re: [a-sit-plus/at-registrierkassen-mustercode] Wie Umsattzähler mit openssl über Command line ohne Passworteingabe verschlüsseln? (#151)

 

Hallo!

also es sollte mit openssl schon funktionieren, ich starte zB:

openssl enc -aes-256-ctr -nosalt -nopad -a -v -in in.txt -out out.txt -K 48693334536f667445724869333446654c6445724869333446654c6445723132 -iv 4c7088375c015979127ce5e127187814

steht in .\in.txt 8 mal (character(0)) wird in .\out.txt "SMFaoW5nJC8=" zurückgeliefert

hth
Frigyes
