### ISSUE TITLE
Export und Zertifikate; Ausfall Signaturerstellungseinheit 

### ISSUE THREAD

**Issue by rksvlobster** [a-sit-plus/at-registrierkassen-mustercode#152]
Schönen guten Abend,

wir haben die folgenden zwei Fragen:

**1.)** Es scheint möglich zu sein, beim Export der Belege nur eine Beleggruppe ohne Angabe von Zertifikaten und Zertifizierungsstellen zu erstellen (Detailfragen, Kapitel 5). Die Belege im Exportformat enthalten dann zwar jeweils die Seriennummer des Zertifikates, mit dem sie signiert wurden, aber eine Verifikation der Signatur ist nur mit einem Zertifikat möglich. Der "CryptographicMaterialContainer" muss auch nicht dem Export beigefügt werden.

_Ist das richtig, dass wir die Zertifikate an keiner Stelle übergeben müssen? Auf welchem Wege kommt dann ein Finanzpolizist oder das BFM an die Zertifikate, mit denen die Belege signiert wurden, die wir exportieren?_

**2.)** Wenn eine Signiereinheit (SE) ausfällt, kann man ja mit einer Kasse weiterhin Belege erstellen nur, dass diese den Hinweis "Sicherheitseinrichtung ausgefallen" angedruckt haben müssen und der Maschinencode gemäß Anforderung aufbereitet wird (§17.4).
Wenn dann mehr als 48 Stunden vergangen sind, muss der Ausfall der SE auf FON gemeldet werden (§17.1).
Wenn dann eine Wiederinbetriebnahme nicht möglich ist, ist eine neue SE zu beschaffen etc. (§17.7).

_Was wir aus dem Gesetzestext nicht herauslesen können ist, ob dann die Kasse bis zur Ankunft der neuen SE weiterbetrieben werden kann (mit "Sicherheitseinrichtung ausgefallen" usw.) und wenn ja, wieviel Zeit sich der Unternehmer lassen kann, um sich um eine neue SE zu kümmern? Für uns liest sich das wie: „Ja“ und „beliebig“, macht aber wenig Sinn._

Vielen Dank im Voraus.

**Comment by asitplus-pteufl** [comment]
zu 1, richtig, Sie brauchen die Zertifikate nicht angeben, weil diese ja im FinOnline registriert werden müssen und somit zur Verfügung stehen. Über die Seriennummer kann dann die Zuordnung erfolgen. Da das Prüftool natürlich keinen Zugang zu FinOnline hat, ist dort die zusätzliche Datei notwendig (die auch den AES-Schlüssel enthält, auch dieser ist ja im FinOnline registriert).

zu 2, da kann ich als A-SIT Plus leider keine Aussage machen, muss hier leider auf die Info der Startseite verweisen bzw. auf die dort angegeben Kontaktinfos.
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by rksvlobster** [comment]
Zu 1: Danke für die Erklärung.
Zu 2: Hm. Arkane Verweise auf Verweise. Im jetzigen Stadium sollten Antworten auf solch triviale Fragen von Menschen, deren täglich Brot es ist, sich mit der RKSV zu beschäftigen, eigentlich wie aus der Pistole geschossen kommen. Verstehen Sie mich bitte nicht falsch, es ist keineswegs Ihre 'Schuld'. Sie arbeiten ja auch nur mit dem diffusen schweizer Käse, der sich RKSV nennt. 150+ Issues hier, 50+ Seiten auf Xing, ellenlange FAQs bei der WKO und es herrscht immer noch Verwirrung und Unklarheit. Alle Beteiligten müssten eigentlich von massiven Rückenproblemen geplagt werden, bei dem vielen Schulterzucken.
Zur Aufheiterung: _Muss ein Nullbeleg zwingend signiert werden?_

**Comment by asitplus-pteufl** [comment]
Es ändert nur leider nichts daran, dass dieses Projekt rein technische Aspekte behandelt. Es ist daher der falsche Anlaufpunkt für organisatorische Themen. Natürlich werden organisatorische Inputs/Fragen wie diese an das BMF weitergeleitet.

**Comment by rksvlobster** [comment]
Es ist wie es ist. Danke Ihnen trotzdem für Ihre Beiträge.

**Comment by norbert2** [comment]
Frage zur Klarstellung für mich:

Kann die Signierungseinheit für eine Kassa  beliebig gewechselt werden? Natürlich mit einem Zertifikat, das bei FON gemeldet ist.
Szenario: 
Die SE fällt aus. Die neue SE wird angehängt. Nullerbeleg wird gedruckt. Weiter mit normalen Kassiergeschäft.

Wenn ja, kann das mit dem Prüftool verifiziert werden? Wie müsste der Aufbau des Crypto-Containers ausschauen? Gibt's da Beispiele dazu?

**Comment by rksvlobster** [comment]
Usere Auffassung und bisherige Handhabe:

Eine Kasse aus einem Pool von 1 bis k Kassen kann zum signieren auf eine beliebige SE aus einem Pool von 1 bis s angemeldeten SEs zugreifen. Das heisst auch, bei jedem Signiervorgang kann eine andere SE genutzt werden. Prinzipiell können 20 Kassen sich auch eine SE teilen oder eine Kasse signiert der Reihe nach mit 20 verschiedenen SEs.
In den CMC müssen dann alle von einer Kasse im laufe ihres RKSV-Lebens benutzten Zertifikate rein. Theoretisch (also ungetestet) könnte man ein Master-CMC anlegen, welches alle Zertifikate enthält.
Dann müsste man nur noch den AES Schlüssel (base64AESKey) pro Kasse passend ersetzen. Es ist aber auch möglich, dass alle Kassen den gleichen AES Schlüssel benutzen.
_"Jede Registrierkasse eines Unternehmers verfügt über genau einen AES-Schlüssel. Prinzipiell kann jeder Registrierkasse ein anderer AES-Schlüssel zugewiesen werden. Zwei
oder mehr Registrierkassen können sich aber auch einen AES-Schlüssel teilen. Bei N Registrierkassen verfügt der Unternehmer daher über einen Pool von 1 bis N AESSchlüssel."_
Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV) V1.2

In dem Fall bräuchte man nur einen einzigen CMC anlegen und beim Prüftool referenzieren. 

Unverständlicherweise ist das Prüftool eine black box (closed source). Um zu erfahren, was es tut oder nicht tut, muss man die "Doku" lesen, hier fragen, die Foren hier durchstöbern, geschickt raten und testen.

Anmerkung: Der CMC ist nur zum Testen relevant. Im laufenden Betrieb wird er nicht benötigt.

**Comment by asitplus-pteufl** [comment]
kann die Aussagen von @rksvlobster bestätigen (sig-einrichtung und AES).

zum Prüftool:
wegen Source Code, bitte die Anfrage ans BMF stellen, das kann A-SIT Plus nicht entscheiden. bezüglich Prüfungen: es wird demnächst auch noch ein Dokument geben dass den genauen Prüfablauf beschreibt. Hier eine generelle Übersicht dazu: Das Prüftool prüft die formale Korrektheit der Belege (Formatprüfungen, Anzahl der Elemente, Länge von bestimmten Elementen wie Verkettung, Signatur etc.), wenn diese Formalprüfungen passen, dann werden die kryptographischen Prüfungen durchgeführt (Entschlüsselung Umsatzzähler, Gültigkeit der Signatur).

Bei den DEP-Prüfungen gibt es eine Detailliste auf der Startseite, aber kurz gesagt: Verkettung, Entwicklung Umsatzzähler, kein Wechsel von Sig-Einrichtungs-Typen (GGS vs. offenen System), eindeutige Belegnummer, Abfolge der Belege.
