### ISSUE TITLE
Kassen-Belege vor Einführung DEP

### ISSUE THREAD

**Issue by DdDIK** [a-sit-plus/at-registrierkassen-mustercode#155]
Hallo,
unsere Kunden haben seit Jahren die Registrierkassen im Betrieb.
Dürfen bisherige Belege in der Kassendatenbank bei Einführung DEP beibehalten werden, oder muss die Kasse ganz von Anfang eingesetzt werden?
Anders gesagt, muss man mit DEP in neue instalierte Kasse anfangen?

**Comment by ErichFreitag** [comment]
Wenn ich ihre Frage richtig verstanden habe:

Aus steuerlicher Sicht läuft die Kasse ganz normal weiter. Damit bleiben auch die bisher erstellten Belege etc. im Datenerfassungsprotokoll der Kasse (= Journal oder ähnlich) unverändert erhalten bzw. werden weitergeführt.

Aus Sicht der RKSV beginnt ab der Inbetriebnahme der Sicherheitseinrichtung (= Auslösen des Startbelegs, Registrierung der Kasse, Start des Umsatzzählers, ...) zusätzlich ein eigenes DEP für Barumsätze (Stichwort "Einrichtung des DEP"). Dieses muss auch insbesondere zusätzlich und gesondert vom bisherigen Datenerfassungsprotokoll in einem bestimmten Format exportiert sowie gesichert werden können.

In diesem RKSV-DEP müssen zumindest alle Barumsätze enthalten sein (Stichwort "Signierung"). Es wird daher im allgemeinen einen Teil der bisher üblichen Transaktionen beinhalten (nicht enthalten sein müssen - jedoch können - z.B. Bareinlagen oder Barausgaben).

Ob sie ein paralleles und zusätzliches RKSV-DEP führen oder ob sie das bisherige Datenerfassungsprotokoll der Kasse entsprechend ergänzen ist eine Architektur- und Implementierungsentscheidung.

**Comment by DdDIK** [comment]
Vielen Dank für Ihre ausführliche Antwor auf meine Frage!
