### ISSUE TITLE
Verkettung

### ISSUE THREAD

**Issue by eczach** [a-sit-plus/at-registrierkassen-mustercode#156]
Folgendermaßen habe ich die Verkettung verstanden:
Der Umsatzzähler wird immer nur und bei allen Belegen verändert, die signiert werden. Wenn zwischendurch Belege ausgestellt werden, die nicht signiert werden (weil sie nicht müssen), so wird der Umsatzzähler auch nicht verändert. In die Erstellung einer Signatur wird immer die Signatur des letzten zuvor signierten Belegs für die Verkettung einbezogen.
Es ist gestattet in der Registrierkassa auch andere als rksv-pflichtige Belege (Rechnungen zur Überweisung etc.) auszugeben und diese nicht zu signieren.
Passt das so? :-) 
Danke!

**Comment by ErichFreitag** [comment]
Ja, das passt soweit.

Ausnahme: beim Startbeleg wird über die Kassen-ID verkettet, da es noch keinen vorigen Beleg gibt.

Ich würde "es ist gestattet..." zur Verdeutlichung umformulieren. Die Registrierkasse ist ja zunächst eine Kasse, in der all das weiterhin erfasst wird, was auch jetzt schon erfassungspflichtig war. Was jetzt dazukommt ist, dass Barumsätze signiert werden müssen. Nicht-Barumsätze dürfen im Sinne der RKSV zusätzlich freiwillig signiert werden. Und auf ein paar Sonderfälle, beispielsweise im Umgang mit Wertgutscheinen, muss gesondertes Augenmerk gelegt werden.

**Comment by eczach** [comment]
zur präzisierung (ob ich alles richtig verstanden habe :-)
so wie ich den text verstanden habe, ist es gestattet auch nicht registrierkassenpflichtige belege in der registrierkassa zu erstellen (barbewegungen, zielrechnungen (bei überweisung) etc. 
diese müssen nicht signiert werden. die verkettung bezieht sich immer auf den vorherigen signierten beleg. 
wenn ich jedoch (freiwillig) signiere, verändert der jeweilige beleg aber auch den umsatzzähler.

**Comment by ErichFreitag** [comment]
Die RKSV ist ja "nur" ein Manipulations-Schutz-Add-On zu den bestehenden Funktionen von Registrierkassen. D.h. seitens der Kasse bleibt zunächst alles wie es ist/war und sie können und müssen je nach Vorgaben natürlich Barbewegungen und dergleichen in der Kasse wie bisher erstellen.

Neu: Barumsätze müssen signiert werden = wenn es keine Barumsätze sind müssen sie nicht signiert werden, dürfen aber signiert werden. Was auch immer sie signieren verändert den Umsatzzähler, korrekt. Das ist aber egal, weil der RKSV-Umsatzzähler irgendwann mit den klassischen Zählern eines Umsatzes ohnedies nicht mehr übereinstimmt (das gelegentlich verwendete Wort "Summenspeicher" differenziert das besser).

Die Verkettung bezieht sich immer (mit Ausnahme des Startbelegs) auf den zuvor signierten Beleg, korrekt.

P.S. mit den Unternehmen, mit denen ich bezüglich RKSV in Kontakt bin, haben wir uns immer dazu entschieden, alles was Richtung Kunde geht zu signieren. Das macht die Sache einfacher und vermeidet, dass Sonderfälle vergessen werden können. Ein klassisches Beispiel dazu ist, dass ein Wertgutschein alleine beim Verkauf keinen Barumsatz darstellt; wird er jedoch gemeinsam mit anderen Barumsätzen gekauft, muss er sehr wohl im 0%-Satz angeführt werden. Die Logik kann da unnötig komplex werden.

**Comment by eczach** [comment]
das ist ein gedanke mit dem ich mich auch beschäftige - einfach zur sicherheit alles signieren. dagegen spricht jedoch, dass die signaturkarte (auch in der nun bei a-trust lieferbaren schnelleren version) leider eben doch noch etwas zeit für die signatur braucht ....
danke für die rasche rückmeldung - sogar am feiertag :-)

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
