### ISSUE TITLE
DEP Erweiterung

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#159]
Hallo,

laut Detailspezifikation Abs 4 können die Klartextdaten für das Signaturformat (Klasse ReceiptRepresentationForSignature) beliebig um weitere JSON-Daten erweitert werden. Auf der anderen Seite die Klasse ReceiptPackage enthält oben genannte Daten (jwsCompactRepresentation).

Wenn man DEP-Eintrag um weitere Daten erweitern möchte (Kundendaten, Positionen usw.) genügt es wenn diese zusätzliche Daten im Objekt ReceiptPackage enthalten sind oder sollte man die Klasse ReceiptRepresentationForSignature erweitern?

Danke
seli

**Comment by asitplus-pteufl** [comment]
Ich bin darauf beim WKO-Vortag am 27.10. eingegangen. Wenn die Folien nicht online sind, bitte kurze direkte Nachricht an peter.teufl@a-sit.at, dann übermittel ich diese.
neben ein paar anderen Details wird die Info aber auch noch auf dieser Seite veröffentlicht.

kurzantwort: Sie können das RKSV-Dep erweitern wie Sie wollen, es muss nur garantiert sein, dass die in der spezifikation geforderten Felder und deren Struktur erhalten bleiben.
