### ISSUE TITLE
"In der Registrierkasse erfassen" == Umsatzzähler++ ?

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#16]
Es gibt ja Geschäftsfälle, deren Erfassung in der Registrierkasse nicht verpflichtend, aber zulässig ist. Dies wären z.B. der Verkauf von Wertgutscheinen oder die Entgegennahme von Bargeld im Namen von Dritten.

Werden diese Geschäftsfälle nun freiwillig in der Registrierkasse erfasst, stellen sich folgende Fragen:

* Muss der Betrag in den maschinenlesbaren Belegdaten aufscheinen? (vermutlich ja, und zwar bei 0%)
* Muss der Umsatzzähler erhöht werden? (Wenn ja, hätte man bei "Verkauf" und Einlösung eines Wertgutscheines eine Doppelerfassung desselben Betrages im Umsatzzähler).

Habe ich da etwas übersehen, oder ist das tatsächlich noch nicht geklärt?

**Comment by pteufl** [comment]
A-SIT Plus kann hier nur technische Aspekte behandeln. Allerdings folgende Info:
Fragen zu diesem und ähnlichen Themen gibt es (aufbereitet) seitens der WKO. Diese werden gerade beantwortet. Ich werde die Infos dazu hier posten.
