### ISSUE TITLE
DEP Datum/Uhrzeitformat limitiert

### ISSUE THREAD

**Issue by giemes** [a-sit-plus/at-registrierkassen-mustercode#160]
Frage zur Änderung im DEP-Prüftool und der Definition:

Die Definition lautet:
> Das Datum und die Uhrzeit wird im ISO 8601 Format ohne der Angabe der Zeitzone angegeben ( JJJJ-MM-TT’T’hh:mm:ss , z. B. 2015-07-21T14:23:34 )

ISO sagt aber, das auch Nachkommastellen (subseconds) möglich sind, zb: https://www.w3.org/TR/NOTE-datetime

Das Finanzamt akzeptiert die Belege mit 3 Nachkommastellen und sendet selbst die Timestamps auch mit 3 Nachkommastellen.

Jetzt die Frage: Warum wird im Prüftool 1.0.0 das Limit OHNE Nachkommastallen restriktiert wenn
a) im 0.7.1 das noch erlaubt war
b) Finanzamt / FinanzOnline die Prüfungen auch erlaubt und selbst so kommuniziert
c) es eine Einschränkung des verwiesenen Standards ist (in Java einfach ISO_LOCAL_DATE_TIME verwenden)

Danke für das Feedback!

lGG

**Comment by ErichFreitag** [comment]
Ich kann das nur soweit kommentieren, als dass dies in der RKSV, Detailspezifikation Punkt 4 genau so spezifiziert ist:

"Beleg-Datum-Uhrzeit: Der Wert dieses Feldes entspricht dem in § 9 Abs. 2 Z 3 angegebenen Wert, JSON-Format string UTF-8 kodiert. Das Datum und die Uhrzeit wird im ISO 8601 Format ohne der Angabe der Zeitzone abgespeichert („JJJJ-MM-TT’T’hh:mm:ss“, z. B. 2015-07-21T14:23:34). Es wird immer von österreichischer Lokalzeit (CET/MEZ) ausgegangen".

**Comment by giemes** [comment]
Ein Standard hat ja grundlegend auch den Sinn Interoperabilität zu vereinfachen. Jetzt macht das Ganze natürlich auch nur dann wirklich Sinn, wenn der Standard auch dem entsprechend eingehalten wird und nicht extra Einschränkungen, etc dazugenommen werden. Libraries, etc können verwendet werden und erleichtern die Umsetzung und Connentivität etc. Dann würde ein einfaches "das ist das Format/Pattern und aus" reichen.

Wenn man sagen würde: der Standard wurde adaptiert dann ist zu sagen:
Extra textuell erwähnt ist das Weglassen der Zeitzone aber nicht des Nachkommateiles der Sekunden. 
Siehe Note von W3C: This profile does not specify how many digits may be used to represent the decimal fraction of a second. An adopting standard that permits fractions of a second must specify both the minimum number of digits (a number greater than or equal to one) and the maximum number of digits (the maximum may be stated to be "unlimited").

Den Kollegen vom BMF ist das anscheinend auch schon aufgefallen weshalb sie zumindest 3 Stellen für den Subsecond-Teil erlauben und auch selbst so verwenden.

Könnten Sie mit den Kollegen vom BMF Rücksprache halten ob dies nicht wirklich gemäß Standard definiert und implementiert werden kann?

Aktuell befindet man sich in einer kleinen Grauzone:
* das BMF akzeptiert die Werte mit bis zu 3 NK-Stellen
* das Prüftool Version 1.0.0 akzeptiert keine (mehr)

Wäre schön wenn wir hier Klarheit bekommen könnten. Vielen Dank!

lGG

**Comment by asitplus-pteufl** [comment]
es wird nur so akzeptiert wie es im "adopting standard", der RKSV definiert ist. genau im pattern "JJJJ-MM-TT’T’hh:mm:ss" das einer variante des ISO-Formats entspricht.
