### ISSUE TITLE
GGS Registrierkassenverbund?

### ISSUE THREAD

**Issue by twisted-pear** [a-sit-plus/at-registrierkassen-mustercode#161]
Im "[Erlass zur Einzelaufzeichnungs-, Registrierkassen- und Belegerteilungspflicht](https://findok.bmf.gv.at/findok?execution=e100000s1&segmentId=7db3876d-7eb1-43ba-8cd6-1ba35b9b14cb)" vom 04.08. steht unter 3.10.1, dass Kassen in einem Registrierkassenverbund jeweils ein eigenes DEP haben und die Startbelege der Kassen untereinander verkettet sind (ausgenommen dem der 1. Kassa, der auch im FON registriert wird).

Soweit ich gesehen habe gibt es noch keine Möglichkeit derartige DEPs zu prüfen, da ja der Startbeleg nicht mit der Kassen-ID verkettet ist. Ist eine derartige Funktionalität geplant (oder bereits vorhanden)?

**Comment by ErichFreitag** [comment]
Die Frage nach der Prüfung kann ich nicht beantworten.

Was mich aber interessiert ist, wo dieser Mechanismus eingesetzt werden soll. Ich verstehe, dass der administrative Aufwand bei einer sehr hohen Zahl an Kassen zunächst sinkt. Anstelle der Vergabe einer eigenen Kassen-ID und der einzelnen Registrierung der Kassen tritt jedoch der Dokumentationsaufwand für die Einrichtung (Reihenfolge, ...). Ein eigenes Datenerfassungsprotokoll wird ja dennoch pro Kasse benötigt und die Belegnummernkreise müssen extra aufgetrennt und zugeordnet werden. Ferner stelle ich es mir nicht trivial vor, dass - wenn eine Kasse in den Verbund dazukommt - auf den jeweils letzten Startbeleg referenziert wird.

Haben sie da mehr Hintergrundinformationen dazu?

**Comment by twisted-pear** [comment]
Leider nein. Mir erschließt sich der Sinn hinter dieser Vorgangsweise auch nicht ganz, aber es ist offenbar zulässig und so wie es im Moment aussieht kann jemand

**Comment by twisted-pear** [comment]
Ein Beispiel, das ich mir vorstellen könnte wäre das aufteilen auf mehrere Filialen. Jede Filiale bekommt einen Verbund, die Zentrale kümmert sich um deren Registrierung im FON. Wenn eine Filiale eine Kassa hinzufügt, muss sie nicht mit dem FON oder der Zentrale interagieren und ist relativ ungebunden. Es muss lediglich der neue Startbeleg geprüft werden (wobei mir immer noch nicht klar ist wie das funktionieren soll).

Momentan sieht es jedenfalls so aus als gäbe es keine Möglichkeit ein derartiges System zu testen.

**Comment by AxelKutschera** [comment]
Wir haben fiskaltrust-Projekte bei denen der Registrierkassenverbund gewählt wird. Es gibt ein paar Spezialitäten, welche - abhängig von dem vorhandenen IT-System - die technische und besonders die organisatorische Abwicklung erleichtert. Es kann zB auch regional über mehrere Filialen ein Kassenverbund organisiert werden.
Ich stimme aber auch zu, dass es In den "normalen" Fällen jedoch nicht sinnvoll sein wird.
Zur Verkettung der Belege: Das funktioniert seriell. Der erste Startbeleg wird erstellt und die nächsten werden mit dem Verkettungswert des vorhergehenden erstellt. Die FON-Meldung wird immer durch den letzten vorgenommen.

**Comment by twisted-pear** [comment]
Wie wird dann der Startbeleg im FON geprüft? Wenn nicht alle vorherigen Startbelege vorhanden sind, kann man ja den Verkettungswert nicht überprüfen. Das selbe Problem ergibt sich auch bei DEPs. Außer natürlich das DEP für eine neue Kassa enthält vor dem eigentlichen Startbeleg auch noch alle anderen bis zum ersten. Mir ist hier irgendwie die korrekte Vorgangsweise nicht klar.

**Comment by AxelKutschera** [comment]
Laut Erlasse: „Für die Prüfung des Startbeleges im Sinne § 6 Abs. 4 RKSV ist nur der zuletzt erstellte Startbeleg heranzuziehen. Monats- und Jahresbelege im Sinne § 8 RKSV sind zwar pro Registrierkasse zu erstellen, für die Prüfung des Jahresbelegs genügt ein Jahresbeleg pro Registrierkassenverbund. FON-Meldungen im Falle von Ausfällen oder Außerbetriebnahmen sind nur erforderlich, wenn die Gesamtheit aller Registrierkassen eines Registrierkassenverbundes betroffen ist.
Pro nachträglich hinzukommender Registrierkasse in einem Registrierkassenverbund sind die Fortsetzung der Startbelegverkettung und die Prüfung des jeweiligen Startbelegs erforderlich.“
Die Verkettung der einzelnen Startbelege (vom 1. bis zum letzen, welcher gemeldet wurde sowie auch bis zu einer nachträglich hinzugefügten RegK) kann geprüft werden. Diese Daten müssen natürlich (nach § 232 BAO) aufbewahrt werden.
Dann kann von jedem verketteten Startbeleg die daraus ausgehende Verkettung der einzelnen DEP pro RegK geprüft werden.
@Dr.Teufl: Gibt es etwas wichtiges zu ergänzen?

**Comment by twisted-pear** [comment]
Das beantwortet aber noch immer nicht wie das DEP einer einzelnen Kassa aufzubewahren bzw. zu prüfen ist. Wenn das DEP einer einzelnen Kassa im Verbund nur den eigenen Startbeleg enthält, dann kann dieses DEP nur geprüft werden wenn alle DEPs bzw. zumindest Startbelege der vorherigen Kassen im Verbund aufbewahrt wurden. (Inklusive solcher, die vielleicht bereits außer Betrieb genommen wurden.)

**Comment by AxelKutschera** [comment]
Natürlich sind die einzelnen DEPs (1.) der Startbelege sowie (2.) der einzelnen Kassen für diese Prüfungen nach § 132 BAO aufzubewahren. (siehe meine Ausführung oben)
* FON muss nicht und wird auch nicht über die komplette Kette informiert. Lediglich der letzte Startbeleg aus der Verkettung der Startbelege muss hinterlegt werden. Dann kann nachvollzogen werden, dass die vorhergehenden Startbelege der einzelnen Kassen korrekt verkettet wurden.. Und es kann auch keine Kasse aus dem Verbund "verschwinden".
* Die DEP (und noch mehr, auch die Belegdaten usw) sind immer vollständig aufzubewahren. Daraus kann die Verkettung inklusive der Verzweigungen aus den Startbelegen nachgerechnet werden. 
Das BMF wird dies wohl in der internen Prüfroutine (zB ohne Kontrolle der Zertifikatsseriennummer) berücksichtigen.

**Comment by twisted-pear** [comment]
Danke für die Antworten.

Wie kann jetzt jemand der das implementieren muss prüfen ob die erstellten DEPs in Ordnung sind? Das Prüftool sagt ja im Moment, dass die Verkettung beim Startbeleg nicht passt. Wenn man in ein erstelltes DEP vor den ersten Beleg die vorhergehenden Startbelege in der richtigen Reihenfolge einfügt und das Prüftool das Ergebnis durchlässt, kann man dann davon ausgehen, dass das erstellte DEP und die Implementierung des Verbunds in Ordnung sind?

**Comment by asitplus-pteufl** [comment]
Ich fasse die Punkte aus der technischen Sicht zusammen (das meiste wurde ohnehin schon erwähnt):
Bsp Kassenverbund mit 30 Kassen:

- Verkettung: Die 1. Kasse erhält "normalen" Startbeleg mit Verkettung auf Kassen-ID. Die 2. Kasse wird auf Startbeleg der 1. Kasse verkettet. 3. auf 2. usw. bis zur 30.

- Kassen-ID: Alle Kassen im Verbund haben die gleiche Kassen-ID

- Belegnummern: Es muss eine Unterscheidung der Kassen in den Belegnummern enthalten sein (unterschiedliche Nummernkreise, siehe Erlass)

- AES-Schlüssel: Es muss für alle Kassen im Verbund der gleiche Schlüssel verwendet werden.

- Registrierung der Kassen, Prüfung des Startbelegs: Es wird eine Kasse registriert. Zur Prüfung wird der Startbeleg der letzten Kasse im Verbund übermittelt (im oberen BSP der Beleg der 30. Kasse).

- Hinzufügen von Kassen: Kommen neue Kassen hinzu werden diese nach dem oben beschriebenen Muster verkettet: also z.B. die 31. mit der 30. Es müssen alle Startbelege diese neuen Kassen geprüft werden.

- Jahresbelege: Es reicht einen Jahresbeleg einzureichen (von einer Kasse des Verbunds).  

-Prüftool: Die Änderungen werden in einer der nächsten Versionen enthalten sein. Es gibt aber beim DEP nur eine Änderung: Als Startbeleg wird in V1.0.0. nur ein Beleg akzeptiert, der 0 als Umsatzzähler hat, alle Steuersätze gleich 0 sind, UND die Verkettung auf die Kassen-ID enthält. Der letzte Punkt wird für GGS-Systeme entfernt. D.h. es werden auch Belege als Startbeleg akzeptiert die nur die ersten beiden Eigenschaften erfüllen. Sonst ist aber die komplette Belegfolge im DEP gleich und somit auch die Ergebnisse.

-DEPs: jede Kasse im Verbund muss ihr eigenes DEP führen (verhält sich also gleich als ob es eine Kasse von einer Gruppe von Kassen im offenen System ist)
