### ISSUE TITLE
Eclipse Build-Project error

### ISSUE THREAD

**Issue by FriNagy** [a-sit-plus/at-registrierkassen-mustercode#162]
Hallo!

ich habe Eclipse installiert, konfigureiert und ein neue Eclipse Project angelegt...

laut Info:
> Um den Maven Build-Prozess eigenständig durchzuführen, sind folgende Schritte notwendig:
>       regkassen-common: mvn install
>       regkassen-core: mvn install
>       regkassen-democashbox: mvn install

funktioniert so weit, allerdings beim letzen  Build bekomme ich:

The POM for at.asitplus:**regkassen-verification-common:jar:1.0.10** is missing, no dependency information available
Failed to execute goal on project regkassen-demo: Could not resolve dependencies for project at.asitplus.regkassen:regkassen-demo:jar:1.0.0: Failure to find at.asitplus:regkassen-verification-common:jar:1.0.10 in http://repo.maven.apache.org/maven2 was cached in the local repository, 

und so, kann ich leider das Programm nicht erstellen
getestet sowohl als aus-checken mit Git oder installieren von Zip

mach ich selbst was falsch?  
oder fehlt wirklich ein build für regkassen-verification-common

Danke
Frigyes

**Comment by asitplus-pteufl** [comment]
Sie finden die "regkassen-verification" jar files in der release, sie sind teil des prüftools, der Source Code davon ist nicht öffentlich. Sie können diese Jar Files aber entweder direkt in ihr Projekt hinzufügen oder mit dem passenden POM-File in ihr MVN repository kopieren.

**Comment by FriNagy** [comment]
vielen Dank für die schnelle Antwort, ( und das am Wochenende )
ich habe eine weile gegoogelt und es so versucht:

> mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file  -Dfile=C:\REGK\regkassen-democashbox\src\main\java\regkassen-verification-common-1.0.10.jar -DgroupId=at.asitplus -DartifactId=regkassen-verification-common -Dversion=1.0.10 -Dpackaging=jar -DgeneratePom=true

> 

scheint zu funktionieren...
mfg fn

**Comment by xoechts** [comment]
thx - hat funktioniert
