### ISSUE TITLE
DEP Sicherung und DEP Export im Exportformat

### ISSUE THREAD

**Issue by rksvlobster** [a-sit-plus/at-registrierkassen-mustercode#163]
Schönen guten Morgen,

RKSV §7 (3) besagt: 
_"Die Daten des Datenerfassungsprotokolls sind zumindest vierteljährlich auf einem elektronischen externen Medium unveränderbar zu sichern. Diese Sicherung ist gemäß § 132 BAO aufzubewahren."_

RKSV §7 (5) besagt: 
_"Das Datenerfassungsprotokoll einer Registrierkasse muss ab 1. Jänner 2017 jederzeit auf einen externen Datenträger im Exportformat Datenerfassungsprotokoll laut Z 3 der Anlage exportiert werden können."_

RKSV §19 (2) besagt: 
_"Auf Verlangen der Organe der Abgabenbehörde hat der Unternehmer das Datenerfassungsprotokoll für einen vom Organ der Abgabenbehörde vorgegebenen Zeitraum auf einen externen Datenträger zu exportieren und zu übergeben. Der Datenträger ist vom Unternehmer bereitzustellen."_

Das sind die einzigen Passagen, die Export und Sicherung betreffen und daraus scheint folgendes ableitbar zu sein:

1. Bei der vierteljährlichen Komplettsicherung des DEP muss weder ein unformatierter noch ein Export im Exportformat stattfinden.

2. Bei einer vierteljährlichen Komplettsicherung gibt es keine Pflicht Null-Belege zu erzeugen. Die Interpretation des Entwurfes der Erläuterungen zur RKSV Abschnitt "Zu §7": _"In der Sicherung hat der Monatsbeleg des letzten Monats des Quartals, der die Unveränderbarkeit des gesamten Datenerfassungsprotokolls im Wege der Signatur sichert, als letzter Beleg enthalten zu sein."_ ist eben nur eine Interpretation und hat keinen rechtsverbindlichen Charakter.

3. Es müssen weder beim unformatierten noch beim Export im Exportformat auf Anfrage Null- oder Schluss-Belege erzeugt werden.

4. Der §19 (7) scheint sich auf den Export im Exportformat zu beziehen, aber ein teilweiser Export macht keinen besonderen Sinn (ohne Startbeleg -> Gesamtkettenicht gegeben). Abgesehen davon enthielte ein Komplettexport logisch immer auch den Export "im Vorgegebenen Zeitraum" und wäre somit rechtskonform.

Übersehen wir da etwas?

Vielen Dank im Voraus.

**Comment by ErichFreitag** [comment]
Meine Sicht dazu ist folgende:

a) sie müssen Export und Sicherung unterscheiden. Die haben zunächst nichts miteinander zu tun.

b) Export ist der Ausschnitt eines Zeitraums des DEP, der auf Verlangen zur Prüfung übergeben wird. Je nach Zeitraum (theoretisch auf Tagesbasis verlangbar, praktisch wohl eher in Monatsabschnitten) sind Inhalte wie Nullbelege enthalten oder nicht. Es gibt zwei verschiedene DEP-Exports - einen nach § 7 (5) im RKSV-Exportformat und einen nach § 19 (2) seit 01.01.2016 in unstrukturierter Form

c) mit Schlussbelegen hat das gar nichts zu tun, sonst würden sie damit ja die Kasse abmelden

d) auch wenn der Erlass nicht rechtsverbindlich ist werden sie daran nicht herumkommen, noch dazu, wo der Erlass Klarstellungen und Vereinfachungen mit sich bringt

e) (meinen sie § 19 (2)?) § 19 (2) stellt den Export des Datenerfassungsprotokolls in unstrukturierter Form dar, nicht im RKSV-Export-Format. Das entspricht dem auch schon bisher exportierbarem Kassenjournal (Hinweise dazu siehe Erlass und Kassenrichtlinie)

f) auch ein teilweiser Export kann für einen Prüfer Sinn machen, der Startbeleg ist - da ein Zeitraum verlangt werden kann - nicht zwangsläufig enthalten. Das hat aber auch keinen unmittelbaren Zusammenhang zum A-SIT-Prüftool (siehe andere Issues hier zu diesem Thema)

g) die Sicherung ist keine Sicherung im technischen Sinne eines Backups, sondern muss wohl im RKSV-Exportformat durchgeführt werden, um im Falle des Falles zumindest bis zum Quartal davor geprüft werden zu können. Komplettsicherungen sind erwünscht und dürfen vorhergehende Sicherungen überschreiben

h) auf Verlangen müssen Nullbelege erzeugt werden können, die haben aber mit einem Export nichts zu tun

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by Phoniexk** [comment]
@ErichFreitag: Ich hätte da jetzt noch eine Frage.

Export nach §7 (5) im definierten RKSV-Export laut Z3 der Anlage ist klar.

Muss/Soll beim Export des Kassenjournals (Export § 19 (2) ohne Formatvorgabe) nochmals der Inhalt des maschinenlesbaren Codes enthalten sein, oder ist dies nicht notwendig weil ohnehin im Export nach §7 (5) enthalten?

**Comment by ErichFreitag** [comment]
Teilweise. Wenn man die Minimalanforderungen aus RKSV und Erlass etc. addiert ergibt sich folgende Mindeststruktur für den Export des Kassenjournals:

Unternehmensbezeichnung - kann entfallen, da nur ein Unternehmen pro DEP
Kennzeichnung nach Kasse - Kassenidentifikationsnummer
Fortlaufende Nummer des Geschäftsfalls - Belegnummer aus dem RKSV-Beleg
Tag der Belegausstellung - Datum und Uhrzeit des Belegs
Menge und handelsübliche Bezeichnung - z.B. eine Zeile im Export pro Artikel/Produkt
Betrag der Barzahlung - Bruttobetrag und Steuersatz pro Artikel/Produkt
	
Option - Summe der Barzahlung pro Beleg
Option - Besonderheiten (Storno, Zahlungsmittel, ...)
Option - Vorgang (also auch alle nicht-signierten Vorgänge)

Ich würde alles so exportieren, dass ein Bezug/Vergleich zum RKSV-Export klar und einfach ist.

**Comment by AxelKutschera** [comment]
Die kurze Antwort ist:
Alles was digital vorhanden ist muss exportiert werden können.
Das kann auch in mehreren Exportdateien erfolgen.

**Comment by Phoniexk** [comment]
Ok vielen dank für die raschen Antworten!
