### ISSUE TITLE
Schlussbeleg

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#164]
Bei uns sind gerade noch folgende Fragen aufgetaucht:
1. Wer erzeugt einen Schlussbeleg ?
2. Wann wird dieser erzeugt ?
3. Wie soll er aussehen ?

**Comment by ErichFreitag** [comment]
Wer? Derjenige, der die Kasse abmeldet.
Das kann sein
- ein händisch ausgelöster Nullbeleg (mit folgender Kassen-Abmeldung)
- ein händisch ausgelöster Nullbeleg in einem Portal (z.B. bei Diebstahl der Kasse) mit folgender Kassen-Abmeldung
- ein automatisch ausgelöster Nullbeleg über eine Kassenfunktion (mit folgender Kassen-Abmeldung)

Wann und wie? Da finden sich im Erlass ausreichend Informationen:

3.6.2 Der bei einer Außerbetriebnahme einer Registrierkasse zu erstellende Schlussbeleg ist auszudrucken oder elektronisch zu erstellen und gemeinsam mit dem sichergestellten DEP gemäß § 132 BAO aufzubewahren. Eine ausgefallene Registrierkasse ist ohne Erstellung des Schlussbelegs über FON abzumelden. Eine außer Betrieb genommene Registrierkasse kann wieder in Betrieb genommen werden. Diese Inbetriebnahme unterliegt den allgemeinen Verpflichtungen der RKSV in Bezug auf die Inbetriebnahme der Sicherheitseinrichtung. Die Wiederverwendung einer außer Betrieb genommenen Signatur- bzw. Siegelerstellungseinheit ist unternehmensbezogen zulässig. Bei Ausfall der Signatur- bzw.
Siegelerstellungseinheit ist der Schlussbeleg ohne Signatur bzw. Siegel zu erstellen und aufzubewahren

4.5.7 Neben der Verkettung und Signierung der Einzelumsätze dienen die Start-, Monats-, Jahres- und
Schlussbelege als zusätzliche Sicherheiten für die Gewährleistung der vollständigen Erfassung der Umsätze in der Registrierkasse. Diese Belege müssen daher ebenfalls signiert und damit in die Belegkette eingeflochten werden. [...] Zudem bestehen für Start-, Jahres- und Schlussbelege eine verpflichtende Ausdruck- und Aufbewahrungspflicht [...] Start-, Monats-, Jahres- und Schlussbelege sollten als solche bzw. als Nullbelege im Feld der handelsüblichen Bezeichnung gekennzeichnet werden.

**Comment by woko1754** [comment]
Vielen Dank für die Antwort !
