### ISSUE TITLE
KassenId nach einem irreparablem Ausfall wiederverwenden?

### ISSUE THREAD

**Issue by maxp1256** [a-sit-plus/at-registrierkassen-mustercode#165]
Hallo,

darf eine KassenId nach einem irreparablen Ausfall wiederverwendet werden?

Gedachte Vorgehensweise: 
(Ausfall - Hardwaredefekt)
(Ab-)Meldung der ausgefallenen Registrierkasse "Kasse1" via Finanzonline
Anmeldung der neuen Registrierkasse "Kasse1"
Startbeleg mit neuer Hardware von "Kasse1" und Umsatzzähler 0

Gibt es hierzu offizielle Aussagen, ob dies so gemacht werden darf, oder ob zwingend eine neue KassenId verwendet werden muss?

**Comment by ErichFreitag** [comment]
Wenn sie eine neue Kasse mit Startbeleg und Umsatzzähler-Reset verwenden muss auch die Kassen-ID neu vergeben werden und die neue Kasse neu angemeldet werden.

**Comment by maxp1256** [comment]
Gibt es hierzu eine offizielle Aussage, ein Dokument oder einen Gesetzestext?

**Comment by ErichFreitag** [comment]
Nicht in dem exakten Wortlaut, wie sie das wohl meinen.

Es ergibt sich daraus, dass sie eine ausgefallene Kasse nur dann wiederverwenden können, wenn sie die Kasse wieder in Betrieb nehmen können. Das würde bedeuten, dass sie insbesondere das Datenerfassungsprotokoll bis zum letzten Beleg rekonstruieren können und die Belegnummern und die Verkettung fortsetzen.

Ein neuer Startbeleg und ein neuer Umsatzzähler bedeutet auch eine neue Kassen-ID. Sie hätten sonst zwei RKSV-Datenerfassungsprotokolle mit derselben Kassen-ID. 

Dazu passende Gesetzesstellen sind beispielsweise

RKSV § 3 26. Startbeleg: **erster Beleg, der unter Verwendung einer Kassenidentifikationsnummer** erstellt wird und die vollständige Verkettung aller unter dieser Kassenidentifikationsnummer erzeugten und gespeicherten Belege sicherstellt.

RKSV § 17 (6) Wenn nach dem Ausfall einer Registrierkasse ein neues Datenerfassungsprotokoll eingerichtet werden muss, ist als Signatur- bzw. Siegelwert des vorhergehenden Barumsatzes (§ 10 Abs. 2 Z 7) der Signatur- bzw. Siegelwert des zuletzt verfügbaren Barumsatzes bzw. der Signatur- bzw. Siegelwert des Startbeleges im Datenerfassungsprotokoll zu verwenden.

RKSV § 6. (1) Die Inbetriebnahme der Sicherheitseinrichtung für die Registrierkasse besteht aus der Einrichtung des Datenerfassungsprotokolls (§ 7) und der Ablage der Kassenidentifikationsnummer als Bestandteil der zu signierenden Daten des ersten Barumsatzes mit Betrag Null (0) (Startbeleg) im Datenerfassungsprotokoll.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by AxelKutschera** [comment]
@Erich: Die Kassen-ID darf gleich sein wenn der AES-Schlüssel anders ist.

**Comment by ErichFreitag** [comment]
@Axel, absolut korrekt und danke für die Ergänzung. Ich habe es in obigem Kontext gesehen (Startbeleg neu, neue Kassenanmeldung, ...). Außerdem bin ich der Meinung, dass der Wechsel der Kassen-ID am einfachsten und am wenigsten fehleranfällig und am wenigsten erklärungsbedürftig etc. ist.
