### ISSUE TITLE
Betrieb einer Kasse mit 2 Karten

### ISSUE THREAD

**Issue by Flanelli** [a-sit-plus/at-registrierkassen-mustercode#166]
Mag sein dass meine Frage manchem hanebüchen erscheint aber dennoch ..,

Annahme: Man verfügt über über 2 Karten ( die natürlich auch beide beim BMF angemeldet sind )

Ein Kartenwechsel ( aus welchen Gründen auch immer ) stellt ja eigentlich keinen tatsächlichen Ausfall
der Sicherheitseinrichtung dar. 

Daher gehe ich davon aus dass bei Wechsel zwischen 2 registrierten Karten NICHT jedesmal
einen Nullbeleg oder gar einen Startbeleg ( mit der Kassen-ID als vorherige Signatur und Umsatzstand NULL ) erstellen muss.

Sehe ich das richtig?
Herzlichen Dank für die Aufmerksamkeit

**Comment by asitplus-pteufl** [comment]
Sie können beliebig aus dem Pool der registrierten Signatureinheiten wählen. Auch bei jeder Signatur wechseln. Natürlich muss dann kein Nullbeleg, Startbeleg erstellt werden.
Dringende Empfehlung: Das Detailfragendokument im Detail lesen.
