### ISSUE TITLE
Verification depformat failed / Prüftool 1.0.0

### ISSUE THREAD

**Issue by pagogc** [a-sit-plus/at-registrierkassen-mustercode#167]
Hallo zusammen,
bin auch gerade an der Integration der RKSV für unser System, zum Abschluss wollte ich nun den Startbeleg überprüfen, dieser schlägt jedoch fehl in FON.
(wir haben vom Kartenhersteller eine Echtkarte bekommen, mit der wir auch im FON gegentesten können).
Da ja das Prüftool regkassen-verification-depformat-1.0.0.jar die gleiche Logik abbildet, haben wir es mit unserem DEP versucht, bekommen jedoch ebenfalls ein FAIL bei:

""verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur","

Die Frage ist jetzt... warum?

Wir haben bereits überprüft:
- header.payload -> lassen sich sauber entschlüsseln, auch mit diversen anderen Tools probiert, ob wieder der richtige String rauskommt.
- Codierung BASE64URL -> scheint korrekt, auch mit diversen Tools gegengeprüft.
- Formatierung der Signatur -> auch korrekt (wir nehmen das RAW von der Signaturkarte und codieren es in BASE64URL). Auch hier geprüft: Entschlüsselung des BASE64RUL Werts in HEX und gegengeprüft mit IDE Debugger und dessen HEX werte der Signatur.
- Signatur der Karte gegen die Karte nochmal verifizieren lassen -> Signatur wird als OK ausgegeben.

Uns fehlt irgendwie der Ansatz, was wir noch prüfen können bzw. was genau durch das A-SIT Tool geprüft wird, warum es fehlschlägt?
Wir haben auch schon eine Supportanfrage/Telefonat mit unserem Kartenhersteller geführt:
"Signatur sei korrekt und LDAP Service ruft auch das korrekte Zertifikat ab."
Prüft das Prüftool überhaupt das Zertifikat über einen LDAP Service?
Gibt es eventuell den Source dazu?

Anbei auch das komplette Log vom Prüftool:
[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/597239/0000_cashbox_full.txt)

Diesen entnehmen wir, dass alle anderen Logischen Prüfungen (darunter auch das Entschlüsseln des Umsatzzählers) korrekt ist.
Die "oberen 2 Fails" sind ja nur begründet aufgrund der fehlgeschlagenen Signatur, nehme ich an.

Vielleicht noch als Hinweis:
Wir benutzen AES256 CRT Modus direkt (also nicht Simulation über ECB/CFB wie in DemoCashbox Source) von openssl (EVP_aes_256_ctr).

Freue mich auf Vorschläge, wir sind mittlerweile komplett ratlos :(.

Mfg

**Comment by asitplus-pteufl** [comment]
was übermitteln sie als hash-wert an die kasse? wie berechnen Sie den hash, welche Daten gehen rein? Senden Sie sicher den Hash an die Karte oder den "plain text"?

**Comment by pagogc** [comment]
> was übermitteln sie als hash-wert an die kasse?
header.payload
> wie berechnen Sie den hash, welche Daten gehen rein? 
Wir nehmen "header.payload" und codieren den SHA256.
SHA256 Funktion von Openssl.
> Senden Sie sicher den Hash an die Karte oder den "plain text"?
Diesen SHA256 übergebe ich Byte für Byte dann an die PSO Commandkette, und diese dann der Signierfunktion der Karte.
Also ja, der Hash wird signiert, nicht "header.payload".

**Comment by ErichFreitag** [comment]
Vielleicht hilft ihnen das folgende Bild - da sind alle kritischen Vorgänge (rosa) bezüglich Signaturerstellung enthalten (Vollständigkeit und Korrektheit ohne Gewähr). Es sollte selbsterklärend sein - beginnen können sie beim Umsatz (grün) oder bei der Signatur (blau). Die Nummern beziehen sich auf die A-SIT-Prozesse im Dokument "Detailfragen".

![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/20393888/e5d4de94-acdd-11e6-9bb6-bc596f12064a.jpg)

**Comment by pagogc** [comment]
Danke @ErichFreitag für die Details.

Ich verstehe wie gesagt, trotzdem mein Problem nicht.
Ich mache es genauso, wie hier beschrieben:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/147

Also header.payload (beides BASE64URL), darüber den SHA256 Hash bilden und diesen Hash an die Karte geben.
Das Ergebnis der Karte (64BYTEARRAY) im RAW zustand hernehmen, BASE64URL codieren und an header.payload anhängen.
Danach von BASE64URL in BASE64 und dem Maschinencode anhängen.

**Comment by ErichFreitag** [comment]
Da kann ich naturgemäß nur vermuten, aber wenn sie schon auf (3) 1. Hash hinweisen dann hängt es wie beschrieben von der Umgebung ab.  Details dazu kann ich keine weiteren nennen.

Vielleicht hilft auch noch https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/133, https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/39 oder https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/111 weiter. 

Wenn ich nichts übersehen habe, sind all diese Fälle auch in der Grafik angeführt. Leider bleibt wohl nur einen Schritt nach dem anderen zu überprüfen.

**Comment by pagogc** [comment]
Nach langen suchen war es doch ein Datenfehler unsererseits.

Header war falsch.
Fragen Sie lieber nicht, wie sowas einfaches passieren konnte ;).

Trotzdem vielen vielen Dank für die Unterstützung aller Beteiligten, ich hangle mich jetzt durch die nächsten Fehler durch :)
