### ISSUE TITLE
Umsatzcodierung falsch, openssl 

### ISSUE THREAD

**Issue by pagogc** [a-sit-plus/at-registrierkassen-mustercode#168]
Hallo zusammen,
ist vielleicht nicht direkt der richtige Frageort, aber aktuell meint das Prüftool meinen Umsatzzähler nicht entschlüsseln zu können.

Unser Decode gibt dies jedoch sauber zurück.

Daher habe ich das Beispiel von hier nachgespielt: 
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/91#issuecomment-225116614

und ich bekomme einen anderen BASE64 Code.

Ich wende mich jetzt an die Teilnehmer hier, da ich bei den Implementationsdetails der OpenSSL (Version 1.0.2.11) in C++ Schwierigkeiten habe und keine Idee mehr, was falsch läuft.

Codesnippet von unseren Wrappern:
![screenshot_704](https://cloud.githubusercontent.com/assets/6831150/20410113/d3b76e00-ad1b-11e6-86eb-33ce1e6c9e51.png)

Eigentliche Verschlüsselungsmethode:
![screenshot_705](https://cloud.githubusercontent.com/assets/6831150/20410141/0051d860-ad1c-11e6-876a-717ec36340ab.png)

Details zum Input:
Passwort ist: WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=
IV: 3e 04 75 88 e2 0f 53 f9 2b bd f4 a9 c0 12 40 0d
Umsatz:  00 00 00 00 00 00 15 85

Ich habe schon mehrere Versuche gemacht, auch von CTR auf CFB Modus geschalten, aber ich bekomme beim besten willen nicht das gleiche Ergebnis wie User 01af:
ByW5rsidWYI=

Mein Ergebnis:
M6iAUXA1jYo=

Durch die Annahme von DemoCashBox.java, müsste doch das Endprodukt gleich sein, oder?

Hat jemand zu mindestens einen Tipp, was ich falsch mache?

Schonmal vielen Dank im Voraus.
LG

**Comment by asitplus-pteufl** [comment]
Aus einer anderen Perspektive: Kodieren Sie den Umsatzzähler vorher korrekt (litte/big endian, two's complement)? Sie könnten mal 0 verschlüsseln, da spielt die Kodierung noch keine Rolle. Wenn das Prüftool dann auch 0 rausbekommt und bei den anderen Umsatzzählern ein Problem macht, dann liegt es vielleicht an der Kodierung. Ist ein schneller check, denn Sie unbedingt vor weiteren Detailanalysen zur Verschlüsselung machen sollten.

**Comment by pagogc** [comment]
Danke für den Tipp.
Beim Kontrollieren des Umsatzzählers, habe ich auch nochmal den IV und den KEY mir im Detail angeschaut.
Dabei habe ich bemerkt, dass der KEY BASE64 kodiert an die Funktion durchgegeben wird, was so nicht funktionieren konnte.

Nach erfolgreicher Decodierung funktioniert nun auch die AES Funktion.
Prüfung von 0 Beleg und normalen Beleg im Prüftool korrekt.
FON steht auch auf Grün :).

**Comment by asitplus-pteufl** [comment]
perfekt. bitte aber auch die entwicklung des umsatzzählers in einem DEP prüfen (positiv, negativ) dann sind Sie auch sicher dass dies alles passt.
