### ISSUE TITLE
Klärung Frage: Input für Sig-Voriger-Beleg

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#17]
In der Funktion calculateSignatureValuePreviousReceipt in DemoCashBox.java wird der Text aus der Anlage zur RKSV, Seite 12, 4. "Klartextdaten für das Signaturformat für die Signierung durch Signaturerstellungseinheit" Punkt "Sig-Voriger-Beleg", der wie folgt lautet:
"Als Input der dieser Hash-Funktion wird das Ergebnis der Signaturerstellung gemäß Z6 verwendet"
dies wird in der vorliegenden Implementierung - siehe Kommentar unten - so interpretiert, dass der gesamte Jws String als Input verwendet wird.

Andere Interpretationen könnten aber auch lauten: 
"Der Wert dieses Feldes entspricht dem in §9 Abs. 2 Z7 angegebenen Wert. JSON Format string"
In diesem §9, Abs. 2 Z7 steht:
"Signaturwert des vorhergehenden Barumsatzes des Datenerfassungsprotokolls (Verkettungswert laut Z4 der Anlage"
Also: Sig-Voriger-Beleg == Signaturwert vorhergehender Barumsatz in DEP (ohne Veränderung)
=> Ein 1:1 Vergleich der beiden Strings wäre direkt möglich.

oder....
dass aus Z6 - Punkt 3 "dem berechneten Signaturwert"  daraus die ersten N (8) Byte extrahiert - verwendet wird. Dies würde bedeuten, dass für den Signaturwert des vorherigen Beleges und der Sig-Voriger-Beleg des aktuellen Beleges, die ersten 10 Zeichen des Base64-Url-Encoded String  gleich wären.
=> ein direkter Vergleich der ersten 10 Zeichen wäre möglich.

Die unten umgesetzte Lösung ermöglicht keinen direkten Vergleich der Signaturwerte "Sig-Voriger-Beleg" mit dem Signaturwert des vorhergehenden Barumsatzes im DEP.

Ich bitte um Feedback diesbezüglich.

 //Detailspezifikation Abs 4 "Sig-Voriger-Beleg"
            //if the first receipt is stored, then the cashbox-identifier is hashed and is used as chaining value
            //otherwise the complete last receipt is hased and the result is used as chaining value
            if (receiptPackage == null) {
                inputForChainCalculation = cashBoxParameters.getCashBoxID();
            } else {
                inputForChainCalculation = receiptPackage.getJwsCompactRepresentation();
            }

**Comment by pteufl** [comment]
Der Muster-Code wurde in Abstimmung mit dem BMF für die Klärung der Interpretationsspielräume veröffentlicht. Die Vorgehensweise, die im Code definiert ist (Hash über vorigen Beleg bzw. Kassen-ID) ist die korrekte (definierte).
Technischer Hintergrund dazu: Hätte man nur z.b. X Zeichen der Signatur genommen so würde es sehr stark vom Signatur-Algorithmus abhängen um welche X Zeichen der Signatur-Kodierung es sich handelt (in einem Worst-Case Szenario wären dies vielleicht nur Meta-Informationen). Um hier ein generisches Verfahren zu verwenden, das unabhängig vom Signaturalgorithmus die gleichen Eigenschaften hat, wurde die Entscheidung getroffen den Hash-Wert des vorigen Belegs zu nehmen. Dies entspricht auch der Verordnung da ja die Signatur des vorigen Belegs ebenso in die Verkettung eingeht.
Die gesamte Signatur konnte aus Platzgründen nicht genommen werden (dies würde das vorige beschriebene Problem der Allgemeinheit natürlich lösen).

**Comment by anzun** [comment]
vielen Dank für die rasche Antwort
