### ISSUE TITLE
Bechereinsatz_Minusartikel

### ISSUE THREAD

**Issue by Quori** [a-sit-plus/at-registrierkassen-mustercode#170]
Guten Tag!
Ist eine Buchung von zwei Artikeln der selben Warengruppe mit einem Minusartikel(z.B. Bechereinsatz) auf den selben BON zulässig? oder müssen zwei getrennte Belege registriert werden.

Vielen Dank für Ihre Antwort!

**Comment by AxelKutschera** [comment]
Guten Morgen, 
außer bei Nullbelegen sind alle Kombinationen möglich.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
