### ISSUE TITLE
Sonderbelege Start, Null(Sammel, Monats, Jahresbelege)

### ISSUE THREAD

**Issue by texTec** [a-sit-plus/at-registrierkassen-mustercode#171]
Muss es sich bei den Sonderbelegen Start, Null(Sammel, Monats, Jahre-Belege) um reale Belege handeln oder können diese auch nur "virtuell" für das DEP erzeugt werden. Natürlich mit korrekter Signatur und jederzeit über das DEP nochmals druckbar. Soll heißen: Es wird kein Artikel mit Wert 0 gebucht und es wird eine spezielle Belegnummer vergeben. (keine Auswirkung auf reale fortlaufende Kunden-Belege).

Beispiel Beleg-Folge:
Start-20161122 (Startbeleg --> Virtueller Beleg nur fürs DEP)
1
2
3
Null-20161122-1 (Sammelbeleg --> Virtueller Beleg nur fürs DEP)
4
..
100
Null-201611 (Monatsbeleg --> Virtueller Beleg nur fürs DEP)
101
102
..
1030
Null-2016 (Jahresbeleg --> Virtueller Beleg nur fürs DEP)

Die Prüfung mittels der bereitgestellten Tools bringt hier keine Fehler.
Ist dies jedoch zulässig ?

**Comment by ErichFreitag** [comment]
Darauf gibt u.a. der Erlass vom 04.08.2016 Antwort:

Erlass 3.6.2 "Der bei einer Außerbetriebnahme einer Registrierkasse zu erstellende Schlussbeleg ist
auszudrucken oder elektronisch zu erstellen und gemeinsam mit dem sichergestellten DEP
gemäß § 132 BAO aufzubewahren".

Erlass 4.5.7 "Zudem bestehen für Start-, Jahres- und Schlussbelege eine verpflichtende Ausdruck- und
Aufbewahrungspflicht" sowie "Der Registrierkassenpflichtige hat daher am Ende des Kalenderjahres bzw. am letzten Tag seiner getätigten Umsätze, grundsätzlich bis zum 31. Dezember, den Jahresbeleg herzustellen und nach Ausdruck aufzubewahren".

In der RKSV in der Version BGBl. 210/2016 ist die Ausdruckspflicht für den Startbeleg entfallen, im Erlass ist sie enthalten. RKSV § 6 (4): "Der Unternehmer hat unmittelbar nach der Registrierung (§ 16) die Erstellung der Signatur bzw. des Siegels [...] unter Zuhilfenahme des Startbeleges zu überprüfen. [...] Das Prüfergebnis ist zu protokollieren und mit dem Startbeleg gemäß § 132 BAO aufzubewahren".

Was aus § 6 RKSV auch hervorgeht ist, dass "ein Prüfergebnis zu protokollieren" ist. Wenn sie mit Finanz-Online arbeiten haben sie zumindest ein Online-Prüfergebnis. Wenn sie mit der Prüf-App arbeiten müssen sie den Beleg ohnedies ausdrucken.

Der Startbeleg ist damit auch nicht "nur" virtuell, sondern muss wie der Jahresbeleg geprüft werden. Achten Sie auch auf die vorgegebenen Inhalte (z.B. "Start-, Monats-, Jahres- und Schlussbelege sollten als solche bzw. als Nullbelege im Feld der handelsüblichen Bezeichnung gekennzeichnet werden"). Mit dem RKSV-DEP-Export könnten sie das nicht nachvollziehen.

**Comment by texTec** [comment]
Womöglich habe ich mich mit dem Wort "virtuell" missverständlich ausgedrückt.

Bei "normalen" Belegen die an den Kunden gehen habe ich einen Beleg (mit diversen Leistungen) und einen Eintrag im DEP der auf den Beleg verweist. Für die Sonderbelege die zur Erfüllung der RKSV benötigt werden habe ich "nur" einen Eintrag im DEP (ohne Verweiß auf einen Beleg mit Leistungen). Selbstverständlich richtig verkettet mit den anderen Belegen. Da im DEP jedoch die komplette JWS-Struktur (inklusive Signature) abgelegt ist habe ich jederzeit die Möglichkeit den START, MONATS, JAHRESBELEG unverändert und prüfbar zu drucken. (Startbeleg wird über FON Webservice geprüft).

Da die Sonderbelege ohnehin keine wirklichen Leistungen/Artikel enthalten, könnte die gedruckte Form 
auch von den "normalen" Belegen abweichend gestaltet werden.

Beispiel Start-Beleg:
![startbeleg](https://cloud.githubusercontent.com/assets/23652559/20524095/fa424338-b0b8-11e6-8421-e91a2309d756.jpg)

Was diese Sonderbelege von den "normalen" Belegen unterscheidet ist somit der Druck + die Belegnummern außerhalb des Belegkreises der Kundenbelege.

**Comment by ErichFreitag** [comment]
a) ich habe noch nicht ganz verstanden, warum sie die Nullbelege überhaupt anders gestalten möchten, sowohl vom Layout als auch von der Belegnummer her. Die Nullbelege sind ja - mit Ausnahme der Sonderbezeichnungen - ganz normale Belege mit einem Barumsatz von 0. Mit Sprüngen in Belegnummern ist halt immer die Nachvollziehbarkeit deutlich schwieriger als bei durchgängigen Nummern.

b) bitte noch um folgende Aufklärung - von welchem DEP sprechen sie? Vom "Kassenjournal"-DEP oder vom RKSV-DEP? Im RKSV-DEP ist z.B. die Bezeichnung "Monatsbeleg" nicht mehr ersichtlich.

c) der QR-Code ist (noch?) nicht korrekt, aber das nur am Rande

d) die gedruckte Form ist nicht vorgegeben, sie können also den Startbeleg wie oben erstellen. Die Idee finde ich gut, die Inhalte sind außer dem Summenzähler allerdings sowieso im QR-Code im Klartext lesbar. Beim Sammelbeleg müssten sie zusätzlich zumindest Beginn und Ende des SE-Ausfalls angeben.

f) es heißt "Summenspeicher" oder "Umsatzzähler", nicht "Summenzähler" (aber das auch nur am Rande). Ob sie den angeben wollen ist eine Frage, weil er ja an sich verschlüsselt ist und nicht im Klartext ersichtlich sein sollte

**Comment by texTec** [comment]
Hallo,

Danke für die Antworten.

a) Eigentlich nur für die Entkoppelung der RKSV-"Sonderbelege" von den "normalen" Kundenbelegen.

Da es sich in unserer Branche immer um Belege gegen einen bestimmten Kunden handelt wäre es zudem von der Implementierung her einfacher. Ansonsten muss ich einen internen Null-Artikel auf ein internes Null Konto gegen einen internen Null Kunden buchen und daraus einen Beleg erstellen. Jetzt würde z.B. nur die JWS Struktur für die "Sonderbelege" erzeugt und in das DEP eingetragen werden.

Zudem wäre es für die Buchhaltung einfacher da diese "Sonderbelege" die nur der RKSV dienen klar von anderen Belegen unterscheidbar sind und gegebenenfalls gar nicht in die Buchhaltung gelangen.

b) Ich spreche vom RKSV-DEP. Im Kassenjournal-DEP würden diese RKSV-"Sonderbelege" nicht aufscheinen. (deshalb sprach ich Eingangs von virtuellen Belegen).

c) Scheint wohl nur eine falsche Einstellung des QR-Code Controls am Report zu sein, da die Daten vom Prüftool als richtig bewertet werden. Ist dieser QR-Code nun korrekt ?

![qr](https://cloud.githubusercontent.com/assets/23652559/20526724/99ee05be-b0c5-11e6-8e50-5b078e3a50f2.jpg)

Danke für die Bemühungen

**Comment by ErichFreitag** [comment]
zu c) noch nicht ganz: \000004_R1-AT1_1_START-20161122_2016-11-22T14:12:11_0,00_0,00_0,00_0,00_0,00_u9jdZMQax2Q=_235FA560_a4ayc/80/OE=_cHuCnXjX2aT3wpG7CUURKfyQCQsOvY2cA2OcGTqCCU05oP6fhWwnPRAHghs9lB57s8ie7f9rq0vORvAvRTbfjQ== - da gehört das  \000004 am Beginn entfernt.

Falls es eine Bedeutung hat - zuvor war es die Kasse 2, hier ist es die Kasse 1

zu b) dann haben sie das "Problem", dass sie Belege im RKSV-DEP nicht entsprechend kennzeichnen können - also wie oben gemäß Erlass "Start-, Monats-, Jahres- und Schlussbelege sollten als solche bzw. als Nullbelege im Feld der handelsüblichen Bezeichnung gekennzeichnet werden" dort nicht enthalten sind. Sie können zwar im Grunde jeden Nullbeleg auch ohne Kennzeichnung logisch finden und zuordnen - es wird halt nur um einiges mühsamer. Die Ausdruckpflicht gemäß Erlass bleibt auch bestehen.

zu a) ich verstehe die Hintergründe und meine, dass es theoretisch so möglich weil ja nachvollziehbar ist. Ich (meine persönliche Meinung) bin aber auch sehr skeptisch, ob sie sich mit eigenen Belegnummern und Belegen außerhalb des Kassenjournals nicht mehr Schwierigkeiten bei Prüfungen einhandeln, als Null-Umsätze zu generieren, unter Umständen vielleicht auch beispielsweise gegen die Kassenrichtlinie 2012 verstossen könnten (...auch Aufzeichnungen über Ereignisse, die letztendlich keinen Geschäftsvorfall bewirken, der infolge finanzieller Auswirkungen auf das Unternehmen als Ereignis im Geschäftsprozess - in Buchführung und/oder Aufzeichnungen - zu erfassen wäre, sollen - insoweit diese Vorgänge erfasst wurden – aufbewahrt werden. [...] sonstige Vorgänge im Geschäftsprozess, insoweit diese aus Gründen der Überprüfung der vollständigen und richtigen Erfassung aller Geschäftsvorfälle oder aus sonstigen für die Abgabenerhebung bedeutsamen Gründen aufzeichnungs- bzw. aufbewahrungspflichtig sind". Da könnte man z.B. den Jahresbeleg schon dazurechnen.

Auch weil sie ja ohnedies die Nullbelege besonders behandeln müssen - siehe oben Kennzeichnung, Prüfung Startbeleg und Jahresbeleg, Angabe Beginn und Ende SE-Ausfall im Sammelbeleg.

**Comment by texTec** [comment]
Ok, dann werde ich hier wohl sicherheitshalber den komplizierteren aber bei Prüfungen unproblematischeren Weg einschlagen.

Danke für Ihre Bemühungen.
