### ISSUE TITLE
aufeinanderfolgende Inbetriebnahme und Außerbetriebnahme

### ISSUE THREAD

**Issue by eczach** [a-sit-plus/at-registrierkassen-mustercode#172]
hallo!
möchte hier gerne meine fragen zusammenfassen, die sich mir beim mitlesen der letzten threads aufgetan haben und bitte im rückmeldung:

eine kassa wird mit schlussbeleg außer betrieb genommen.
nach einiger zeit wird die gleiche kassa (id, aes, dep) wieder in betrieb genommen. 

- wird in diesem fall nun als verkettungswert die kassen-id oder die letzte signatur (also die des schlussbelegs) herangezogen?
- wird der umsatzzähler auf 0 gestellt oder der letzte wert des umsatzzählers (der zum zeitpunkt des schlussbelegs) herangezogen?

danke
ernst c. zach

**Comment by ErichFreitag** [comment]
Wenn sie die gleiche Kasse wieder in Betrieb nehmen und dort fortgesetzt werden kann wo sie aufgehört haben ist lediglich eine Wiederinbetriebnahmemeldung erforderlich. Also letzte Signatur des Schlussbelegs und Umsatzzähler Letztstand. Das ist z.B. bei Saisonbetrieben typisch.

**Comment by Zachi67** [comment]
Servus, ich stehe vor einem ähnlichen Problem. Wofür genau der Schlussbeleg nach obigem Kommentar nötig sein soll, will sich mir nicht so recht erschließen... Unter der Voraussetzung, dass das Prüftool dieselben Algorithmen verwendet, wie das BMF, kann aus meiner Sicht das folgende behauptet werden: Es kann nicht fest gestellt werden, welcher Typ von Nullbeleg erstellt wurde, somit könnte ich zur Außerbetriebnahme verwenden, welchen ich will (z.B. einen Jahresbeleg). Einen Startbeleg für die Wiederinbetriebnahme zu erstellen, nachdem ich meine Kasse mit einem Schlussbeleg außer Betrieb genommen habe, ist wohl eine schlechte Idee, denn da legt sich das Prüftool auf die Bretter. Es erscheint damit am einfachsten, einen Nullbeleg mit entsprechender Bezeichnung zu erstellen, um eine Kasse wieder in Betrieb zu nehmen, nachdem ich einen Schlussbeleg erstellt habe. Ob das passt? Keine Ahnung, wir werden das so mal implementieren.

**Comment by ErichFreitag** [comment]
Zum Schlussbeleg: RKSV § 17 (8) Im Fall einer planmäßigen Außerbetriebnahme der Registrierkasse (Abs. 1 Z 3) hat der Unternehmer einen Schlussbeleg mit Betrag Null (0) zu erstellen. Der Schlussbeleg ist auszudrucken und gemäß § 132 BAO aufzubewahren. 

Als Außerbetriebnahme gilt alles, was nicht nur vorübergehend ist, typisch 48 Stunden.

Der Schlussbeleg ist als solcher zu kennzeichnen und damit nicht ident mit dem Jahresbeleg. 

Ein neuer Startbeleg ist bei Weiterführung der Kasse schlichtweg falsch. Vor allem dann, wenn damit die Einrichtung des DEP etc. verbunden ist.

Zur Wiederinbetriebnahme brauchen sie keinen Nullbeleg, es genügt die Fortsetzung. Schaden tut aber ein Nullbeleg auch nichts. Achten müssen sie z.B. bei Saisonkassen, dass bei einem Jahreswechsel der Jahresbeleg als erster Beleg erstellt werden muss.

Formal haben sie schon auf den ersten Blick recht - Nullbeleg ist Nullbeleg. Auf den zweiten Blick sind damit jedoch Prüfungen, Bezeichnungen und spezielle Inhalte (Sammelbeleg) erforderlich.

**Comment by Zachi67** [comment]
Das hört sich erst mal stimmig an. Jetzt komme ich aber auf folgendes Problem: Ich habe bis zum 31.12. kassiert, die letzten Belege sind notsigniert (mit "Sicherheitseinrichtung ausgefallen" markierte Belege). Am 02.01. will ich weiter arbeiten. Ist meine Sicherheitseinrichtung nach wie vor nicht verfügbar, so würde ich jetzt die Fortsetzung des Kassierens unterbinden ("[...] bei einem Jahreswechsel der Jahresbeleg als erster Beleg erstellt werden muss [...]", siehe Kommentar Erich Freitag). Kann ich hingegen arbeiten, weil meine Sicherheitseinrichtung wieder verfügbar ist, darf ich dann zuerst den Sammelbeleg und im Anschluss den Jahresbeleg erstellen oder muss ich zwingend erst den Jahresbeleg erstellen? Brauche ich weiterhin im Januar zum Jahresbeleg zusätzlich einen Monatsbeleg oder reichen je Jahr 11 Monats- und ein Jahresbeleg?

**Comment by areiter** [comment]
@Zachi67 bzgl. ihrer ersten Anmerkung. Diese Frage habe ich beim letzten Registrierkassen Meeting gestellt. Antwort von Hrn. Engelbert war dass der Jahresbeleg tatsächlich gültig signiert sein muss. Sollte zu diesem Zeitpunkt die Sicherheitseinrichtung ausgefallen sein kann aber weitergearbeitet werden und es kann zu einem späteren Zeitpunkt (sobald die SE wieder funktionsfähig ist) ein weitere "Jahresbeleg" (Nullbeleg) erstellt werden, der dann an FON gesendet wird.

Ich nehme an das wird in die nächste Version der FAQs aufgenommen werden.

**Comment by ErichFreitag** [comment]
Zum zweiten Teil - es sind 11 Monatsbelege und ein Jahresbeleg.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by eczach** [comment]
darf ich dann nochmal wegen meiner eingangsfrage - die aus meiner sicht ja eine technische ist - nachfragen: 

eine kassa wird mit schlussbeleg außer betrieb genommen.
nach einiger zeit wird die gleiche kassa (id, aes, dep) wieder in betrieb genommen.

    wird in diesem fall nun als verkettungswert die kassen-id oder die letzte signatur (also die des schlussbelegs) herangezogen?
    wird der umsatzzähler auf 0 gestellt oder der letzte wert des umsatzzählers (der zum zeitpunkt des schlussbelegs) herangezogen?

danke!

**Comment by ErichFreitag** [comment]
Wie oben - letzte Signatur, letzter Umsatzzähler - als "wäre nichts passiert". Was dazu kommt ist die Meldung der Wiederinbetriebnahme an Finanz Online.

**Comment by eczach** [comment]
vielen dank! für mich wäre das auch logisch und wollte nur nochmals nachfragen, da ja im thread hr.teufl geschrieben hat, dass nur pteufl, tzefferer, asitplus-pteufl gesichert korrekte aussagen treffen können :-)
so steht ja im detailfragendokument explizit _"Startbeleg (siehe 2.2.2): Bei Startbelegen wird der Umsatzzähler auf den Wert 0 gesetzt und verschlüsselt"_ und _"Beim Startbeleg wird der Verkettungswert über die Kassen-ID gebildet"_ 
ich habe bislang keine passage in den dokumenten gefunden, die mein geschildertes szenario mit der konsequenz, dass ein startbeleg auch in "normaler verkettung" gebildet werden kann, gefunden. somit meine bitte an die "offiziell aussageberechtigten" hier um eine antwort :-)

**Comment by ErichFreitag** [comment]
Ich kommentiere das mal und vielleicht möchte Hr. Teufl das bestätigen oder ergänzen.

Ich kann ihnen einen anderen Blickwinkel auf die Thematik anbieten. Der Startbeleg ist zunächst genauso ein Nullbeleg wie jeder andere Nullbeleg (Monatsbeleg, Sammelbeleg, Kontrollbeleg, ...). Sie können grundsätzlich beliebig viele Nullbelege generieren und einschieben - die haben keinerlei Konsequenz (außer dass vielleicht jemand frägt wozu).

Sie können die Nullbelege auch (mit Ausnahme der Bezeichnungen und der zusätzlichen Inhalte des Sammelbelegs) nicht unterscheiden. Sie können diese lediglich logisch zuordnen.

Nur die Konsequenzen, die mit Nullbelegen, die zu bestimmten Zeitpunkten zu generieren sind, unterscheiden sich. Der Jahresbeleg ist beispielsweise auszudrucken und zu prüfen.

Und die Konsequenz des Startbelegs ist, die RKSV-Konformität der Kasse zu starten. Daraus resultiert wieder, dass der Umsatzzähler auf 0 gesetzt werden muss. Und damit wieder das RKSV-Datenerfassungsprotokoll initialisiert werden muss. Und die Kasse zuvor angemeldet werden muss.

Also - die reine Erzeugung eines Nullbelegs mit der Bezeichnung "Start" ist nichts anderes als ein Nullbeleg. Sie müssen ja auch keinen "Startbeleg" generieren, sie müssen lediglich einen Barumsatz von 0.- generieren und damit die ganze Maschine starten und den Beleg auf Korrektheit prüfen.

Genauso können sie zu einem Tagesabschluss einen Nullbeleg einschieben (halt ohne weitere Konsequenzen). Oder sie können einen Barumsatz von 0.- EUR zu Monatsbeginn erzeugen und den als Monatsbeleg betrachten (die sinnvolle Bezeichnung fehlt hat). Und so weiter. Einzige Ausnahme: der Sammelbeleg wird auf Grund der Inhalte mehr Logik benötigen als ein reiner Barumsatz von 0.-.

Was sie halt nicht tun dürfen ist mit einem Start-Nullbeleg für die selbe Kassen-ID und AES etc. den Umsatzzähler auf 0 setzen, wenn die identische Kasse schon mal in Betrieb war.

Vielleicht hilft die Verabschiedung von den Begriffen und die Betrachtung als Nullbelege sowie die damit verbundene Logik.

**Comment by eczach** [comment]
vielen dank für ihre gedanken - ich habe die logik des ganzen auch so als sinnvoll verstanden und umgesetzt und warte auf die bestätigung :-)

**Comment by AxelKutschera** [comment]
Nur ein ergänzender Gedanke: Ich meine, dass es nach einer Außerbetriebnahme der RegK keine Wiederinbetriebnahme möglich ist.

**Comment by eczach** [comment]
warum? kann nicht ein betrieb ein seiner registrierkassen eine zeitlang außer betrieb nehmen und z.b. ein halbes jahr später wieder in betrieb nehmen? z.b. nach auflösung einer filiale und neueröffnung einer anderen einige zeit später?

**Comment by AxelKutschera** [comment]
Nach meinem heutigen Wissensstand kann man diese Wiederinbetriebnahme nicht in FinanzOnline melden. Eine Wiederinbetriebnahme der RegK geht nur nach einem Ausfall und nicht nach einer Außerbetriebnahme. 
Daher ist es immer eine "neue" Registrierkasse und diese ist neu über FinanzOnline zu registrieren.
Das hat natürlich nichts damit zu tun, dass man die gleiche Hardware verwenden kann.

**Comment by ErichFreitag** [comment]
Danke Axel, da gebe ich dir recht. Betrieblich halte ich das für problematisch. Lass uns das privat diskutieren und das Ergebnis dann hier posten.

**Comment by eczach** [comment]
ok - wenn es IMMER eine neue registrierkasse darstellt, wenn eine inbetriebnahme vorgenommen wird, so würde es dafür sprechen, dass es besser wäre mit summenzähler 0 und verkettungswert kassen-id zu beginnen. gleichzeitig natürlich auch mit einem neuen aes schlüssel, kassen-id kann gleich bleiben - das wäre also das szenario 1.
szenario 2 (wiederinbetriebnahmeszenario): letzten summenzähler, letzte signatur bei gleicher kassen-id und unverändertem aes-key verwenden.
ich habe nun den eindruck, dass ich - pragmatisch - mit szenario 1 eher auf der sicheren seite bin denn mit szenario 2.

**Comment by ErichFreitag** [comment]
Technisch ja - betrieblich sehe ich mit einer selben Kassen-ID einige Probleme.
Szenario 2 ist offensichtlich technisch in Finanz-Online verhindert.

Die Sache ist für mich noch ein wenig unrund, ich habe die Frage zur Klärung an das BMF gestellt: https://communities.wko.at/Kassensoftware/Lists/oTechnischerechtliche%20Fragestellungen%20zur%20RKSV/Flat.aspx?RootFolder=%2FKassensoftware%2FLists%2FoTechnischerechtliche%20Fragestellungen%20zur%20RKSV%2FAu%C3%9Ferbetriebnahme%20und%20Wiederinbetriebnahme%20einer%20Kasse&FolderCTID=0x01200200907C3B3FD56F92409366C063EF841033

**Comment by eczach** [comment]
wo sehen sie bei verwendung der selben kassen-id betrieblich die probleme?
danke für die anfrage!

**Comment by ErichFreitag** [comment]
Stellen sie sich ein Unternehmen mit ausreichend vielen Kassen vor.

Sie hätten dann mehrere Kassen mit der selben ID.
Die eine ist abgeschlossen und abgemeldet.
Die andere ist aktiv.

Die eine war an jenem Standort.
Die zweite, die gleich heißt, steht jetzt an einem anderen Standort.

Sie müssen das zweite DEP sichern. Parallel zum ersten mit der selben Kassen-ID.
Sie müssen das richtige DEP zum Export finden.
Das eine müssen sie noch 7 Jahre aufbewahren, das andere führen sie weiter.

Sie haben vielleicht eine Portal-Verwaltung, wo dann zwei Kassen mit der selben ID auftauchen.
Sie müssen das einem Prüfer erklären.

Ich finde das alles unnötig verwirrend. Noch dazu wo ja die Kassen-ID nach außen hin Richtung Kunden etc.  praktisch keine Wirkung hat.

Entweder man kann eine Kasse ohne Umstände weiterführen oder man macht eine neue (aber das ist eben meine persönliche Meinung dazu).

**Comment by eczach** [comment]
danke, verstehe nun ihre überlegung: eine gleiche kassen-id für verschiedene kassen zu vergeben wäre tatsächlich problematisch und - sobald kassen mit gleicher id in betrieb genommen werden nicht rechtskonform.
ich gehe von folgender vorstellung aus: ein betrieb hat mehrere kassen, jede selbstverständlich mit unterschiedlicher kassen-id. eine der kassen wir außer betrieb genommen oder geht verloren/kaputt. einer inbetriebnahme einer solchen kasse mit einer zuvor verwendeten, jedoch mittlerweile abgemeldeten kassen-id sehe ich als wenig problematisch.
mein hintergrund dazu: in unserer lösung vergeben wir im rahmen der lizensierung ein-eindeutige mit der lizenz verbundene kassen-id's. jemand, der versuchen würde eine kassen-id mehrfach in betrieb zu nehmen würde einerseits eine lizenzverletzung begehen und andererseits - so nehme ich an - bereits bei der anmeldung bei finanzonline scheitern.

**Comment by ErichFreitag** [comment]
Darum wäre ich ja für eine nahtlose Weiterführ-Möglichkeit, auch wenn ich eine Kasse mal ordnungsgemäß abgemeldet habe und wieder anmelde. Es spricht ja denke ich außer der derzeitigen FON-Sichtweise nichts dagegen.

Ich möchte es auch nicht jenen Kunden erklären müssen, was sie dann genau zu tun haben, die sich ohnedies mit technischen IT-Dingen schwer tun.

Wenn eine Kasse wegen Defekt u.ä. getauscht werden muss, dann kann ich zu 99% die Kasse sowieso nicht mehr weiterführen, weil mir wahrscheinlich das DEP und die letzten Einträge fehlen bzw. eine Rekonstruktion viel zu aufwändig und fehleranfällig wäre - damit ist wohl oder übel eine neue Kasse mit neuer ID fällig.

Ihr Lizenzmodell - OK, verstanden. Ich habe jedoch auch Kunden, die sich die RKSV-Kassen-ID selbst gestalten wollen. Da ist zwecks Verwaltung meist was mit Filialnummer etc. enthalten.

**Comment by eczach** [comment]
eine weiterführmöglichkeit wäre sicher sinnvoll. bei defekt sollte es - so wie ich die texte verstanden habe - eigentlich reichen eine neue kasse mit neuem aes-schlüssel und dep auszustatten. die kassen-id müßte nicht zwingend eine neue sein, da es ja nur darum geht, dass nicht bei einem unternehmer zwei idente kassen-id's gleichzeitig aktiv sind. aber warten wir auf die antworten :-)
danke jedenfalls für die interessanten postings hier!

**Comment by ErichFreitag** [comment]
Hier die Fragen und die Antwort des BMF zu diesem Thema:

Die Außerbetriebnahme einer Kasse scheint klar. Schlussbeleg falls möglich erzeugen und signieren, aufbewahren und die Kasse abmelden, DEP exportieren und ebenso aufbewahren.
Stimmt

Möchte man nun diese Kasse zu einem späteren Zeitpunkt weiterführen so scheint es, dass eine Wiederinbetriebnahme einer abgemeldeten Kasse via FinanzOnline nicht möglich ist (derzeit nur für ausgefallene, aber nicht für abgemeldete Kassen vorgesehen?).
Stimmt, da die Außerbetriebnahme lt. Pkt. 3.5.3.3. und 3.6.2. des Erlass zur Einzelaufzeichnungs-, Registrierkassen- und Belegerteilungspflicht ein endgültiges Ereignis darstellt. Durch den Schlussbeleg wird auch das DEP außer Betrieb genommen.

Die daraus zu schließende Konsequenz: eine Anmeldung als neue Kasse ist erforderlich = die alte Kasse kann nicht weitergeführt werden.
Stimmt; allerdings kann für die „Wiederinbetriebnahme" die alte Kassenidentifikationsnummer verwendet werden.

Dazu die folgenden Fragen:

a) außer dem Formalakt der Abmeldung und der scheinbaren technischen Verhinderung wüsste ich nichts, was dagegen sprechen würde, wenn die Kasse einfach weitergeführt werden könnte? Sprich das DEP weitergeführt wird und die Kasse wieder als "in Betrieb" gemeldet wird. Das wäre ein Vorgang wie bei Saisonkassen, nur dass sie halt der Form halber abgemeldet und wieder angemeldet werden.
Laut  Erlass zur Einzelaufzeichnungs-, Registrierkassen- und Belegerteilungspflicht ist bei saisonbedingten Betriebssperren etc. keine Außerbetriebnahme erforderlich (vgl. Pkt. 3.6. vorletzter Absatz des Erlasses), sehr wohl aber in Fällen, in denen die RK auf Dauer still gelegt wird bzw. nicht mehr benutzbar ist (Pkt. 3.5.3.3. und 3.6. des Erlasses).

b) kann eine solche wieder in Betrieb genommene Kasse mit der selben Kassen-ID angemeldet werden? Lediglich im Erlass findet sich ein Hinweis, dass eine außer Betrieb genommene Kasse wieder in Betrieb genommen werden kann (was damit und wie dies auch genau gemeint ist?)
ja

c) wenn ja verträgt sich das mit einer identen Kassen-ID nicht, da ansonsten zwei Kassen mit der selben ID vorhanden wären?
verträgt sich schon, da bei der Prüfung auf idente Kassen-ID nur aufrechte (nicht außer Betrieb genommene) RK herangezogen werden

d) eine solcherart wieder in Betrieb genommene Kasse "unterliegt den allgemeinen Verpflichtungen bezüglich der Inbetriebnahme" - sprich zumindest einer Überprüfung des ersten Belegs - OK. Ist damit auch ein Startbeleg plus insbesondere das Setzen des Umsatzzählers auf 0 verbunden? Wenn ja müsste auch ein neues DEP erstellt werden (siehe e)).
Stimmt, es sind eine neue Initialisierung, Startbelegerstellung und –prüfung erforderlich (Pkt. 3.5.3.3. und 3.6.2. des o.a. Erlasses).

e) würde eine außer und wieder in Betrieb genommene Kasse tatsächlich der kompletten Prozedur - im besonderen Umsatzzähler auf 0 setzen - unterzogen werden müssen, hätte das erhebliche Konsequenzen für einen Betreiber (initialisieren von Journal, Logs, Zählern, neues DEP, ...) ohne dass damit ein Nutzen verbunden ist?
Die Konsequenzen sind aus sicherheitstechnischen und prüfungstaktischen Überlegungen geboten. Siehe dazu auch a)

**Comment by eczach** [comment]
ok - damit aus meiner sicht also alles klar. 
- ein startbeleg beginnt immer mit der kassen-id als verkettungswert und dem umsatzzähler  0
- startbeleg und schlussbeleg können somit in einem DEP nur einmal vorkommen
- die kassen-id darf aber in zusammenhang mit einem neuen DEP weiterverwendet werden
passt meine zusmmenfassung?

**Comment by ErichFreitag** [comment]
Ja, so sehe ich das.

Ich habe das "Glück", dass wir in meinen unterstützten Projekten in praktisch allen solchen Fällen eine neue Kassen-ID verwenden können und wollen, das erspart eine Menge Ärger und folgt immer dem selben Prozess.
