### ISSUE TITLE
BMF-App - Allgemeiner Fehler

### ISSUE THREAD

**Issue by senton82** [a-sit-plus/at-registrierkassen-mustercode#174]
Hallo zusammen,

es ist mir bewusst, dass diese Frage off-topic zu diesem Projekt ist, aber ich komme irgendwie nicht weiter und hoffe, dass eventuell jemand ähnliche Erfahrungen gemacht hat.

In unserem Kassensystem haben wir schon seit längerem die Signierung eingebaut. Nun wollte ich erstmals einen Startbeleg mit der BMF-App testen. Sowohl die Kasse als auch die Signiereinheit (Smartcard von A-Trust) wurden erfolgreich im FON eingetragen.

Nach dem Scan des QR-Codes erhalte ich lediglich die folgende Fehlermeldung in der App:
"Allgemeiner Fehler, Belegprüfung fehlgeschlagen. Bitte überprüfen Sie den Beleg".

Allerdings unterscheidet sich diese Meldung von jener, die im Handbuch suggeriert wird, auch wird der Beleg zur weiteren Fehleranalyse nicht an FON übertragen.

Die Verifikation des Startbelegs inkl. Verkettung mit etwaigen anderen Belegen mit dem hier zur Verfügung gestellten Prüftool liefert immer ein korrektes Ergebnis.

Hat irgendjemand von euch eine Idee, was hier schief geht?

LG,
Stefan

**Comment by ErichFreitag** [comment]
Dazu kann ich konkret nichts sagen, aber sie könnten den QR-Code posten, vielleicht ist etwas zu erkennen.

**Comment by senton82** [comment]
Hallo,

danke für die Rückmeldung. 

Anbei der QR-Code.
![startbeleg_qr](https://cloud.githubusercontent.com/assets/5689354/20556971/c36c4cee-b169-11e6-9690-0a316409cbcb.png)

**Comment by asitplus-pteufl** [comment]
SIe haben da am Anfang/Ende Klammern {}.. Damit ist die Basisstruktur des Belegs falsch und das Prüfservice nimmt den nicht entgegen da schon die Basisanforderungen nicht erfüllt sind.

**Comment by senton82** [comment]
@asitplus-pteufl : Es ist mir ehrlicherweise etwas peinlich, aber genau das wars. Ein simpler Fehler im Ausgabe-Template.

Danke für die Hilfe, Überprüfung ist nun erfoglreich :-)

**Comment by SLMaWi** [comment]
Sehr geehrter Damen und Herren!

Wir haben bei der Prüfung unseres Startbelegs leider das selbe Problem.
Die Belegcheck-App meldet beim Scannen des Startbelegs "Belegprüfung fehlgeschlagen. Bitte überprüfen Sie den Beleg." In FinanzOnline wird der Beleg leider nicht übertragen.
Bitte um Hinweis, wo hier der Fehler liegt.

Der dazugehörige QR-Code sieht folgendermaßen aus:
![startbeleg fehler](https://cloud.githubusercontent.com/assets/19283174/21604587/450c0a3c-d1a4-11e6-9bc2-c50b16f594fa.JPG)

**Comment by asitplus-pteufl** [comment]
Bitte unbedingt das Prüftool verwenden!
Der Beleg entspricht nicht den Anforderungen da keine Seriennummer für das Zert vorhanden ist (zwei __ nach QCUwLnwVHqdZM7IehulinA==).
_R1-AT1_T1_BL-07000106_2017-01-03T10:06:29_0,00_0,00_0,00_0,00_0,00_QCUwLnwVHqdZM7IehulinA==__H5NgPbU7+tU=_m1ZFrtW5Kwbk1W8ITDf80OKpynWNv/cWQQ5e4XVVWgHc1Vf7S/CkDdyp3/pURkTfFNYQ0R8iJkkZcJpQgoTNtQ==

**Comment by asitplus-pteufl** [comment]
Bitte nicht ein bestehendes Issue hijacken, sondern bei neuen Themen bitte auch neue Issues anlegen.

**Comment by ckvsoft** [comment]
Schaut aus als fehlt hier die Seriennummer.

**Comment by SLMaWi** [comment]
Danke für die Hinweise!
In Zukunft werde ich neue Issues anlegen.
