### ISSUE TITLE
Schlussbeleg auch als Monatsbeleg möglich?

### ISSUE THREAD

**Issue by giemes** [a-sit-plus/at-registrierkassen-mustercode#176]
Kurze Frage: Ist der Monatsabschlussbeleg auch als Schlussbeleg beim Schließen der Kassa gültig oder muss der Schlussbeleg zB: den Text "Schlussbeleg" beinhalten?

**Comment by ErichFreitag** [comment]
a) für Start-, Jahres- und Schlussbelege besteht laut Erlass eine verpflichtende Ausdruck- und Aufbewahrungspflicht (für Monatsbelege nicht)

b) Start-, Monats-, Jahres- und Schlussbelege sollten als solche bzw. als Nullbelege im Feld der
handelsüblichen Bezeichnung gekennzeichnet werden (Monatsbelege nicht)

c) mit dem Schlussbeleg ist auch die Abmeldung der Kasse verbunden (mit dem Monatsbeleg nicht)

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
