### ISSUE TITLE
Prüftool 1.0, Ergebniss der DEP-Export Prüfung...

### ISSUE THREAD

**Issue by riko2016** [a-sit-plus/at-registrierkassen-mustercode#177]
Ist es Korrekt dass im Ergebnis-File n_cashbox_full.json nach einer DEP Prüfung ein paar mal FAIL vorkommt obwohl im File n_cashbox.json alles als korrekt angegeben wird ("PASS")?
Auch scheint es dass die Einträge doppelt enthalten sind...
Beispiel Startbeleg:
"verificationId" : "RECEIPT_FULL", "verificationState" : "FAIL"
"verificationId" : "STATE_CONSOLIDATED", "verificationState" : "FAIL"

Beim 2. mal hat 
"verificationId" : "RECEIPT_FULL", "verificationState" : "PASS"
"verificationId" : "STATE_CONSOLIDATED" , "verificationState" : "PASS"

**Comment by ErichFreitag** [comment]
Schauen sie mal bitte ob https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/134 das beantwortet.

**Comment by riko2016** [comment]
Ok, da in der Datei ganz oben "PASS" steht... ist das somit für mich erledigt...
Startbeleg wurde ja auch vom BMF akzeptiert.
DANKE.
