### ISSUE TITLE
Prüfttool "FAIL" bei Start_Beleg

### ISSUE THREAD

**Issue by Georg632** [a-sit-plus/at-registrierkassen-mustercode#178]
Hallo,

ich habe mit dem regkassen-demo-1.0.0.jar Belege erstellt.
cryptographicMaterialContainer.json 
und
dep-export.json
mit dem 
regkassen-verification-depformat-1.0.0.jar
geprüft.
(java -jar regkassen-verification-depformat-1.0.0.jar -v -f -i dep-export.json -c cryptographicMaterialContainer.json -o output55)

Beim Startbeleg kommen trotzdem Fails raus. Ist das normal oder mache ich irgendwas falsch?

`verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",
    "verificationTimestamp" : "2016-11-23T18:00:18.311+01:00",
    "verificationResultList" : 

{
      "verificationId" : "STATE_CONSOLIDATED",
      "version" : 1,
      "verificationName" : "Statusprüfung der Kasse und Signatur-/Siegelerstellungseinheit",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die Zustände der Kasse und der verwendeten Signatur-/Siegelerstellungseinheit und die Ergebnisse der zuvor durchgeführten Prüfungen (vor allem der Belegtyp) ausgewertet. Handelt es sich um einen Startbeleg, wird überprüft ob eine Inbetriebnahme der Kasse möglich ist.",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2016-11-23T18:00:18.687+01:00",
      "verificationResultList" : [ {
        "verificationId" : "STATE_CASHBOX",
        "version" : 1,
        "verificationName" : "Statusprüfung der Kasse",
        "verificationTextualDescription" : "Es wird der Status der Kasse zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.",
        "verificationState" : "FAIL",
        "verificationTimestamp" : "2016-11-23T18:00:18.688+01:00"
      }
`

**Comment by asitplus-pteufl** [comment]
können sie den startbeleg posten? zu welchem Zeitpunkt wurde dieser erstellt (zukunft?)

**Comment by Georg632** [comment]
Nein war nicht in der Zukunft. (2016-03-11T03:57:08)

Startbeleg vom dep export:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMTAwX0NBU0hCT1gtREVNTy0xX0NBU0hCT1gtREVNTy0xLVJlY2VpcHQtSUQtNTcwXzIwMTYtMDMtMTFUMDM6NTc6MDhfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX1NhdFRGakZyaG5rPV8zYzE0MGJmNzliMmQyMmNiX2NnOGhOVTVpaHRvPQ.UUjkNy8jtnS_75oUjlERK2jmzrI-hXEnwwyKc1xwCphSn1WQ6FH6US1q74guXyzJeD2H25-jDp7p804yM_ohfQ

Startbeleg OCR:
_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-
Receipt-ID-570_2016-03-11T03:57:08_0,00_
0,00_0,00_0,00_0,00_JGVVGFRRNODHS===_3c1
40bf79b2d22cb_OIHSCNKOMKDNU===_KFEOINZPE
O3HJP7PTIKI4UIRFNUONTVSH2CXCJ6DBSFHGXDQB
KMFFH2VSDUFD6SRFVVO7CBOL4WMS6B5Q7NZ7IYOT
3U7GTRSGP5CC7I=

**Comment by asitplus-pteufl** [comment]
Der Beleg erfüllt nicht die Basisanforderungen, da fehlt am Anfang das beginnende "_" Zeichen. Allerdings passt die Fehlermeldung nicht dazu, dass werden wir uns anschauen.
Bitte für den CMC-Container noch beachten, dass da in der aktuellen Version Grop/Kleinschreibung noch relevant ist (also bitte die gleiche Schreibweise für die Seriennummer verwenden wie sie im Beleg steht).

**Comment by Georg632** [comment]
Das beginnende Zeichen ist vorhanden - sorry ging beim kopieren verloren.

CMC sieht so aus:
"3c140bf79b2d22cb" : {
      "id" : "3c140bf79b2d22cb",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" "MIIBSDCB8KADAgECAgg8FAv3my0iyzAKBggqhkjOPQQDAjAWMRQwEgYDVQQDDAtSZWdLYXNzYSBDQTAeFw0xNjExMjMwOTM4MDNaFw0xNjExMjQwOTM4MTNaMB4xHDAaBgNVBAMME1NpZ25pbmcgY2VydGlmaWNhdGUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAThpNlHPQ2B88iQAXymudioQUxQ+acb4Uep/h8HmPsj6xUXt8y78aeYSMM4eCXDzeKQJ1dr2CdtvfkadbF3K67YoyAwHjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAKBggqhkjOPQQDAgNHADBEAiALC1CLxJvuR452TWQfnRQds1Wsi8QLNEUkCmLnSMGLpwIgBaCWI2KGTcVWXsoG36g/RISeCqokbVBNQTNviPPb6Lw="

Ist alles original von der Java Test-Application.

**Comment by asitplus-pteufl** [comment]
zur sicherheit: das sind also alles daten die über den muster-code erstellt worden sind?

**Comment by asitplus-pteufl** [comment]
können sie einfach das DEP und den CMC als Dateien posten?

**Comment by Georg632** [comment]
Ja genau. Doppelklick auf regkassen-demo-1.0.0.jar - dann wird das alles erstellt.


[dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/610620/dep-export.txt)
[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/610621/cryptographicMaterialContainer.txt)

**Comment by asitplus-pteufl** [comment]
kann ich nicht nachvollziehen, alle prüfungen sind auf PASS

**Comment by Georg632** [comment]
Hm sehr seltsam. Habe es nochmals auf meinen Privaten Notebook nachgestellt mit den selben files und ich bekomme die gleichen fails beim 0000_cashbox_full.json

**Comment by ErichFreitag** [comment]
Wenn ich die Testfiles generiere und den Beleg 570 anschaue, dann kommt bei mir ein QR-Code (BASE64, nicht direkt mit obigem OCR vergleichbar) mit 
_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-570_2016-03-11T03:57:08_0,00_0,00_0,00_0,00_0,00_SatTFjFrhnk=_9a73f4e7917df9d2_cg8hNU5ihto=_rQ5SjyvaOamkYiLIDRkQWsZyqzzK5bZ7pEjgUsPVIPjOorKiK90RC55lvVPT7+9n/HBXo6e1Bmd1CC2sJ0uQoA==

Das ist eine andere Zertifikatsseriennummer als im CMC enthalten ist. Vielleicht hilft das weiter.

**Comment by Georg632** [comment]
Es geht ja eigentlich nur um das:

        "verificationId" : "STATE_CASHBOX",
        "version" : 1,
        "verificationName" : "Statusprüfung der Kasse",
        "verificationTextualDescription" : "Es wird der Status der Kasse zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.",
        "verificationState" : "FAIL",
        "verificationTimestamp" : "2016-11-24T09:35:35.919+01:00"
      },

was für ein Cashbox Status wird hier geprüft?

**Comment by Georg632** [comment]
Wie ich gerade lese ist das File: "cashbox_FULL.json" nur für die Entwickler.
Cashbox-/app-/dep.json weisen keine Fehler auf. Kann ich das dann ignorieren?

**Comment by asitplus-pteufl** [comment]
Ich hab hier auch eine weitere Meldung bekommen, dass es da einen doppelten Eintrag gibt von dem einer Fail ist, wir werden das überprüfen. Aber Sie haben Recht, es spielt keine Rolle, wenn oben PASS herauskommt oder eben die anderen Ergebnisse auf PASS sind.
