### ISSUE TITLE
Prüftool - Fallweise Probleme bei Ausführung

### ISSUE THREAD

**Issue by Flanelli** [a-sit-plus/at-registrierkassen-mustercode#179]
Man möge mir verzeihen wenn mein Anliegen hier nicht richtig platziert ist
aber ich wäre sehr dankbar wenn jemand unabhängiger meine Daten prüfen könnte.
Ich habe fallweise Probleme bei der Ausführung des Prüftools ( java mag mich nicht )
Anbei einige Daten ( 1 Startbeleg, 2 Belege signiert, ok,, 2 Belege signiert ausgefallen,,
1 Sammelbeleg, 1 Beleg signiert, ok,, 1 Monatsbeleg.
Alle Daten wurden am gleichen Tag hintereinander erfasst.
Vielen Dank im Voraus
[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611625/cryptographicMaterialContainer.txt)
[dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611628/dep-export.txt)
[qr-code-rep.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611629/qr-code-rep.txt)

**Comment by asitplus-pteufl** [comment]
Falsche Seriennummer im CMC-Container
Keine Signatur im Beleg (hat nur 12 Elemente).
weiter hab ich nicht geprüft.

**Comment by ErichFreitag** [comment]
Ein paar weitere Details dazu:

Falsche Seriennummer im CMC: "0187D8D4F9F0539FEBECC70458W" - das "W" kann nicht sein (kommt auch in den Belegen nicht vor).

Signatur von einigen Belegen im DEP fehlerhaft.
(wenn ich richtig gezählt habe der erste und der sechste).

Barumsatz 2. Beleg 200 EUR 20%, Umsatzzähler steht auf 20.000,00 EUR
Barumsatz 3. Beleg 100 EUR 0%, Umsatzzähler steht auf 30.000,00 EUR (u.s.w.)

**Comment by Flanelli** [comment]
Sehr geehrter Hr. Dr,. Teufl,
danke für die Reaktion - vor allen die so rasche.

Leider hat sich bei der Seriennummer ein Tipfehler eingeschlichen, das letzte Zeiche W gehört weg.
Im Anhang nochmals die Datei mit der nun korrekten Seriennummer.

Bzgl. der nur 12 Elemente in den Daten der "qr-code-rep.txt" kann ich diese aber NICHT erkennen
Es sind defintiv alle Belege mit 13 Elementen in dieser Datei vorhanden.
Im Anhang die zur einfacheren Zählung manuell durch Leerzeichen samt Zählüberschrift
getrennten Elemente - es SIND 13

Nochmals herzlichen Dank

[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611782/cryptographicMaterialContainer.txt)
[qr-code-rep_mitZaehlheader.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611783/qr-code-rep_mitZaehlheader.txt)

**Comment by Flanelli** [comment]
Sehr Geehrter Herr Ing. Freitag,

das mit dem "W" hatte ich soeben auch entdeckt
Bzgl. der Barumsätze muss ich das prüfen.

Vielen Dank

**Comment by Flanelli** [comment]
Ich erlaube mir nun die, meines Erachtens nun korrigierten Daten zu senden
und ersuche nochmals um eine Überprüfung.
Seriennummer = nun richtig gestellt.
Umsatzzähler = nun richtiges Format
Die, von Herrn Ing. Freitag angeführten Belege mit falschen Signaturen waren und sind
1 = Startbeleg
6 = Sammelbelg

Herzlichen Dank, ohne die Unterstützung hier wäre man wohl "verloren"

[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611923/cryptographicMaterialContainer.txt)
[dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611925/dep-export.txt)
[qr-code-rep.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/611926/qr-code-rep.txt)

**Comment by ErichFreitag** [comment]
Meinerseits bitte gerne.

Im CMC gibt es noch ein "W" zu viel:
"certificateOrPublicKeyMap" : {
    "0187D8D4F9F0539FEBECC70458W" : {
      "id" : "0187D8D4F9F0539FEBECC70458",

Die Umsatzzähler dürften jetzt passen.

Was gibt denn jetzt das Prüftool aus?

**Comment by Flanelli** [comment]
Sehr geehrter Herr Ing. Fretiag.

Axh herjeh, ich habe das erste "w" vergessen zu eliminjieren  - danke.
Tja, das Prüftool ...
Genau damit habe ich derzeit ein Riesenproblem - ich krieg das Teil auf dem
derzeit zur Verfugung stehenden System einfach nicht richtig zum Laufen
muss aber betonen dass ich mit Java seit eh und jeh auf Kriegsfuss bin und
daher auch dahingehend Tips zum Handling nicht wirklich fruchten würden.

Somit bin ich mehr oder weniger auf die Hilfe angewiesen dass mir jemand
aus der Community natürlich ohne jeglichen Ansprich auf Verbindlchkeit
solche Fehler aufzeigen wie dies hier geschieht.

Haben Sie eventuell eine Erkenntnis über die, von Ihnen zuvor angesprochenen
fehlerhaften Signaturen der Belege 1 und 6? Lag dies möglicherweise am
falschen Umsatzzähler?

Der Startbeleg sollte doch jedenfalls korekt sein, hier wird ja der Umsatz mit 0
und der vorherige Signaturwert durch den Dummy KASSAID irrtumsfrei
zum Signieren übergeben. 

Mit einem weiteren Dankeschön ....

**Comment by asitplus-pteufl** [comment]
Sie werden eine Plattform verwenden müssen auf der das Prüftool läuft. Die Hilfestellung hier kann ja nur punktuell erfolgen und Ihnen bei dem einen oder anderen Beleg helfen, aber um eine korrekte Implementierung zu haben wird es wohl auf Ihre Seite notwendig sein klare Testszenarien zu entwickeln (aufbauend auf denen die wir beigelegt haben) und diese bei Änderungen durchlaufen zu lassen. Ohne diesen detaillierten Tests (für die Sie das Prüftool verwenden können) ist es unwahrscheinlich dass Sie eine korrekte Implementierung haben werden.

**Comment by Flanelli** [comment]
Sehr geehrter Hr. Dr. Teufl,
natürlich haben Sie damit völlig recht und es wird auch daran gearbeitet alsbald wieder eine
entsprechende Umgebung zu installieren. 
Allerdings schreitet die Zeit unerbittlich voran und somit ist jeder noch so kleine Schritt sehr
wertvoll - wie man ja auch an der klaren Problemaufzeigung von Hr. Ing. Freitag sieht dessen
Kommentar z.b. bzgl. Umsatzdarstellung sogleich einer positiven Erledigung zugeführt werden konnte.
Damit konnte zumindest das Kapitel technisch abgehakt werden.

Was mich nach wie vor jedoch in höchstem Maße verunsichert ist Ihre Fehleranalyse bzgl. 
**"Keine Signatur im Beleg (hat nur 12 Elemente)."**
Wenn mir das Prüftool entgegen der definitiv coehandenen 13 Elemente nun so einen Fehler auswerfen würde hilft mir die beste Plattform nichts. Ich denke das können Sie sicher auch naczhvollzoehen.

Dennoch herzlichen Dank dafür dass Sie auf meine wohl eher etwas unbedarften Anmerkungen nach wie vor mit Aufmerksamkeit reagieren - ich hoffe auf weitere Unterstützung.

**Comment by ErichFreitag** [comment]
Die sieben Belege laufen jetzt ohne Fehler durch das Prüftool.

Was noch fehlt ist, dass sie die Einträge im qr-code-rep pro Zeile unter Anführungszeichen setzen und mit Komma abschließen müssen.

**Comment by Flanelli** [comment]
Sehr geehrter Herr Ing. Freitag,
großen, großen Dank für Ihre Bemühungen, dies hat mir außerordentlich weitergeholfen

Ich hoffe,, dass ich Ihre Geduld und Entgegenkommen nicht mehr strapazieren muß aber falls
doch bin ich guten Mutes :-)

**Comment by ErichFreitag** [comment]
Bitte gerne.

Schauen sie halt, dass sie das Prüftool zum Laufen bekommen. Soooo schwer ist das nicht.

Viel Erfolg noch!
