### ISSUE TITLE
RK Suite AT0 ist für geschlossenes System vorgesehen 

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#18]
In Anlage Seite 1, unter Punkt 2. Registrierkassenalgorithmuskennzeichen ist folgender Text:
Die folgenden Kennzeichen sind definiert:
R1-CM:
ZDA: CM wird als Platzhalter für die zur Verfügung stehenden ZDAs gesehen. Wenn ein
**geschlossenes System** laut § 20 zum Einsatz kommt, muss **AT0** als ZDA angebenden werden.

Daraus folgt, das AT0 nur für geschlossene Systeme zu verwenden ist.

In RKSuite.java ist AT0 für die zda-ID gesetzt
public enum RKSuite {
    //RK Suite defined in Detailspezifikation/ABS 2
    R1_AT0("1", "AT0", "ES256", "SHA-256", 8);

Ich nehme an, es sollte daher lauten:
R1_AT1("1","AT1","ES256","SHA-256",8);

**Comment by pteufl** [comment]
Die Wahl von AT0 hat mehrere Gründe:
-Es werden im Demo-Code nur dynamisch generierte Software-Zertifikate verwendet, die natürlich nicht von einem ZDA ausgestellt wurden. Eine ID für einen ZDA würde hier also nicht passen.
-Die IDs für die ZDAs wurden noch nicht festgelegt.
-Es sollte im Muster-Code auch kein ZDA bevorzugt werden, daher die Wahl des neutralen "AT0"

Natürlich muss im realen Code dann so wie Sie es schreiben, die ZDA-ID angepasst werden.

**Comment by anzun** [comment]
Vielen Dank für die rasche Antwort

**Comment by DrBGM** [comment]
Gibt es schon ein Update ? 

Registrierkassenalgorithmuskennzeichen?
Festlegung:  IDs für die ZDAs ?

**Aufbereitung der zu signierenden Daten – Hinzufügen des Registrierkassenalgorithmuskennzeichen als Präfix:**
Zu der im vorigen Schritt erstellten Zeichenkette wird das jeweilige Registrierkassenalgorithmuskennzeichen hinzugefügt. In diesem Beispiel wird R1-AT75 verwendet. R1 entspricht dem zum Zeitpunkt der Erstellung dieses Dokuments einzig verfügbaren Kennzeichen. AT75 steht für einen fiktiven österreichischen ZDA. Daraus ergibt sich (für die bessere Lesbarkeit wurden Zeilenumbrüche eingefügt):

Welche Kennzeichen gibt es schon außer R1? 
Was bedeutet R1 ?
Bitte die Liste aller ZDA und deren IDs?

MfG 
DrBGM

**Comment by asitplus-pteufl** [comment]
welches update sollte es da geben?

Welche Kennzeichen gibt es schon außer R1? 
Aktuell ist nur R1 definiert. Da nicht davon auszugehen ist, dass die verwendeten Algorithmen in den nächsten Jahren als kryptographisch unsicher gelten werden, ist nicht davon auszugehen dass hier in der absehbaren Zukunft weitere dazukommen werden.

Was bedeutet R1 ?
R1 ist die Algorithmensuite, die ist der Verordnung zur RKSV definiert. Die technische Umsetzung ist in dem Dokument "Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV)" näher erklärt. Beispiele sind im Mustercode enthalten.

Bitte die Liste aller ZDA und deren IDs?
Die Liste der ZDAs ist nicht fix, sondern hängt von den am Markt agierenden Firmen ab. Die aktuellen Anbieter finden Sie auf der Infoseite des BMFs: https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Sicherheitseinrichtung_in_Registrierkassen.html

**Comment by smtm** [comment]
Fesch wäre schon eine Liste der ZDA IDs in diesem Thread. 

Ich habe diese Seite gefunden als ich mir den Kopf kratzte und googelte "AT75 steht für einen fiktiven österreichischen ZDA"...

**Comment by ErichFreitag** [comment]
Für A-Trust _R1-AT1.
Für Global Trust _R1-AT2.
Für Prime Sign _R1-AT3.

VDAs statt ZDAs seit August 2016.

**Comment by DrBGM** [comment]
eine Liste der ZDA IDs habe ich schon mit meinem Post am 14. Oktober 2016 versucht zu bekommen. Die Antwort von Herr Dr. Teufel hat mich auch nicht weitergebracht!

Wir verwenden für A-Trust _R1-AT1.

Ah ... ich sehe gerade Herr Freitag hat schon geantwortet - Danke !

**Comment by asitplus-pteufl** [comment]
@DrBGM @smtm Fesch wäre die Liste hier vielleicht - zumindest von einer oberflächlichen Betrachtung her - aber sicher nicht seriös (seitens A-SIT Plus), da dieser Thread nicht gewartet wird. Daher wurde am 14.10.2016 ein Link zur entsprechenden BMF-Seite veröffentlicht, die aktuelle und gewartete Informationen bieten kann. Ich vermute auch, dass sich der Aufwand auf diesen Link zu klicken und danach die Fragen durchzugehen in Grenzen halten wird.
