### ISSUE TITLE
Gibt es eine Javadoc vom API?

### ISSUE THREAD

**Issue by steph-k** [a-sit-plus/at-registrierkassen-mustercode#180]
Hi,

gibt es eine Javadoc vom API? Wir wollen eine Schnittstelle von unserem Java Kassensystem erstellen und sehen den Wald vor lauter Bäumen nicht.

Beste Grüße

**Comment by asitplus-pteufl** [comment]
Bitte lesen Sie das Detailfragen Dokument (siehe https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/tag/1.2-DOK), dort finden Sie alle relevanten technischen Prozesse und Spezifikationen.
Zum Mustercode: Es gibt kein API, es wird ein Muster-Code zur Verfügung gestellt, der alle relevanten Elemente der RKSV demonstriert.

**Comment by ErichFreitag** [comment]
@steph-k - das klingt nach "wir fangen gerade erst an" (?) - dann sollten sie nicht zuletzt aus Zeitgründen eine Zusammenarbeit mit einem Integrationspartner in Erwägung ziehen, z.B. www.fiskaltrust.at oder www.efsta.org und andere. Da bekommen sie geschätzte 80% der RKSV-Aufgaben mit einer Middleware abgedeckt.
