### ISSUE TITLE
Prüftool 1.0.0; Startbeleg PASS mit einigen FAILS

### ISSUE THREAD

**Issue by rksvlobster** [a-sit-plus/at-registrierkassen-mustercode#181]
Hi,
wir haben einen einzigen Beleg im DEP.
Den Startbeleg.
Wir haben ihn exportiert und das Prüftool über den Export laufen lassen.

0000_app.json - Überall "PASS"
0000_cashbox.json - Überall "PASS"
0000_dep.json - Überall "PASS"
DEP.json - Überall "PASS"

[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/619265/0000_cashbox_full.txt)

0000_cashbox_full.json - einige "FAIL"
Der root node "VERIFICATION_FROM_CASHBOX" -> "PASS"
"TYPE_OF_RECEIPT" - "TYPE_OF_RECEIPT_START" -> "PASS" (Die anderen types of receipt "FAIL", was aber ok ist)
Aber "RECEIPT_FULL" -> "FAIL"
Weil darunter "STATE_CONSOLIDATED" -> "FAIL"
Weil darunter "STATE_CASHBOX" -> "FAIL"
Der Rest der Prüfungen steht auf "PASS"

Ist das relevant? Wo oder was ist der Fehler (die Fehlermeldung)?
Wenn wir weitere Belege erzeugen und exportieren, haben diese keine Fehler. Auch nicht in der xxxx_cashbox_full.json. Überall nur "PASS". Der Startbreleg hat aber unabhängig davon, ob es weitere Belege im Export gibt oder nicht, immer die gleichen "FAIL"s.

Was macht diese "Statusprüfung der Kasse" mit der Beschreibung "Es wird der Status der Kasse zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet."?

PS: Abgesehen davon scheinen die Prüfungen
"CONSTRAINTS_PRE_DB"
"RKSUITE"
"RECEIPT_FULL"
und die dazugehörigen Unterprüfungen mehrfach vorzukommen.

Vielen Dank im Voraus

**Comment by Georg632** [comment]
Schau mal hier: https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/178#issuecomment-262577275

**Comment by asitplus-pteufl** [comment]
@Georg632 danke! 
@rksvlobster Bitte meinen letzten Eintrag im Issue das von @Georg632 verlinkt wurde, beachten.

Short Story: Known Issue, wird in der nächsten Version behoben, wenn oben PASS rauskommt, bitte ignorieren.

**Comment by rksvlobster** [comment]
Danke schön, Georg. Ich hatte deinen issue schon gelesen, aber mir war nicht so hundertprozentig klar, dass das als 'bug' aufgenommen wurde.

Danke an das a-sit Team für die Klarstellung und ein schönes Wochenende euch allen!

**Comment by asitplus-pteufl** [comment]
danke, ebenso
