### ISSUE TITLE
Restriktiver Umgang mit NULL-Belegen

### ISSUE THREAD

**Issue by senton82** [a-sit-plus/at-registrierkassen-mustercode#183]
Laut @asitplus-pteufl wird das Prüftool nur dahingehend angepasst, dass auf die Kategorisierung der NULL-Belege, wie hier im readme aufgelistet, verwiesen wird, das Prüftool aber dennoch einen Fehler liefert, sobald ein NULL-Beleg mit ausgefallener Signatureinheit erstellt wird.

Dies beeinflusst aktuell die Art und Weise wie Unit-Tests bei uns implementiert sind, da diese zum Schluss immer gegen das Prüftool validiert werden - bei Umsetzung der lockeren Restriktion bzgl. ausgefallener Signatureinheit bei manuellen NULL-Belege, Monatsbelege usw. lässt dies unsere Tests brechen.

Meine grundsätzlich Überlegung wäre also, hier genauso restriktiv wie das Prüftool zu bleiben und jeden zu erstellenden NULL-Beleg nur mit einer funktionierenden Signatureinheit vornehmen zu lassen.

Wäre es somit korrekt, im Zuge eines Aufalles der Signatureinheit einen Monatsbeleg erst dann zu erstellen, sobald die Signatureinheit wieder verfügbar ist, benötigte Belge dazwischen aber weiterhin mit ausgefallener Signatureinheit verarbeitet werden können? Gleiches gilt natürlich auch für die Erstellung des Jahresbeleges.

Danke für eure Gedanken dazu.

LG,
Stefan

**Comment by hardmuf** [comment]
Hallo, 
Gibt es eigentlich einen Unterschied zwischen den NULL-Belegen (Monat, Jahres usw.) und einem Tatsächlichem Null-Beleg? Ware wird hergeschenkt oder die Ware wird nur ausgetauscht... Das wäre ja auch ein Null-Beleg... und der muss auch mit ausgefallener Sicherheitseinrichtung möglich sein... Oder sehe ich da gerade etwas ganz falsch?

LG

Michael

**Comment by argetherapie** [comment]
Aus "Gesammelte FAQ Arbeitskreis Kassensoftware_20161201.pdf", (Letzte Aktualisierung: 01.12.2016)
>73) Die RKSV sieht in § 7 die Sicherung des DEP vor und dazu wird in den erläuternden 
Bestimmungen folgendes festgehalten: In der Sicherung hat der Monatsbeleg des 
letzten Monats des Quartals, der die Unveränderbarkeit des gesamten 
Datenerfassungsprotokolls im Wege der Signatur sichert, als letzter Beleg 
enthalten zu sein. 
Dies ist grundsätzlich vernünftig, nur was ist zu tun, wenn die Signatureinheit 
ausgefallen ist? Genügt dann auch hier der Hinweis, dass diese ausgefallen ist (wie 
bei einem „normalen“ Kassenbon) oder kann das Monat dann nicht abgeschlossen 
werden? 
Die Antwort des BMF: 
Ja, Hinweis „Sicherheitseinrichtung ausgefallen“ und signierter Sammelbeleg.

Wir haben das ebenfalls so implementiert, dass der erste **gültig** signierte Beleg nach einem Monatswechsel **immer** ein Monats/Jahresbeleg ist. Ist die SE ausgefallen, entstehen dazwischen unsignierte Belege bis die SE wieder online ist, aber keine (unsignierten) Monatsbelege. Zusammen mit einem gültig signierten Monatsbeleg wird auch das DEP-Backup angestoßen, dh die Sicherung enthält als letzten DEP-Eintrag **immer** einen gültig signierten 0-Beleg. Der Jahresbeleg wird zusätzlich ausgedruckt.

LG
Walter

**Comment by asitplus-pteufl** [comment]
@hardmuf Bitte den Hinweis am Anfang des READMEs beachten: https://github.com/a-sit-plus/at-registrierkassen-mustercode

**Comment by ckvsoft** [comment]
a. Ich hätte da auch eine Frage zum Monatsbeleg.
Wir erfassen den Tages bzw. Monatsabschluss in der Kasse. Dieser Abschluss wird daher signiert und ist ein NULL Beleg.
Kann dieser gleichzeitig der "Monats NULL Beleg" sein oder muss dann trotzdem ein Monatsbeleg, der optisch wie ein "Normaler" Beleg aussieht, erstellt werden? Das gleiche natürlich auch beim Jahresabschluss.

b. Ein Sammelbeleg nach einen Ausfall der Sicherheitseinrichtung muss ja Anfang und Ende des Ausfalles beinhalten. Wenn die Signatureinheit aber wärend einer Erstellung wieder funktioniert könnte dieser Beleg wieder gültig signiert sein bevor der Sammelbeleg erstellt werden konnte. Ist dieser danach auch gültig?

lg Chris

**Comment by senton82** [comment]
@argetherapie : Danke für den Input bzgl. gleicher Handhabung. Auch ist der Kommentar des Arbeitskreises interessant. Das der letzte Beleg eines DEP-Backups ein gültiger Monats/Jahresbeleg sein muss, war mir bislang nicht klar. Danke dafür!

@hardmuf : Meiner Aufassung nach ist ein NULL-Beleg ein Beleg, der einen Verkauf mit Umsatz 0 darstellt, allerdings ist es gegebenfalls notwendig mehr Details dazu festzuhalten. Sollten zum Beispiel ein Schlussbeleg als NULL-Beleg erfasst worden sein, sollte es der Kasse nicht mehr möglich sein weitere Belege zu erstellen. Auch muss im Bedarfsfall zwischen manuell erstellten Null-Belegen oder automatisierten, wie zum Beispiel Monats/Jahresbelgen, unterschieden werden könne.

HTH,
Stefan

**Comment by AxelKutschera** [comment]
@ckvsoft :
a. NULL-Beleg ist immer gleich zu erstellen. Nach dem Erlass Punkt "4.5.7. Start-, Monats-, Jahres- und Schlussbelege ab 1. April 2017 (§ 8 RKSV)" gilt auch: 
"Start-, Monats-, Jahres- und Schlussbelege sollten als solche bzw. als Nullbelege im Feld der
handelsüblichen Bezeichnung gekennzeichnet werden."

b. Dies ist entsprechend dem Erlass Punkt "3.6.1. Ausfall der Signatur- bzw. Siegelerstellungseinheit oder der Registrierkasse" möglich.

**Comment by AxelKutschera** [comment]
@senton82 : Ich weise darauf hin, dass hier nur der § Abs 7 Abs. 3 RKSV gilt:
"Die Daten des Datenerfassungsprotokolls sind ZUMINDEST vierteljährlich auf einem elektronischen externen Medium unveränderbar zu sichern."

Da steht "zumindest": Also ist immer eine Sicherung - auch vor dem Monatsende - völlig unabhängig vom Quartal möglich. Der letzter Beleg eines Monats muss demnach nicht diese Sicherung abschließen.

Auch auf den Unterschied zwischen den "Daten des Datenerfassungsprotokolls" und dem "Exportformat Datenerfassungsprotokoll laut Z 3 der Anlage" weise ich hin.

Wir sichern die Belege hierfür immer zeitnah in unserem revisionssicheren Online-Speicher. Dabei ist der Bezug auf das Quartal überhaupt nicht relevant.

**Comment by argetherapie** [comment]
@AxelKutschera : Nicht jeder kann und will auf einen revisionssicheren Onlinespeicher gehen. Muss er auch nicht.
Nach allen bisherigen Aussagen des BMF (auch Hr. Engelbert persönlich) gilt eine Sicherung auch dann als ausreichend manipulationssicher, wenn deren letztes Item ein **signierter** 0-Beleg ist. Es ist naheliegend, dass das zumeist ein Monatsbeleg ist - und das dürfte auch im Sinne des Erfinders sein. Ist akurat zum Zeitwechsel die SE down, ist auch ein späterer signierter Sammelbeleg (welcher nun einen **unsignierten** Monatsbeleg enthalten kann) gut genug. Letzteres wird im FAQ nr 73 diskutiert und bestätigt.

Zu "§ Abs 7 Abs. 3 RKSV": Das hat der Erlass konkretisiert (oder wie andere meinen: umsetzbar gemacht):
> BMF-010102/0029-IV/2/2016: 3.2.1.4. Sicherung des DEP 
Das vollständige DEP ist zumindest vierteljährlich auf einem elektronischen, externen 
Medium unveränderbar zu sichern. Als geeignete Medien gelten beispielsweise 
schreibgeschützte (abgeschlossene) externe Festplatten, USB-Sticks und Speicher externer 
Server, die vor unberechtigten Datenzugriffen geschützt sind. **Die Unveränderbarkeit des 
Inhaltes der Daten ist durch die Signatur bzw. das Siegel und insbesondere durch die 
signierten Monatsbelege gegeben.** _(meine Hervorhebung)_ Jede Sicherung ist gemäß § 132 BAO aufzubewahren. 
Sollten die Daten des DEP zur Sicherung verschlüsselt werden, müssen die Daten 
inhaltsgetreu wiederhergestellt werden können.

**Comment by argetherapie** [comment]
@senton82 _"Das der letzte Beleg eines DEP-Backups ein gültiger Monats/Jahresbeleg sein muss, war mir bislang nicht klar."_
.. "sein muss" würde ich nicht sagen, jedoch möchte ich behaupten, dass es eine zweckmäßige Strategie zu manipulationssicheren DEP-Sicherungen ist, wenn der letzte Beleg in der Sicherung ein signierter 0-Beleg ist.

**Comment by senton82** [comment]
Ich danke allen Beteiligten für ihren Beitrag. Folgende Dinge halte ich somit für mich fest:

Die Strategie automatisch einen Monats/Jahresbeleg bei funktionierender Signatureinheit zu erstellen ist korrekt. Bei einer ausgefallenen Sicherheitseinrichtung über den Monats/Jahreswechsel würde vor dem ersten wieder gültig signierten Beleg sowohl ein Sammelbeleg als auch ein Monats/Jahresbeleg erstellt werden.

Die Erstellung eines erfolgreich signierten Monats/Jahresbeleg stellt einen guten Zeitpunkt für die manipulationssichere Sicherung des DEP dar. Diesen Gedanken können wir gut nachvollziehen und werden eventuell auch einen automatischen Export anwerfen.

Danke nochmals für euren Input.

**Comment by AxelKutschera** [comment]
Man sollte alle Rechtsgrundlagen und Meinungen beachten.

Z.B. zur "Unveränderbarkeit":
1. "Als geeignete Medien gelten beispielsweise **schreibgeschützte** (abgeschlossene) externe Festplatten, USB-Sticks und Speicher externer Server, **die vor unberechtigten Datenzugriffen geschützt sind."** Das fett gedruckte sollte nicht vergessen werden. = Dies umfasst z.B. auch den Schutz vor dem Löschen. = Revisionssicherheit. Vgl. auch USt-Rili Rz 1566.
2. "Die **Unveränderbarkeit** des Inhaltes der Daten ist durch die Signatur bzw. das Siegel und insbesondere durch die signierten Monatsbelege gegeben." = Vollständigkeitsbeweis.
Es muss auch immer ein internes Kontrollsystem (vgl. KWT, KFS-DV1, Kapitel 5) vorhanden sein.

Zum Zeitpunkt: 
Der Zeitpunk der Sicherung ist irrelevant. 
- Es kann in Echtzeit gesichert werden.
- Es muss spätestens nach einem Vierteljahr gesichert werden. Dies muss jedoch nicht das Quartal sein.

Bei manueller Sicherung wird die Sicherung mit dem Monatsbeleg zu Quartalsende technisch und organisatorisch sinnvoll sein.
