### ISSUE TITLE
hex Zertifikatsseriennummer mit führender "0"

### ISSUE THREAD

**Issue by aunterlu** [a-sit-plus/at-registrierkassen-mustercode#184]
Wir wandeln die Zertifikatsseriennummer in Hex um und hängen am Beginn eine "0" dazu, falls die Stellenanzahl ungerade ist. Wir haben hier leider keine Zertifikate mit so einer Nummer. Ist das korrekt? Im Finanzonline-Dialogverfahren wurde bei der Eingabe dieser Nummer und dem Prüfwert. Die Nummer so akzeptiert und die Signatureinrichtung erfolgreich registriert. Beim Startbeleg gibt es aber anscheinend ein "fail"

**Comment by aunterlu** [comment]
Ich habe es jetzt mit eine Testzertifikat mit einer Hex-Seriennummer mit führender "0" getestet. Das Verifizieren des Datenerfassungsprotokolls liefert auch ein "PASS" zurück. 
In der Dokumentation auf Seite 13 steht bei "Zertifikat-Seriennummer" ein Beispiel Nummer mit ungerader Stellenanzahl wird die Nummer ohne führende "0" angegeben, das hat mich jetzt irritiert.

**Comment by aunterlu** [comment]
Ich habe mir jetzt mit dem Kunden die Registrierungen in FinanzOnline ansehen können. Das Problem ist durch das reinkopieren der Daten mit Cut und Paste passiert. Und zwar an zwei Stellen:
1. Bei der Kassen-ID wurde am Ende ein Leerzeichen eingegeben und damit hat die Kassen-ID mit dem Startbeleg nicht übereingestimmt.
2. Beim Kopieren der Hex-Seriennummer wurde wahrscheinlich auch ein Leerzeichen am Ende mit reinkopiert und deshalb wurde diese Nummer nicht genommen. Der Kunde hat dann die dezimale Seriennummer mit Prüfwert händisch eingegeben und diese wurde gespeichert. Das in der Anzeige von FinanzOnline die führnde "0" nicht angezeigt wird hat nur zur Verwirrung beigetragen.

Nach dem Ausserbetriebnehmen der Kasse und neu Registrieren der Kasse mit der korrekten ID wurde der Startbeleg akzeptiert.

Es wäre gut, wenn Leerzeichen und Zeilenumbrüche  am Anfang und Ende der Eingabedaten im Dialogverfahren automatisch rausgelöscht werden (trim).

**Comment by aunterlu** [comment]
Die Fehlermeldung in FinanzOnline hat übrigens folgendermaßen ausgesehen. Hier sollte vielleicht ein Hinweis auf die falsche Kassen-ID stehen:

VERIFICATION_FROM_CASHBOX
1
Prüfergebnis - Kasse
Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.
FAIL
Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.
2016-11-30T10:24:29.421+01:00
 
 
RECEIPT_FULL
1
Detailprüfung des maschinenlesbaren Codes
Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.
FAIL
2016-11-30T10:24:29.587+01:00
 
 
CRYPTO
1
Kryptographische Prüfungen
In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).
FAIL
2016-11-30T10:24:29.590+01:00
 
 
CRYPTO_TURNOVER_COUNTER
1
Kryptographie: Entschlüsselung des Umsatzzählers
Es wird die Entschlüsselung des Umsatzzählers überprüft. Eine Aussage über die Korrektheit kann nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).
FAIL
2016-11-30T10:24:29.631+01:00

**Comment by asitplus-pteufl** [comment]
Danke für die Informationen! Ich werde diese weiterleiten.

Bezüglich dem Prüftool und der Seriennummer. Dort ist die Prüfung rein auf die Informationen beschränkt die im cryptocontainer File vorhanden sind. Wenn dort die gleiche Seriennummer wie im Beleg gefunden wird, dann passt das für das Prüftool, unabhängig davon was wirklich im Zertifikat steht.

**Comment by aunterlu** [comment]
Vielen Dank fürs weiterleiten!

**Comment by asitplus-pteufl** [comment]
Zu Trim habe ich folgende Aussage vom BMF bekommen:
Die TRIM-Funktion wird mit 20.12.2016 zur Verfügung stehen.

**Comment by aunterlu** [comment]
Sehr gut, wieder eine Fehlerquelle weniger. Danke!
