### ISSUE TITLE
Prüftool ist besser als FinanzOnline

### ISSUE THREAD

**Issue by ct-graz** [a-sit-plus/at-registrierkassen-mustercode#185]
Ich habe soeben für die eigene Firma die Kassa in Betrieb genommen und einen Startbeleg erstellt.
Das Prüftool befindet ihn in Ordnung, die App am Handy auch, nur das Finanzonline-Webservice meldet einen Fehler im maschinenlesbaren Code. CRYPTO_TURNOVER_COUNTER-Fehler "AES-Schlüssel nicht verfügbar".
Im Finanzamt Graz: niemand wissend.
Bei FON alle unwissend und unfähig. Man möge sich an die Foren der WKÖ wenden, denn dort sind sie noch nicht geschult worden.
Nun sehe ich, dass der Beleg durch die App erfolgreich im FON gelandet ist.
Offenbar ist nur das Webservice fehlerhaft.
Von dort ist in nächster Zukunft keine Unterstützung zu erwarten.

**Comment by giemes** [comment]
Schlüssel und Kassa in FinanzOnline bereits eingegeben ?

**Comment by asitplus-pteufl** [comment]
A-SIT Plus wird Fragen die Unterstellungen und/oder Beleidigungen enthalten nicht beantworten.

**Comment by ct-graz** [comment]
Eigentlich enthält dies weder eine Frage, eine Beleidigung, noch eine Unterstellung, nur gesammelte Aussagen der Finanzer im Rahmen eines Telefonmarathons.
Natürlich sind Kassa und SE registriert - mit dem Service. Anderenfalls könnte ja auch die App nicht erfolgreich prüfen.
Conclusio: Bei dieser Fehlermeldung nicht am Prüftool zweifeln, sondern die App verwenden.

**Comment by asitplus-pteufl** [comment]
Stellungnahme des BMF:
Die Belegprüfung mittels App wurde im Produktivsystem durchgeführt und hat funktioniert.
Die Belegprüfung mittels Webservice wurde als Testübermittlung gekennzeichnet und landet daher im Testsystem. Dort ist die Kasse mit der im Beleg angeführte Kassenidentifikationsnummer aber nicht registriert sondern mit einer anderen Kassen-ID und deshalb kann kein AES-Schlüssel ermittelt werden. Es ist daher entweder eine Kasse mit der richtigen Kassen-ID zu registrieren oder die Kassen-ID im Beleg zu ändern.
Eine Übermittlung dieses Beleges als Produktionsübermittlung sollte zu einem positiven Ergebnis führen.

**Comment by ct-graz** [comment]
Heute hat es funktioniert. Es kam sogar die Meldung, dass der Beleg schon da sei.
Da das Service gestern aber zuerst Kassa und SE im Echtsystem definiert hat, kann ich mir nicht erklären, warum das selbe Service den Beleg danach  mit "T" sendete. In der Folge habe ich heute schon immer wieder mit "T" getestet. 
Danke. Schade, dass man selbst am Telefon niemanden erreicht, der das aufklären kann.
