### ISSUE TITLE
Sammelbeleg nach Ausfall

### ISSUE THREAD

**Issue by ckvsoft** [a-sit-plus/at-registrierkassen-mustercode#186]
Kann mir Bitte wer sagen wie es mit der Datumsreihenfolge beim Nachbonieren aussieht?

Signatureinheit Ausfall zb. am ersten in der Früh, Ich Boniere bis Mittag mit Signatr ausgefallen und fahr dann auf Montage, komme aber erst am zweiten in die Firma und möchte die Belege fürn ersten Nachbonieren.
Am zweiten geht aber die Signatureinheit wieder.
Wenn ich jetzt vorher den Sammelbeleg ausstelle weil die Signatur wieder ok ist ist das Datum der zweite und ich könnte ja dann nicht mehr für den ersten Nachbonieren.
Für mich ist es nicht ersichtlich das der Sammelbeleg auch nacher erstellt werden darf.

Danke

**Comment by ErichFreitag** [comment]
Sie sprechen von "Nachbonieren" - das ist ein Vorgang, bei dem sie die während eines Ausfalls der Kasse z.b. händisch erfassten Belege nacherfassen.

Das ist etwas anderes als der Sammelbeleg nach Ausfall und Wiederverfügbarkeit der Signaturerstellungseinheit. Der Erlass gibt unter 3.6.1. dazu Auskunft:

"Der nach dem Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit gemäß § 17 Abs. 4 RKSV erforderliche Sammelbeleg ist unmittelbar nach dem letzten Beleg bei ausgefallener Signatur- bzw. Siegelerstellungseinheit bzw. nach dem ersten Beleg bei wieder hergestellter Signatur- bzw. Siegelerstellungseinheit zu erstellen".

**Comment by ckvsoft** [comment]
Oder auch bei mobilen Gruppen die Ihre händisch ausgestellten Belege "Nachbonieren" auch wenn die Kasse nicht ausgefallen ist.

Im meinen Beispiel ist aber die Kasse ausgefallen, wenn ich Richtig informiert bin darf ich ja auch mit ausgefallener Kasse diese Belege Nachbonieren. Beim Nachbonieren sag ich der Kasse das Datum zb. Gestern und während oder auch kurz davor ist der Ausfall beendet.

Jetzt müsste ich einen Sammelbeleg ausstellen wo der Ausfall von bis drauf steht. Jetzt bin ich aber beim Nachbonieren von Gestern habe zB. zwei Belege Nachboniert und die Kasse geht wieder. Dieser NullBon hat aber das heutige Datum somit könnte ich keine Belege von gestern mehr Nachbonieren. Ich hätte aber noch zB. 10 Stück. Wie geht man damit um.
Hoffe es ist jetzt ein wenig verständlicher was ich meine.

**Comment by AxelKutschera** [comment]
Eine Anmerkung zu Datum/Uhrzeit:
- Nicht das Datum/Uhrzeit des Geschäftsfalls 
- sondern der Zeitpunkt der **Signaturerstellung** ist das korrekte Datum/Uhrzeit des Belegs 
Dies gilt auch bei Nacherfassung das Geschäftsfalls. 
Der Zeitpunkt der Geschäftsvorfalls ist für die RKSV Datum/Uhrzeit des Belegs irrelevant.

**Comment by AxelKutschera** [comment]
SE ist bei uns “SicherheitEinrichtung“
SEE ist bei uns “SignaturErstellungsEinheit“

Wenn die SE ausgefallen ist, dann gibt es kein RKSV-DEP..

Korrekt? LG

**Comment by ErichFreitag** [comment]
Meinerseits ja :-)

**Comment by ckvsoft** [comment]
Wenn ich das mit dem Nachbonieren bei mobilen Gruppen falsch verstanden habe dann wohl auch einige andere. Es gibt in diversen Softwarekassen den Punkt Nachbonieren und man kann das Datum einstellen. 

Sprich egal wann der händisch erstellte Beleg ausgestellt wurde bei der Eingabe in die Kasse wird immer das aktuelle Datum verwendet.  Ok

Lg chris

**Comment by Flanelli** [comment]
Sehr geehrter Herr Kutschera,
möglicherweise liege ich damit falsch aber ich kann Ihrer Ausführung bzgl
_**"Wenn die SE ausgefallen ist, dann gibt es kein RKSV-DEP"**_
nicht nachvollziehen.
Es ist doch lt. den 
FESTLEGUNGEN DES BMF ZU DETAILFRAGEN DER 
REGISTRIERKASSENSICHERHEITSVERORDNUNG (RKSV) 
BUNDESMINISTERIUM FÜR FINANZEN 
A-SIT PLUS GMBH 
VERSION 1.2  –  05.09.2016 
eindeutig wie folgt festgehalten:

3.2  Erstellung der JWS-Signatur **(Sicherheitseinrichtung ausgefallen**) 
Eingabewerte 
   Aufbereitete Belegdaten (Ausgabewert aus Prozess 2.3) 
Prozessbeschreibung  
Beim **Ausfall der Sicherheitseinrichtung** kann die JWS-Signatur nicht erstellt werden. Um dennoch 
in der Lage zu sein, Belege zu erstellen, die der **RKSV entsprechen und im DEP abgelegt** werden 
können,  wird  für  diese  Fälle  eine  zur  kompakten  Repräsentation  der  JWS-Signatur  kompatible 
Darstellung  gewählt:  header.payload.sicherheitseinrichtung-ausgefallen.  Die 
ersten  beiden  Elemente  header  und  payload  entsprechen  dabei  der  kompakten  JWS-
Repräsentation. 
   Header: siehe Prozess 3.1 
   Payload: siehe Prozess 3.1 
   sicherheitseinrichtung-ausgefallen:  Statt  dem  Signaturwert,  der  in  diesem  Fall  nicht 
berechnet  werden  kann,  wird  die  Zeichenkette  Sicherheitseinrichtung 
ausgefallen BASE64-URL kodiert und als drittes Element anstelle des Signaturwertes 
in  der  kompakten  Darstellung  der  JWS-Signatur  verwendet.  In  der  BASE64-URL 
Kodierung  entspricht  dies  dem  Wert 
U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg.

Somit wäre logischerwiese allenfalls bei einem physischen Ausfall der Kassa kein RKSV-DEP möglich
aber falls nur die Signatureinheit ( sprich Karte oder Reader ) defekt ist, wird durch die Simulation
über die kompatible Darstellung das RKSV-DEP samt Umsatzzähler etc. weiter erstellt.

Sehe ich das nun wirklich falsch?

**Comment by AxelKutschera** [comment]
Ich sehen das Problem in diesem Satz:
"Beim Ausfall der **Sicherheitseinrichtung** kann die JWS-Signatur nicht erstellt werden. Um dennoch
in der Lage zu sein, Belege zu erstellen, die der RKSV entsprechen und im DEP abgelegt werden
können, wird für diese Fälle eine zur kompakten Repräsentation der JWS-Signatur kompatible
Darstellung gewählt: header.payload.sicherheitseinrichtung-ausgefallen."
- Ich meine, dass hier anstelle von "**Sicherheitseinrichtung**" der Begriff "**Signaturerstellungseinheit**" stehen müsste. - Hier gilt die RKSV.
- Verwirrend wird es natürlich dadurch, dass in diesem Fall "**Sicherheitseinrichtung ausgefallen**" auf dem Beleg stehen soll. Korrekt wäre "**Signaturerstellungseinheit ausgefallen**".

**Comment by Flanelli** [comment]
Herzlichen Dank für das Aufzeigen dieses "Problems".
Leider ist dieser Fall bzw. der terminologische Umgang seitens des "xxx". nicht der einzige Umstand
der zur Verwirrung in der gesamten Causa beiträgt. Man muß sich halt schlicht und einfach immer
vor Augen halten das klare Aussagen und 100%-tig eindeutige Nachvollziehbarkeiten immer nur
vom Unternehmer und Steuerzahler eingefordert werden.. Dieser hat daher wohl auch gegebenenfalls
alle Auslegungen  des Gesetzgebers als unmißverständlich zu betrachten und sich danach zu richten.
Sollte nun jemand meine Worte möglicherweise auch als beleidigend intepretieren erlaube ich mir den Verweis auf das standardisierte "Es gilt die Unschuldsvermutung".

**Comment by ckvsoft** [comment]
Das ist durchaus etwas verwirrend. Für was steht der Begriff Sicherheitseinrichtung?
Wenn ich die Aufbereitung selbst in der Kasse mache kann eigentlich nur die Signaturerstellungseinheit ausgefallen sein. Dann wird eben mit sicherheitseinrichtung-ausgefallen signiert.
Ansonsten funktioniert ja die Kasse eh gleich gar nicht.

Wenn die Sicherheitseinrichtung extern ist schaut das wieder anders aus. Dann kann ja auch nicht mit sicherheitseinrichtung-ausgefallen signiert werden.

**Comment by ErichFreitag** [comment]
Was unter der Sicherheitseinrichtung gemäß RKSV zu verstehen ist, ist auch dort definiert, nämlich die Verkettung der Barumsätze/Belege. Das bedingt eine Signaturerstellungseinheit und das DEP.

Gleichzeitig ist mit "Sicherheitseinrichtung ausgefallen" eigentlich die Signaturerstellungseinheit gemeint, die Begriffe werden vermischt. Ist so.

Somit: SE(E) = Signaturerstellungseinheit nicht verfügbar = "Sicherheitseinrichtung ausgefallen".

Kein Zugriff auf das DEP etc. = Kasse ausgefallen. "Die Kasse" könnte noch funktionieren, darf aber nicht (weil keine Belegverkettung mehr hergestellt werden kann).

**Comment by lebail** [comment]
Noch eine Frage, die irgendwie zu dieser Thematik passt (keine Sorge, mir sind die RKSV-Hintergründe klar, und ich kenne den Unterschied zwischen Kassen- und Sicherheitseinrichtungsausfall):

Wäre es zulässig, im Falle einer ausgefallenen Sicherheitseinrichtung gleich die ganze Kasse als ausgefallen zu betrachten und bis zur Behebung des Schadens händische Belege auszustellen (und diese dann nachzuerfassen)?

Hintergrund der Frage ist ein Kassenbetreiber, der nur eine Handvoll Umsätze pro Monat macht (damit aber dennoch über die Umsatzgrenze kommt) und seinen Kunden keine Belege mit der Aufschrift "Sicherheitseinrichtung ausgefallen" aushändigen möchte (nebst Erklärung, warum das da steht).

**Comment by ErichFreitag** [comment]
Rein formal nein. Sowohl die RKSV als auch die Schnittstelle zu Finanz-Online trennen diese beiden Szenarien klar.

**Comment by MartinDomig** [comment]
Ich weiß von zumindest einem (sehr großen und bekannten) Kassenhersteller, das genau so handhabt.

**Comment by geraldsix** [comment]
Ich habe ein anderes Problem das zum Thema Ausfall einer SEE passt.
Es ist bei einem unserer größeren Kunden geplant im Bezug auf das DEP einen Kassenverbund einzurichten. D.h. alle Kassen-Arbeitsplätze in der Filiale arbeiten sollen mit der selben Kassen-ID arbeiten und sind im Sinne der RKSV eine Kasse mit mehreren Eingabestationen. Jeder Arbeitsplatz hat jedoch seine eigene SEE zugeordnet. Wenn ich jetzt z.B. auf Eingabestation 1 eine Ausfall der SEE habe und auf Eingabestation 2 funktioniert sie weiterhin, dann hätte ich im DEP ja durcheinander Beleg mit "Signatureinrichtung ausgefallen" und richtig signierten. 
Ist das so zulässig - oder muss in diesem Fall wenn eine SEE ausfällt alle Belege mit "Signatureinrichtung ausgefallen" übermittelt werden, solange bis wieder alle funktionieren?

**Comment by ckvsoft** [comment]
@ErichFreitag Was unter der Sicherheitseinrichtung gemäß RKSV zu verstehen ist, ist auch dort definiert, nämlich die Verkettung der Barumsätze/Belege
so hätte ich das auch gesehen, in meinen Fall funktioniert auch die Kasse nicht. War nur etwas verwirrend.
Danke für mich scheint jetzt alles klar zu sein.

**Comment by ErichFreitag** [comment]
@ckvsoft: fein.

@MartinDomig: Vorgabe und Handhabung können zwei unterschiedliche Dinge sein.

@geraldsix: bitte ein neues Issue dazu erstellen

**Comment by Flanelli** [comment]
Um nun das ganze Prozedere noch verwirrender zu machen hat nun aktuell die Wirtschaftskammer einen leitfaden für Unternehmer als PDF veröffentlich in dem aud Seite 32 wie folgt zu lesen ist: 

Wenn nur die Signaturerstellungseinheit ausfällt kann unter folgenden 
Voraussetzungen weiter gearbeitet werden:
•  Das Kassensystem muss auf jedem Beleg den Hinweis  
**„Signaturerstellungseinheit ausgefallen“** drucken.

Nur zur Klarstellung, ich kann sehr wogl bestens zwischen den beiden Begriffen "Signatur" und "Sicherheit"
unterscheiden und betrachte zwangsläufig den derzeit vom BMF vorgegebenen Begriff "Sicherheitseinrichtung ausgefallen" als verbindlich aber es ist letztendlich schlicht und einfach desaströs wie in der gesamten Angelegenheit alleine schon begriffsbestimmend keine durchgehende Einigkeit herrscht.  Erklären Sie bitte das einmal einem Kunden der in diesem Falle die Info vom WKO liest und dann am Beleg etwas anders vorfindet. Ein "Sie können uns getrost vertrauen" würde ich jedenfalls als Kunde nicht akzeptieren ...
.

**Comment by ErichFreitag** [comment]
Wie dem Readme und den gelegentlichen Ergänzungen von Hr. Teufl zu entnehmen ist, handelt es sich hier um ein Forum der A-SIT zur Beantwortung technischer Fragestellungen rund um die RKSV.

Wir haben uns darauf verständigt, dass unter diesen Voraussetzungen auch rechtliche und organisatorische Fragestellungen zugelassen und soweit hier möglich beantwortet werden. Das erfolgt freiwillig, kostenlos und vor allem zu dem Zweck, den Herstellern Antworten auf Fragen zu geben, Unterstützung bei Problemen zu geben und Lösungsmöglichkeiten im Rahmen der Vorgaben aufzuzeigen, um eine rechtskonforme und wirtschaftlich vernünftige Implementierung zu ermöglichen. 

Meiner Ansicht nach ist daher dieses Forum nicht dazu da
- um darüber zu diskutieren, was jemandem gefällt oder nicht
- um darüber zu diskutieren, was jemand wissentlich oder unwissentlich anders implementiert hat als dies gefordert ist
- sich darüber zu monieren, dass jemand etwas fälschlich oder in Unkenntnis verbreitet

Zwecks Übersichtlichkeit bitte auch für ein neues Thema ein neues Issue anzulegen und gegebenenfalls auf bestehende Issues zu verlinken, ansonsten die Übersichtlichkeit stark leidet.

**Comment by Flanelli** [comment]
Sehr gehrter Herr Ing. Freitag,
tut mir leid - danke für den freundlichen Hinweis - ich werde dies zukünftig beachten.

**Comment by AxelKutschera** [comment]
@lebail (ich war leider 20 Stunden offline, möchte aber noch ergänzen.)
* Die beiden Begriffe "Kassen- und Sicherheitseinrichtungsausfall" sind für uns **rechtlich** gleichbedeutend, da die "Kasse" im Sinne der RKSV als funktionierende Sicherheitseinrichtung (SE = DEP + KA-ID) angesehen wird. Wenn die SE (das DEP) ausfällt, dann ist die RegK ausgefallen.
* Wir definieren es so:
  - Ausfall der RegK = Ausfall des gesamten Kassensystems (zB Hardware oder E131-DEP kann nicht geschrieben werden)
  - Ausfall der SE = RKSV-DEP kann nicht geschrieben werden.
  - Ausfall der SEE = Es kann nicht korrekt signiert werden.

Zu: "Wäre es zulässig, im Falle einer ausgefallenen Sicherheitseinrichtung gleich die ganze Kasse als ausgefallen zu betrachten und bis zur Behebung des Schadens händische Belege auszustellen (und diese dann nachzuerfassen)?"
* In der § 17 Abs 5 RKSV steht, dass im Falle des Ausfalls der SE eine andere RegK verwendet werden soll, falls dies nicht möglich ist, **sind** händische Belege auszustellen und nachzuerfassen. 
(@ErichFreitag : Bitte korrigiere mich, da Du "Rein formal nein" geschrieben hast.)

--> Daher hat der Kassenbetreiber in diesem Fall keine Beleg mit der Aufschrift "Sicherheitseinrichtung ausgefallen" auszuhändigen.

Falls diese Belegerstellung dennoch mit der RegK gemacht wird, empfehlen wir das in der fiskaltrust-Schnittstelle so: "Die Registrierkasse bzw. Eingabestation muss automatisch einen Beleg und eine Beleg-Zweitschrift erstellen. Der Beleg ist mit der Kennzeichnung „Elektronisches Aufzeichnungssystem ausgefallen“ und einem laufenden Fehler-Zähler anstelle des Signaturblocks zu versehen." 

Ich hoffe, dass ich die Szenarien ausreichend verständlich beschrieben habe und stehe bei Fragen gerne zur Verfügung.

**Comment by AxelKutschera** [comment]
@Flanelli : Daher ist es ganz wichtig, dass wir versuchen, die Begriffe ganz deutlich zu trennen.

**Comment by AxelKutschera** [comment]
@geraldsix : 
* DEP mit durcheinander Beleg mit "Signatureinrichtung ausgefallen" und richtig signierten.
--> Das sehe rechtlich nach § 17 Abs 4 RKSV nur dann zulässig, wenn keine andere RegK verwendet werden kann. 
Daher sollte es nicht - bzw. nur bis zum Erkennen des Ausfalls - passieren, dass eine RegK mit SEE mit "**Sicherheits**richtung ausgefallen" (nicht "Signatureinrichtung ausgefallen") arbeitet. 
Diese Belege im Ausfallmodus müssen mit einem Sammelbeleg abgeschlossen werden.

Falls es ein "geschlossenes Gesamtsystem" nach § 20 ff RKSV werden soll (nur dort wird der Ausdruck "Kassenverbund" verwendet), gibt es noch einige andere interessante Fragen für die spezielle Lösungen umsetzbar sind.

**Comment by ErichFreitag** [comment]
Keine Korrektur, @AxelKutschera. 

@lebail hatte sich für mich auf den Ausfall der Signaturerstellungseinheit bezogen (Schluss aus dem Text "Sicherheitseinrichtung ausgefallen" am Beleg), daher kein Kassenausfall und damit auch nicht dadurch ersetzbar.

**Comment by ErichFreitag** [comment]
@geraldsix - wir hatten solche Fälle hier schon einige Male - sie handeln sich durch diese Architektur Probleme ein, siehe z.B. https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/135.

**Comment by Flanelli** [comment]
Sehr geehrter Herr Kutschera,
ich erlaube mir daher nachstehend nochmals die Zusammenfassung der Szenarien wobei ich in
diesem Fall davon ausgehe dass die Sicherheitseinrichtung lokal auf einem PC über einen Reader samt
Karte abläuft ( kein WEB,, kein Server - lediglich ein PC )
Als Begriffsbestimmung gelten Ihre Ausführungen
**SE ist bei uns “SicherheitEinrichtung“
SEE ist bei uns “SignaturErstellungsEinheit"**  

1) Fällt die SEE aus wird weiter boniert,, der Beleg mit header.payload."Sicherheitseinrichtung
    ausgefallen"  erstellt und im DEP abgelegt. Nachdem in den 
    FESTLEGUNGEN DES BMF ZU DETAILFRAGEN 05.09.2016
    unter 3.2 Erstellung der JWS-Signatur (Sicherheitseinrichtung ausgefallen)    
    eindeutig festgehalten  wir wie dies zu erfolgen hat kann es doch rechtlich keinesfalls so sein dass
    dies nur dann erfolgen darf wenn keine andere Reg-Kassa vorhanden ist bzw. die aktuelle Kassa
    ja alles andere korrekt durchführen ( bis eben auf die Signatur ).
    Somit ist es zwangsläufig so dass im DEP sowohl "korrekt" signrierte als auch "kompatibel" signierte
    Daten aufweisen kann. 
    Nachdem rein rechnisch der Umsatzzähler und die lückenlose Belegfolge ja nicht von der Funktion der 
    SEE abhängig ist wären handschriftlichen Belege und deren Nachbonierung sinnlos und überflüssig.

2) Fällt die SE aus kann dies wohl nur auf einem technischen Problem der Routinen Base64, Base64-URL, 
    AES256-Verschlüsselung,, SHA256 beruhen. In diesem Fall wäre die korrekte Abbildung eines Beleges
    im DEP generell nicht mehr möglich und somit wäre dies automatisch gleichzusetzen mit einem Ausfall 
    der Registrierkasse als Ganzes.
    Nachdem es lt. Gesetzgeber in der Kassa keine Umgehung der Sicherheisteintischtung geben darf wäre
    auch eine weiter Bonierung auf dieser Kassa bzw. dem Kassenpörogramm am PC bos zur Behebung 
    des Problems unzulässig.
    Anstelle in diesem Fall aber handschriftliche Belege auszustellen und insbesondere trotz prinzipiell ja
    funktionierende Kassa auf alle anderen Aufzeichnungen wie Statistiken, Kundenrabatte,
   Tagesabschlüße, Gutscheinverwalrungen etc. etc. etc. zu verzichten ist die grundlegende Installation 
   eines Zweitsystem am PC die wohl einzig sinnvolle Lösung. Dieses System umgeht keine 
   Sicherheitseinrichtung sondern übernimmt lediglich die "handschriftliche" Belegerstellung und speichert 
   alle relevanten internen Daten für Statistiken etc. siehe zuvor )
   Auf den Belegen für den Kunden wird deutlichst darauf huingewiesen dass die Erstellung ohne jegliche 
   Sicherheitseinrichtung erfolgt ist,, auch der QR-CODE enthält den Hinweis in Reinschrift und auch 
   ansonsten werden alle Daten mit einem Kennzeichen versehen.
   Es ist wohl nicht vorstellbar dass der Gesetzgeber die Erstellung von Belegen im Falle eines 
   Kassenauisfalles ZWINGEND handschriftlich einfordern kann. Dies würde schon aus rein
   gleichstellungstechnischen Richtlinien gar nicht standhalten.
 
3) Fällt die Kassa bzw. der PC bzw. die Software als Ganzes aus stellt sich keine weitere Frage
    Die Erfassung der Belege wird auch da sinnvollerweise nicht handschriftlich sondern mit einem
    "Notfallsystem" erfolgen

Wie gesagt, alles bezieht sich auf eine reine Kassa Typ 3 ( PC-Kassa ) mit lokaler SE / SEE
Hier wird es im Normalfall wohl nur zu temporären Ausfällen der SEE kommen.
Das Szenario reicht von "Ich zieh mal die Karte raus und schau was da drauf ist" bis zum immer wieder
mal auftretenden "Nebengeräuschen" von Kartenlesern und dergleichen.
Der worst case würde jedenfalls ganz andere Probleme mit sich bringen als die hier aungeführten
aber damit muß man auch im Handel schon seit langem leben bzw. hoffen es nicht zu erleben.

**Comment by ErichFreitag** [comment]
Ich darf dem Axel Kutschera kurz vorgreifen:

1. Ausfall der SEE - ich formuliere es als "Sicherheitseinrichtung ausgefallen" im Klartext am Beleg sowie statt der Signatur, damit auch im maschinenlesbaren Code und im DEP - korrekt. Weiterarbeiten möglich, Fehlerbehebungsmaßnahmen einleiten, Sammelbeleg nach Wiederverfügbarkeit.


2. Nicht nur - es kann die Festplatte defekt oder voll sein, die Datenbank nicht verfügbar sein - was auch immer daran hindert, das DEP zu lesen oder zu schreiben. Kasse ist damit "tot". Damit gibt es aber auch keinen QR-Code mehr, mit dem sie auf etwas hinweisen können. Es gibt dafür auch keine Vorgabe. 

Maßnahme: händische Belege+Zweitschrift oder wie oben von @AxelKutschera beschrieben elektronische Belege+Zweitbelege. Dazu auch ein Zitat "Wenn die Registrierkasse ausfällt und weiterhin über die Eingabestationen erfasst werden kann, so ist in der Registrierkasse eine Nacherfassung samt Signatur vorzunehmen" aus dem letzten Arbeitskreis Kassensoftware der WKO. 

Ob sie ein Zweitsystem brauchen oder nicht wird nicht zuletzt stark branchen- und funktionsabhängig sein. Und wenn sie schon ein Zweitsystem haben können sie ja auch dort die Signaturerstellungseinheit wieder anstecken?


3. siehe 2.

**Comment by Flanelli** [comment]
Sehr geehrter Herr Ing. Freitag,
ein weiteres mal Dank für die klare und präzise Aussage.
Punkt 1) ist damit zumindest für mich erledigt und so zu handhaben
Punkt 2/3) Das "Notfallsystem" ist auch nur dafür gedacht dass bei Totalausfall zumindest sehr rasch
über ein Restore der Stammdatensicherung die vorübergehende Belegerstellung ohne jedes weiterem eventuell noch zusätzlich auftretende Handicap mit der SE/SEE erfolgen kann. 
Der QR-Code wird in diesem Fall "direkt" und ohne jegliche Verschlüsselungen etc. rein als einscanbare
Textmenge erstellt , so wie dies auch bisher seit etlichen Jahren bei uns Usus war. Die zusätzliche Ablage dieser Daten erfolgt auch wie bis dato in internen Protokollen und somit kann auch eine lückenlose Erfassung elektronisch nachgewiesen werden. Wie gesagt - lediglich der Notfall.  
Das diese Vorgangsweise anstelle einer händischen Paragonschreiberei vom Gesetzgeber "verboten" ist
kann ich mir beim besten Willen nicht vorstellen denn "Zettelbeweise" würden sich ja weitaus leichter als maniuplatiives Instrument eignen wenn es jemand darauf anlegen sollte.   

Jedenfalls nochmals Danke, zumindest für meine Wenigkeit sehe ich nun diese Thema als positiv abgeschlossen und somit der Gesamtablauf angeruindet und einsatzbereit.

**Comment by AxelKutschera** [comment]
@Flanelli : 

Zu 1.: Wie weiter oben geschrieben gilt das nur, wenn keine andere funktionierende RegK vorhanden (§ 17 Abs. 4 RKSV)
Zu 2. + 3.: Korrekt. Wir schreiben in diesem Fall „Elektronisches Aufzeichnungssystem ausgefallen“ auf den Beleg.

Wir haben diese Szenarien in unserer kostenfreien Middleware abgebildet und in der Entwickler-Doku beschrieben. https://github.com/fiskaltrust/interface

**Comment by Flanelli** [comment]
Sehr geehrter Herr Kutschera,,
auch Ihnen herzlichen Dank, es löst sich somit auch in Wohlgefallen auf..
