### ISSUE TITLE
FORMAT_CHAIN_VALUE Fail

### ISSUE THREAD

**Issue by xandi1987** [a-sit-plus/at-registrierkassen-mustercode#187]
Guten Abend,
ich bekomme bei meinen Tests den Fehler "Die Länge des Verkettungswertes ist ungleich 64 Bit.". Ich habe den Code mehrmals überprüft und finde keinen Fehler. Kann überprüft werden ob das Prüftool einen Bug enthält?
Anbei mein Test-Export.

Mfg

Alexander Ziegler 

[dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/637486/dep-export.txt)

**Comment by Flanelli** [comment]
Auf den ersten Blick sieht das nach fehlender Base64-URL kodierung aus
 z.B. == am Ende kann nicht sein, auch statt + sollte ein - sein

**Comment by ckvsoft** [comment]
@xandi1987 mit Base64-URL noPadding kodieren.

lg Chris

**Comment by asitplus-pteufl** [comment]
@xandi1987 konnten Sie das Problem mit den Hinweisen lösen?

**Comment by xandi1987** [comment]
Es lag an etwas völlig anderen. Danke aber trotzdem ich konnte das Problem lösen. Bitte entschuldigen Sie die späte Antwort.

**Comment by AxelKutschera** [comment]
@xandi1987 : Wir sind doch eh alle bei der Arbeit. ;-)
