### ISSUE TITLE
getValueFromMachineCode() offset problem

### ISSUE THREAD

**Issue by toshniba** [a-sit-plus/at-registrierkassen-mustercode#188]
Ein simples split('_') ist hier nicht ausreichend, weil die KassenID beliebig sein kann (auch mit Unterstrich(en)). Ebenso die Belegnummer.

**Comment by lebail** [comment]
Wenn in der Kassen-ID oder der Belegmnummer ein Unterstrich enthalten wäre, dann müsste dieser "escaped" werden. Anderenfalls wäre eine korrekte Auftrennung der Felder nicht möglich. Ob alle beteiligten Programme das Escaping unterstützen, ist allerdings fraglich.

Angesichts potentieller Probleme wäre es wohl empfehlenswert, dass eine Kassensoftware in den Feldern  Kassen-ID und Belegnummer keine Unterstriche zulässt.

Das Thema hatten wir übrigens schon: https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/41

**Comment by toshniba** [comment]
Danke für die schnelle Antwort.
Aber das ist nur informell soweit ich das nachvollziehen kann.
Also ist es ein Good-Will der Hersteller (also uns), dass wir den Unterstrich am Besten ganz verbieten, auch wenn die eigenen Software dafür ausgelegt ist!?
Bei der Kassen-ID ja noch ok, aber die Belegnummer ist ja schon (ewig) im selben Format (u.U. mit Unterstrich) in Verwendung. Hier müsste dann auch ggf. eine Adaption erfolgen?!
Und bezüglich der Kassen-ID würde ich das schon noch deutlich kommunizieren, da der Unterstrich sicherlich ein sehr beliebtes Trennzeichen für viele sein wird.
Man hätte wohl die base-Kodierungen noch weiter in die Paranoia reiten sollen und um diese zwei Felder erweitern... ;-)

**Comment by asitplus-pteufl** [comment]
Das Verwenden von "_" ist nicht möglich, da es als Trennzeichen definiert ist (siehe RKSV bzw. Detaildokumente). 
BASE64-Kodierung wird nur dort verwendet wo Binärdaten in Verwendung sind. Eine Anwendung von BASE64-Kodierung auf andere Felder würde den maschinenlesbaren Code verlängern. Dies ist angesichts der QR-Kodierung nicht wünschenswert. 
Falls man das "Paranoia" interpretieren darf: nur dass da keine Missverständnisse aufkommen: BASE64-Kodierung führt keine Verschlüsselung durch. Die wird nur beim Umsatzzähler über den AES-Algorithmus durchgeführt.

**Comment by toshniba** [comment]
Das hab ich bisher wohl überlesen, dass das Trennzeichen "_" als gültiges Zeichen in BelegNr und KassenID ausgeschlossen ist. Bitte wo steht das? Oder soll die Verwendung als Trennzeichen diesen Ausschluss implizieren?

**Comment by lebail** [comment]
Es steht vermutlich nirgends.

Das ist wohl eines der vielen Dinge, an die man bei der Erstellung der RKSV nicht gedacht hat. Daher steht dort jetzt eben drinnen, dass sämtliche UTF8-Zeichen zulässig sind - auch wenn die Verwendung des Trennzeichens (Unterstrich) innerhalb der Felder aus technischer Sicht kaum erstrebenswert ist.

**Comment by asitplus-pteufl** [comment]
das muss nicht genannt werden, da die Verwendung als Trennzeichen die Verwendung in den Feldern implizit ausschließt.
Bitte um eine Präzisierung der "vielen Dinge", damit etwaige technische Punkte berücksichtigt werden können.

**Comment by toshniba** [comment]
Hmm ist wohl sowas wie ein Programmierer-Codex den ich noch nicht kenne? Wie ist das rechtlich gedeckt?

**Comment by lebail** [comment]
@asitplus-pteufl: Mit den "vielen Dingen" meinte ich jene, die erst später (z.B. im Erlass) konkretisiert wurden, bzw. von denen sich zeigte, dass sie ursprünglich suboptimal festgelegt wurden.

Z.B. wurde der Aufbau des maschinenlesbaren Codes in einer sochen Weise festgelegt, dass man einige von der RKSV verlangte Daten nur mit Mühe (und ziemlich unelegant) darin unterbringen kann (siehe z.B. "TRA" und "STO" im Umsatzzähler-Feld, Kennzeichnung des Ausfalls der Sicherheitseinrichtung, Unmöglichkeit der Erweiterung der USt.-Felder - z.B. um zwischen USt.-befreit und diversen USt.-Sonderfällen unterscheiden zu können).

Derzeit sind aus meiner Sicht aber keine technischen Punkte mehr offen - nicht zuletzt dank Ihrer vorbildlichen Arbeit.

**Comment by asitplus-pteufl** [comment]
@toshniba aus der Sicht dieses Projekts (Mustercode, Prüftools für Hersteller), das nur technische Aspekte abdecken kann, ist es eindeutig, dass ein definiertes Trennzeichen nicht Teil eines Feldes sein kann.

rechtliche und organisatorische Aspekte/Fragen können im Rahmen dieses Projekts nicht behandelt werden. Ich ergänze diesen Eintrag noch um den Standard-Disclaimer zu diesen Aspekten:

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by asitplus-pteufl** [comment]
@lebail danke für die Infos.

**Comment by toshniba** [comment]
In Ordnung, bleiben wir beim technischen Aspekt. Woher kann man ableiten, dass das Trennzeichen nicht verwendet werden darf? Z. B. im Vergleich zum CSV-Format, bei dem im Falle der Verwendung eines Kommas ein Enclosing durchgeführt werden muss.
Und selbst wenn der Unterstrich in der Kassen-ID oder der Belegnummer escaped wird, dann wäre das simple split('_') immer noch falsch - zumindest in der Programmiersprache, die ich verwende. Ist das in Java anders?

**Comment by asitplus-pteufl** [comment]
Bei CSV ist ein Escape Zeichen definiert, in der RKSV nicht. Daher kann auch keine Escape-Sequenz abgeleitet werden.

**Comment by toshniba** [comment]
In Ordnung, dachte ja nur, dass die Klarstellung mit dem Trennzeichen irgendwo geregelt und klar dokumentiert hätte werden sollen.

**Comment by asitplus-pteufl** [comment]
@toshniba Diese Anmerkung nehme ich natürlich gerne entgegen und werde sie an das BMF weitergeben. Danke für den Hinweis.

**Comment by Flanelli** [comment]
Die "Exlusivität" des Unterstriches ist meines Erachtesn auf den ersten Blick erkennbar und daher auch
eindeutig ohne weitere niotwendige Erwähnung aus der Definition in der Dolumentation unter
2.3  Aufbereiten der zu signierenden Daten 
Für die Aufbereitung der zu signierenden Daten wird wie folgt vorgegangen: 
Zusammenfügen der Belegdaten: Die Werte, der im vorigen Schritt definierten 
**Belegdaten, werden über das Zeichen _ zusammengefügt**  

Da würde mich schon eher der Aspekt stören dass aufgrund der Gegebenheiten das JSON-Format für
numerische Wert "zurechtgebogen" wurde. Natürlich ist in vielen Bereichen eine benutzerspezifische Definrtion machbar wenn der Beistrich anstelle des Punktes als Dezimaltrennzeichen verwendet wird.
Der Grund dafür ist schon klar aber dennoch sollte dann trotz Hinweise auf diese "Verbiegung"
nicht  als Format: 
 **JSON-Format  **number**  mit  2  Kommastellen**.  Dezimaltrennzeichen entspricht , 
als Terminus gewählt werden.
Das ist definitiv ein technischer Aspekt den der Gesetzgeber halt "verbiegt".

Ich hoffe, ich habe mich nicht wieder daneben benommen indem ich darauf hingewiesen habe. :-)
