### ISSUE TITLE
"FAIL" bei Receipt-Prüfung 

### ISSUE THREAD

**Issue by Flanelli** [a-sit-plus/at-registrierkassen-mustercode#189]
[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/643746/0000_cashbox_full.txt)
Ich wäre sehr dankbar wenn mir jemand erklären könnte warum
via regkassen-verification-receipts-1.0.0.jar
im Prüfergebnis ( 0000_cashbox_full.json ) im Teilbereich
    "verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",

das "FAIL"  ausgewiesen wird.
[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/643746/0000_cashbox_full.txt)

Es handelt sich bei diesem Beleg um einen Startbeleg der zudem auch im Prüfergebnis
"verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "PASS",
  "verificationResultDetailedMessage" : "Die Registrierung Ihrer Registrierkasse und der Signatur-/Siegelerstellungseinheit war erfolgreich. Der vorliegende Startbeleg wurde gesetzeskonform erstellt. Bundesministerium für Finanzen.",

offensichtlich alles ok ist?

Bei allen anderen darauf folgenden Belegen ist im übrigen 
    "verificationId" : "RECEIPT_FULL", mit "PASS" ausgewiesen

Herzlichen Dank

**Comment by ErichFreitag** [comment]
Siehe z.B. https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/178, https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/181 etc. Hilft das weiter?

**Comment by Flanelli** [comment]
Sehr geehrter Herr Ing. Freitag,
wie immer von Ihnen die klare, weiterführende Erklärung.
Herzlichen Dank.

PS.: Nachdem nun das Prüftool läuft ( lag an der policy ) verunsichert ledes "Fail" 
dass eigentlich keines sein kann ein wenig, aber ich lerne nun auch durch noch
sorgsameres Lesen in anderen Beiträgen dazu.

**Comment by asitplus-pteufl** [comment]
noch zwei kurze Infos von mir:
-Doppelte Ausgabe ist ein Fehler, wie in den anderen Issues beschrieben, bitte ignorieren

-Bei den Belegtypen gibt es immer FAILs da ja nur ein Belegtyp auf PASS sein kann.

@ErichFreitag  Danke für die Hinweise!

**Comment by Flanelli** [comment]
Ebenfalls schönen Dank Herr Dr. Teufl,
Damit erlaube ich mir das Schließen des Issue
