### ISSUE TITLE
Code Beispiele

### ISSUE THREAD

**Issue by mprunner** [a-sit-plus/at-registrierkassen-mustercode#19]
wird es auch kleine Beispiele in anderen Programmiersprachen geben (vb, vb.net  oder c# ) ?

**Comment by pteufl** [comment]
Aktuell gibt es dazu keine Planung. Vielleicht aber ein paar Hintergrundinfos dazu:
Java ist eine High-Level und weit verbreitete Sprache (TOP 1 laut http://spectrum.ieee.org/computing/software/the-2015-top-ten-programming-languages). Darum wurde sie auch für den Mustercode gewählt. Java ist auch hervorragend geeignet um Beispiel Code zu erstellen, da eine hohe Lesbarkeit gegeben ist. 
Der vorhandene Code kann unabhängig nicht direkt in einer (JAVA) Kassenimplementierung verwendet werden, da sich der Code nur auf die Demonstration der wichtigen Elemente der RKSV fokussiert und nicht auf produktive Notwendigkeiten (Tests, Exception Handling, Logging etc., der Code enthält demo-spezifische Funktionen wie beschädigte sig-einrichtungen etc.). Es wurde aber sehr wohl darauf geachtet spezielle Eigenschaften die in anderen Sprachen (bzw. Bibliotheken) nicht vorhanden sind allgemein dazustellen. Bsp dafür ist die Verschlüsselung mit CTR. In anderen Sprachen gibt es diesen Modus nicht. Deswegen wurden im Code Beispiele gezeigt wie man diesen Modus emulieren kann. Ähnliches gilt für PKCS11 und die geplante Integration von APDUs für die Ansteuerung von Karten (sofern wir von allen ZDAs die Informationen dazu bekommen).
