### ISSUE TITLE
Die kryptographische Gültigkeit der Signatur ist nicht gegeben

### ISSUE THREAD

**Issue by herbertmanfred** [a-sit-plus/at-registrierkassen-mustercode#190]
Zum Testen der Signatur mit A-Trust Karte habe ich für  regkassen-verification-receipts-1.0.0.jar einen minimalen Testfall erstellt mit nur einem Eintrag (qr-code-rep.json):
````json
["_R1-AT1_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-1_2016-12-10T16:55:29_0,00_0,00_0,00_0,00_0,00_4r1iIdZGeAQ=_a1234567_cg8hNU5ihto=_thIc92iHJjjTB+pccXKcx6uPaAGlTXtZQoHPaaITQXD0IsZSfC99+adc9HPrGAHXs4pvnHSUXvijCCvFPs2o0hw=="]
````

zu diesen Werten komme ich mit dem Code (von apduExamples_0.5):
(der QR Code Eintrag entspicht dem String ``qr_str ``)

```java
package at.atrust.cashregister;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

import javax.smartcardio.Card;
import javax.smartcardio.CardException;
import javax.smartcardio.CardTerminal;
import javax.smartcardio.CardTerminals;
import javax.smartcardio.TerminalFactory;

import org.bouncycastle.cert.X509CertificateHolder;

/**
 * Created by chinnow on 21.10.2015.
 */
public class ExampleClient {

	public static void main(String[] a) {

		try {
			List<Card> cards = getAttachedCards();
			Card myCard = cards.get(0);
			ICashRegisterSmartCard cashRegisterSmartCard = CashRegisterSmartCardFactory.createInstance(myCard);
			String cin = cashRegisterSmartCard.getCIN();
			//System.out.println("I'm using card with cin " + cin);
			X509CertificateHolder cert = cashRegisterSmartCard.getCertificate();
			//System.out.println("I'm using cert with Subject " + cert.getSubject().toString());
			String certSerialDec = cashRegisterSmartCard.getCertificateSerialDecimal();
			//System.out.println("I'm using cert with ID (dec) " + certSerialDec);
			String certSerialHex = cashRegisterSmartCard.getCertificateSerialHex();
			//System.out.println("I'm using cert with ID (hex) " + certSerialHex);
			
			String signatureCertificateOrPublicKey = Base64.getEncoder().encodeToString(cert.getEncoded());
			System.out.println("signatureCertificateOrPublicKey: " + signatureCertificateOrPublicKey);
			
			String machineCode = "_R1-AT1_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-1_2016-12-10T16:55:29_0,00_0,00_0,00_0,00_0,00_4r1iIdZGeAQ=_a1234567_cg8hNU5ihto=";
			System.out.println("machineCode: " + machineCode);
			
			String machineCodeB64 = Base64.getUrlEncoder().encodeToString(machineCode.getBytes());
			System.out.println("machineCode Base64: " + machineCodeB64);
			
			String header = "eyJhbGciOiJFUzI1NiJ9";
			String toSign = header + "." + machineCodeB64;
			System.out.println("toSign: " + toSign);
	
			MessageDigest digest = MessageDigest.getInstance("SHA-256");
			byte[] exampleSha256Hash = digest.digest(toSign.getBytes("UTF-8"));
			System.out.println("sha256Hash:" + bytesToHex(exampleSha256Hash));
			String exampleCardPIN = "123456";

			byte[] exampleSignature = cashRegisterSmartCard.doSignatur(exampleSha256Hash, exampleCardPIN);
			String signed = Base64.getEncoder().encodeToString(exampleSignature);
			System.out.println("Signiert: " + signed );
			
			String qr_str = machineCode + "_" + signed;

			System.out.println("qr string: " + qr_str );
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static String bytesToHex(byte[] bytes) {
        StringBuffer result = new StringBuffer();
        for (byte byt : bytes) result.append(Integer.toString((byt & 0xff) + 0x100, 16).substring(1));
        return result.toString();
    }


	private static List<Card> getAttachedCards() {
		TerminalFactory terminalFactory;
		try {
			terminalFactory = TerminalFactory.getInstance("PC/SC", null);
		} catch (NoSuchAlgorithmException e) {
			terminalFactory = TerminalFactory.getDefault();
		}
		CardTerminals cardTerminals = terminalFactory.terminals();
		List<Card> cards = new ArrayList<>(5);
		try {
			for (CardTerminal terminal : cardTerminals.list(CardTerminals.State.CARD_INSERTION)) {
				try {
					Card card = terminal.connect("*");
					cards.add(card);
				} catch (CardException e) {
					e.printStackTrace();
				}
			}
		} catch (CardException e) {
			e.printStackTrace();
		}
		return cards;
	}
}
```

Die Datei ```cryptographicMaterialContainer.json``` sieht folgendermaßen aus
(wobei ich <signatureCertificateOrPublicKey_von_java_output> mit dem output von ```signatureCertificateOrPublicKey``` vom java code ersetzt habe:

```json
{
  "base64AESKey" : "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=",
  "certificateOrPublicKeyMap" : {
    "a1234567" : {
      "id" : "a1234567",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey": <signatureCertificateOrPublicKey_von_java_output>
    }
  }
}
```

rufe ich nun das testtool regkassen-verification-receipts-1.0.0.jar auf erhalte ich folgenden Output:
```
-----------------------------------------------------------------------------
DETAILED MACHINE-READABLE CODE VALIDATION: This process validates the machine readable codes within the given input file.
Machine readable code validation # 0: FAIL
DETAILS:
{
  "verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.",
  "verificationTimestamp" : "2016-12-10T19:38:06.581+01:00",
  "verificationResultList" : [ {
    "verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",
    "verificationTimestamp" : "2016-12-10T19:38:06.640+01:00",
    "verificationResultList" : [ {
      "verificationId" : "CRYPTO",
      "version" : 1,
      "verificationName" : "Kryptographische Prüfungen",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2016-12-10T19:38:06.653+01:00",
      "verificationResultList" : [ {
        "verificationId" : "CRYPTO_SIGNATURE",
        "version" : 1,
        "verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
        "verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.",
        "verificationTimestamp" : "2016-12-10T19:38:06.653+01:00"
      } ]
    } ]
  } ]
}
-----------------------------

-----------------------------------------------------------------------------
DETAILED MACHINE-READABLE CODE VALIDATION complete.
```

Wie aus dem Code herauszulesen ist, komme ich auf den zu signierenden Hash mit zusammenfügen des headers und des MaschienenlesbarenCodes (beide Base64URL codiert) also ```"eyJhbGciOiJFUzI1NiJ9.<base64encodedMachinenlesbarenCode>"``` und dann sha256 darauf angewandt. Das signierte ByteArray encode ich dann Base64 und hänge es an den maschienenlesbaren Code von vorhin mit einem unterstrich ```_``` an. 

Habe ich bei der Aufbereitung der Daten für die Signatur einen Fehler oder lese ich das Zertifikat für ```cryptographicMaterialContainer.json``` mit ```Base64.getEncoder().encodeToString(cert.getEncoded());``` falsch aus?

**Comment by ErichFreitag** [comment]
Schauen sie bitte mal folgendes durch, ob es ihnen weiterhilft:

https://github.com/a-sit-plus/at-registrierkassen-mustercode/raw/master/Dokumente/2016-11-18%20SIG-Check.pdf sowie https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/133, https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/147, https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/39 usw., sonst nach "Gültigkeit" suchen und auf Issues filtern.

**Comment by herbertmanfred** [comment]
danke für die schnelle Antwort! Habe mir nochmals alle Beiträge durgelesen und finde keinen Fehler beim aufbereiten der Daten. Desshalb kann der Fehler nur bei einem nicht passenden Zertifikat base64 String sein, den ich ```cryptographicMaterialContainer.json``` übergebe. Auf diesen String komme ich mit
```java
Base64.getEncoder().encodeToString(cert.getEncoded());
```
bzw. habe ich auch beim a-trust client windows programm das zertifikat base64 exportiert (enstpricht der selben zeichenkette wie beim java code export wenn man 
```-----BEGIN CERTIFICATE-----``` und ```-----END CERTIFICATE-----```, sowie die Zeilenumbrüche nach 64 Zeichen wegnimmt)

Ist diese Vorgehensweise falsch bzw wie liest man den zu übergebenen BASE64 String, den man in ```cryptographicMaterialContainer.json```einfügen muss aus?

**Comment by ErichFreitag** [comment]
Bezüglich A-Trust-Interface kann ich ihnen im Detail nicht weiterhelfen. Was mir auffällt, ist dass die Zertifikats-Seriennummer ungewöhnlich aussieht ("id" : "a1234567"). Können sie die vollständige cryptographicMaterialContainer.json posten?

**Comment by herbertmanfred** [comment]
die Seriennummer ist ein ein Hex Wert mit der selben Länge (8 Zeichen), ich habe es nur hier bei ```qr-code-rep.json``` und beim ```cryptographicMaterialContainer.json``` ersetzt (den test habe ich mit den echten Werten durchgeführt) und das Base64 Zertifikat ist 1792 Zeichen lang. Da es sich um die Daten auf der A-Trust Signaturkarte handelt will ich sie hier nicht posten (vor allem weil ich mir nicht sicher bin um welches Zertifikate es sich handelt, da ich ja anscheinend ein falsches auslese).

**Comment by ErichFreitag** [comment]
OK, dann hätte ich noch https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/122, https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/133 und https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/105.

Sie können mir die cryptographicMaterialContainer.json auch per E-Mail an erich.freitag@pqrst.at senden und ich kann versuchen etwas herauszulesen.

**Comment by asitplus-pteufl** [comment]
Ich habe zwei Anmerkungen:
Verwenden Sie bei der BASE64-URL Kodierung der Payload Padding Zeichen (=)?  Diese sind laut JWS-Standard nicht erlaubt.

Was ist denn in dieser Methode enthalten?
cashRegisterSmartCard.doSignatur(exampleSha256Hash, exampleCardPIN);

**Comment by herbertmanfred** [comment]
@asitplus-pteufl Danke für den Hinweis der Padding Zeichen im BASE64-URL kodierten Payload. Genau hier lag der Fehler!
Wenn ich im Code die Zeile die den Maschienenlesbaren Code BASE64-URL kodiert mit
```java
String machineCodeB64 = Base64.getUrlEncoder().encodeToString(machineCode.getBytes()).replaceAll("=*$", "");
```
ersetze, funktioniert es!

Danke für die schnelle und kompetente Hilfe!

**Comment by herbertmanfred** [comment]
Die Methode ```cashRegisterSmartCard.doSignatur(exampleSha256Hash, exampleCardPIN);```
ist übrigens aus dem a-trust Musterkode der Chipkarten: http://labs.a-trust.at/developer/ShowSource.aspx?id=114

**Comment by Alex1130** [comment]
Bitte um eine Bestätigung meiner Annahme:
wenn ich den Signaturwert mit dem asign Client als gültig verifizieren kann in diesem Modul aber `Die kryptographische Gültigkeit der Signatur ist nicht gegeben` angezeigt wird kann der Fehler auch darin begründet sein, dass der Fehler auch im cryptographicMaterialContainer.json liegen kann?

**Comment by asitplus-pteufl** [comment]
@Alex1130  Bitte unbedingt das Sig. FAQ lesen, dort wird (bis auf das Padding-Thema von oben) auf alle Aspekte eingegangen die falsch sein können. Das Padding Thema wird in Kürze hinzugefügt.

https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-11-18%20SIG-Check.pdf (ist auch vom README auf der Startseite verlinkt).

ZDA-Spezifische Fragen können wir leider nicht beantworten. Dazu bitte die ZDAs direkt kontaktieren.

**Comment by herbertmanfred** [comment]
@Alex1130 in ```cryptographicMaterialContainer.json``` muss das richtige Zertifikat beim Feld ```signatureCertificateOrPublicKey``` eingegeben werden (wenn sie es mit der A-Trust Karte signieren eben das Zertifikat von der Karte), sonst kann das Testtool die Signatur nicht prüfen.

**Comment by Alex1130** [comment]
@herbertmanfred 
Danke für die Antwort - ich habe das Zertifikat so ausgelesen wie Sie das beschreiben a-trust Client: BASE64 codiert und die Zeilenumbrüche entfernt,  Die hexSerial-ID und das Zertifikat nahm ich von dem mit 6 stelligem PIN geschützten Zertifikat. Ist das so richtig?

**Comment by Alex1130** [comment]
@asitplus-pteufl Ja, dieses Dokument hatte ich bereits konsultiert.
Ich habe mit den Testergebnissen des Democodes experimentiert (CashBoxDemoOutput) und dabei ist mir aufgefallen, dass die gleiche Fehlermeldung auftritt wenn ein falsches Signaturzertifikat im cryptographicMaterialContainer.json abgelegt wird.

**Comment by asitplus-pteufl** [comment]
Wenn sie das Zert BASE64-Kodiert auslesen, kann da nicht viel falsch sein (natürlich muss es da richtige sein). Leider ist eine genaue Aussage im Prüftool nicht möglich, nur dass die Signatur nicht gültig ist. Am besten ist es wohl wenn sie wirklich Schritt für Schritt alles durchgehen (anhand des Doks). Ich habe dieses soeben aktualisiert um die Padding-Infos (letzte Folie).

https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf

**Comment by herbertmanfred** [comment]
@Alex1130 ja so sollte es richtig sein (ich habe beim atrust Client gleich BASE64 exportiert also nicht erst nachher umgewandelt)

**Comment by Martin78** [comment]
Ich kämpfe mit dem ähnlichen oder gleichen Problem herum! Hab die Daten unter  #323 geposted
Das löschen der "=" mittels replaceAll("=*$", "") hat bei mir keinen Erfolg gebracht.
Wäre für jede Idee dankbar!
