### ISSUE TITLE
Format des QR-Codes

### ISSUE THREAD

**Issue by maxp1256** [a-sit-plus/at-registrierkassen-mustercode#193]
Hallo,

gibt es eine nähere Spezifikation, wie der QR-Code aufzubereiten ist?
Unsere Barcode-Bibliothek bietet folgende Optionen:

Encoding:
- Numeric
- Alphanumeric
- Byte
- Kanji

Fehlerkorrektur:
- L
- M
- Q
- H

Vielen Dank!

**Comment by ErichFreitag** [comment]
RKSV § 3 20. QR-Code: zweidimensionales Symbol nach Standard JIS X 0510/2004

**Comment by asitplus-pteufl** [comment]
Kodierung der zeichen entweder ASCII (nur wenn auch garantiert ist dass Beleg/Kassen-ID etc. nur ASCII Zeichen enthält) oder UTF-8. Welche Details bei Ihren Kategorien dahinter stehen weiß ich leider nicht, ich vermute aber dass Alphanumeric entweder ASCII oder UTF-8 ist. Bitte in der Lib prüfen.
