### ISSUE TITLE
Die kryptographische Gültigkeit der Signatur ist nicht gegeben (2)

### ISSUE THREAD

**Issue by Alex1130** [a-sit-plus/at-registrierkassen-mustercode#194]
@asitplus-pteufl  Ich bin nochmal alle Issues und Dokumente durchgegangen:
Meine Vermutung ist, dass  der Fehler beim SHA256 liegt. Mit der Bitte um Durchsicht und Hilfe hänge ich ein Beispiel an welches die Eingangs Daten, Zwischenwerte und Ausgangswerte eines Startbeleges enthält . 
[BeispielAblauf.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/649069/BeispielAblauf.txt)

**Comment by ErichFreitag** [comment]
Vielleicht hilft da noch https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/157, auch in Bezug auf ihren Beitrag in https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/190

**Comment by Alex1130** [comment]
@ErichFreitag leider ist es das nicht. Die Fehlermeldung ist im Fall #157 :
`Die Prüfung des Belegs konnte nicht vollständig durchgeführt werden. Vermutlich konnte das Zertifikat oder der Schlüssel mit der im Beleg angegeben Seriennummer bzw. dem angegebenen Ordnungsbegriff des Unternehmens und der Schlüssel-ID nicht in der cryptographicMaterialContainer.json Datei gefunden werden....`

**Comment by ErichFreitag** [comment]
War nur eine Idee, weil sie geschrieben hatten "Ich habe mit den Testergebnissen des Democodes experimentiert (CashBoxDemoOutput) und dabei ist mir aufgefallen, dass die gleiche Fehlermeldung auftritt wenn ein falsches Signaturzertifikat im cryptographicMaterialContainer.json abgelegt wird" und ihrem Beispielablauf die Seriennummer mit Großbuchstaben enthalten ist.

**Comment by asitplus-pteufl** [comment]
Bei der Hash-Berechnung bekomme ich auch das gleiche Ergebnis.
Signatur kann ich natürlich nicht nachstellen, aber sehe da in erster Linie keinen Fehler.

Ich hab jetzt ihr Zert dekodiert (siehe unten). Das ist sicher das falsche: Aus 2 Gründen:
-Dieses Zertifikat hat einen RSA-Schlüssel, dieser ist nicht für die RKSV geeignet. Es gibt Karten die haben zwei Zertifikate, bitte überprüfen ob da noch ein anderes ist, oder ob Ihnen ein falsches Zertifikat ausgestellt wurde. Die Signatur in Ihrem Beleg schaut aber auf den schnellen Blick aus als ob sie von einem ECC Schlüssel erstellt wurde. Das würde dann wieder darauf hindeuten, dass im CryptoContainer einfach das falsche Zert liegt.
-Es hat eine andere Seriennummer als in Ihrem Beleg angegeben.

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 700594325 (0x29c23895)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU=A-Trust Registrierkasse.ENC, CN=A-Trust Registrierkasse.ENC
        Validity
            Not Before: Jun 21 08:08:40 2016 GMT
            Not After : Jun 21 06:08:40 2021 GMT
        Subject: C=AT, CN=UID ATU57227138/serialNumber=341431436102
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (1536 bit)
                Modulus (1536 bit):
                    00:d7:7f:3c:b6:4d:f4:21:32:fa:69:c2:0e:4d:31:
                    cf:8a:c4:77:66:fd:86:ab:c4:bb:6c:64:2a:83:18:
                    c0:06:22:fa:aa:b4:b4:bb:67:1c:c8:09:ef:27:ed:
                    d3:27:58:7a:29:94:fe:20:b7:90:f8:b4:1d:e8:be:
                    4c:73:38:fa:5f:b4:cd:86:b2:8a:eb:44:03:de:25:
                    de:4b:25:00:6d:89:f7:51:f1:31:f8:1f:4c:f9:7c:
                    bc:37:0c:3f:bd:27:be:7a:33:6b:12:ab:84:1b:75:
                    71:2e:14:ae:db:66:db:4c:4d:41:5e:30:44:8e:50:
                    d3:18:c6:93:76:58:05:ab:2a:03:c7:5d:40:e4:19:
                    fe:2e:47:83:77:c5:b2:fa:48:a1:9e:85:c4:72:f4:
                    53:64:83:db:63:ae:80:77:29:ef:5d:30:78:74:4a:
                    03:03:dc:5e:58:f0:db:27:21:ff:82:2c:e6:5e:93:
                    9b:f8:69:01:ab:c7:1a:35:89:00:cd:8e:5f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Data Encipherment
            X509v3 Subject Key Identifier: 
                4A:14:03:EF:C9:43:BB:6C
            Authority Information Access: 
                <EMPTY>

            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Alternative Name: 
                email:rauchkultur@gmx.at
            X509v3 Authority Key Identifier: 
                keyid:41:F6:64:F2:23:B4:6E:20

    Signature Algorithm: sha256WithRSAEncryption
        70:fe:f7:4e:fc:1a:8a:f1:9c:e1:9c:75:86:9c:1f:d1:40:21:
        24:11:5b:76:7a:6a:80:f8:70:1f:ba:aa:ff:18:1f:85:99:45:
        5d:96:d1:21:46:1f:a6:82:31:cf:cc:48:4f:04:16:bf:3a:ff:
        8d:42:5d:5c:e4:41:fb:39:7c:4e:80:9e:f4:97:d5:af:a1:da:
        4d:cf:4f:36:f3:4f:bb:58:2c:da:ad:96:c5:3c:a1:a2:54:5c:
        7f:a6:4b:03:6e:d2:6c:6d:de:82:e0:ea:70:21:c7:6e:af:24:
        90:14:5a:a4:a5:e7:53:ae:e3:c8:4d:3b:30:57:1a:f0:8b:73:
        ae:8e:46:ee:a9:4e:f6:5b:b3:6a:f2:5c:b9:ec:0d:be:83:7b:
        45:e1:35:a7:db:f9:0b:9a:57:9b:ae:44:3d:6e:66:37:5a:09:
        62:7d:48:69:fc:1e:8d:0f:ae:2c:8c:41:7c:70:6c:60:1d:71:
        11:7e:10:c6:4d:0f:dd:cc:af:1d:e3:5c:75:81:af:89:3a:5c:
        80:2c:d8:3d:33:f6:bd:2a:9e:96:b1:af:35:b1:f2:52:81:5e:
        84:5d:98:56:50:cb:2e:11:90:eb:75:37:14:26:72:ce:74:87:
        61:97:92:3b:9b:9d:4b:27:0f:e8:2f:93:e3:d4:bb:84:6f:95:
        35:f2:9f:e9

**Comment by asitplus-pteufl** [comment]
wunderbar! ich schreib es immer als wichtigen Hinweis dazu: Bitte auch detaillierte Testfälle erstellen im RKSV-DEP ablegen und mit dem Prüftool überprüfen. Wichtig ist vor allem die korrekte Kodierung, Abbildung des Umsatzzählers, da beim Einzelbeleg nicht ersichtlich.
