### ISSUE TITLE
WKO Forum | Sammelbeleg | DEP Export/Backup | Null-Beleg 

### ISSUE THREAD

**Issue by Georg632** [a-sit-plus/at-registrierkassen-mustercode#195]
Ich habe mir zu den Begriffen oben nun alle Issues angesehen und blick noch weniger durch als vorher.

1) WKO-Forum:
Der Link den asitplus-pteufl immer postet wenn es zu nicht technischen Fragen kommt (https://www.bmf.gv.at/top-themen/Registrierkassen.html) führt mich zu einem 404 Fehler. Ebenfalls habe ich keine Ahnung wie mein WKO Account genügen Rechte bekommt um in der Community mitlesen zu können.

2) Sammelbeleg:
Wenn die Signatureinheit ausgefallen ist und es wurde weiter Kassiert und sie geht wieder online - muss ja ein Sammelbeleg erstellt werden.
Beispiel: ich habe Bon Nummer 5 bis 10 ohne Signatur erstellt. So wie ich das nun verstanden habe muss nun der Sammelbeleg irgendwie diese 5 Bons definieren (damit es nachvollziehbar ist das dieses ohne Signatur erstellt worden sind). Was ich noch nicht verstehe - wo soll das hingeschrieben werden das diese 5 Bons nicht signiert worden sind? Im JWS ist das nicht ersichtlich oder?

3) DEP Export:
Was ist der unterschied zwischen dem DEP Export (= alle JWS in chronologischer Reihenfolge) und dem vierteljährlichen zu erstellenden Backups? Gibt es für die Backups ein vordefiniertes Format?

4) Null-Beleg:
Ich verstehe auch den Sinn eines monatlichen/jährlichen Null Belegs nicht.
Es steht ja nichts drinnen außer der aktuelle Umsatzzähler? 

Hat zwar alles keinen Bezug auf den Mustercode/Prüftool - aber vielleicht kann mir trotzdem jemand helfen :-)

**Comment by asitplus-pteufl** [comment]
Zu 1 kann ich gleich eine Korrektur anbieten, das hat sich leider geändert:
https://www.bmf.gv.at/top-themen/Informationen_zu_Registrierkassen.html

**Comment by Georg632** [comment]
Aber wie ich die Rechte für WKO-Communities bekomme weißt du auch nicht?

**Comment by ErichFreitag** [comment]
Zu 2) dorthin, wo sie den Sammelbeleg einsehen können, also z.B. in einem Journal. Inhalt gemäß Erlass, d.h. Beginn und Ende des Ausfalls muss erkennbar sein

Zu 3) Export erfolgt über einen Zeitraum und wird einem Organ der Abgabenbehörde übergeben. Sicherung erfolgt immer vollständig, hat zwangsläufig das selbe Format wie der RKSV-Export und ist mit einem Monatsbeleg abzuschließen

Zu 4) Sinn des Monatsbelegs z.B. zum Abschluss der DEP-Sicherung. Sinn des Jahresbelegs z.B. die Prüfung bei Finanz Online.

Lesen sie bitte den Erlass, der gibt auf solche Fragen gut Anwort.

Die Rechte für die WKO-Community gibt es unter https://communities.wko.at/default.aspx über Frau Mag. Elisabeth Klinger gemacht werden. https://www.wko.at/Content.Node/Mitarbeiterkontaktseite.html?rollenid=2753134

**Comment by Georg632** [comment]
2) Wir haben bereits einen Export der alle ausgestellten Bons (also jeden ausgedruckten Bon) untereinander anzeigt. Hier wird dann wohl zwangsläufig "Sicherheitseinrichtung ausgefallen" dabei stehen bei den Bons. Würde das schon reichen?

3) Okay also der einzige Unterschied besteht darin das der Export über einen Zeitraum geht und das Backup immer vollständig sein muss.

Vielen Dank für die schnelle Antwort @ErichFreitag

**Comment by ErichFreitag** [comment]
Zu 3) es gibt schon noch ein paar formale Unterschiede - beispielsweise muss die (jeweils letzte Komplett-)Sicherung für 7 Jahre aufbewahrt werden etc.

Zu 2) Nein, das stellt ja keinen Sammelbeleg gemäß RKSV dar.

**Comment by Georg632** [comment]
3) aber das Format (also JWS chronologisch) ist gleich?

2) Sorry das habe ich falsch geschrieben.
Es müsste dann unter den Bons bei denen dabei steh ".. ausgefallen" ein eigener Bon vorkommen in dem z.B. der Zeitraum bzw. die Bonnummern der Bons steht welche eine ausgefallene Signatureinheit hatten?

**Comment by ErichFreitag** [comment]
3) Format bei Sicherung wie beim Export, sonst macht eine zumindest quartalsweise Sicherung wenig Sinn. Varianten z.B. nach Erlass 3.2.1.4 "Sollten die Daten des DEP zur Sicherung verschlüsselt werden, müssen die Daten inhaltsgetreu wiederhergestellt werden können".

2) ja, eben der Sammelbeleg - ein "normaler" Nullbeleg mit den Zusatzinformationen Beginn und Ende des Ausfalls. Ob ein Ausdruck aller Bons hilfreich ist weiß ich nicht - ich würde eher nach gewissen Kriterien suchen wollen oder die Sonderbelege extra verfügbar machen.

**Comment by Georg632** [comment]
zu 3: ich dachte immer beim Export muss mehr ausgegeben werden - (Menge, Artikel usw.) damit es Nachvollziehbarer ist.

zu 2: okay, ich glaube ich habs verstanden :-)
(Ausdrucken muss ich ja nur den Jahresbeleg - wenn ich das richtig verstanden habe)

nochmals vielen Dank @ErichFreitag - hast mir sehr geholfen.

**Comment by Flanelli** [comment]
@Georg632 
Nachdem ja ohnehin das auch bsherige detailierte Belegsprotokoll trotz der RKSV weitergeführt werden
muss und auch sinnvollerweise alle,wie immer gearteten Belegsvorgänge und Inhalte aufweisen sollte
ist die klare Aussage eines Sammelbeleges relaltiv einfach zu erwirken.
Beispiel; Ist bei uns  zwar JSON aber die Inhalte kann man ja in jedem individuellen Format abbilden,
{
    "Belege-Detail": [ 
    {
	"Belegnummer": "100664",
	"Kassen-ID": "DDP1",
	"Bezug-POS": "113372",
	"Beleg-Datum-Uhrzeit": "2016-11-26T13:11:19",
	"Beleg-Summe": 0.00,
	"Beleg-Inhalte": [
	{
           "Artikel": "SAMMELBELEG 100659 - 100663 ( 734,28 )  2016-11-26 13:08 -  2016-11-26 13:10",
           "Menge": 1.00,
           "Preis": 0.00
	}
      ]
    }
  ]
}

**Comment by Georg632** [comment]
@Flanelli 
Ja genauso hätte ich das jetzt auch gemacht. Nur bei uns ist es mit dem Artikel ein bisschen ein Problem. (Datenbank bezogen) - aber das ist ein anderes Thema, wird irgendwie möglich sein. :-)

Danke für deine Antwort.

**Comment by ErichFreitag** [comment]
Ganz fertig sind wir noch nicht, @Georg632 :-)

Es gibt zwei Exporte des Datenerfassungsprotokolls - jenen nach § 7 und jenen nach § 19. Der § 19-Export ist jener des "Kassenjournals", den es auch jetzt schon gibt (zumindest seit 01.01.2016) und der wesentlich mehr Details enthält als der RKSV-Export (praktisch "alles"). Das ist wohl das, was @Flanelli meint - das heißt aber noch nicht, dass dort automatisch "Sammelbeleg" steht (das muss also zusätzlich hinein).

Gemäß Erlass müssen der Startbeleg, der Jahresbeleg und der Schlussbeleg ausgedruckt (und aufbewahrt) werden (können). Die anderen müssen natürlich auch aufbewahrt werden (aber nicht explizit ausgedruckt).

**Comment by AxelKutschera** [comment]
Bitte nicht vergessen: 
zu 3: Es gibt neben der Exportverpflichtung nach (a) RKSV; auch die nach (b) §§ 131 und 132 BAO 
zu 2: Belege können auch revisionssicher elektronisch gespeichert werden.

**Comment by Flanelli** [comment]
@ErichFreitag 
Völlige Zustimmung dass im Prinzip ja nichts das automatisch irgendwo steht, letztendlich soll und wird alles wohl sehr bewußt in Protokolle geschrieben und insbesondere im Detailprotokoll nach  § 19. Da diese Aufzeichnung ja bereits in der Verordnung von 2012 "empfohlen" wurden waren und sind sie auch immer sehr beliebte Nachschlagwerke eines peniblen Prüfers. Daher ist es nur höchst empfehlenswert diese Protokoll aich noch spitzfindiger zu gestalten und alle nur erdenklichen Querverweise auf Vorgänge auch auf nicht RKSV.relevante Daten abzubilden.

**Comment by Georg632** [comment]
@ErichFreitag 
Ja, den Kassenjournal Export sollte es schon geben. Das habe ich gemeint mit dem Export wo alle Bons in ein File geworfen werden. Wie ich dieses besonderen Belege (mit dem echt tollen namen Null Belege) jetzt hinzufüge weiß ich jetzt (hoffe ich).

zu 2) Okay das mit dem Ausdruck werde ich notieren - danke :-)

@AxelKutschera 
zu 3) 131 und 132 sind aber keinen neuen Gesetze oder? Die Kasse gibt es schon eine Zeit - das sollte bereits implementiert sein. Aber danke für den Hinweis - werde ich prüfen.

**Comment by AxelKutschera** [comment]
@Georg632  zu 3) Ja, das ist alt. Jedoch - insbesondere wegen § 131 Abs 1 Z 6b BAO - umfangreicher als der Export nach § 7 RKSV. 
Daher **soll** es diese Funktion bereits vor 2016 geben. 
Seit 2016 **muss** es diese Funktion geben. 
(Ich versuche eine Frage immer vollständig zu beantworten, sonst muss man sich - besonders, wenn man nur diesen Ausschnitt liest - immer Bruchstücke zusammensuchen.)

**Comment by Georg632** [comment]
Heute sind noch 2 Fragen aufgetaucht:

1)
Wenn ich einen Wertgutschein verkaufe ist dieser ja nicht RKSV pflichtig (erst wenn dieser eingelöst wird).
Ich möchte ihn aber trotzdem signieren - wie gehe ich dann vor? Schreibe ich den Wert dann in die Null% Stelle? Dann erhöht sich der Umsatzzähler. Muss ich diesen dann, wenn ein Gutschein eingelöst wird im Null% bereich wieder Minus rechnen um den Umsatzzähler nicht zu verfälschen?

Beispiel wie ich das meine:
Kunde kauft 5€ Gutschein:
Signatur: 5€ Null% 
Umsatzzähler: 5€
--------------------------------
Kunde kauft Artikel: 15€
Kunde bezahlt 10€ Bar | 5€ Gutschein
Signatur: 15€ 20% Umsatz | -5€ Null%
Umsatzzähler: 15€


2)
Wenn ich so eine Rückgabe habe mit -15€ und einen den gleichen Artikel wieder hergebe mit +15€
dann würde bei der 20%igen Steuerstelle 0€ drinnenstehen. (bei allen anderen auch)
Wie unterscheide ich diesen signierten Bon mit einem Null Beleg?

**Comment by ErichFreitag** [comment]
Wenn sie einen Wertgutschein beim Verkauf signieren möchten, kommt der Betrag in den 0%-Steuersatz. Beim Einlösen kommen die jeweiligen Steuersätze der Artikel zum Tragen. Es erfolgt kein Abzug, es werden 15 € Umsatz gebucht -> Umsatzzähler auf 20 €.

Der Umsatzzähler erhöht sich damit, ja. Sie müssen sich lediglich von dem Gedanken verabschieden, dass der Umsatzzähler den Umsatz zählt (der Begriff "Summenspeicher" drückt das besser aus).

2. Den unterscheiden sie aus RKSV-(DEP-)Sicht gar nicht, aus Kassensicht haben sie ja beide Artikel enthalten. Sie müssen den auch nicht von einem Null-Beleg unterscheiden - einen Null-Beleg können sie im Grunde ja jederzeit produzieren und im Kassenjournal können sie nachvollziehen, was da war. Wenn sie den Beleg drucken ist ohnedies klar, dass es kein "normaler" Nullbeleg ist - im Datenerfassungsprotokoll ist es nicht ersichtlich, aber auch egal.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
