### ISSUE TITLE
Ablauf der unterschiedlichen Schnittstellen

### ISSUE THREAD

**Issue by envomer** [a-sit-plus/at-registrierkassen-mustercode#197]
Hallo Leute,

ich hätte da ein paar Fragen bzgl. Registrierkassen und der Signierung von Rechnungen. Also ich bin bei einer Firma tätig die eine Online Registrierkasse Webseite anbietet. Sie ist PHP-basierend und ähnelt HelloCash und andere online Registrierkassen.

Da ab 2017 die Signatur Pflicht ist, und es noch in unser System integriert werden muss, möchte ich gerne den genauen Ablauf/Kommunikation zwischen den unterschiedlichen Schnittstellen wissen: RegKassa, FinanzOnline und A-Trust. Also wer schickt/empfängt welche Informationen an wem/von wem?

Was ist die genaue Funktion bzw. Aufgabe von den unterschiedlichen Belegarten wie der Nullbeleg, Startbeleg, Schlußbeleg.

Danke im voraus.

**Comment by AxelKutschera** [comment]
Vielleicht ist das ein guter Einstieg:
https://bmf-webtv.ots.at/aktuell/informationsvideo-in-5-schritten-zur-legalen-registrierkasse 

Ein Folder des BMF: https://www.bmf.gv.at/services/publikationen/BMF-BR-US_Sicherheitseinrichtung_RegK_112016.pdf?5o2lsh

Oder: https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Sicherheitseinrichtung_in_Registrierkassen.html#heading_Folder__Informationen_zur_Sicherheitseinrichtung_in_Registrierkassen

Zusammenstellung der Rechtsgrundlagen zB auf https://www.fiskaltrust.at/rechtsgrundlagen/ 

Sonst ist es leichter, zum Einstieg zu telefonieren... ;-)

**Comment by ErichFreitag** [comment]
@envomer - unten finden sie ein Datenmodell zur RKSV. Wenn sie beim grünen Block beginnen sehen sie, wie die Verarbeitung abläuft.

Hinzu kommen grob
- die Funktionalität der Verarbeitung
- die Führung, der Export und die Sicherung des Datenerfassungsprotokolls
- die Ansteuerung der Signaturerstellungseinheiten (Online -> 1 Zertifikat pro Unternehmen)
- die (wenn auch optionale) Schnittstelle zu Finanz Online
- die Erzeugung und Darstellung der maschinenlesbaren Codes
- die erwähnten Sonderbelege (Nullbelege)
- das Ausfallsmanagement
- die Logik und das Handling von Sonderfällen (Kauf auf Rechnung, Rechnungszahlungen, Wertgutscheine, ...)

Ihr Posting klingt, als würden sie jetzt beginnen, sich mit der Thematik zu beschäftigen - ich kann ihnen nur dringendst empfehlen, mit einem Anbieter einer fiskalen Middleware zusammenzuarbeiten. Letzten Endes müssen ihre Kunden am 01.04.2017 alles fertig und betriebsbereit haben.

![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/21172364/c3842df0-c1d1-11e6-896b-614f664da3b7.jpg)

**Comment by envomer** [comment]
@AxelKutschera Danke für die schnelle Antwort und die Ressourcen.

@ErichFreitag Danke für das umfangreiche Diagram. Ist sehr hilfreich.

Nun ich habe das jetzt so verstanden. 

Der Kunde kauft eine Sicherheitseinrichtung und teilt die FinanzOnline mit.
Dann registriert er ebenfalls die Registrierkasse bei denen.

Wenn das alles erledigt ist, teilt er uns die Zertifikatsseriennummer seiner Signierungseinheit mit.
Nun erstellt er einen signierten Startbeleg. Im Hintergrund werden die Daten wie auf dem Diagram verarbeitet. Es entsteht ein Code
```
_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-82_2016-03-11T04:24:46_0,00_0,00_0,00_0,00_0,00_NLoiSHL3bsM=_eee257579b03302f_cg8hNU5ihto=
```
der an die API von A-Trust verschickt werden muss um die Rechnung zu signieren. Aber um die API benutzen zu können, bräuchte man ein a.sign RK Online Konto (http://labs.a-trust.at/developer/pdf/RegistrierkasseMobileDev.pdf). 
Nachdem eine Antwort von A-Trust zurück kommt sendet man den signierten Beleg code an FinanzOnline mittels deren Webservice (https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/BMF_UID_Abfrage_Webservice_V5.pdf?5b0u43).

Stimmt das soweit?

**Comment by ErichFreitag** [comment]
Ich würde sagen, das stimmt mal soweit, was aber nur das Setup betrifft:

a) Sicherheitseinrichtung/Zertifikat besorgen, Hardware besorgen oder als Signierungsdienst in Anspruch nehmen und bei FinanzOnline registrieren ("das Unternehmen x verwendet 1...n Zertifikate").

b) Kasse mit ID und AES-Schlüssel registrieren. Startbeleg erstellen (obiger Code beispielhaft OK), signieren, Datenerfassungsprotokoll starten. Startbeleg prüfen (via Webservice oder via PrüfApp). Damit ist die Kasse betriebsbereit.

Also - wie sie signieren ist eine Architektur- und Preisfrage etc. Lokal mit Kartenleser/USB-Stick und Chip oder remote als Dienst bei A-Trust oder einem anderen Anbieter. Die Seriennummer des Zertifikats alleine wird nicht reichen, das muss wohl auch wo physisch vorhanden sein.

Ab dann geht aber der Betrieb los - mit all oben aufgeführten Themen "nebenbei". Und das waren erst 5% von dem, was ihnen eine fiskale Middleware abnimmt.

**Comment by envomer** [comment]
@ErichFreitag Danke. Sie waren eine große Hilfe 👍

**Comment by ErichFreitag** [comment]
Bitte gerne. Alle aktuellen Dokumente zu diesem Thema finden sie zusammengefasst unter http://www.pqrst.at/PDFs/PQRST_RKSV_Rechtliche_Anforderungen.pdf
