### ISSUE TITLE
Ausfall der Verbindung zw. Eingabestation und System für Signaturerstellung

### ISSUE THREAD

**Issue by wpichler** [a-sit-plus/at-registrierkassen-mustercode#198]
Hallo,

folgendes Scenario:

Eingabestationen die übers Netzwerk mit einem System zur Erstellung des Payloads und der Signatur verbunden ist. Die Eingabestationen haben eine Offline Funktionalität - d.h. bei Ausfall der Netzwerkverbindung arbeiten diese mit dem letzt Stand weiter - und synchronisieren dann wieder bei Verbindung.

Nachdem der Payload aber nicht auf der Eingabestation erstellt wird - kann kein gültiger Payload im Falle einer Störung der Verbindung erstellt werden.
Fällt die Signatureinheit aus - dann ist das kein Problem - das System für die Signatur kann die entsprechenden Payloads mit "Signatureinheit ausgefallen" erstellen.

Ist der erste Fall in irgendeiner Art und Weise zu handhaben ? Oder muß in so einem Fall die Eingabestation stillgelegt werden ?

Was ist wenn das System zur Erstellung der Payloads / Signaturen ausfällt - dann müssten alle Eingabestationen stillgelegt werden ?

**Comment by ErichFreitag** [comment]
Aus der letzten Sitzung des Arbeitskreises Kassensoftware der WKO:

Frage:
"Wenn eine Kassa offline war und wieder online geht, so ist ein Sammelbeleg vorgesehen. Dürfen auch die Rechnungen mit vollen Beträgen nachsigniert werden (also nicht mit einem Nullbetrag mittels Sammelbeleg) zwecks besserer Nachvollziehbarkeit im DEP? Wobei natürlich trotzdem die Kennzeichnung im DEP für Sicherheitseinrichtung ausgefallen erfolgt und auf den Offline-Rechnungen ebenfalls "Sicherheitseinrichtung ausgefallen" aufgedruckt wird".

Antwort:
Wenn während des Ausfalles Belege mit „Sicherheitseinrichtung ausgefallen“ an Stelle der Signatur im maschinenlesbaren Code ins DEP aufgenommen werden, ist nur der vorgeschriebene Sammelbeleg sinnvoll. Im andern Fall würde der Umsatzzähler doppelt angesprochen werden.
Wenn die Registrierkasse selbst ausgefallen ist, dann kann auch einzeln nacherfasst werden.
Wenn die Registrierkasse ausfällt und weiterhin über die Eingabestationen erfasst werden kann, so ist in der Registrierkasse eine Nacherfassung samt Signatur vorzunehmen.


Hilft das in ihrem Fall weiter?

**Comment by wpichler** [comment]
Leider noch nicht ganz - da ich ja in diesem Fall das Problem habe das die Eingabestation im "Offline" Modus zwar Bestellungen erfassen kann (und das soll auch so bleiben) - aber nicht den Payload mit "Sicherheitseinrichtung ausgefallen" erstellen kann - da der Payload für normal von der zentralen Signatur Box erledigt wird.

**Comment by wpichler** [comment]
Ergänzung:
Was mich hier etwas verwirrt - unter:
https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20009390&FassungVom=2017-04-01

Dieser Abschnitt:
Sollte dies nicht möglich sein, hat der Unternehmer bei der Aufbereitung und Verwendung des maschinenlesbaren Codes (§ 10) an Stelle des Signatur- bzw. Siegelwertes des betreffenden Barumsatzes (§ 10 Abs. 2 Z 8) die Zeichenkette „Sicherheitseinrichtung ausgefallen“ im Ergebnis der Signatur- bzw. Siegelerstellung laut Z 6 der Anlage zu verwenden

Deutet darauf hin das der Payload erstellt werden muss - nur an Stelle der Signatur kommt der Text.

Unter diesem Link:
https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/Technisch-rechtliche-Grundlagen-zur-Registrierkassenpflicht.pdf

Findet man:
4  RKSV  bei einem Ausfall der Signaturerstellungseinheit die Barumsätze  auf einer anderen
Registrierkasse (mit Anbindung zu einer Signaturerstellungseinheit) erfasst werden.
Sollte  die  Erfassung  an  einer  Kasse  ohne  Sicherheitseinrichtung  erfolgen  (Ausfall  der
Signatureinrichtung  aufgrund  z.B.  einer  defekten  Karte),  so  ist  am  Beleg  ein
entsprechender  Aufdruck  „Sicherheitseinrichtung  ausgefallen“  anzudrucken.  Bei
Wiederinbetriebnahme ist ein signierter Sammelbeleg zu erstellen.

Also kein Payload - nur der Aufdruck "Sicherheitseinrichtung ausgefallen"

**Comment by ErichFreitag** [comment]
Wenn "nur" die Signatur nicht erstellt werden kann, dann kommt
- auf den Beleg zusätzlich der Text "Sicherheitseinrichtung ausgefallen"
- anstelle des Signaturwertes der codierte Text "Sicherheitseinrichtung ausgefallen" im maschinenlesbaren Code und damit auch im Datenerfassungsprotokoll (somit inklusive Payload).

Ohne Zugriff auf den Umsatzzähler plus dem Datenerfassungsprotokoll (= Kasse) kann keine Payload erzeugt werden. In diesem Fall gilt das oben stehende, d.h. sie können über die Eingabestationen erfassen - das wirkt sinngemäß wie die Ausstellung händischer Belege. Sie haben nur dann keinen Umsatzzähler und keine Verkettung, daher auch keine Payload und damit keinen maschinenlesbaren Code.

Funktioniert alles wieder sind die während des Ausfalls erstellten Belege (in der Kasse) nachzuerfassen und mit einer Signatur zu versehen. Die Frage, die jetzt übrig bleibt ist, wie dann die "händisch-elektronisch" erstellten Belege gekennzeichnet werden sollen - eine Antwort gibt der Beitrag unter https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/186.

**Comment by AxelKutschera** [comment]
Wir definieren es so und schreiben folgende Hinweise auf einen Ausfall auf den Beleg:

* Ausfall der RegK = Ausfall des gesamten Kassensystems (zB Hardware oder E131-DEP kann nicht geschrieben werden) (§ 17 Abs 5 RKSV) 
     --> Kein elektronischer Beleg; Handschriftliche Belege + Nacherfassung
* Ausfall der Sicherheitseinrichtung (SE) = RKSV-DEP kann nicht geschrieben werden. (§ 17 Abs 5 RKSV) 
     --> Hinweis "Elektronisches Aufzeichnungssystem ausgefallen" + Automatisierte Nacherfassung
* Ausfall der Signaturerstellungseinheit (SEE) = Es kann nicht korrekt signiert werden. 
     --> Hinweis "Sicherheitseinrichtung ausgefallen" + Signierter Sammelbeleg (§ 17 Abs 4 RKSV) 

Wobei es verwirrend ist, da beim Ausfall der Signaturerstellungseinheit (SEE) der Ausdruck "Sicherheitseinrichtung ausgefallen" (SE) am Beleg steht.
Siehe auch #196

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
