### ISSUE TITLE
Kassenlösung mit Eingabeschnittstelle ?

### ISSUE THREAD

**Issue by hs562** [a-sit-plus/at-registrierkassen-mustercode#199]
Hallo u. guten Tag,
eine Frage an alle Anbieter von Kassenlösungen:
Bei einem Kunden gibt es bereits eine Warenwirtschaft/Fakturierung/Buchhaltung etc.. und eine bestehende Kassenlösung - allerdings OHNE den ab 4.2017 geforderten Sicherheitseinrichtungen.
Frage daher:
Gibt es eine (PC-)Kasenlösung, die über eine EINGABE-Schnittstelle Daten vom Warenwirtschaftssystem (IBM i Series) erhält und den signierten Kassenbon dann ausdruckt usw..?

Vielen, lieben Dank für Informationen im Voraus
HS

**Comment by AxelKutschera** [comment]
Wir sind zwar keine Kassenhersteller, haben jedoch Partner, welche derartige Systeme anbieten.
Einige davon stehen auf der öffentlichen Liste. https://www.fiskaltrust.at/partner 
Um eine individuelle Empfehlung auszusprechen stehe ich gerne außerhalb des Forums zur Verfügung.
Beste Grüße Axel Kutschera

**Comment by ckvsoft** [comment]
Mal einen Blick auf QRK werfen. Da gibt es eine Schnittstelle.  Ist opensource. 
www.ckvsoft.at

**Comment by hs562** [comment]
Besten Dank für alle Infos!!
(Bin bereits mit einem Hersteller in Kontakt - somit vorerst erledigt)
