### ISSUE TITLE
Frage zu Wiki Eintrag: Link statt QR Code OCR Kette "_" als Trennzeichen

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#20]
Das im WIKI Eintrag angeführte Beispiel macht deutlich, dass es im Text der Detailspezifikation (Seite 5, 13 - Prüfung des maschinenlesbaren Codes) eine ungeklärte Frage ergibt:

Das "_" kann nicht als Trennzeichen zwischen "Signierten Belegdaten" und "Signaturwert" verwendet werden, da sich innerhalb der "Signierten Belegdaten" bereits "_" als Trennzeichen zwischen den einzelnen Belegdaten befinden...

Beispiel:
_R1-AT0_DEMO-CASH-BOX703_496410_2015-12-17T11:22:26_61,33_15,42_38,26_0,00_42,81_udSL0zTzFaA=_b869153bc32a1c9_TZgOKfzheUs=_d7VoZ/nyr/8Mt2NVBZ0L4ivQwdlE3CmCFmz10bA5NXhGQ1QkunsDTqKvOSy//3nO8WT0+ypQqrDXMvyOGOXl9w==

Detailspezifikation:
13. Prüfung des maschinenlesbaren Codes
....
2. Extraktion der „Signierten Belegdaten“ und des „Signaturwerts“: Die „Signierten Belegdaten“ und der „Signaturwert“ werden aus der UTF8-kodierten Zeichenkette über das Trennzeichen „_“ extrahiert. Der BASE64-kodierte Signaturwert wird BASE64-dekodiert.

**Comment by lebail** [comment]
Der Signaturwert ist einfach als letztes Feld der durch Unterstriche getrennten Belegdaten anzusehen. Dann klappt es ...

**Comment by pteufl** [comment]
Der Antwort von lebail kann ich nichts hinzufügen. Die Elemente im maschinenlesbaren Code sind durch Unterstriche getrennt. In der Detailspezifikation wird nur textuell eine Gruppierung eingeführt: signierte Belegdaten und der Signaturwert. Die signierten Belegdaten sind alle Felder die vor dem Signaturwert kommen. Der Signaturwert ist der letzte Wert im signierten Beleg. Ist die Frage damit geklärt?

**Comment by shawtaylor** [comment]
Hallo,
wie komme ich an die Zertifikat-Seriennummer?

Ist das die Funktion   smartCard.readCertificate().GetSerialNumber()       (libCashRegisterSmartCard)

CardINI.Write("Card", "GetSerialNumber", smartCard.readCertificate().GetSerialNumber());

mfg

Shaw
