### ISSUE TITLE
Monats- und Jahresbelege

### ISSUE THREAD

**Issue by Alex1130** [a-sit-plus/at-registrierkassen-mustercode#200]
1. Durch einen Benutzerfehler wird ein manueller Monats/Jahresbeleg erstellt obwohl ohnedies ein automatisierter erstellt wurde (beziehungsweise ein zweiter manueller). Für das RKSV-DEP ist es einfach ein weiterer signierter Nullbeleg - ich nehme an da ist es egal - Hauptsache Nullbeleg als letzter der Vorperiode bzw. erster der neuen Periode . 

* Stimmt meine Annahme bzgl RKSV-DEP? 
* Ist es für das Kassenjournal belanglos wenn mehrere Monats/Jahresbelege gebucht werden ?
2. Es werden beim Finanzamt mehrere Kassen registriert. Davon kommt nur eine kleine Anzahl regelmäßig zum Einsatz, die anderen sind für saisonale Engpässe gedacht bzw. als Ersatz für Hardwareausfälle.

* Muss ein Monatsbeleg erstellt werden auch wenn eine Kasse in diesem Monat keine Umsätze generiert (genauer keine Einträge im RKSV DEP dazu gekommen sind) ?
* Muss ein Jahresbeleg erstellt werden auch wenn eine Kasse in diesem Jahr keine Umsätze generiert (genauer keine Einträge im RKSV DEP dazu gekommen sind) ?

**Comment by ErichFreitag** [comment]
Zu 1) korrekt, dem RKSV-DEP ist es soweit egal wieviele Monatsbelege enthalten sind, wohl ebenso für das Kassenjournal (woraus wahrscheinlich zusätzlich hervorgehen wird, dass der eine automatisch und der andere manuell erstellt wurde). 

Stellen sie beispielsweise nach einem Monatsbeleg noch weitere Belege (im Monat) aus, wird ein zusätzlicher Monatsbeleg eingeschoben (siehe Erlass 4.5.7). Auch daraus ist ersichtlich, dass immer der letzte Monatsbeleg relevant ist. Wichtig ist der Monatsbeleg auch insbesondere beim Abschluss der DEP-Sicherung.


Zu 2) Nein, siehe ebenso Erlass 4.5.7 "In Monaten, in denen keine Geschäftstätigkeit stattfindet bzw. in denen aus geschäftlichen Gründen kein oder ein eingeschränkter Bedarf an Registrierkassen besteht müssen für diese im jeweiligen Monat nicht verwendeten Kassen keine Monatsbelege erstellt werden" 

sowie 

"Der Registrierkassenpflichtige hat daher am Ende des Kalenderjahres bzw. am letzten Tag seiner getätigten Umsätze, grundsätzlich bis zum 31. Dezember, den Jahresbeleg herzustellen und nach Ausdruck aufzubewahren. [...] Bei sogenannten Saisonbetrieben (zB Schwimmbad) kann dieser Vorgang auch zu Saisonende, spätestens jedoch vor Beginn der unternehmerischen Tätigkeit im neuen Jahr
erfolgen" und "Eine Stilllegung der Registrierkasse während der Betriebsferien oder saisonbedingter
Betriebssperren bedingen keinen Ausfall und keine Außerbetriebnahme der Registrierkasse
und der Signatur- bzw. Siegelerstellungseinheit".

Das trifft zwar nicht wörtlich zu, zeigt jedoch worum es geht. Das BMF hat das in der letzten Arbeitskreissitzung mit "Satz 1 ist die Generalnorm, Satz 2 beschreibt einen Sonderfall (Wortfolge: … kann dieser Vorgang auch zu Saisonende …). D.h., dass bei Saisonbetrieben der Jahresbeleg spätestens beim Wiederaufsperren erstellt und geprüft werden muss. Der Jahresbeleg ist grundsätzlich zum kalendermäßigen Jahresende zu erstellen" beschrieben.

Sprich: im allgemeinen ja, in Sonderfällen entsprechend anders. Sie müssen sich halt überlegen, wie sie dann sicherstellen, dass der Jahresbeleg trotzdem (bei "Saisonende" oder "Saisonstart") generiert wird.

Ich denke, das können sie auch auf ihren Fall umlegen. Die formal ungeklärte Frage betrifft Ersatzkassen - da kann überlegt werden, ob diese auch schon vor einer tatsächlichen Inbetriebnahme registriert sein müssen (weil sie ja ohnedies eine defekte Kasse auch abmelden müssen). 

Wenn das in einem Betrieb mit mehreren Kassen erfolgt und nachvollziehbar ist, dass z.B. eine Kasse als Reserve dient, wird das wohl auch kein Problem sein. Eine Empfehlung (von mir) ist auch, dass auch Ersatzkassen ständig in Betrieb sind (womit mit einem Monatsbeleg auch gleich die Funktion überprüft werden kann). Es wäre nicht das erste Mal, dass eine (länger) ausgeschaltene Kasse bei einem Neustart nicht mehr funktioniert.

**Comment by AxelKutschera** [comment]
Ich sehe es so:
- In den Monaten einer Stilllegung einer RegK sind keine Monatsbelege zu erstellen 
       - Damit dokumentiert man, dass die RegK stillgelegt wurde.
- In den Monaten, in denen lediglich keine Umsätze erfasst wurden, sind Monatsbelege zu erstellen 
       - Damit dokumentiert man, dass es keine Umsätze gab.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
