### ISSUE TITLE
Interpretation der Prüftool Ergebnisse.

### ISSUE THREAD

**Issue by RobertSchellenberger** [a-sit-plus/at-registrierkassen-mustercode#201]
Habe mit dem Prüftool mein DEP getestet und es wurden einige resultfiles erstellt, zu welchen ich ein paar Fragen hätte.

1. Die Files welche mit 0000_ beginnen sollen hiermit den Startbeleg darstellen nehme ich an.
Im Cashbox_full file ist auch bei TYPE_OF_RECEIPT ... TYPE_OF_RECEIPT_START ein PASS zu finden.
Kann ich damit davon ausgehen dass auch die Android APP nach dem Scannen dieses Belegs eine Erfolgsmeldung abgeben wird?

2. Das File 0001_ entspricht in meinem Fall einem Standardbeleg.
Die Files "app", "cashbox" und auch "cashbox_full" vermelden PASS. (auch bei den CHAINING Tests)
Das File 0001_dep bringt jedoch FAIL im Bereich des DEP_CHAINING_VALUE.
Die Datei dep.json ohne nummer davor vermeldet jedoch PASS in oberster Ebene obwohl sie ebenso am Ende des Files bei DEP_CHAINING_VALUE FAIL.
Woran könnte das liegen?

Besten Dank
Schellenberger Robert

**Comment by asitplus-pteufl** [comment]
Können Sie die die Dateien bitte posten?

**Comment by RobertSchellenberger** [comment]
[verification.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/668197/verification.zip)

Mach ich doch gerne.
Besten Dank schon mal für ihre Bemühungen.

**Comment by asitplus-pteufl** [comment]
Möchte mich für die späte Antwort entschuldigen, leider ist das etwas untergegangen:
zu 1: Generell ja, wenn das Prüftool sagt der Beleg passt, dann ist formal alles korrekt. Es kann dennoch zu Fehlern in FinOnline kommen wenn z.B. Sig-Einrichtung und/oder Kasse nicht richtig registriert sind (das kann das Prüftool nicht überprüfen).

zu 2. bei DEP.JSON sind einfach alle Ergebnisse in einer Liste (es gibt also keine oberste Ebene). Sie werden dort auch ein FAIL beim zweiten Beleg finden. In dem Fall stimmt einfach die Verkettung nicht (Hash-Wert Berechnung).

**Comment by RobertSchellenberger** [comment]
Danke für die Mühen.
Haben nun im DEP.JSON File keine Probleme mehr.
Jedoch ist uns im cashbox_full file des Startbelegs aufgefallen dass bei "verificationId" : "RECEIPT_FULL" der  "verificationState" : "FAIL" und bei "verificationId" : "STATE_CONSOLIDATED" ebenso der  "verificationState" : "FAIL" ist. Ist das normal im Startbeleg?

**Comment by asitplus-pteufl** [comment]
Ja, das ist ein Known Issue im Prüftool, wenn Sie aber genau reinschauen dann sehen Sie auf der obersten Ebene ein PASS und ebenso, dass es einen zweiten Eintrag mit STATE_CONSOLIDATE gibt wo das PASS steht.
Somit einfach ignorieren.
