### ISSUE TITLE
Signaturzertifikat und Zertifizierungsstelle für DEP-Export

### ISSUE THREAD

**Issue by bonus7771** [a-sit-plus/at-registrierkassen-mustercode#202]
Hallo,

ich arbeite mit JAVA und direktem Zugriff auf die Karte mittels APDU.

Wie erhalte ich in dieser Umgebung das im DER-Format kodierte Signaturzertifikat sowie das im DER-Format kodierte Zertifikat der jeweiligen Zertifizierungsstelle für den DEP-Export gemäß Pkt 11 der Detailspezifikationen bzw. S 54 der BMF-Festlegungen zu Detailfragen?

**Comment by asitplus-pteufl** [comment]
Bevor Sie da in Details gehen: Diese Angaben sind optional, es besteht keine Notwendigkeit diese dem RKSV-DEP Export beizufügen.

Bezüglich den APDUs, bitte direkt mit dem ZDA klären, Muster-Code für die Verwendung der Karte sollten von den ZDAs zur Verfügung stehen.

**Comment by bonus7771** [comment]
ok, das habe ich gelesen; jedoch steht unter Pkt 3 der Det.Spez aber nichts von "optional".  Kann ich diese Felder trotzdem leer oder gleich ganz weglassen?

**Comment by asitplus-pteufl** [comment]
beide Varianten sind in Ordnung. Sie werden auch sehen, dass das Prüftool beide Varianten akzeptiert.

**Comment by bonus7771** [comment]
Super, danke für die rasche Antwort!

**Comment by ep27** [comment]
Auch wenn ich eher nicht mehr machen will als ich muss, stelle ich doch die Frage - ich habe mir von A-Trust ein rk-Online Zertifikat besorgt. Wenn ich das sozusagen als Fleißaufgabe angeben will, hätte ich gedacht, ich codiere einfach den Inhalt, des Zertifikats, das man nach Erstellung herunterladen kann nach base64. Aber das hat bei mir dann 1753 Zeichen was mir sehr übertrieben vorkommt.

Und was würde ich bei der Zertifizierunsstelle eingeben? base64 von "a-trust" wird wohl nicht passen.
