### ISSUE TITLE
DEP und Adresse

### ISSUE THREAD

**Issue by RKSV** [a-sit-plus/at-registrierkassen-mustercode#203]
Kurze Fragestellung: Muss im DEP die Adresse jeder einzelnen Filiale gespeichert werden oder gilt hier die UID als die eindeutige Bezeichnung des Unternehmers?

Hintergrundgedanke: 
Mindestanforderung Journal aus BAO
Die Belegerteilungsverpflichtung kann im Falle einer Organschaft (§ 2 Abs. 2 Z 2 UStG 1994) auch von der Organgesellschaft, im Falle der Unternehmereinheit im Sinn des Umsatzsteuerrechtes auch von einer der in der Unternehmereinheit zusammengeschlossenen Personengesellschaften (Personengemeinschaften) erfüllt werden.
(3) Die Belege haben mindestens folgende Angaben zu enthalten:
1. eine eindeutige Bezeichnung des liefernden oder leistenden Unternehmers oder desjenigen, der gemäß Abs. 2 an Stelle des Unternehmers einen Beleg erteilen kann,

**Comment by ErichFreitag** [comment]
Zunächst die Frage - in welchem DEP - im Datenerfassungsprotokoll der Kasse ("Journal") oder im Datenerfassungsprotokoll gemäß RKSV?

Im Journal müssen sie ohnedies "alles" speichern. Bezüglich RKSV-DEP kann es nur ein einem Unternehmen zugeordnetes DEP pro Kasse geben, da die Signaturen an ein Unternehmen (z.B. identifiziert über die UID) gebunden sind.

**Comment by AxelKutschera** [comment]
Die UID-Nummer ist ausreichend.

PS: Der Name @RKSV ist toll ;-)

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
