### ISSUE TITLE
regkassen-verification-depformat - source codes

### ISSUE THREAD

**Issue by jantursky** [a-sit-plus/at-registrierkassen-mustercode#204]
Hello,

is it possible to provide _source codes_ for verification process of the library **regkassen-verification-depformat-1.0.0.jar**? I'm trying to implement this solution on the mobile platform, but before choosing this solution as final, we need to test it, if the depformat verification will pass on the mobile platform (Android, iOS, ...) also. Is it possible?

**Comment by asitplus-pteufl** [comment]
This needs to be decided by the BMF, and the current position is not to release the source code.
