### ISSUE TITLE
RKSV Fragen

### ISSUE THREAD

**Issue by envomer** [a-sit-plus/at-registrierkassen-mustercode#205]
Hi,

ich habe da noch ein paar Fragen.

1. Sammelbeleg
- Inhalt eines Beleges, welche Merkmale
- Ablauf bei Ausfall, Reihenfolge was passiert
- Automatisch oder kann man auch selber erstellen als Kunde
- Allgemeiner Ablauf und Funktion

2. Tages-, Monats-, Jahresabschlüsse 
- Inhalt und Merkmale von unterschiedlichen Abschlüssen (Tag, Monat, Jahr)
- Erstellt man diese Selber oder werden die automatisch generiert
- Wird der Summenzähler auf Null gestellt nach Ende der Zeitspanne; z.B.: Jahresabschluss

3. Summenzähler
- Was wird genau gezählt (Steuern, Umsatz Netto/Brutto)

4. Signierte Rechnungen
- Werden signierte Rechnungen von Hersteller oder A-Trust an Finanzamt geschickt
- Testzugang zu Webservice

**Comment by ErichFreitag** [comment]
Dass sie sich meiner Meinung nach dringend mit einer fiskalen Middleware auseinandersetzen sollten habe ich schon erwähnt.

ad Sammelbeleg: 
Ablauf: ein Sammelbeleg ist zu erstellen, wenn die Signaturerstellungseinheit ausgefallen war und wieder verfügbar ist. Er wird typisch nach einem wieder signierbaren Beleg als signierter Nullbeleg eingefügt.

Inhalt: Barumsatz 0 plus Kennzeichnung des Beginns und des Endes des Ausfalls der Signaturerstellungseinheit

Funktion: siehe Inhalt

Erstellung: wird wohl nur automatisch gehen


ad Tages-, Monats-, Jahresabschlüsse

Im Sinne der RKSV gibt es keine Abschlüsse. 

Es gibt Monatsbelege und Jahresbelege. Die sind jeweils zu Ende eines Monats zu erstellen und haben einen Barumsatz von 0 zuzüglich einer sinnvollen Bezeichnung. Jeder Jahresbeleg muss zusätzlich wie der Startbeleg geprüft werden.

Der Summenzähler läuft vom Startbeleg weg bis zum Lebensende einer Kasse (Schlussbeleg) durchgehend und wird nie auf 0 gesetzt.


ad Summenzähler

Es werden positive und negative Brutto-Barumsätze gezählt.


ad Signierte Rechnungen

In der RKSV gibt es keine signierten Rechnungen, es gibt nur signierte Barumsätze. Zu A-Trust oder zum Finanzamt wird nichts gesendet. Richtung Finanzamt gibt es lediglich An- und Abmeldungen, Ausfalls- und Wiederverfügbarkeitsmeldungen plus den Start- und Jahresbelegprüfungen.

A-Trust hat damit auch nichts zu tun - A-Trust ist einer von 3 VDAs in Österreich, wo sie Zertifikate und/oder Signaturdienste beziehen können.


Testzugang zu Webservice: siehe FON-Dokumentation. 
art_uebermittlung für Testübermittlungen
vda_id = AT9 für Testübermittlungen ohne gültigem Zertifikat

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
