### ISSUE TITLE
Startbeleg bei vorhandenen DEP

### ISSUE THREAD

**Issue by envomer** [a-sit-plus/at-registrierkassen-mustercode#206]
Was passiert wenn man den Startbeleg bei einer Kassa generiert die schon vergangene Rechnungen im DEP hat?

Wird der Summenzähler auf 0 gesetzt oder lauft er mit der derzeitigen Summe weiter?

**Comment by AxelKutschera** [comment]
Unser Dienst behandelt es so:
1. Vor dem Startbeleg ist die RegK ist nicht in Betrieb und kann nicht mit manipulationssicher Sicherheitseinrichtung (SE) arbeiten. Dies würde einem Ausfall entsprechen. 
2. Belege dürfen nicht signiert werden. Daher kein DEP, Summenzähler, QR.
3. Es müssten handschriftliche Belege erstellt werden. Analog zu den sonstigen Bestimmungen können Umsätze vor der Inbetriebnahme der Sicherheitseinrichtung (SE) als Ausfallbelege nacherfasst werden.

**Comment by ErichFreitag** [comment]
Wenn sie - ohne Dienst - einen Startbeleg generieren, nachdem es schon einen gegeben hat, wird und kann das nicht funktionieren, da 
- damit der Umsatzzähler auf 0 gesetzt wird (was im laufenden Betrieb nicht sein darf)
- das Datenerfassungsprotokoll neu eingerichtet wird (was im laufenden Betrieb nicht sein darf)
- die Verkettung nicht auf den letzten Beleg zeigt (was im laufenden Betrieb nicht sein darf)
- die Kasse damit registriert werden muss (was bei einer bestehenden Kasse nicht möglich ist)

sprich - ohne Schlussbeleg (inklusive Kassenabmeldung) und komplettem Clean-Up (DEP-Sicherung, ...) kann kein neuer Startbeleg erzeugt werden.

**Comment by envomer** [comment]
@ErichFreitag @AxelKutschera  Danke.
