### ISSUE TITLE
Rechnungen und Belege

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#207]
Hallo,

wenn eine Rechnung (Warenwirtschaftssystem) zu einem späteren Zeitpunk BAR bezahlt wird (z.B. nach einer Woche) kann man einen Beleg erstellen, signieren, auf die Rechnung verweisen und keine Steuer am Beleg anführen (0%).

Wie soll man aber eine Rechnung behandeln die in mehreren Teilen und mit mehreren Zahlungsarten begliechen wird z.B.
Rechnung = 1000 EUR (Brutto)
1 Woche nach der Rechnungsaustellung zahlt der Kunde 300 EUR BAR
Nach 14 Tagen überweisst der Kunde 500 EUR
... und nach 20 Tagen zahlt der Kunde wieder die restlichen 200 EUR in BAR.

Man kann wieder die BAR Belege erstellen und auf die Rechnung verweisen aber wie soll man in diesem Fall die Steuern aufteilen? oder kann man auch in diesen Fällen die Steuer mit 0% auf dem Beleg angeben?
Muss die Rechnung in diesem Fall signiert werden oder nur die Belege?

Danke im Vorraus für die Rückmeldung.

**Comment by lebail** [comment]
Die Rechnung ist in diesem Beispiel eine Zielrechnung und muss daher nicht signiert werden. Die beiden Barbelege verweisen auf diese Rechnung und können mit 0% USt. erfasst werden (und sind zu signieren).

Es wäre aber auch zulässig, die Beträge auf den Barzahlungsbelegen den passenden Steuersätzen zuzuordnen, wenn auf diesen Belegen erkennbar ist, dass es sich hinsichtlich der USt. um Rechnungsduplikate handelt.

Siehe Erlass, Punkt 4.6.6

Disclaimer: Das ist keine offizielle Antwort; ich bin hier nur ein ganz normaler User.

**Comment by AxelKutschera** [comment]
Die Belege sind nach RKSV zu erstellen:
- EUR 300,- / Betrag-Satz-Null / signieren / Verweis auf die Re-Nummer
- EUR 200,- / Betrag-Satz-Null / signieren / Verweis auf die Re-Nummer

Die Umsatzsteuer muss in den Belegen nicht aufgeteilt werden. Man darf sie aber aufteilen. 
Dies ist nur bei einer Rechnung mit verschiedenen Steuersätzen relevant. (Wir haben diesbezüglich einige Beispiele.)
Wann die Umsatzsteuer an das Finanzamt abzuführen ist, hat mit den Belegen nichts zu tun. 

Wenn die Belege nicht alle Rechnungsmerkmale enthalten, muss auf dem Beleg auch kein Hinweis auf ein "Rechnungsduplikat" stehen.

**Comment by AlgoLinz** [comment]
danke für schnelle Antworten lebail, Herr Kutschera.
Herr Kutschera, wo kann ich die Beispiele anschauen?

mfg

**Comment by AxelKutschera** [comment]
Beispiele kann ich per Mail beantworten bzw. gibt es (kostenfrei) für unsere Partner.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by AlgoLinz** [comment]
Die Belege können auf die Zielrechnungen verweisen. Ist es möglich auch die Nullbelege (Startbeleg, Kontrollbeleg, Monatsbeleg usw.) auf eine dazu erstellte Zielrechnung mit den entpsrechenden Merkmalen zu verweisen.

(sorry für die organisatorische Frage)
@AxelKutschera - Ihre E-Mail Adresse habe ich leider nicht.

**Comment by AxelKutschera** [comment]
@AlgoLinz 
Das ist eine interessante Idee... ;-)
Diese Nullbelege haben als Merkmal, den Hinweis auf diesen Sonderbeleg anzumerken.

Im Erlass Kapitel 4.5.7. (Seite 57 2. Absatz) steht: 
"**Start-, Monats-, Jahres- und Schlussbelege ab 1. April 2017 (§ 8 RKSV)**
Start-, Monats-, Jahres- und Schlussbelege sollten als solche bzw. als Nullbelege im Feld der handelsüblichen Bezeichnung gekennzeichnet werden."

+436641028485 https://www.fiskaltrust.at/impressum/

**Comment by AlgoLinz** [comment]
vielen Dank für die Antworten.

**Comment by AxelKutschera** [comment]
Gerne - Telefonieren geht auch gerne am Abend. ;-)
