### ISSUE TITLE
Bonabbruch

### ISSUE THREAD

**Issue by Georg67** [a-sit-plus/at-registrierkassen-mustercode#208]
Unser Kassaprogramm verfügt über die Funktion des Bonabbruchs. Hier wird der laufende Kassiervorgang abgebrochen (Wenn z.B. ein Kunde sein Geld vergessen hat). Wie ist ein Bonabbruch zu signieren? Trainings-Buchnung? Storno-Buchung mit Umsatz 0?

Für entsprechende Informationen wäre ich dankbar.

**Comment by ErichFreitag** [comment]
Gar nicht, weil es ja zu keinem Barumsatz gekommen ist?

**Comment by Georg67** [comment]
Tut es bei einer Trainings-Buchung auch nicht, aber sie muss trotzdem signiert werden.

**Comment by ErichFreitag** [comment]
Das ist schon korrekt, aber das ist auch extra so spezifiziert. Abbruch - kein Barumatz - keine Signierung.

**Comment by ckvsoft** [comment]
Wann ist der Abbruch? Nachdem der Bon erstellt wurde wirds ja nicht sein, dann müsste der BON storniert werden. Wenn vorher dann gibt es ja keinen BON.

**Comment by lebail** [comment]
Das gegeständliche Beispiel ist sicherlich keine Trainingsbuchung.

Ich nehme an, es gibt 2 Möglichkeiten:

- Entweder der Kundenbeleg wurde bereits ausgestellt (und signiert), dann ist im Falle der Nichtbezahlung eine Stornobuchung über den (negativen) Zahlbetrag zu erfassen (und zu signieren).
- Oder der Kundenbeleg wurde noch nicht ausgestellt, dann gibt es auch nichts zu stornieren und zu signieren.

**Comment by Georg67** [comment]
Es gibt Fälle, wo bereits Positionen erfasst wurden, aber es zu keinem Abschluss (keiner Zahlung) kommt.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by AxelKutschera** [comment]
Ich verwende zur Erklärung zwei Fälle:
1. "Sofort-Storno": Die Positionen wurden lediglich in einer Bildschirmmaske erfasst und nicht im Protokoll gespeichert. (Es wurde keinerlei ID vergeben)
--> Diese Eingabe darf gelöscht werden, ohne protokolliert zu werden.
Hierzu auch das KFS-DV1 "Änderungen vor dem technischen Buchungszeitpunkt sind hiervon nicht betroffen. " Kap.3.8 (20) letzter Satz. [zu finden unter https://www.fiskaltrust.at/products/consulting/rechtsgrundlagen/ --> [KFS/DV1 Fachsenat für Datenverarbeitung der Kammer der Wirtschaftstreuhänder – Ordnungsmäßigkeit von IT-Buchführungen](https://www.fiskaltrust.at/wp-content/uploads/2016/12/110500-52-KFS-DV1.pdf) ]

2. "Storno": Die Erfassung der Positionen wurde bereits in einer Tabelle zB mit ID gespeichert. 
--> Dann ist diese Erfassung zu protokollieren und darf nur mehr durch eine Storno-Bonierung (hier ohne Signatur) korrigiert werden.
Hierzu wird im Erlass  Kapitel "2.4.1. Geschäftsvorfall Allgemein" der Geschäftsvorfall beschrieben mit: 
"Im Regelfall handelt es sich bei Geschäftsvorfällen um Ereignisse im Geschäftsbetrieb, die mit der Ersterfassung der Auftragsposition (zB **Bestellungseingabe im Kassensystem, Warenwirtschaftssystem, Artikelscan an der Kasse,** Einschalten des Taxameters) beginnen und in deren Rahmen üblicherweise ein geldwerter Leistungsaustausch zwischen dem Unternehmer/Abgabepflichtigen und dem Kunden stattfindet."

--> Beide Fälle sind - da kein Barumsatz stattgefunden hat - nicht zu signieren. (so wie @ErichFreitag schreibt)
