### ISSUE TITLE
Zeitpunkt Prüfung Jahresbeleg

### ISSUE THREAD

**Issue by lonelypbdev** [a-sit-plus/at-registrierkassen-mustercode#209]
Ich hoffe es wurde hier noch nicht gefragt, aber wie verhält es sich bei der Prüfung des Jahresbelegs genau?
Der Jahresbeleg ist ja, so wie der Startbeleg, zu prüfen. Muss der Jahresbeleg dabei nach dessen Erstellung sofort geprüft werden? D.h. dürfen weitere Belege erstellt werden bevor die Prüfung erfolgt ist.

In der Praxis trifft das jene Kassen die keine permanente Internetverbindung haben.
Szenario wäre folgendes: am 2. Jänner wird der erste Beleg geschrieben. Dabei erkennt unser System das der Jahresbeleg erstellt werden muss und erstellt diesen (und würde diesen auch sofort per Webservice prüfen).
Besteht nun aber keine Internetverbindung, so kann die Prüfung erst erfolgen, wenn der Kassen-PC zum nächsten Mal eine Internet-Verbindung hat (zB zum Programm-Update).
Von der Möglichkeit per Handy-App zu prüfen möchte ich hier mal absehen, da auch das nicht jedem Kunden zuzumuten/möglich ist.

Ich spreche hier nur von der Prüfung, nicht von der Signierung!

Also weiter Belege erfassen ja oder nein? Und wenn ja, bis wann muss dann der Jahresbeleg geprüft sein?

**Comment by ErichFreitag** [comment]
Siehe Erlass 4.5.7 "Jahresbelege sind wie Startbelege zu prüfen (Abschnitt 3.5.3.2.), wobei diese Prüfung spätestens bis zum 15. Februar des Folgejahres durchgeführt sein muss". Ungeachtet dessen sollten sie die Prüfung möglichst zeitnah durchführen.

D.h. sie können auch weiter Belege nach dem Jahresbeleg (für das neue Jahr) erfassen. Sollte es dabei zu einem Problem kommen ist eine nachvollziehbare Dokumentation der Ursachen und der Fehlerbehebung sinnvoll.

Die Prüfapp kann man denke ich einem Kunden schon zumuten, gegebenenfalls ist bei der Einrichtung zu unterstützen. Eine App aufzurufen, den QR-Code (?) einzuscannen und das Prüfergebnis zu lesen verlangt keine außerordentlichen Kenntnisse.

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.

**Comment by lonelypbdev** [comment]
Danke Hr. Freitag, im Erlass steht es eh ganz genau drin.
Ich versuche eben den Weg zu gehen, das die SW so viel wie möglich selbst erledigt. Der Kunde soll sich über die ganzen zusätzlichen Erfordernisse der RK gar keine Gedanken machen müssen...

**Comment by ErichFreitag** [comment]
Das ist ein guter Ansatz, möglichst viel zu automatisieren. Es entbindet halt den Betreiber trotzdem nicht von gewissen Pflichten - abgesehen von der Sicherung des Datenerfassungsprotokolls wird sich ja auch jemand das Prüfergebnis des Jahresbelegs ansehen müssen usw.
