### ISSUE TITLE
Quellcode für Verification

### ISSUE THREAD

**Issue by andix25** [a-sit-plus/at-registrierkassen-mustercode#21]
Ich finde den Quellcode für die beiden `regkassen-verification`-Tools nicht im Repositiory.

Wäre es möglich die Quellcodes auch zu veröffentlichen? Ich würde die "offiziellen" Verification-Tools gerne als Unit-Test in meine Implementierung einbauen.

**Comment by pteufl** [comment]
Nach derzeitigem Stand ist dazu keine Veröffentlichung vorgesehen.
Was ich aber schon ankündigen kann, sind weitreichende Testfälle die es den Herstellern ermöglichen die verschiedenen Abläufe, Varianten von Belegen besser als jetzt testen zu können.

**Comment by andix25** [comment]
Schade.

Danke trotzdem für die rasche Antwort.

**Comment by lebail** [comment]
Unter diesen Umständen muss ich doch noch mit einer schon lange offenen Frage lästig sein:

Ist die derzeitige Version des Verification-Tools in der Lage, auch "echte" Signaturen (z.B. solche von der A-Trust-Chipkarte) zu verifizieren? Und wenn nein, ist dies für die Zukunft geplant?

Vielen Dank!

**Comment by pteufl** [comment]
beim prüftool muss jetzt schon das signatur zertifikat angegeben werden. es wird auch geprüft ob die signatur kryptographisch korrekt ist (mit dem öffentlichen schlüssel im angegeben Zertifikat). ob das nun mit dem selbst-signierten zertifikat aus dem demo-code oder dann mit einem a-trust/globaltrust/etc. zertifikat gemacht wird ist egal. die gültigkeit/vertrauenswürdigkeit/widerruffstatus des zertifikats werden nicht überprüft.

**Comment by lebail** [comment]
Vielen Dank!

Ich wollte nur sichergehen, dass der Grund für die bei mir auftretenden kryptographischen Validierungsfehler des DEP (bei Benutzung von Chipkarten- oder "Mobil"-Signaturen des bekannten österreichischen Anbieters) tatsächlich in meiner Implementierung zu suchen ist - und nicht etwa in einem noch fehlenden Feature des Prüftools.

**Comment by pteufl** [comment]
hier noch ein hinweis: es kann sein, dass bei der signaturkarte gleich das korrekte signaturformat im Sinne von JWS zurückkommt. die im muster-code verwendete transformation (DER) ist dann nicht notwendig. vielleicht liegt hier das problem.

**Comment by andix25** [comment]
@lebail: Bei mir liefert A-Trust Mobile keine funktionierende Signatur. Offenbar wird das falsche Zertifikat zur Erstellung der Signatur benutzt. A-Trust Chip funktioniert.

Genau das bestätigt mir auch dieses Kontrolltool hier. Ich benutze dafür ``SignatureVerificationModuleJWSFormat`` sowie ``QRCodeRepVerificationModule``

**Comment by lebail** [comment]
Vielen Dank!

Ich hatte ebenfalls einen solchen Verdacht. Denn wenn ich mir die Zertifikate mit
> openssl x509 -in cert.pem -text

ansehe, erhalte ich …

… für ein A-Trust-Mobile-Zertifikat aus dem Testsystem
> Signature Algorithm: sha1WithRSAEncryption

… für meine A-Trust-Chipkarte
> Signature Algorithm: sha256WithRSAEncryption

… und für ein A-Sit Zertifikat aus dem Democode
>  Signature Algorithm: ecdsa-with-SHA256

Dass das SHA1 (beim Mobilzertifikat) nicht passt, hatte ich erwartet; aber auch die anderen beiden stimmen interessanterweise nicht überein. Ist unter diesen Umständen tatsächlich anzunehmen, dass das Zertifikat meiner Chipkarte in Ordnung ist? Vielleicht sind ja unterschiedliche Varianten der Karte im Umlauf …

**Comment by pteufl** [comment]
@lebail Können Sie bitte den ganzen OpenSSL Text posten?
Der Signaturalgorithmus (und der Hash dazu) mit dem das Zertifikat signiert wurde ist nicht relevant (das kann durchaus RSA sein wenn die CA einen RSA Schlüssel hat). Wichtig ist aber die Art des Schlüsselpaars im Zertifikat. Das darf KEIN RSA Schlüssel sein, sonder muss ein ECC Schlüssel Paar sein.

**Comment by lebail** [comment]
Danke. Das dürfte dann ohnehin passen (wegen: Public Key Algorithm: id-ecPublicKey):
			
Mobil-Zertifikat:
> openssl x509 -in mobcert.pem -text
			
			Certificate:
			 Data:
			  Version: 3 (0x2)
			  Serial Number: 963244433 (0x3969f191)
			 Signature Algorithm: sha1WithRSAEncryption
			  Issuer: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU=a-sign-Premium-Test-Sig-02, CN=a-sign-Premium-Test-Sig-02
			  Validity
			Not Before: Oct  7 16:10:12 2015 GMT
			Not After : Oct  7 14:10:12 2020 GMT
			  Subject: C=AT, CN=UID ATU99999999, SN=ATU99999999, GN=UID/serialNumber=487800320656
			  Subject Public Key Info:
			Public Key Algorithm: id-ecPublicKey
			 Public-Key: (256 bit)
			 pub: 
			  04:77:47:e1:53:21:29:f7:52:66:cf:79:28:e2:a5:
			  68:4f:1b:14:c2:72:71:1a:1d:2d:af:76:91:55:53:
			  bf:46:dd:d3:dd:a3:ea:09:b9:33:05:29:92:30:e1:
			  57:ac:cb:ae:d3:8b:ab:6a:c4:01:e9:28:59:2c:55:
			  72:10:fb:b2:df
			 ASN1 OID: prime256v1
			  X509v3 extensions:
			Authority Information Access: 
			 CA Issuers - URI:http://www.a-trust.at/certs/a-sign-Premium-Test-Sig-02.crt
			 OCSP - URI:http://ocsp-test.a-trust.at/ocsp
			
			X509v3 Key Usage: critical
			 Digital Signature, Non Repudiation
			qcStatements: critical
			 0.0......F..0..+.......
			X509v3 CRL Distribution Points: 
			
			 Full Name:
			URI:ldap://ldap-test.a-trust.at/ou=a-sign-Premium-Test-Sig-02,o=A-Trust,c=AT?certificaterevocationlist?base?objectclass=eidCertificationAuthority
			
			X509v3 Basic Constraints: 
			 CA:FALSE
			X509v3 Certificate Policies: 
			 Policy: 0.4.0.1456.1.1
			 Policy: 1.2.40.0.17.1.11
			CPS: http://www.a-trust.at/docs/cp/a-sign-Premium
			
			X509v3 Authority Key Identifier: 
			 keyid:46:06:9F:8E:41:8E:15:BD
			
			X509v3 Subject Key Identifier: 
			 40:BC:3A:7F:AA:5C:4C:50
			X509v3 Subject Alternative Name: 
			 email:test@test.com
			 Signature Algorithm: sha1WithRSAEncryption
			4c:fe:2f:df:4e:53:1d:a4:1c:ab:f5:d5:55:24:08:7b:65:32:
			c0:61:8a:f1:2d:11:1e:aa:51:b4:e0:d0:ff:b9:cd:04:96:a8:
			5b:04:a2:45:e2:fd:af:6e:00:bf:87:2c:0f:48:7f:5b:1a:59:
			0e:e1:d1:78:13:b6:7a:0e:c4:37:f0:83:37:b9:cd:30:54:ff:
			86:b9:c5:3f:b4:4c:7f:48:64:4a:da:a6:61:b1:0d:56:43:20:
			f7:98:2d:14:b4:67:c1:37:2a:e8:2c:04:20:87:18:64:41:ba:
			5b:9c:bf:52:ea:f5:54:bb:f1:71:41:c6:14:12:84:2b:ac:e0:
			42:54:f7:ef:b8:6e:e2:f1:ee:30:f5:29:0b:9e:e0:a2:a2:ce:
			31:48:6d:2a:ca:9d:32:04:83:76:a2:ca:75:26:2e:1d:70:cd:
			6c:7c:5a:57:4a:eb:1b:e5:df:63:91:00:45:79:65:ac:34:61:
			82:0f:ce:20:19:7b:66:39:e5:82:5d:57:51:02:9b:ca:14:ff:
			2f:0a:72:9d:e8:ba:37:8d:31:cb:11:40:5d:dc:f6:26:78:da:
			5c:4c:e2:b5:00:ec:6d:27:1f:5f:90:2e:bb:e1:1c:cf:34:51:
			04:30:74:6b:b2:97:f5:cf:2f:3e:37:d8:c8:6f:b1:44:4d:a0:
			93:50:03:aa
			-----BEGIN CERTIFICATE-----
			MIIEzDCCA7SgAwIBAgIEOWnxkTANBgkqhkiG9w0BAQUFADCBoTELMAkGA1UEBhMC
			QVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUg
			aW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaYS1zaWduLVBy
			ZW1pdW0tVGVzdC1TaWctMDIxIzAhBgNVBAMMGmEtc2lnbi1QcmVtaXVtLVRlc3Qt
			U2lnLTAyMB4XDTE1MTAwNzE2MTAxMloXDTIwMTAwNzE0MTAxMlowYjELMAkGA1UE
			BgwCQVQxGDAWBgNVBAMMD1VJRCBBVFU5OTk5OTk5OTEUMBIGA1UEBAwLQVRVOTk5
			OTk5OTkxDDAKBgNVBCoMA1VJRDEVMBMGA1UEBQwMNDg3ODAwMzIwNjU2MFkwEwYH
			KoZIzj0CAQYIKoZIzj0DAQcDQgAEd0fhUyEp91Jmz3ko4qVoTxsUwnJxGh0tr3aR
			VVO/Rt3T3aPqCbkzBSmSMOFXrMuu04urasQB6ShZLFVyEPuy36OCAhMwggIPMIGE
			BggrBgEFBQcBAQR4MHYwRgYIKwYBBQUHMAKGOmh0dHA6Ly93d3cuYS10cnVzdC5h
			dC9jZXJ0cy9hLXNpZ24tUHJlbWl1bS1UZXN0LVNpZy0wMi5jcnQwLAYIKwYBBQUH
			MAGGIGh0dHA6Ly9vY3NwLXRlc3QuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQE
			AwIGwDAnBggrBgEFBQcBAwEB/wQYMBYwCAYGBACORgEBMAoGCCsGAQUFBwsBMIGk
			BgNVHR8EgZwwgZkwgZaggZOggZCGgY1sZGFwOi8vbGRhcC10ZXN0LmEtdHJ1c3Qu
			YXQvb3U9YS1zaWduLVByZW1pdW0tVGVzdC1TaWctMDIsbz1BLVRydXN0LGM9QVQ/
			Y2VydGlmaWNhdGVyZXZvY2F0aW9ubGlzdD9iYXNlP29iamVjdGNsYXNzPWVpZENl
			cnRpZmljYXRpb25BdXRob3JpdHkwCQYDVR0TBAIwADBZBgNVHSAEUjBQMAgGBgQA
			izABATBEBgYqKAARAQswOjA4BggrBgEFBQcCARYsaHR0cDovL3d3dy5hLXRydXN0
			LmF0L2RvY3MvY3AvYS1zaWduLVByZW1pdW0wEwYDVR0jBAwwCoAIRgafjkGOFb0w
			EQYDVR0OBAoECEC8On+qXExQMBgGA1UdEQQRMA+BDXRlc3RAdGVzdC5jb20wDQYJ
			KoZIhvcNAQEFBQADggEBAEz+L99OUx2kHKv11VUkCHtlMsBhivEtER6qUbTg0P+5
			zQSWqFsEokXi/a9uAL+HLA9If1saWQ7h0XgTtnoOxDfwgze5zTBU/4a5xT+0TH9I
			ZErapmGxDVZDIPeYLRS0Z8E3KugsBCCHGGRBulucv1Lq9VS78XFBxhQShCus4EJU
			9++4buLx7jD1KQue4KKizjFIbSrKnTIEg3aiynUmLh1wzWx8WldK6xvl32ORAEV5
			Zaw0YYIPziAZe2Y55YJdV1ECm8oU/y8Kcp3oujeNMcsRQF3c9iZ42lxM4rUA7G0n
			H1+QLrvhHM80UQQwdGuyl/XPLz432MhvsURNoJNQA6o=
			-----END CERTIFICATE-----
			
Chipkarte:
> openssl x509 -in cardcert.pem -text
			
			Certificate:
			 Data:
			  Version: 3 (0x2)
			  Serial Number: 1709358 (0x1a152e)
			 Signature Algorithm: sha256WithRSAEncryption
			  Issuer: C=AT, O=A-Trust Ges. f. Sicherheitssysteme im elektr. Datenverkehr GmbH, OU=A-Trust Registrierkasse.CA, CN=A-Trust Registrierkasse.CA
			  Validity
			Not Before: Oct 22 07:56:11 2015 GMT
			Not After : Oct 22 05:56:11 2020 GMT
			  Subject: C=AT, CN=Steuernummer xxxxx/xxxx/serialNumber=961846274648
			  Subject Public Key Info:
			Public Key Algorithm: id-ecPublicKey
			 Public-Key: (256 bit)
			 pub: 
			  04:c6:5a:36:56:04:33:ae:f0:85:1f:1e:74:52:1d:
			  7a:e4:3c:2f:ca:47:c8:7f:4f:70:17:23:fd:ff:2e:
			  21:11:3b:16:6a:55:91:d5:cc:ea:8c:86:98:3d:e7:
			  53:ac:9f:b7:95:ff:d9:5f:2e:0f:3e:b2:78:a9:ba:
			  fa:18:e3:95:27
			 ASN1 OID: prime256v1
			  X509v3 extensions:
			X509v3 Subject Key Identifier: 
			 42:70:DB:B4:A9:4C:FA:3D
			X509v3 Key Usage: critical
			 Digital Signature, Non Repudiation
			1.2.40.0.10.1.11.1: 
			 ..Steuernummer xxxxx/xxxx
			X509v3 Authority Key Identifier: 
			 keyid:40:47:9E:AE:E3:90:DF:B6
			
			X509v3 Basic Constraints: 
			 CA:FALSE
			Authority Information Access: 
			 CA Issuers - URI:http://www.a-trust.at/certs/A-Trust-Registrierkasse-CA.cer
			
			X509v3 Certificate Policies: 
			 Policy: 1.2.40.0.17.1.24
			CPS: http://www.a-trust.at/docs/cp/A-Trust-Registrierkasse
			
			X509v3 Subject Alternative Name: 
			 email:xxx@example.com
			 Signature Algorithm: sha256WithRSAEncryption
			48:35:5c:e8:e3:2a:2b:53:f7:5c:a1:08:5f:7a:d8:a7:01:d4:
			06:b0:33:7c:50:18:53:fb:2c:15:9e:7b:f7:1b:02:d4:05:09:
			92:cd:3d:27:7e:b4:06:95:f1:c7:ea:73:c1:49:d7:bd:f3:f4:
			d3:10:98:ac:4a:e6:7e:e8:e0:09:a2:04:ad:3a:f3:8c:cb:9e:
			fd:5c:c4:47:a7:94:3c:94:d7:c8:3d:7f:9b:16:7a:86:e2:52:
			01:71:01:b9:b6:16:f6:1d:52:bb:c3:54:d8:7b:d5:6b:b5:3b:
			9c:b4:16:ca:3e:b3:a4:d7:9c:a6:d0:80:46:d3:33:9d:d3:ee:
			45:c4:97:0a:a6:82:2a:5d:00:8b:3c:fe:40:7d:f9:3b:f0:b0:
			e8:78:e4:f2:d2:2b:1d:ae:16:63:c8:f0:96:63:d7:ba:94:76:
			d3:db:58:3f:62:c0:19:6e:78:23:4c:93:f1:d5:4b:1f:5b:e0:
			b0:4b:fb:5f:a3:1f:82:43:77:68:31:e6:8e:43:2c:35:c9:ae:
			5f:ae:d6:ef:f3:00:04:bf:10:9d:bb:60:0a:76:6c:dd:b9:a2:
			a2:04:a1:78:7f:eb:0b:d7:7c:34:85:31:4a:e5:63:6a:5c:1c:
			97:63:b4:7b:4a:55:8e:bf:f1:76:fa:a0:ca:ca:08:0b:e0:5b:
			34:cc:52:91:13:d8:30:b6:12:46:52:f4:2f:5d:57:7f:df:5f:
			71:e6:1d:57:2c:0a:8e:c0:69:24:a4:29:01:e3:98:3b:c9:cd:
			7e:cb:b7:4a:df:9e:60:fc:0f:93:4c:3f:1a:95:e5:28:c2:81:
			39:bb:7a:27:a9:f2:32:fe:b5:ab:df:02:32:03:69:cc:31:7a:
			8c:85:14:23:3d:58:72:bb:96:da:f1:c7:c0:84:3b:25:8e:23:
			4a:31:78:3b:dd:cb:53:b7:a4:aa:65:4e:be:54:72:54:1a:86:
			ed:fc:a7:19:3a:65:8d:3c:f8:08:8e:9f:87:18:77:52:40:72:
			a8:da:a1:5e:b0:cb:26:6b:60:20:74:4e:56:b2:e6:49:fe:67:
			a2:ab:1a:45:41:00:71:e2:66:42:20:91:2f:ec:99:cc:54:4f:
			cb:fe:e3:b6:78:66:dc:3b:e6:6b:09:4c:63:f4:2c:a6:32:d0:
			76:41:5e:83:49:f2:b7:0a:b7:2b:91:0f:1b:d1:90:7c:04:0a:
			c7:36:81:b4:ca:ba:7a:75:d9:09:b9:64:b6:80:9b:38:79:48:
			30:fe:8d:0a:0b:c2:24:4e:90:0a:0f:ef:b0:11:3d:67:99:08:
			17:b9:2f:77:a9:0e:85:5a:67:fc:64:24:51:90:28:df:37:a8:
			83:46:2e:46:f0:31:84:71
			-----BEGIN CERTIFICATE-----
			MIIE1jCCAr6gAwIBAgIDGhUuMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYDVQQGEwJB
			VDFIMEYGA1UECgw/QS1UcnVzdCBHZXMuIGYuIFNpY2hlcmhlaXRzc3lzdGVtZSBp
			bSBlbGVrdHIuIERhdGVudmVya2VociBHbWJIMSMwIQYDVQQLDBpBLVRydXN0IFJl
			Z2lzdHJpZXJrYXNzZS5DQTEjMCEGA1UEAwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fz
			c2UuQ0EwHhcNMTUxMDIyMDc1NjExWhcNMjAxMDIyMDU1NjExWjBGMQswCQYDVQQG
			EwJBVDEgMB4GA1UEAwwXU3RldWVybnVtbWVyIDEyODIyLzc5MDcxFTATBgNVBAUT
			DDk2MTg0NjI3NDY0ODBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMZaNlYEM67w
			hR8edFIdeuQ8L8pHyH9PcBcj/f8uIRE7FmpVkdXM6oyGmD3nU6yft5X/2V8uDz6y
			eKm6+hjjlSejggE6MIIBNjARBgNVHQ4ECgQIQnDbtKlM+j0wDgYDVR0PAQH/BAQD
			AgbAMCQGByooAAoBCwEEGQwXU3RldWVybnVtbWVyIDEyODIyLzc5MDcwEwYDVR0j
			BAwwCoAIQEeeruOQ37YwCQYDVR0TBAIwADBWBggrBgEFBQcBAQRKMEgwRgYIKwYB
			BQUHMAKGOmh0dHA6Ly93d3cuYS10cnVzdC5hdC9jZXJ0cy9BLVRydXN0LVJlZ2lz
			dHJpZXJrYXNzZS1DQS5jZXIwWAYDVR0gBFEwTzBNBgYqKAARARgwQzBBBggrBgEF
			BQcCARY1aHR0cDovL3d3dy5hLXRydXN0LmF0L2RvY3MvY3AvQS1UcnVzdC1SZWdp
			c3RyaWVya2Fzc2UwGQYDVR0RBBIwEIEOaW5mb0BwYXNjYWwuYXQwDQYJKoZIhvcN
			AQELBQADggIBAEg1XOjjKitT91yhCF962KcB1AawM3xQGFP7LBWee/cbAtQFCZLN
			PSd+tAaV8cfqc8FJ173z9NMQmKxK5n7o4AmiBK0684zLnv1cxEenlDyU18g9f5sW
			eobiUgFxAbm2FvYdUrvDVNh71Wu1O5y0Fso+s6TXnKbQgEbTM53T7kXElwqmgipd
			AIs8/kB9+TvwsOh45PLSKx2uFmPI8JZj17qUdtPbWD9iwBlueCNMk/HVSx9b4LBL
			+1+jH4JDd2gx5o5DLDXJrl+u1u/zAAS/EJ27YAp2bN25oqIEoXh/6wvXfDSFMUrl
			Y2pcHJdjtHtKVY6/8Xb6oMrKCAvgWzTMUpET2DC2EkZS9C9dV3/fX3HmHVcsCo7A
			aSSkKQHjmDvJzX7Lt0rfnmD8D5NMPxqV5SjCgTm7eiep8jL+tavfAjIDacwxeoyF
			FCM9WHK7ltrxx8CEOyWOI0oxeDvdy1O3pKplTr5UclQahu38pxk6ZY08+AiOn4cY
			d1JAcqjaoV6wyyZrYCB0Tlay5kn+Z6KrGkVBAHHiZkIgkS/smcxUT8v+47Z4Ztw7
			5msJTGP0LKYy0HZBXoNJ8rcKtyuRDxvRkHwECsc2gbTKunp12Qm5ZLaAmzh5SDD+
			jQoLwiROkAoP77ARPWeZCBe5L3epDoVaZ/xkJFGQKN83qINGLkbwMYRx
			-----END CERTIFICATE-----

**Comment by pteufl** [comment]
können Sie das Code-Snippet posten das Sie zum Signieren verwenden?
Bitte auch unbedingt die von mir oben gemachte Anmerkung beachten: C&P hier:
"hier noch ein hinweis: es kann sein, dass bei der signaturkarte gleich das korrekte signaturformat im Sinne von JWS zurückkommt. die im muster-code verwendete transformation (DER) ist dann nicht notwendig. vielleicht liegt hier das problem."

**Comment by lebail** [comment]
Ich programmiere in C unter Linux und speichere die Daten in einer sqlite-
Datenbank. Zum Signieren mit der Chipkarte verwende ich
den A-Trust PKCS#11-Treiber (für Windows gibt es diesen schon zum Download,
für Linux habe ich von A-Trust eine Vorab-Version bekommen).

Ich mache keine Transformationen und speichere die Signatur so, wie sie
von Karte bzw. Webservice geliefert wird.

Ich poste einmal die mir am relevantesten erscheinenden Code-Teile.
Weiteres folgt bei Bedarf. Vielen Dank für das Drüberschauen!

		/* Signatur mit Chipkarte */
		void Sign_ATrustChip(long rid, char *to_be_signed)
		{
		
		/* rid ist die interne Belegnummer (primary key); */
		/* to_be_signed ist der String aus dem QRCode (natuerlich ohne Signatur), */
		/* gemaess A-Trust-Codebeispielen ist dieser String direkt (ohne BASE64 etc.) */
		/* an den Treiber (Funktion C_RKSign()) zu schicken */ 
		
		  unsigned long ulSignatureLen = 256;
		  char signature[ulSignatureLen];
			 
		  int rv = C_Initialize(NULL);
		  rv = C_RKSign(to_be_signed, strlen(to_be_signed),
			 signature, &ulSignatureLen);
		  if(!rv)	
		 	 qSaveSignatureATrustChip(rid, signature, ulSignatureLen);
		  else 
		    seterr(987);
		  rv = C_Finalize(NULL);
		}

qSaveSignatureATrustChip() schreibt die Signatur, so wie sie von der Karte kommt,
in die sqlite-Datenbank. Die BASE64-Kodierung für die Ausgabe mache ich erst beim Auslesen.


Bei der Mobil-Version baue ich zuerst beim Auslesen der Daten aus der sqlite-
Datenbank das geforderte JSON-Objekt für den POST-Request zusammen; vereinfacht sieht das so aus:

     SELECT JSON_OBJECT('password', password, 'to_be_signed',
      TO_BASE64(to_be_signed, 0)) FROM … WHERE …;

Das A-Trust-Webservice erwartet den zu signierenden String BASE64-kodiert, anderenfalls liefert es
eine Fehlermeldung.

TO_BASE64() und FROM_BASE64 sind (ausreichend getestete) benutzerdefinierte SQL-Funktionen.

		/* Signatur mit Webservice ("mobile") */
		void Sign_ATrustMobile(long rid, char *url, char *json)
		{  
		/* rid ist die interne Belegnummer (primary key); */
		/* url ist der URL des Webservices */
		/* json ist das JSON-Objekt, das an das Webservice zu uebermitteln ist */
		
		  char *sign = doHttpsRequest(url, json); 
		  if(sign)
		 	 qSaveSignatureATrustMobile(rid, sign);
		  else 
		    seterr(988);
		  free(sign);
		}

doHttpsRequest(url, json) führt den Request per CURL aus

In qSaveSignatureATrustMobile(rid, sign) wird die folgende SQL-Abfrage ausgeführt,
sodass die Signatur aus dem gelieferten JSON-Objekt extrahiert und dann unkodiert gespeichert wird:

UPDATE receipts SET signature=FROM_BASE64(JSON_EXTRACT(?2, '$.signature')) WHERE rid=?1

**Comment by pteufl** [comment]
haben Sie schon mal probiert dem C_RKSign die JWS Repräsentation des PlainTexts zu übergeben? (bitte mal das BSP ignorieren)

Nach dem JWS-Standard ist der plaintext für die Signatur: header.payload
wobei der header dem base64-url kodierten Wert des jeweiligen Algorithmus entspricht: für den ES256 ist dies: eyJhbGciOiJFUzI1NiJ9

Den maschinenlesbaren Code (QR-Code) ohne Signatur dann einfach BASE64-URL kodieren und die beiden Werte (header und payload) zusammenfügen:
also z.B: (am besten gleich mit dem String probieren und das Ergebnis and as Prüftool schicken).
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMF9ERU1PLUNBU0gtQk9YNTI0XzM2NjU4NV8yMDE1LTEyLTE3VDExOjIzOjQzXzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF81UVUvYVNROG50dz1fMjBmMmVkMTcyZGFhMDllNV9sRFVrTmhFZUpLWT0

maschinenlesbarer Code dazu (ohne Signatur): 
_R1-AT0_DEMO-CASH-BOX524_366585_2015-12-17T11:23:43_0,00_0,00_0,00_0,00_0,00_5QU/aSQ8ntw=_20f2ed172daa09e5_lDUkNhEeJKY=

**Comment by pteufl** [comment]
Ich hab die Information bekommen dass die PKCS11 Bespiele aktualisiert wurden:
http://labs.a-trust.at/developer/source.aspx

**Comment by lebail** [comment]
Vielen herzlichen Dank für die Tipps!

Die Chipkarten-Signatur habe ich nun erfolgreich verifiziert. Die Mobil-Variante sehe ich mir später nochmals an.

**Comment by pteufl** [comment]
perfekt. einen hinweis den ich hier noch machen möchte (aufgrund von Nachhaltigkeit). die verwendung der C_RKSign ist speziell nur für diese PKCS11 Bibliothek verfügbar. Sie ist nicht Teil des PKCS11 standards. Sollten Sie mal auf eine andere Karte/PKCS11 Bibliothek wechseln dann müssen Sie diesen Code neu schreiben, da es die Funktionen so nicht gibt.
Allgemeiner wäre es wenn sie selbst den SHA256 Hash rechnen und dann über Standard PKCS11-Funktionen die Signatur auslösen (oder auch direkt über die APDUs).

**Comment by lebail** [comment]
Danke! Ein Umstieg auf APDU ist ohnehin geplant.

Eigentlich wollte ich es von Anfang an per APDU machen, allerdings erschien mir (als Neuling im Bereich der Chipkarten und Signaturen) die vorhandene Dokumentation zu dürftig.

Der fertige Treiber versprach zumindest ein schnelleres erstes Erfolgserlebnis, was natürlich durch den ehemals irreführenden Beispielcode wieder relativiert wurde ...

**Comment by pteufl** [comment]
APDU Bsps werden im Source Code noch folgen. Wenn Sie PKCS11 ohne der speziellen Funktion verwenden sind sie sogar noch allgemeiner unterwegs da sehr viele HSMs etc. PKCS11 als Standard verwenden.
