### ISSUE TITLE
Gesamtrabatt und DEP

### ISSUE THREAD

**Issue by MichaelSchustereder** [a-sit-plus/at-registrierkassen-mustercode#211]
Hallo,

ich habe eine Frage zur Darstellung eines Gesamtrabattes einer Rechnung im DEP. Unter Gesamtrabatt verstehe ich eine Reduzierung des Rechnungsendbetrages (und somit des Zahlbetrages) und nicht einer einzelnen Rechnungsposition.

Aus buchhaltärischer Sicht gibt es die Möglichkeit, da es sich um einen Sofortrabatt handelt, anteilig die einzelnen Erlöse auf den Buchhaltungskonten und somit auch die MWSt-Beträge um den Rabatt zu reduzieren. 

Ein Beispiel:
Artikel        Bruttobetrag     Ust
Testartikel 1       € 50,00     20%
Testartikel 2       € 40,00     10%
Summe € 90.00
-10% Rabatt € -9,00
Rechungsbetrag/Zahlbetrag € 81,00

MWSt-Splittung (Beträge sind anteilig um den Rabatt reduziert)
Netto Ust Steuer Brutto
€ 37,50 20% € 7,50 € 45,00
€ 32,73 10% € 3,27 € 36,00

Bis jetzt war ich der Meinung, dass dies auch für das DEP gilt. Mich verwirrt/verunsichert das Beispiel in den Detailfragen RKSV V1.2 unter 2.5.1 .  Hier kann man interpretieren, dass der Rabatt negativ im "Beleg-Satz-Null" berücksichtigt wird. Falls dies zutrifft, muss dann auch am Beleg die MWSt-Splittung entsprechend dargestellt werden? 

Herzlichen Dank für die Antwort und einen guten Rutsch!

**Comment by ErichFreitag** [comment]
Ganz habe ich ihre Frage nicht verstanden - einerseits, was die Auswirkung auf das DEP betrifft und andererseits die MWSt-Splittung am Beleg, die sie ja selbst schon anführen.

Meine Sicht der Dinge: ein Sofortrabatt wird auch sofort gewährt, wird daher nicht gesondert gebucht und verringert die betreffenden Beträge. Damit wird auch die Umsatzsteuer von den verminderten Beträgen berechnet und entsprechend reduziert in den Steuersätzen angegeben. Der Rabatt kommt dann im 0 %-Steuersatz gar nicht mehr vor, weil er schon in den Beträgen eingerechnet wurde.

Ich vermute, dass "Rabatt" im Prozess 2.5.1 eher Beispielcharakter hat, wie sich negative Barumsätze auswirken können, aber keine Vorgabe darstellt, wie Rabatte generell abzubilden sind.

**Comment by AxelKutschera** [comment]
Aus dem "Rechnungsbetrag/Zahlbetrag" schließe ich, dass bei Ihnen eine Ausgangsrechnung erstellt wurde. Bei Bezahlung dürfte der Betrag zur Gänze im Beleg-Satz-Null erfasst werden. Damit ist kein Aliquotieren erforderlich. 
Beispiele kann ich gerne per Mail senden.
Guten Rutsch!

**Comment by lebail** [comment]
@AxelKutschera: Sehe ich das richtig, dass die genannte Vereinfachung (alles in Betrag-Satz-Null) nur dann gilt, wenn man zu einer bereits elektronisch erstellten Ausgangsrechnung einen eigenständigen Kassenbeleg erstellt? Wenn hingegen der Kassenbeleg selbst die Rechnung (gemäß UStG) darstellt, dann muss man die Beträge meiner Meinung nach sehr wohl aufsplitten (sonst müsste man ja niemals aufsplitten).

**Comment by AxelKutschera** [comment]
Ja, aber so genau ist das nicht definiert, wird aber in dieser Richtung gehen.
Merkmals wird z.B. sein, ob es 
- getrennte Nummern-Kreise für Rechnungen und RKSV-Beleg gibt.
- Rechnungen in einem gesonderten Fakturierungs-Programm (Modul) geschrieben werden.
- Vor der Zahlung übergeben werden.
...

**Comment by MichaelSchustereder** [comment]
Herzlichen Dank für die raschen Rückmeldungen und entschuldigt, meine etwas missverständliche Fragestellung.

In meinem Beispiel handelt es sich um einen normalen Barverkauf an der Kasse und nicht um eine Bezahlung einer Ausgangsrechnung.

@ErichFreitag: ich bin derselben Meinung, dass der Gesamtbetrag aliquot die MWSt Beträge reduziert - wie in meinem Beispiel angeführt. Wenn der "Rabatt" im Prozess 2.5.1 Beispielcharakter hat und keine Vorgabe darstellt, wie Rabatte generell abzubilden sind, dann ist meine Frage damit beantwortet. 

Jedoch kommt dies, meiner Meinung nach, leider nicht eindeutig raus - außer "Rabatt" wird in dem Beispiel in einem abweichenden Kontext verstanden - zB: als Reduktion des Rechnungsbetrages aufgrund einer  Gutschrift.

**Comment by AxelKutschera** [comment]
Bei den Beispielen werden immer wieder verschiedenste Kassentypen zugrunde gelegt. Wie Sie richtig schreiben, werden diese nicht vollständig und daher differenziert interpretierbar formuliert.

Dieses Beispiel könnte aus einer Meinung der KRL 2012 zu Typ2-Kassen (klassische Registrierkassen) entstanden sein. 

Nach Kapitle 5.1.1. soll ein Z-Bon folgenden Inhalt haben:
"... durchgeführte Nach-Stornobuchungen, **Preisnachlässe**, Retouren, Minusumsätze, durch welche der Tagesumsatz gemindert wurde"

Darunter steht dann noch als Meinung des BMF:: 
"zusätzlich bei Kassen mit Bargeldlade:
 rechnerischer Bargeldbestand / Kredit / andere geldwerte Bestände in Schublade
 Anzahl der Nur-Schubladenöffnungen
 Barentnahmen und Bareinlagen"

Rechtlich ableiten lässt sich einer derartige Verpflichtung nicht direkt.
Daher wird es notwendig sein, diese Fragen nicht allgemein sondern - abhängig von den technischen und organisatorischen Maßnahmen der Registrierkasse - im Einzelfall zu entscheiden.

**Comment by MichaelSchustereder** [comment]
@AxelKutschera: Herzlichen Dank für die äußerst rasche und umfassende Antwort!

**Comment by asitplus-pteufl** [comment]
Danke für die Diskussion und die Antworten. Ich möchte dennoch auf den Standard-Text bezüglich org/technischen Themen hinweisen. Die Intention ist nicht, dass wir damit die Diskussion zu solchen Themen unterbinden wollen, aber wir möchten klar klarstellen, dass seitens A-SIT Plus hier keine Antworten kommen werden/können und somit hier keine falschen Erwartungshaltungen in die Beantwortung gesetzt werden.

Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
