### ISSUE TITLE
Stornorechnung.

### ISSUE THREAD

**Issue by texTec** [a-sit-plus/at-registrierkassen-mustercode#212]
Hallo,

Ist eine Stornorechnung die eine Rechnung vor Führung des DEP betrifft zu signieren und in
den Umsatzzähler aufzunehmen ?

Danke.

**Comment by Flanelli** [comment]
Ja - genauso wie die Zahlung  einer Rechnung die vor der Inbetriebnahme der SE  erstellt wurde
aber nach der Inbetriebnahme als geltender Barumsatz vom Kunden an der kassa bezahlt wurde.

**Comment by texTec** [comment]
Ok. Vielen Dank für die Antwort.
