### ISSUE TITLE
Zertifikat für cryptographicMaterialContainer

### ISSUE THREAD

**Issue by NikolausJaeger2001** [a-sit-plus/at-registrierkassen-mustercode#213]
Hallo,
Ich habe Probleme mit der Belegprüfung.
Die Datei cryptographicMaterialContainer habe ich wie folgt angepasst, aber der Wert für "signatureCertificateOrPublicKey" ist mir unklar.
{
  "base64AESKey" : "9Dkvhh6oupcaR2tzKC/ABKsH+mgIcTEVQrIA/EqWdfE=",
  "certificateOrPublicKeyMap" : {
    "51F5CD27" : {
      "id" : "51F5CD27",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : ""
    }
  }
}

Über die Api kann ich den Public Key des Zertifikats auslesen, mit diesem funktioniert die Prüfung aber ebenso wenig wie mit dem Base64 Export des Zertifikats. In letzterem Fall ergibt sich zwischen -----BEGIN CERTIFICATE----- und -----END CERTIFICATE----- ein 1824 Zeichen langer Wert, das erscheint mir im Vergleich zu den Beispielen deutlich zu lang.

Die Prüfung schlägt in allen Punkten fehl, zumindest der Umsatzzähler ist aber korrekt verschlüsselt, da ich die verschlüsselten Werte der Testcases reproduzieren kann.
Deswegen meine Vermutung, das die Datei "cryptographicMaterialContainer" inkorrekt befüllt ist.

Können Sie mir hier witerhelfen?

**Comment by ErichFreitag** [comment]
Das passt schon grundsätzlich, wenn sie das was zwischen "---BEGIN CERTIFICATE---" und "---END---" steht in "signatureCertificateOrPublicKey" eintragen. 

Sie können diesen String auch decodieren und prüfen, was dort enthalten ist, z.B. unter https://certlogik.com/decoder/. Beispielsweise müssen sie die oben angegebene Seriennummer wiederfinden. Was dabei (noch)  sein kann sehen sie unter https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/194.

Wenn sie nicht weiterkommen posten sie bitte ihre Daten, dann kann sich das jemand näher ansehen.

**Comment by areiter** [comment]
Sie haben anscheinend das Zertifikat in PEM Kodierung vorliegen.
Da müssen sie die `----BEGIN CERTIFICATE----- ` und `----END CERTIFICATE----- ` Zeile, sowie alle Zeilenumbrüche im base64 kodierten Zertifikat entfernen und dann in den cryptographicMaterialContainer einfügen.

**Comment by NikolausJaeger2001** [comment]
Vielen Dank für die rasche Antwort. 
Das entfernen der Zeilenumbrüche war die Lösung.
