### ISSUE TITLE
RK Chip - Fehler 500 (A-Trust)

### ISSUE THREAD

**Issue by envomer** [a-sit-plus/at-registrierkassen-mustercode#214]
Wir versuchen schon seit längere Zeit mit der API von A-Trust zu kommunizieren um Rechnungen zu signieren, aber bekommen nur die Fehlermeldung 'HTTP/1.1 500 unspecified error'.

Die Signierung mit den Testaten funktioniert aber sobald wir die URL und die Zugangsdaten fürs Live-System umändern kommt die Fehlermeldung.

Dies ist unser code mit dem wir die Signierung durchführen. Ein aktivierte RK-Chip Karte ist bereits vorhanden.

```php
$url = 'https://www.a-trust.at/asignrkonline/v2/RK0000/Sign/JWS';

$data = array(
    'password' => '123456789',
    'jws_payload' => $payload
);

$options = array(
    'http' => array(
        'header' => "Content-type: application/json\r\n" ,
        'method' => 'POST' ,
        'content' => json_encode($data),
    ),
    'ssl' => array(
        'verify_peer' => false,
    )
);

$context = stream_context_create($options);
$result = file_get_contents($url , false , $context);
```

Code example von A-trust (http://labs.a-trust.at/developer/ShowSource.aspx?id=129):
```php
print "Signatur";
// sign 
$url = 'https://hs-abnahme.a-trust.at/RegistrierkasseMobile/v2/u123456789/Sign/JWS';
$data = '{"password":"123456789","jws_payload":"_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-82_2016-03-11T04:24:46_0,00_0,00_0,00_0,00_0,00_NLoiSHL3bsM=_eee257579b03302f_cg8hNU5ihto="}';
 
$options = array(
    'http' => array(
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => $data,
    ),
);
 
$context  = stream_context_create($options);
$result = file_get_contents($url, false, $context);
var_dump($result);
```

**Comment by lebail** [comment]
Könnte es sein, dass der Benutzername (also das RK0000) falsch ist? RK0000 ist wohl der Benutzername des A-Trust-Webshops, aber nicht der Benutzername des darin bestellten Produktes a.sign RK ONLINE. Die Benutzernamen von a.sign RK ONLINE haben die Form u000000000 (zumindest sieht meiner so aus).

**Comment by envomer** [comment]
@lebail RK0000 ist nur ein Beispiel gewesen.

Bitten korrigieren Sie mich falls ich falsch liege: Soweit ich das verstehe werden unsere Partnerdaten Zugänge (bsp: RK1234)
verwendet um Rechnung der Endkunden über unser Partnerkonto zu signieren.

Dabei wird die Live-System URL (https://www.a-trust.at/asignrkonline/v2/) benutzt.

Dies hier ist ein Screenshot von der a.sign RK MOBILE Developer Manual:
<img width="779" alt="screenshot 2017-01-04 18 27 19" src="https://cloud.githubusercontent.com/assets/5601749/21652186/feefcde6-d2ab-11e6-8c1c-df5bc4e06dc0.png">

**Comment by lebail** [comment]
Der Partner-Benutzername (im Testsystem-Beispiel "partner4711") wird benötigt, um neue Endbenutzer-Konten anzulegen - das geht sowohl per Webshop als auch über das Webservice. Man muss dazu erst im Webshop einen "Credit" für das Produkt "a.sign RK ONLINE" gekauft haben.

Die auf diese Weise angelegeten Konten erhalten einen Benutzernamen der Form "u000000000" (in obigem Testbeispiel "u123456789") und ein zugehöriges Passwort (im Beispiel "123456789"). Erst diese Benutzerdaten dienen dann zum Signieren.

Mit dem Partner-Benutzernamen selbst kann man nicht signieren.

**Comment by envomer** [comment]
@lebail verstehe und danke für die schnellen Antworten.

Dann habe ich das wohl falsch verstanden.
Ok, sobald ich mit dem Partnerzugang einen Endbenutzer-Konto angelegt habe, kann ich Rechnungen signieren. Muss ich dann für jeden meiner Kunden jetzt ein Endbenutzer-Konto anlegen oder kann ich ein Konto für mehrere Kunden benutzen?

**Comment by Phoniexk** [comment]
@envomer ja natürlich benötigt jeder Kunde ein EIGENES Endbenutzer-Konto. **Das Endkunden-Konto muss ja bei A-Trust auf die Steuernummer Ihrer Kunden registriert werden**. Ich hoffe Sie haben die Endkunden-Kontos nicht auf Ihre eigene Firmen-Steuernummer registriert. 

Es kann ja auch nicht anders funktionieren. Ansonsten würden ja alle Ihre Kunden mit der selben Signatur signieren. Außerdem wird Ihnen (bzw. dem Kunden) FinanzOnline auch Rückmelden dass für diesen Kunden keine Signatur beim VDA hinterlegt ist. Sprich Ihre Kunden können die Registrierkasse nicht im FinanzOnline melden.

Einfach die Vorträge/Dokumente von A-Trust genau durchlesen und auch die Dokumentation zum FON-Webservice, dann sollten sich Ihre Fehler beheben lassen.

**Comment by AxelKutschera** [comment]
Wer sich die Programmierung des Prozesses ersparen möchte - wir haben die Einbindung sowohl der RK-Online als auch des RK-Chip in einer Registrierkassen-Konfiguration in unserem https://portal.fiskaltrust.at über eine Web-Oberfläche automatisiert. 
Diese Funktion ist kostenlos verwendbar.

**Comment by envomer** [comment]
@Phoniexk Danke für die rasche und detaillierte Antwort.
Wir werden unseren Code jetzt anpassen.

@AxelKutschera Danke fuer den Link. Werden wir uns auch anschauen.

**Comment by envomer** [comment]
@AxelKutschera Wir haben uns bei Ihrem Service registriert aber bekamen bei jedem anmelde Versuch  eine 500 Fehlermeldung. Können Sie uns da weiterhelfen?

**Comment by AxelKutschera** [comment]
@envomer - da es bei uns um 17:00 und jetzt funktioniert würde ich vorschlagen, dass Sie mich am Handy anrufen. https://www.fiskaltrust.at/impressum/
