### ISSUE TITLE
Startbeleg wird im Prüftool als Null-Beleg erkannt

### ISSUE THREAD

**Issue by NikolausJaeger2001** [a-sit-plus/at-registrierkassen-mustercode#216]
Hallo,
der Startbeleg unserer Software wird im Testtool als Null-Beleg erkannt, weswegen die DEP-Prüfung mangels Startbelegs fehlschlägt.
Im Log wird angegeben, das für die Verkettung nicht die KassenID verwendet wurde, was jedoch nicht so ist. Der Vorgang ist lt. Spezifikation der Selbe wie für Standard-Belege, mit dem Unterschied das die KassenId als Basis genommen wird. Die Standard-Belege weisen im Testtool keine Fehler auf.

**Das ist der Output des Testtools zum Startbeleg:**
[ {
  "verificationId" : "RKSV_DEP_EXPORT",
  "version" : 1,
  "verificationName" : "RKSV-DEP-Export Prüfung",
  "verificationTextualDescription" : "Es wird die Richtigkeit des exportierten RKSV-DEP überprüft: Abfolge der Belege, Entwicklung des verschlüsselten Umsatzzählers, Verkettung der Belege.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Am Beginn des exportierten RKSV-DEP befindet sich kein gültiger Startbeleg.",
  "input" : {
    "RK_SUITE_ID" : "R1",
    "TYPE_RECEIPT" : "NULL_BELEG",
    "CASHBOX_ID" : "TT-0-1",
    "DECRYPTED_TURNOVER_VALUE" : "0",
    "SIGNED_PREV" : "NULL",
    "SYSTEM_TYPE_INITIAL" : "OPEN",
    "TURNOVER_SUM" : "0",
    "CASHBOX_ID_INITIAL" : "TT-0-1",
    "SYSTEM_TYPE" : "OPEN",
    "RECEIPT" : "_R1-AT1_TT-0-1_1_2017-01-04T06:12:18_0,00_0,00_0,00_0,00_0,00_J0awlPb0RZo=_51F5CD27_PH9U9KhZzs0=_qs/BwY0dU1xGQ8oXx6xAfVqHlf3oykC50YPApuzvNCZiduk9EO3LOxywh0w2RzWp5VVQtiecMpMlZO9AJ3Wd0A==",
    "TYPE_RECEIPT_PREV" : "NULL",
    "KNOWN_RECEIPT_IDS" : "NULL",
    "SIGNED_PENULT" : "NULL",
    "RECEIPT_PREV" : "NULL"
  },
  "verificationTimestamp" : "2017-01-05T21:58:42.129+01:00",
  "verificationResultList" : [ {
    "verificationId" : "DEP_STATE",
    "version" : 1,
    "verificationName" : "Abfolge der Belege",
    "verificationTextualDescription" : "In diesem Modul wird überprüft, ob die Abfolge der Belege im exportierten RKSV-DEP korrekt ist: Position des Startbeleges, Position des Sammelbeleges nach dem Ausfall der Signatureinrichtung.",
    "verificationState" : "FAIL",
    "verificationResultDetailedMessage" : "Am Beginn des exportierten RKSV-DEP befindet sich kein gültiger Startbeleg.",
    "input" : {
      "TYPE_RECEIPT_PREV" : "NULL",
      "TYPE_RECEIPT" : "NULL_BELEG",
      "SIGNED_PREV" : "NULL",
      "SIGNED_PENULT" : "NULL"
    },
    "verificationTimestamp" : "2017-01-05T21:58:42.130+01:00"
  } ]
} ]

Habe Sie einen Anzatz wo die Ursache des Problems liegen könnte?

**Comment by areiter** [comment]
Ich bekomme für die KassenID `TT-0-1` einen Verkettungswert für den Startbeleg von `2ZyMgp8vtbc=`
Das deckt sich nicht mit ihrem Verkettungswert von `PH9U9KhZzs0=`

Ich denke also dass da beim Erstellen des Verkettungswertes für den Startbeleg etwas schief geht

**Comment by NikolausJaeger2001** [comment]
Hallo, danke für die Antwort.
Ich erstelle die Verkettung für den Startbeleg folgendermaßen:
- KasseID im UTF8 Format
- Diesem String signiere ich und codiere die ersten 8 Byte im Base64 Format.

Nachdem Sie mir als Antwort geschrieben haben, das der Wert bei Ihnen 2ZyMgp8vtbc= ergibt ist das sicherlich falsch, da ich mit der Signierung jedes mal einen anderen Wert erhalte.

Ich habe mir den at-registrierkassen-mustercode durchgesehen, komme aber nicht dahinter wo der Denkfehler liegt.

**Comment by areiter** [comment]
Der erste Schritt passt. KassenID in utf8.
Danach muss der SHA256 Hashwert davon gebildet werden und die ersten 8Byte base64 kodiert.

Das ergibt den Verkettungswert für den ersten Beleg.

**Comment by ckvsoft** [comment]
Nicht signieren, sondern sha256 verschlüsseln

**Comment by NikolausJaeger2001** [comment]
Hallo,
sollte das dann nicht die selbe Funktion sein, die auch bei der Verschlüsselung des Umsatzzählers zum Einsatz kommt?
Mit dieser komme ich aber nicht auf den korrekten output.

**Comment by areiter** [comment]
Der Verkettungswert für den Startbeleg hat mit Verschlüsselung nichts zu tun.
In der Detailspezifikation ist dies genau definiert:

> ...Für die Erfassung des ersten Barumsatzes wird der Wert des Felds „Kassen-ID“ als Input dieser Hash-Funktion verwendet. Aus dem Ergebnis der Hash-Funktion werden startend mit Byte 0, N Bytes extrahiert und BASE-64-kodiert. Die Anzahl der zu extrahierenden Bytes (N) wird ebenfalls über das Registrierkassenalgorithmuskennzeichen definiert. Durch den Einsatz von Zugriffsteuerungsmethoden muss garantiert sein, dass auch bei der parallelen Abarbeitung der Belegerstellung die Verkettung über die Signaturwerte korrekt abgebildet wird.
> 

```

**Comment by NikolausJaeger2001** [comment]
Hallo,
der sah256 hash für die KasseId "TT-0-1" ergibt "d99c8c829f2fb5b7bb90523f634155c1316ecef91fb3c0107540a354bf377b61"
davon als ByteArray die ersten 8 Bytes:
(0) = 100
(1) = 0
(2) = 57
(4) = 57
(5) = 0
(6) = 99
(7) = 0
Diese ergeben aber Base64 codiert den Wert: "ZAA5ADkAYwA="

Wo liegt hier der Fehler?

**Comment by areiter** [comment]
Ich kann ihren Ausführungen leider nicht folgen.
Der von ihnen berechnete Hash stimmt, unter der Annahme dass es sich dabei um eine Hex-Darstellung des Hashwertes handelt, wobei jeweils zwei Zeichen ein byte darstellen.

Die ersten 8 Byte des Hashes sind also (wieder in hex Darstellung): `d99c8c829f2fb5b7`
Oder so wie sie es in Dezimaldarstellung angegeben haben:

> (0) = 217
(1) = 156
(2) = 140
(3) = 130
(4) = 159
(5) = 47
(6) = 181
(7) = 183

Und diese Werte base64 kodiert ergeben nunmal `2ZyMgp8vtbc=`

**Comment by NikolausJaeger2001** [comment]
Danke für die Hilfestellung!
