### ISSUE TITLE
ZDA-ID und Zertifikatseriennummer bei ausgefallener Signatureinheit/en

### ISSUE THREAD

**Issue by mrpipe** [a-sit-plus/at-registrierkassen-mustercode#218]
Welche ZDA-ID und Zertifikatseriennummer sind im MachineCodeRepOfReceipt bei ausgefallener Signatureinheit/en zu verwenden. In diesem Falle steht ja die Signatureinheit/en nicht zur Verfügung.
Dadurch können die Daten auch nicht abgerufen bzw. zugeordnet werden. Soll hier z.B. die ZDA-ID und Zertifikatseriennummer der letzten erfolgreichen Signierung verwendet werden?

**Comment by ErichFreitag** [comment]
Ja, die letzte - siehe https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/103 und andere.

**Comment by mrpipe** [comment]
Danke für die Info.
