### ISSUE TITLE
Frage zu Nuller-Belegen

### ISSUE THREAD

**Issue by norbert2** [a-sit-plus/at-registrierkassen-mustercode#219]
Für die konkrete Frage muss ich leider etwas weiter ausholen.
Ein Kunde von mir setzt eine seit nun schon Jahrzehnten bewährte DOS-Kassa mit integrierter Warenwirtschaft (Clipper, DBase) ein.
Der RKSV-Einbau in dem alten Programm war nicht mehr vernünftig möglich.
Es wurde jedoch eine Schnittstelle eingebaut, mit der jeder Beleg an das neue Signierungsprogramm übergeben wird (VB6, SQL-Datenbank)
Jeder Beleg scheint nun wie bisher im alten DOS-Programm UND in der Datenbank des Signierungsprogramms.
Hier die Frage zu den 0-er-Belegen:
Die 0-er-Belege möchte ich NUR vom alten DOS-Programm angestoßen und NUR in der neuen Datenbank mit DEP speichern - mit einem eigenen Nummernkreis für diese 0-er-Belege. Das alte System wird also nicht mit den 0-er-Belegen "belastet". Interessiert den Kunden dort nicht.
Im neuen SE-System sind dann ALLE Belege gespeichert. Sowieso im DEP und auch in einer Tabelle, in der jede Belegzeile (also mit Artikel, Preis, Menge usw.) enthalten ist.
Ist es also zulässig, dass im alten Kassensystem die 0-er-Belege nicht aufscheinen?

**Comment by ErichFreitag** [comment]
Ich denke, das ist grundsätzlich zulässig. Schauen wir uns die einzelnen Belege an:

Startbeleg - dient zur Inbetriebnahme der Kasse, hat wohl im alten System keinen Bezug.

Monats- und Jahresbelege - dienen zum jeweiligen Abschluss eines Monats sowie zum Abschluss des DEP etc. Ein Fall, den sie betrachten sollten ist, wie der Monatsabschluss im alten System mit dem Monatsbeleg im neuen System zusammenpasst.

Kontrollbeleg - dient zur Prüfung der Registrierkasse, hat im alten System keinen Bezug.

Schlussbeleg - dient zur Außerbetriebnahme der Kasse, hat wohl im alten System keinen Bezug.

Sammelbeleg - dient zur Kennzeichnung von Ausfällen der Sicherheitseinrichtung, hat im alten System keinen Bezug. Den müssen sie wohl auch vom neuen System her anstossen.

Außer eventuell bei den Monats-/Jahresbelegen sehe ich keine diesbezüglichen Hindernisse. Bei Startbeleg, Kontrollbeleg und Schlussbeleg ist die Frage, wie und wo sie die auslösen wollen (Alt- oder Neusystem). Sie müssen ja auch einen Kontroll-Nullbeleg (oder einen Null-Umsatz) generieren können.

Eigene Nummernkreise sind grundsätzlich zulässig, wenn sie einer nachvollziehbaren Systematik folgen.

**Comment by norbert2** [comment]
Danke für die rasche und ausführliche Antwort.
Ich werde wohl alle Nuller-Belege von der alten Kassa anstoßen lassen. 
Da ist die einfache Erstellung dieser Belege wichtig. Mit Drücken von zwei F-Tasten ist die Sache erledigt.
Beim Signierungsprogramm werden die Belegnummern für die 0-er-Belege fortlaufend automatisch nummeriert. Eigener Kreis eben auch deshalb, damit im normalen Nummernkreis nicht zu erklärende Lücken entstehen.
Die Koordinierung zwischen bestehendem Kassensystem und Signierungsprogramm bezüglich der Monats- und Jahresbelege wird organisatorisch und programmtechnisch lösbar sein.

**Comment by ErichFreitag** [comment]
Den Sammelbeleg müssen sie vermutlich sinnvollerweise im neuen System erzeugen, weil sie nur (?) dort wissen, wann Beginn und Ende des Ausfalls der Signaturerstellungseinheit war. Den händisch zu erzeugen ist wohl nicht zumutbar.

Der Rest klingt OK.
