### ISSUE TITLE
unsigned char (byte)

### ISSUE THREAD

**Issue by ckvsoft** [a-sit-plus/at-registrierkassen-mustercode#22]
Ich hätte da eine Frage zum Handling mit unsigned und signed.
In Java sind ja Bytes signed, in C# und C++ allerdings unsigned.
Bei der Erstellung einses Hashes  des IV (Initialisation Vector) sind hier unterschiede. Wie ist damit umzugehen?

mfg Christian

**Comment by areiter** [comment]
Die dezimale Darstellung ist irrelevant für die Berechnung des Hashwertes.

Ein Beispiel aus Java

```
byte[] b = new byte[] { (byte)10, (byte)20, (byte)30, (byte)150, (byte)160, (byte)200 };
//Alternativ auch: byte[] b = new byte[] { (byte)10, (byte)20, (byte)30, (byte)150, (byte)160, (byte)-56 };
MessageDigest sha1 = MessageDigest.getInstance("SHA1");
System.out.println(Hex.encodeHexString(sha1.digest(b)));
//42b6416abd557545f067755ff5f8fd566659de6e
```
Liefert den selben Hashwert wie C#:
```
byte[] b = new byte[] { (byte)10, (byte)20, (byte)30, (byte)150, (byte)160, (byte)200 };
Console.WriteLine(BitConverter.ToString(SHA1.Create().ComputeHash(b)));
//42-B6-41-6A-BD-55-75-45-F0-67-75-5F-F5-F8-FD-56-66-59-DE-6E
```

**Comment by ckvsoft** [comment]
Ok, Danke für die rasche Antwort. Ist wahr, sorry ;-)
