### ISSUE TITLE
Umsatzzähler bei nicht Barumsätzen

### ISSUE THREAD

**Issue by NikolausJaeger2001** [a-sit-plus/at-registrierkassen-mustercode#221]
Hallo,
Ich habe eine Detailfrage zu nicht Barumsätzen.
Wir signieren alle in der Kasse erstellten Belege, unabhängig davon ob diese Bar oder zb. mit Erlagschein bezahlt werden.
Diese Belege dürfen soweit ich das verstanden habe den Umsatzzähler nicht erhöhen.
Müssen in diesem Fall die Steuersummen wie bei einem Null-Beleg auf 0 gesetzt werden?

Vielen Dank im vorraus.

**Comment by ErichFreitag** [comment]
a) wenn sie etwas signieren dann verändert das auch den Umsatzzähler

b) der Umsatzzähler zählt nicht "den Umsatz" - das ist ein Teil der Sicherheitseinrichtung

c) Nicht-Barumsätze sind im 0%-Steuersatz, aber mit deren Wert einzutragen

**Comment by Flanelli** [comment]
@ErichFreitag 
Ich möchte keineswegs anmaßend erscheinen aber zur Klarheit erlaube ich mir denoch zu behaupten dass
zu a) Nullbelege die signiert werden müssen ( z.b. Sammelbeleg, Jahresbeleg ) den Umsatzzähler nicht verändern ( können )

**Comment by ErichFreitag** [comment]
Passt schon, @Flanelli. 

Und um ganz genau zu sein - der verschlüsselte Umsatzzähler ändert sich demnach doch. :-) (der Wert des Summenspeichers bei Nullbelegen natürlich nicht).

**Comment by Flanelli** [comment]
Aufrichtiges Kompliment @ErichFreitag 
Ihre Kompetenz bis ins allerletzte Detail  ist und bleibt einfach unübertoffen :-)

**Comment by ErichFreitag** [comment]
Jeder hat hier und anderswo seine spezifischen Kompetenzen.
Den Rest lass ich so stehen. Danke!

**Comment by NikolausJaeger2001** [comment]
Vielen Dank für die kompetenten Antworten.
