### ISSUE TITLE
Startbeleg Überprüfung

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#222]
Habe meine Kasse Initialisiert, beim BMF (im Testmodus) die SE und die Kasse registriert. Die Übeprüfung des Startbeleges wird über WebService mit folgender Fehlermeldung abgelehnt:
cvc-pattern-valid: Value '......... maschinen lesbarer code......' is not facet-valid with respect to pattern '(_[^_]+){13}' for type '#AnonType_beleg'.

Auch nach der Code Überprüfung und Suche im Web kann ich den Fehler nicht erklären.
Beim Überprüfen des DEP Eintrages mittels Prüftool habe ich folgende Ergebnise:
- 0000_app.json => alles auf PASS
- 0000_cashbox.json => alles auf PASS
- 0000_dep.json => alles auf PASS
- dep.json => alles auf PASS
- 0000_cashbox_full.json => alles auf PASS bis auf folgende Zeilen:

1)
"verificationId" : "RECEIPT_FULL",
"verificationState" : "FAIL",

2)
"verificationId" : "STATE_CONSOLIDATED",
"verificationState" : "FAIL",
"verificationId" : "STATE_CASHBOX",
"verificationState" : "FAIL",

Hat jemand vielleicht die Idee was das Problem beim diesem Beleg sein könnte? 
Vielen Dank für die Bemühungen

**Comment by AlgoLinz** [comment]
Das Problem mit WebService Fehlermeldung: 
"cvc-pattern-valid: Value '......... maschinen lesbarer code......' is not facet-valid with respect to pattern '([^]+){13}' for type '#AnonType_beleg'."

habe ich gefunden und behoben (es lag am übergebenem und in diesem Fall fehlerhaften maschinenlesbaren code).

Wurde aber gerne wissen was die oben genannten FAIL states vom Prüftool bedeuten. Kann mir das jemand vielleicht erklären. 

Danke.

**Comment by Flanelli** [comment]
@AlgoLinz 
Eine wirklich eindeutige und restlos alle Unsicherheitsbedenken beeseitigende Erklärung kann wohl nur Herr. Dr. Teufl abgeben. Nach den disherigen diversen Postings íst ja davon auszugehen dass man das "FAIL" in den beiden von Ihnen angeführten  Abschnitten ignorieren kann soferne alles anderen Abschnitte ein "PASS" aufweisen ( Ausgenommen natürlich die logischerweise nicht zutreffenden unterscheidlichen Belegtypen in den Abschnitten "TYPE_OF_RECEIPT_........"
Es wäre allerdings doch sehr vorteilhaft wenn eine, alles Unsicherheiten wiklich ausräumende und verbindlichr Erklärung dazu abgegeben wird denn es ist letzendlich doch sehr befremdlich wenn ein Prüftool und in diesem Falle ja ein behördlich empfohlenes und doch abgesegnetes Prüfwerkzeug dem Anwender die Interpretation überläßt bzw. der Tenor lautet "Das kann man ingorieren wenn ...."
Die Erkenntnis es könnte doch ein tatsächlicher Fehler im Startbeleg sein ist zum Zeitpunkt der Prüfung durch die BMF-APP dann wohl mehr als unangenehm.

**Comment by AlgoLinz** [comment]
Hallo Flanelli,

vielen Dank für die Antwort. Ich lasse den Ticket noch ein paar Tage offen, vielleicht kann uns Herr Dr. Teufl etwas mehr dazu sagen.

Eine klare Antwort wäre natürlich hilfreich.

Mit freundlichen Grüßen

**Comment by asitplus-pteufl** [comment]
Es gibt noch einen Fehler im Prüftool (known Issue): Beim ersten Beleg werden noch zwei Ergebnisse (die die Sie oben nennen) abgelegt. Eines davon ist FAIL, eines davon ist PASS. Wenn eines PASS ist, passt alles, bzw. bekommen Sie ganz oben das PASS raus, das ist der wichtigste Indikator. Der Fehler wird in der nächsten Version behoben
