### ISSUE TITLE
Die kryptographische Gültigkeit der Signatur ist nicht gegeben.

### ISSUE THREAD

**Issue by JoKump** [a-sit-plus/at-registrierkassen-mustercode#224]
Hallo!
Auch nach Lesen der zu diesem Thema existierenden Beiträge habe ich den Fehler noch nicht gefunden und hoffe auf den zündenden Input hier.
Zur Ausgangslage: In meiner RK-Software (.Net, c#) verwende ich RK Online von a-trust, von dort habe ich die Informationen zum Zertifikat bekommen (siehe CMC). Den zu signierenden Wert denke ich richtig erstellt zu haben, bitte jedoch um Korrektur, falls nicht.
Das Prüftool (1.0.0) liefert mir eben diesen Fehler. Ich bin kein Spezialist für Signierung, darum stehe ich ein wenig "daneben".
Vielen Dank schon im Voraus!
Johannes Kump

[check_startbeleg.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/693340/check_startbeleg.zip)

**Comment by ErichFreitag** [comment]
Unmittelbar sehe ich keinen Fehler, außer das die Signatur nicht gültig ist.

Sie können wohl oder übel nur die Schritte einzeln überprüfen, siehe https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf sowie den Ablauf unten.

![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/21766443/e777c8f0-d66e-11e6-80cd-2f831cf386eb.jpg)

**Comment by ckvsoft** [comment]
Ich würde sagen das der Hashwert der KassenID nicht die ersten 8 Bytes sind.

**Comment by areiter** [comment]
Die Länge ihrer Signatur scheint mir nicht zu passen. Sie sollte 64 byte haben, hat bei ihnen aber 84.
Base64 decodiert man die Signatur `VWhsQTdsY2tsYlNhc19DdlhfMTM5TlhNS3VVSmVrMkE0cTJRVWN0X3JQb2NtZHZqVlFnVnV1WXk1d0pLNjVUemZ1MnBTdHpaZ1J6YTNWMjZwQ29qT3c=`

Kommt wieder folgendes Base64URL codierte raus (Nach UTF8 Decodierung).
`UhlA7lcklbSas_CvX_139NXMKuUJek2A4q2QUct_rPocmdvjVQgVuuYy5wJK65Tzfu2pStzZgRza3V26pCojOw`

Base64URL dekodiert man das nun kommt eine 64 Byte lange signatur raus. Ich nehme also an dass sie die Signatur einfach zweimal base64 kodiert haben (1x Base64URL codiert, einmal Base64 codiert).

**Comment by JoKump** [comment]
Vielen Dank für die raschen Antworten!
Nachdem ich das a-Trust-Dokument noch einmal genauer unter die Lupe genommen habe, hat der Hinweis von @areiter sehr weitergeholfen!
Wie so oft ist das Problem vor dem Computer gewesen! ;)
Das Ergebnis der Signatur ist bereits Base64Url kodiert und ich habe in meinem Code einmal zuviel kodiert. Nach Korrektur des Codes ergibt die Prüfung mit dem Tool "PASS"! YAY!
Vielen Dank noch einmal!
Mit den besten Grüßen
Johannes Kump
