### ISSUE TITLE
WebService - Beleg Überprüfung

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#226]
Hallo,

habe einen WebService Konto im FON angelegt, die ChipKarte (A-Trust) mit meinem UID  aktiviert. Die Signatureinheit und auch die Registrierkasse wurden über WebService im TEST-Modus angemeldet (art_uebermittlung = 'T').

Die Signatureinheit und die Registrierkasse scheinen im FON nicht auf (möglicherweise wegen dem Testmodus) und die Überprüfung des Startbeleges mittels WebService und auch mit BMF-Belegcheck-App werden mit folgender Fehlermeldung abgeleht:

"Der vorliegende Beleg kann nicht geprüft werden, da er von einer nicht zu Ihrem Unternehmen registrierten Registrierkasse ausgestellt wurde oder die Registrierung über FinanzOnline unvollständig ist bzw. mit den Daten im maschinenlesbaren Code differiert. Bundesministerium für Finanzen."

Kann man die Belege im Testmodus nicht überprüfen oder habe ich etwas übersehen? (Prüftool liefert ein OK für den gleichen Beleg)

**Comment by Phoniexk** [comment]
Hallo,

Auch bei uns tritt dieses Problem bei der Prüfung mittels Webservice auf. Wir haben ebenfalls für unseren Firmen-FinanzOnline-Account einen RK-Webservice-Benutzer angelegt. Zertifikat (ATrust RK Online) und Kassa wurden im Testmodus via Webservice angemeldet. Scheinen im LOG auch als angemeldet im Testmodus auf.

Das Prüftool meldet für den Startbeleg (sowohl für DEP als auch für "qr-code-rep") jeweils PASS.

Laut Dokumentation zum Webservice soll man für Testübertragungen "AT9" verwenden, da ja kein gültiges Zertifikat beim VDA regstriert ist. Unten angefügt sind meine Daten für das Prüftool, sowie die Ergebnisse des Prüftools (Einmal für AT1 und einmal für AT9).

[prueftool_at9.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/697474/prueftool_at9.zip)
[prueftool_at1.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/697475/prueftool_at1.zip)

Dem FON-Webservice wurden für die Belegprüfung jeweils die Daten aus der Datei "qr-code-rep.json" (d.h. UTF-8 kodierte Zeichenkette, die den maschinenlesbaren Code für die Belegprüfung entsprechend der in Z 12 der Anlage zur Registrierkassensicherheitsverordnung festgelegten Codierung enthält) übergeben, gemäß dem Beispiel https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/Muster_Belegpruefung.xml?5n755k

Als Rückmeldung erhält man vom FON-Webservice folgende Fehlermeldung:

[Beleg_126055.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/697490/Beleg_126055.txt)

Ich kann diese Fehlermeldung überhaupt nicht verstehen. Wie soll aus dem Beleg erkannt werden, welches Unternehmen den Beleg ausgestellt hat???

In der näheren Erklärung ist ja angeführt:

> Das Ergebnis sagt aus ob das angemeldete Unternehmen berechtigt ist den vorliegenden Beleg zu prüfen.

Ich werde ja meinen eigenen Beleg prüfen dürfen!?! Ich konnte auch keine entsprechende Freigabemöglichkeit im FinanzOnline finden.

Hat jemand damit Erfahrung? Tritt des Problem eventuell nur bei Testübermittlungen auf und im "Live-System" würde die Belegprüfung funktionieren?

**Comment by AlgoLinz** [comment]
Die Signatureinheit habe ich jetzt nocheinmal registriert (WebService) und dieses mal unter Anwendung von HEX-Seriennummer. Die Übeprüfung des Beleges klapte dann. Bis jetzt meldete ich die Signatureinheit unter Anwendung der Seriennummer in der dezimalen Darstellung. Es wäre sehr komisch und beunruhigend wenn das an der decimalen Darstellung der Seriennummer gelegen wäre.  

Die Übeprüfung der QR-Codes mit BMF-App funktioniert nach wie vor nicht. Die Fehlermeldung ist gleich geblieben (siehe oben) obwohl maschinen lesbarer code in beiden Fällen identisch ist.

**Comment by Phoniexk** [comment]
Seltsam, ich habe die Signatureinheit aber defintiv als HEX-Seriennummer registriert. Trotzdem bekomme ich diese Fehlermeldung...

**Comment by asitplus-pteufl** [comment]
A-SIT Plus kann im Allgemeinen keine Fragen zum FinOnline WebService beantworten. Bitte die Anfrage an das BMF stellen.

Es muss auf jedem Fall im Beleg immer die HEX-Darstellung verwendet werden. In FinOnline und dem Web-Service kann auch beides verwendet werden.

**Comment by Phoniexk** [comment]
Laut Hotline von FinanzOnline kann mir bei diesem Problem nicht geholfen werden. Ich sollte mich bei A-Trust melden. Ich habe versucht an der Hotline zu Erklären dass es sich nur um Test-Zertifikate handelt und A-Trust diesbezüglich sicherlich keinen Support geben kann. Zumal die Fehlermeldung ja eindeutig ein Berechtigungsproblem im FinanzOnline darstellt.

Bei der Hotline konnte mir niemand helfen, da diesbezüglich keine Erfahrung vorliegt.

Ehrlich gesagt weiß ich jetzt nicht, wer mir noch helfen kann!? ATrust wird mir bei einem Fehler im FinanzOnline keine Hilfe geben können, macht auch keinen Sinn.

**Comment by ErichFreitag** [comment]
Sie schreiben oben, dass sie ein Zertifikat registriert haben, dann aber AT9 verwenden. Ohne es genau sagen zu können: das widerspricht sich meiner Meinung nach. AT9 ist denke ich unabhängig von Produktiv- oder Testübermittlungen und sagt nur, dass sie noch kein Zertifikat haben. Wenn sie schon eines hinterlegt haben, können sie ja mal dieses verwenden?

**Comment by Phoniexk** [comment]
Wie gesagt Zertifikat und Kassa (ID & AES) sind im FON im Testmodus angemeldet. Laut Webservice-Beschreibung soll für Testübermittlungen "AT9" verwendet werden. Wie beschrieben haben wir beim Startbeleg sowohl "AT1" als auch "AT9" versucht, es führt beides mal zur genannten Meldung im FON.

Ein echtes Zertifikat haben wir nicht hinterlegt. Für uns selbst besteht keine Registrierkassenpflicht, wir programmieren nur das Webservice für unsere Kunden.

**Comment by asitplus-pteufl** [comment]
Wenn Sie kein Zertifikat im FinOnline registriert haben (über WebService oder manuell), dann kann die Prüfung nicht funktionieren. Es kann ja zu Ihrer Seriennummer im Beleg kein Zertifikat gefunden werden (und damit kein Unternehmen etc.). Bitte ebenso nochmal prüfen: Die Seriennummer in Ihrem Beleg schaut nach Dez. Kodierung aus (außer es ist zufällig eine Hex Zahl mit Ziffern < A). Im Beleg muss Hex verwendet werden (siehe Detailfragen)

**Comment by Phoniexk** [comment]
Vielleicht habe ich gerade einen Denkfehler aber im Ordner "input" in der Datei "qr-code-rep.json" hat die Seriennummer den Wert "2F03C7EF". Ich habe mir extra nochmal die hochgeladenen Dateien angeschaut.

Naja aber wie kann ich dann das Webservice testen, wenn ich gültiges Zertifikat registrieren muss. Ich möcht es ja nur testen, damit bei der Installation beim Endkunden keine Fehler auftretten. Sprich für reine Testzwecke gibt es kein echtes Zertifikat, sondern nur Testzertifikate die im Testmodus angemeldet sind.

Oder ist das Testweise übermitteln nur mit einem echten Zertifikat möglich? Dann müsste ich nämlich schon ein Zertifikat und eine Kassen-ID bei einem Endkunden registrieren, obwohl dort noch keine Registrierkasse mit den Anforderungen für 01.04.2017 in Betrieb ist. Wie gesagt wir programmieren die Funktionen erst bei uns intern in der Firma und selbst haben wir keine Registrierkassenpflicht -> d.h. das Anmelden und Kaufen von Zertifikaten wäre dann ausschließlich dass wir den Startbeleg Testweise übermitteln können, damit wir wissen ob das Webservice funktioniert.

**Comment by Phoniexk** [comment]
Jetzt haben wir auf unser Unternehmen ein echtes Zertifikat bei A-Trust angemeldet und das Zertifikat sowie auch die Registrierkasse im FinanzOnline im Produktivsystem angemeldet. Sprich Zertifikat + Registrierkasse scheinen im FON als "registriert" auf.

Auch danach war es nicht möglich im Testmodus den Startbeleg zu senden. Deshalb haben wir den Startbeleg ebenfalls im Produktivsystem übermittelt. Jetzt war die Prüfung des Startbeleges möglich, dieser war auch fehlerfrei und die Registrierkasse ist jetzt korrekt in Betrieb genommen.

Nachdem es sich ja nur um einen Test handelte, mussten wir jetzt anschließend die Registrierkasse wieder außer Betrieb nehmen. Da ja auch das Zertifikat nur für Testzwecke benötigt wurde, haben wir dieses ebenfalls wieder außer Betrieb genommen. Das Zertifikat ist halt jetzt auch umsonst angemeldet, weil es ja in weiterer Folge nicht benötigt wird, aber die Zertifikate kosten ja nicht die Welt.

Scheinbar ist es nicht möglich im Testverfahren via Webservice eine vollständige Inbetriennahme durchzuführen, lässt sich nur mit "Live" - Daten durchführen.

**Comment by asitplus-pteufl** [comment]
Meine Antwort in Bezug auf die Seriennummer davor war etwas zu schnell (ich vermute dass es da eine Verwechslung mit einem anderen Issue gab), sorry für die Umstände.

Bezüglich Web Service, ich kann das als A-SIT Plus nicht beantworten, werde diesen Thread an das BMF weiterleiten.

**Comment by AlgoLinz** [comment]
@Phoniexk, eine vollständige Inbetriebnahme im Testmodus ist möglich.

Ich habe über WebService (art_uebermittlung = 'T' + AT1) meine Signatureinheit (Chipkarte auf das Unternehmen aktiviert) und die Reg-Kasse registrieren können. 

Nach Anfangsschwierigkeiten (siehe oben) habe den Startbeleg erfolgreich prüfen können (WebService).
Nur die Übeprüfung des Startbeleges mit BMF-App funktioniert nicht. Die Prüfung wird mit der gleichen Fehlermeldung wie bei dir abgelehnt.

Kann ich den Issue schliessen?

**Comment by Phoniexk** [comment]
Ok ja bei mir war es wie gesagt im Testmodus in keiner konstellation möglich.

Bei der BMF-App kann ich mir eine Fehlermeldung durchaus vorstellen. Beim Webservice kann man ja unterscheiden zwischen Test- oder Produktivsystem. Mit der BMF-App kann man ja keinen Testbeleg übermitteln, d.h. Zertifikat+Reg-Kassa im Testmodus wird die BMF-App nicht erkennen, da Testmodus nur für Webservice gilt.

Von mir aus kann es geschlossen werden, dass es im Produktivsystem funktionieren würde, weiß ich ja jetzt.

**Comment by wpichler** [comment]
Hallo,

ich habe leider genau das selbe Problem - Kasse und Signatur sind Produktiv im FON angemeldet. Startbeleg wird vom Prüftool akzeptiert.
Allerdings bekomme ich bei der BMF-App - und mit der SOAP Schnittstelle genau die selbe Fehlermeldung das der Beleg nicht zum Unternehmen passt.
Hier ist der SOAP Request den ich sende:
      (rkdb){
         fastnr = None
         paket_nr = 1
         ts_erstellung = "2017-01-21T21:10:48.287952"
         belegpruefung = 
            (belegpruefung){
               satznr = 1
               kundeninfo = "Startbeleg"
               beleg = "_R1-AT100_426572a2-dfcb-11e6-8583-001a4b7afba6_STARTBELEG_2017-01-21T18:37:25_0,00_0,00_0,00_0,00_0,00_lWX7t5kKAWs=_6D963841_29Q42nveevo=_F7Gsfir390vqLPePtnfRiWfXFvas0WtWFwqt6QM38ZwOPK8ZiI2DWecEUZelf1tksCuMCLBVIne4uqb6fpq/0A=="
            }
      }

Ich habe auch schon versucht bei der Hex Seriennummer von lower case auf upper case (wie im Beispiel) zu ändern - bringt auch nichts.
Seriennummer ist genauso im FON hinterlegt - ATU stimmt mit der Karte 100% überein.

Wenn das nur mit dem BMF geklärt werden kann - wie komme ich dort zu den richtigen Ansprechpartnern ?

**Comment by Phoniexk** [comment]
Im WKO-Forum für Kassenhersteller https://communities.wko.at/Kassensoftware gibt es eine Rubik für Fragen zum Webservice, dort werden Antworten vom BMF gegeben. Dort werden vom BMF auch die im FON übermittelten Daten überprüft und eine Rückmeldung was der Fehler war gegeben.

Was mir schonmal beim Beleg auffällt, AT100 gibt es nicht ;)
Möglicherweise kann deshalb das Zertifikat nicht zugeordnet werden.
