### ISSUE TITLE
FORMAT_BASE64_CHARS

### ISSUE THREAD

**Issue by samuel4711** [a-sit-plus/at-registrierkassen-mustercode#227]
Hallo in die Runde,
wir haben an der Stelle ein kleines Problem, wir versuchen einen Start Beleg bei Finanzonline zu melden, das Prüftool 1.0.0 ( regkassen-verification-depformat-1.0.0.jar ) meckert diesen Beleg nicht an.
Hier kommt die Meldung : 
  "verificationId" : "RKSV_DEP_EXPORT",
  "version" : 1,
  "verificationName" : "RKSV-DEP-Export Prüfung",
  "verificationTextualDescription" : "Es wird die Richtigkeit des exportierten RKSV-DEP überprüft: Abfolge der Belege, Entwicklung des verschlüsselten Umsatzzählers, Verkettung der Belege.",
  "verificationState" : "PASS",
  "verificationResultDetailedMessage" : "Die Belege im exportierten RKSV-DEP weisen keinen Fehler auf (Verkettung zu vorigem Beleg, Entwicklung des Umsatzzählers, Belegabfolge).",
  "input" : {
Möchte ich nun diesen Beleg bei Finanzonline anmelden, bekomme ich die Fehlermeldung :
 <verificationId>FORMAT_CHAIN_VALUE_PREVIOUS_RECEIPT_BASE64</verificationId>
                <version>1</version>
                <verificationName>Formatprüfung: Verkettungswert</verificationName>
                <verificationTextualDescription>In diesem Modul und den dazugehörigen Submodulen werden unterschiedliche Prüfungen im Zusammenhang mit der BASE64-Kodierung (gültige Zeichen, Länge) des Verkettungswerts durchgeführt.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-01-09T14:58:49.160+01:00</verificationTimestamp>
                <verificationResultList>
                  <verificationResult>
                    <verificationId>FORMAT_BASE64_DECODE_ENCODE</verificationId>
                    <version>1</version>
                    <verificationName>Formatprüfung: BASE64 Dekodierung/Kodierung</verificationName>
                    <verificationTextualDescription>In diesem Modul wird überprüft ob die Dekodierung eines BASE64-Werts und die anschließende Kodierung wieder den Ausgangswert ergibt.</verificationTextualDescription>
                    <verificationState>FAIL</verificationState>
                    <verificationTimestamp>2017-01-09T14:58:49.160+01:00</verificationTimestamp>
                    <verificationResultList>
                      <verificationResult>
                        <verificationId>FORMAT_BASE64_CHARS</verificationId>
                        <version>1</version>
                        <verificationName>Formatprüfung: Gültige BASE64-Zeichen</verificationName>
                        <verificationTextualDescription>Es wird in diesem Modul überprüft ob die gegebene Zeichenkette nur Zeichen beinhaltet die für die BASE64-Kodierung verwendet werden dürfen.</verificationTextualDescription>
                        <verificationState>FAIL</verificationState>
                        <verificationTimestamp>2017-01-09T14:58:49.160+01:00</verificationTimestamp>
                      </verificationResult>
                    </verificationResultList>
                  </verificationResult>
Mein Maschinenlesbarer Code sieht wie folgt aus :
_R1-AT1_Acafe_1_2017-01-09T13:17:41_0,00_0,00_0,00_0,00_0,00_P7JKFa4iNGrnbB/qTTnP6w==_7BF7F2A7_zmCi6+OfQHs=_sZ/OVAgxyfYiWyUbWcNUH9zR6pLRr6mCBXsDsysyxYKyGAWy7WZDdHxvSJBwK1AC9kqnl44bfMftt4DeN+vaag==

Beide Prüftools ( regkassen-verification-depformat-1.0.0.jar , regkassen-verification-receipts-1.0.0.jar ) meckern den Beleg nicht an.
Bin für jeden Tip dankbar.

**Comment by samuel4711** [comment]
Hallo,
leider nein, hier bekomme ich die Meldung ales schick, zumindest sehe ich da keinen Fehler.

[0000_cashbox_full.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/696433/0000_cashbox_full.zip)

**Comment by asitplus-pteufl** [comment]
Stimmt auch alles laut dem Ergebnis.
Können Sie den QR-Code dazu posten? Es gab schon öfters Fälle wo die Kodierung im QR-Code falsch war oder new Lines etc. für BASE64 eingefügt wurden.

**Comment by areiter** [comment]
Seltsam.
Ich bleib bei meiner Version. Meiner Meinung nach sollte der Startverkettungswert für `Acafe` den folgenden Wert haben: `HL9ypsCnA68=`
Können sie das mal versuchen?

**Comment by asitplus-pteufl** [comment]
Das geteilte Prüfergebnis sagt aus dass der Beleg stimmt... Ist es sicher das Ergebnis das zu dem oben genannten Beleg gehört? Der Prüfkern prüft nämlich schon die Verkettung auf die Kassen-ID (Voraussetzung für einen gültigen Startbeleg) und wenn @areiter dann da etwas anderes herausbekommt, dann kann auch das Prüftool kein positives Ergebnis liefern.

**Comment by samuel4711** [comment]
anbei der Startbeleg

![startbeleg](https://cloud.githubusercontent.com/assets/10289392/21813057/39c184de-d755-11e6-98d3-83751770021a.jpg)

**Comment by samuel4711** [comment]
kleiner Nachtrag ... 
Acafe wurde im Beleg auch auf MUHcafe geändert.

**Comment by asitplus-pteufl** [comment]
es ist genau das Problem das in der Fehlermeldung beschrieben ist, es sind keine gültigen BASE64-Zeichen enthalten (bzw. die Abfolge ist nicht korrekt). In BASE64 gibt es kein Padding mit mehr als 2 =. Sie haben einmal 3 = und einmal sogar 5. 
Zum Thema Prüftool und FinOnline: Sie haben da zwei ganz unterschiedliche Belege geprüft (der oben genannte hat die Padding Fehler nicht). D.h. es ist auch ganz klar dass da was anderes rauskommt.

Hier noch der Beleg des QR-Codes:
_R1-AT75_MOHCAFE_1_2017-01-09T11:25:38_0,00_0,00_0,00_0,00_0,00_H6ZEUFNOEI2GVZ3MD7VE2OOP5M======_7BF7F2A7_ZZQKF27DT5AHW===_I5TJPLV2E6URTO2Y7H456HKHQVZIVPZ2U4SBS4SCJ35K4YCZHKXSCVUD25SNFWS2U23UPQHBDK4ISMG475WCDZ3Y6LAQMQLW5J66G6Y=

**Comment by samuel4711** [comment]
Hallo,
vielen dank bis dato für die Hilfe. Ich habe einen Fehler bei der Wandlung der DAten gemacvht, habe statt den MaschinenCode in QR Code den ocr Code in QR Code gedruckt. Daher auch die unterschiedlichen Belege. Sorry.
Fehler habe ich nun gefunden und auch korrigiert. Leider bekomme ich den Fehler immer noch. Hier nun die Rohdaten des QR
_R1-AT1_KASSE_1_2017-01-09T14:18:24_0,00_0,00_0,00_0,00_0,00_BaJJCcgCLKVzIDWiF3XFDg==_7BF7F2A7_Y/uhSXQmDB8=_SrTDKhSblC7g8kJ5Ooz/ee9wf/DZuimtrm+QtlnJzWR78ZYVrc55ak6eQnXAlJFdrvlkr2OxvAQPRdszXRKZ4g==
![qr](https://cloud.githubusercontent.com/assets/10289392/21893160/3090e16c-d8da-11e6-90c8-db67cc1f9573.jpg)

**Comment by ErichFreitag** [comment]
Im QR-Code steht alles in Großbuchstaben, das ist so nicht korrekt.

**Comment by samuel4711** [comment]
Vielen Dank an alle ...
Der Fehler waren eigentlich 2.
1. Wir haben versehentlich den OCRCode in einen QR Code gedruckt.
2- Wir haben ein toupper bei der Daten für den QRCode gehabt.
Läuft und Kasse ist online. Danke für die Unterstützung.
