### ISSUE TITLE
muss Jahresbeleg mit APP geprüft werden?

### ISSUE THREAD

**Issue by manfred78** [a-sit-plus/at-registrierkassen-mustercode#229]
ich bin mal soweit durch mit dem ganzen RKSV und habe auch schon eine Testkassa registriert bis hin zur Prüfung des Startbeleges mit der APP am Handy.

Meine Frage nun:
ich habe gelesen, dass auch der Jahresbeleg (Montatsbeleg Dezember) jedes Jahr mit der APP geprüft werden muss? Stimmt das? Und wenn ja - kann der Anwender also die APP installieren - den Code eingeben und dann (solange er das Handy nicht wechselt) einfach jedes Jahr den Beleg scannen . oder ist da die "Nummer" aus FinanzOnline nicht mehr gültig und er muss wieder eine neue anfordern?
Wie lange hat er dann Zeit für die Prüfung? (z.B. Kunde öffnet erst um Feber wieder und der Monatsbeleg für Dezember kommt dann erst , ...) und was passiert wenn Frist überschritten wird?

Danke für die Aufklärung

lg
Manfred

**Comment by ErichFreitag** [comment]
Korrekt, auch die Jahresbelege müssen jedes Jahr erzeugt und geprüft werden. Das erfolgt mit der selben App und mit dem selben Auth-Code.

Laut Erlass 4.5.7 ist die Prüfung bis spätestens 15. Februar durchzuführen.

**Comment by Georg632** [comment]
Hierzu hätte ich ein Webservice frage:

Hier kommt als Antwort zurück das dieser Beleg mit einer erfolgreich In Betrieb genommenen Kasse erstellt worden ist.
Ist dies korrekt für einen Jahresbeleg? Ich habe mir da etwas anderes erwartet?

**Comment by ErichFreitag** [comment]
Sie können ja grundsätzlich jeden Beleg prüfen. Die Antwort bedeutet, dass (soweit prüfbar) "alles in Ordnung ist", sprich die Kasse ordnungsgemäß in Betrieb und registriert ist. Was hätten sie denn erwartet?

**Comment by Georg632** [comment]
Mit irgendeinen Bezug auf den Jahresbeleg. Aber wenn mit der Nachricht der Jahrebeleg hochgeladen ist alles passt habe ich damit auch kein Problem :-)
vielen Dank.

**Comment by wjjw73** [comment]
Kann die APP auch OCR-Codes überprüfen? Ist ja laut Erlass möglich.

**Comment by ErichFreitag** [comment]
@Georg632 - die Prüfung weiß ja nicht, dass es ein Jahresbeleg ist (sie könnte es aus dem Datum heraus vermuten, aber das ist keine Gewähr dafür).

@wjjw73 Nein, OCR-Codes sind derzeit (noch?) nicht möglich. Vorschlag zur Prüfung: z.B. mit Online-Tool in einen QR-Code umwandeln und diesen prüfen.

**Comment by Georg632** [comment]
Heißt es nicht ich muss den Jahresbeleg hochladen? Wie weiß er dann ob dies schon geschehen ist wenn er es nicht Identifizieren kann? Oder geht das per Webservice gar nicht?

**Comment by ErichFreitag** [comment]
Es heißt, dass sie den Jahresbeleg prüfen müssen und das bis 15.02. erfolgt sein muss. Ich nehme also an, dass in einem neuen Jahr z.B. ein Nullbeleg erwartet und akzeptiert wird (was ja "technisch" einem Jahresbeleg entspricht).

**Comment by Georg632** [comment]
Okay - also alles halb so wild.
Gut dann danke ;)
