### ISSUE TITLE
Differences between contents of the files "qr-code-rep,txt" and "ocr-code-rep.txt"

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#23]
In both mentioned files from "example-output-0.5.zip" package there should be same content but it is not.

On every file's line (every document/beleg) there are differences for "Stand-Umsatz-Zaehler-AES256-ICM:" and "Sig-Voriger-Beleg". All other fields are OK (excluding electronic signature, which is also different).

Why the contents of equivalent files are different? 
(in my opinion they should be same)

**Comment by pteufl** [comment]
for the "qr-codes"  base64 encoding is used, while base32 encoding is used for the "ocr" counterparts: reason: base32 is easier to recognize for the ocr process (only upper-case letters required).

the "detailspezifikation" states that difference in section "14. Erstellung der OCR-fähigen Zeichenkette"
https://www.bmf.gv.at/steuern/RKSV.pdf?555ads

**Comment by slavok1** [comment]
Thanks for the answer
