### ISSUE TITLE
Verschlüsselung mit Bouncy Castle

### ISSUE THREAD

**Issue by PeterRumpf** [a-sit-plus/at-registrierkassen-mustercode#230]
Wir wollen die Verschlüsselung mit Bouncy Castle durchführen.  Leider habe ich auf in der Bouncy Castle Doku keinen Hinweis auf "AES/ICM" gefunden. Kennt jemand Bouncy Castle oder hat damit sogar die Verschlüsselung umgesetzt?

**Comment by ErichFreitag** [comment]
Im A-SIT-Mustercode gibt es mehrere Varianten der Einbindung von Crypto-Libraries. Ich vermute, dass bcprov-jdk15on-1.52.jar und bcpkix-jdk15on-1.52.jar im lib-Verzeichnis damit zu tun haben und ihnen vielleicht weiterhilft. Abgesehen davon gibt es für AES/ICM ja auch Alternativen.

**Comment by asitplus-pteufl** [comment]
Kennt jemand Bouncy Castle?
Ja, A-SIT Plus kennt diese Library.

..hat damit sogar die Verschlüsselung umgesetzt?
Ja, A-SIT Plus hat im Demo-Code in DIESEM Projekt diese Verschlüsselung umgesetzt und Varianten mit ECB und CFB gezeigt.

Wo findet man diese Demo-Implementierung:
In diesem Projekt, Infos im Readme, Quick-Link: https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-common/src/main/java/at/asitplus/regkassen/common/util/CryptoUtil.java

Wie geht man generell vor?
Es sollte unbedingt zuerst das Detailspezifikationsdokument und das Readme gelesen werden, dort sind alle technischen Prozesse definiert und es wird auf die relevanten Teile des Muster-Codes verwiesen.

**Comment by AxelKutschera** [comment]
Wir haben unsere Middleware ebenfalls mit Bouncy Castle umgesetzt.

**Comment by PeterRumpf** [comment]
Hallo vielen Dank
wir haben erfolgreich mit BouncyCastle umgesetzt,
Habe vorher an der Falschen stelle gesucht...
