### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by RkRKlink** [a-sit-plus/at-registrierkassen-mustercode#231]
Guten Tag, 
beim Prüfen meines erstellten DEP tritt ein Fehler beim prüfen der Signatur & Umsatzzählers

![image](https://cloud.githubusercontent.com/assets/24695839/21884741/dcc4251e-d8b4-11e6-834e-b99167a11cb5.png)

Leider weiß ich nicht mehr weiter, was ich noch überprüfen kann woran es liegt. Könnte mir hier eventuell jemand weiter helfen?

[DEP.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/701254/DEP.txt)

[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/701258/cryptographicMaterialContainer.txt)

Danke schon mal im voraus!

**Comment by ErichFreitag** [comment]
Der AES-Schlüssel im cryptographicMaterialContainter ist kein gültiger Eintrag.

**Comment by RkRKlink** [comment]
Und wie so das nicht? Wie sollte er denn dann aussehen?

**Comment by ErichFreitag** [comment]
AES-256 -> 32 Zeichen -> BASE64-codiert -> 44 Zeichen

**Comment by RkRKlink** [comment]
Danke für die schnelle und gute Hilfe !
