### ISSUE TITLE
Kaution

### ISSUE THREAD

**Issue by eczach** [a-sit-plus/at-registrierkassen-mustercode#232]
Wahrscheinlich etwas off-topic in dieser Gruppe, jedoch habe ich den Eindruck gewonnen, dass hier viele sich sehr gut im Grenzgebiet zwischen Recht und Technik auskennen (eine Besonderheit der ganzen RKSV-Materie) - deshalb trotzdem meine Frage:

Folgende Situation am Beispiel einer Autovermietung:

Ein Kunde zahlt bei Abholung eines Fahrzeuges eine Kaution vorab, die in der Regel dem zu erwartenden Mietpreis zzgl. einer Sicherheit (Kaution) entspricht (z.B. 250,00). Der Kunde erhält die Bestätigung für den Erhalt der Kautionsleistung mit dem Mietvertrag. Die Kaution wird NICHT in der Registrierkassa erfasst bzw. signiert.

Bei Rückgabe des Fahrzeuges wird eine Rechnung für die Anmietung des Fahrzeuges (z.B. 200,00) erstellt. Dieser Betrag wird in der Registrierkassa erfasst und signiert. Der Kunde erhält die 50,00 zurück.

Ist diese Vorgehensweise korrekt?

Danke für Rückmeldung!

**Comment by ErichFreitag** [comment]
Nachdem die Kaution wie in diesem Fall geschildert kein Barumsatz ist muss sie auch nicht signiert werden. Ich finde das aus RKSV-Sicht korrekt (kassentechnisch und buchhalterisch müssen sie es ja unabhängig davon abwickeln).

**Comment by AxelKutschera** [comment]
Ich habe diverse Geschäftsvorfälle für (große) Autovermietungen (als Steuerberater) behandelt und erlaube mir zu sagen, dass diverse Vorgänge z.B. mit Kreditkarten nicht so einfach zu beurteilen sind....

**Comment by eczach** [comment]
das habe ich befürchtet .... die antwort von erichfreitag hat mir besser gefallen :-) 
warum ist der konkrete fall nicht so einfach zu beurteilen?

**Comment by AxelKutschera** [comment]
Dies ist nicht das Forum zur Beantwortung steuerlicher Fragen. 
Ich bin jedoch gerne (jederzeit) persönlich zu erreichen.
