### ISSUE TITLE
Startbeleg von WebService nicht akzeptiert

### ISSUE THREAD

**Issue by HPL1** [a-sit-plus/at-registrierkassen-mustercode#233]
Das WebService von FinanzOnline mag unsere Startbelege nicht, obwohl das Prüftool von a-sit als auch die BMF Belegcheck App damit zufrieden sind.

Wir haben per WebService  übermittelt:
_R1-AT1_WD0000_2017/8.0_2017-01-12T16:48:06_0,00_0,00_0,00_0,00_0,00_HZY3yH/bL30ByRyVN/MEpA==_677dda3d_s3molg2D4i8=_ZAhknGjQ-Uoj4XhIcxG1pAlybnuXZK5CnVVMAW4ESopbbTbFzH_Z81IylxQcPdx6T4UvE-orHSYJrvPtqz2D7g

Und folgende Fehlermeldung bekommen:
<soapenv:Fault>
<faultcode>soapenv:Client</faultcode>
<faultstring>Validation error</faultstring>
<detail>
<spring-ws:ValidationError 
xmlns:spring-ws="http://springframework.org/spring-ws">cvc-pattern-valid: Value 
'_R1-AT1_WD0000_2017/1.0_2017-01-12T20:15:00_0,00_0,00_0,00_0,00_0,00_pdumvb356/JxtnHZ/B2Ctw==_677dda3d_s3molg2D4i8=_cxELZxQOFTwBCEUgleocgZcB1TZDPWOTutaguYeNkDt71Ghsb_aLsGdXfr4xFoISCh7CUuJPEKVx8WSM1IfbWA'b
is not facet-valid with respect to pattern '(_[^_]+){13}' for type 
'#AnonType_beleg'.</spring-ws:ValidationError>

<spring-ws:ValidationError 
xmlns:spring-ws="http://springframework.org/spring-ws">cvc-type.3.1.3: The value 
'_R1-AT1_WD0000_2017/1.0_2017-01-12T20:15:00_0,00_0,00_0,00_0,00_0,00_pdumvb356/JxtnHZ/B2Ctw==_677dda3d_s3molg2D4i8=_cxELZxQOFTwBCEUgleocgZcB1TZDPWOTutaguYeNkDt71Ghsb_aLsGdXfr4xFoISCh7CUuJPEKVx8WSM1IfbWA' 
of element 'SOAPSDK4:beleg' is not valid.</spring-ws:ValidationError>
</detail>
</soapenv:Fault>

Via Belegcheckk App wird der Beleg akzeptiert.
Auffällig ist dass unser iPhone App zum Anzeigen von QR-Code Daten (i-nigma) einen leicht anderen String anzeigt, als wir in unserer Software mit der Bibliothek von ATrust erstellt und an das WebService übermittelt haben.

Unsere Handy-App zeigt an:
_R1-AT1_WD0000_2017/8.0_2017-01-12T16:48:06_0,00_0,00_0,00_0,00_0,00_HZY3yH/bL30ByRyVN/MEpA==_677dda3d_s3molg2D4i8=_ZAhknGjQ+Uoj4XhIcxG1pAlybnuXZK5CnVVMAW4ESopbbTbFzH/Z81IylxQcPdx6T4UvE+orHSYJrvPtqz2D7g==
Da wird im letzten Teil zweimal statt – (minus) + (plus) und einmal statt _ (Underline) / (Schrägstrich) angezeigt. Zusätzlich am Ende ==.

Wäre sehr nett, wenn uns hier irgendjemand aufklären könnte.
Vielen Dank im Voraus.

**Comment by ErichFreitag** [comment]
Das was sie an das Webservice übermitteln ist BASE64URL-codiert. Woher nehmen sie diese Daten?

Das was im letzten Eintrag steht ist korrekt BASE64-codiert.

Die Belegcheck-App prüft den QR-Code, das würde mit dem Ergebnis der Handy-App passen. Was übermitteln sie an das Webservice?

**Comment by HPL1** [comment]
Danke für die schnelle Antwort.

 

Die Daten, die wir an das WebService senden entstehen so:

Der erste Teil ist der Datenstring, den wir als Input an die Funktion SignJWS der A-Trust Bibliothek asignRKCom.dll übergeben.

In unserem Beispiel:

_R1-AT1_WD0000_2017/8.0_2017-01-12T16:48:06_0,00_0,00_0,00_0,00_0,00_HZY3yH/bL30ByRyVN/MEpA==_677dda3d_s3molg2D4i8=

Retour kommt laut Doku:

Durchführen einer Signatur auf der Karte. Die Funktion bereitet die eingegebenen Daten

nach dem JWS Standard auf, d.h. es wird der entsprechende JWS-Header mit dem

Algorithmus erzeugt und sowohl Daten als auch Header Base64-URL kodiert. Der zurückgegebene

Wert entspricht der JWS Signatur bestehend aus Protected Header, Payload

und Signatur jeweils Base64-URL kodiert und durch Punkt getrennt.

 

Der zweite Teil – getrennt durch Underline vom ersten – ist die Signatur (der dritte Teil) aus obiger Funktion. Eben Base64-URL kodiert.

Das Prüftool von a-sit akzeptiert dies beim Export des DEPs.

 

Den QR-Code – aus dem die zweite Zeile unserer Anfrage stammt - erstellen wir mit der Funktion EncodeFromJWS derselben A-Trust Bibliothek.

Der Input dafür ist der Output aus obiger Funktion SignJWS. Als Ergebnis wird ein .bmp Datei erstellt.

 

Wie Sie sicher bemerken, ist das alles komplettes Neuland für uns.

Da tun wir uns halt ein wenig schwer. Dass es nicht nur uns so geht, wissen wir aus mehreren Gesprächen mit unserem Mitbewerb.

Umso dankbarer sind wir, wenn da jemand ein wenig Licht in unsere Dunkelheit bringt.

 

Danke im Voraus für Ihre Mühen.

 

H. Peter Lienhardt

 

HPL Software KG

Schauensteingasse 6, 8010 Graz, Austria

Tel +43 (316) 714985

Fax +43 (316) 714985 9

FN 114439v, LG für ZRS Graz

 <http://www.hpl.at/> http://www.hpl.at

**Comment by asitplus-pteufl** [comment]
"Der zweite Teil – getrennt durch Underline vom ersten – ist die Signatur (der dritte Teil) aus obiger Funktion. Eben Base64-URL kodiert."

Nein, das ist nicht korrekt, im maschinenlesbaren Code wird BASE64 verwendet. (siehe 4.1 Aufbereitung des maschinenlesbaren Codes (Basis-Code) im Detailfragendokument.

Bitte auch unbedingt darauf achten, dass im JWS-Standard zwar BASE64-URL Kodierung verwendet wird im Standard aber explizit das Padding-Zeichen "=" entfernt wird.

Bei BASE64 im Beleg PaddingZeichen "=" natürlich verwendbar.

Bitte auch noch die Hinweise unter https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf beachten, (Dokument wird vom README dieses Projekts verlinkt).

**Comment by HPL1** [comment]
Sehr geehrte Hr. Dr. Teufl

 

Danke für die schnelle Antwort.

Ehrlich gesagt bin ich jetzt ziemlich verwirrt.

Seit Wochen implementieren wir und testen täglich mehrmals mit Ihrem Prüftool, dem wir auch im DEP die BASE64-URL kodierten Daten übergeben und sehen eben seit Wochen nur PASS und nie FAIL.

Erst mit der Übermittlung an das WebService sind die Probleme aufgetaucht.

 

mit freundlichen Grüßen

 

H. Peter Lienhardt

 

HPL Software KG

Schauensteingasse 6, 8010 Graz, Austria

Tel +43 (316) 714985

Fax +43 (316) 714985 9

FN 114439v, LG für ZRS Graz

 <http://www.hpl.at/> http://www.hpl.at

**Comment by asitplus-pteufl** [comment]
Achtung, im DEP sind ja die JWS-Daten wo BASE64-URL verwendet wird. Im QR-Code steht aber direkt der maschinenlesbare Code.
Daher passen die bisherigen Ergebnisse schon.
Das Problem bei der BASE64-URL Kodierung ist, dass sie ja auch "_" als Zeichen enthalten kann, dieser Zeichen im Maschinenlesbaren Code aber schon für die Trennung der Elemente verwendet wird. Die Fehlermeldung oben bekommen Sie weil der maschinenlesbare Code in der Signatur noch mal ein "_" enthält, jetzt schaut es dann aber so aus als hätte der Beleg um ein Element mehr. Daher schlägt schon mal die Basisprüfung fehl.
Sie können das lokal auch leicht mit dem Prüftool prüfen, dieses kann ja neben dem ganzen DEP auch direkt die maschinenlesbaren Code prüfen.

**Comment by HPL1** [comment]
Nochmals vielen Dank für Ihre schnelle und vor allem verständliche Antwort.
Jetzt ist Licht in unser Dunkel gekommen… ;-)

 

mit freundlichen Grüßen

 

H. Peter Lienhardt

 

HPL Software KG

Schauensteingasse 6, 8010 Graz, Austria

Tel +43 (316) 714985

Fax +43 (316) 714985 9

FN 114439v, LG für ZRS Graz

 <http://www.hpl.at/> http://www.hpl.at

**Comment by asitplus-pteufl** [comment]
wunderbar!
einfach die BASE64-URL signatur dekodieren und BASE64 kodieren und an den maschinenlesbaren Code hängen, das sollte es dann sein.
