### ISSUE TITLE
Prüfung Startbeleg OCR-Schrift

### ISSUE THREAD

**Issue by PS4055** [a-sit-plus/at-registrierkassen-mustercode#234]
Da in der BMF Prüf-App nur QR-Codes und Links geprüft werden können, wollte ich nachfragen wie ich die OCR-Schrift prüfen lassen kann. Danke.

**Comment by ErichFreitag** [comment]
Das ist umfassend unter https://www.xing.com/communities/posts/startbeleg-pruefen-1012482261 behandelt.

**Comment by cmaxmedia** [comment]
Den Beleg ausdrucken und via OCR wieder einscannen. Wurde dann die selbe Zeichenkette gescannt, sollte es passen.

**Comment by asitplus-pteufl** [comment]
Nach Absprache mit BMF, OCR Fragen bitte im WKO Forum stellen.
https://communities.wko.at/Kassensoftware
Kategorie: Technische/rechtliche Fragestellungen zur RKSV
