### ISSUE TITLE
Monatsbeleg bei vorherigem Ausfall der Sicherheitseinrichtung 

### ISSUE THREAD

**Issue by PS4055** [a-sit-plus/at-registrierkassen-mustercode#235]
Beispiel:
Ausfall Sicherheitseinrichtung der Kassa beim letzer Bon im aktuellen Monat am 27.1.
Keine weiteren Verkäufe bis zum Monatsende

Danach würde die Sicherheitseinrichtung wieder funktionieren.
Muss dann vor dem Monatsbeleg ein Nullbeleg gemacht werden oder reicht der Monatsbeleg?

**Comment by ErichFreitag** [comment]
Siehe Startseite 18.11.2016 Signieren von Nullbelegen.

Wenn die Sicherheitseinrichtung wieder funktioniert müssen sie immer einen Sammelbeleg generieren, der wird durch den Monatsbeleg nicht ersetzt (der Sammelbeleg enthält auch zusätzliche Informationen). Der Monatsbeleg ist ja selbst ein Nullbeleg.

**Comment by cmaxmedia** [comment]
Hierzu bräuchte ich vielleicht auch weitere Informationen, da in der Dokumentation "2016-09-05-Detailfragen-RKSV-V1.2.pdf" zum Thema Sammelbelege auf eine neuere (nicht vorhandene) Dokumentation hingewiesen wird.

Bei mir ergibt sich der folgende Zeitliche Ablauf bei der Erfassung von Barbelegen, wo mitten drinnen die Signatureinheit ausgefallen ist:

Datum              Betrag    Umsatz Neu   Umsatz Alt   Typ          Status
01.01.2017 08:00   120,00        240,00       120,00   Barbeleg     In Ordnung
01.01.2017 08:05   100,00        340,00       240,00   Barbeleg     In Ordnung
01.01.2017 08:06    10,00        340,00       340,00   Barbeleg     Signatureinheit ausgefallen
01.01.2017 08:07    10,00        340,00       340,00   Barbeleg     Signatureinheit ausgefallen
01.01.2017 08:08    10,00        340,00       340,00   Barbeleg     Signatureinheit ausgefallen
01.01.2017 08:09    10,00        340,00       340,00   Barbeleg     Signatureinheit ausgefallen
01.01.2017 08:10    40,00        380,00       340,00   Sammelbeleg  In Ordnung
01.01.2017 08:10    10,00        390,00       380,00   Barbeleg     In Ordnung

Da ja eine Anforderung der RKSV die nahtlose Verkettung der Belege und dem Umsatz ist, ist es meines Erachtens wichtig, bei ausgefallener Signatureinheit, den Umsatz hier nicht hochzudrehen. Dieser wird erst beim Sammelbeleg wieder angepasst, da sich nur so eine Verkettung der Umsätze in der Signatur bewerkstelligen lässt?

Liege ich da richtig?
Danke im Voraus

**Comment by ErichFreitag** [comment]
Bezüglich Sammelbeleg gibt es im Erlass 3.6.1 Ergänzungen und Erleichterungen (insbesondere diesen nach einem Beleg bei Wiederverfügbarkeit erstellen zu können).

Die Ansicht ist nicht korrekt. Der Umsatz ist immer anzupassen, unabhängig von der Funktion der Signatureinheit. Der Sammelbeleg ist definitiv ein Nullbeleg, also mit 0 EUR Barumsatz (plus Information über Beginn und Ausfall der Signatureinheit), womit schon alleine aus diesem Grund der Umsatzzähler beim Sammelbeleg nicht angepasst werden kann.

Bei Ausfall der Signatureinheit gibt es lediglich keine Signatur (sondern den Ersatztext), der Umsatzzähler und die Verkettung der Belege werden trotzdem nahtlos weitergeführt.

**Comment by cmaxmedia** [comment]
Danke für die Info. Da ja der Umsatz ein Teil der Signatur ist, ist zwar eine Verkettung der Umsätze gegeben, allerdings kann hier manipuliert werden, oder?

**Comment by ErichFreitag** [comment]
Korrekt werden nicht die Umsätze, sondern die Belege verkettet. Die Umsatzänderung ergibt sich ja durch die Summe der Barumsätze und ist damit ebenso lückenlos nachvollziehbar, da auch diese Teil der Signatur sind.

**Comment by cmaxmedia** [comment]
Ist die SEE wieder in Betrieb, brauche ich ja für das Signieren des neuen Beleges den Signaturhash vom letzten. Sollte ich beim Erstellen des Sammelbeleges (08:10) hier dann den letzten signierten Beleg (08:05) heranziehen oder vom fehlerhaften (08:09)?
Danke vielmals!

**Comment by ErichFreitag** [comment]
Sie machen diesbezüglich immer das selbe - mit dem letzten RKSV-Beleg verketten. In diesem Fall also den von 08:09. (RKSV-Beleg deshalb, weil sie ja auch Nicht-Barumsätze haben können, die nicht signiert werden, also auch nicht in die Belegverkettung eingehen).

Zur Verdeutlichung an ihrem obigen Beispiel:
08:05 letzter signierter Beleg
08:06 Ausfall SEE
...
08:09 noch immer Ausfall
08:10 SEE wieder verfügbar

In den Sammelbeleg kommt die Zusatzinfo "Start Ausfall 08:06" (oder dessen Belegnummer) und "Ende Ausfall 08:09".

Gemäß RKSV müssten sie den Sammelbeleg vor dem nächsten wieder-signierbaren Beleg erstellen. Das ist aber technisch aufwändig (Signierung ausprobieren, wenn Fehler und jetzt wieder OK neuen Beleg zwischenspeichern und Sammelbeleg einschieben, ...). 

Der Erlass hat daher eine Erleichterung gebracht, bei dem sie die Reihenfolge in ihrem Beispiel umdrehen können, d.h.
08:09 Beleg erstellen - noch immer Ausfall - "SE ausgefallen"
08:10 Beleg erstellen - SEE wieder verfügbar - normal signieren
08:10 Sammelbeleg einfügen - normal signieren
also den Sammelbeleg auch NACH dem ersten wieder signierbaren Beleg einfügen können (Erlass 3.6.1 zweiter Absatz).

**Comment by cmaxmedia** [comment]
Irgendwas verstehe ich da noch nicht. "Sie machen diesbezüglich immer das selbe - mit dem letzten RKSV-Beleg verketten": 
Stimmt, nämlich immer mit dem Signaturhash des letzten RKSV Beleges. 

Ist die SEE wieder in Betrieb, so steht beim letzten RKSV Beleg "Signatureinheit ausgefallen", also wird der Hashwert für diese neue Verkettung immer der selbe sein.

Außer ich erstelle für alle ausgefallenen Belege im Nachhinein eine Signatur, dann würde der Hashwert wieder passen.

**Comment by ErichFreitag** [comment]
Den Hashwert bilden sie ja nicht nur über die Signatur, sondern über den kompletten Inhalt des maschinenlesbaren Codes des letzten RKSV-Belegs. (siehe A-SIT Detailfragen Prozess 2.4.2). Damit ist alleine auf Grund der Belegnummer, der Umsatzzählerverschlüsselung und des letzten Verkettungswerts jeder neue Signaturwert anders.

**Comment by ckvsoft** [comment]
@ErichFreitag
Wie ist das jetzt zu verstehen. 
>  Nicht-Barumsätze haben können, die nicht signiert werden, also auch nicht in die Belegverkettung eingehen).

Hat es nicht geheißen das freiwillig erfasste Belege trotzdem signiert werden müssen? 
Wie zb. Tages/Monatsabschluss

**Comment by ErichFreitag** [comment]
Freiwillig erfasste Barumsätze werden ja eben signiert und sind damit auch RKSV-Belege. Ich wollte oben nur die Belegverkettung verdeutlichen, also auf welchen Kassenvorgang sich die Referenz zum letzten Beleg bezieht, sprich auf jeden signierten Beleg, egal ob verplichtend oder freiwillig über die Sicherheitseinrichtung geführt.

**Comment by cmaxmedia** [comment]
Ich habe da irgendwo ein Timing/Logikproblem. Im Beispiel steht: "Eingabewert für Hashalgorithmus: Als Eingabewert wird die kompakte Repräsentation der JWS-Signatur des vorhergehenden Beleges herangezogen "

- Es steht hier "JWS Signatur" und nicht "Lesbare JWS Struktur" des vorigen Beleges.
- Es steht auch nicht, dass hier die Signatur dieses vorigen Beleges erst erstellt werden muss, noch
- dass der letzte Beleg erst jetzt signiert werden muss

Zum Zeitpunkt des vorigen Beleges ist die SEE aber ausgefallen und in der Signatur steht "Einheit ausgefallen"

**Comment by cmaxmedia** [comment]
@ckvsoft: Ich habe es so verstanden, dass alle Belege, welche in das DEP eingehen, auch signiert werden müssen. Nicht-Barumsätze müssen nicht ins DEP und somit auch nicht signiert werden

**Comment by ErichFreitag** [comment]
@cmaxmedia - vielleicht liegt es nur an bestimmten Worten:

A-SIT-Detailfragen 2.4.2 Eingabewert für Hashalgorithmus – **Kompakte Repräsentation** der JWS-Signatur:
eyJhbGciOiJFUzI1NiJ9. X1IxLUFUMF9ERU1PLUNBU0gtQk9YNTI0XzM2NjU4N18yMDE1LTEyLTE3VDExOjIzOjQ0XzM0LDc3XzU5LDY0XzM4LDEzXzAsMDBfMCwwMF84TUc4QzFLcjdIQT1fMjBmMmVkMTcyZGFhMDllNV94VGZadmtCU1RyND0. 
GeWps9kci-fUqKLymS1pHlIbv0L8Oek-v6TDmZj9Ffucb8yvSijqZ8LcBalV9lADMX Q8U3itViKkd_i1Ba22BA

also Header, payload und Signatur des letzten Belegs. Der Signaturteil bleibt in ihrem Beispiel gleich ("SE ausgefallen"), aber die Payload ändert sich jedesmal, damit auch der neue Hashwert.

**Comment by ErichFreitag** [comment]
Korrekt - alle Belege über das RKSV-DEP müssen auch über die Sicherheitseinrichtung geführt werden (ich schreibe hier deshalb nicht "signiert werden", weil ja formal bei einem Ausfall der SE keine Signierung stattfindet).

**Comment by cmaxmedia** [comment]
Ok, dann scheint mir das Problem jenes zu sein, dass ich Header, payload und Signatur, vollständig von einer Schnittstelle bekomme ;(

**Comment by cmaxmedia** [comment]
Ne, Moment mal. In 3.1 steht "Payload: Dabei handelt es sich um die signierten Daten", was ich ja nicht machen kann, da SE ausgefallen
Vorerst mal Mahlzeit und danke für die Hilfestellung!

**Comment by ErichFreitag** [comment]
Gerne. Ich versuch es nochmals anders:
Header - ist klar, ist auf Grund des Algorithmus ein Fixwert.
Payload - maschinenlesbarer Code von Reg.Alg.-Kennzeichen bis Sig-Voriger-Beleg
Signatur - Signatur oder Ersatztext

Das ganze in die kompakte Darstellung gebracht. Das ist der Eingabewert für den Hashalgorithmus.

Vielleicht hilft das folgende Bild.
![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/21962015/95be43fe-db19-11e6-90af-171852824192.jpg)

**Comment by cmaxmedia** [comment]
Ich möchte vielleicht noch Anmerken, dass von der BMF Belegcheck App schon mehrere Kassen-ID mit mehreren Kunden, registriert und alle erstellten Start- und Folgebelege als korrekt markiert wurden. Also muss ich davon ausgehen, dass die von mir verwendeten Methoden einen richtigen Output erzeugen. Somit stellt sich für mich die Frage, des unter funktionierenden Umständen erstellen Beleges, nicht mehr.

Nur kann ich diese Methoden nicht übertragen, wenn die SE ausfällt, da sich für mich eben dieses kleine, aber nicht unerhebliche Logikproblem ergibt.

Soll ich dann die Signatur des zuletzt erfolgreich signierten Beleges verwenden, und den letzten Teil ersetzen oder gar den Lesbaren Code verwenden, ohne zu signieren?

Statt:
eyJhbGciOiJFUzI1NiJ9. X1IxLUFUMF9ERU1PLUNBU0gtQk9YNTI0XzM2NjU4N18yMDE1LTEyLTE3VDExOjIzOjQ0XzM0LDc3XzU5LDY0XzM4LDEzXzAsMDBfMCwwMF84TUc4QzFLcjdIQT1fMjBmMmVkMTcyZGFhMDllNV94VGZadmtCU1RyND0.
 GeWps9kci-fUqKLymS1pHlIbv0L8Oek-v6TDmZj9Ffucb8yvSijqZ8LcBalV9lADMX Q8U3itViKkd_i1Ba22BA

das hier:
eyJhbGciOiJFUzI1NiJ9. X1IxLUFUMF9ERU1PLUNBU0gtQk9YNTI0XzM2NjU4N18yMDE1LTEyLTE3VDExOjIzOjQ0XzM0LDc3XzU5LDY0XzM4LDEzXzAsMDBfMCwwMF84TUc4QzFLcjdIQT1fMjBmMmVkMTcyZGFhMDllNV94VGZadmtCU1RyND0.
SE ausgefallen

oder das hier mit den aktuellen Belegdaten befüllen:
_R1-AT0
_DEMO-CASH-BOX524 
_366587 
_2015-12-17T11:23:44_34,77 
_59,64 _38,13 _0,00 _0,00 _8MG8C1Kr7HA= 
_20f2ed172daa09e5 _xTfZvkBSTr4= 
_SE Ausgefallen 

und beim Belege mit defekter SE anfügen? Den Mittelteil kann ich ja nicht signieren...

**Comment by ErichFreitag** [comment]
Die Aufbereitung der Belegdaten bleibt immer gleich. Den Verkettungswert errechnen sie ebenso über den Hashwert des Belegs zuvor, wie bei jedem anderen Beleg auch.

Wenn die SE-Einheit ausgefallen ist können sie ja nicht signieren. Daher kommt anstelle der Signatur der BASE64- bzw. BASE64-URL-codierte Text "Sicherheitseinrichtung ausgefallen" = U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg== bzw. U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg, also

_R1-AT0
_DEMO-CASH-BOX524
_366587
_2015-12-17T11:23:44_34,77
_59,64 _38,13 _0,00 _0,00 _8MG8C1Kr7HA=
_20f2ed172daa09e5 _xTfZvkBSTr4=
_U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==

mit aktuellen Belegdaten befüllt.

**Comment by cmaxmedia** [comment]
Bei jenen Belegen, wo die SEE ausgefallen ist, bleibt dann aber der Signaturhash für den jeweils nächsten Beleg immer derselbe, da der geänderte Inhalt ja nicht neu signiert werden kann? Ist die Ausgabe so korrekt:

Letzte Sig	                Aktuelle Sig
abWTEWo3TZE=	BKkNuD2fKjg=      => Wieder in Betrieb
abWTEWo3TZE=	abWTEWo3TZE=   => Ausfall
abWTEWo3TZE=	abWTEWo3TZE=   => Ausfall
vPKwVu2CXe8=	abWTEWo3TZE=   => Ausfall, Aktuelle Sig wurde mit "SE Ausgefallen" erweitert
eHb52NaB3E0=	vPKwVu2CXe8=    => Hier hats noch funktioniert

**Comment by ErichFreitag** [comment]
Nein, verwechseln sie Signatur mit Hashwert für die Belegverkettung?

Bei ausgefallener SE steht anstelle der Signatur immer _U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==. 

Da sie jedoch über die Belegdaten mit sich ändernder Belegnummer, sich änderndem verschlüsseltem Umsatzzähler etc. einen Hashwert bilden ist der jedesmal anders, selbst wenn die Beträge die selben wären.

**Comment by cmaxmedia** [comment]
Im Beispiel oben handelt sind es nur die Hashwerte. Die Details wären dann so im DEP:

```
Letzte Sig	Aktuelle Sig
abWTEWo3TZE=	BKkNuD2fKjg=   => Wieder in Betrieb
abWTEWo3TZE=	abWTEWo3TZE=   => Ausfall
abWTEWo3TZE=	abWTEWo3TZE=   => Ausfall
vPKwVu2CXe8=	abWTEWo3TZE=   => Hier ist der Ausfall und die Aktuelle Sig wurde mit "SE Ausgefallen" erweitert
eHb52NaB3E0=	vPKwVu2CXe8=   => Hier hats noch funktioniert

Lesbar
_R1-AT1_envira.ERP.270H830677_8_2017-01-15T13:44:51_12000_0,00_0,00_0,00_0,00_3QKX7NRDMVlhH71/BFlwJw==_10553C51_abWTEWo3TZE=_8L5HZiPN3/QaC7BquzbEdlpoTR7J5cZHrnyLYMlFgG92vcMnJjmW0Oawo5iQGu81srRJyLpSRfXWSZMOw1oILg==
_R1-AT1_envira.ERP.270H830677_4_2017-01-15T11:01:28_24000_0,00_0,00_0,00_0,00_m+pIRsQQC2Mw1ZFAJ3ImnQ==_10553C51_eHb52NaB3E0=_U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
_R1-AT1_envira.ERP.270H830677_4_2017-01-15T11:01:28_24000_0,00_0,00_0,00_0,00_m+pIRsQQC2Mw1ZFAJ3ImnQ==_10553C51_eHb52NaB3E0=_U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
_R1-AT1_envira.ERP.270H830677_4_2017-01-15T11:01:28_24000_0,00_0,00_0,00_0,00_m+pIRsQQC2Mw1ZFAJ3ImnQ==_10553C51_eHb52NaB3E0=_U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
_R1-AT1_envira.ERP.270H830677_4_2017-01-15T11:01:28_24000_0,00_0,00_0,00_0,00_m+pIRsQQC2Mw1ZFAJ3ImnQ==_10553C51_eHb52NaB3E0=_0tOZ5BiOxkhnph613spZpgpoJ27o04qA6P9m3cFqId1MZHz0NkrYfbPmtBTdXG/zXq0QoLoAPhh2Fz21Bku5nQ==

Signiert:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfOF8yMDE3LTAxLTE1VDEzOjQ0OjUxXzEyMDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfM1FLWDdOUkRNVmxoSDcxL0JGbHdKdz09XzEwNTUzQzUxX2FiV1RFV28zVFpFPQ.8L5HZiPN3_QaC7BquzbEdlpoTR7J5cZHrnyLYMlFgG92vcMnJjmW0Oawo5iQGu81srRJyLpSRfXWSZMOw1oILg
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfNF8yMDE3LTAxLTE1VDExOjAxOjI4XzI0MDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbStwSVJzUVFDMk13MVpGQUozSW1uUT09XzEwNTUzQzUxX2VIYjUyTmFCM0UwPQ.U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfNF8yMDE3LTAxLTE1VDExOjAxOjI4XzI0MDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbStwSVJzUVFDMk13MVpGQUozSW1uUT09XzEwNTUzQzUxX2VIYjUyTmFCM0UwPQ.U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfNF8yMDE3LTAxLTE1VDExOjAxOjI4XzI0MDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbStwSVJzUVFDMk13MVpGQUozSW1uUT09XzEwNTUzQzUxX2VIYjUyTmFCM0UwPQ.U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfNF8yMDE3LTAxLTE1VDExOjAxOjI4XzI0MDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbStwSVJzUVFDMk13MVpGQUozSW1uUT09XzEwNTUzQzUxX2VIYjUyTmFCM0UwPQ.0tOZ5BiOxkhnph613spZpgpoJ27o04qA6P9m3cFqId1MZHz0NkrYfbPmtBTdXG_zXq0QoLoAPhh2Fz21Bku5nQ
```

Gefühlsmäßig richtig?

**Comment by ErichFreitag** [comment]
Nein, das kann immer noch nicht sein :-) Von unten nach oben gelesen:

_R1-AT1_envira.ERP.270H830677_8_2017-01-15T13:44:51_**12000**_0,00_0,00_0,00_0,00_3QKX7NRDMVlhH71/BFlwJw==_10553C51_abWTEWo3TZE=_8L5HZiPN3/QaC7BquzbEdlpoTR7J5cZHrnyLYMlFgG92vcMnJjmW0Oawo5iQGu81srRJyLpSRfXWSZMOw1oILg==
_Schaut bis auf "12000" grundsätzlich vernünftig aus._

[...]

_R1-AT1_envira.ERP.270H830677_4_2017-01-15T11:01:28_**24000**_0,00_0,00_0,00_0,00_**m+pIRsQQC2Mw1ZFAJ3ImnQ==**_10553C51_**eHb52NaB3E0=**_**U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==**
_Belegnummer ändert sich nicht, Umsatzzähler ändert sich nicht - kann nicht sein. "24000" ist kein gültiger Eintrag. Belegverkettung ändert sich nicht. Eintrag SE-Ausfall ist falsch (muss sein _U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==)_

_R1-AT1_envira.ERP.270H830677_4_2017-01-15T11:01:28_**24000**_0,00_0,00_0,00_0,00_m+pIRsQQC2Mw1ZFAJ3ImnQ==_10553C51_eHb52NaB3E0=_0tOZ5BiOxkhnph613spZpgpoJ27o04qA6P9m3cFqId1MZHz0NkrYfbPmtBTdXG/zXq0QoLoAPhh2Fz21Bku5nQ==
_Mag sein, grundsätzlich OK bis auf "24000"._

Signiert:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfOF8yMDE3LTAxLTE1VDEzOjQ0OjUxXzEyMDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfM1FLWDdOUkRNVmxoSDcxL0JGbHdKdz09XzEwNTUzQzUxX2FiV1RFV28zVFpFPQ.8L5HZiPN3_QaC7BquzbEdlpoTR7J5cZHrnyLYMlFgG92vcMnJjmW0Oawo5iQGu81srRJyLpSRfXWSZMOw1oILg
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9lbnZpcmEuRVJQLjI3MEg4MzA2NzdfNF8yMDE3LTAxLTE1VDExOjAxOjI4XzI0MDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbStwSVJzUVFDMk13MVpGQUozSW1uUT09XzEwNTUzQzUxX2VIYjUyTmFCM0UwPQ.U2lnbmF0dXJlaW5oZWl0IGF1c2dlZmFsbGVuIQ==
[...]

Das ist nicht signiert, das ist nur die umcodierte Darstellung für den DEP-Export - das hat mit Signierung nichts zu tun.

**Comment by ErichFreitag** [comment]
Sie brauchen sich nur einmal die Beispiele anzusehen, die das A-SIT-Prüftool für Testfälle liefert. 

/* 01 A-SIT suite 1 cashbox 1 receipt 06  */ 
"_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-6_2016-09-05T15:36:49_120,34_21,49_135,72_34,39_193,07_k8wUAJDJ+Ro=_c2148316e9b79f78_**yS+iU3vakTI=**_**U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==",**

/* 02 A-SIT suite 1 cashbox 1 receipt 07  */ 
"_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-7_2016-09-05T15:36:50_0,00_0,00_0,00_0,00_0,00_albA1g2F6vI=_2354b4e6f42a3a6b_**Xpx1kEb/GNk=**_**U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==**",

 /* 03 A-SIT suite 1 cashbox 1 receipt 08  */ 
"_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-8_2016-09-05T15:36:50_91,22_198,23_89,89_172,01_3,84_VFJB_c2148316e9b79f78_**7RzU15NMudg=**_**U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==**",

[...]
	
/* 07 A-SIT suite 1 cashbox 1 receipt 12  */ 
"_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-12_2016-09-05T15:36:50_0,00_0,00_0,00_0,00_0,00_qpYfQmO7L0U=_c2148316e9b79f78_AZfhjRyhuZc=_**gTlBdlBBy1qgPzg4+uKk7b0afN1bq0B63ZWmYeDpHtw/3Ax98bMexYcyt9z67yLKxNLTDZAcAwDcqmYEsQnScQ==**",

**Comment by cmaxmedia** [comment]
Ok, nach nochmaligem durcharbeiten der Detailfragen und der Aufbereitung hab ich es jetzt sauber implementiert. Danke für die Untersützung!

**Comment by ErichFreitag** [comment]
Sehr fein. Lassen sie bitte auch unbedingt den RKSV-DEP-Export mit einigen Belegen durch das A-SIT-Prüftool laufen.

**Comment by cmaxmedia** [comment]
Hab das Prüftool grade ins laufen bekommen - Java ist eindeutig nicht mein Ding ;)
