### ISSUE TITLE
Der entschlüsselte Umsatzzähler hat einen Wert ungleich 0

### ISSUE THREAD

**Issue by RkRKlink** [a-sit-plus/at-registrierkassen-mustercode#236]
Guten Tag,

ich hab jetzt bei meinem DEP den Fehler das der Umsatzzähler ungleich 0 sein soll.
Da ich mich mit Java auch nicht so gut auskenne weiß ich nicht woran es eventuell noch liegen könnte.

Danke schon mal im vorraus =)

[DEP.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/704023/DEP.txt)
[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/704024/cryptographicMaterialContainer.txt)

**Comment by RkRKlink** [comment]
Schreibe mein Programm mit C#

**Comment by ErichFreitag** [comment]
Bitte um die Info, was das Prüftool dazu ausgibt.

**Comment by RkRKlink** [comment]
![image](https://cloud.githubusercontent.com/assets/24695839/21926616/cff774c0-d982-11e6-92e7-0641e7754a03.png)

**Comment by ErichFreitag** [comment]
Die Detailinformationen dazu sollten ihnen weiterhelfen. Soweit ich es rauslesen kann hat der erste Beleg = Startbeleg einen Umsatzzähler ungleich 0.

**Comment by RkRKlink** [comment]
Aber der Wert den er verschlüsselt ist 0, deswegen weiß ich nicht wo der Fehler liegt.

**Comment by ErichFreitag** [comment]
Zunächst mal daran, dass der AES-Schlüssel falsch ist:
"base64AESKey" : "WQRtiiy44Bv389U=",

Das müssen BASE64-codiert 44 Zeichen sein.

**Comment by RkRKlink** [comment]
Oje habe die Container txt datei nicht aktualisiert. Der Aes Schlüssel ist bereits angepasst
[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/704050/cryptographicMaterialContainer.txt)

**Comment by areiter** [comment]
Da stimmt wohl was an Ihrer Implementierung der Umsatzzählervershclüsselung nicht. Das lässt sich aber aus der Java Implementierung sehr gut ableiten. So groß sind da die Unterschiede zu C# auch wieder nicht.

**Comment by asitplus-pteufl** [comment]
Sie können da nur Schritt für Schritt vorgehen, prinzipiell kann der Fehler von zwei Prozessen kommen. die Aufbereitung des Umsatzzählers und dessen Verschlüsselung. Leider ist es im Prüftool nicht möglich festzustellen woher das kommt.

Ich würde die Aufbereitung im ersten Schritt mal ausschließen in dem Sie ein 8 byte Array mit dem Wert 0 verschlüsseln (alle Byte-Werte auf 0). Dann haben Sie mal etwaige Fehler bei der 2er K. Darstellung ausgeschlossen. Basierend darauf die Verschlüsselung adaptieren bis da mal ein korrektes Ergebnis rauskommt.
Wenn Sie das haben, dann den Fokus auf die Aufbereitung legen.

Links: Auch wenn Sie c# entwickeln, Java Code können Sie dann schon lesen, verstehen. Bitte unbedingt den Demo-Code zu Verschlüsselung/Aufbereitung anschauen. Da steht auch viel Text dabei. Ebenso das Detaildokument im Detail lesen, da wird das alles textuell beschrieben.

https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-common/src/main/java/at/asitplus/regkassen/common/util/CryptoUtil.java

Ebenso anschauen welche Methoden Ihnen in Ihrer Implementierung für die Verschlüsselung zur Verfügung stehen (wenn ICM, dann perfekt), wenn nur CFB/ECB dann einfach in oben genannten Methode schauen wie man das emuliert (steht auch alles im Detaildokument).

**Comment by RkRKlink** [comment]
Danke schon mal. Dann werd ich mich da noch mal durcharbeiten.

**Comment by cmaxmedia** [comment]
Vielleicht auch mal bei a-sign reinschauen. Die haben ein sehr schönes c# Beispielprojekt, was mir sehr weitergeholfen hat:
http://labs.a-trust.at/developer/source.aspx

**Comment by RkRKlink** [comment]
@cmaxmedia  genial danke ! 
Jetzt ist alles auf pass !
Danke an alle für die Hilfe!
