### ISSUE TITLE
Startbeleg via FON Webservice wird nicht akzeptiert...

### ISSUE THREAD

**Issue by rksvHackler** [a-sit-plus/at-registrierkassen-mustercode#237]
Guten Tag zusammen,
nach einigen guten Übermittlungen an den FON Webservice kommen derzeit immer wieder einige zustande, bei denen der Startbeleg nicht als gültig akzeptiert wird. Nachdem er technisch korrekt aussieht, interessiert mich ob es anderen auch so geht.
Die Hauptfehlermeldung ist:
"Der vorliegende Beleg ist zwar gesetzeskonform zustande gekommen, die Registrierkasse war aber zum Belegerstellungzeitpunkt im FinanzOnline „nur“ registriert. Bitte überprüfen Sie, ob in der Zwischenzeit die erforderliche Startbelegprüfung stattgefunden hat"

Was lustig ist, denn das ist der Startbeleg.

Die Fehlercodes sehen wie folgt aus:
FAIL:
  -> RECEIPT_FULL / FAIL
           STATE_CONSOLIDATED / FAIL
                 STATE_CASHBOX / FAIL

Zugegeben habe ich hier ein kleines Problem, nämlich dass im Startbeleg selbst die Uhrzeit mit 08:56 Uhr angegeben ist, während die Übertragung (auf einer anderen Maschine) um 08:55 Uhr durchgeführt wurde. (Uhrzeiten differieren halt etwas)
Die Übertragung selbst besteht aus 3 Übertragungen (einmal registrierung_kasse (um 08:55:53), danach registrierung_se (08:55:54) und dann eben die o.a. belegpruefung (08:55:55).

Kann ein solches Verhalten vielleicht jemand erklären?

Mit besten Grüßen
ein rksv_hackler

**Comment by asitplus-pteufl** [comment]
was sagt das prüftool zu dem beleg?

**Comment by aunterlu** [comment]
Ja, wir haben das auch bei ein paar Kunden (bei Überprüfung mit der App.). Anscheinend ein Bug bei FinanzOnline. Laut einem Kunden ist das dem Finanzamt bekannt.

**Comment by AxelKutschera** [comment]
Eine Anmerkung zum Zeitpunkt.
Mit dem BMF ist vereinbart, dass es bei einer Abweichung von bis zu 75 Minuten (in die Zukunft) zu keiner FON-Fehlermeldung kommt. 
Damit sind sowohl geringfügig abweichende Uhrzeiten auf dem Computer als auch Zeitdifferenzen bei Umstellung von Sommer- auf Winterzeit kein Problem.

**Comment by vejo** [comment]
@AxelKutschera 

Das mit dem BMF vereinbarte Zeitfenster ist sicher wohlüberlegt und funktioniert wohl auch in einer heilen Welt.
Wenn man aber davon ausgeht, dass ggf. zum Zeitpunkt der Inbetriebnahme der Kasse FON oder das Webservice gerade nicht erreichbar ist, oder gar die 7-tägige Meldefrist in Betracht zieht, sind diese Einschränkungen kontraproduktiv.
Sollte diesbezüglich in der Finanz-Online-Software nicht nachgebessert werden, steht am 1. April der ganze Laden.
Bitte um Anregung ans BMF, die Art der Prüfung noch einmal zu überdenken, zumindest für den ohnedies angespannten Startzeitpunkt Ende März / Anfang April.
Danke.

Siehe diesbezüglich auch Thread:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/223#issuecomment-272615765

**Comment by cmaxmedia** [comment]
In der BMF Belegcheck App, wird ein Startbeleg pro Kassen-ID nur einmal als Korrekt angezeigt. Bei weiteren Prüfungen des Startbeleges, ist die Kasse ja schon in Betrieb genommen. Alle anderen Belege, außer des Startbeleges, können beliebig oft, ohne Fehlermeldungen, geprüft werden.

Fehlerhafter Beleg: http://wiki.envira.at/index.php?title=Datei:Fon_13.jpg
Korrekter Startbeleg, aber Kasse bereits in Betrieb: http://wiki.envira.at/index.php?title=Datei:Fon_14.jpg

Es empfiehlt sich, nach erfolgreichen Entwickeln, die Registrierkasse in FON zu deaktivieren...

**Comment by eczach** [comment]
einer meiner kunden (bei einer kassa keinerlei problem, bei der anderen die fehlermeldung) hat nun auch diese meldung erhalten:
"Der vorliegende Beleg ist zwar gesetzeskonform zustande gekommen, die
Registrierkasse war aber zum Belegerstellungzeitpunkt im FinanzOnline „nur“
registriert. Bitte überprüfen Sie, ob in der Zwischenzeit die erforderliche
Startbelegprüfung stattgefunden hat."
ist dies nun tatsächlich ein problem bei FON? wie kann ich hier am besten weiter recherchieren.

**Comment by giemes** [comment]
@eczach siehe #223 - @asitplus-pteufl hat die Antwort vom BMF bekommen ...

**Comment by eczach** [comment]
danke für den hinweis - merke gerade dass der titel des issues nicht ganz passt - werde ein neues issue deswegen aufmachen
