### ISSUE TITLE
FinanzOnline Webservice PHP/Java/C++ integration

### ISSUE THREAD

**Issue by envomer** [a-sit-plus/at-registrierkassen-mustercode#238]
Hallo.

Hat jemand vielleicht eine Ahnung wie man den Registrierkassen Webservice von FinanzOnline in PHP/Java/C++ oder irgendeine andere Programmiersprache benutzen kann?

Ich habe bis jetzt nur eine login session generieren können, konnte aber keine Sicherheitseinrichtung anmelden.

So schaut mein jetziger PHP code aus.
```php
$requestParams = array(
	'tid' => $teilnehmerId, // ist ein 12-stelliger string
	'benid' => $benutzerId, // ist ein 9 stelliger string
	'id' => $loginSession, // ist ein 25 stelliger string
	'art_uebermittlung' => "T",
	'erzwinge_asynchron' => false,
	'rkdb' => array(
		'fastnr' => 99,
		'paket_nr' => 1,
		'ts_erstellung' => '2017-01-14T09:00:00',
		'registrierung_se' => array(
			'satznr' => 99,
			'kundeninfo' => '99',
			'art_se' => 'SIGNATURKARTE',
			'vda_id' => 'AT9',
			'zertifikatsseriennummer' => '75BCD15',
		),
	),
);

$client = new \SoapClient('https://finanzonline.bmf.gv.at/fonws/ws/regKasseService.wsdl');
$response = $client->rkdb($requestParams);
```

Zurzeit bekomme ich nur eine 'Validation error' Meldung zurück. 
```
cvc-complex-type.2.4.a: Invalid content was found starting with element 'tid'. One of '{"https://finanzonline.bmf.gv.at/rkdb":tid}' is expected.
```
Kann mir da jemand vielleicht helfen?

**Comment by cmaxmedia** [comment]
Hier brauchen Sie einen Aufruf mit Parameter:
```
$payload = array(
	'tid' => $teilnehmerId,
	'id' => $loginSession,
	'benid' => $benutzerId,
	'art_uebermittlung' => "T",
);
$belpruef = array(
	'fastnr' => "92",
	'paket_nr' => "112",
	'ts_erstellung'=>"2017-01-14T17:15:00",
	'belegpruefung'=>array(
		"satznr"=>1,
		"beleg"=>"_R1-ATx_CASHBOX-DEMO-1_CASHBOX-DEMOxxx"
	)
);
$client = new SoapClient('https://finanzonline.bmf.gv.at/fonws/ws/regKasseService.wsdl');
$client->__soapCall("rkdb", array( $payload, $belpruef ));


```

**Comment by envomer** [comment]
@cmaxmedia Habe den code umgeändert, aber noch immer den gleichen Fehler.
Echt komisch.

**Comment by cmaxmedia** [comment]
Sorry, ich hab gestern den falschen Response interpretiert ;(

**Comment by envomer** [comment]
@cmaxmedia Kein ding und danke.

Wissen Sie vielleicht ob es irgendwo eine implementation von FO-Webservice gibt? Egal welche Programmiersprache.

**Comment by duxthefux** [comment]
Habe das selbe Problem. Bekomme nur "Validation Error" retour?

**Comment by duxthefux** [comment]
<img width="890" alt="bildschirmfoto 2017-01-18 um 18 40 10" src="https://cloud.githubusercontent.com/assets/6758162/22075744/88877408-ddad-11e6-924d-6912c7ee8015.png">

bekomme nur das retour...
cvc-complex-type.2.4.b: The content of element 'ns1:loginRequest' is not complete. One of '{"https://finanzonline.bmf.gv.at/fon/ws/session":tid}' is expected.

**Comment by hardmuf** [comment]
hallo,

können sie vielleicht den request posten den sie schicken?

ich würde einmal darauf tippen dass der teilnehmerid (tid) nicht bzw.
falsch übermittelt wird.


Am 18.01.2017 6:40 nachm. schrieb "duxthefux" <notifications@github.com>:

**Comment by duxthefux** [comment]
```
$url     = "https://finanzonline.bmf.gv.at/fonws/ws/sessionService.wsdl";
$context = stream_context_create(array(
	'ssl' => array(
		'verify_peer' => false,
		'verify_peer_name' => false,
		'allow_self_signed' => true
	)
));

try {
	$client = new SoapClient($url, array(
			'stream_context' => $context,
			"trace" => true,
			'soap_version'   => SOAP_1_1
	));
	$res = $client->__soapCall("login", array("tid" => "xxx", "benid" => "webuser1", "pin" => "Test1234", "herstellerid" => "ATU123456789"));
} catch(Exception $e){
	dd($e);
}
```

**Comment by hardmuf** [comment]
ich hab eigentlich den tatsächlichen soap request / trace gemeint....

Am 18.01.2017 6:46 nachm. schrieb "duxthefux" <notifications@github.com>:

$url     = "https://finanzonline.bmf.gv.at/fonws/ws/sessionService.wsdl";
$context = stream_context_create(array(
	'ssl' => array(
		'verify_peer' => false,
		'verify_peer_name' => false,
		'allow_self_signed' => true
	)
));

try {
	$client = new SoapClient($url, array(
			'stream_context' => $context,
			"trace" => true,
			'soap_version'   => SOAP_1_1
	));
	$res = $client->__soapCall("login", array("tid" => "xxx", "benid" =>
"webuser1", "pin" => "Test1234", "herstellerid" => "ATU123456789"));
} catch(Exception $e){
	dd($e);
}

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/238#issuecomment-273547380>,
or mute the thread

**Comment by duxthefux** [comment]
-trace: {▼
    2. SoapClient->__soapCall() ==> new SoapFault(): {▼
      src: {▼
        /Users/christopherfuchs/github/ready2order/backend/sys/fon.php:21: """
          \t));\n
          \t$res = $client->__soapCall("login", array("tid" => "16628226b663", "benid" => "webuser1", "pin" => "Test1234", "herstellerid" => "ATU69778145"));\n
          } catch(Exception $e){\n
          """
      }
    }
    1. {main} ==> SoapClient->__soapCall(): {▼
      src: {▶}
      args: array:2 [▼
        0 => "login"
        1 => array:4 [▼
          "tid" => "XXXX"
          "benid" => "XXX"
          "pin" => "XXXX"
          "herstellerid" => "XXX"
        ]
      ]
    }
  }

**Comment by hardmuf** [comment]
sorry ich meine den soap request bzw. den xml string der an finanzonline
 mittels get/post geschickt wird...

ich hab es heute mit c# programmiert und es hat ohne probleme funktioniert..

Am 18.01.2017 8:10 nachm. schrieb "duxthefux" <notifications@github.com>:

**Comment by duxthefux** [comment]
Puh ich weiß nicht wie ich den herausfinde? Ob das nicht der PHP Client intern macht? Wie ist es in c# gelöst? könnt ich den code sehen?

**Comment by cmaxmedia** [comment]
@envomer Jetzt passts

```
//Login
$payload = array(
	"tid"=>			$fon_tid,
	"benid"=>		$fon_benid,
	"pin"=>			$fon_pin,
	"herstellerid"=>	$fon_hersteller
);

$client = new SoapClient("https://finanzonline.bmf.gv.at/fonws/ws/sessionService.wsdl", array('trace' => $trace, 'exceptions' => $exceptions));
$response = $client->login( $payload );
print_r($response);
$fon_session_id = (string) $response->id;

//Beleg prüfen
$data = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns="https://finanzonline.bmf.gv.at/rkdb">
<SOAP-ENV:Body>
<rkdbRequest><tid>' . $fon_tid . '</tid>
	<benid>' . $fon_benid . '</benid>
	<id>' . $fon_session_id . '</id>
	<art_uebermittlung>T</art_uebermittlung>
	<erzwinge_asynchron>1</erzwinge_asynchron>
	<rkdb>
		<fastnr>999999999</fastnr>
		<paket_nr>1</paket_nr>
		<ts_erstellung>2017-01-14T17:15:00</ts_erstellung>
		<belegpruefung>
			<satznr>1</satznr>
			<beleg>_R1-ATx_CASHBOX-DEMO-1_CASHBOX-DEMO-d1-Receipt-ID-1_2016-06-29T23:21:02_0,00_0,00_0,00_0,00_0,00_4K6WEIOWIZ4AI===_30d4d15e_OIHSCNKOMKDNU===_RT33QOOYVPEIBLJVFXKRZMG5M6EYQDOG4CPJWIQMJQC37QCQSPI6EG2MPJPYUL2JE3WF6SEP2J4UFAUT7IJBOO2AONJHPTHDDSPXZPA=</beleg>
		</belegpruefung>
	</rkdb>
</rkdbRequest>
</SOAP-ENV:Body></SOAP-ENV:Envelope>';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://finanzonline.bmf.gv.at/fonws/ws/regKasseService.wsdl");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);

$headers = array(
	"Content-Type: text/xml; charset=utf-8",
	"Accept: text/xml",
	"Cache-Control: no-cache",
	"Pragma: no-cache",
	"SOAPAction: https://finanzonline.bmf.gv.at/rkdb",
	"Content-Length: " . strlen($data)
);

curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);


$response = curl_exec($ch);
curl_close($ch);
print_r($response);


```

**Comment by hardmuf** [comment]
@duxthefux

c# code kann ich morgen gerne posten, aber jetzt gibts eh ein schönes php
beispiel.... reicht das?



Am 18.01.2017 8:21 nachm. schrieb "cmaxmedia" <notifications@github.com>:

**Comment by envomer** [comment]
@cmaxmedia Dankeschön. Ist sehr hilfreich. CURL to the rescue ^^

Ich habe mich damit beschäftigt und festgestellt dass FinanzOnline PHP SoapClient requests nicht akzeptiert weil die Daten nicht dem prefix "ns1" beginnen. Würde man anstelle von ```<tid>XXXXX</tid>``` ->```<ns1:tid>XXXXX</ns1:tid>``` verschicken würde FinanzOnline diesen request akzeptieren.

Funktioniert nicht:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://finanzonline.bmf.gv.at/rkdb">
    <SOAP-ENV:Body>
        <ns1:rkdbRequest>
            <tid>XXXXXXXX</tid>
            <benid>XXXXXXX</benid>
            <id>XXXXXXXXXXXXX</id>
            <art_uebermittlung>T</art_uebermittlung>
            <erzwinge_asynchron>false</erzwinge_asynchron>
            <rkdb>
                <fastnr>999999999</fastnr>
                <paket_nr>112</paket_nr>
                <ts_erstellung>2017-01-18T20:03:45</ts_erstellung>
                <registrierung_se>
                    <satznr>99</satznr>
                    <kundeninfo>99</kundeninfo>
                    <art_se>SIGNATURKARTE</art_se>
                    <vda_id>AT9</vda_id>
                    <zertifikat>75BCD15</zertifikat>
                </registrierung_se>
            </rkdb>
        </ns1:rkdbRequest>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```


Funktioniert:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://finanzonline.bmf.gv.at/rkdb">
    <SOAP-ENV:Body>
        <ns1:rkdbRequest>
            <ns1:tid>XXXXXXXX</ns1:tid>
            <ns1:benid>XXXXXXX</ns1:benid>
            <ns1:id>XXXXXXXXXXXXX</ns1:id>
            <ns1:art_uebermittlung>T</ns1:art_uebermittlung>
            <ns1:erzwinge_asynchron>false</ns1:erzwinge_asynchron>
            <ns1:rkdb>
                <ns1:fastnr>999999999</ns1:fastnr>
                <ns1:paket_nr>112</ns1:paket_nr>
                <ns1:ts_erstellung>2017-01-18T20:03:45</ns1:ts_erstellung>
                <ns1:registrierung_se>
                    <ns1:satznr>99</ns1:satznr>
                    <ns1:kundeninfo>99</ns1:kundeninfo>
                    <ns1:art_se>SIGNATURKARTE</ns1:art_se>
                    <ns1:vda_id>AT9</ns1:vda_id>
                    <ns1:zertifikat>75BCD15</ns1:zertifikat>
                </ns1:registrierung_se>
            </ns1:rkdb>
        </ns1:rkdbRequest>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Danke nochmals :D

**Comment by cmaxmedia** [comment]
Leider bekomme ich "Es ist keine steuerliche Vertretungsvollmacht vorhanden." zurück. Weiß jemand, was man hier in den Tiefen von FON einstellen muss?

**Comment by AxelKutschera** [comment]
Ich kenne FON erst seit 20 Jahren... ;-)
Das bedeutet vermutlich, dass die Anmeldedaten:
<ns1:tid>XXXXXXXX</ns1:tid>
            <ns1:benid>XXXXXXX</ns1:benid>
            <ns1:id>XXXXXXXXXXXXX</ns1:id>

nicht mit der FASTNR zusammenpassen.
                <ns1:fastnr>999999999</ns1:fastnr>

**Comment by duxthefux** [comment]
Ich bekomme inzwischen folgende Meldung (sowhohl bei "Beleg prüfen" als auch "Registrierkasse anmelden"

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <ns5:rkdbResponse xmlns:ns5="https://finanzonline.bmf.gv.at/rkdb">
            <ns5:paket_nr>1</ns5:paket_nr>
            <ns5:ts_erstellung>2017-01-14T17:15:00</ns5:ts_erstellung>
            <ns5:result>
                <ns5:satznr>99</ns5:satznr>
                <ns5:rkdbMessage>
                    <ns5:rc>0</ns5:rc>
                    <ns5:msg></ns5:msg>
                </ns5:rkdbMessage>
            </ns5:result>
        </ns5:rkdbResponse>
    </soapenv:Body>
</soapenv:Envelope>`

Wie ist die zu interpretieren?

**Comment by cmaxmedia** [comment]
Responsecodes finden sich in der Doku: 
- https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/softwarehersteller-funktionen.html#heading__2
- https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/BMF_Registrierkassen_Webservice.pdf?5q37o6

**Comment by duxthefux** [comment]
Danke, aber das Dokument habe ich natürlich bereits. 

Ist  <ns5:rc>0</ns5:rc> der ResultCode? Dann würd dich mich schon auskennen

**Comment by cmaxmedia** [comment]
Denke schon, dass RC für Responsecode steht. Wenn lt. Doku der Responsecode 0 ist, dann wurde korrekt übermittelt. Komischerweise auch, wenn in einer produktiven Übermittlung der Inhalt des Belegs überhaupt nicht passt... Ich schätze, dass das Ergebnis dann über FON abgerufen werden muss?

**Comment by afill** [comment]
@AxelKutschera Wie läuft das mit der Vollmacht - Muss ich mir die von all meinen Kunden holen, oder gibt es eine Art GeneralVollmacht für den RK Webservice?

**Comment by AxelKutschera** [comment]
@afill 
Variante 1:
1. Wenn der Steuerpflichtigen (RegK-Betreiber) selbst einen FinanzOnline-Zugang hat, kann dieser den Webservice-Benutzer für sich selbst anlegen.

Variante 2: 
Eine Vollmacht kann sich **nur ein Steuerberater** und nicht der Kassenhersteller (-händler) vom Steuerpflichtigen (RegK-Betreiber) und auch nur einzeln holen. 
Diese Vollmacht wird in FinanzOnline eingetragen. 
Danach kann der Steuerberater in FinanzOnline einen Webservice-Benutzer anlegen.

Es gibt keine "GeneralVollmacht" für alle Steuerpflichtige.
Die Funktion ist in diesem Handbuch des BMF beschrieben. https://www.fiskaltrust.at/wp-content/uploads/2015/08/161108-BMF_Handbuch_Registrierkassen.pdf 

Einen Leitfaden mit der Übersicht zum Manipulationsschutz haben wir unter https://www.fiskaltrust.at/checklist

**Comment by afill** [comment]
Danke für die ausführliche Antwort

**Comment by envomer** [comment]
Danke an euch alle :D

**Comment by duxthefux** [comment]
Wie wandle ich den XML Response in ein Object um?

`$xml = new SimpleXMLElement($xmlResponse);` funktioniert nicht..gibt einfach ein leeres Object retour? 

Hat das schon wer gelöst?

Danke!

**Comment by afill** [comment]
`$xml = simplexml_load_string($curl_soap_response, NULL, NULL, "http://schemas.xmlsoap.org/soap/envelope/");
$ns = $xml->getNamespaces(true);
$soap = $xml->children($ns['soapenv']);
$encoded = $soap->Body->children($ns['ns5']);`

**Comment by Zerogiven** [comment]
Falls jemand ein paar Beispiele zum Verwenden der FinanzOnline Webservices in PHP sucht, hier gibts eine kleine Library von mir die einige der Services abdeckt: https://github.com/CSoellinger/php-fon-webservices

**Comment by AxelKutschera** [comment]
Eine andere Möglichkeit ist die Nutzung unserer lizenzkostenfreien Middleware: https://github.com/fiskaltrust oder https://docs.fiskaltrust.cloud
