### ISSUE TITLE
Vorgehen bei fehlerhafter Signatur

### ISSUE THREAD

**Issue by NikolausJaeger2001** [a-sit-plus/at-registrierkassen-mustercode#239]
Hallo,
wie sieht das korrekte Vorgehen bei einem Beleg mit fehlerhafter Signatur aus?
Wenn zb. beim Überprüfen des DEP festgestellt wird, das bei einem Beleg der Umsatzzähler nicht korrekt ist.

Danke

**Comment by AxelKutschera** [comment]
So schnell es geht, 
- Fehler herausfinden
- Fehler beseitigen
- Fehler dokumentieren
- Möglicherweise RegK stilllegen, über FON abmelden und eine neue RegK (neues DEP) registrieren.
- Warten, wie das Finanzamt den Fall bei einer Prüfung beurteilt.

- Im Einzelfall einen spezialisierten Steuerberater kosultieren

**Comment by NikolausJaeger2001** [comment]
So weit so gut, ich melde die Kasse in diesem Fall über FON ab. 
Wie sieht dann das dann aber aus wenn ich sie  wieder aktiviere?

- Kann die gleiche KassenID verwendet werden
- Muss eine neue Signatureinheit verwendet werden
-oder reicht es einfach erneut einen Startbeleg zu erstellen?

**Comment by ErichFreitag** [comment]
Sie können die gleiche Kassen-ID verwenden und sie müssen die Kasse neu in Betrieb nehmen = einen Startbeleg erzeugen. Siehe z.B. https://communities.wko.at/Kassensoftware/Lists/oTechnischerechtliche%20Fragestellungen%20zur%20RKSV/Flat.aspx?RootFolder=%2FKassensoftware%2FLists%2FoTechnischerechtliche%20Fragestellungen%20zur%20RKSV%2FAu%C3%9Ferbetriebnahme%20und%20Wiederinbetriebnahme%20einer%20Kasse&FolderCTID=0x01200200907C3B3FD56F92409366C063EF841033 oder Erlass 3.6.2 "...Eine außer Betrieb genommene Registrierkasse kann wieder in Betrieb genommen werden. Diese Inbetriebnahme unterliegt den allgemeinen Verpflichtungen der RKSV in Bezug auf die Inbetriebnahme der Sicherheitseinrichtung". Eine neue Signatureinheit brauchen sie nicht, das alte DEP müssen sie aufbewahren.

**Comment by AxelKutschera** [comment]
@ErichFreitag 
Muss man deiner Meinung nach bei der Neuinbetriebnahme ein neuer Startbeleg gemacht werden?
Varianten 
- einen alten Startbeleg nehmen
- oder einen anderen verfügbaren Beleg

Das sollte gehen (finde ich aber nicht so gut).

**Comment by ErichFreitag** [comment]
Ja, Axel, meiner Meinung nach muss ein neuer Startbeleg gemacht werden.

Ich habe das mal hinterfragt (siehe Link WKO oben), weil es an sich nicht logisch ist und technisch nicht notwendig. Man könnte ja eine abgemeldete Kasse auch ganz einfach weiterführen (sprich wieder in Betrieb nehmen, egal mit welchem Beleg).

Die Auskunft des BMF ist da eindeutig, z.B. "es sind eine neue Initialisierung, Startbelegerstellung und –prüfung erforderlich (Pkt. 3.5.3.3. und 3.6.2. des o.a. Erlasses)". Als Grund wird "Die Konsequenzen sind aus sicherheitstechnischen und prüfungstaktischen Überlegungen geboten" ausgeführt.

Soll sein. Und heißt für mich, dass Schlussbeleg = Außerbetriebnahme eine gewisse Endgültigkeit mit sich bringt.

**Comment by NikolausJaeger2001** [comment]
Vielen Dank.

**Comment by AxelKutschera** [comment]
Ich habe das nur so in den Raum gestellt, im Hinblick auf fehlerhafte Startbeleg-Prüfungen, beschrieben im Erlass Kapitel:
"3.5.3.3. Behandlung von Fehlersituationen bei der Startbelegprüfung"
...
"Bei der Initialisierung der Registrierkasse (Abschnitt 3.5.2.) kann eine neue oder die ursprünglich bekannt gegebene Kassenidentifikationsnummer verwendet werden. Als Verkettungswert laut Z 4 der Anlage zur RKSV im Startbeleg kann auch der Signaturwert des letzten Barumsatzes des bei der Außerbetriebnahme oder Standardsicherung gemäß § 7 Abs. 3 RKSV gesicherten Datenerfassungsprotokolls oder des ursprünglich erstellten Startbeleges verwendet werden."
