### ISSUE TITLE
BON zu Rechnung

### ISSUE THREAD

**Issue by ckvsoft** [a-sit-plus/at-registrierkassen-mustercode#24]
Wie wird der "BON zur Rechnung" gehändelt?

Ich erstelle eine Rechnung diese wird dann BAR bezahlt. In der Kasse gebe ich den Verweis zu einer Rechnungsnummer und trage den Brutto Betrag mit 0% MwSt. ein.

Im Summenzähler wird dieser dann berücksichtigt. Doch der Betrag ist Brutto und der Summenzähler Netto. Wenn ich aber den Nettobetrag eingebe steht am BON fälschlicherweise der NETTO Betrag. Wie ist damit umzugehen? Oder gibt es da ein Eigenes Kürzel?

Danke

**Comment by csokay** [comment]
Warum ist es ein Betrag mit 0%? 
Ich dachte eher ein Betrag mit 20% (oder halt entsprechend der Rechnung).

**Comment by ckvsoft** [comment]
Es ist zulässig auf diesem Beleg lediglich auf die Nummer der Rechnung zu verweisen und keine Aufschlüsselung der Umsätze nach Steuersätzen vorzunehmen, wenn die Rechnung zur Abfuhr der 
Steuerschuld schon im (elektronischen) Aufzeichnungssystem erfasst wurde. Die 
Erfassung in der Registrierkasse und der Ausdruck des Registrierkassenbelegs lösen 
keine Umsatzsteuerpflicht kraft Rechnung aus, weil dadurch keine zweite Rechnung 
iSd. § 11 UStG 1994 entsteht. Es ist zweckmäßig, den Registrierkassenbeleg als 
Zweitausfertigung zu kennzeichnen (Pkt. 2.4.13 im Erlass). Entscheidend ist der 
Zeitpunkt der Barzahlung und nicht, wann die Lieferung oder sonstige Leistung 
erbracht wird. Daher ist beispielsweise eine Anzahlung für eine noch nicht 
erbrachte Leistung oder eine nachträgliche Barzahlung elektronisch zu erfassen.

**Comment by ckvsoft** [comment]
Kann da keiner was dazu sagen?
Danke

**Comment by pteufl** [comment]
Klärung über BMF. Antwort sobald verfügbar.

**Comment by ckvsoft** [comment]
Ok, Danke.
Gibt es bei BMF ein Forum, bzw. eine Stelle wo man Fragen kann?

**Comment by Obritzberger** [comment]
Mich würde dieses Thema auch sehr interessieren - gibt es schon eine Antwort auf diese Frage wie eine Zielrechnung die später BAR bezahlt wird richtig aufbereitet sein muss?

**Comment by ckvsoft** [comment]
Noch keine Antwort.  Ab eigentlich hat es sich erledigt. Es ist jetzt ja auch der Summenzahlers Brutto.

Lg Christian

**Comment by asitplus-pteufl** [comment]
Antwort des BMF:
Der Summenzähler summiert die Bruttobeträge. Beim Erfassen einer Rechnung, die aus einem Warenwirtschaftssystem stammt und bereits Steuerpflicht auslöst, ist der Bruttobetrag unter der Steuerklasse „0 %“ in der Registrierkasse zu erfassen. Es genügt die Bezugnahme auf die Rechnungsnummer aus dem Warenwirtschaftssystem. Es müssen nicht die Einzelinhalte noch einmal eingegeben werden.
Das Kommentar von ckvsoft vom 20. Jänner war absolut richtig
