### ISSUE TITLE
Länge der Signatur

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#240]
Darf ich davon ausgehen, dass im Falle des Registrierkassenalgorithmuskennzeichens "R1" die von einer beliebigen Sicherheitseinrichtung gelieferte Signatur _immer_ 512 Bit (64 Byte) lang ist?

Eine Sicherheitseinrichtung, die eine Signatur mit einer (in unkodiertem Zustand) anderen Länge liefert, müsste also als ausgefallen betrachtet werden.

**Comment by ErichFreitag** [comment]
Ja, siehe auch https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/224. 

Ausgefallen würde ich nicht sagen, eher ein grundsätzliches Problem?

**Comment by lebail** [comment]
Vielen Dank.

Zum Glück ist es kein Problem, denn es tritt gar nicht auf ;-)

Ich bin nur gerade dabei, verschiedenste Plausibilitätsprüfungen einzubauen, und da dachte ich auch an die Prüfung der Länge der Signatur.
