### ISSUE TITLE
Zahlung mittels Kundenkonto

### ISSUE THREAD

**Issue by NikolausJaeger2001** [a-sit-plus/at-registrierkassen-mustercode#241]
Hallo,
wenn ein Kunde eine Bareinzahlung auf sein Kundenkonto tätigt ist das klarerweise ein Barumsatz.
Wird mit diesem Guthaben später ein Beleg bezahlt, ist  das nach meinem Verständnis ein unbarer Beleg im Sinne der Registrierkassenverordnung. 
Ist das korrekt?

**Comment by ErichFreitag** [comment]
Nicht unbedingt, weil ja bei der Bareinzahlung kein Umsatz stattfindet. Eher umgekehrt.

Was sind das für Fälle mit "Bareinzahlung auf Kundenkonto"? Bitte um ein Beispiel zwecks Verständnis.

**Comment by NikolausJaeger2001** [comment]
In der Gastronomie zb. ein Stammgast der im vorraus 100,- auf sein Kundenkonto einzahlt. Bei jedem Besuch werden die Konsumationen dann von diesem abgebucht.

Auch die Verwendung für eine Gutscheinkarte ist möglich.

**Comment by Flanelli** [comment]
Zahlungen auf ein Kundenkonto ohne dass dafür ein konkreter Geschäftsfall mit einer Geldforderung des Unternehmens dem Kunden gegenüber vorliegt stellt genauso wie ein Wertgutschein eine Verbindlichkeit des Unternehmens dem Kunden gegenüber dar. Daher wäre dies auch im jeweiligen Wert der zeitlich tatsächlichen Konsumation erst dann ein echter Barumsatz. Die Zahlung ohne Gegenwert ist dem kauf eines Gutscheines gleichzustellen.

**Comment by AxelKutschera** [comment]
Eine Ergänzung: 
Wenn bei der Konsumation kein Gutschein usw. verwendet wird, sondern zB ein Lieferschein erstellt wird, sehe ich das nicht als Barumsatz.

**Comment by ErichFreitag** [comment]
Hilfreich wenngleich unter der Überschrift "Automaten" sind vielleicht auch noch die Ausführungen im WKO-FAQ-Papier unter den Punkten 86ff, beispielsweise (Auszug) 

"Der Transfer von angelegten Guthaben aus dem Verfügungsbereich des Kunden in den Verfügungsbereich eines Unternehmers für die Bezahlung einer Leistung stellt wegen der Analogie zur Bezahlung mit Bankomat- oder Kreditkarte eine Barzahlung und damit aus Sicht des Unternehmers einen registrierkassen- und belegerteilungspflichtigen Barumsatz dar".

Eine "reine Barbewegung" wie Ein- oder Auszahlungen ist kein signierpflichtiger Barumsatz, korrekt.

**Comment by NikolausJaeger2001** [comment]
Wenn ein Beleg erstellt wird der bar bezahlt wird aber neben einigen anderen "normalen" Artikeln auch einen Wertgutschein(Verkauf) enthält, ist dieser auch ein Barumsatz oder?

Ebenso sollte  ein Beleg der mit gemischter Zahlung(Bar + Erlagschein) abgeschlossen wird  einen Barumsatz darstellen?

**Comment by ErichFreitag** [comment]
Umgekehrt gewissermassen :-)

Ein Wertgutschein alleine verkauft ist nicht signierpflichtig. Ein Wertgutschein gemeinsam mit anderen Artikeln schon, weil sich der Umsatz mitverändert und der Wertgutschein im 0%-Steuersatz angeführt wird.

Wenn ein Beleg teilweise bar bezahlt wird ist es auch ein Barumsatz, ja.

**Comment by AxelKutschera** [comment]
@Erich: das gilt in diesem Fall für Guthaben zB auf KundenKarten welche direkt abgebucht werden.

**Comment by NikolausJaeger2001** [comment]
Danke.

**Comment by ErichFreitag** [comment]
Danke, @Axel - ist mir klar, darum als "hilfreich" vermerkt. 

Und auch danke für deine und andere Ergänzungen und Kommentare - das Engagement und das Einbringen verschiedener qualifizierter Sichten von unterschiedlichen Personen mit diversesten Erfahrungen und Wissen ist denke ich für alle eine Bereicherung und zumindest für mich einzigartig in dieser Kombination.

**Comment by AxelKutschera** [comment]
@ErichFreitag 
Ebenfalls Danke - Networking soll ja ein Geben und Nehmen sein... ;-)
