### ISSUE TITLE
Sammelbeleg 'einfügen'

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#242]
In einem der bisherigen Issues schrieb @ErichFreitag:

Ein Sammelbeleg ist zu erstellen, wenn die Signaturerstellungseinheit ausgefallen war und wieder verfügbar ist. Er wird typisch nach einem wieder signierbaren Beleg als signierter Nullbeleg **eingefügt**.......

Was heisst in diesem Fall eingefügt?

Wird der Sammelbeleg von Beleg-Nr her nach der Speicherung des ersten gültigen Beleges (nach dem Ausfall) mit einer höcheren Beleg-Nr gespeichert z.B.:
Beleg-Nr 10: Signatureinheit ausgefallen
Beleg-Nr: 11: Signatureinheit wieder OK
Beleg-Nr: 12: Sammelbeleg
 
oder wird der Sammelbeleg vor dem ersten gültigen Beleg (nach dem Ausfall) gespeichert (d.h. Sammelbeleg hat eine niedrigere Beleg-Nr)?
Beleg-Nr 10: Signatureinheit ausgefallen
Beleg-Nr: 11: Sammelbeleg
Beleg-Nr: 12: Signatureinheit wieder OK

Danke.

**Comment by lebail** [comment]
Es sind beide Varianten zulässig.

Ursprünglich war von der RKSV nur die zweite Variante vorgesehen, der zugehörige Erlass gestattet aber auch Variante 1, die technisch einfacher zu realisieren ist.

**Comment by AlgoLinz** [comment]
Danke @lebail
