### ISSUE TITLE
Frage zur Installation von "Unlimited Strength Policy" von Oracle"

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#244]
Guten Tag,
ich hoffe ich bin hier im Forum mit meiner Frage richtig.
Unser Registrierkassensystem wurde vor Jahren in "PowerBasic" geschrieben und jetzt an die RKSV Vorschriften angepasst.
Um sicherzustellen dass alles korrekt implementiert wurde möchte ich das Prüftool aus dem Registrierkassen Mustercode nutzen.

Leider habe ich mit Java überhaupt keine Erfahrung konnte aber mit den Erläuterungen von README.MD Java soweit auf meinen PC (Win10) installieren und auch den Code entpacken.

Lediglich bei der Installation der Kryptografie policy "local_policy.rar" klemmt es noch.
Wenn ich diese mit: java -jar local_policy.rar, im Verzeichniss in dem der Democode abgelegt ist, ausführe bekomme ich die Meldung: "kein Hauptmanifestattribut, in local_policy.rar"

Ich bitte um Hilfe.
Vielen Dank !

**Comment by ErichFreitag** [comment]
Soweit ich das nachvollziehen und mich erinnern kann müssen sie nicht die local_policy.jar ausführen, sondern die bestehende Datei im Verzeichnis ..\lib\security damit ersetzen. Zwecks eventuellem Restore können sie die bestehende Datei umbenennen und die neue ebenso, das sieht dann bei mir so aus:

![java_security_policy](https://cloud.githubusercontent.com/assets/18228048/21994529/6d3e0696-dc20-11e6-8dfd-2a98b5559c9a.JPG)

**Comment by Skerge12** [comment]
Vielen Dank für die Info.

Jetzt bekomme ich beim Aufruf:  "java -jar regkassen-demo-1.0.0.jar""
"turnover counter lengh in bytes is invalid, using lengh 8"
und dann:
 "Executing Simulation run: Testsuite_Test_Szenario_1 
 ....   bis 8

Ich nehme an das ist jetzt richtig so ?

**Comment by cmaxmedia** [comment]
Folgende Schritte haben bei mir funktioniert, um den DEP Export zu prüfen:
1) Java Runtime installieren: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
2) JCE Policy 8 downloaden (http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) und in das Installationsverzeichnis (C:\Program Files\Java\jre1.8.0_111\lib\security) entpacken und vorhandene Dateien überschreiben

3) Datei "Stammdaten.json" erstellen und die notwendigen Daten eingeben:

```
{
  "base64AESKey" : "AES Passwort eingeben",
  "certificateOrPublicKeyMap" : {
    "Zertifikat-HEX eingeben" : {
      "id" : "Zertifikat-HEX eingeben",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : "Zertifikat-SN eingeben"
    }
  }
}
```
4) BAT-Datei erstellen und Befehlszeile festlegen:
```
"C:\Program Files\Java\jre1.8.0_111\bin\java.exe" -jar "C:\Registrierkasse\regkassen-demo-1.0.0\regkassen-verification-depformat-1.0.0.jar" -v -f -i "C:\Registrierkasse\DEP_Export.csv" -c "C:\Registrierkasse\Stammdaten.json" -o "C:\Registrierkasse\Prüfausgabe"
pause
```
5) BAT Datei ausführen und das Beste hoffen ;)

**Comment by Skerge12** [comment]
1000 Dank :)

**Comment by ErichFreitag** [comment]
Um das oben noch zu ergänzen bzw. abzuschließen:

regkassen-demo liefert Testfälle. Ohne Angabe der Länge des Umsatzzählers wird 8 verwendet, soweit OK.

Für ihre Tests verwenden sie regkassen-verification-depformat-1.0.0.jar für den RKSV-DEP-Export, das ist das umfassendere Prüfwerkzeug (regkassen-verification-receipts-1.0.0.jar prüft nur einzelne Belege ohne Verkettung etc.).

**Comment by Skerge12** [comment]
Dankeschön :)

**Comment by Skerge12** [comment]
Guten Tag,
ich bin jetzt mit der RKSV Implementierung soweit fertig dass ich das Prüftool mit einem exportierten DEP laufen lassen möchte.
Dazu habe ich noch bitte ein Frage bezüglich des Json Files in welchem die Signaturdaten abgelegt werden müssen:

....
 "base64AESKey" : "AES Passwort eingeben",
  "certificateOrPublicKeyMap" : {
    "Zertifikat-HEX eingeben" : {
      "id" : "Zertifikat-HEX eingeben",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : "Zertifikat-SN eingeben"
...

> AES Passwort eingeben: damit ist der aes KEY gemeint ?    (AES Passwort ist für mich etwas verwirred)
> Zertifikat-HEX eingeben : Ist damit das Public Zertifikat gemeint das ich aus der Karte auslese. z.B.:  MIIFsDCCA5igAwIBAgINASo0/WflfWvLWNGxVjANBgkqhkiG9w0BAQsFADB7MQswCQYDVQQGEwJBVDENMAsGA1UECBMEV2llbjENMAsGA1UEBxMEV2llbjEjMCEGA1UEChMaZS1jb21tZXJjZSBtb25pdG9yaW5nIEdtYkgxKTAnBgNVBAMTIEdMT0JBTFRSVVNUIFJLUy1DQ..... usw ...

Vielen Dank für die Hilfe.

**Comment by asitplus-pteufl** [comment]
Es ist der BASE64-kodierte AES-Schlüssel. Können Sie mir die Quelle des Begriffs "AES Passwort eingeben" nennen. Das ist in der Tat die falsche Bezeichnung und sollte nicht in diesem Projekt so genannt werden. Falls dies dennoch wo passiert, muss das natürlich gleich korrigiert werden.

Sie brauchen nur die Seriennummer des Zertifikats angeben (im HEX-Format, exakt gleich wie im Beleg). Diese Infos finden Sie aber alle im Detailfragen Dokument, bzw. sehen Sie in den Demo-Outputs der DemoKasse

**Comment by perler-at** [comment]
Hallo!
Wie komme ich auf den Wert "Zertifikat-SN"? In den Beispielen des Testtools (cryptographicMaterialContainer.json) ist dort eine lange Zeichenkette angegeben. Gehört dort stattdessen wirklich nur die Zertifikat Seriennummer ("Zertifikat-SN") hinein?
