### ISSUE TITLE
Jahresbeleg ohne Sicherheitseinrichtung.

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#245]
Ist es erlaubt weiter zu kassieren, wenn die Sicherheitseinrichtung am Jahresende und im nächsten Jahr nicht funktioniert ?

**Comment by ErichFreitag** [comment]
Da gibt es ein kleines Dilemma. 

Grundsätzlich können sie weiterarbeiten, eben mit ausgefallener Sicherheitseinrichtung. Und natürlich Fehlerbehebungsmaßnahmen zeitnah treffen.

Der Jahresbeleg muss aber korrekt signiert werden. Geprüft werden muss er bis spätestens 15. Februar. 

Als Ausweg schlage ich vor, dass sie trotzdem den (unsignierten) Monatsbeleg Dezember = Jahresbeleg erstellen (dann ist zumindest mal der Umsatzzähler und der Vorgang festgehalten) und dass sie dann raschest möglich einen signierten Nullbeleg erzeugen und erst diesen im Sinne des Jahresbelegs prüfen.

Wahrscheinlich noch wichtiger ist eine entsprechend nachvollziehbare Dokumentation.

**Comment by woko1754** [comment]
Danke für die Antwort.
Laut Readme ist ein Jahresbeleg ohne Signierung nicht erlaubt. Ich denke es währe am einfachsten die Kasse solange zu sperren, bis die Sicherheitseinrichtung wieder läuft, damit der Jahresbeleg nicht vergessen wird.

**Comment by ErichFreitag** [comment]
Der Jahresbeleg ohne Signierung ist nicht erlaubt, der Monatsbeleg schon. Eine Kassensperre ist natürlich auch eine Möglichkeit, verhindert aber nicht, auf den Jahresbeleg bei Wiederfunktion vergessen zu können.

**Comment by mrpipe** [comment]
In den Daten welche signiert werden wird ja nicht unterschieden ob Monatsbeleg, Jahresbeleg oder normaler
Zahlungseingang. Es gibt nur NULL Belege oder welche mit einem Betrag. Ich habe mal versucht was das
Prüftool dazu sagt. Und dieses markiert NULL-Belege, welche nicht signiert sind mit einem FAIL und es steht da: "Dieser Nullbeleg wurde nicht kryptographisch signiert. Ein Nullbeleg muss über eine gültige Signatur verfügen." Nachfolgende Belege, welche dann wieder signiert sind bekommen ein PASS. Auch Belege mit Betrag und ausgefallener Signatureinrichtung werden mit einem PASS makiert.

Jetzt die Frage, darf das DEP denn überhaupt unsignierte NULL Belege enthalten, oder anders gesagt gibt
es Fälle bei denen es OK ist, dass das Prüftool ein FAIL ausgibt?

**Comment by ErichFreitag** [comment]
Auf der Startseite steht unter 18.11.2016 Signieren von Nullbelegen welche zulässig sind und welche nicht und wie sich das Tool Version 1.0.0 dazu verhält.

**Comment by mrpipe** [comment]
Vielen Dank, jetzt ist es klar.
