### ISSUE TITLE
Kurze APDU Frage:

### ISSUE THREAD

**Issue by Georg632** [a-sit-plus/at-registrierkassen-mustercode#246]
1)
Aus dem Test APDU Code:
String pin = "123456";

            byte[] signature = null;
            for (int i = 0; i < 10; i++) {
                Stopwatch sw = new Stopwatch();
                sw.Restart();
                signature = smartCard.sign(pin, hash);
                sw.Stop();
                Console.WriteLine("time taken for signature with selection:  " + sw.ElapsedMilliseconds + " ms");
            }

Wie ist der Pin definiert? Ich kann da eingeben was ich will und es funktioniert.

2)
Den ZDA kann man mittels APDU nicht auslesen oder?

Lg

**Comment by ckvsoft** [comment]
Näheres ist in der Datei "SmardCard_ACOS.cs" und SmartCard_CardOS_5.3.cs zu finden.
Grundsätzlich macht es jeder Anbieter anders und ist auch für jede Karte anders zu händeln. Dieses Beispiel ist für AT1
Achtung, bei mehrmaliger Falscheingabe ist die Karte gesperrt.

**Comment by ckvsoft** [comment]
Die ZDA kann man nicht auslesen. Anhand der ATR kann man aber feststellen um welchen Zertifizierungsdienstanbietern es sich handelt.

**Comment by asitplus-pteufl** [comment]
Da das eine VDA-relevante Frage ist, kann A-SIT Plus hier keine Auskunft geben. Ich schließe dieses Issue.
