### ISSUE TITLE
Welche Teile des Vorbelgs müssen für die Berechung des SIG-Voriger-Beleg herangezogen werden? 

### ISSUE THREAD

**Issue by Sec4AT** [a-sit-plus/at-registrierkassen-mustercode#247]
Ich habe da leider noch ein Verständnis Problem mit der Verkettung der Belegen.

Wenn ich eine Rechnung Signierte erhalte ich wenn alles funktioniert eine BASE64-URL / JWS-Signatur mit den Beispielwert  eyJhbGciiqJBAzI1NiJ1.
Für die Verkettung beim nächsten Beleg darf ich einfach den Wert den Vorbeleges verwenden "eyJhbGciiqJBAzI1NiJ1" oder muss ich aus den elf Datensätzen mit den Wert neu errechnen?

Danke
Sec

**Comment by ErichFreitag** [comment]
Wie die Verkettung funktioniert lesen sie bitte im A-SIT-Dokument "Detailfragen" unter Punkt 2.4 nach. Kurz gesagt bilden sie außer beim Startbeleg einen Hashwert über die Inhalte des vorhergehenden Belegs.

Ihr Beispiel des Signaturwerts sieht seltsam aus, aber das ist eine andere Sache.

**Comment by cmaxmedia** [comment]
Die JWS Signatur wird am besten in den Detailfragen unter 3.1 Erstellung der JWS Signatur erklärt. Diese besteht aus 3 Teilen mit . getrennt:

- der erste Teil bleibt immer gleich und besteht bestenfalls aus dem Base64URL-Wert von {"alg":"ES256"} also eyJhbGciOiJFUzI1NiJ9
- der zweite ist der Payload, welcher bei jedem Beleg aufbereitet wird und den Signaturhash des vorigen Beleges enthält (was die eigentliche Verkettung bewerkstelligt)
- der dritte ist die eigentliche Signatur, welche bezogen werden muss. Ist die SEE ausgefallen und es kann nicht signiert werden, so muss dieser dritte Teil aus dem Base64URL kodierten Text "Sicherheitseinrichtung ausgefallen" bestehen
