### ISSUE TITLE
Frage bezüglich Generierung eines neuen DEPs bei Erzeugung Startbeleg

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#248]
Wenn ich für eine Registrierkasse einen Startbeleg erzeuge, muss ich dann ein neues DEP generieren oder kann ich das vorhandene, in dem ja bisher unsignierte Einträge vorhanden sind,  weiter nutzen ?
Falls ich es weiter nutzen kann: Wie findet das Prüftool heraus ab wann gültige Signaturen vorliegen sollten ?

**Comment by ErichFreitag** [comment]
Die Erzeugung eines Startbelegs und die Einrichtung des RKSV-DEPs sind praktisch untrennbar miteinander verbunden. Der erste Eintrag im RKSV-DEP muss daher der Startbeleg sein.

Das RKSV-DEP ist aber nur ein Add-on zu den bestehenden Datenerfassungsprotokollen, sprich Kassenjournalen. Dieses können und müssen sie weiter verwenden, ab dem Startbeleg = RKSV-Inbetriebnahme gilt zusätzlich das RKSV-DEP.

**Comment by cmaxmedia** [comment]
Wenn das vorhandene DEP passt, warum nicht? Der Finanz wird es egal sein, wie viele Kassen-IDs bzw. Startbelege Sie in einer Tabelle führen oder ob sich andere Datensätze darin befinden.

Im Ergebnis müssen Sie halt sicherstellen, dass zu jeder Kassen-ID die korrekten Datensätze exportiert werden. Die Anforderungen der Finanz und des Prüftools sind hier eindeutig, nämlich ein Export eines korrekten, durchgängigen und lückenlosen DEP je Kasse
