### ISSUE TITLE
Signaturformat für Signierung durch Signaturerstellungseinheit

### ISSUE THREAD

**Issue by avosskoetter** [a-sit-plus/at-registrierkassen-mustercode#25]
Wie sieht die komprimierte Darstellung des Signaturformat für Signierung durch Signaturerstellungseinheit wirklich aus?

a) Wie in der Detailspezifikationen zur RKSV angegeben - mit Bezeichner des JSON-Feldes: _RKA_Wert(JSON-Feld)_Wert(JSON-Feld)_...

b) Wie im Mustercode und den Beispielen - ohne Bezeichner des JSON-Feldes: _RKA_Wert_Wert_... 

Die gleiche Frage gilt auch für die Daten die als maschinenlesbarer Code (QR-Code) gedruckt werden müssen und für die Daten die im DEP-Export landen.

**Comment by pteufl** [comment]
Sehr schnell geantwortet: im Sinne von B (A beschreibt dies aber auch gleich).

Wert(XXX) bezieht sich darauf dass der Wert extrahiert wird. Zur Sicherheit am besten die Beispiele vom Muster-Code beiziehen.

**Comment by avosskoetter** [comment]
Ok, Danke für die schnelle Info.
