### ISSUE TITLE
Eindeutigkeit des Initialisierungsvektors (IV) für AES

### ISSUE THREAD

**Issue by devobj** [a-sit-plus/at-registrierkassen-mustercode#250]
Hallo,

in den [Detailfragen der RKSV](https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.2-DOK/2016-09-05-Detailfragen-RKSV-V1.2.pdf) wird im Kapitel 2.5.2 folgendes beschrieben:
>  ACHTUNG  –  Hinweis  zur  Sicherheit:  Es  muss  garantiert  sein,  dass  für  jede 
Verschlüsselungsoperation,  die  mit  einem  gegebenen  AES-Schlüssel  durchgeführt  wird, 
niemals  der  gleiche  IV  verwendet  wird.  Dies  bedeutet  im  Wesentlichen,  dass  für  eine 
Kassen-ID jede Belegnummer nur einmal verwendet werden darf. >  

Es kann aber auch vorkommen, dass verschiedene Kassen die gleiche Verkettung von Kassen-ID und Belegnummer erzeugen.

Beispiel:
```
Kassen-ID: 1
Belegnummer: 11

Kassen-ID: 11
Belegnummer: 1

Verkettung ist jeweils: 111
```

Deshalb wäre es wohl am sichersten, wenn man für jede Kasse einen anderen AES-Schlüssel verwendet.

**Comment by AxelKutschera** [comment]
Das kann nicht passieren, da jede Kasse (jedes DEP) eine eigene, eindeutige Kassen-ID haben muss.
(An jeder Kasse können auch mehrere Eingabestationen angeschlossen werden.)

Natürlich kann auch für jede Kasse ein eigener AES verwendet werden.

**Comment by cmaxmedia** [comment]
Bei zwei verschiedenen Kassen-IDs ergibt sich derselbe IV, somit muss mMn ein anderer AES Schlüssel verwendet werden, obwohl die "1" als Kassen-ID vielleicht auch zu hinterfragen ist...

**Comment by cmaxmedia** [comment]
Gibt es eigentlich eine Niederschrift über die Fragestellung, ab wann eine neue Kassen-ID vergeben werden muss?

**Comment by ErichFreitag** [comment]
Das Tripel KassenID - Belegnummer - AES-Schlüssel muss auf Lebenszeit der Kasse eindeutig sein. Der Grund ist, dass man den AES-Schlüssel nicht durch mehrfach identische Operationen auf einen sich ändernden Umsatzzähler mit identem IV herausfinden können soll.

In ihrem Beispiel heißt das, dass man sowohl die Kasse 1 als auch die Kasse 11 und die zugehörigen Belege haben müsste. Da haben sie bei identem AES-Schlüssel schon grundsätzlich recht. Wie hoch dann allerdings die mathematische Wahrscheinlichkeit steigt, dass das schon signifikant einen Hinweis auf den AES-Schlüssel gibt kann ich nicht sagen. 

Ich vermute bei zwei Operationen noch eher gering. Selbst wenn - ich bin der Meinung, dass die Verschlüsselung des Umsatzzählers schon OK ist nur: wer fängt unbefugt mit den Daten (würde er sie errechnen können) wirklich etwas an? Ich weiß dann ungefähr den Umsatz einer Kasse und mit Glück (bei identem AES-Schlüssel) den ungefähren Umsatz aller Kassen (wenn ich zu den Daten komme). Den ungefähren Umsatz eines Unternehmens finde ich aber anders leichter heraus...

Wen jemandem dabei unwohl ist steht ja der Vergabe eines AES-Schlüsslels pro Kasse außer dem Verwaltungsaufwand nichts entgegen.

Damit zu neuer Kassen-ID: wenn das Tripel KassenID - Belegnummer - AES-Schlüssel nicht mehr eindeutig ist. Also eigentlich wohl nie.

Praktisch wird es sein, eine neue KassenID zu vergeben, wenn sie eine Kasse abmelden und eine neue anmelden (z.B. bei einem Defekt). Sie dürfen zwar wieder mit derselben KassenID anmelden, ich rate aber eher zu einer neuen (damit lassen sich alte und neue Kasse sauber trennen und dokumentieren und DEP-sichern etc.).
