### ISSUE TITLE
Ausfall Sicherheitseinrichtung

### ISSUE THREAD

**Issue by Phoniexk** [a-sit-plus/at-registrierkassen-mustercode#251]
Hallo,

Wenn die Sicherheitseinrichtung ausfällt muss als Signatur "Sicherheitseinrichtung ausgefallen" (Base64-URL codiert) verwendet werden. Nach dem Ausfall muss ein Sammelbeleg über die Belege mit Ausfall erstellt werden, aus dem Sammelbeleg muss Anfang und Ende des Ausfalls hervorgehen.

> Bei Ausfall der Signatur- bzw. Siegelerstellungseinheit ist gemäß §§ 17 Abs. 4 und 7 RKSV vorzugehen. Der nach dem Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit gemäß § 17 Abs. 4 RKSV erforderliche Sammelbeleg ist unmittelbar nach dem letzten Beleg bei ausgefallener Signatur- bzw. Siegelerstellungseinheit bzw. nach dem ersten Beleg bei wieder hergestellter Signatur- bzw. Siegelerstellungseinheit zu erstellen.

> Aus dem Beleg muss der Beginn und das Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit (zB: durch Angabe der jeweiligen laufenden Nummer) hervorgehen.

Folgendes Szenario:

1. Der Kunde verwendet RK Online von A-Trust.

1. Der Kunde erstellt den letzten Beleg des Tages. Signatur mittels RK Online nicht möglich (z.B. keine Internetverbindung)

1. Beleg wird (korrekt nach allen Vorgaben) mit "Sicherheitseinrichtung ausgefallen" gekennzeichnet

1. Der Kunde erhält eine Warnung über den Ausfall

1. Der Kunde ignoriert die Warnung und geht für 5 Tage in Urlaub

1. Nach 5 Tagen wird wieder ein Beleg erstellt. Die Sicherheitseinrichtung ist wieder funktionsfähig, ein Beleg mit gültiger Signatur wird erstellt

1. Aufgrund des vorhergenden Ausfalls wird ein Sammelbeleg erstellt. Über den Sammelbeleg ist ersichtlich dass der Ausfall 5 Tagen dauerte (da erst nach 5 Tagen wieder eine gültige Signatur erfolgte).

Für die Kassensoftware existiert nur der Beleg mit Ausfall vor 5 Tagen und der Beleg mit gültiger Signatur nach 5 Tagen. Deshalb ist laut Sammelbeleg die Zeitdauer des Ausfalls 5 Tage. Eigentlich sollte bei einem Ausfall der länger als 48 Stunden dauert, eine Meldung im FON erfolgen.

a) Die Frage ist nun, sind die 48 Stunden nur gültig wenn in diesem Zeitraum aktiv Belege erstellt werden? Kann in diesem speziellen Fall die Dauer des Ausfalls ignoriert werden (d.h. keine Meldung im FON nötig)?

Falls nur der Zeitraum aktiver Belegerstellung gilt, wie ist dass dann im Punkt b) zu sehen?

b) Sicherheitseinrichtung ist vor 5 Tagen ausgefallen (letzter Beleg), erster Beleg nach 5 Tagen ebenfalls ausfall, zweiter Beleg nach 5 Tagen -> Sicherheitseinrichtung funktioniert wieder. Gilt jetzt ein Ausfall länger als 48h Stunden der Meldepflichtig ist?

**Comment by ErichFreitag** [comment]
Die 48 Stunden gelten ab dem Moment, wo ein Beleg signiert werden soll und das nicht möglich ist. Und die 48 Stunden gelten ab dem ersten Ausfall. Anders macht es weder Sinn noch wäre es technisch einfach möglich.

Im Sammelbeleg müssen sie ja nicht das Datum angeben, sie können beispielsweise auch Belegnummern zur Kennzeichnung von Beginn und Endes des Ausfalls verwenden. Das entbindet aber auch nicht von den 48 Stunden. Wenn in den 5 Tagen keine Belege erstellt werden wird es aber auch nicht überaus tragisch sein einen dann nochbestehenen Ausfall unmittelbar zu melden - als Regel gibt es aber nur die 48 Stunden.

Bei vielen Systemen kommt nur eine einmalige Warnung, die Belege wird nicht jeder überprüfen. Die Warnung daher zu ignorieren - tja. Die Frage ist, wann es dann nach dem Urlaub auffällt... Im besten Fall kann man sich also noch mit einer Dokumentation des Vorfalls und des Urlaubs helfen.

**Comment by Phoniexk** [comment]
> Wenn in den 5 Tagen keine Belege erstellt werden wird es aber auch nicht überaus tragisch sein einen dann nochbestehenen Ausfall unmittelbar zu melden - als Regel gibt es aber nur die 48 Stunden.

Heißt aber in beiden Fällen a) und b) muss auf jeden Fall eine Meldung im FON erfolgen?

**Comment by ErichFreitag** [comment]
Formal gibt es nur die 48 Stunden-Regel, ja.

**Comment by Phoniexk** [comment]
Es ist aber immer die Rede von "nicht vorrübergehende Ausfälle" müssen gemeldet werden. Spricht etwas dagegen JEDEN Ausfall automatisiert via Webservice zu melden, auch wenn die SE nur bei einem einzigen Beleg ausgefallen ist (Zeitdauert des Ausfalls z.B. 1min)?

**Comment by ErichFreitag** [comment]
Dagegen spricht, dass die Regel eine andere ist, eben "nicht **nur** vorübergehende Ausfälle". Eine Minute ist wohl in diesem Sinne "vorübergehend".

**Comment by AxelKutschera** [comment]
Eine Anmerkung: 
Die 48 Stunden sind die Meinung des BMF.
In Kapitel 3.8 des Erlasses steht: "Von einem nur vorübergehenden Ausfall der Sicherheitseinrichtung in der Registrierkasse ist **jedenfalls bei Stromausfall, planmäßigen Wartungsarbeiten und anderen Ereignissen auszugehen, die zu einer Funktionsunfähigkeit der Sicherheitseinrichtung führen, die nicht
länger als 48 Stunden** andauert."
-- Und das ist so nur als Beispiel formuliert...

In § 17 Abs 1 RKSV steht, was gilt: "jeden nicht nur vorübergehenden Ausfall"

Das Finanzamt könnte im Einzelfall auch einen anderen Zeitraum verlangen.

**Comment by AxelKutschera** [comment]
Man darf alles melden, was man möchte.

**Comment by Phoniexk** [comment]
@AxelKutschera hat was die RKSV anbelangt recht.

§ 17 Abs 1 der RKSV:

> Der Unternehmer oder sein bevollmächtigter Parteienvertreter hat über FinanzOnline [.....] jeden **nicht nur vorübergehenden Ausfall** [.....] ohne unnötigen Aufschub bekannt zu geben.

Wir haben zusätzlich auch das Rechtsservice der WKO kontaktiert. Auch hier kam die klare Aussage: 

> Die RKSV schreibt vor dass jeder **nicht vorübergehende Ausfall** gemeldet werden **muss**. Die RKSV schreibt aber **nicht** vor, dass ausschließlich nur **nicht vorübergehende Ausfälle** gemeldet werden **dürfen**.

Auf explizite Nachfrage wurde bestätigt:

> **JEDER** Ausfall der Sicherheitseinrichtung kann im FinanzOnline gemeldet, auch wenn es sich um nur einen einzigen Beleg handelt und der **Ausfall nur vorrübergehen** war. Die RKSV beinhaltet nichts gegenteiliges.

Ich sehe das wie @AxelKutschera im Erlass ist nur ein Beispiel angegeben, was ein **vorübergehender Ausfall** bedeuten kann. Außerdem ist auch im Erlass nicht definiert, dass ausschließlich nur **nicht vorübergehende Ausfälle** gemeldet werden **dürfen**.

Damit ist für uns klar, wenn man das Webservice verwendet, kann jeder Ausfall im FON gemeldet werden, auch wenn es sich um einen einzigen Beleg handelt und der Ausfall eine Dauer von z.B. 1 min hatte. Damit wäre auch das Problem im ersten Post quasi erledigt, da die Meldung des Ausfalls mit dem letzten Beleg erfolgt und somit VOR dem Urlaub des Kunden.

**Comment by AxelKutschera** [comment]
Hier ist die Meinung des Erlasses und der WKO irrelevant. 

Ich meine (als Steuerberater), dass ALLES, was ein Steuerpflichtiger dem Finanzamt mitteilen möchte,  gemeldet werden darf.

**Comment by ErichFreitag** [comment]
Die RKSV spricht von "nicht nur vorübergehenden Ausfall", nicht von "nicht vorübergehender Ausfall".

Nur vorübergehend bedeutet "innerhalb eines bestimmten Zeitraums wieder verfügbar." NICHT nur vorübergehend bedeutet, "außerhalb eines bestimmten Zeitraums noch immer nicht verfügbar".

Ein (nur) vorübergehender Ausfall interessiert nicht, sondern nur länger dauernde Ausfälle. Bei einem vorübergehenden Ausfall wie Stromausfall als Beispiel im Erlass wissen sie ja im ersten Moment noch gar nicht, ob der Ausfall vorübergehend sein wird oder nicht. Daher kommen auch die 48 Stunden.

Somit automatisch jeden einzelnen Ausfall zu melden sehe ich nicht als Intention dieser Bestimmung. 

Wenngleich - dem Webservice wird es mehr oder weniger egal sein und besser zu melden als darauf wie auch immer zu vergessen. Und technisch gibt es dazu auch keine bekannten Einschränkungen plus dem von @AxelKutschera zuvor.

**Comment by AxelKutschera** [comment]
@Phoniexk Sorry - ich habe so lange an meinem Posting geschrieben, dass sich unsere Antworten überschnitten haben. ;-)
Vielen Dank für die ausführliche Unterstützung meiner Meinung!
