### ISSUE TITLE
Barzahlung/Teilzahlung von in Vergangenheit ausgestellter Rechnung

### ISSUE THREAD

**Issue by duxthefux** [a-sit-plus/at-registrierkassen-mustercode#252]
Hallo,

wie sind folgende Fälle korrekt abzubilden (auch bezügl. Umsatzzähler):

a) Kunde kauft Ware um 120 € Brutto auf Rechnung (Betrag soll überwiesen werden) ein.
Kunde kommt am nächsten Tag und will doch Bar zahlen.

Frage: Wie wirkt sich die dieser Fall (2 Fälle eigentlich) auf den Umsatzzähler aus? Da ja nur einmal die 120 € in den Umsatzzähler einfließen sollen und nicht 2 mal? Ersterer wäre ja nicht signaturpflichtig, was wenn man aber freiwillig alles signieren will?

b) Kunde kauft Ware um 120 € Brutto, zahlt davon 30 € bar und den Rest auf Rechnung (Betrag soll überwiesen werden) ein.
Kunde kommt am nächsten Tag und zahlt den Rest bar.

c) a) Kunde kauft Ware um 120 € Brutto auf Rechnung (Betrag soll überwiesen werden) ein.
Kunde überweist Betrag nach 7 Tagen erfolgreich aufs Konto.

Vielen Dank!

**Comment by lebail** [comment]
Bezüglich des Umsatzzählers ist es ganz einfach: Alles, was signiert wird und einen Betrag ungleich Null hat, wird zum Umsatzzähler addiert.

Ja, dadurch werden manche Beträge mehrfach im Umsatzzähler erfasst.

Das macht aber nichts, denn der Umsatzzähler dient trotz seines Namens nicht zur Ermittlung des Umsatzes, sondern ist lediglich Teil der Sicherheitseinrichtung.

**Comment by duxthefux** [comment]
Vielen Dank für die raschen Antworten!
