### ISSUE TITLE
Umsatzzähler im Java Demo

### ISSUE THREAD

**Issue by Martin78** [a-sit-plus/at-registrierkassen-mustercode#253]
Der Demo Code generiert 10 Belege inkl. Signaturen und speichert diese ab. 
Dabei wird, soweit ich verstanden habe, immer mit einem Umsatzzähler von 0 begonnen. Oder liege ich da falsch?
In DemoCashBox.java
```
    //internal turnover counter... starts with 0
    protected long turnoverCounter = 0;
```

Im Realfall muss dieser Umsatzzähler nach jeder Signatur abgespeichert werden. Das fehlt im Code, oder?
Ich nehme an, der Umsatzzähler muss verschlüsselt abgespeichert (Variable: el10_encryptedTurnOverValue) werden und beim Beginn eines jeden Signaturprozesses geholt und entschlüsselt werden? Wo finde ich das entschlüsseln im Code?

**Comment by ErichFreitag** [comment]
In der Realität läuft der Umsatzzähler vom Startbeleg mit 0,00 EUR bis zum Lebensende der Kasse immer weiter.

Wo und wie sie den Umsatzzähler speichern ist ihre Sache - im maschinenlesbaren Code und damit im DEP ist er verschlüsselt. Das Entschlüsseln finden sie an den selben Stellen wie encrypt, nämlich mit decrypt - siehe Dokument A-SIT-Detailfragen (suche nach decrypt).

**Comment by Martin78** [comment]
Danke
