### ISSUE TITLE
Wo ist die eigentliche Signatur im Sample Code?

### ISSUE THREAD

**Issue by Martin78** [a-sit-plus/at-registrierkassen-mustercode#254]
Ich kombiniere den Sample Code mit dem APDU Code von Atrust.
Vielleicht check ich es grad nicht aber ich frage mich wo genau eigentlich die Signatur gemacht wird?!? 
Ok, laut Kommentaren wird nur eine "nicht für Realsysteme zulässige" Software Signatur gemacht. 

Ich denke das passiert in signMachineCodeRepOfReceipt. Diese Methode implementieren unterschiedlichste Module wie z.b. ComNimbusdsJwsModule, ManualJWSModule oder OrgBitbucketBcJwsModule.
Laut Doku gibt es noch kein APDU Example. Das ist wirklich schade weil genau DAS am wichtigsten wäre, kommt es schließlich an realen Systemen am häufigsten zum Einsatz!

Dann gibt es noch das Package at.asitplus.regkassen.core.modules.signature.rawsignatureprovider. Diese Module implementieren eine Methode public byte[] signData(final byte[] dataToBeSigned) genau wie mein APDU Code den ich mit signMachineCodeRepOfReceipt verbinden möchte.

Wie genau mache ich das? Z.b. den Output von signMachineCodeRepOfReceipt in ManualJWSModule in ein byte Array wandeln und signData übergeben?

Warum wird signData in eurem Example nie aufgerufen?

**Comment by AxelKutschera** [comment]
Wer sich all diese Gedanken ersparen möchte, kann gerne unsere kostenlose Middleware und das Konfigurationsportal verwenden.

**Comment by areiter** [comment]
Im Github Democode sind deshalb keine APDU Beispiele enthalten weil diese abhängig vom gewählten ZDA, und dort sogar teilweise abhängig von der eingesetzten Smartcard OS Type und Version.

Sie bekommen diese Beispiele aber bei ihrem ZDA. 
Bei A-Trust bekommen sie diese hier [1], bei Globaltrust werden diese sobald die Partnervereinbarung steht zur Verfügung gestellt. Mit Primesign hab ich leider keine Erfahrung.

Was ist jetzt also ihre konkrete Frage? Das oben genannte sollte mit den A-Trust Beispielen abgedeckt sein

[1] http://labs.a-trust.at/developer/ShowSource.aspx?id=114

**Comment by Martin78** [comment]
Die Atrust Beispiele kenne ich. Ich habe nämlich genau diese auf meine Smartcardreader angepasst.

Meine Frage ist, wo genau soll ich mein signData(final byte[] dataToBeSigned) in Klasse ManualJWSModule einbauen?

Ich schätze in Zeile 65
`byte[] signatureResult = signature.sign();`

Stimmt das? Und wenn ja, benötige ich die nachfolgenden Zeilen auch:
`byte[] jwsSignature = CryptoUtil.convertDEREncodedSignatureToJWSConcatenated(signatureResult);
String jwsSignatureBase64Url = CashBoxUtils.base64Encode(jwsSignature, true);
return jwsHeaderBase64Url + "." + jwsPayloadBase64Url + "." + jwsSignatureBase64Url;`

Ich denke schon, wollt nur mal genau nachfragen.

**Comment by areiter** [comment]
Ja Zeile 65 klingt gut. 

Den Aufruf an `convertDEREncodedSignatureToJWSConcatenated(...)` brauchen sie nur wenn sie die Signatur in DER Encoding vorliegen haben.
Wenn sie direkt APDUs verwenden werden direkt die Aneinandergefügten `r` und `s` Werte zurückgeliefert, ohne das DER encoding drumherum. (zumindest bei aktuellen AT1 Smartcards)

Meiner Meinung nach würden sie also das Ergebnis ihrer Signaturerstellung direkt `jwsSignature` zuweisen

**Comment by Martin78** [comment]
Danke für die Hilfe, das werde ich so ausprobieren!

**Comment by Martin78** [comment]
Ich schaffe mittlerweile den Signaturprozess mittels APDU Commandos fast;)
das eigentliche APDU Kommando, das den Hash Wert signiert, kommt mit dem Fehler 6700 (Wrong length) zurück.
Ich verwende A-Trust Karten und in deren Doku signieren sie immer einen Haswert mit der Länge 32 Bytes. Mein Hashwert, also das vorgeschlagene jwsDataToBeSigned.getBytes() hingegen ist viel länger (143 Bytes).
Das lässt mich vermuten das ich das FALSCHE in die Signatur schicke! Was genau gehört den signiert?

Hat jemand einen Tipp für mich?

**Comment by ErichFreitag** [comment]
Vielleicht hilft ihnen das:

![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/22184719/57bc9a8c-e0d8-11e6-8ef0-41e771743b67.jpg)

**Comment by areiter** [comment]
Ich denke hier müssen sie jetzt unterscheiden. die Grafik von @ErichFreitag  hilft ihnen sicher dabei was zu signieren ist. Aber egal was (und von welcher Länge) sie in eine Hash-Funktion reinschicken, das Ergebnis wird immer die selbe Länge haben. Das sind bei SHA256 256bit bzw. 32Byte.

**Comment by Martin78** [comment]
Vielen Dank für die Hilfe!
Ich lasse es vorher durch eine Hash Funktion laufen:
`MessageDigest md = MessageDigest.getInstance("SHA-256");`
`md.update(jwsDataToBeSigned.getBytes());`
`byte[] jwsSignatureSHA256 = md.digest();`

und gebe dies anschließend meiner Signatur Karte:
`jwsSignature = signatureDevice.doSignatur(jwsSignatureSHA256, "123456");`

Ich denke das müsste so korrekt sein

**Comment by areiter** [comment]
Und welche Länge hat hier dann `jwsSignatureSHA256` ?
Vl. setzen sie in `signatureDevice.doSignatur(...)`  die Länge der APDU nicht richtig?

**Comment by Martin78** [comment]
jwsSignatureSHA256 hat jetzt 32 Byte da ich es durch die Hashfunktion laufen lasse. 
Die Signatur über die Smartcard funktioniert so jetzt.

**Comment by areiter** [comment]
Also läuft alles? Dann bitte Issue schließen

**Comment by smtm** [comment]
Ich finde die Grafik von @ErichFreitag echt gut um die Komplexität des Verfahrens zu illustrieren. Ich wäre froh gewesen diese früher entdeckt zu haben. Sollte, imho im README.md dieses Repos eingebaut werden.
