### ISSUE TITLE
BMF SOAP Schnittstelle

### ISSUE THREAD

**Issue by wpichler** [a-sit-plus/at-registrierkassen-mustercode#256]
Hallo,

lt. Auskunft bekommt man unter:
 https://communities.wko.at/Kassensoftware

Hilfe zur BMF SOAP Schnittstelle.

Ich bekomme dort aber mit meinem Benutzer wpichler@callino.at trotz Administrator Rechte keinen Zugang. Die Damen vom Support sind schon am abklären - aber vielleicht weiß ja jemand schon Bescheid an wen ich mich wenden kann, um da Zugriff zu bekommen.

Im Detail geht es um die RKDB SOAP Schnittstelle - welche auch über eine Funktion zur Status Abfrage verfügen sollte - ich konnte aber bis jetzt nicht rausfinden wie ich diese Funktion aufrufen kann. Die anderen Funktionen zur Registrierung / Auswfall usw. fkt. soweit problemlos.

**Comment by ErichFreitag** [comment]
Die Rechte für die WKO-Community gibt es unter https://communities.wko.at/default.aspx über Frau Mag. Elisabeth Klinger. https://www.wko.at/Content.Node/Mitarbeiterkontaktseite.html?rollenid=2753134

**Comment by Phoniexk** [comment]
Oder einfach an **ubit@wko.at**, dann kümmert sich der nächste "freie" Mitarbeiter darum ;)

**Comment by wpichler** [comment]
Ich wurde bereits bedient ;-) Besten Dank
