### ISSUE TITLE
Signierung von Nicht-Barumsätzen

### ISSUE THREAD

**Issue by Phoniexk** [a-sit-plus/at-registrierkassen-mustercode#257]
Hallo,

eine allgemine Frage an die Community:

a) 
Aus dem Erlass geht hervor dass bei einer freiwilligen Signierung von Nicht-Barumsätzen (z.b. durchlaufende Posten), **diese dem 0%-Umsatz zugewiesen gehören.** 

Aus der WKO-FAQ geht aus **4.6.6. Klarstellungen im Bereich Brutto/Netto, 0% und Umsatzzähler** unter dem Subpunkt **„Signierung von Nicht-Barumsätzen, wie Lieferscheine etc.“** folgendes hervor: 

> Nicht-Barumsätze dürfen freiwillig signiert werden, allfällige Beträge sind dann immer als 0%-Betrag zu buchen und in den Umsatzzähler mit dem 0%-Betrag aufzunehmen.

Nach diesem Satz gehört ein (freiwillig signierter) durchlaufender Posten unter „Betrag-Satz-Null“ eingetragen und der Umsatzzähler entsprechend angepasst.

Dabei ergibt sich aber folgendes Problem: 
1.	Registrierkasse wird in Betrieb genommen (Stand-Umsatzzähler: 0€).
2.	Es wird ein Beleg mit einer Bareinlage von 200€ freiwillig signiert (Stand-Umsatzzähler: 200€). 
3.	Der Betrieb kassiert den ganzen Tag nur Bargeld (Stand-Umsatzzähler: 5000€)
4.	Am Tagesende wird ein Beleg mit einer Barentnahme von 4800€ freiwillig signiert (Stand-Umsatzzähler: 200€)

Wenn der Unternehmen täglich nach Geschäftsende so viel Bargeld entnimmt, dass immer 200€ in der Kasse bleiben, dann wird der Umsatzzähler immer am Tagesende bei 200€ bleiben.

Ist das tatsächlich so vorgesehen? Ich nehme mal an, ich habe hier etwas falsch verstanden, bitte um Aufklärung.

b) Laut Erlass 4.6.6. Betrag der Barzahlung nach Steuersätzen (ab 2017) gilt:

> Belegbeträge, die dem Steuersatz 0% zuzuweisen sind, sind am Beleg nur dann als mit 0% zu versteuernde Umsätze auszuweisen, wenn es sich dabei um steuerfreie oder nicht steuerbare Umsätze handelt. Dies gilt im übrigen auch für durchlaufende Posten, die sich aus einer freiwillige Erfassung auf einem signierten Beleg befinden. In allen anderen Fällen genügt eine Anmerkung "inkl. USt" bzw. sollte beispielsweise der Hinweis "Nettobetrag und MwSt auf Bon ungültig, korrekte Angaben auf referenzierter Rechnung" am Beleg angebracht werden. 

Ein durchlaufender Posten mit 10% MWST, müsste demnach den 0%-Umsätzen zugwiesen werden, aber am Beleg selber mit 10% angeführt werden!?

Wie darf man diese Passage jetzt genau verstehen?

**Comment by AxelKutschera** [comment]
a) Das ist so vorgesehen. Der Umsatzzähler hat weder mit dem Umsatz zu tun noch mit dem Kassastand.
Die Option, dass alles signiert wird empfehle ich jedoch nicht, da die Kontrolle der Vollständigkeit durch das Finanzamt komplizierter wird. 
b) Durchlaufende Posten dürfen nach Wunsch der WKO auch in die Steuersätze aufgeteilt werden.
Die Anmerkungen sind nur für Zwecke der Umsatzsteuer um diese nicht doppelt zu schulden.

**Comment by lebail** [comment]
Aus dem unter b.) zitierten Text des Erlasses folgt aber meiner Meinung nach, dass man durchlaufende und freiwillig signierte Posten im Belegtext nicht als 0%-Umsatz ausweisen darf, obwohl sie im maschinenlesbaren Code bei den 0%-Umsätzen stehen.

Man muss im Belegtext bei der Aufstellung der Beträge nach Umsatzsteuersätzen also zwischen einerseits steuerfreien/nicht steuerbaren und andererseits sonstigen 0%-Umsätzen (durchlaufend/freiwillig) unterscheiden - und darf diese nicht einfach gesammelt unter 0% USt. angeben. Sehe ich das richtig?

**Comment by Phoniexk** [comment]
@AxelKutschera: 

Danke, dann ist a) für uns umissverständlich geklärt.

Bezüglich b) würde es dann heißen, dass ein Durchlaufer mit 10% MWST, auch als 10% MWST signiert werden darf und entsprechend am Belegtext mit 10% ausgewiesen wird?

**Comment by AxelKutschera** [comment]
b) Ja, dies erfolgt - zB wie bei Tankstellen - mit dem Hinweis auf den Durchlaufenden Posten.
"Mit * gekennzeichnete Beträge werden im Namen und auf Rechnung der **Mineralöl-Gesellschaft** vereinnahmt."

**Comment by Phoniexk** [comment]
Vielen Dank, alles klar!

**Comment by lebail** [comment]
@AxelKutschera: Vielen Dank!

Ein kleines Detail ist mir aber dennoch nicht klar. Es geht mir _nicht_ um die Auflistung der Posten selbst (da ist mir die Sache mit dem * klar), sondern um die am Ende des Beleges befindliche Aufschlüsselung der Zahlbeträge nach USt.-Sätzen. Ich ging bisher davon aus, dass diese exakt dieselben Inhalte zeigen soll wie die Betragsfelder des maschinenlesbaren Codes. Nun bin ich mir dessen aber nicht mehr sicher.

Wenn ich (neben 20%-Umsätzen von z.B. 50 €) sowohl steuerfreie 0%-Umsätze (z.B. 10 €) als auch Durchlaufposten (z.B. 20 €, mit * markiert) auf einem Beleg habe, muss die Aufschlüsselung am Ende des Beleges dann so aussehen:

20% USt.: 50,00 
0% USt.: 30,00

oder so:

20% USt.: 50,00 
0% USt.: 10,00
sonstige (*): 20,00

Die erste Variante würde genau den Angaben im maschinenlesbaren Code entsprechen, die zweite enthielte die zusätzliche Auftrennung der 0%-Umsätze.

Vielen Dank im Voraus!

**Comment by ErichFreitag** [comment]
Ich bin für die erste Lösung.
Erstens entspricht es dem maschinenlesbaren Code.
Zweitens entspricht es den angeführten Steuersätzen.
Drittens würde mich "sonstige" mehr verwirren als informieren.
Viertens wird bezüglich RKSV nicht zwischen echten und unechten 0%-Umsätzen unterschieden.

**Comment by lebail** [comment]
Vielen Dank für die Antwort. Auch ich bevorzuge Variante 1 - vor allem deshalb, weil ich sie schon seit langem fertig habe ;-)
