### ISSUE TITLE
Beleg zu Rechnung

### ISSUE THREAD

**Issue by Martin78** [a-sit-plus/at-registrierkassen-mustercode#258]
Wie gehe ich mit folgendem Fall um?
1) Er wird ein Zahlungsbeleg erstellt. Dieser hat eine eindeutige Nummer z.b. B101. Er wird Signiert und der Umsatzzähler dementsprechend geupdatet. 
2) Aus diesem Zahlungsbeleg (Nummer B101) wird nun eine Rechnung erstellt mit Nummer z.b. R16 wo Mwst., Kunde usw. aufgeschlüsselt ist. Der Betrag bleibt natürlich gleich.

Wie ist dabei vor zu gehen? Der Umsatzzähler ändert sich natürlich nicht. Wie mache ich die Signatur der neuen Rechnung?

Vorschläge:
1) Ich könnte die Signatur des Beleges nehmen uns nochmals auf die Rechnung drucken. Das geht aber nicht da verschiedene Belegnummern (B101 vs. R16 => Signatur falsch)
2) Ich könnte die Rechnung neu signieren. Aber mit welchen Beträgen? Der Umsatzähler darf ja nicht upgedatet werden.
3) Keine Signatur aber nur Verweis auf den signierten Zahlungsbeleg drucken

Oder gibts bessere Vorschläge?

**Comment by ErichFreitag** [comment]
Ich habe den Ablauf noch nicht verstanden: zuerst kommt ein Zahlungsbeleg und dann eine Rechnung?
Bei welchen Fällen kommt das vor? Warum wollen sie eine Rechnung signieren? Bitte um zusätzliche Infos.

**Comment by Martin78** [comment]
Die Kassa arbeitet so. Man kann z.b. aus mehreren Belegen einen Gesamtrechnung erstellen.
Der Normalfall ist natürlich das gleich eine Rechnung gedruckt wird, dann gibt es kein Problem.

Zahlungsbelege und Rechnungen haben unterschiedliche Nummernkreise.

**Comment by ErichFreitag** [comment]
Ok, danke. Dann noch die Frage - wozu wollen sie die Rechnung überhaupt signieren? Das ist nicht erforderlich, es geht zunächst nur um die Barumsätze und die scheinen sie ja korrekt abzuwickeln (also Variante 3 - keine Signierung).

Und Verweise auf die Zahlungsbelege, damit klar ist, dass die Rechnung oder dieser/jener Teil davon (bereits) mit Beleg sowieso bezahlt wurde (das ist aber kein RKSV-, sondern ein Steuer- und Buchhaltungsthema).

**Comment by Martin78** [comment]
Ok, vielen Dank für die rasche Antwort! Dann mach ich es einfach mit einem Verweis.

Einmal ein dickes Lob an die Leute hier im Forum! Die Reaktionsgeschwindigkeit ist unglaublich, egal ob unter Tags, Abends oder am WE! :)

Das Implementieren der RKSV ist nicht ohne. Aber dank des sehr guten a-sit-plus Java Democodes, den ich großteils reusen kann (unsere Kassa läuft auf Android) und diesem Forum ist es "einigermaßen" zügig umsetzbar.
