### ISSUE TITLE
Prüftool: Vermutlich konnte das Zertifikat oder der Schlüssel mit der im Beleg ...

### ISSUE THREAD

**Issue by Alex1130** [a-sit-plus/at-registrierkassen-mustercode#259]
Nachdem mir bei #194 geglückt ist von zwei Zertifikaten, das falsche auszuwählen, dachte ich bereits alle Fallangeln zu kennen...
Jetzt mit einer neuen Karte (CARDOS53 von A-Trust) habe ich ein neues Problem 
`````
"Die Prüfung des Belegs konnte nicht vollständig durchgeführt werden. Vermutlich konnte das Zertifikat oder der Schlüssel mit der im Beleg angegeben Seriennummer bzw. dem angegebenen Ordnungsbegriff des Unternehmens und der Schlüssel-ID nicht in der cryptographicMaterialContainer.json Datei gefunden werden. Bitte überprüfen Sie diese Datei und die darin hinterlegten Informationen. ..."
`````
ich habe 
* es mit Groß/Kleinschreibung probiert #157
* auf https://certlogik.com/decoder/  angeschaut ob das Zertifikat ähnlich ist wie das mittlerweile gut funktionierende (@erichfreitag ich danke für den link in topic #213)
* die Datei cryptographicMaterialContainer.json mit der funktionierenden verglichen ob ein formaler Fehler vorliegt.
Die beiden Vermutungen die mir bleiben sind - ich habe trotz aller Sorgfalt wieder ein falsches Zertifikat ausgewählt, oder beim Signieren mit der neuen Karte ist ein algorithmischer Fehler (ACOS04 geht gut, CARDOS53 geht nicht gut)

Die Werte des Test-Startbeleges:
`````
_R1-AT1_TRAXS-1_100104489_2017-01-25T05:52:43_0,00_0,00_0,00_0,00_0,00_/uzrQAEaYrrB9S1/yDAIIg==_52A870E5_j54s71si2uU=
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9UUkFYUy0xXzEwMDEwNDQ4OV8yMDE3LTAxLTI1VDA1OjUyOjQzXzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8vdXpyUUFFYVlyckI5UzEveURBSUlnPT1fNTJBODcwRTVfajU0czcxc2kydVU9.3ccH__713G21nejXRuMfPiKifCyLKOOdBBbM7VFtWHOl4bAtYKbBg74cCW49pxN6aQfV2XsoxZGAV0Qwz8q_TA
`````
[cryptographicMaterialContainer.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/730268/cryptographicMaterialContainer.json.txt)
[DEP_Kasse_1.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/730269/DEP_Kasse_1.json.txt)

**Comment by ErichFreitag** [comment]
In der ersten Zeile fehlt die Signatur - ist die zweite Zeile der DEP-Export-Eintrag dazu?

**Comment by Alex1130** [comment]
@ErichFreitag ja, die zweite Zeile ist der DEP-Export wie in der angehängten Datei, die erste Zeile ist das payload.

**Comment by ErichFreitag** [comment]
Wenn ich die Signatur aus dem DEP-Export auf BASE64 recodiere, dann ergibt die Prüfung bei mir "gültig". Bitte posten sie den maschinenlesbaren Code komplett, d.h. inklusive Signatur.

**Comment by ckvsoft** [comment]
@Alex1130 Die Signatur kommt OK zurück? Schaun sie sich den Democode und die APDUS an. In der Beschreibung für die CardOS53 ist ein Fehler bei den APDUs. Im C++ Code stimmt es.

**Comment by Alex1130** [comment]
@ErichFreitag 
`````
_R1-AT1_TRAXS-1_100104489_2017-01-25T05:52:43_0,00_0,00_0,00_0,00_0,00_/uzrQAEaYrrB9S1/yDAIIg==_52A870E5_j54s71si2uU=.3ccH//713G21nejXRuMfPiKifCyLKOOdBBbM7VFtWHOl4bAtYKbBg74cCW49pxN6aQfV2XsoxZGAV0Qwz8q/TA==
`````
Danke für Ihre Hilfe, es ist beruhigend, dass die Prüfung "gültig" ergibt. (Wie kann ich diese Prüfung selbst durchführen?)
Vermutlich bedeutet das auch, dass die Signatur erfolgreich verlaufen ist und die APDUs stimmen. @ckvsoft Ich habe sicherheitshalber noch den C++ Demo Code mit meinem C# Code und dem Developer Manual V0.2  verglichen und das scheint zu passen. (Zum Glück hatte ich nicht die falsche Beschreibung!)

Während mich das freut , verstehe ich nicht woran das Prüftool scheitert...

**Comment by ErichFreitag** [comment]
Mich beruhigt das noch nicht, dass meine Prüfung OK ergibt und jene des Prüftools einen Fehler.

Bitte posten sie das gesamte Result der Prütool-Prüfung (also das 0000_cashbox_full.json-file).

Ich prüfe das mit einem Tool von mir, das ist aus verschiedensten Gründen nur für mich verwendbar. Prüfen können wir, indem sie mir wie oben die Daten zukommen lassen.

**Comment by rhinterndorfer** [comment]
Bei mir kommt auch die Fehlermeldung "Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber ..." bei der Prüfung mit "regkassen-verification-depformat-1.0.0.jar".

Die Prüfung mit "regkassen-verification-receipts-1.0.0.jar" läuft erfolgreich durch. 
Habe nur einen Startbeleg generiert.

Ich habe die Base64 URL Kodierung geprüft und es scheint für mich in Ordnung zu sein.
Habe ich etwas übersehen?
Habe die Inhalte der Prüfdateien beigefügt.

[cryptographicMaterialContainer.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/733333/cryptographicMaterialContainer.json.txt)

[dep-export-wSg9954936361.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/733334/dep-export-wSg9954936361.json.txt)

[qr-code.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/733335/qr-code.json.txt)

**Comment by Alex1130** [comment]
@ErichFreitag 
[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/734533/0000_cashbox_full.json.txt)

**Comment by ErichFreitag** [comment]
Danke, @Alex1130. Ich bin jetzt ratlos, was dieses Thema betrifft. Das Zertifikat dürfte passen, die Seriennummer dürfte passen, die Einträge dürften passen. Meine Prüfung gibt OK, ihre Fehlermeldung sagt aus "Zertifikat/Seriennummer nicht gefunden".

Bitte @pteufl einen Blick darauf zu werfen.

**Comment by ckvsoft** [comment]
@Alex1130 Wenn ich die Datei cryptographicMaterialContainer.json.txt in meinen Editor lade habe ich ein Sonderzeichen vor der Zertifikatsnummer (0x200E)
`  "certificateOrPublicKeyMap" : {
    ---->>> hier --->>>".52A870E5" : {
      "id" : "52A870E5",`

vielleicht liegt es daran.

**Comment by ErichFreitag** [comment]
Super-Idee, @ckvsoft - sogar drei Sonderzeichen. Die scheint mein Editor zu unterdrücken. Bei mir läuft es jetzt mit Pass - danke!

**Comment by Alex1130** [comment]
@ckvsoft das war es! Habe vi hoch gefahren und tatsächlich da sah ich es auch!
Danke! Irgenwie verrückt (ich habe die Datei nur mit gedit bearbeitet - wie ich das Sonderzeichen eingefügt habe??? k.A. (google sagt 0x200e Unicode left to right marker)
Danke! Da wäre ich nie alleine drauf gekommen!
Danke @ErichFreitag für die Überprüfung und die vielen anderen hilfreichen Postsauch bei anderen Themen.

**Comment by asitplus-pteufl** [comment]
Kann man das schließen, oder gibt es noch offene Fragen (auch an mich)?

**Comment by Alex1130** [comment]
Anregung für eine spätere Version des Prüftools: Beim Parsen der strings im Prüftool "unsichtbare" Zeichen zu ignorieren oder in der Fehlermeldung genauere Angaben zu machen woran es scheitert (zB Zertifikat S/Nr im DEP ist x aber das Zertifikat S/Nr im CMC in Zeile N ist  y )
@asitplus-pteufl Somit schließe ich es jetzt.
