### ISSUE TITLE
DEP-Export bei Datenhaltung auf Server-Kasse

### ISSUE THREAD

**Issue by avosskoetter** [a-sit-plus/at-registrierkassen-mustercode#26]
Wie muss der DEP-Export aussehen, wenn die Datenerfassungsprotokolle mehrerer Kassen auf einer Server-Kasse geführt werden und die Signaturen durch die selbe Signaturerstellungseinheit erstellt wurden?

Es gibt im DEP-Export zwar die Unterscheidung zwischen den einzelnen Signaturerstellungseinheit über die Zertifikate/Seriennummer der Zertifikate, aber es gibt keine Unterscheidung mehrerer Kassenidentifikationsnummer die mit der selben Signaturerstellungseinheit arbeiten.

Muss hier ggf. eine Export-Datei pro Kassenidentifikationsnummer erstellt werden?

**Comment by pteufl** [comment]
DEP Export ist immer für eine Kassen-ID definiert. Wenn Sie z.B. eine Server-Lösung für mehrere Kassen-IDs haben, dann muss gewährleistet sein, dass der Export des DEPs pro Kasse (also Kassen-ID) möglich ist.

**Comment by avosskoetter** [comment]
Wie vermutet, Danke für die schnelle Info.
