### ISSUE TITLE
Detailfragen Dokument Link-Format

### ISSUE THREAD

**Issue by twisted-pear** [a-sit-plus/at-registrierkassen-mustercode#260]
Im Detailfragen Dokument steht bei den Beispielen für Prozess 4.4 folgedes:

    https://cashbox.example.at/receipts/machinereadablecode#HASH-VALUE-8-BASE64-
URL

Das kann aber nicht funktionieren, weil bei URLs das Anchor Element (der Teil hinter dem `#`) nicht übertragen wird. Das ist nur für den Client gedacht. Daher kann hier der Server so wie ich das sehe den gewünschten Beleg garnicht liefern.

**Comment by ckvsoft** [comment]
@twisted-pear  Das könnte zb. mit PHP ausgewertet werden (parse_url)

**Comment by twisted-pear** [comment]
Das mein ich nicht. Der Server hat überhaupt keinen Zugriff auf den Teil nach dem `#`. Das ist der "Fragment Identifier", der wird nicht gesendet. Siehe https://en.wikipedia.org/wiki/Fragment_identifier.

**Comment by ckvsoft** [comment]
@twisted-pear Alles Klar, javascript ist hier die Rettung ;-)
test at http://service.ckvsoft.at/fragment.php#FRAGMENT
`<script type="text/javascript">
var parts = location.href.split('#');
if(parts.length > 1) {
    var params = parts[0].split('?');
    var mark = '?';
    if(params.length > 1) {
        mark = '&';
    }
    location.href = parts[0] + mark + 'fragment=' + parts[1];
}
</script>

<?php
if(isset($_GET['fragment']))
{
    echo $_GET['fragment'];
}
?>`

**Comment by asitplus-pteufl** [comment]
Haben Sie auch die Spezifikation (4.4 Aufbereitung Link) gelesen? Auszug "Die URL kann dabei aus beliebigen Komponenten bestehen. Wesentliche Anforderung ist, dass ein Teil der URL (Teil des Pfades, als Parameter, als Fragment etc.) einem Teil des SHA256-Hash-Werts entspricht der über den maschinenlesbaren Code gerechnet wird." Auch die Beispiele zeigen dass andere Varianten möglich sind.
Daher: Sie müssen kein Fragment verwenden.

Warum sind Fragmente trotz der Nichtübermittlung des Browser enthalten: Weil es für die Prüfung des Links (Eingabe in App) egal ist. Das Fragment steht ja lokal zur Verfügung (weil eingegeben) und kann somit in der App gelesen werden. Der Call der dann auf den externen Server für den Belegabruf verwendet wird, mag das Fragment schon verlieren, nur ist das ja egal, solange der externe Server den korrekten Beleg bereitstellt. Der Hashwert kann ja nicht zwangsmäßig die ID für das Abrufen des Belegs aus der Datenbank sein. Da hat man ja möglicherweise andere IDs oder schon andere URL-Methoden vorgesehen (über den Pfad, als Parameter etc.), dann können Sie das Fragment einfach hinten dazu hängen (oder irgendwo anders in der URL den Hash unterbringen).

Zusammenfassung: (1) Sie müssen keine Fragmente verwenden. (2) Vorschlag: Geben's den Hash irgendwo in die URL rein, so wie es für Ihr System am besten passt.

**Comment by twisted-pear** [comment]
Aaaaah, so macht das ganze schon mehr Sinn, vielen Dank.
