### ISSUE TITLE
Fehler bei Installation Mustercode 1.0.0

### ISSUE THREAD

**Issue by PeterRumpf** [a-sit-plus/at-registrierkassen-mustercode#261]
Hallo
wir haben Schwierigkeiten bei der Aktualisierung unserer JAVA Testumgebung. auf die Version 1.0.0.

Ich denke unsere Problem ist dass eine Referenz auf “verification” fehlschlägt 
s. 
[Install Log.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/732275/Install.Log.txt)

[ERROR]
Failed to execute goal on project regkassen-demo: Could not resolve dependencies for project
at.asitplus.regkassen:regkassen-demo:jar:1.0.0: Failure to find at.asitplus:regkassen-verification-
common:jar:1.0.10

Hat jemand eine Idee?
Vielen Dank

**Comment by PeterRumpf** [comment]
problem gelöst

**Comment by xoechts** [comment]
Habe heute das repo gecloned und habe auch das Problem. Wie wurde das "Problem gelöst"?

**Comment by asitplus-pteufl** [comment]
siehe https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/162
