### ISSUE TITLE
startbelegprüfung - fehlermeldung via app

### ISSUE THREAD

**Issue by eczach** [a-sit-plus/at-registrierkassen-mustercode#263]
einer meiner kunden (bei einer kassa keinerlei problem, bei der anderen die fehlermeldung) hat bei der prüfung seines startbelegs via bmf-app nachfolgende meldung erhalten:
"Der vorliegende Beleg ist zwar gesetzeskonform zustande gekommen, die
Registrierkasse war aber zum Belegerstellungzeitpunkt im FinanzOnline „nur“
registriert. Bitte überprüfen Sie, ob in der Zwischenzeit die erforderliche
Startbelegprüfung stattgefunden hat."
in anderen threads habe ich den hinweis gelesen, dass möglicherweise dies ein bei FON bekannter fehler von finanzonline sei und auch hinweise auf eine zeitabhängigkeit (der kunde hat auch bei der einen kassa den startbeleg sofort erfolgreich geprüft, bei der anderen kassa mit obiger fehlermeldung erst 4 stunden später).
für mich liest sich die fehlermeldung so, als ob FON den startbeleg nicht als startbeleg sondern als einen anderen glaubte zu erkennen. wie kann ich hier weiter recherchieren und meinen kunden unterstützen?
danke!

**Comment by asitplus-pteufl** [comment]
Ich kann hier fürs Erste nur das hier Wiederholen #223 
Das dürfte auch in Ihrem Fall eine Rolle spielen, aber eines müssten Sie dennoch hinterfragen: Auch jetzt sollte die Meldung die Sie beschreiben nur kommen wenn es kein Startbeleg ist, weil wenn es einer wäre, dann würde der Status REGISTRIERT ja passen. Können Sie da nachprüfen ob es wirklich ein Startbeleg bei der Prüfung war?

**Comment by eczach** [comment]
nach aussagen des kunden war es der startbeleg. ich glaube dies auch eher, da ihm ja zuvor bereits bei einer anderer kassa problemlos registrierung der signaturkarten, der kassa und prüfung des startbelegs gelang.
ich werde schauen, dass ich von ihm das dep und den cryptocontainer zu test erhalte.

**Comment by asitplus-pteufl** [comment]
Bitte Vorsicht wenn Sie den CryptoContainer hier posten, dort ist ja direkt das Schlüsselmaterial enthalten.

**Comment by eczach** [comment]
angelegenheit geklärt: der startbeleg MUSS immer als verknüpfungswert die kassen-id enthalten, durch eine zwischendurch zerstörte datenbank wurde statt der kassenid ein anderen wert weitergeben. anscheinend definiet sich der startbeleg eben durch die referenz auf die kasse-id als solcher.

**Comment by asitplus-pteufl** [comment]
@eczach zur weiteren Info, ja der Startbeleg ist so spezifiziert (Detailfragen, Verordnung), wenn das nicht wäre, dann würde er von einem Nullbeleg (z.B. Jahresbeleg, Sammelbeleg) nicht unterscheidbar sein (Umsatzzähler = 0 kann auch dort vorkommen, wenn auch nur sehr selten).
