### ISSUE TITLE
Registrierung einer Signatureinheit via BMF WebService

### ISSUE THREAD

**Issue by ChristianSpath** [a-sit-plus/at-registrierkassen-mustercode#264]
Hallo zusammen!

Ich bin mit dem Web service des BMF etwas auf Kriegsfuß. Login und Logout habe ich geschafft. Bei der Registrierung einer Signatureinrichtung erhalte ich allerdings folgende Fehlermeldung:

_cvc-complex-type.2.4.a: Invalid content was found starting with element 'tid'. One of '{"https://finanzonline.bmf.gv.at/rkdb":tid}' is expected._

Hier ist mein Request:
        
 
    $rkClient = new SoapClient("https://finanzonline.bmf.gv.at/fonws/ws/regKasseService.wsdl");

	$requestParams = array
	(
		'tid' => "1.......j..8",
		'benid' => "..........",
		'id' => $sessionId,
		'art_uebermittlung' => "T",
		'erzwinge_asynchron' => false,
		'rkdb' => array
		(
			'fastnr' => 99,
			'paket_nr' => 1,
			'ts_erstellung' => '2017-01-28T08:00:00',
			'registrierung_se' => array
			(
				'satznr' => 99,
				'kundeninfo' => '99',
				'art_se' => 'SIGNATURKARTE',
				'vda_id' => 'AT9',
				'zertifikatsseriennummer' => '4abb09b1',
			),
		),
	);

	$respRegSig = $rkClient->rkdb($requestParams);

Ich habe hier zwar einen Post gefunden, der auf das gleiche Problem hinweist. Allerdings habe ich das Problem mit diesem nicht lösen können.

Gibt es vielleicht irgendwo einen Beispielcode in C#?

Vielen Dank für eure Hilfe

LG,
Chri

**Comment by Scaenicus** [comment]
Ich hab keinen C#-Code aber was mir auffällt ist, dass man so mit PHP Probleme haben wird, weil der Namespace nicht korrekt im SOAP-XML landet.
Das XML sollte so ähnlich aussehen:


```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:ns1="https://finanzonline.bmf.gv.at/rkdb">
   <soapenv:Header/>
   <soapenv:Body>
    <ns1:rkdbRequest>
      <ns1:tid>xxxxxxxxxxxxxxxx</ns1:tid>
      <ns1:benid>yyyyyyyyyyyyyyyy</ns1:benid>
      <ns1:id>zzzzzzzzzzzzzzzzzzz</ns1:id>
      <ns1:art_uebermittlung>T</ns1:art_uebermittlung>
      <ns1:rkdb>
        <ns1:paket_nr>12073601</ns1:paket_nr>
        <ns1:ts_erstellung>2017-01-12T08:36:01+01:00</ns1:ts_erstellung>
        <ns1:registrierung_kasse>
          <ns1:satznr>798</ns1:satznr>
          <ns1:kundeninfo>xxxxxxxxxxxxxxxxxxxxxxxxxxx</ns1:kundeninfo>
          <ns1:kassenidentifikationsnummer>798</ns1:kassenidentifikationsnummer>
          <ns1:anmerkung>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</ns1:anmerkung>
          <ns1:benutzerschluessel>MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIz</ns1:benutzerschluessel>
        </ns1:registrierung_kasse>
      </ns1:rkdb>
    </ns1:rkdbRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by ChristianSpath** [comment]
Hallo Philipp!

Vielen Dank für deine Hilfe, ich werde das demnächst ausprobieren.

LG
Chri

**Comment by asitplus-pteufl** [comment]
Aus Gründen der Übersichtlichkeit schließe ich dieses Issues, da hier keine offensichtlichen offenen Punkte erkennbar sind. Falls doch noch Punkte behandelt werden müssen, bitte einfach wieder öffnen.
