### ISSUE TITLE
Beispiel Verschlüsselung Umsatzzähler CFB Modus

### ISSUE THREAD

**Issue by BiancaMore** [a-sit-plus/at-registrierkassen-mustercode#266]
Hallo,

es war jemand schon so nett und hat folgendes Beispiel für die Verschlüsselung des Umsatzzählers gepostet. 

KassenID: "CashBox01"
Belegnr: "00000001"
Umsatz: 55,09
AES-Key (base64 encoded): "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU="
IV (ersten 16 byte): 3e 04 75 88 e2 0f 53 f9 2b bd f4 a9 c0 12 40 0d
Umsatz als Byte Array: 00 00 00 00 00 00 15 85
Ergebnis: "ByW5rsidWYI="

Ich erhalte nun ein anderes Ergebnis, was daran liegt, dass ich für die Verschlüsselung nicht den ICM/CTR Modus, sondern den CFB Modus verwende. Dies ist leider erforderlich, da im DBMS_CRYPTO von Oracle noch kein ICM/CTR-Modus angeboten wird.

Hat sich sonst noch jemand mit der Verschlüsselung über den CFB Modus beschäftigt und kann mir ein entsprechenden Beispiel schicken?

**Comment by asitplus-pteufl** [comment]
Bitte das Suchfeld ganz oben benutzen, bzw. einfach das README und die Detailfragen nutzen. Alles was Sie da anfragen ist spezifiziert, demonstriert und wurde mehrfach in den Issues behandelt.

Suche im Muster-Code:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/search?utf8=✓&q=CFB

Suche nach Issues:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/search?q=CFB&type=Issues&utf8=✓

Detaildokument:
Runterladen von https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.2-DOK/2016-09-05-Detailfragen-RKSV-V1.2.pdf
Danach Suche im PDF nach CFB.

**Comment by BiancaMore** [comment]
Soweit ich das nun verstanden habe bildet der verschlüsselte Umsatzzähler immer den selben Wert, egal welche Verschlüsselungsmethode (ICM/CTR,CFB oder ECB) ich verwende. Ich bin davon ausgegangen, dass eine andere Verschlüsselungsmethode automatisch auch zu einem anderen Ergebnis führen muss, daher mein Thread.

Mein Ergebnis stimmt zwar noch nicht, aber jetzt kann ich auf die Fehlersuche gehen.

Vielen Dank.

**Comment by areiter** [comment]
Obwohl schon geschlossen, ich kann das jetzt so hier nicht stehen lassen. Vl. meinen sie es auch anders als ich ihren Text verstehe:

Wird ein Wert mit AES im CTR Mode verschlüssel, ist das Ergebnis natürlich ein anderes als würde der Wert mit AES im ECB Mode verschlüsselt werden.
Das ist aber hier gar nicht der Use Case. Hier wurde definiert dass die Umsatzzählerverschlüsselung mit AES im CTR Mode zu erfolgen hat. 
Wie der CTR Mode nun implementiert ist, ist eine andere Geschichte. Entweder ihre AES Implementierung bietet nativ den CTR Mode, oder sie müssen ihn implementieren, z.B. unter Zuhilfenahme des ECB Modes.
