### ISSUE TITLE
DEP: 1 Zeile pro Beleg oder pro Position?

### ISSUE THREAD

**Issue by BernhardMaier** [a-sit-plus/at-registrierkassen-mustercode#267]
Hallo,

§ 7. (1) RKSV besagt, dass jede Registrierkasse ein Datenerfassungsprotokoll zu führen hat, in dem jeder einzelne Barumsatz zu erfassen und abzuspeichern ist. Für jeden Barumsatz sind zumindest die Belegdaten gemäß § 132a Abs. 3 BAO festzuhalten.

Ist mit Barumsatz die Gesamtrechnung oder die einzelnen Positionen einer Rechnung gemeint? Ich frage deshalb, weil § 132a Abs. 2 BAO vorschreibt, dass im Datenerfassungsprotokoll auch Menge, Bezeichnung und Zahlungsbetrag pro Position gespeichert wird.

Wie soll dies bewerkstelligt werden, wenn auf dem Beleg und im Datenerfasssungsprotokoll die verschlüsselten Werte des Gesamtbeleges gespeichert werden? Muss man für jede Position einen QR-Code auf den Beleg drucken? Bitte um Antwort.

**Comment by BernhardMaier** [comment]
Vielen dank für die rasche Antwort. Ich werde 2 Exporte in meinem Programm anbieten, einen nach  § 7 Abs. 5 (JSON, Belegebene) und einen nach § 19 RKSV (erweiterte Belegdaten, Postenebene).

**Comment by ErichFreitag** [comment]
OK, dann sind sie diesbezüglich konform. Der § 7-Export umfasst immer den ganzen Lebenszyklus der Kasse ab dem Startbeleg und ist vom Output her ident mit der DEP-Sicherung.

Werfen sie noch einen Blick in die Kassenrichtlinie 2012, was alles zum Datenerfassungsprotokoll der Kasse gehört - das geht bis zu Konfigurationsänderungen etc. Überlegen sie dafür auch ein vernünftiges Format (.csv, Standards, ...).

**Comment by AxelKutschera** [comment]
@BernhardMaier 
- Mit Barumsatz ist der Gesamtbeleg (nicht Rechnung) gemeint.
- Ich kann aus § 132a Abs. 2 BAO (ich glaube es sollte § 132a Abs 3 BAO heißen) nicht herauslesen, dass der Zahlungsbetrag pro Position gespeichert wird. - Wo soll das stehen?

**Comment by BernhardMaier** [comment]
@AxelKutschera 

- Mit "Rechnung" habe ich die den Gesamtbeleg bzw. die Gesamtrechnung gemeint.
- Stimmt, ich habe mich, wie auch im 1. Absatz meines ersten Kommentars, auf § 132a Abs 3 BAO bezogen. Der Kommentar mit "Zahlungsbetrag pro Position" war meine persönliche Interpretation des Gesetzestextes, da in § 7 Abs. 1 RKSV auf die Belegdaten gemäß § 132a Abs 3 BAO verwiesen wird, in § 7 Abs. 5 RKSV wird hingegen der Export nach dem speziellen JSON-Format beschrieben, der ja keine Infos auf Postenebene (Mengen, handelsüblichen Bezeichnungen der Artikel etc.) beinhaltet. Danke für Ihr Mitwirken, das Issue ist für mich erledigt.
