### ISSUE TITLE
(C#) Kartenleser auswahl bei mehreren Kartenlesern

### ISSUE THREAD

**Issue by oldfox94** [a-sit-plus/at-registrierkassen-mustercode#268]
Hallo,

aktuell stehen wir vor dem Problem, dass wird einen bestimmten Kartenleser auswählen müssten.
Wir arbeiten derzeit mit dem A-Trust Wrapper für C# .NET
Leider haben wir noch nicht rausgefunden wie man hier explizit einen Kartenleser ansprechen kann.

Hat in diesem Thema schon irgendjemand erfahrung oder beispielcodes?

Ich bedanke mich im voraus.
Raphael

**Comment by areiter** [comment]
Ich kenne den _A-Trust Wrapper_ jetzt nicht, aber ich verwene die Smartcards direkt mittels pcsc-sharp (https://github.com/danm-de/pcsc-sharp) und das funktioniert problemlos. 
Da kommen sie gar nicht drumherum den Reader explizit auszuwählen.

Handelt es sich bei dem A-Trust Wrapper um eine .net Assembly? Vl. verwendet diese intern auch pcsc-sharp? Oder meinen sie mit _A-Trust Wrapper_ die PKCS#11 Library?

**Comment by oldfox94** [comment]
Danke für die schnelle Antwort.
Nein leider, wir haben einige Kunden wo 2 Katenleser benötigt werden (Verleihsystem und wir)
Es ist nicht möglich auf einer Karte dies abzubilden da sonst beide Programme abstürzen.


> Oder meinen sie mit A-Trust Wrapper die PKCS#11 Library?

Ja ich vermute PKCS#11, bzw. nach PKCS#11 Standart lt. Beschreibung.
Diese .net dll steuert die asingp11.dll an und gibt die Signatur zurück.
(http://labs.a-trust.at/developer/ShowSource.aspx?id=125)

Es ist zwar möglich direkt die asingp11.dll einzubinden (via DLLImport) jedoch wird die Funktion "GetSlotInfo" im Beispielprojekt nicht verwendet.
Es gibt auch eine Developement Manual nur werde ich nicht wirklich schlau daraus...
(https://labs.a-trust.at/developer/pdf/asignClient_Developers_Manual.pdf)

**Comment by areiter** [comment]
Sorry mit der A-Trust  "PKCS#11" Library kann ich ihnen leider nicht helfen.
Es gibt unter Windows allerdings Smartcard Transactions mit denen sie den Zugriff aus mehreren Applikationen auf die Smartcard synchonisieren können [1] (ich nehme an sie verwenden Windows, weil sie auf die A-Trust DLL referenzieren)
Vl. hilft ihnen das anderwertig weiter.

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa379469(v=vs.85).aspx

**Comment by oldfox94** [comment]
Vielen Dank für Ihre Bemühungen, wir haben nun die Lösung. :)
Wir haben jetzt das APDU Example von A-Trust verwendet und mit diesem gibt es mehr Möglichkeiten.
(http://labs.a-trust.at/developer/ShowSource.aspx?id=114)

Hier kann man von einer Auflistung von Kartenlesern einen bestimmten auswählen usw...
Danke nochmals!
Hiermit schließe ich das Issue.
