### ISSUE TITLE
Link führt ins nichts

### ISSUE THREAD

**Issue by simonmau** [a-sit-plus/at-registrierkassen-mustercode#269]
Unter [https://github.com/a-sit-plus/at-registrierkassen-mustercode#%C3%9Cbersicht](https://github.com/a-sit-plus/at-registrierkassen-mustercode#%C3%9Cbersicht) , im 1. Absatz befindet sich ein Link zu [https://www.bmf.gv.at/top-themen/Registrierkassen.html](https://www.bmf.gv.at/top-themen/Registrierkassen.html). Dieser Link ist leider nicht mehr gültig.

**Comment by AxelKutschera** [comment]
Der Link ist zB https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html

**Comment by simonmau** [comment]
Danke, wenn wir das ausbessern könnten wäre das schön, in ein paar Jahren

**Comment by asitplus-pteufl** [comment]
danke, ist korrigiert!
