### ISSUE TITLE
Beleg zu mehreren Rechnungen

### ISSUE THREAD

**Issue by devobj** [a-sit-plus/at-registrierkassen-mustercode#270]
Hallo,

für einen Zahlungsvorgang wird ja ein Zahlungsbeleg erstellt, der dann signiert werden muss (Barumsätze und ggf. durchlaufende Posten, falls diese mit Barumsätze vermischt sind).

Wie sieht es aus, wenn ein Kunde mehrere Rechnungen mit einem Zahlungsvorgang bezahlen will. Wird dann auch nur ein Zahlungsbeleg mit Signatur erstellt?

Beispiel:
```
RG1: 10 EUR
RG2: 20 EUR
RG3: 30 EUR
Zahlbeleg Q1: 60 EUR mit Verweis auf RG1, RG2, RG3 und QR-Code Aufdruck.
```

Interessant wird es, wenn darauf auch Teilzahlungen oder durchlaufende Posten noch verrechnet werden. Langt in diesem Fall beim Ausdruck des Zahlungsbelegs auch ein Verweis auf die Rechnungen aus?

**Comment by ErichFreitag** [comment]
Grundsätzlich ist die Idee in Ordnung. Sie müssen Barumsätze erfassen, eintragen und signieren. Bei der Barzahlung von Rechnungen gibt es drei Möglichkeiten der Abbildung - ein davon ist, die Barumsätze in den Steuersätzen oder im 0%-Satz abzubilden und einen Verweis auf die Rechnung anzubringen.

Das Vorgehen wäre also aus dieser Sicht betrachtet durchaus konform. Was sie jedoch damit deutlich erschweren, ist a) bei einer Prüfung das nachvollziehbar aufzuschlüsseln und b) der Buchhaltung viel Arbeit bei der Auftrennung bereiten. Wenn es nicht vernünftig anders geht - OK, sonst würde ich auf alle Fälle die Geschäftsfälle sauber voneinander trennen (also 3 Belege für die Zahlung von 3 Rechnungen ausstellen etc.).
