### ISSUE TITLE
Webservice Registrierkasse - Frage bezüglich tid und benid

### ISSUE THREAD

**Issue by FelixKarner** [a-sit-plus/at-registrierkassen-mustercode#271]
Sehr geehrte Damen und Herren,

ich hätte eine Frage bezüglich des Webservice für Registrierkassen:
Laut der Dokumentation auf FinanzOnline werden für den Aufruf die Parameter: Teilnehmer-ID, Benutzer-ID, Session-ID, sowie Registrierkassenparameter übergeben. Wieso ist es notwendig hier die Teilnehmer-ID und Benutzer-ID  wieder anzugeben (beim Login werden ja bereits tid und benid verwendet)? Können beim Login und den Registrierkassen-Funktionen verschiedene Teilnehmer/Benutzer verwendet werden, oder müssen diese ohnehin immer die selben sein? Falls diese voneinander abweichen können, welchen Zweck erfüllt dies?
Ich wäre Ihnen für eine Auskunft oder einen Verweis auf eine Dokumentation die mir entgangen sein könnte sehr verbunden.

Mit freundlichen Grüßen,
Felix Karner
Advokat GmbH

**Comment by maxp1256** [comment]
Ich denke dies hat technische Gründe, da das Session-Webservice auch für andere Aufgaben verwendet wird und dem RKSV-Webservice sonst nur die SessionId bekannt wäre. Ist aber nur eine Vermutung.

**Comment by FelixKarner** [comment]
Vielen Dank für Ihre Antwort @maxp1256 :), nachdem ich auch nichts gegenteiliges mehr feststellen konnte habe ich es dabei belassen davon auszugehen, dass es sich hier immer um die selben Credentials handelt.
