### ISSUE TITLE
Umsatzzähler reset

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#272]
Hallo,

kann mir jemand bitte mit eine frage helfen und zwar:
darf man den Umsatzzähler nach Ende des Jahres z.B. am 31.12. um 24:00 resetieren, damit
es wieder mit 0.00 anfängt?

Danke im Voraus

**Comment by ErichFreitag** [comment]
NEIN!!! :-) Der Umsatzzähler läuft bis zum Lebensende der Kasse durch.

**Comment by areiter** [comment]
Der Umsatzzähler ist untrennbar mit dem DEP verbunden.
Wenn sie den Umsatzzähler zurücksetzen möchten muss die Kasse abgemeldet werden, ein neues DEP gestartet und die neue Kasse wieder registreirt werden

**Comment by espeitslo** [comment]
Perfekt, vielen dank für den Antwort, ist ja irgendwie logisch, aber es steht niergendwo. Eigentlich komme ich aus eine Firma die solche Fiskalization für SLO, CRO und SRB macht und dort ist es überall ganz anders festgestellt. Jeder Beleg wird in real time online gemeldet und erst danach mit eine code ausgedrückt.
