### ISSUE TITLE
Duty free Zonen

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#273]
Hi,

wie ist es genau vorgeschrieben bezüglich Steuerfreie Zonen, z.B. Flughafen, müssen dort 
auch alle Trasnaktionen fiskaliziert werden? Meine Meinung nach, gehören solche Geschäfte auch unter
Definition für Regiseterkassen, wahrscheinlich sind nur die Betrag-Sätze anders, bzw null?

MfG

**Comment by ErichFreitag** [comment]
Nachdem es Unternehmen in Österreich (?) sind gilt das genauso und in den jeweiligen Steuersätzen. Eine Ausnahme diesbezüglich wäre mir nicht bekannt.

**Comment by espeitslo** [comment]
Ja das ist schon klar, aber am Flughafen ist eine Steuerfreie Zone, zwar bin ich nicht sicher, aber dort is so zu sagen no mans land und nicht Österreich oder? Ich wurde das auch genau so sagen dass es auch für dennen das gleiche gilt, aber leider brauche ich das irgendwie Offiziel gegeben und kann sowas niergendwo finden, ausser die Definition welche Unternehmer müssen Registrierkassen führen und in diese Kategorie fallen auch Geschäfte in Steuerfrei Zonen.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
