### ISSUE TITLE
FinanzOnline meldet Fehler für Startbeleg, der im Prüftool für fehlerfrei erklärt wird

### ISSUE THREAD

**Issue by UktTVg** [a-sit-plus/at-registrierkassen-mustercode#274]
Hallo,

Die BMF-Belegcheck-App bzw. in Folge FinanzOnline erkennt einen Startbeleg nicht als solchen, der vom Prüftool problemlos erkannt wird und dort alle Tests besteht.
Aus dem XML-Prüfbericht aus FinanzOnline lässt sich leider nur erkennen, dass der Test TYPE_OF_RECEIPT fehlschlägt, weil kein einziger Sub-Test davon (TYPE_OF_RECEIPT_START, TYPE_OF_RECEIPT_STANDARD, etc.) erfolgreich ist.

Im Prüftool (DEP-Export-Überprüfung) besteht der Startbeleg wie gesagt ohne Probleme alle Tests, genau wie die nachfolgenden Belege.

Das einzige was ich mir eventuell im Entferntesten vorstellen könnte ist, dass die Tests in FinanzOnline den verschlüsselten Umsatzzähler von 0 nicht erkennen, weil dieser in meiner Implementierung auf 8 Byte fixiert ist, auch wenn zur Darstellung weniger ausreichen würden. Wäre das eine Möglichkeit?

Gibt es sonstige Ideen woran das Problem liegen könnte?

Vielen Dank!

**Comment by ErichFreitag** [comment]
Der formale Unterschied ist der, dass das Prüftool Daten aus dem DEP-Export liest und die Belegcheck-App den QR-Code. Wenn sie möchten posten sie hier bitte die Daten und den QR-Code.

**Comment by UktTVg** [comment]
JWS Startbeleg: `eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8xXzE1NjhfMjAxNy0wMi0wMVQxNjoxODowN18wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfaG1qdnFTUVNyN1E9XzdERDA4QzdDX2E0YXljLzgwL09FPQ.YkWhzNFoyYIj6yA45czx3G6u2_88Rjsk7pbxYjYbbBjF-uFVTLZ3I8fZSPS2jEUtLH4Wqqs2qXn5sseBhEcubQ`

QR-Code Startbeleg:
![screenshot from 2017-02-02 16 21 40](https://cloud.githubusercontent.com/assets/25507628/22555606/819e2cbe-e964-11e6-9f29-bee196f67d7e.png)

**Comment by ErichFreitag** [comment]
Bitte noch um den cryptographicMaterialContainer dazu.

**Comment by asitplus-pteufl** [comment]
überprüfen Sie ob in FinOnline der korrekte AES-Schlüssel registriert ist.

**Comment by UktTVg** [comment]
Der Schlüssel wurde tatsächlich falsch in FinanzOnline eingetragen, das war das Problem - vielen Dank!
