### ISSUE TITLE
FinanzOnline erlaubt mehrmalige Registrierung der selben Kasse

### ISSUE THREAD

**Issue by aunterlu** [a-sit-plus/at-registrierkassen-mustercode#275]
Aufgrund einer fehlerhaften Startbelegsprüfung bei einem Kunden bin ich jetzt draufgekommen, dass es in FinanzOnline möglich ist eine Kasse mit der gleichen Kassen-ID und dem gleichen AES-Schlüssels zweimal zu registrieren! Ob das jetzt Auswirkung auf Probleme mit der Startbelegsprüfung in diesem Fall hat, kann ich noch nicht nachvollziehen.

**Comment by aunterlu** [comment]
Bei dem Kunden wurde auch die Sicherheitseinrichtung außer Betrieb und dann wieder in Betrieb genommen. Kann dadurch die Startbelegprüfung fehlschlagen?

**Comment by asitplus-pteufl** [comment]
FinOnline Fragen können im Rahmen dieses Projekts nicht beantwortet werden.
Nur so viel: Eine Kasse kann mehrere Lebenszyklen haben: Registrierung->SB-Prüfung->In BETRIEB->Außer Betrieb->Neue Registrierung->neue SB-Prüfung->IN BETRIEB_>...

Der SB muss immer zum aktuellen Zyklus passen.
