### ISSUE TITLE
Eine Kassa - mehrere Zertifikate 

### ISSUE THREAD

**Issue by norbert2** [a-sit-plus/at-registrierkassen-mustercode#277]
Wie schaut der korrekte Ablauf aus, wenn eine Signierungseinheit getauscht werden muss?
Ausgangsszenario:
Für Kassa 1 werden zwei Zertifikate bei FAO angemeldet.
Kassa läuft mit Zertifikat A, danach Defekt.
Mit Zert. A können keine 0-er-Belege mehr erstellt werden.
Also kann die Kassa nicht mit Zert. A außer Betrieb genommen werden.
Wie hat der korrekte Ablauf auszuschauen?

Zusatzfrage:
Pro Kassa darf das DEP nur je Zertifikat ausgegeben werden?
Oder können in einem DEP schon mehrere Zertifikate verwendet werden?

**Comment by Phoniexk** [comment]
Ich kann nur zur Zusatzfrage was beisteuern:

siehe PDF-Dokument "**Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV)**" im Punkt **5 Export des Datenerfassungsprotokolls**

**Beispiel – Export des DEPs wenn keine Signaturzertifikate vorhanden sind**

> Im folgenden Beispiel wird davon ausgegangen, dass kein Signaturzertifikat vorhanden ist. Alle Belege – auch wenn Sie mit unterschiedlichen Zertifikaten signiert wurden – werden in einer Gruppe chronologisch abgelegt.

**Comment by ErichFreitag** [comment]
a) sie melden die Zertifikate nicht pro Kasse, sondern pro Unternehmen an
b) es ist grundsätzlich egal, welche Kasse mit welchem Zertifikat signiert
c) eine Außerbetriebnahme der Kasse hat so keinen Bezug zu einem Ausfall eines Zertifikats
d) wenn es eine Außerbetriebnahme der Kasse geben soll hat das auch damit nichts zu tun - man kann eine Kasse auch ohne Schlussbeleg außer Betrieb nehmen (z.B. bei Defekt)
e) in einem DEP-Export können mehrere Zertifikate enthalten sein

Bitte das eventuell dahingehend die Frage nochmals zu formulieren.

**Comment by norbert2** [comment]
Danke für die prompte und gute Nachricht.
Es können also die - angemeldeten - Zertifikate beliebig gemixt werden, ohne irgendwelche 0-er-Belege erstellen zu müssen.
Ich habe da nur den Verdacht gehabt, weil das Java-Prüftool einen Krypto-Container verlangt, in dem schon das Zertifikat angegeben sein muss, mit dem signiert wurde.
Bei der Prüfung des DEP durch die Finanz gibts offensichtlich andere Tools, die die angemeldeten Zertifikate der Firma berücksichtigt.

**Comment by ErichFreitag** [comment]
Solange die Zertifikate/SE-Einheiten funktionieren sind keine Nullbelege erforderlich, auch nicht bei einem Wechsel. Der Crypto-Container wird für die Verifikation der Signatur und des Umsatzzählers benötigt. Und den brauchen sie deshalb, weil das Tool keinen Zugriff auf die Finanz-Online-Daten hat (die werden damit sozusagen simuliert).

**Comment by norbert2** [comment]
Alles klar. Danke.
