### ISSUE TITLE
Reihenfolge der erstellten Belege

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#278]
Hallo,

wurde mich interessieren wie ist die Reihenfolge der zu erstellten Belege in den "kritischen/besonderen" Situationen wenn z.B: Ausfall, Monatsbeleg und auch DEP Sicherung hintereinander behandelt werden müssen?

Annahme: Signatureinheit wurde vor der Erstellung des Monatsbeleges in Betrieb genommen.
Schritt 1: Monatsbeleg
Schritt 2: Sammelbeleg
Schritt 3: DEP Sicherung

Ist meine Annahme richtig oder?
Danke.

**Comment by ErichFreitag** [comment]
Ganz kann ich die Frage nicht nachvollziehen... einmal geht es um Ausfall und einmal um Inbetriebnahme? Vielleicht wollen sie das nochmals detaillierter schildern.

Generell: Sammelbeleg nach Wiederverfügbarkeit der Signatureinheit. Monatsbeleg beliebig, der darf auch unsigniert sein. DEP-Sicherung zumindest quartalsweise mit Monatsbeleg als letzten Beleg.

**Comment by AlgoLinz** [comment]
Sorry,

hier die detaliertere Beschreibung:
Die Wiederinbetriebnahme einer Signatureinheit fällt zufällig am 01. April d.h. für das letzte Monat muss ein Monatsbeleg erstellt werden, zusätzlich muss ich auch ein Sammelbeleg erstellen weil die Signatureinheit wieder OK ist, und weil die DEP Sicherung mindestens einmal im Quartal erstellt werden muss, muss auch die DEP Sicherung angestoßen werden.

Jetzt ist die Frage in welcher Reihenfolge die Belege für oben beschriebene Vorgänge erstellt werden müssen?

1. Monatsbeleg
2. Sammelbeleg
3. DEP-Sicherung

oder

1. Monatsbeleg
2. DEP-Sicherung
3. Sammelbeleg

Danke.

**Comment by ErichFreitag** [comment]
Wenn ich die Reihenfolge richtig verstehe ist die SE genau in dem Moment wieder verfügbar, wenn der Monatsbeleg generiert wird?

Wenn ja: dann generieren sie den Monatsbeleg als nächsten Beleg. Unsigniert oder signiert, in diesem Fall wieder signiert. Jetzt kommt der Sammelbeleg nach der Wiederverfügbarkeit.

Damit haben sie zwei Nullbelege - der DEP-Export kann ja zwischen Monatsbeleg und Sammelbeleg nicht unterscheiden. Also können sie auch mit dem Sammelbeleg als letztem Beleg die DEP-Sicherung durchführen. 

Zulässig ist formal beides. Schöner ist wohl die erste Variante, weil der wieder signierte Monatsbeleg auch mit dem Sammelbeleg abgeschlossen wird. Wenn nicht ist das halt spätestens im nächsten Quartal enthalten. Auf den eigentlichen Sinn der DEP-Sicherung (nämlich das Festhalten des Standes des Umsatzzählers und der gesamten Historie) haben beide Varianten keinen Einfluss.

**Comment by Alex1130** [comment]
Ist es aufgrund von Formvorschriften verboten einen Sammelbeleg als Monatsbeleg zu behandeln? (Nullbeleg als letzter Beleg des Vormonats bzw. erster Beleg des laufenden Monats?) Im DEP Export wäre es erlaubt ?

**Comment by theshadowtwentyseven** [comment]
Der Monatsbeleg ist mir gemäß §8 Abs. 2 klar, entspricht vereinfacht gesagt dem Umsatzzähler plus 0 Barumsatz. Doch was meinen Sie mit DEP-Sicherung?

**Comment by AlgoLinz** [comment]
Mindestens einmal im Quartal muss das gesamte DEP auf einem externem Speichermedium gesichert werden.

**Comment by AlgoLinz** [comment]
@ErichFreitag danke für die Antwort.
Für Deinen Einsatz hier sollte Dir jeder Forumteilnehmer mindestens eine Flasche guten Wein zusenden :)

**Comment by ErichFreitag** [comment]
Gerne, @AlgoLinz und danke.

@Alex1130 Zu Sammelbeleg und Monatsbeleg: technisch schaut das gleich aus. Im DEP-Export kann es nicht unterschieden werden (man könnte es auf Grund der Signaturen erkennen, weiß dann aber nicht, ob es ein Sammelbeleg oder ein Monatsbeleg ist). Formal müssen beide vorhanden sein und der Sammelbeleg enthält ja zusätzlich auch Beginn und Ausfallsende.

@theshadowtwentyseven Die DEP-Sicherung entspricht einem Export vom Startbeleg bis zum Monatsbeleg als Abschluss der Sicherung. Das ist keine technische, sondern eine steuerliche Maßnahme, um zumindest Umsatz und Verlauf bis zur letzten Sicherung nachweisen zu können.

**Comment by theshadowtwentyseven** [comment]
@ ErichFreitag: derzeit exportieren wir jedes Monat alles ab Startbeleg bis zum Monatsbeleg und sichern Monatsweise. Womit die Dateien zwangsweise immer länger werden. So ist immer die gesamte DEP Historie vorhanden.

Wie meinst Du also die Sicherung bis zum letzten Export?

**Comment by ErichFreitag** [comment]
Jetzt versteh ich nicht, was sie meinen, dass ich meine :-)

a) eine DEP-Sicherung ist ein DEP-Export vom Startbeleg bis zum Monatsbeleg als letzten Beleg (alternativ Schlussbeleg bei Außerbetriebnahme). Das dürfte ja soweit passen.

b) ein DEP-Export kann zumindest theoretisch mit jedem beliebigem Start- und Endedatum angestossen werden - deshalb unterscheide ich die beiden Begriffe "Export" und "Sicherung". Zusätzlich zum RKSV-Export kommt ja noch der Export des Kassenjournals nach § 19 RKSV hinzu.

c) wichtig ist die Sicherung als Aufbewahrung der Nachvollziehbarkeit zumindest bis zum letzten Quartal, um Schätzungen oder ähnliches zu vermeiden. Monatsweise Sicherung im Zuge des (automatischen) Monatsbelegs finde ich sowieso am einfachsten und sinnvollsten.
