### ISSUE TITLE
Zahlbeleg und durchlaufende Posten

### ISSUE THREAD

**Issue by devobj** [a-sit-plus/at-registrierkassen-mustercode#279]
Hallo,

bei einem gemeinsamen Zahlvorgang von Barzahlung und durchlaufenden Posten (Verrechnung von Kundenguthaben) soll nach den Vorgaben ein Zahlbeleg mit beiden Beträgen signiert werden.

Beispiel:
Rechnung: 30 EUR
Bar: 10 EUR
Kundenkonto: 20 EUR

Normalerweise erhält der Kunde bei diesem Vorgang einen Zahlbeleg (Quittung) nur für die Barzahlung von 10 EUR.  Einen Zahlbeleg erhält der Kunde ebenfalls für die vorherige Bareinzahlung in das Kundenkonto. Nicht aber für die Verrechnung des Kundenkontos.

Muss bei dem Zahlbeleg für die Barzahlung von 10 EUR nur die Kundenkonto-Verechnung im QR-Code abgebildet (BetragSatzNull erhöhen) sein oder muss diese auch auf dem Zahlbeleg extra ausgewiesen werden? Dabei muss auch bedenkt werden, dass Kundenkonto-Verrechnungen nicht unbedingt aus Barzahlungen entstehen müssen, sondern auch aus z.B. aus Banküberweisungen.

Wie sieht es dann aus, wenn man diesen Beleg bzw. die Barzahlung stornieren will?

**Comment by ErichFreitag** [comment]
Wir müssen da ein paar Dinge unterscheiden, zunächst mal Rechnung und Beleg. Eine Barzahlung (auch Teilzahlung oder Anzahlung) einer Rechnung hat ein paar Besonderheiten.

Generell wird das signiert und in den Umsatzzähler aufgenommen, was Barumsatz ist. Zusätzlich freiwillig alles andere im 0%-Steuersatz. Ein Storno ist eine Rückabwicklung eines Geschäftsfalls und daher mit gegenüber dem ursprünglichen Inhalt negativen Beträgen auszuführen.

Wohin die 10 EUR bei Bezahlung einer Rechnung kommen hängt davon ab, wie sie diesen Fall abbilden wollen - es gibt dafür drei Möglichkeiten. Z.B. die skizzierte - 10 EUR im 0%-Steuersatz plus einen Verweis auf die Rechnnung, unabhängig von einem Kundenkonto.

**Comment by cashReg1984** [comment]
Darf ich mich hier mit einer ähnlichen Frage anhängen:
Lt. Erlaß https://findok.bmf.gv.at/findok?execution=e1s1, Pkt. 2.4.11 Anzahlungen, etc.,  ist es zulässig beim Beleg auf eine Rechnung zu verweisen, wenn vorhanden. Was ist in so einem Fall dann in die Betrag-Satz-* Felder (Normal, Ermaessigt_1, Ermaessigt_2, Null, Besonders) zu schreiben? 0,00?

**Comment by ErichFreitag** [comment]
Wenn eine Barzahlung vorgenommen wird, die auf eine Rechnung verweist, tragen sie den Betrag der Anzahlung in die entsprechenden Steuersätze ein - es ist ja auch ein Barumsatz. Wenn sie mehrere Steuersätze haben müssen sie den Anzahlungsbetrag aufteilen und in einem Steuersatz gegebenenfalls runden.

**Comment by cashReg1984** [comment]
Danke für die schnelle Antwort. Scheint für mich bei diesem Anwendungsfall (und einigen weiteren ;-) ) nicht eindeutig zu sein. Laut Auskunft WKO Tirol, könne man sich die Aufteilung sparen, es genüge der Verweis auf eine Rechnung. Es konnte mir aber dort nicht gesagt werden, ob oder in welches der genannten Felder der Barumsatz hineinsoll. Würde es ausreichen, nur den Umsatzzähler zu erhöhen und den Betrag im Summenspeicher abzuspeichern?

**Comment by AxelKutschera** [comment]
@ErichFreitag Bei einem Verweis auf die Rechnung soll der gesamte Betrag in den Betrag-Satz-Null genommen werden.
Der Summenzähler wird immer nur durch die Summe der aufgeteilten Einzel-Beträge erhöht (oder verringert).

Interessant wird es immer erst bei gemischten Fällen oder Cent-Differenzen...

**Comment by ErichFreitag** [comment]
Das liegt daran, dass sie drei Möglichkeiten haben, Barzahlungen für Rechnungen abzubilden. Der Hintergrund dabei ist immer darauf zu achten, dass keine doppelte Umsatzsteuerschuld entsteht (Barumsatz und Rechnung). Daher ist es in allen Fällen wichtig, am Barzahlungsbeleg den Verweis auf die Rechnung anzubringen.

a) Beleg ohne Einträge in den Steuersätzen, nur "Beleg für erhaltene Barzahlung für Rechnung xy" und "Rechnungsduplikat" - keine Signierung, kein (QR-)Code, kein Umsatzzählereinfluss (Erlass 2.4.11)

b) Beleg mit Zahlungen im 0%-Steuersatz, normale Signierung, normaler (QR-)Code, normaler Umsatzzählereinfluss plus Vermerk "Referenz Rechnung xy" (Erlass 4.6.6)

c) Beleg mit Zahlung in den Steuersätzen wie auf der Rechnung, normale Signierung, normaler QR-Code, normale Umsatzzählerbeeinflussung plus "Rechnungsduplikat zu xy" (WKO-FAQ)

Bei c) müssen sie nachweisen können, dass z.B. im Kassenjournal der Bezug zur Rechnung eindeutig nachvollziehbar ist. Für die Buchhaltung ist das auch schwieriger als a) oder b). Am steuerlich eindeutigsten ist wohl b)

**Comment by AxelKutschera** [comment]
Ich würde die Frage der UST-Schuld und Darstellung als Rechnung immer ausklammern. 
Wir sollten hier immer nur die RKSV. - Sonst wird steuerlich schwer.

Der Verweis auf die Rechnung hilft zB nicht, um das Ust-Problem zu lösen.

a) Wenn ich es richtig verstehe, dann ist das nicht richtig.

Die Frage des Nachweises bzw. der Buchhaltung würde ich auch nicht so formulieren und wird wohl der Steuerberater treffen müssen ... ;-)

**Comment by ErichFreitag** [comment]
Das ganze ist ja nur eine Krücke, wie man damit umgehen kann. Na dann zur Klärung von a) der gesamte Text:

"Eine Barzahlung liegt auch vor, wenn der Unternehmer dem Leistungsempfänger eine Rechnung iSd UStG 1994 mit Zahlungsanweisung übergibt, der Leistungsempfänger diesen Betrag aber dennoch beim Unternehmer vor Ort in bar bezahlt. In diesem Fall entsteht die Umsatzsteuerschuld nicht ein zweites Mal. Der leistende Unternehmer stellt keine „Rechnung“ im Sinn des UStG 1994, sondern einen Beleg über die empfangene Barzahlung iSd § 132a BAO bzw. RKSV aus.

Es ist zulässig, auf diesem Beleg lediglich auf die Nummer der Rechnung zu verweisen und keine Aufschlüsselung der Umsätze nach Steuersätzen vorzunehmen, wenn die Rechnung zur Abfuhr der Steuerschuld schon im (elektronischen) Aufzeichnungssystem erfasst wurde.

Die Erfassung des Umsatzes in der Registrierkasse und der Ausdruck des Registrierkassenbelegs lösen keine Umsatzsteuerschuld kraft Rechnung aus. Für den Fall einer gesonderten Rechnungsausstellung nach § 11 UStG ist es – um eine Steuerschuld kraft Rechnungsausstellung zu vermeiden – zweckmäßig, den Registrierkassenbeleg als Rechnungsduplikat (vgl. UStR 2000 Rz 1527 f) zu kennzeichnen".

**Comment by cashReg1984** [comment]
@ErichFreitag  Punkte a, b und c:
Kann man bei Verweis auf eine Rechnung alternativ eine der drei Möglichkeiten wählen? 
ad a.) Wäre dann bei a die RKSV überhaupt erforderlich? Oder verstehe ich das komplett falsch? 
ad b.) Wenn das so mit der RKSV konform geht, scheint mir das die einfachste Lösung zu sein. 
ad c.) Bei Barzahlung d. gesamten Rechnungsbetrages ok, aber das würde wieder an den Punkt zurückführen, an dem die Frage ihren Ausgang genommen hat: Wie sind die Beträge bei Teilzahlungen in Bar auf die genannten Felder aufzuteilen?

**Comment by cashReg1984** [comment]
@AxelKutschera "Bei einem Verweis auf die Rechnung soll der gesamte Betrag in den Betrag-Satz-Null genommen werden."
Meine Wunschvariante. Ist das so RKSV konform?

**Comment by ErichFreitag** [comment]
Ja, sie können eine der drei Möglichkeiten wählen. a) und b) sind im Erlass angeführt, c) ist in der WKO-FAQ enthalten.

Welche Variante sie wählen ist zunächst egal (außer möglichen Auswirkungen Richtung Buchhaltung, einfacheren oder komplizierteren Nachweisen bei Prüfungen etc.). "RKSV-konform" ist ein heikles Thema - Gesetz ist nur die RKSV; der Erlass und die WKO-FAQ sind Rechtsmeinungen des BMF, an denen man aber wohl nicht herumkommt, die auch sinnvoll sind und die Implementierung der RKSV in bestimmten Geschäftsfällen detaillieren. 

Wenn sie also nach diesen Regelungswerken implementieren wird dagegen wohl niemand argumentieren können, dass es nicht RKSV-konform sei. Bezüglich "wie sie es warum genauso machen" wird eine entsprechende Dokumentation nicht schaden.

Welche Variante sie wählen wird davon abhängen, wie sie es am sinnvollsten und einfachsten implementieren können. Da hat jeder Hersteller so seine Schwierigkeiten und Präferenzen. c) ist beispielsweise überhaupt erst spät dazugekommen, weil sich halt manche wieder damit leicher tun.

a) sie erhalten eine Barzahlung, das ist ein Barumsatz und wäre zu signieren. Die hier skizzierte Variante "umgeht" die RKSV, weil es schon eine Rechnung gibt und die Zahlung auf die Rechnung referenziert - ansonsten (Axel verzeih, ich hab es nicht erfunden - siehe oben) die Umsatzsteuerschuld doppelt geschuldet werden würde.

b) ist wohl das, was Axel Kutschera und ich mit "alles in 0%" meinen

c) teilen sie genauso auf, wie es den Steuersätzen entspricht plus eventueller Rundung in einem Steuersatz, vor allem bei Teilzahlungen.

Schauen sie in den Erlass zu den betreffenden Punkten (2.4.11 und 4.6.6) und in die WKO-FAQ zu 4.6.6.

**Comment by cashReg1984** [comment]
@ErichFreitag & @AxelKutschera 
Glaube das ist jetzt klar für mich. Werde wohl die Variante b umsetzen.
Besten Dank für die kompetenten Auskünfte!

**Comment by AxelKutschera** [comment]
@cashReg1984 b) und c) ist zulässig.
