### ISSUE TITLE
Umsatzzähler Verschlüsselungsdifferenz

### ISSUE THREAD

**Issue by cwlent** [a-sit-plus/at-registrierkassen-mustercode#28]
Hallo,

die Umsatzzähler Verschlüsselung von der demo kassa mit dem Umsatzzähler Verschlüsselung von a-Trust verglichen und bekommen unterschiedliche Werte bei den selben Parametern!

KassenID = DEMO-CASH-BOX932
Belegnummer = 222858
Umsatzzähler = 0
aesKey = vKAPeUsPJWATuLBRKR0rFJoLyfnF7iDKJWZ9jJJhVdY=

mustercode (DemoCashBox) Ausgabe:
16: jTBqW2Jwi6fvqLntYgZl4Q== 
  8: jTBqW2Jwi6c=

a-Trust (Umsatzzähler in C#):
16: b3Cyscs9VYUFnS5Dd+cNlA==
  8: b3Cyscs9VYU=

Sollen nicht nach unserer Meinung  die Werte gleich sein?

**Comment by lebail** [comment]
Ich bekomme mit meinen (völlig unabhängig von den genannten Beispielcodes erstellten) benutzerdefinierten SQL-Funktionen in C das selbe Ergebnis wie die Demo-Cashbox:

     SELECT TO_BASE64(AES256_CTR(
       TO_BINARY(0, 8),                              /* Umsatzzähler: 0, Länge: 8 */
       SHA256('DEMO-CASH-BOX932' || '222858', 16),   /* IV = erste 16 Bytes des Hash */
       FROM_BASE64('vKAPeUsPJWATuLBRKR0rFJoLyfnF7iDKJWZ9jJJhVdY=')
     ), 0)                                           /* 0 = BASE64, 1 = BASE64URL */

Ergebnis:

     jTBqW2Jwi6c=

**Comment by A-Trust** [comment]
Mit Ihren Daten bekommen wir die gleichen Ergebnisse wie die DemoCashBox:

```
public static void Test3()
{
  Console.WriteLine("TEST3 - Hersteller Test");

  string kassenID = "DEMO-CASH-BOX932";
  Console.WriteLine("Kassen ID: " + kassenID);

  string belegnummer = "222858";
  Console.WriteLine("Belegnummer: " + belegnummer);

  string aesB64 = "vKAPeUsPJWATuLBRKR0rFJoLyfnF7iDKJWZ9jJJhVdY=";
  byte[] aesKey = Convert.FromBase64String(aesB64);

  long umsatz = 0;
  Console.WriteLine("Umsatz: " + umsatz);


  byte[] encryptedBytes = RKAesIcm.Encrypt(umsatz, kassenID, belegnummer, aesKey);
  Console.WriteLine("Verschlüsselter Umsatz (B64): " + Convert.ToBase64String(encryptedBytes));
} 
```

Ausgabe:
```
TEST3 - Hersteller Test
Kassen ID: DEMO-CASH-BOX932
Belegnummer: 222858
Umsatz: 0
Verschlüsselter Umsatz (B64): jTBqW2Jwi6fvqLntYgZl4Q==
```

Bitte kontrollieren Sie den AES Schlüssel in ihrem Testcode.

**Comment by cwlent** [comment]
Danke A-Trust für den Hinweis!

Das Problem lag an der Anwendungskonfigurationsdatei,diese wurde nicht korrekt in das Ausführungsverzeichnis übernommen.

Jetzt ist der Fehler behoben und die Werte sind gleich.

**Comment by shawtaylor** [comment]
@ lebail 

Funktioniert dein SQL?

**Comment by lebail** [comment]
Ja.

Die im Beispiel vorkommenden Funktionen sind allerdings in C geschriebene benutzerdefinierte SQL-Funktionen für SQLite; die sind standardmäßig nicht vorhanden.

**Comment by shawtaylor** [comment]
Habe es jetzt über MariaDB gemacht.

SET SESSION block_encryption_mode='aes-256-ecb';
SELECT TO_BASE64(    
                  AES_ENCRYPT(    
		                        CAST(0 AS BINARY) ,    
		                        SHA2('DEMO-CASH-BOX932' || '222858',256),        
		                        FROM_BASE64('vKAPeUsPJWATuLBRKR0rFJoLyfnF7iDKJWZ9jJJhVdY=')     
				        )
			    )	
 
	Ergebnis: 5Az/8Efxqu12oatP7rTB6g==				 
	Geht leider nicht!

**Comment by Scaenicus** [comment]
Kurze Frage: Werden alle Währungsbeträge und der Summenspeicher als Ganzzahl (z.B. x100 in Cent) zusammengerechnet?
Unterschiedliche Systeme stellen die gleiche Fließkommazahl als Binärcode anders dar - das ist eine häufige Falle beim Hashen und Verschlüsseln von Kommazahlen.

**Comment by lebail** [comment]
@shawtaylor: Ich habe mich mit der AES_ENCRYPT()-Funktion von MariaDB noch nicht beschäftigt, aber da diese den CTR-Modus nicht unterstützt, müsste man wohl die im Detailfragen-Dokument unter Punkt 2.5.4 beschriebene Ersatz-Implementierung per ECB durchführen.

Außerdem tut CAST(0 AS BINARY) sicher nicht das Gewünschte, denn das wandelt lediglich die Zahl 0 in einen Textstring '0' um (der BINARY-Typ von MariaDB ist im Prinzip dasselbe wie CHAR).

Und der Initialisierungvektor sollte lediglich aus den ersten 16 Bytes des SHA256-Hashes bestehen.

@Scaenicus: Der Umsatzzähler wird als Integer in Cent geführt.

Wie man vom Rechnungsbetrag dorthin kommt, ist nicht spezifiziert. Ich habe es z.B. so gemacht, dass ich bereits beim Erstellen der Rechnung zwar Einzelpreis und Anzahl eines Rechnungspostens noch als Fließkomma speichere (damit man auch 0,675 kg * 1,1255 €/kg etc. machen kann), den sich daraus ergebenden Nettopreis jedes Postens aber mal 100 rechne und kaufmännisch auf einen Integer runde. Alle weiteren Berechnungen (auch die USt.) arbeiten dann nur mit Ganzzahlen in Cent. So kann man, wenn man es richtig macht, auch jegliche Rundungsdifferenzen zwischen Netto- und Bruttosumme der Gesamtrechnung ausschließen.

**Comment by Scaenicus** [comment]
@lebail super Antwort, aber meine Frage war eigentlich an @shawtaylor zur Fehlersuche, bei mir wird alles in der Software berechnet und funktioniert schon. :-)

**Comment by lebail** [comment]
@Scaenicus: Ja, ich habe mich ohnehin gewundert; bei mir ist aber anfangs nur der erste Absatz erschienen, und der sah wirklich nach einer allgemeinen Frage aus.

Ansonsten: Betreffend die Umwandlung des Umsatzzählers ins Binärformat: Ich weiß nicht, ob MariaDB eine passende Funktion hat. Auf die Schnelle konnte ich keine finden.

Wahrscheinlich muss man das als Schleife programmieren, in MySQL bzw. MariaDB gibt es sowas ja. In dem von mir benutzten SQLite nicht, daher habe ich es als user-defined function in C gemacht. Auch wenn das nicht viel hilft, hier mein entsprechender C-Code:

```
static void uf_TO_BINARY(sqlite3_context *cdb, int argc, sqlite3_value **argv)
{
  if(argc == 2)
  {
    long long value = sqlite3_value_int64(argv[0]);
    size_t length = sqlite3_value_int(argv[1]);

    if(length > 0 && length <= 8)
    {
        unsigned char out[length];
        unsigned char *endptr = out + length;
        unsigned char *ptr = endptr;
	    
        do
	{
	  *--ptr = (unsigned char)(value & 0xff);
	  value >>= 8;
	}    
	while(--length);
	    
	sqlite3_result_blob(cdb, ptr, endptr - ptr, SQLITE_TRANSIENT);
	return;
    }
  }
  sqlite3_result_null(cdb);
}

```

**Comment by shawtaylor** [comment]
@lebail  Was hast du als Ergebnis bei

 SELECT   SHA256('DEMO-CASH-BOX932' || '222858', 16)

**Comment by lebail** [comment]
Ich habe es noch BASE64-kodiert, damit man etwas lesen kann:
`SELECT TO_BASE64(SHA256('DEMO-CASH-BOX932' || '222858', 16), 0)
`
Ergebnis: 3BwHC3E3telOSaOMF5ulKw==

**Comment by shawtaylor** [comment]
@Scaenicus
Hab es schon 1 Woche in C# ausprobiert. Habe aber kapituliert ;-)
