### ISSUE TITLE
Nullbeleg nach Ausfall der Signierungseinheit

### ISSUE THREAD

**Issue by theshadowtwentyseven** [a-sit-plus/at-registrierkassen-mustercode#280]
**Szenario**: Start Belegt erstellt, Registrierkasse ist in Betrieb. Nun fällt die Signier Einheit aus. Also wird jeder reguläre Beleg geprüft ob sie funktioniert und falls nicht gemäß "Detailspezifikationen" Absatz Abs. 6. mit "Sicherheitseinrichtung ausgefallen" im DEP gekennzeichnet.

Nun wird die Signier Einheit repariert und ist erneut verfügbar. Dies merkt das System natürlich erst beim signieren der nächsten Rechnung (zB. #999) auf.

**Frage**: Wie soll dies im DEP festgehalten werden? Mittels:

A) Sammelbeleg der Wiederinbetriebnahme der Signatur Einheit gemäß § 17 Abs. 4. gefolgt von
B) Regulär signierter Rechnung

oder in umgekehrter Reihenfolge nämlich B) und dann A)

Wichtig: bei uns entspricht Belegnummer = Rechnungsnummer.

Die Herausforderung ist, dass für jede Rechnung eine einzigartige Rechnungsnummer vergeben wurde, #999 in unserem Fall. Somit könnten wir bei A)+B) entweder beide mit #999 kennzeichnen oder müssten die nächst freie für den Sammelbeleg vergeben. Womit wir aber erst recht ungültig wären, den A hätte zb. #1000 bzw. B. #999.

**Comment by ErichFreitag** [comment]
a) "Sicherheitseinrichtung ausgefallen" nicht nur im DEP, sondern auch auf dem Beleg aufgedruckt und statt der Signatur im maschinenlesbaren Code

b) Rechnung ist Rechnung und Beleg ist Beleg. Die RKSV interessiert nur Barumsätze mit Belegen.

c) es sind beide Reihenfolgen zulässig. Den Sammelbeleg vor einem wieder signierten Beleg einzuschieben ist technisch meist schwieriger. Damit auch die nächste freie für den Sammelbeleg, in Sonderfällen auch ein eigener Nummernkreis.

**Comment by theshadowtwentyseven** [comment]
Danke schön für die super schnelle Antwort. Sprich:

* die Belege haben einen von der Rechnungsnummer unabhängigen Zähler
* damit können wir Rechnung die "auf Rechnung" ausgestellt werden sauber separieren:
 * dort wird bloß Rechnungsnummer erhöht, aber kein DEP Eintrag erstellt und
 * die Belegnummer wir nur auf Barrechnungen angedruckt und kann mit DEP referenziert werden

**Comment by ErichFreitag** [comment]
Wenn nichts grobes dagegen spricht würde ich für die Barumsätze via RKSV immer eine eigene und fortluafende Belegnummer führen, das erspart viel Kopfzerbrechen und Erklärungsaufwand. Also ja, so wie ausgeführt - super (die Belegnummer nur auf Belegen mit Barumsätzen um ganz genau zu sein).
