### ISSUE TITLE
Nicht steuerrelevante Kassaein- Ausgangänge

### ISSUE THREAD

**Issue by Tom-KK** [a-sit-plus/at-registrierkassen-mustercode#283]
Muss ein nicht steuerrelevanter Kassaeingang/ausgang (Eingang:Wechselgeld / Ausgang:Ich nehme im laufenden Betrieb Geld aus der Kassa um etwas zu bezahlen) signiert werden?

Wen Ja: Ich nehme an, dieser muss dann der Betrag-Satz-Null übergeben werden? Weitere Frage: Muss der Summenzähler in diesem Fall aufaddiert werden?

**Comment by AxelKutschera** [comment]
Nein

(Wenn Ja, würde der Betrag-Satz-Null übergeben und der Summenzähler aufaddiert werden.)

**Comment by Tom-KK** [comment]
Vielen Dank

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
