### ISSUE TITLE
QR-Code "JIS X 0510:2004"

### ISSUE THREAD

**Issue by Tom-KK** [a-sit-plus/at-registrierkassen-mustercode#284]
In der „Festlegung des BMF zu Detailfragen RKVS“ steht auf Seite 49, dass der QR-Code nach Standard: „JIS X 0510:2004“ erstellt werden soll.

Soweit wir recherchiert haben, ist das ein Micro-QR Code, der maximal 21 alphanumerische Zeichen darstellen kann.

21 alphanumerische Zeichen ist jedoch viel zu wenig.
Wie ist das zu verstehen ?

**Comment by lebail** [comment]
JIS X 0510 wurde im Jahr 2004 um den Micro QR Code _erweitert_. Der "normale" QR-Code ist darin aber immer noch enthalten. Und einen solchen muss man hier verwenden.

**Comment by Tom-KK** [comment]
Was genau ist der "normale" QR-Code ?


PS Vielen Dank für diesen Eintrag
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/44

**Comment by lebail** [comment]
Jeder, der in JIS X 0510 spezifiziert ist und die erforderliche Zeichenzahl kodieren kann. Das wären "QR-Code Model 1" und "QR Code Model 2". Empfehlenswert ist wohl Model 2 - wegen der besseren Fehlerkorrektur.

**Comment by Tom-KK** [comment]
Gut, scheinbar haben wir den Standard JIS X 0510 2004 falsch verstanden.
Wir wären der Meinung gewesen, es handle sich dabei **ausschließlich** um den Micro QR Code.

Vielen Dank

**Comment by AlgoLinz** [comment]
Kann jemand vielleicht eine Bibliothek für die Erzeugung von QR-Codes (JIS X 0510 2004) für C# vorschlagen?

**Comment by areiter** [comment]
@AlgoLinz  habe mit ZXing gute Erfahrungen gemacht 
https://zxingnet.codeplex.com/

**Comment by AlgoLinz** [comment]
Danke @areiter
Ich verwende auch ZXing aber in der Dokumentation finde ich keine Angaben bezüglich JIS X 0510 2004.
Deshalb die Frage nach eventuellen alternativen.

**Comment by lebail** [comment]
Das, was man üblicherweise als QR-Code bezeichnet, ist genau das, was in JIS X 0510:2004 spezifiziert ist. Wenn eine Bilbliothek QR-Codes erzeugt, welche mit gängigen Programmen lesbar sind, dann werden diese ziemlich sicher dem genannten Standard entsprechen (sonst wären sie ja nicht lesbar).

**Comment by Phoniexk** [comment]
Ganz einfach: QR-Code mit einer Bibliothek erstellen, die BMF Beleg-Check-App verwenden (vorher ausloggen), Code prüfen -> wird der Code von der App erkannt, dann passt alles.

**Comment by Tom-KK** [comment]
Alles Klar.
Vielen Dank für die Infos.
