### ISSUE TITLE
Berechnung Umsatzzähler bei bestehenden Kassen

### ISSUE THREAD

**Issue by UktTVg** [a-sit-plus/at-registrierkassen-mustercode#285]
Hallo,

wie berechnet sich der Umsatzzähler nach dem Startbeleg (wo er ja per Definition 0 sein muss), wenn zu einer bereits bestehenden und verwendeten Kasse die RKSV-Funktionalität hinzugefügt wird?
Das Prüftool meldet einen Fehler, wenn die maschinenlesbaren Codes der Belege nach dem Startbeleg nicht die korrekt weiterberechneten Umsatzzähler enthalten.

Kurzes Beispiel:
1. Kasse mit aktuellem Umsatzzähler von 2000 (Cent)
2. RKSV-Funktionalität wird aktiviert
3. Startbeleg wird erstellt mit Umsatzzähler 0
4. Standardbeleg mit Betrag 100 (Cent), Umsatzzähler 2100 (weil Umsatzzähler bevor RKSV aktiviert wurde auf 2000 war)

=> Prüftool schreit

Anders:
1.-3. gleich
4. Standardbeleg mit Betrag 100 (Cent), Umsatzzähler 100

=> Prüftool meldet keine Fehler, aber es entsteht ein zweiter, paralleler Umsatzzähler und beispielsweise auf Monatsbelegen entspricht der Umsatzzähler im maschinenlesbaren Code nicht dem textuell aufgedruckten Umsatzzähler am Beleg.

Welche Variante ist richtig?

**Comment by ErichFreitag** [comment]
Sie müssen sich lediglich vom Gedanken verabschieden, dass der RKSV-Umsatzzähler den Umsatz zählt. Ja, tut er schon, aber nicht exakt. Es ist ein Teil der Sicherheitseinrichtung, der mit dem Startbeleg bei 0 beginnt, völlig unabhängig vom tatsächlichen Kassen-Umsatzstand, und auf Lebenszeit der Kasse weiterläuft.
