### ISSUE TITLE
Monatsbeleg/ Month document context

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#29]
Are there any requirements or obligations in connection with creation of the "Monatsbeleg".
For example after midnight of the last day in calendar month must be created just Monatsbeleg as 1st document in new month, if not the cash register is locked for issuing the Payment documents.

Who is responsible for creating the Monatsbeleg, cash register or just owner of the cash register? 

Or are there any other rules in connection with Monatsbeleg.

**Comment by pteufl** [comment]
there will be further explanations for this and other use cases in an upcoming pdf document.
some short answers:
-there is no obligation to keep the "Monatsbeleg"
-the register could do this automatically, but also the owner by entering 0 for all tax-sets
