### ISSUE TITLE
Überprüfung Verschlüsselung CTR über ECB

### ISSUE THREAD

**Issue by maxstricker** [a-sit-plus/at-registrierkassen-mustercode#291]
Hallo,

ich würde gerne meine Implementierung der Verschlüsselung des Umsatzzählers teste, komme aber nicht ganz auf die Musterlösung hin. Als Referenzwerte verwende ich [diese](https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/44).
Da meine AES256-library in C kein CTR kann, muss ich ihn über ECB emulieren, wie in 2.5.4 der Dokumentation beschrieben.
Wie ich das Verstanden habe erzeuge ich den IV aus SHA256(KassenID+Belegnummer).
Daraufhin rechne ich AES256-ECB auf den IV. Daraufhin werden die Bytes des Umsatzzählers über XOR mit dem verschlüsselten IV verrechnet. Zum Schluss kodiere ich das Ergebnis noch Base64 und es sollte passen.

Hier die Ausgabe meines Programms:
```
KASSEN-ID: "DEMO-CASH-BOX817"
BELEGNUMMER: 83470
UMSATZ: 8733

AES KEY: RCsRmHn5tkLQrRpiZq2ucwPpwvHJLiMgLvwrwEImddI=
AES KEY binary: 68 43 17 152 121 249 182 66 208 173 26 98 102 173 174 115 3 233 194 241 201 46 35 32 46 252 43 192 66 38 117 210

IV binary: 9 57 141 91 161 44 37 40 183 9 90 216 55 63 93 20

DATA: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 34 29

VERSCHLÜSSELT: vXvqlWy0797woqe38ehByg==
VERSCHLÜSSELT binary: 118 88 118 113 108 87 121 48 55 57 55 119 111 113 101 51 56 101 104 66 121 103 61 61
```

Korrekt wäre `vXvqlWy0zcM=`, d.h. die ersten 8 bytes sind korrekt.

Wenn ich [diesen PHP Demo Code](https://gist.github.com/smtm/092b3e441feb405374c1322758140c66) verwende, die entsprechenden Daten eintrage und AES-256-ECB durch AES-256-CTR ersetze erhalte ich "mein" Ergebnis `vXvqlWy0797woqe38ehByg==`

Liegt es an der Codierung/Länge des Umsatzzählers? Wie kann ich die Richtigkeit der Implementierung überprüfen?
Für [das Beispiel hier](https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/28) erhalte ich z.B. `miysFL45LoO60sTNJ1g39Q==`.

Grüße,
maxstricker

**Comment by areiter** [comment]
Ich denke ihr Umsatzzähler ist zu lang. Der hat im genannten Beispiel 16 byte (Data) 
Data sollte folgendermaßen aussehen (für 8byte lange Umsatzzähler):
`DATA: 0 0 0 0 0 0 34 29 0 0 0 0 0 0 0 0` 

Nach dem XOR nehmen sie dann die ersten 8 byte und führen eine base64 kodierung durch, dann kommt das gewünschte Ergebnis `vXvqlWy0zcM=` raus.

**Comment by maxstricker** [comment]
Vielen Dank, nun komme ich auf das korrekte Ergebnis.
