### ISSUE TITLE
Durchlaufende Posten und RKSV-Umsatzzähler

### ISSUE THREAD

**Issue by ChristianSpath** [a-sit-plus/at-registrierkassen-mustercode#292]
Hallo zusammen!

Erhöhen durchlaufende Posten den Umsatzzähler der RKSV? Wie sieht es mit Trinkgeldern aus?

Ich habe die Detailfragen und die Spezifikation durchgesehen und Informationen zu Trinkgeldern und durchlaufenden Posten gefunden, aber leider nicht ob sie den Umsatzzähler der RKSV beeinflussen.

Vielen Dank für eure Hilfe!

**Comment by lebail** [comment]
_Alles_, was signiert wird, ist zum Umsatzzähler zu addieren. Auch wenn es freiwillig signiert wird. Und auch wenn es dazu führt, dass manche Umsätze mehrfach den Umsatzzähler erhöhen (z.B. Gutscheinkauf und dessen spätere Einlösung).

**Comment by ChristianSpath** [comment]
Danke für die schnelle Antwort!!!

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
