### ISSUE TITLE
Testumgebung A-Trust RK Mobile

### ISSUE THREAD

**Issue by smtm** [a-sit-plus/at-registrierkassen-mustercode#293]
Ich bekomme am Mac wenn ich versuche mich mit dem Test/Abnahme System der mit dem URL https://hs-abnahme.a-trust.at/asignrkonline/v2 (das a.sign RK Mobile Service) zu verbinden diese Meldungen:

![image001](https://cloud.githubusercontent.com/assets/3277/22749842/029053be-ee2f-11e6-9061-7f359dea4d5a.png)

Auf Anfrage beim (kostenpflichtigen?) A-Trust Support kam diese Antwort:

"Sie müssen dem Aussteller-Zertifikat vertrauen. Sie finden die Zertifikate unter:
https://www.a-trust.at/certs/A-Trust-Root-05.crt
https://www.a-trust.at/certs/a-sign-SSL-EV-05.crt"

![image001](https://cloud.githubusercontent.com/assets/3277/22749664/6bdeab8c-ee2e-11e6-9f27-0d0b71cde5f2.png)
![image002](https://cloud.githubusercontent.com/assets/3277/22749684/7f770ad6-ee2e-11e6-85f1-582b3b840042.png)

Hatten andere beim Ansprechen der A-Trust Umgebung auch diesen Zustand?

Ist es normal das ein Testserver eines Zertifikatanbieters solche "untrusted Meldungen generiert, oder könnte das vielleicht an meinem Environment liegen. Bin auf MacOS Sierra 10.12.3.

Bin etwas verunsichert.

**Comment by Phoniexk** [comment]
Ich glaube da bräuchten wir noch ein paar genauere Infos wie Sie genau mit der REST-Schnittstelle von RK-Online kommunizieren. Welche Programmiersprache, Programmcode mit ihren bisherigen Versuch. Prinzipiell sind im Developer Manual von RK-Online Beispiele für die gängigsten Sprachen auch Beispiele enthalten.

Ich musste für die Kommunikation mit der API bisher gar keine Zertifikaten hinzufügen.

PS: Der kostenpflichtige Support ist im RK-Partnervertrag von A-Trust angeführt!

**Comment by AxelKutschera** [comment]
Wir helfen gerne mit unserer kostenlosen Schnittstelle und dem Verwaltungsportal weiter:
https://github.com/fiskaltrust/interface

**Comment by smtm** [comment]
@Phoniexk Der Code ist in Ruby, aber das ist noch gar nicht das Problem. Die Aussage von A-Trust ist ich soll bei mir Zertifikate installieren um mit deren Test Server zu kommunizieren? Ok, kann ich gerne machen und hier 3-4 Stunden versenken um mit deren kryptischen und knappen Angaben die Konnektivität herzustellen. 

Nur mir kommt es komisch vor dass eine Zertifizierungsstelle es nicht schafft einen Server so herzurichten dass ein Herumfummeln mit Zertifikaten ein Nicht-Thema ist.

Ok aber hier nun konkret der Code  der Ruby Klasse

```
require "cgi" 
require 'net/https'
require "uri" 

class Asignrkonline

  def self.init
    @partner_username = "partner4711" 
    @partner_password = "partnerpwd" 

    @user_name        = "u478999999" 
    @user_password    = "999999f" 

    @url = 'https://hs-abnahme.a-trust.at/asignrkonline/v2'
  end

  def self.sign_hash(hash)
    self.init
    url = "#{@url}/#{@user_name}/Sign/Hash" 
    uri = URI.parse(url)
    request = Net::HTTP::Post.new(url)
    request.add_field"Content-Type", "application/json\r\n" 
    request.body = {:password=>@user_password,:hash=>hash}.to_json
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true 
    response = http.request(request)
    response.body   
  end
end

```

Bei 
response = http.request(request)

kommt die Meldung 

`Errno::ECONNRESET Exception: Connection reset by peer - SSL_connect
`
Daher mein Ansatz: Zuerst mal schauen ob ich mit dem Browser an den Server komme.

Ich bin gerade dabei das cas.pem File einzubauen das hier http://labs.a-trust.at/developer/ShowSource.aspx?id=118  mit drinnen ist. Das ist jedoch vom 16.10.2015. Wäre gut möglich dass das .cas File nicht nicht mehr up to Date ist, zumal sich die Pfade laut Doku geändert haben.

```
def self.sign_hash(user_name,user_password,hash)
    self.init
    url = "#{@url}/#{@user_name}/Sign/Hash"
    uri = URI.parse(url)
    request = Net::HTTP::Post.new(url)
    request.add_field"Content-Type", "application/json\r\n"
    request.body = {:password=>@user_password,:hash=>hash}.to_json

    pem = File.read("config/atrust/cas.pem")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.cert = OpenSSL::X509::Certificate.new(pem)
    http.key = OpenSSL::PKey::RSA.new(pem)
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    response = http.request(request)
    response.body   
  end
```


Jetzt bekomme ich da Meldung bei 

`http.key = OpenSSL::PKey::RSA.new(pem)
`

`Neither PUB key nor PRIV key:: nested asn1 error
`
Hmhh, what next?

PS: Hab auch kein Problem für Support zu zahlen wenn das Problem gelöst wird :)

**Comment by Phoniexk** [comment]
Ok bei Ruby kann ich leider nicht direkt helfen, da ich C# verwende. Generell muss man darauf achten, dass kein SSL3 für die Kommunikation aktiviert ist, d.h. am Besten schauen dass nur TLS 1.1 oder TLS 1.2 verwendet wird. 

In C# hatte ich keine Probleme mit der Verwendung des Testsystems: https://hs-abnahme.a-trust.at/asignrkonline/v2/

Im Live-System https://hs-abnahme.a-trust.at/asignrkonline/v2/ wird aber hingegen ein Zertifikat von DigiCert verwendet, dementsprechend sollten Sie dort keine Fehlermeldung bekommen.

Da beim Testsystem eben nur Testdaten zum Einsatz kommen, wird dort scheinbar auch nur ein selbstsigniertes Zertifikat eingesetzt. Also für das Testsystem wird dann in Ihrem Fall nichts anderes über bleiben, als die Zertifikate zu installieren. 

Ich kenne mich mit Ruby nicht aus, aber möglicherweise gibt es eine Möglichkeit die Prüfung der Zertifikate zu unterdrücken bzw. Fehler zu ignorieren. Wie gesagt im Live-System werden andere Zertifikate verwendet.

http://stackoverflow.com/questions/7969688/how-to-connect-to-an-https-server-with-an-invalid-certificate-using-the-latest-v

**Comment by csokay** [comment]
Das Problem ist so wie von A-Trust beschrieben. Deren Root-Zertifikate müssen am Mac importiert werden, damit der Mac denen automatisch vertraut. 
Importieren geht ganz einfach über das Programm "Schlüsselverwaltung" (/Applications/Utilitues/Keychain.app). 
Oder in diesem Popup bei "Vertrauen" nicht "Use system defaults" wählen, sondern "Always Trust".

Hintergrund ist, dass die Root Zertifikate von A-Trust anscheinend bei Apple nicht hinterlegt sind, und daher nicht automatisch im Betriebssystem.

Ich hoffe, das hilft.

**Comment by smtm** [comment]
Okay, wow. That much for using the latest Software...

Super Danke für die Inputs. Ich habe dann die Curl Beispiele mit oder ohne dem Parameter --cacert cas.pem gemacht.

```
curl --cacert cas.pem -o outputSign.txt -X POST -H "Content-Type: application/json" -d @requestSign.json "https://hs-abnahme.a-trust.at/RegistrierkasseMobile/v1/u123456789/Sign"

curl -o outputSign.txt -X POST -H "Content-Type: application/json" -d @requestSign.json "https://hs-abnahme.a-trust.at/RegistrierkasseMobile/v1/u123456789/Sign"
```
Dann Terminal geschlossen  und wieder aufgemacht. Dann ging's ohne --cacert Parameter. Super & Yay.

Ich kämpfe noch mit der Ruby Net:HTTP Library und dem start block wie hier beschrieben 

http://stackoverflow.com/questions/7969688/how-to-connect-to-an-https-server-with-an-invalid-certificate-using-the-latest- .
Aber das krieg ich hin.

Aber ich glaube ich teste die Signiermethoden gleich gegen den a-trust Produktionsserver. Da sollte es diese SSL CERT Themen hoffentlich nicht geben. Wäre dann ein a-trust User / Zertifikat zum testen der nie bei FON registriert wird.

**Comment by Phoniexk** [comment]
> Aber ich glaube ich teste die Signiermethoden gleich gegen den a-trust Produktionsserver. Da sollte es diese SSL CERT Themen hoffentlich nicht geben. Wäre dann ein a-trust User / Zertifikat zum testen der nie bei FON registriert wird.

Wir haben auch sowohl für RK Online als auch RK Chip jeweils ein Zertifikat im Produktivsystem von A-Trust auf unser Unternehmen registriert. Im FinanzOnline haben wir aber auch Zertifikat und Kassa (aussagekräftiger Name wie "DEMOCASHBOX") im FON-Produktivsystem mittels Webservice registriert. Dadurch können/konnten wir einen echten Test machen, ob beim Kunden dann alles funktioniert. Nach erfolgreichem Test die "DEMOCASHBOX" einfach wieder außer Betrieb nehmen. 

Im Testsystem von FON stößt man leider immer wieder auf Fehlermeldungen, weshalb ein echter Test durchaus sinnvoll ist.

**Comment by smtm** [comment]
Beim Produktivsystem (https://www.a-trust.at/asignrkonline/v2) gab es keine SSL Cert Issues. Sehr fein.

Ok, Test Zertifikat auf Produktion macht also durchaus Sinn, vor allem im Hinblick auf FON Zusammenspiel.

Also frei nach dem Motto: always test in production ;)
