### ISSUE TITLE
Zertifikat-Seriennummer

### ISSUE THREAD

**Issue by walterpan** [a-sit-plus/at-registrierkassen-mustercode#295]
Welches Format muss die Zertifikatsseriennummer im Payload haben? 
Beispiel:
JWS Payload '_R1−AT0_DEMO−CASH−BOX817__83468_2015−11−25T19:20:10_0,00_0,00_0,00_0,00_0,00_sqv3XHcI8mU=_−3667961875706356849_d3YUbS4CoRo='
Die einzelnen Werte dieses Arrays sind durch Unterstriche ( _ ) getrennt. Der vorletzte Wert ist diese Seriennummer. Diese Nummer gibt es Dezimal und in Hex. Welche ist zu nehmen? Und ist sie im Beispiel gehasht oder ähnliches?
Ich programmiere eine Online-Kasse in PHP und sende zur Signierung die Posts an A-trust. Ich hoffe, jemand kann mir weiter helfen. Danke im voraus.

**Comment by Phoniexk** [comment]
Auf der Starseite finden Sie das Dokument **Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV)** dort wird beim Aufbau für den maschinenlesbaren Code ganz am Beginn, ich glaube Punkt 2.1, alles erklärt.

**Comment by walterpan** [comment]
Natürlich kannte ich dieses Dokument bereits. Es gibt nur so viele Beispiele, wo dieser Wert keine HEX-Zahl zu sein scheint. Das hat mich etwas verwirrt.
Trotzdem, danke für die Info.
