### ISSUE TITLE
Frage bezüglich Prüfung der Belegverkettung

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#296]
Guten Tag,
ich möchte in unsere Kassensoftware eine Funktion integrieren die automatisch überprüft ob die Belegverkettung korrekt ist.
Soweit ich es verstanden habe ist immer ein Teil des vorherigen Beleges im nächsten Beleg vorhanden.
Ich konnte aber noch nicht herausfinden welcher Teil dies ist.

Wenn ich 2 aufeinanderfolgende Datensätze vergleiche finde ich hier keine entsprechende Gemeinsamkeit

"_R1-AT2_Testkasse Leibnitz_2016000012_2016-12-07T14:15:03_-12,00_0,00_0,00_0,00_0,00_U1RP_012A34FD67E57D6BCB58D1B156_nipa0uLwjzA=_0jOe8kGAUSih0gvZ4fyUQ9Z/1J8WFl64fqgjcMXGPzQtUSmwNO/eYQ13HxZfi9t16iESAzHavinBYxWWufimjw== / "

"_R1-AT2_Testkasse Leibnitz_2016000013_2016-12-07T14:19:47_-10,00_0,00_0,00_0,00_0,00_U1RP_012A34FD67E57D6BCB58D1B156_EDKu/IVRPvw=_RilP2t7S8CzmMFFR0nzq7qg6b9CS9IBDcWVcoLgd9l8q0wC2UqG8LMw62e/jHNBIkT+PFUTiol0ikhOcJ77o1Q== / "

Ich bitte um Hilfe.
Vielen Dank !

**Comment by ErichFreitag** [comment]
Sie werden so keine Gemeinsamkeiten finden, da ein Hash gebildet wird. Sehen sie bitte in der A-SIT-Detailspezifikation unter Punkt 2.4.2 nach - dort ist beschrieben, wie der Verkettungswert gebildet wird.

Übrigens zu den beiden Codes oben:
- da fehlt das Trennzeichen zwischen Uhrzeit und erstem Betrag.
- die Seriennummer ist außergewöhnlich lang
- das Leerzeichen und "/" am Ende der Signatur gehört da nicht her
- das Trennzeichen zu Beginn vor R1 fehlt
