### ISSUE TITLE
Verschlüsselung mit Crypto++ liefert falsches Ergebnis

### ISSUE THREAD

**Issue by MartinT85** [a-sit-plus/at-registrierkassen-mustercode#297]
Hallo zusammen,

Aktuell habe ich das Problem, dass das Prüftool mir im DEP.json einen DECRYPTED_TURNOVER_VALUE mit dem Wert 1572837564906061082 ausgibt. Im zu prüfenden DEP ist nur ein Startbeleg vorhanden, trotzdem erkennt er diesen aufgrund des Turnover Wertes als Nullbeleg.

Zu testzwecken steht auch in meiner cryptographicMaterialContainer.json der base64AESKey: WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=

Der Startbeleg hat die Belegnummer: 000000
Die Kassenbezeichnung lautet: CashBox01
Dies ergibt bei mir den Hash: 4b6740b0040082554ee53b4e6d6534068375dbf2a6bdfdeeaa0a40a6fa50bc80
welcher dann verkürzt wird zu 4b6740b004008255
Da es sich um einen Startbeleg handelt, ist der Umsatzzähler = 0, entspricht also einem Byte Array der Länge 16. welches mit 0 initialisiert wird.

Das Ergebnis der Verschlüsselung wird auf 8 Bytes verkürzt und anschließend Base64 kodiert.
Als Ergebnis erhalte ich QRQNs8pVEhQ=
sollte aber laut diesem Post https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/91
den Wert l/swzun6050= erhalten.

Meinen Quellcode kann man hier einsehen: http://pastebin.com/C4QqBTp1

Danke für die Hilfestellung!

**Comment by areiter** [comment]
Mir scheint es so als würden sie in folgendem Schritt Hex Darstellung und bytes verwechseln.
`memcpy(initialisierungsvektorBytes, initialisierungsvektor.data(), CryptoPP::AES::BLOCKSIZE);
//In 'initialisierungsvektorBytes' steht nun der folgende Text : 4b6740b004008255`

Wenn ich das richtig verstehe steht in `initialisierungsvektor` der IV als String in Hexkodierung. Wobei immer zwei Zeichen ein Byte darstellen `4b 67 40 ...`
Abgesehen davon dass sie den IV als String übergeben (was nicht korrekt ist) kürzen sie den IV hier also effektiv auf 8byte in hex Darstellung zusammen.

Sie müssten also zuerst `ivHashKomplett` dekodieren (oder erst gar nicht hex kodieren, wird im Beispiel nicht gezeigt) und davon dann die ersten 16 byte nehmen.

**Comment by ckvsoft** [comment]
Hallo

Vielleicht hilft das.
Der turnoverCounter sollte BigEndian sein.
```
byte key[ AES::MAX_KEYLENGTH ], iv[ AES::BLOCKSIZE ];
StringSource ssk(symmetricKey , true, new HexDecoder( new ArraySink(key, AES::MAX_KEYLENGTH)));
StringSource ssv(concatenatedHashValue, true, new HexDecoder( new ArraySink(iv, AES::BLOCKSIZE)));

    byte out[RKSuitSize];
    memset( out, 0x00, RKSuitSize );

    try {
        CTR_Mode<AES>::Encryption encryption(key,sizeof(key),iv, sizeof(iv));
        encryption.ProcessData(out,Union.data,sizeof(Union.data));
    } catch (Exception &e) {
        ...
    }

```

**Comment by MartinT85** [comment]
Vielen Dank für die hilfreichen Antworten! Ich konnte das Problem nun lösen und erhalte die gewünschten Ergebnisse 👍 Hätte tatsächlich die Umwandlung zu Hex lassen sollen und direkt weitergearbeitet...
