### ISSUE TITLE
Klarstellungen / Fragen Signaturerstellung JWS

### ISSUE THREAD

**Issue by maxstricker** [a-sit-plus/at-registrierkassen-mustercode#298]
Guten Tag,

ich bin an einer Implementierung der RKSV dran und arbeite das Dokument "Festlegungen des BMF ...) durch. Inklusive Punkt zwei scheint mir alles klar zu sein und ich kann nun die Prozesse nachbilden. 
Wo ich mir allerdings nicht sicher bin, ist die Erstellung der JWS-Signatur. Das JWS-Format ist mir klar, allerdings bin ich mir bei der Signaturberechnung unschlüssig.
Wie genau erfolgt diese? Ich habe hier eine SmartCard der A-Trust, wie wird diese in den Prozess eingebunden? Muss die Signaturberechnung auf der SmartCard erfolgen? Oder ist es auch zulässig die Signatur in Software zu rechnen? Das Zertifikat könnte ich ja aus der Karte auslesen.

Hat jemand Code/Beispiele für mich? In den Festlegungen lese ich zur Signatur via APDUs "Code ist noch nicht vorhanden." 

Danke und Grüße

**Comment by ErichFreitag** [comment]
Die Signatur erfolgt über die SmartCard. Reine Software-Erstellung ist nur für geschlossene Gesamtsysteme zulässig.

Die "Festlegungen..." beschreiben den Prozess. Wie es konkret mit der A-Trust-Karte geht finden sie in den dortigen Spezifikationen. Dazu auch in diesem Forum z.B. nach "APDU" suchen.

Wie die Signatur funktioniert sehen sie im Dokument https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf.

**Comment by areiter** [comment]
Kleine Ergänzung: Sie können von der Smartcard zwar das Zertifikat auslesen, aber nicht den zugehörigen privaten Schlüssel der für die Signaturerstellung benötigt wird.
Dieser kann nur über die von der Smartcard bereitgestellten Funktionalitäten verwendet werden.

Codebeispiele zu A-Trust gibts z.B. hier: http://labs.a-trust.at/developer/ShowSource.aspx?id=114
