### ISSUE TITLE
Durchlaufposten, Umsatzzähler - Varianten

### ISSUE THREAD

**Issue by rhoefler** [a-sit-plus/at-registrierkassen-mustercode#299]
Trotz umfangreicher Beschäftigung sind mir manche Sachverhalte immer noch nicht ganz klar. Insbesonders zum Thema Durchlaufposten komme ich noch nicht ganz auf einen grünen Zweig.

Frage 1:
Es war hier öfters die Rede davon, dass nur gewisse Belege signiert werden müssen. Das Einzahlen aufs Kundenkonto ohne konkreten Geschäftsfall (bzw. Wertgutschein) oder die bare Begleichung einer vor einigen Tagen erstellten Warenwirtschaftsrechnung auf Ziel beispielsweise waren hier erwähnt als nicht signierungspflichtige Vorgänge. Nach meinem Verständnis heisst, dass ein nicht signierter Vorgang auch nicht im RKSV-DEP erscheint, denn schließlich ist im RKSV-DEP ja alles signiert, solange die Sicherheitseinrichtung nicht ausgefallen ist.

Bedeutet das, dass ich im alten DEP einen Vorgang habe, der im RKSV-DEP nicht vorkommt? 
Anders ausgedrückt, ich habe in einer bestimmten Zeitspanne (zB. 1 Stunde) 2 Barumsätze und 1 Begleichung einer alten Warenwirtschaftsrechnung auf Ziel - würde das alte DEP für diese Stunde nun 3 Vorgänge enthalten und das RKSV-DEP nur 2 Vorgänge?

Frage 2:
Könnte eigentlich ein Durchlaufposten als Nullbeleg im RKSV-DEP geführt werden?

Frage 3:
Vorausgesetzt, jeder Durchlaufposten wird signiert und es handelt sich dabei jeweils um einen Standardbeleg. Werden also alle Durchlaufposten signiert und damit dem 0% Umsatz zugerechnet (Einzahlung auf Kassa zB. Bankabhebung als positiver Betrag, dem entgegengesetzt die Auszahlung aus der Kassa zB. Bankeinzahlung als negativer Betrag) so entspricht der Umsatzzähler grundsätzlich immer dem Kassastand.

Die diesbezüglich Aussage von AxelKutschera im Issue 257:
"Die Option, dass alles signiert wird empfehle ich jedoch nicht, da die Kontrolle der Vollständigkeit durch das Finanzamt komplizierter wird."

ist für mich nicht ganz nachvollziehbar, da nach meinem Verständnis es hier am einfachsten wäre, da RKSV-DEP und Belege 1:1 übereinstimmen und zugleich Umsatzzähler = Kassastand

oder habe ich da etwas übersehen?

Frage 4:
Spricht etwas dagegen, jeden Vorgang also auch alle Durchlaufposten zu signieren und als 0%-Umsatz in einem Standardbeleg zu führen? 

Der Sinn der RKSV ist ja, dass mit jedem Beleg die Historie davor kryptografisch unveränderbar wird. Wenn ich mehr Vorgänge einbeziehe, so sind auch mehr Vorgänge unveränderbar festgehalten und damit der kryptografisch sichergestellte Manipulationsschutz auf einen größeren Kreis von Vorgängen ausgeweitet.

Frage 5:
Vorausgesetzt die Variante aus Frage 4 (alle Durchlaufposten sind 0% Umsatz und Beitrag zum Umsatzzähler) wird gewählt, so ist immer Umsatzzähler = Kassastand, außer ein Sonderfall:

Sicherheitseinrichtung ausgefallen

Zumindest habe ich es so aufgefasst, dass beim Sammelbeleg nach Wiederinbetriebnahme einer ausgefallenen Sicherheitseinrichtung die Summen seit dem Beginn des Ausfalls nach Steuersätzen aufgeschlüsselt ins RKSV-DEP geschrieben werden müssen, in weiterer Folge (vielleicht deshalb oder generell) verlangt das Prüftool 1.0.0 offensichtlich, dass die Summe dieses Sammelbelegs zum Umsatzzähler zu addieren ist.

Sehe ich das richtig? Gibt es noch andere Fälle dieser Art?

Frage 6:
Wäre es denkbar und sinnvoll, die Variante aus Frage 4 nur bei Einzahlungen zu wählen und neutrale Auszahlungen (zB. Bankeinzahlung) nicht im RKSV-DEP abzubilden?

Vielen Dank im Voraus!

**Comment by AxelKutschera** [comment]
Frage 1:
Die bare Begleichung einer vor einigen Tagen erstellten Warenwirtschaftsrechnung IST signierungspflichtig

JA: Im alten DEP ist ein Vorgang, der im RKSV-DEP nicht vorkommt.

Frage 2:
Wenn ein Durchlaufposten freiwillig erfasst wird, dann nicht als Nullbeleg sondern nur im Betrag-Satz-Null.

Frage 3:
Der Umsatzzähler kann grundsätzlich dem Kassastand entsprechen. 
Ausnahmen gibt es zB wenn ein Wertgutschein bei der Ausgabe freiwillig signiert wird und beim Einlösen verpflichtend signiert werden muss. Daher gehen wir auch den Weg, dass nicht freiwillig signiert wird, da die Nachvollziehbarkeit darunter leidet.

Sorry, jetzt lese ich erst, dass hier bereits auf mich Bezug genommen wird: 
Die diesbezüglich Aussage von AxelKutschera im Issue 257:
"Die Option, dass alles signiert wird empfehle ich jedoch nicht, da die Kontrolle der Vollständigkeit durch das Finanzamt komplizierter wird."

"RKSV-DEP und Belege 1:1 übereinstimmen und zugleich Umsatzzähler = Kassastand"
-- Wie oben beschrieben gibt´s das nicht.
ZB müssen zur Kontrolle der korrekten Besteuerung der Barumsätze ALLE Beleg kontrolliert werden und nicht nur die Bareingänge.
-- Ich akzeptiere aber auch andere Meinungen. :-)

Frage 4:
Spricht etwas dagegen, jeden Vorgang also auch alle Durchlaufposten zu signieren und als 0%-Umsatz in einem Standardbeleg zu führen?
-- Nein 

Frage 5:
Wie oben beschrieben - nein.

Sicherheitseinrichtung ausgefallen
Diverse Fälle sind in anderen Issues beschrieben bzw. steht im Erlass ... oder will jemand anderer antworten?

Frage 6:
Das ist denkbar.

**Comment by ErichFreitag** [comment]
Zu Frage 5: der Sammelbeleg enthält als Nullbeleg zusätzlich die Angabe über Beginn und Ende des Ausfalls der Signaturerstellungseinheit. Das kann über Belegreferenzen und/oder über Datum und Uhrzeit erfolgen. Das hat aber nichts mit dem Umsatzzähler zu tun, denn dieser läuft ja auch mit ausgefallener Signaturerstellungseinheit weiter. 

In dem Sinne gibt es keine Sonderfälle. Signiert = Umsatzzähler beeinflusst. Nicht signiert = Umsatzzähler nicht beeinflusst.

**Comment by devobj** [comment]
> In dem Sinne gibt es keine Sonderfälle. Signiert = Umsatzzähler beeinflusst. Nicht signiert = Umsatzzähler nicht beeinflusst.

Wäre somit die folgende Aussage korrekt?
_Während die Sicherheitseinrichtung ausgefallen ist, ändert sich der Umsatzzähler nicht. Erst nach dem Sammelbeleg kann sich der Umsatzzähler wieder mit Standardbelegen oder Stornobelegen verändern._

**Comment by lebail** [comment]
Nein.

Auch jene Belege, die mit dem Text "Sicherheitseinrichtung ausgefallen" versehen wurden, gelten in diesem Zusammenhang als "signiert", kommen ins RKSV-DEP und ändern den Umsatzzähler.

Lediglich Belege, die bewusst nicht signiert werden (weil es nicht vorgeschrieben ist und man es auch nicht freiwillig tut), kommen nicht ins RKSV-DEP und beeinflussen den Umsatzzähler daher nicht.

**Comment by ErichFreitag** [comment]
Nein, weil der Umsatzzähler mit der Signaturerstellungseinheit nichts zu tun hat. Der läuft mit oder ohne Signatur wie bei jedem anderen Beleg weiter.

**Comment by rhoefler** [comment]
Vorerst vielen Dank für die raschen und zielgerichteten Antworten!

Einhaken möchte ich noch bei den Themen Sammelbeleg (nach Sicherheitseinrichtung ausgefallen) und Umsatzzähler, inbesonders betreffend der Aussage:

Signiert = Umsatzzähler beeinflusst. Nicht signiert = Umsatzzähler nicht beeinflusst.


Frage 7:

Für mich wäre alles stimmig, wenn folgendes gilt:

Standardbeleg - Beleg-Satz-xxx jeweils befüllt (natürlich auch 0 möglich) - Umsatzzähler beeinflusst
Stornobeleg - Beleg-Satz-xxx jeweils befüllt (natürlich auch 0 möglich) - Umsatzzähler beeinflusst
Startbeleg - Beleg-Satz-xxx jeweils 0 - Umsatzzähler auf 0 gesetzt
Nullbelege - Beleg-Satz-xxx jeweils 0 - Umsatzzähler NICHT beeinflusst
Trainingsbeleg - Beleg-Satz-xxx jeweils befüllt (natürlich auch 0 möglich) - Umsatzzähler NICHT beeinflusst

gleiches gilt natürlich, wenn obige Belegtypen während des Ausfalls der Signaturerstellungseinheit erstellt werden.

Sind wir uns hier soweit einig?


Frage 8:

Interessant wird es für mich beim Thema Sammelbeleg bei Reaktivierung der Signaturerstellungseinheit.

Hier haben Sie Herr Freitag im Issue 235 geschrieben:
Der Umsatz ist immer anzupassen, unabhängig von der Funktion der Signatureinheit. Der Sammelbeleg ist definitiv ein Nullbeleg, also mit 0 EUR Barumsatz (plus Information über Beginn und Ausfall der Signatureinheit), womit schon alleine aus diesem Grund der Umsatzzähler beim Sammelbeleg nicht angepasst werden kann.

Das heisst, der Sammelbeleg ist Nullbeleg, also müssen auch die einzelnen Beleg-Satz-xxx Beträge jeweils 0 sein?

Ich hab da doch irgendwo gelesen, dass die Summe der während des Ausfalls getätigten Umsätze nach Steuersätzen aufgeschlüsselt angegeben werden müssen. Das kann dann aber nur den physischen Beleg (Ausdruck/PDF) betreffen und nicht das DEP! Sehe ich das richtig?

**Comment by ErichFreitag** [comment]
Zu 7 sind wir uns einig, ja. Winzige Ausnahme: auch bei einem Nullbeleg wird der Umsatzzähler beeinflusst, nämlich mit 0. Nur als formaler Hinweis, dass dafür keine Sonderbehandlung notwendig ist (im Gegensatz zum Trainingsbeleg).

Und der Sammelbeleg ist ein Nullbeleg, korrekt. Damit auch in den einzelnen Sätzen ein Betrag von 0. Die Ausnahme ist eben, dass Beginn und Ende des SEE-Ausfalls damit verbunden sein müssen. Die Summe des Umsatzzählers sieht man sowieso, weil er ja auch während des Ausfalls weiterläuft und jetzt 0 dazugezählt ergibt den aktuellen Umsatzzähler - ohne irgendwelche Besonderheiten, aber wie immer verschlüsselt im maschinenlesbaren Code.

Ich weiß nicht wo sie das gelesen haben, ich kenne das nicht. Und es gibt auch keinen physischen Ausdruck des Sammelbelegs - er muss nur im Datenerfassungsprotokoll (und zwar sowohl im RKSV-DEP als Nullbeleg als auch im Kassenjournal mit Beginn- und Ende-Information) irgendwie einsichtig sein, falls es jemand nachvollziehen möchte.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient der Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie, die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html). Sollte Ihr Anliegen dort nicht behandelt sein, bitten wir Sie, die am Ende dieses Dokuments genannten Kontaktpunkte bzw. Informationsquellen zu berücksichtigen.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur von den Benutzern der Organisation A-SIT Plus (pteufl, tzefferer, asitplus-pteufl) getätigt. Für die Korrektheit der Aussagen anderer Benutzerinnen und Benutzer kann keine Garantie übernommen werden.
