### ISSUE TITLE
Zahlenformat im QR Code (Komma oder Punkt)

### ISSUE THREAD

**Issue by andix25** [a-sit-plus/at-registrierkassen-mustercode#30]
In der Detailspezifikation steht hierzu folgendes:

> Betrag-Satz-Normal: Der Wert dieses Feldes entspricht dem in § 9 Abs. 2 Z 4 angegebenen Wert, JSON-Format **number** mit 2 Kommastellen. Ist kein Betrag mit dieser MWST vorhanden so wird 0,00 eingetragen.

Der Wert ``0,00`` (mit Komma) als JSON-"number" formatiert müsste doch nun ``0.00`` (mit Punkt) ergeben, oder vielleicht auch ``.00``.

Siehe RFC 4627 Abschnitt 2.4: https://tools.ietf.org/html/rfc4627. Es wird explizit ein Punkt (``.``) als ``decimal-point`` definiert.

Zum QR-Code sagt die Detailspezifikation nun:
>Die einzelnen Felder werden UTF-8 kodiert und mit dem Zeichen „_“ zusammengeführt und in einer Zeichenkette gespeichert. Unter Verwendung der oben genannten Bezeichner und der Notation Wert(JSON-Feld) für das **Extrahieren des Wertes aus der JSON-Datenstruktur** des Belegs ergibt sich folgende Darstellung.
>„Wert(Kassen-ID)_Wert(Belegnummer)_Wert(Beleg-Datum-Uhrzeit)_ Wert(Betrag-Satz-Normal)_Wert(Betrag-Satz-Ermaessigt-1)_Wert(Betrag-Satz-Ermaessigt-2)_Wert(Betrag-Satz-Null)_Wert(Betrag-Satz-Besonders)_ Wert(Stand-Umsatz-Zaehler-AES256-ICM)_Wert(Zertifikat-Seriennummer)_ Wert(Sig-Voriger-Beleg)“

Aus meiner Interpretation ergab sich also, dass Zahlen in den QR-Code auch mit JSON-Notation (mit Punkt) geschrieben werden müssen. 

**Jedoch benutzt Ihre Referenzimplementierung das deutsche Komma. Gibt es dafür eine Begründung? Widerspricht das nicht der Verordnung?**

Vielen Dank im vorhinein für die Klarstellung.

**Comment by pteufl** [comment]
Format ist ",".
Widerspricht nicht, Basis war JSON Number, mit Detailergänzungen die dann genauere Festlegungen machen.

**Comment by andix25** [comment]
Gibt es dazu eine Quelle dieser "Detailergänzungen"? Ich würde das gerne begründen können wieso ich es im Widerspruch zum Verordnungstext implementieren muss.

**Comment by pteufl** [comment]
Kläre das.

**Comment by andix25** [comment]
Danke!

**Comment by andix25** [comment]
Im Dokument "FESTLEGUNGEN DES BMF ZU DETAILFRAGEN DER
REGISTRIERKASSENSICHERHEITSVERORDNUNG (RKSV)" wurde nun das Komma als Dezimaltrennzeichen festgelegt.

Nun hab ich was handfestes nach dem ich mich richten würde und auf das ich mich beziehen kann.

Darf ich davon ausgehen dass das so bleibt? :)

**Comment by pteufl** [comment]
ja, diese Schreibweise ist auf jeden Fall gültig. Es wird noch abgestimmt ob andere Schreibweisen auch gültig sind.
