### ISSUE TITLE
Wo sind die Ergebnis-Codes für die "GetInfo" Abfrage dokumentiert?

### ISSUE THREAD

**Issue by rikogithub** [a-sit-plus/at-registrierkassen-mustercode#302]
Hallo,

weiß jemand wo die Rückgabecodes der C_RKInfo Funktion aus der asignp11.dll zu finden sind?
Mein Problem ist dass die Abfrage der Zertifikat-Seriennummer (GetInfo) den Code 0x00E0 rückliefert und ich keine Unterlagen finde wo die Codes beschrieben sind.

Danke!
Richard.

**Comment by argetherapie** [comment]
PKCS #11 V2.20: CRYPTOGRAPHIC TOKEN INTERFACE STANDARD

#define CKR_TOKEN_NOT_PRESENT                 0x000000E0

**Comment by rikogithub** [comment]
Danke für die Info...
Aber laut der Doku sollte dieser Code nicht zurückgeliefert werden:

_C_GetInfo
returns general information about Cryptoki. pInfo points to the location that receives the information.
Return values: CKR_ARGUMENTS_BAD, CKR_CRYPTOKI_NOT_INITIALIZED, CKR_FUNCTION_FAILED, CKR_GENERAL_ERROR, CKR_HOST_MEMORY, CKR_OK._

Wie kann man den Fehler beheben?
Heißt das der RK-Chip USB-Stick ist defekt, oder evtl. das Zertifikat nicht aktiviert?
Bei meinem Testserver (anderer RK-Chip USB-Stick) funktioniert die Abfrage ohne Fehler. Leider kann ich aktuell die Stick's nicht tauschen um das zu verifizieren...

Danke für weitere Infos...
Richard.

**Comment by argetherapie** [comment]
Wir haben das vor gut einem Jahr gemacht. Soweit ich mich jetzt erinnern kann, kam das wenn eine falsche Karte im Lesegerät (zB e-card oder Bankomatkarte) steckte. Die Doku schweigt sich darob aus, richtig.

Darauf hin haben wir das implementiert:

	/// <summary>
	/// PKCS #11 V2.20: CRYPTOGRAPHIC TOKEN INTERFACE STANDARD
	/// </summary>
	internal enum PKCS11ErrorCodes
	{
		CKR_GENERAL_ERROR =          0x00000005,
		CKR_FUNCTION_FAILED =        0x00000006,
		CKR_ARGUMENTS_BAD =          0x00000007,
		CKR_DATA_INVALID =           0x00000020, // 32
		CKR_DEVICE_REMOVED =         0x00000032, // 50
		CKR_ENCRYPTED_DATA_INVALID = 0x00000040, // 64
		CKR_TOKEN_NOT_PRESENT =      0x000000E0, // 224
		CKR_TOKEN_NOT_RECOGNIZED =   0x000000E1  // 225
	}

		/// <summary>
		/// Translate PKCS11ErrorCodes to Exceptions
		/// </summary>
		private static void pThrowPKCSError(int ret)
		{
			if (Enum.IsDefined(typeof(PKCS11ErrorCodes), ret)) {
				switch ((PKCS11ErrorCodes)ret) {
					case PKCS11ErrorCodes.CKR_GENERAL_ERROR:
					case PKCS11ErrorCodes.CKR_FUNCTION_FAILED:
					case PKCS11ErrorCodes.CKR_ARGUMENTS_BAD:
					case PKCS11ErrorCodes.CKR_DATA_INVALID:
					case PKCS11ErrorCodes.CKR_ENCRYPTED_DATA_INVALID:
						throw new RKSVException(
							new RKSVErrorInfo() {
								ErrorText = string.Format("Generelle SEE-Fehlfunktion:{0}Errorcode: {1}",
								Environment.NewLine, (PKCS11ErrorCodes)ret),
								Gestartet = true,
								IsValid = false
							});
					case PKCS11ErrorCodes.CKR_DEVICE_REMOVED:
					case PKCS11ErrorCodes.CKR_TOKEN_NOT_PRESENT:
					case PKCS11ErrorCodes.CKR_TOKEN_NOT_RECOGNIZED:
						throw new RKSVException(
							new RKSVErrorInfo() {
								ErrorText = string.Format("Die SEE ist nicht erreichbar!{0}" +
									"Errorcode: {1}{0}" +
									"Bitte stelle sicher, dass das Kartenlesegerät/USB-Chip angesteckt ist{0}" +
									"bzw die richtige Chipkarte eingesteckt ist.",
									Environment.NewLine, (PKCS11ErrorCodes)ret),
								Gestartet = true,
								NichtErreichbar = true,
								FalscheKarte = true,
								IsValid = false
							});
				}
			}
			throw new RKSVException(
				new RKSVErrorInfo() {
					ErrorText = string.Format("Generelle SEE-Fehlfunktion:{0}Errorcode: 0x{1:X4} ({1})", Environment.NewLine, ret),
					Gestartet = true,
					IsValid = false
				});
		}

Uns reicht das, da wir dem Chip so weit wie möglich aus dem Weg gehen.
Genaueres weiß vermutlich A-Trust..  ;-)

**Comment by rikogithub** [comment]
Ok... Danke für deine Infos...
Ich werde mir am Montag das Teil bringen lassen damit ich es durchchecken kann.
A-Trust werde ich auch fragen...

Falls noch jemand eine Info hat bitte hier posten...

Danke,
Richard.

**Comment by rikogithub** [comment]
A-Trust schweigt auf meine Anfrage...
Unser Kunde hatte keinen aktivierten Chip... nach der Aktivierung funktioniert jetzt alles wie gewohnt.

Danke,
Richard.
