### ISSUE TITLE
Stornobeleg U1RP

### ISSUE THREAD

**Issue by schuhlos** [a-sit-plus/at-registrierkassen-mustercode#304]
Hallo,

ich habe eine grundsätzliche Frage in Bezug auf das Prüftool und dem Stornobeleg. Die Prüfung des DEP mittels dem bereigestellten Tool ist solange erfolgreich bis ich zur ersten Stornierung komme. Dann habe ich plötzlich ein FAIL bei der Prüfung.

Ausgangssituation:

Kassenbeleg (BON 48) wird erstellt und kassiert -> DEP wird geschrieben | OK!
Kassenbeleg (BON 49) wird erstellt -> DEP wird geschrieben | OK!
Kassenbeleg (BON 50) wird erstellt und kassiert -> DEP wird geschrieben | OK!
Zusteller kommt von Tour zurück und Kunde hat Bestellung nicht angenommen. Kassenbeleg (BON 49) wir storniert

Der Kassenbeleg bekommt keine neue Nummer zugewiesen sondern wird mit "BON 49" storniert. Ich nehme nun den sign-voriger-beleg aus "BON 50" zum Signieren.

Soweit läuft alles korrekt ab, jedoch bei der Prüfung bekomme ich folgende Meldung:

{
  "verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.",
  "verificationTimestamp" : "2017-02-11T20:09:15.890+01:00",
  "verificationResultList" : [ {
    "verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",
    "verificationTimestamp" : "2017-02-11T20:09:15.890+01:00",
    "verificationResultList" : [ {
      "verificationId" : "FORMAT",
      "version" : 1,
      "verificationName" : "Detailformatprüfung des maschinenlesbaren Codes",
      "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Korrektheit des Formats der Elemente des maschinenlesbaren Codes.",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-02-11T20:09:15.890+01:00",
      "verificationResultList" : [ {
        "verificationId" : "FORMAT_CHAIN_VALUE_PREVIOUS_RECEIPT_BASE64",
        "version" : 1,
        "verificationName" : "Formatprüfung: Verkettungswert",
        "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden unterschiedliche Prüfungen im Zusammenhang mit der BASE64-Kodierung (gültige Zeichen, Länge) des Verkettungswerts durchgeführt.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Die Input-Parameter sind unvollständig. Mindestens ein Parameter ist leer: {1}",
        "verificationTimestamp" : "2017-02-11T20:09:15.906+01:00"
      } ]
    } ]
  } ]
}

Ich bin mit meinen Latein am Ende. Hat vielleicht noch jemand eine Idee dazu?

Vielen Dank im Voraus.

LG

Christian

**Comment by ckvsoft** [comment]
Warum bekommt das Storno keine neue Nummer? Es ist ja ein neuer Vorgang.

**Comment by schuhlos** [comment]
Die interne ID für den Vorgang wird neu vergeben. Auf dem Rechnungsbon wird jedoch der Kassenbon mit STORNO ausgedruckt. War bisher kein Problem bei den Prüfungen. 
Kann dies ggf. das Problem sein bzgl. der Nummer?

**Comment by ckvsoft** [comment]
Ich denke schon. Es gibt ja dann zweimal die gleiche Nummer. 
Ich erstelle einen neuen Bon  (51)  auf den steht dann das es ein Storno für 49 ist.
Die Beträge sind dann minus.

**Comment by schuhlos** [comment]
Sry, mein Fehler. Der Fehler lag daran, dass ich beim Storno den Verkettungswert nicht berücksichtigt habe. Zumindest hat es auch was positives gehabt, da ich nun die Belegnummerierung auch gleich umprogrammiert habe.
