### ISSUE TITLE
Sicherung Kassa-DEP

### ISSUE THREAD

**Issue by norbert2** [a-sit-plus/at-registrierkassen-mustercode#305]
Laut meiner Information ist das DEP auf USB-Stick, externen Laufwerken oder externen Servern zu sichern.
Was ist genau unter externem Server zu verstehen?
Mein Kunde hat ein lokales Netzwerk mit einem Server und 3 Arbeitsstationen.
Der Server ist ein physischer Server im Büro.
Das Kassa-DEP wird auf ein Netzlaufwerk dieses Servers gesichert. Ist das zulässig?

**Comment by ErichFreitag** [comment]
Ich sehe einen externen Server als einen, der nicht vom Unternehmen selbst betrieben wird. Aspekte sind dazu Schutz vor unberechtigtem Zugriff, Garantie der Aufbewahrungsfrist, Datenschutz wo zutreffend, Unveränderbarkeit der Inhalte, jederzeitiger Zugriff durch befugte Personen, Entschlüsselung bei verschlüsseltem Inhalt etc.

Die Sicherung des Kassen-DEPs muss ebenso unveränderbar z.B. auf einem externen Datenträger erfolgen, genauso wie das RKSV-DEP, wo ein elektronisches externes Medium explizit vorgegeben ist. Ein von der Kasse entkoppelter Server entspricht wohl einem externen Medium in diesem Sinne. Die Anforderungen sind die selben wie bei externen Servern.

**Comment by norbert2** [comment]
Danke für Ihre prompte Stellungnahme.

Bezüglich des Begriffes der "Unveränderbarkeit" gibt es meiner Meinung nach Klärungsbedarf.
Einige Foren bzw. auch Experten verstehen unter unveränderbarer Speicherung die Speicherung auf WORM-Datenträgern. Also z.B. abgeschlossene CDs.

Die folgende Meinung - laut WKO-Seite sieht die Unveränderbarkeit mit Signierung und Verkettung als ohnehin gegeben an.

----------------------------

https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/FAQ-Arbeitskreis-Kassensoftware.pdf

Hier der Punkt 51.)
51 
_Die Unveränderbarkeit der quartalsweisen Sicherung ist bereits durch die Signaturverkettung gegeben, es sind also nicht etwa WORM-Datenträger etc. zu verwenden._

--------------------------------

Für mich ist diese Erklärung logisch. 
Wieso sollten Heerscharen von Programmieren sich mit Verschlüsselung, Verkettung und Signierung herumplagen, wenn dann die Unveränderbarkeit eigentlich eh hardwaremäßig sichergestellt werden muss?
Wir von der IT wissen, dass jedes einzelne Byte eines Files verändert werden kann. Wesentlich ist eben, dass diese Manipulation halt auch festgestellt werden kann.

Bitte nochmals Ihren Standpunkt:
Ist man mit der quartalsmäßigen Sicherung des Kassa-DEP im Json-Format auf USB-Stick oder externer Festplatte auf der sicheren Seite?

**Comment by ErichFreitag** [comment]
Ich habe oben bewusst zwischen Kassen-DEP und RKSV-DEP unterschieden.

Die Sicherung des RKSV-DEP auf einen USB-Stick oder auf eine externe Festplatte o.ä. genügt der RKSV. Das aber "nur" deshalb, weil durch die Verkettung und Signatur eine Manipulation praktisch ausgeschlossen ist.

Parallel dazu müssen sie auch das Kassen-DEP sichern. Das ist der RKSV "egal". In der Kassenrichtlinie findet sich hier jetzt wieder der Begriff "eine unveränderbare Speicherung auf einem externen Datenträger". Da dort meist keine Mechanismen gegen Unveränderbarkeit vorgesehen sind, ist etwas wie eine abgeschlossene CD wohl das bessere Medium dafür.

**Comment by AxelKutschera** [comment]
Diese Forderung der RKSV wird als "Revisionssicherheit" beschrieben. 
Diese besteht aus mehreren Teilen:
- Unveränderbarkeit - durch die Signaturverkettung
- Zeitpunkt der Sicherung - durch den Monatsbeleg/Jahresbeleg
- Verhinderung des Löschens - durch technische und organistorische Maßnahmen - Daher wird ein "abgeschlossener" Datenträger bzw. ein externer Server verlangt, den der Anwender bzw. Kassenhersteller nicht löschen kann.

Diese FAQ wurde auch im WKO/UBIT-Forum behandelt:
https://communities.wko.at/Kassensoftware/Lists/oTechnischerechtliche%20Fragestellungen%20zur%20RKSV/Flat.aspx?RootFolder=%2FKassensoftware%2FLists%2FoTechnischerechtliche%20Fragestellungen%20zur%20RKSV%2FKl%C3%A4rung%20und%20Rechtssicherheit%20bez%C3%BCglich%20der%20Durchf%C3%BChrung%20der%20DEP-Sicherungen&FolderCTID=0x01200200907C3B3FD56F92409366C063EF841033

**Comment by norbert2** [comment]
Danke zunächst für die Klarstellung Kassa-DEP und RKSV-DEP.

Also dann bezüglich RKSV-DEP:
Wenn die 3 Punkte, die Hr. Kutschera zur Revisionssicherheit aufzählt, ALLE zutreffen müssen, sehe  ich leider einen Widerspruch zur Stellungnahme von Hr. Freitag.
Genügt nun der USB-Stick für das RKSV-DEP oder nicht?

Bezüglich Kassa-DEP:
(Mehr Stellungnahme als Frage)
Wenn ich da an meinen Friseur oder meine Masseurin denke, die sich eine Kassa gekauft haben (als Kassa - kein PC) die sicher KEIN CD-Laufwerk haben, weiß ich nicht, ob dort die Sicherung des KASSEN-DEP den Richtlinien spricht. Und eine Verbindung zu einem externen Server haben die auch sicher nicht.
Die CD als solches ist meiner Meinung ja ohnehin etwas antiquiert, zumindest nicht mehr sehr gebräuchlich.

**Comment by AxelKutschera** [comment]
Für die Unveränderbarkeit reicht das, was Erich Freitag geschrieben hat.
Für den Zeitpunkt und das Löschen muss man mehr tun.

Z.B. ist durch die Verkettung der Signaturen das Löschen der letzten Belege eben nicht verhindert. Daher ist die Einhaltung der RKSV auch nicht 100%ige Garantie, dass nichts manipuliert wurde.

--> Ich bin auch der Meinung, dass es viele nicht 100% richtig machen und damit bei einer Prüfung auch keine Probleme bekommen werden. - Vielleicht will man es ja auch nicht so genau wissen... ;-)

**Comment by aunterlu** [comment]
Eine CD oder "abgeschlossener Datenträger" ist in Bezug auf Revisionssicherheit nicht besser als ein USB Laufwerk. Das Verhindern des "Löschens" kann nur durch organisatorische Maßnahmen sichergestellt werden. Jede CD kann durch eine neue CD mit verändertem Inhalt ersetzt werden und damit hat man das gleiche Result wie bei einem USB-Laufwerk. Auch sprechen die Probleme der Haltbarkeit von selbst beschriebenen CD's gegen dieses Medium.

**Comment by AxelKutschera** [comment]
Korrekt

**Comment by Phoniexk** [comment]
@AxelKutschera und @ErichFreitag haben Sie Empfehlungen für revisionssichere Speicher? Sowohl für das RKSV-DEP als auch für Kassen-DEP (Kassenjournal)? 

Soweit ich sehen kann bietet der E-Tresor von A-Trust nur die Möglichkeit das RKSV-DEP zu sichern. 
Interessant wäre auch ein lokaler "offline" Speicher.

Eigentlich müsste dann ja auch jede Registrierkasse eine direkte Schnittstelle zu einem revisionssicheren Speicher besitzen!? Wenn die Registrierkasse das Kassen-DEP (Kassenjournal) nur als File zur Verfügung stellt und dann der Unternehmer es händisch in einem revisionssicheren Speicher übergibt, dann könnte man das Kassenjournal ja auf Weg vom Export bis zum revisionssicheren Speicher ja schon wieder verändern.

**Comment by lebail** [comment]
Ich hätte eine Idee:

Wann immer man das Kassenjournal gemäß KRL exportiert, könnte man gleichzeitig einen Trainingsbeleg gemäß RKSV erstellen, der in den Betragsfeldern einen Hash über das exportierte Kassenjournal enthält.

Ein Trainingsbeleg beeinflusst den Umsatzzähler nicht, wird aber in die Signaturkette eingebunden. Auf diese Weise könnte man beliebige Daten (z.B. Exportdateien) RKSV-mäßig signieren und somit die Unversehrtheit der Daten überprüfbar machen.

Achtung: Das ist nur eine dumme Idee, bitte nicht implementieren …

**Comment by AxelKutschera** [comment]
@Phoniexk Wir haben genau für diese Anforderung das fiskaltrust Online-Backup (inkl. E-Tresor) entwickelt.
Da die Nummerierung und Summenspeicherung nicht durch die Kassensoftware gemacht wird, gewährleistet ebenfalls der fiskaltrust-Dienst auch lokal die Vollständigkeit.

Es gäbe auch noch andere dumme Ideen...

**Comment by Flanelli** [comment]
Es gäbe auch noch die dumme Idee dass sowohl kassenanwendende Unternehmer als auch kassenerzeugende Firmen vom Gesetzgeber nicht mit dem Generalverdacht einer mutwilligen Datenmanipulation von abgeschlossenen Geschäftsfällen behaftet werden ...

**Comment by norbert2** [comment]
Ich bedanke mich für die angeregte Diskussion und für die "Dummen Ideen" ;-)

Es entbehrt wohl wirklich nicht einer gewissen Ironie, dass wir wohl alle miteinander 
nicht genau wissen, wo wir das Endergebnis unserer monatelangen Bemühungen - als solches betrachte ich das RKSV-DEP und eigentlich auch das Kassa-DEP -  endlagern sollen.

Genauso könnte man es ironisch sehen, dass genau der IT die endgültige und irreversible Abbildung und Speicherung von Vorgängen der realen Welt anheim stellt.

Allerdings bin ich auch zuversichtlich, dass sich früher oder später "best practice"-Abläufe herausstellen werden und Abweichungen bis dorthin nicht sofort mit Zuchthaus bestraft werden.
Unsere Sonntage können wir dann wieder mit Erfreulicherem verbringen.

**Comment by AxelKutschera** [comment]
Danke für die Anregung und die Vorfreude auf Freizeit. :-)

**Comment by MichaelSchustereder** [comment]
Wenn ein USB-Stick laut RKSV ein geeignetes Medium zum Sichern ist, dann ist ein Netzlaufwerk am Server allemal auch ein geeignetes Medium - zumindest meine Meinung. 

Beide sind "vor unberechtigten Datenzugriffen zu schützten". Folgende Fragen stelle ich mir dazu:
1. Wer ist der "Berechtigte"? Beim USB-Stick muss ich davon ausgehen, dass der Unternehmer selbst schon mal berechtigt ist ;-)
2. Wie kann der USB-Stick vor unberechtigten Zugriff geschützt werden?

**Comment by Phoniexk** [comment]
In der RKSV steht nirgends dass ein USB-Stick geeignet ist. 

Im Erlass wird folgendes festgehalten:

> Als geeignete Medien gelten beispielsweise schreibgeschützte (abgeschlossene) externe Festplatten, USB-Sticks und Speicher externer Server, die vor unberechtigten Datenzugriffen geschützt sind.

Dementsprechend ist ein simpler USB-Stick - ohne weitere Maßnahmen - nicht geeignet.

**Comment by ErichFreitag** [comment]
Für die RKSV ist das ohnedies mit "schreibgeschützte (abgeschlossene) externe Festplatten, USB-Sticks und Speicher externer Server" klargestellt.

Ein Schutz gegen unberechtigte Zugriffe kann z.B. ein Verschluss des USB-Sticks in einem Hardware-Tresor sein. Oder eine Verschlüsselung der Daten. Oder ein externer Server mit entsprechender Zugriffsverwaltung und -überwachung. Oder - siehe oben - ein E-Tresor. Oder ...

**Comment by Flanelli** [comment]
Letztendlich bleibt das Thema "akademisch" denn 90% der Kleinfirmen die gerade mal knapp über der Grenze der Reg-Kassenpflicht liegen werden sich die Kosten einer, zumindest theoretisch wirklich "wasserdichten" Speicherung der Daten schlicht und einfach nicht leisten können.

**Comment by argetherapie** [comment]
Ich denke es reicht wenn sich die (vor allem kleinen) Unternehmer revisionsichere USB-Sticks zulegen. Die sind auch einfach und verläßlich hand zu haben. Damit lässt sich eigentlich die BAO erfüllen. Und das nicht nur bezüglich des RKSV.
https://www.ecosia.org/search?q=revisionssicher+usb+speicher

**Comment by lebail** [comment]
@argetherapie: Danke für den Hinweis! Nach sowas habe ich bereits gelegentlich gesucht - und war bisher nicht fündig geworden. Übermäßig viele Anbieter scheint es da ja nicht zu geben.

Das Konzept des einzigen aufgefundenen Produktes (S***MEM) gefällt mir ja recht gut (Unveränderbarkeit einmal geschriebener Dateien, eingebaute Echtzeituhr, automatisch erstellte Journaldatei für alle Aktivitäten, dennoch Kompatibilität mit normalen USB-Sticks, kein Treiber erforderlich).

Allerdings dürfte das teurer kommen als diverse Online-Lösungen. Denn der Stick lässt sich (ab der ersten Benutzung) nur 15 Monate lang beschreiben (dann sperrt er sich gegen Schreibzugriffe), kann vor der ersten Benutzung maximal 2 Jahre gelagert werden und kostet 79 € (exkl. USt.) + 19,90 € Versandkosten.

Auch mit anderen Suchbegriffen (z.B. write-once USB stick) konnte ich keine weiteren Produkte finden, nur Fragen, ob es sowas denn gäbe.

**Comment by Flanelli** [comment]
Revisionssichere USB-Sticks sind für Kleinstunternehmer ebenfalls aus Kostengründen undenkbar.

**Comment by Alex1130** [comment]
Laut meiner Ansicht müsste folgendes als revisionssicher gelten:
https://en.wikipedia.org/wiki/Trusted_timestamping

**Comment by MichaelSchustereder** [comment]
Nachdem, die Unveränderbarkeit des Inhaltes der Daten durch die Signatur und insbesondere durch die
signierten Monatsbelege gegeben ist (laut RKSV oder Erlass), stelle ich mir die Frage, warum ein revisionssicherer USB-Stick notwendig ist?

Das Einzige dass damit der revisionssichere USB-Stick abdeckt, ist, dass ich die Sicherung nicht gelöscht werden kann (außer ich übersehe hier etwas). Das Löschen der Daten am USB-Stick kann man mit dem Verlust des USB-Sticks gleichsetzen - somit stelle ich die Notwendigkeit infrage, dies technisch lösen zu müssen.

Auch bei der angesprochenen Verwahrung des USB-Sticks in einem Hardware-Tresor hat dennoch zum Zeitpunkt der Sicherung, der Anwender Zugriff auf den USB-Stick. Somit ist aus meiner Sicht, der Anwender/Unternehmer, berechtigt zum Zugriff. 
Und den Zugriff kann ich auch auf einem Verzeichnis am Server, mit entsrechender Berechtigungsstruktur, sicherstellen.

**Comment by argetherapie** [comment]
@lebail: FILER*X, ab 17,99 bei 8GB; und von Zeitbegrenzungen lese und weiß ich auch nichts...

**Comment by ErichFreitag** [comment]
Die Unveränderbarkeit ist schon durch den Monatsbeleg gegeben, aber man könnte ja z.B. das letzte Monat löschen, ohne das es unmittelbar auffällt.

USB-Sticks werden eher bei Unternehmen, die eine Kasse betreiben zum Einsatz kommen. Server bei Unternehmen mit entsprechenden Strukturen.

Am Ende wird herauskommen: hat sich der Kassenbetreiber etwas überlegt, wie er den Anforderungen in seiner Situation bestmöglich nachkommen kann.

**Comment by lebail** [comment]
@argetherapie: Danke.

Leider funktioniert der nur unter Windows; und dadurch, dass er keine herstellerseitig gestellte Uhr eingebaut hat, wird er wohl auch nicht viel Beweiskraft haben (man könnte ja alles - inkl. Manipulationen - auf einen neuen Stick schreiben und den alten verschwinden lassen …)

**Comment by cmaxmedia** [comment]
Bin mir jetzt nicht mehr ganz sicher, ob ich jetzt nicht doch einen Uplink zur nächsten Atomuhr für die RKSV brauche. Ist es korrekt, wenn ich den Kunden den folgenden Workflow empfehle:
- USB Stick bei M**markt kaufen 
- DEP + Beleg jeder Monat/Quartal/Jahr auf Stick sichern (geht automatisch bei mir)
- Stick in den Tresor oder fern vom Standort sicher ablegen 
- Bei erneuter Sicherung hervorholen, sichern und wieder ablegen

**Comment by argetherapie** [comment]
@Flanelli: "Kostengründe" gibts mehrere, denk ich. Einmal gewiss die Euros, dann jedoch auch die Praktikabilität. Eine Datei (oder ein Ordner, den die Regkasse dem Anwender vor die Nase hält) alle 4 Monate auf einen Stick zu kopieren, sollte einigermaßen KISS sein.
Und übrigens: nicht jede RegKasse ist online oder in einem Servernetz ...

@lebail: Revisionssichere USB-Sticks: Der Anwender kann nichts überschreiben >> Es entsteht eine **History** der Backups. Ich kann nicht unbemerkt "rückdatieren", indem ich alte Daten auf einen neuen "Ersatz" schreibe. Der Prüfer kann frühere Zustände sehen und prüfen.
( ;-) Eine wirklich dumme Idee wäre jetzt, von Anfang einen ganzen Fächer solcher Sticks parallel zu beschreiben, um eine Auswahl bei der Manipulation zu haben... )

Das alles ist allerdings mit der RKSV nicht neu, sondern - wie @AxelKutschera zurecht erwähnt - ALLGEMEIN ein Frage der Ordnungsmäßigkeit der IT-Buchführung, wozu nun mal das DEP gehört.
www.kwt.or.at/PortalData/1/Resources/fachgutachten/52-KFS-DV1.pdf; Kap 3.8 und 3.9:
"Bei  der  Verwendung  von  IT-Buchführungen  ist  zu  berücksichtigen,  dass  die 
**Unveränderbarkeit und die Nachvollziehbarkeit allfälliger Änderungen** nicht nur auf 
Ebene  der  IT-Anwendung,  sondern  auch  auf  anderen  Ebenen  (z.B.  Datenbank) 
sicherzustellen  sind.  Rein  mit  technischen  Mitteln  ist  das  Kriterium  der 
Unveränderbarkeit typischerweise nicht umzusetzen, daher bedarf es in der Regel 
zusätzlicher organisatorischer Maßnahmen."
Sprich: Die Kassenhersteller können technische Hilfe/Brücken anbieten - den entscheidenden Rest muss der Unternehmer organisieren. (außer jemand kauft Komplettlösungen)

**Comment by Alex1130** [comment]
@cmaxmedia 

> Bin mir jetzt nicht mehr ganz sicher, ob ich jetzt nicht doch einen Uplink zur nächsten Atomuhr für die RKSV brauche.

Nicht für das RKSV-DEP aber u.U. für das Kassen-DEP (das aber ohnedies schon seit 2013)

**Comment by Flanelli** [comment]
@cmaxmedia 
Ich empfehle den Kunden im Prinzip etwas ähnliches wie ihre Überlegungen,
1) Laden sie ihren Anwalt an umd an zum Grillfest ein - möglicherweise wird er dann pekuniär milde 
   agieren wobei solche Einladungen generell nicht ungünstig zu bertrachten sind ::-) 
2) USB Stick beim Billigstanbieter kaufen
3) DEP + Komplettsicherung jedes Monat, Quartal und Jahr auf Stick sichern
4) Beim Anwalt ( dem milde gestimmten ) abgeben und optimalerweise nach Kopieren der Daten
    den Stick wieder mitnehmen.

Bzgl. der Selbstzerstörung von Belegen habe ich irgendwo in den Tiefen der behördlichen Bestimmungsorgien einmal gelesen dass der Unternehmer dafür zu sorgen hat dass solche Belege ( falls keine elektronische Belegsammlung existiert ) dauerhaft lesbar aufzubewahren wären womit man also entweder Spezialdrucker samt entsprechendem Papier einsetzen oder die Belege fein säuberlich kopieren müßte. ( Am besten auch gleich beim Anwalt deponieren bevor jemand noch auf die Idee käme man würde auch die Belege nachträglich manipulativ erstellen )

Sorry, aber langsam entwickelt sich das Thema zum ...

**Comment by AxelKutschera** [comment]
Wenn Internet vorhanden ist, dann wird wohl ein revisionssicherer Speicher um EUR 4,- pro Jahr günstiger sein als das technische und organisatorischen Handling einer manuellen Sicherung.
Zudem wird das Cloud-Upload meist zeitnah und nicht nur vierteljährlich gemacht.

**Comment by norbert2** [comment]
E-Tresor und Cloud gut und schön.
Wie wir wissen kann alles gehackt werden. So kann - wie Ihre Beiträge beweisen - JEDES Medium zerpflückt werden. 
Hätte ich gewusst, dass es ein derartiges Streitthema ist und ein USB-Stick oder externe Festplatte überhaupt angezweifelt werden können, hätte ich meinen Kunden von vornherein gesagt, dass ich diese RKSV NICHT umsetzen kann und will. Weil eben völlig UNPRAKTIKABEL.
Allerdings glaube ich auch, dass da doch die Pferde mit uns Technikern durchgehen ....

Weil wir schon beim Philosophieren sind:
Gibt es nicht andere Geschäftsbereiche und Buchhaltungen, sowohl in der Wirtschaft aber natürlich auch genauso von staatlichen Stellen, die einer MANIPULATIONSSICHEREN Speicherung nicht viel mehr bedürften?  Wieso meinen Friseur quälen und nicht die Buchhaltungen der Stadt Salzburg oder Linz?
Stichwort Spekulation und  SWAP-Geschäfte.

**Comment by ErichFreitag** [comment]
Salzburg war doch lange Zeit sicher gegen Revision? :-)

Ich versuche, das Thema abzuschließen: es ist nicht verlangt, alles technisch mögliche und unmögliche zu tun. Die DEPs gehören gesichert und zwar so, dass nach - ich nenne es mal - Maßgabe aller Möglichkeiten keine Veränderungen und Manipulationen stattfinden können. Das ist ja auch mit der RKSV kein unbedingt neues Thema. 

Also bestmöglich, in Kombination mit technischen und organisatorischen Maßnahmen. Dazu gibt es in dieser Diskussion jetzt genug vernünftige Ansätze.

**Comment by norbert2** [comment]
So sehe ich das auch.
