### ISSUE TITLE
Wiederinbetriebnahme einer Kassa

### ISSUE THREAD

**Issue by xandi1987** [a-sit-plus/at-registrierkassen-mustercode#306]
Hallo,

ich betrachte derzeit folgendes Szenario:

1. Die Registrierkasse wird mit einem Schlussbeleg "geschlossen" und außer Betrieb genommen (siehe "Planmäßigen Außerbetriebnahme der Registrierkasse). Grund dafür könnte die Unterschreitung der Anforderungen für den Betrieb einer Registrierkasse sein. 
2. Das System wird weiterhin für die Belegserteilungspflich verwendet, jedoch ohne Signatur. 
3. Später werden jedoch die Anforderungen überschritten und die Pflicht tritt wieder in Kraft

Die grundlegenden Fragen:

- Macht dieses Szenario überhaupt Sinn? 
- Darf man dann das selbe Zertifikat verwenden? 
- Wie sieht der Export dafür aus? Man würde 2 Startbelege auffinden.

**Comment by ErichFreitag** [comment]
Das Szenario macht nur dann Sinn, wenn die Registrierkasse mit RKSV zu diesem Zeitpunkt mit Sicherheit nicht mehr benötigt wird. Eine Außerbetriebnahme ist ein sehr bewusster Akt und beendet die RKSV-Lebenszeit dieser Kasse unwiderruflich.

Im Zuge der Außerbetriebnahme müssen sie insbesondere auch das DEP sichern.

Bei einer Wiederinbetriebnahme machen sie das wie bei einer Neuinbetriebnahme - also Startbeleg und DEP einrichten und neu registrieren. Damit gibt es nur einen Startbeleg pro DEP. Ich empfehle dabei auch die Kassen-ID zu ändern, um die DEP-Sicherungen (das alte und das neue) sauber trennen zu können.

Das Zertifikat dürfen sie weiterhin verwenden, das ist ja an das Unternehmen gebunden.

**Comment by xandi1987** [comment]
Danke für die Antwort.
