### ISSUE TITLE
Kassen-ID

### ISSUE THREAD

**Issue by ct-graz** [a-sit-plus/at-registrierkassen-mustercode#307]
Gibt es gar keine Beschränkungen bei der Kassen-ID?
Sie steht ja auf jedem Beleg.
Was ist mit anstößigen Begriffen usw?
Da könnte ja jeder seinen Unmut über die RKSV ausdrücken.
Spätestens beim Scannen ist das lesbar.

**Comment by lebail** [comment]
Naja, sie sollte "möglichst kurz" sein (Erlass, Punkt 3.2.3) und aus naheliegenden Gründen keinen Unterstrich enthalten (auch wenn letzteres nirgendwo ausdrücklich steht). Ansonsten ist jeder UTF8-String erlaubt.

Unmut ausdrücken kann man wohl auch außerhalb der Kassen-ID. Schließlich hindert einen keiner daran, beliebigen Klartext auf den Beleg zu schreiben …

**Comment by ct-graz** [comment]
Ja schon, z.B. das Verbotsgesetz. Was, wenn jemand eine ID verwendet, die als Autonummer klar verboten ist, wie HEIL8?

**Comment by AxelKutschera** [comment]
Achtung - die KA-ID muss nach § 11 Abs 1 RKSV immer am Beleg ausgewiesen werden!

**Comment by Alex1130** [comment]
Spannend, ich habe es bisher so ausgelegt, dass Kassen ID ohnedies implizit im maschinenlesbaren Code angeführt ist. Danke @AxelKutschera für den Hinweis.
