### ISSUE TITLE
Finanzonline error

### ISSUE THREAD

**Issue by blhasan** [a-sit-plus/at-registrierkassen-mustercode#308]
Hi
Ich versuche eine Start beleg signieren.

AES: y+01xKWMYlRq+LEN4TJEGaSC+NNqADs0BrNbc6xQh+0=

belegzeile : 
`_R1-AT1_1_0_2017-02-13T16:53:17_0,00_0,00_0,00_0,00_0,00_CfpgJ86dB/o=_9DFEFC4_a4ayc/80/OE=`

bekomme ich folgende JWS
`{"result":"eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8xXzBfMjAxNy0wMi0xM1QxNjo1NDo1OF8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfQ2ZwZ0o4NmRCL289XzlERkVGQzRfYTRheWMvODAvT0U9.gfnvfVRPtUYBENGjV6qWq5kggPnJiYND8vW2m1dcgSu7o6UJXXzJBQ9axlvk9AnBzTrkJMnuv22VlCysOTqBGw"}`

QR-Code:
`_R1-AT1_1_0_2017-02-13T16:53:17_0,00_0,00_0,00_0,00_0,00_CfpgJ86dB/o=_9DFEFC4_a4ayc/80/OE=_gfnvfVRPtUYBENGjV6qWq5kggPnJiYND8vW2m1dcgSu7o6UJXXzJBQ9axlvk9AnBzTrkJMnuv22VlCysOTqBGw==`

Bekomme aber im finanzonline folgende Fehler:

`<?xml version='1.0' encoding='UTF-8'?>
<verificationResultList>
  <verificationResult>
    <verificationId>VERIFICATION_FROM_CASHBOX</verificationId>
    <version>1</version>
    <verificationName>Prüfergebnis - Kasse</verificationName>
    <verificationTextualDescription>Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.</verificationTextualDescription>
    <verificationState>FAIL</verificationState>
    <verificationResultDetailedMessage>Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.</verificationResultDetailedMessage>
    <verificationTimestamp>2017-02-13T16:56:37.901+01:00</verificationTimestamp>
    <verificationResultList>
      <verificationResult>
        <verificationId>RECEIPT_FULL</verificationId>
        <version>1</version>
        <verificationName>Detailprüfung des maschinenlesbaren Codes</verificationName>
        <verificationTextualDescription>Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.</verificationTextualDescription>
        <verificationState>FAIL</verificationState>
        <verificationTimestamp>2017-02-13T16:56:38.327+01:00</verificationTimestamp>
        <verificationResultList>
          <verificationResult>
            <verificationId>CRYPTO</verificationId>
            <version>1</version>
            <verificationName>Kryptographische Prüfungen</verificationName>
            <verificationTextualDescription>In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).</verificationTextualDescription>
            <verificationState>FAIL</verificationState>
            <verificationTimestamp>2017-02-13T16:56:38.330+01:00</verificationTimestamp>
            <verificationResultList>
              <verificationResult>
                <verificationId>CRYPTO_SIGNATURE</verificationId>
                <version>1</version>
                <verificationName>Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur</verificationName>
                <verificationTextualDescription>In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-13T16:56:38.330+01:00</verificationTimestamp>
              </verificationResult>
            </verificationResultList>
          </verificationResult>
        </verificationResultList>
      </verificationResult>
    </verificationResultList>
  </verificationResult>
</verificationResultList>

`

**Comment by areiter** [comment]
Können sie den gesamten Cryptographic Material Container posten bzw. das Zertifikat

**Comment by asitplus-pteufl** [comment]
Bevor Sie in FinOnline Belege hochladen, bitte unbedingt Ihre Implementierung mit dem Prüftool überprüfen.
