### ISSUE TITLE
WIKI korrigieren: Brutto statt Netto

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#31]
Derzeit in WIKI:
**Handelt es sich um Netto/Brutto-Werte im Umsatzzähler bzw. bei den einzelnen Steuersätzen?**
Es werde sowohl im Umsatzzähler als auch bei den einzelnen Steuersätzen die im maschinenlesbaren Code und im DEP-Export-Format enthalten sind, **Netto**-Beträge verwendet.

**Richtig (Klarstellung durch BMF)**
Quelle: E-Mail von Mag. Elisabeth Klinger, 
Von: <ubit@wko.at>
Datum: 10. Februar 2016 um 13:45
Betreff: Klarstellungen im Bereich Brutto/Netto, 0% und Umsatzzähler

 Bei der Aufteilung der Barzahlung gemäß §§ 9 Abs. 2 Z 4, 10 Abs. 2 Z 4 und 11 Abs. 1 Z 3 RKSV sind beim jeweiligen Steuersatz immer **Bruttobeträge** (Betrag inkl. USt.) anzugeben.

·         Dem Satz-Null sind Bruttobeträge zuzuordnen, die entweder von der USt. befreit sind, beim Unternehmer nicht, nicht zur Gänze bzw. mit einem anderen % als den % des Signaturformates (derzeit 20% für Satz-Normal, 10% für Satz-Ermaessigt-1, 13% für Satz-Ermaessigt-2 und 19% für Satz-Besonders) der USt. unterliegen oder deren USt. auf Grund anderer Unterlagen geschuldet wird. Darunter fallen beispielsweise Beträge, die im Namen und auf Rechnung dritter vereinnahmt werden (durchlaufende Posten), nicht zur Gänze besteuert sind (Differenzzahlungen) oder auf eine Rechnung verweisen.

·         Sämtliche Beträge in Belegen, die Barzahlungen darstellen oder mit zumindest einer Barzahlung kombiniert sind, sind als **Bruttobeträge **(inkl. USt.) zu signieren und in den Umsatzzähler aufzunehmen. Dies gilt auch für Stornobuchungen, nicht jedoch für Trainingsbuchungen. Eine freiwillige Signierung von Beträgen aus Belegen ohne Signierungspflicht (z.B.: Belege ohne Barzahlungen) mit Aufnahme in den Umsatzzähler ist immer möglich. Der Umsatzzähler ist als Summenzähler Teil der Sicherheitseinrichtung einer Registrierkasse und für Umsatzanalysen nur in Verbindung mit den weiteren, in der Registrierkasse aufgezeichneten Daten vorgesehen.

**Comment by pteufl** [comment]
Danke, Sie sind mir zuvor gekommen. Die Info ist jetzt auf der Startseite. Die BSP im Mustercode und die Einträge im Wiki werden in der nächsten Version aktualisiert.
