### ISSUE TITLE
Frage bezüglich des Json Files mit den Signaturdaten zur Verwendung des Prüftools

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#311]
Guten Tag,
ich bin jetzt mit der RKSV Implementierung soweit fertig dass ich das Prüftool mit einem exportierten DEP laufen lassen möchte.
Dazu habe ich noch bitte ein Frage bezüglich des Json Files in welchem die Signaturdaten für das Prüftool abgelegt werden müssen:
{
  "base64AESKey" : "AES Passwort eingeben",
  "certificateOrPublicKeyMap" : {
    "Zertifikat-HEX eingeben" : {
      "id" : "Zertifikat-HEX eingeben",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : "Zertifikat-SN eingeben"
    }
  }
}

AES Passwort eingeben:
Damit ist der aes KEY gemeint ? (AES Passwort ist für mich etwas verwirrend)

Zertifikat-HEX eingeben :
Ist damit das Public Zertifikat gemeint das ich aus der Karte auslese ?
z.B.: MIIFsDCCA5igAwIBAgINASo0/WflfWvLWNGxVjANBgkqhkiG9w0BAQsFADB7MQswCQYDVQQGEwJBVDENMAsGA1UECBMEV2llbjENMAsGA1UEBxMEV2llbjEjMCEGA1UEChMaZS1jb21tZXJjZSBtb25pdG9yaW5nIEdtYkgxKTAnBgNVBAMTIEdMT0JBTFRSVVNUIFJLUy1DQ..... usw ...

Vielen Dank für die Hilfe.

**Comment by smtm** [comment]
Hier ein Beispiel (Daten leicht verändert) mit der es bei mir funktioniert:

  * 18E28C09 kommt von A-TRUST HEX Nummer des Certs
  * base64AESKey: Wird selbst vergeben - hab's hier mal aus den Beispielen kopiert.
  * MIIFHDCCAw... kommt auch von A-Trust

```
{
    "base64AESKey": "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=",
    "certificateOrPublicKeyMap": {
        "18529C07": {
            "id": "18E28C09",
            "signatureCertificateOrPublicKey": "MIIFHDCCAwSgAwIBAgIEGFKcBzANBgkqhkiG9w0BAQsFADCBoTELMA1UEBhMCJEWQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDIxMDEzMzg1N1oXDTIyMDIxMDEzMzg1N1owPjELMAkGA1UEBhMCQVQxGDAWBgNVBAMMD1VJRCBBVFUxMjM0NTY3ODEVMBMGA1UEBRMMMjA5NTA0NTI0NTM2MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1sUnjI5xwc+1AZpC9qPVI68RTDS8YbcqDropmmxYVaoPqcUWDqxT6yiuK3m1D5vkGz2i051kNHAXLQ8KMWqXfqOCAYcwggGDMH8GCCsGAQUFBwEBBHMwcTBGBggrBgEFBQcwAoY6aHR0cDovL3d3dy5hLXRydXN0LmF0L2NlcnRzL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlLUNBLmNlcjAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQEAwIGwDARBgNVHQ4ECgQIR4zanImggzQwRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybC5hLXRydXN0LmF0L2NybC9BLVRydXN0LVJlZ2lzdHJpZXJrYXNzZS5DQTAJBgNVHRMEAjAAMFgGA1UdIARRME8wTQYGKigAEQEYMEMwQQYIKwYBBQUHAgEWNWh0dHA6Ly93d3cuYS10cnVzdC5hdC9kb2NzL2NwL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlMBMGA1UdIwQMMAqACEBHnq7jkN+2MBwGByooAAoBCwEEEQwPVUlEIEFUVTEyMzQ1Njc4MA0GCSqGSIb3DQEBCwUAA4ICAQCKmKOoHQ2dVB1AYlJotApPiXJQDsgB4TX2zmqkESl4SJOrcI5Z0ImF0QYGzhgn/1jtxHipm1he+XILOdhSzalhjjIznSlXPuYoghlCTEkm8WRToJfkHL3/sTBVxdICx9wnQJvitR8xErTJOms6FscWsVs/dvikE3PXFu+PnxCGMOZ/nL6ebr4t7/u+r9V5D6pYTeysCL4cPrIQqkdh2XN4+XK3jtQ9mqfbB21Bj0A4RnNb3mxvNdO3PAab3AA7X5Hj7v1m6cjRmykhY2Tp7468AemcKdQY/76EpLSVPVUY49JKNdZwoNBh4GZ5aNYGTE+WUg4q4GfVlIN9ICrlziN17rODip9jRgP5utahGKsZAMnU0VKnef0h7o1PA7lOsc67fHXpNrauyU2REXCk/Uc7QmLXQ3friTxiEn/xKD+Xx/6RU09fGrx/Jdqeham6H2GJ7gOMb8LKDR7j2RqMZQnH+LZRm5Vay2q09KuTREPjFaMrrDgkxzzwNW8IvBpSC8OyPm9Bpu3SuEzmfRFaXx7Lk83yLS4Gic4pG7QsXB30gMXG0VutdWwijPTCT93o8WNps/MNCm4vYkdTAr2akrHUmWX9IjdoDXKPYB1OT5BXgOnkfihao/5G7XzQaT48mT0Ldgj3G25t7Oy5QrD9HR6wFh8uQp8dxHITanGVg3DfyQ==",
            "signatureDeviceType": "CERTIFICATE"
        }
    }
}
```

Liebe Grüße 
Roland

**Comment by Skerge12** [comment]
Vielen Dank für die Info :)
