### ISSUE TITLE
APDU Chain- oder Issuer-Zertifikat auslesen

### ISSUE THREAD

**Issue by Philipp1968** [a-sit-plus/at-registrierkassen-mustercode#314]
In den APDU Beispielen wird nur das Signatur-Zertifikat ausgelesen, bzw. verwendet.

Für den Datenexport von Belegen wird aber auch das Aussteller-Zertifikat, bzw. in manchen Quelltexten als Chain-Certificate bezeichnet, benötigt. Auch das RK-DLL liefert mit der Funktion LoadInfo() von der gesteckten Karte beide Zertifikate.

Wie kann ich das Aussteller-Zertifikat mit APDU auslesen? Für z.B. die A-Trust AT1-Karten?

In den Beispiel-Programmen gibt es zwei Kartentypen, die mit

public override X509Certificate2 readCertificate()
{
   return getCertificate(DF_SIG, EF_C_CH_DS);
}

das Zertifikat lesen.

Abhängig vom Kartentyp sind die Byte-Arrays

byte[] DF_SIG = new byte[] { 0xDF, 0x70 };
byte[] EF_C_CH_DS = new byte[] { 0xc0, 0x02 };

oder

byte[] DF_SIG = new byte[] { 0xDF, 0x01 };
byte[] EF_C_CH_DS = new byte[] { 0xc0, 0x00 };

Wie müssen die Definitionen bzw. Byte-Arrays für das Auslesen des Aussteller-Zertifikats aussehen?

Ich habe leider auch in den Mocca-Projektsourcen keine Entsprechung gefunden, und auch mit den international verfügbaren Informationen zu PKCS und ACOS leider keinen Erfolg gehabt.

Danke!

**Comment by lebail** [comment]
Ich konnte das bis jetzt auch nicht herausfinden, und es würde mich ebenfalls interessieren.

Auch in der A-Trust-Dokumentation zur Karte (die ist als PDF in den "APDU-Registrierkassenbeispielen" auf http://labs.a-trust.at/developer/ShowSource.aspx?id=114 enthalten) steht nichts dazu.

Ich tröste mich momentan damit, dass das Ausstellerzertifikat im DEP-Export ohnehin optional ist - man muss es also nicht hineinschreiben.

**Comment by asitplus-pteufl** [comment]
Lassen Sie die Zertifikat im DEP-Export weg, diese wurden explizit in mehreren Darstellungen als optional definiert.
