### ISSUE TITLE
 Testaccount für Webservice 

### ISSUE THREAD

**Issue by jayarm** [a-sit-plus/at-registrierkassen-mustercode#315]
Hallo,

ich möchte den Webservice (https://finanzonline.bmf.gv.at/fonws/ws/sessionService.wsdl) nutzen, aber leider habe ich nirgendwo herausfinden können, ob es einen Testaccount zum anmelden an Finanzonline gibt. 
Habe ich etwas überlesen oder wie habt ihr das gemacht?

Danke im voraus 
Joe

**Comment by MichaelSchustereder** [comment]
Wir haben unsere eigene Firmenanmeldung verwendet.

**Comment by jayarm** [comment]
Danke für die Antwort. 
Aber wir kommen aus Deutschland und somit kann man meines Wissens keinen Account beantragen, richtig?

**Comment by MichaelSchustereder** [comment]
In dem Issue #115 wurde die Frage bereits behandelt.
