### ISSUE TITLE
Sammelbeleg nach "Sicherheitseinrichtung ausgefallen" im Fall von z.B. a.sign RK MOBILE

### ISSUE THREAD

**Issue by FischC** [a-sit-plus/at-registrierkassen-mustercode#316]
Guten Abend!

Sollte es im Zusammenhang mit a.sign RK MOBILE zu einem Übertragungsfehler kommen, dann signieren wir die betroffene Rechung mit "Sicherheitseinrichtung ausgefallen" (entsprechend 3.2)!. Da dies jedoch kein permanenter Fehler ist, ist es sehr wahrscheinlich, dass der nächste Aufruf erfolgreich möglich ist.

Ist es in diesem Fall zwingend notwendig eine Sammelrechnung/NULLBON zu erstellen oder reicht es einfach die nächste Rechung zu signieren?

Wenn ja wie ist folgender Paragraph § 17(4) im Fall (von vereinzelten/kurzfristigen Ausfällen) auszulegen:
Nach Wiederinbetriebnahme der Signatur- bzw. Siegelerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern.

mfg & danke
FischC

**Comment by AxelKutschera** [comment]
Ja, ("Sammelrechnung" --> "Sammelbeleg")

Auch wenn bei einem einzelnen Beleg die SEE ausgefallen ist, muss ein Sammelbeleg erstellt werden.

Bei einem nicht nur vorübergehenden Ausfall (> 48 Stunden) ist zusätzlich die Meldung über den Ausfall (und danach über die Wiederinbetriebnahme) innerhalb einer Woche per FinanzOnline zu machen.

Zusatz: Wenn die SEE (oder auch die ganze RegK) ausgefallen ist, muss eine andere RegK verwendet werden. Nur wenn keine zweite RegK vorhanden ist, darf die RegK weiter arbeiten und ist das Szenario mit Sammelbeleg  abzuschließen.

**Comment by FischC** [comment]
Danke für die rasche Antwort!

D.h. in der Realität wird nach jedem einmaligem "Ausfall"  einfach so lange zusätzliche ein Nullbeleg generiert (da es nur diese eine Kasse gibt), sobald dieser erfolgreich signiert wurde, wird zum Normalbetrieb übergegangen und kein zusätzlicher Nullbeleg generiert ...

Oder verstehen wir hier prinzipiell etwas falsch an der Definition des Sammelbelegs?

mfg & danke

**Comment by lebail** [comment]
Sie brauchen pro Ausfall nur _einen_ Nullbeleg, wobei dieser wahlweise vor oder nach dem ersten wieder erfolgreich signierten Normalbeleg erstellt werden darf. Die Variante "danach" dürfte einfacher zu realisieren sein.
