### ISSUE TITLE
Wie viele Signaturerstellungseinheiten pro Kasse mit Moblen Zertifikat

### ISSUE THREAD

**Issue by smtm** [a-sit-plus/at-registrierkassen-mustercode#318]
Im Dokument 2016-09-05-Detailfragen-RKSV-V1.2.pdf Punkt 1.2 Relationen wird von einem 1:n Zustand von Kassa zu Signaturerstellungseinheiten gesprochen. Wenn wir das Mobile Zertifikat von A-Trust verwenden gibt es da Szenarien wo wir (gleichzeitig) mehr als ein Zertifikat ansprechen. Also wir gehen mit den API Calls auf https://www.a-trust.at/asignrkonline/v2 und nutzen diese um die JWS Signatur zu erstellen. Somit stellt das Zertifikat, das wir mit User und Passwort ansprechen die Signaturerstellungseinheit dar.

Oder ist das ganze im Lifecycle der Kasse zu sehen: da in sagen wir mal 2-3 Jahren evtl. ein anderes Zertifikat zur Anwendung kommen könnte und da wäre es schon gut die Referenz auf das Zertifikat zu haben die die Belege aus der Anfangsphase signiert haben?

**Comment by ErichFreitag** [comment]
Das ist egal, mit welchem und wie vielen Zertifikaten sie signieren - einzige Voraussetzung ist, dass die Zertifikate dem Unternehmen zugeordnet sind.

**Comment by smtm** [comment]
Mir geht es um die Datenmodellierung: Wir haben einfache Betriebe: eine Kasse = ein Unternehmen. Sollte ich diese 1:n Relation (Kasse zu Signatureinheit)  aufbauen oder ist das ein overkill für diese Betriebsgstruktur? Oder übersehe ich hier einen Aspekt?

**Comment by ErichFreitag** [comment]
Das brauchen sie nicht, weil es egal ist, mit welchem zugeordnetem Zertifikat sie signieren.

**Comment by Phoniexk** [comment]
Sowie im Dokument beschrieben wird, gibt es einen Pool aus Registrierkassen und einen Pool aus Zertifikaten. Wichtig ist dass die Zertifikate dem Unternehmen zugeordnet sind und nicht einer Registrierkasse.

Sie können eine Kasse mit 3 Zertifikaten betreiben oder auch 3 Kassen mit einem Zertifikat. Die Zertifikate sind nicht fix mit einer Registrierkasse verbunden.

In Ihrem Modell könnten z.B. die Anmeldedaten für RK-Online verloren gehen, das Zertifikat ablaufen, etc. also Sie sollten damit planen, dass irgendwann ein neues Zertifikat benötigt wird.

**Comment by Phoniexk** [comment]
> Oder ist das ganze im Lifecycle der Kasse zu sehen: da in sagen wir mal 2-3 Jahren evtl. ein anderes Zertifikat zur Anwendung kommen könnte und da wäre es schon gut die Referenz auf das Zertifikat zu haben die die Belege aus der Anfangsphase signiert haben?

Sie müssen auf jeden Fall darauf achten, dass das DEP auch weiterhin korrket exportiert werden kann. Falls Sie für den Export/Sicherung - aus welchen Gründen auch immer - eine Referenz auf alte Zertifikatsdaten benötigen, dann sollten diese auch später noch zur Verfgügung stehen.

**Comment by smtm** [comment]
Ich denke im machine readable code stellt **185459C07** die Referenz auf das Zertifikat dar und R1-AT1 deutet darauf hin dass es ein A-Trust Zertifikat ist.

_R1-AT1_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-6_2017-02-15T17:25:55_60,00_40,00_400,00_5,01_0,00_k8wUAFWM_185459C07_bjaX1nv9BtM

Aber Sie haben recht wenn User/Passwort bei RK Online nicht mehr zusammen passen dann können ab dann keine Belege mehr signiert werden. Ein neues Zertifikat müsste gelöst werden und eingetragen werden. Die Public Key Daten sind ja ohnehin mit der HEX Nummer des Certs abrufbar. 
Das Prüfprogramm braucht offensichtlich auch nicht die Public Key Daten (Habe das Programm mal ohne Netz laufen lassen - ging auch)

**Comment by Phoniexk** [comment]
Ja natürlich über den maschinenlesbaren Code hat man im RKSV-DEP eine Referenz. Ich meinte damit aber nicht nur den RKSV-Export, sondern auch den zweiten Export ohne Strukturvorgabe. Wenn Sie hier z.B. auch die Seriennummer des Zertifikats in einer Spalte anzeigen, sollte dann nicht aufgrund einer fehlenden Referenz "N/A" angezeigt werden, sondern schon auch die Seriennummer. Das würde sonst beim Prüfung vermutlich Fragen aufwerfen.

Das Prüfprogramm holt sich die Zertifikatsdaten nicht aus dem Internet. Sie geben im cryptographicMaterialContainer das Zertifikat + Seriennummer an, mit diesen Daten wird dann das RKSV-DEP überprüft.
