### ISSUE TITLE
Zertifikats-Seriennummer Hexadezimal oder Dezimal bei Beleg gespeichert

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#32]
Die Seriennummer des Zertifikates könnte sowohl als BigInteger, als auch als hexadezimaler Wert im jeweiligen Beleg gespeichert werden. Gibt es hier eine Vorgabe seitens des BMF?

**Comment by pteufl** [comment]
ist ein guter Punkt. generell ist die Dezimal Variante eher Java-orientiert, da sonst eher die HEX-Variante verwendet wird. aktueller Status dazu: egal.
Zum Ordnungsbegriff für Unternehmen bei geschlossenen Gesamtsystemen, da wird es noch in Abstimmung mit dem BMF eine Aussage geben.
Beide Punkte werden in den nächsten Version explizit genannt.
