### ISSUE TITLE
RK-Chipkarte für USB-Stick Frage..

### ISSUE THREAD

**Issue by rikogithub** [a-sit-plus/at-registrierkassen-mustercode#322]
Hallo,
weiß jemand wie man die Chip-Karte über die asignp11.dll wieder ansprechen kann nachdem man den USB-Stick abgesteckt und anschließend wieder angesteckt hat (auch wenn die Chipkarte nicht gewechselt wurde)?

Signieren oder Zertifikatsabfrage funktioniert nur wieder nachdem das Registrierkassenprogramm beendet und neu gestartet wird.
Der Aufruf der Funktionen C_Finalize und C_Initialize hilft in diesem Fall nicht.

Danke für jede Info,
Richard.

**Comment by Phoniexk** [comment]
Auch beim Demo-Software von A-Trust ist es nur mit beenden und neustarten möglich. Das ist aber auch beim Kartenlesegerät so. Beim Kartenlesegeräte funktioniert nur das entfernen und stecken der Karte ohne Neustart.

Nachdem es auch in der Demo-Software so auftritt, habe ich aber auch keine Lösung dafür gesucht.

**Comment by rikogithub** [comment]
@Phoniexk:
Ja, nur leider ist das keine saubere Lösung für ein Produktivsystem...
Da ich schon soweit alles versucht habe, liegt es wahrscheinlich an der geladenen Dll, die ich aber nicht aus dem Speicher bekomme...

**Comment by ckvsoft** [comment]
Ich spreche die Karte direkt über APDUS an, da ist es egal wie oft an oder abgesteckt wird. Da kann ich das selber handeln.

**Comment by wjjw73** [comment]
Mache ich auch direkt über APDUs (USB-Stick mit Chip) und für Online-Lösungen die RK-Mobile von A-Trust! :)
Bis dato keine Probleme.

/Werner Weiss

**Comment by ckvsoft** [comment]
Wird von A-Trust auch empfohlen.

**Comment by rikogithub** [comment]
@ckvsoft,wjjw73:
Danke für den Hinweis... werde ich auch so machen.

**Comment by argetherapie** [comment]
Falls es noch jemanden interessiert:
Die aktuelle asignp11.dll v1.3.2.41 hat dieses Problem offensichtlich nicht mehr.
(Soeben getestet mit Aus- und wieder Anstecken des gesamten Chipkarten Lesegerätes bei laufendem Prozess)

Aus den ReleaseNotes.txt von A-Trust:
Version 1.3.2.38
- Update der PKCS#11 Schnittstelle zur Erkennung neuer Kartenleser nach Finalize Initialize Aufrufen
