### ISSUE TITLE
Startbeleg Prüfung nicht OK

### ISSUE THREAD

**Issue by Martin78** [a-sit-plus/at-registrierkassen-mustercode#323]
Ich komme im Moment nicht weiter. Meine Startbeleg Prüfung schlägt im FON und im Prüftool fehl.
Ich weiß leider nicht wo ich mit der Suche beginnen sollte...

Hier meine Daten:

[cryptographicMaterialContainer_start.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/780815/cryptographicMaterialContainer_start.json.txt)
[qr-code-rep.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/780816/qr-code-rep.json.txt)
[0000_app.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/780817/0000_app.json.txt)
[0000_cashbox.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/780818/0000_cashbox.json.txt)
[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/780819/0000_cashbox_full.json.txt)

**Comment by rolandro** [comment]
Hallo Martin,
In deiner cryptographicMaterialContainer_start.json.txt sind beim Zertifikat
Zeilenumbruchzeichen ("\n") drinnen. Die sollten da nicht drinnen stehen.
"MIIFPTCCAyWgAwIBAgIEaiHpyzANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNV **\n** ...."
lg

**Comment by Martin78** [comment]
Danke für den Tipp. Beim Auslesen von A-Trust Karten bekommt man immer die Zeilenumbrüche rein.
Hab sie entfernt aber ändert nichts am Testresultat. Fehler bleibt.

**Comment by areiter** [comment]
Ihr Problem zu diagnostizieren ist etwas schwierig. Das Prüfergebnis sagt einfach aus dass ihre Signatur kryptographisch ungültig ist.

Haben sie folgendes Dokument schon durchgearbeitet? https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf

Die ausschlaggebende Frage ist wohl: Wie berechnen sie den Hash (auf welchen Daten) der dann an die Sicherheitseinrichtung gesendet wird.

**Comment by Martin78** [comment]
Ja, genau das war vor einiger Zeit mein Problem das ich nicht wusste was ich in die Signatureinheit schicke. Siehe Post #254 
Damals hab ich gemeint ich habe es gelöst und scheinbar hat es jemand anderes auch so gemacht, siehe #190 

So sieht mein Code aus, d.h. ich schicke es vorher durch eine SHA-256 Hashfunktion:
`String jwsHeaderBase64Url = "eyJhbGciOiJFUzI1NiJ9";
String jwsPayloadBase64Url = RKSVUtils.base64Encode(machineCodeRepOfReceipt.getBytes(), true);
String jwsDataToBeSigned = jwsHeaderBase64Url + "." + jwsPayloadBase64Url;
            
MessageDigest md = MessageDigest.getInstance("SHA-256");
//calculate hash value
md.update(jwsDataToBeSigned.getBytes("UTF-8"));
byte[] jwsSignatureSHA256 = md.digest();

// Signieren
byte[] jwsSignature;
if (fastSignature) {
            	jwsSignature = signatureDevice.doSignaturWithoutSelection(jwsSignatureSHA256, "123456");
} else {
            	jwsSignature = signatureDevice.doSignatur(jwsSignatureSHA256, "123456");
}			
			
//encode result as BASE64-URL
String jwsSignatureBase64Url = RKSVUtils.base64Encode(jwsSignature, true);
			
//store as JWS compact representation
String ret = jwsHeaderBase64Url + "." + jwsPayloadBase64Url + "." + jwsSignatureBase64Url;`

**Comment by areiter** [comment]
Posten sie mal ein Beispiel mit konkreten Werten für: `machineCodeRepOfReceipt` `jwsDataToBeSigned.getBytes("UTF-8")` `jwsSignatureSHA256 `  `jwsSignature ` `ret `

**Comment by Martin78** [comment]
Hier eine Beispiel mit allen Schritten vom obigen Code:

machineCodeRepOfReceipt
_R1-AT1_2_N68_2017-02-16T23:33:37_0,00_0,00_0,00_0,00_0,00_hryqi3Tyua0=\n_6a21e9cb_1HNeOiZeFu4=\n


jwsDataToBeSigned.getBytes("UTF-8")
65794a68624763694f694a46557a49314e694a392e583149784c5546554d563879583034324f4638794d4445334c5441794c5445325644497a4f6a4d7a4f6a4d33587a41734d4442664d4377774d4638774c444177587a41734d4442664d4377770a4d46396f636e6c7861544e55655856684d44304b587a5a684d6a466c4f574e69587a4649546d56506156706c526e553050516f3d0a	


jwsSignatureSHA256
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855


jwsSignature
707c845bca7b171b55068aad52c33e261d0c8ecdf39e62db5d7e3af23d1599a18eda13262a39bd3a87cc480884b19d3357d7f7185c821574c257c5e872f01d6d

ret
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8yX042OF8yMDE3LTAyLTE2VDIzOjMzOjM3XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCww\nMF9ocnlxaTNUeXVhMD0KXzZhMjFlOWNiXzFITmVPaVplRnU0PQo=\n.cHyEW8p7FxtVBoqtUsM-Jh0Mjs3znmLbXX468j0VmaGO2hMmKjm9OofMSAiEsZ0zV9f3GFyCFXTC\nV8XocvAdbQ==\n

**Comment by areiter** [comment]
In ihrem `machineCodeRepOfReceipt` sind 2 Zeilen umbrücke `\n` enthalten die da nicht hin gehören

**Comment by Martin78** [comment]
Das ist mir mittlerweile auch aufgefallen. Da hat mir die Java String replace Methode einen Streich gespielt?!?

Hab jetzt keine \n mehr. Geht aber dennoch nicht. Selber Fehler

machineCodeRepOfReceipt	
_R1-AT1_2_N77_2017-02-17T00:04:53_0,00_0,00_0,00_0,00_0,00_2AILxnORJak=_6a21e9cb_1HNeOiZeFu4=	

jwsDataToBeSigned.getBytes("UTF-8")	
65794a68624763694f694a46557a49314e694a392e583149784c5546554d563879583034334e3138794d4445334c5441794c544533564441774f6a41304f6a557a587a41734d4442664d4377774d4638774c444177587a41734d4442664d4377774d46387951556c4d65473550556b7068617a31664e6d45794d57553559324a664d55684f5a553970576d564764545139 

jwsSignatureSHA256	
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855	

jwsSignatureStr	
3136e11ed9ba88b064af6a00bcd3e1040bef3c2894ae8aab60cce74d8e53088734b9b2caf5d142cb576c9fbf6af4362c04f539654ce63f83c446bd1d3390e73c	

ret
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8yX043N18yMDE3LTAyLTE3VDAwOjA0OjUzXzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8yQUlMeG5PUkphaz1fNmEyMWU5Y2JfMUhOZU9pWmVGdTQ9.MTbhHtm6iLBkr2oAvNPhBAvvPCiUroqrYMznTY5TCIc0ubLK9dFCy1dsn79q9DYsBPU5ZUzmP4PERr0dM5DnPA==

**Comment by Martin78** [comment]
Problem gelöst. Es waren die \n aber mit all dem Debug output hab ich einen sau blöden fehler zusätzlich eingebaut:)
Danke für Ihre Hilfe!
