### ISSUE TITLE
Steuersätze

### ISSUE THREAD

**Issue by wjjw73** [a-sit-plus/at-registrierkassen-mustercode#324]
Ich habe mich gefragt, ob es egal ist, in welchen Felder die (derzeitigen) Steuersätze eingetragen werden.
Es gibt ja:
- Beleg-Satz-Normal
- Beleg-Satz-Ermaessigt-1
- Beleg-Satz-Ermaessigt-2
- Beleg-Satz-Null
- Beleg-Satz-Besonders

Ich hätte gedacht 20% in Normal, 10% in Ermäßigt-1, 0% in Null, 12% in Ermäßigt-2 und 19% in Besonders.
Diese Definition hab ich jedoch nirgendwo gefunden.
Ist die Annahme korrekt? 
Eigentlich ist es ja auch egal, solange die Summe (Umsatzzähler) stimmt.

**Comment by lebail** [comment]
Es ist nicht egal. Ihre Liste ist aber korrekt - abgesehen davon, dass Ermäßigt-2 derzeit nicht 12%, sondern 13% beträgt.

**Comment by wjjw73** [comment]
13% - ja Tippfehler... Ab-Hof Verkäufe.
Wenn nicht egal, wie wird dann bei einer Steuersatzänderung vorgegangen?
Wäre es dann nicht gleich besser gewesen:
- Beleg-Satz-20-Prozenz
....

**Comment by ErichFreitag** [comment]
Nicht nur Ab-Hof-Verkäufe...

Bei Steuersatzänderungen wird sich wohl verordnungs- und/oder gesetzestechnisch was ändern müssen. Das ist nicht vorhersehbar. Und ob etwas besser gewesen wäre ist leider müßig...

**Comment by AxelKutschera** [comment]
Die Meinung des BMF zur Zuordnung steht im Erlass des BMF auf Seite 35:
https://www.fiskaltrust.at/wp-content/uploads/2015/08/160804-Erlass-zur-Einzelaufzeichnungs-Registrierkassen-und-Belegerteilungspflicht-72122.1.X.X-ak.pdf

**Comment by wjjw73** [comment]
Super, genau das habe ich gesucht!
Danke Axel!

**Comment by AxelKutschera** [comment]
gerne - obwohl ich nicht weiß, wer @wjjw73 ist? ;-)
