### ISSUE TITLE
Gültiger Zeitraum für Monatsbelege

### ISSUE THREAD

**Issue by devobj** [a-sit-plus/at-registrierkassen-mustercode#326]
Hallo,

der Monatsbeleg soll nach Vorgabe RKSV am Ende des Monats erstellt werden. Wie sieht es aber aus, wenn  z.B. die automatische Sicherung kurz vor Mitternacht beginnt und aufgrund von Verzögerungen (Signierung & Backup insb. bei vielen Kassen) im nächsten Monat nach 0:00 Uhr endet, sodass einige Kassen z.B. Monatsbelege von 23:59 Uhr besitzen, andere dagegen Monatsbelege von 0:01 Uhr.

**Comment by ErichFreitag** [comment]
Sie verwechseln vermutlich das Datenbackup mit der Sicherung des RKSV-DEPs. Das RKSV-DEP gibt es pro Kasse und kann somit nur in sich konsistent sein.

**Comment by devobj** [comment]
Ich verstehe es so, dass jedes DEP am Ende des Monats einen Monatsbeleg enthalten muss. Bei dieser Erstellung wird das DEP auch gesichert. Meine Frage bezieht sich darauf, ob man z.B. einen Monatsbeleg für Februar auch am 01.03. um 0:01 Uhr aufgrund von Verzögerungen erstellen kann. Genau genommen, kann der Benutzer ja bis kurz vor Mitternacht gültige Belege für den Monat Februar erstellen wollen.

**Comment by MichaelSchustereder** [comment]
Wir produzieren den Monatsbeleg automatisiert beim ersten Start der Kasse im neuen Monat und sichern anschließend das DEP. Somit wird der Monatsbeleg für Jänner erst im Februar produziert. Dies ist laut WKO zulässig, sofern sichergestellt ist, dass der Monatsbeleg als erstes erstellt wird. Wesentlich ist nur, dass dieser Monatsbeleg gemacht wird und zwar vor den „Verkäufen“ des neuen Monats.

**Comment by ErichFreitag** [comment]
Siehe Erlass 4.5.7: "Bei Unternehmen, deren Öffnungszeiten über Mitternacht hinausgehen, ist es möglich, den Monatsbeleg nach Ende der Öffnungszeiten zu erstellen, spätestens allerdings am nächsten
Öffnungstag, so dieser zeitnah stattfindet (etwa eine Woche)".

**Comment by devobj** [comment]
Danke für die Info.
