### ISSUE TITLE
Belegprüfungsfehler

### ISSUE THREAD

**Issue by grazkassa** [a-sit-plus/at-registrierkassen-mustercode#328]
Hallo, 

Noch eine Frage .
Sowie ich das verstanden habe kann man Signatureinheiten und RK beliebig an und abmelden .
Meine Frage hauptsächlich während der Entwicklung relevant .
Ich verwende natürlich die gleiche Kassen ID und das gleiche Zertifikat zum Entwickeln .
Vor 2 Tagen war es Problemlos möglich, die SE und RK abzumelden (Außer Betrieb ) und neu Anzumelden und den Startbeleg zu prüfen .
Das ist jetzt nicht mehr möglich da diese ominöse Meldung kommt die hier schon besprochen wurde : 
ABER bei uns findet die Startbelegprüfung IMMER nach dem programatischen Anlegen der SE und RK.
Was eben vor 2 Tagen noch funktioniert hat .
Die jetzige Fehlermeldung : 

Obwohl der Startbeleg gesetzeskonform zustande gekommen ist, weist die Ihre Signatur- bzw. Siegelerstellungseinheit im FinanzOnline einen Status auf, bei dem die gesetzlich vorgeschriebene Inbetriebnahme nicht möglich ist. Für eine erfolgreiche Startbelegprüfung muss Ihre Signatur- bzw. Siegelerstellungseinheit über FinanzOnline (neu) registriert werden.

die SE neu Anmelden bringt nichts .
Alles abmelden bringt nichts , neue RK Nummer vergeben bringt leider nichts .

Vielleicht kann jemand so nett und helfen ?

Vielen Dank 
LG
Ramy

**Comment by grazkassa** [comment]
Spielt auch vielleicht die PaketNr eine Rolle ? Also Anmeldeprozess Paket 1 , und Beleprüfung Paket 2 ?

Danke !!

**Comment by tragatschnig** [comment]
Der selbe Fall schlägt bei unseren Tests auf. Die BMF Hotline kann dieses Verhalten weder bestätigen noch widerlegen. Evtl kann mal jemand "mit mehr Gewicht" nachhaken, wie da nun die aktuelle Sachlage ist?

Unsere Fragen dazu, basierend auf unseren Vermutungen, warum das FON diesen Fehler zurückliefert:
-) ist die Anmeldung der SE und RK sowie die Prüfung des Beleges zeitkritisch? Gibt es eine Latenzzeit, welche beachtet werden muss zwischen Erwerb eines Zertifikates, Registrierung der SE und Prüfung des Startbeleges?
-) gibt es (nun doch) eine Einschränkung, wie oft ein Zertifikat für die Anmeldung einer SE "wiederverwendet" werden darf?

Und eventuell lässt sich auch dabei noch klären, warum das Testszenario ein anderes Verhalten aufweist als das Produktivszenario. Im Testmodus und im Prüftool läuft das alles ja pipifein durch. Abweichung im Verhalten der beiden FON-"Modi"  zwingt uns dazu, unsere Tests am Produktivszenario durchzuführen. Wenn aber nun das Produktivszenario verhindert, dass z.B. ein Zertifikat öfters für die Anmeldung von SEs verwendet werden kann, ist das auch mehr als suboptimal.

**Comment by noxe** [comment]
Ich habe das selbe Problem hier - ging vor einigen Wochen noch problemlos!??
