### ISSUE TITLE
Brutto-Netto - ig/rc oder MOSS

### ISSUE THREAD

**Issue by giemes** [a-sit-plus/at-registrierkassen-mustercode#33]
Nur kurze Nachfrage zu den Sonderfällen:

Wenn ich innergemeinschaftliche Lieferungen (oder Reverse Charge) Bar-Einnahmen habe oder Einnahmen im Bereich "Spezielle Elektronische Leistungen B2C im EU-Ausland (MOSS-EU Art 25a UStG)" habe, werden diese "nicht in Österreich versteuert" und gehören somit im Signaturformat in die NULL-Satz (nicht im Sonder-Satz dazu).

Sehe ich das richtig?

Danke!
lG_Gerd

**Comment by pteufl** [comment]
ich leite das ans BMF weiter, da ich hier nur technische Auskünfte geben kann.

**Comment by giemes** [comment]
gäbs da etwas Neues dazu?
Danke!
lG_Gerd

**Comment by giemes** [comment]
Ist das BMF schon zu einer Stellungnahme zu erreichen gewesen?
Würde mich über Feedback freuen - Danke!
lGG

**Comment by asitplus-pteufl** [comment]
ist in bearbeitung.

**Comment by asitplus-pteufl** [comment]
Antwort des BMF:
Elektronisch erbrachte sonstige Leistungen an Nichtunternehmer iSd § 3a Abs. 5 Z 3 UStG
1994 werden an dem Ort erbracht, an dem der Leistungsempfänger seinen Wohnsitz, Sitz
oder gewöhnlichen Aufenthalt hat.
Ist dieser Sitz nun außerhalb von Österreich aber im Gemeinschaftsgebiet, ist die erbrachte Leistung in Österreich nicht steuerbar. In der Registrierkasse sind diese Umsätze in der 0 % Steuerklasse zu erfassen.
