### ISSUE TITLE
Mehrfache Inbetriebnahme

### ISSUE THREAD

**Issue by PeterRumpf** [a-sit-plus/at-registrierkassen-mustercode#330]
Hallo
unser Kunde betreibt mehrere Filialen.
Für besondere Anlässe kann der Filialleiter eine zusätzliche Kasse in der Zentrale anfordern (z.B. Veranstaltung, Straßenfest...). Hierfür hat die Firma mehrere Geräte zur Verfügung.
Nach der Veranstaltung wird die Kasse in der Filiale abgebaut und wieder in der Zentrale eingelagert.
Die Betriebsdauer der Zusatz-Kasse liegt im Bereich einiger Tage bis max. 2 Wochen.

Unser Prozess für diesen Fall sollte folgendermaßen aussehen:

1. Inbetriebnahme der Kasse mit neuen DEP, Startbeleg usw. mit entspr. Meldungen usw.
2. Schlussbeleg, planmäßigen Außerbetriebnahme mit entspr. Meldungen usw.
3. Datensicherung DEP.
4. Abbau

Findet in einer Filiale mehrmals im Jahr eine Veranstaltung statt, würde sich dieser Vorgang entsprechend wiederholen, d.h. wie hätten für jeden Betriebsintervall ein eigenes dep.

Aus organisatorischen Gründen würde die Zusatz-Kasse in der jeweiligen Filiale mit der gleichen Kassenidentifikationsnummer betrieben werden. Die Kasse kann über die Kassenidentifikationsnummer aber eindeutig der Filiale zugeordnet werden. z.B. 0190-31  für Kasse 31 in Store 190

Wäre diese Vorgehensweise so korrekt.
Danke Peter

**Comment by ErichFreitag** [comment]
Ja und nein...

Es ist nicht unbedingt erforderlich, diese Kassen ab- und wieder anzumelden. Wenn das Kassen für solche Zwecke sind, können sie auch angemeldet bleiben, auch wenn sie zeitweise nicht betrieben werden. Eine Außerbetriebnahme ist etwas ziemlich endgültiges für eine Kasse. Dokumentieren würde ich nur, wo wann welche Kasse eingesetzt wird. 

Im Zuge dessen ist auch die Jahresbelegsprüfung nicht zu vergessen und die gegebenfalls automatische Monatsbelegserstellung bei Wiederinbetriebnahmen nach längeren Pausen (natürlich auch bei monatsübergreifendem Betrieb).

Das mit der gleichen Kassen-ID habe ich nicht verstanden - zumindest darf es innerhalb eines Unternehmens immer nur eindeutige Kassen-IDs geben.

**Comment by PeterRumpf** [comment]
Hallo
Die Kassen ID ist im Unternehmen eindeutig durch die Kombination "FilialNr-KassenNr"   0190-31 für Kasse Nr. 31 in Filiale Nr. 190.

Nach einer Veranstaltung von 3 Tagen in Filiale Nr 190 (als KasseId 190-31 ) kann aber das gleiche Gerät durchaus einige Tage später in Filiale Nr 220 (als Kasse Id (220-31 ) eingesetzt werden. 
...Und wie im obigen beispiel erwähnt ein halbes Jahr später wieder in Filiale 190 als KasseId 190-31.
 
Alle Nachfolgeprozesse im Unternehmen (Warenwirtschaft, SAP usw) benötigen ja auch eine eindeutige Zuordnung zur Filiale somit ist es problematisch die Kasse "einfach weiterlaufen zu lassen"..

**Comment by ErichFreitag** [comment]
OK, auch gut. Sie müssen halt nur entscheiden, was am Ende aufwändiger ist.

Fixe "Wander-Kassen-ID" einem Vorgang/Zeitraum zuordnen oder xx DEPs mit gleicher Kassen-ID aufbewahren und jedesmal konfigurieren und auf abmelden nicht vergessen und ...

**Comment by PeterRumpf** [comment]
Ich denke den Prozess wie beschrieben (In/Ausserbetriebnahme) durchzuführen ist evtl etwas aufwendiger aber unterm streich eindeutiger und weniger Fehleranfällig, . Insb. weil das Aufstellen der Kassen durch einein externen Dienstleister durchgeführt wird.

Muss für eine Kasse die im laufenden Jahr außer Betrieb genommen wird ein Jahresendbeleg erstellt werden oder reicht da der Schlussbeleg.

**Comment by ErichFreitag** [comment]
Die Außerbetriebnahme erfolgt mit dem Schlussbeleg.

Wenn das ein externer Dienstleister macht achten sie auch auf die DEP-Sicherung - die muss pro abgemeldeter Kasse aufbewahrt werden, also irgendwie zum Unternehmer kommen.

**Comment by PeterRumpf** [comment]
Danke
Die Außerbetriebnahme und die Sicherung(en) erfolgen noch in der Filiale. Die Aufbewahrung des DEP bzw. dessen Sicherung ist gewährleistet.

Danke für die Informationen.
Peter
