### ISSUE TITLE
Belegnummern fortlaufend oder nur eindeutig?

### ISSUE THREAD

**Issue by x-t-i-a-n** [a-sit-plus/at-registrierkassen-mustercode#331]
In den "DETAILFRAGEN" steht:
_Jeder von einer Registrierkasse erstellte Beleg muss über die Belegnummer des Barumsatzes eindeutig pro Kassen-ID und AES-Schlüssel unterscheidbar gemacht werden. Die Belegnummer eines Belegs ist innerhalb eines Unternehmens für Kassen-ID und AES-Schlüssel eindeutig._

Muss nun die Belegnummer fortlaufend vergeben werden, oder ist es zulässig Belegnummern z.B. mit einem Jahres-Präfix  zu versehen und jedes Jahr wieder von 1 (mit vorangestellter Jahreszahl) zu beginnen:

Also:
2016-1, 2016-2, ... und dann 2017-1, 20017-2 usw. ?

Zusatzfrage:
Da Bareinlagen und Barentnahmen in/aus der Kassa nicht signiert werden müssen, werden damit diese Belege/Belegnummern auch nicht im DEP aufgenommen. Ist das zulässig?

**Comment by ErichFreitag** [comment]
Belegnummern sind vorzugsweise fortlaufend zu vergeben, da ansonsten erhöhter Erklärungsaufwand bei Prüfungen entsteht. Sie dürfen aber auch einer Systematik folgen, z.B. wie hier mit einer Jahreszahl vorangestellt, sollten dann aber wieder fortlaufend sein.

Was nicht signiert wird kommt auch nicht in das RKSV-DEP, korrekt.

**Comment by x-t-i-a-n** [comment]
Nachdem wir in der Kasse fortlaufende Belegnummern für alle Geschäftsfälle vergeben. ist es dann wohl sinnvoll, auch Bareinlagen und Barentnahmen zu signieren und ins RKSV-DEP zu übernehmen.

Sind diese nun als NULL-Belege ohne Änderung des Umsatzzählers zu erstellen, oder ist die Einlage/Entnahme im Beleg-Satz-Null aufzuführen und damit im Umsatzzähler mitzuführen?

**Comment by AxelKutschera** [comment]
Alles, was signiert wird, muss in den Summenzähler. Wenn der Betrag nicht umsatzsteuerpflichtig ist, dann eben in den Betrag-Satz-Null..

**Comment by ErichFreitag** [comment]
Es wird auch davon abhängen, welche Geschäftsfälle sie noch abbilden. Wenn alle Geschäftsfälle eine fortlaufende Belegnummer bekommen können auf den RKSV-Belegen wieder welche fehlen (Kassensturz, Wechselgeld, ...). Im Gegenzug "alles zu signieren" ist auch nicht sinnvoll - da braucht es nun mal eine Entscheidungslogik und/oder einen eigenen Belgnummernkreis.

**Comment by AxelKutschera** [comment]
Im Erlass Kapital 4.6.2 Fortlaufende Nummer steht:
"4.6.2. Fortlaufende Nummer
Die in § 132 Abs. 3 Z 2 BAO geforderte Angabe („eine fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung des Geschäftsvorfalles einmalig vergeben wird“) entspricht wörtlich dem Rechnungserfordernis des § 11 Abs. 1 Z 3 lit. h UStG 1994 (siehe UStR 2000 Abschnitt 11.1.6.6.)."

Daher ist der jährliche, aber auch tägliche Neubeginn möglich.
Wir verwenden bei fiskaltrust ZUSÄTZLICH den bestehenden Nummern jedoch eine lückenlos, fortlaufende und aufsteigende Nummer für jeden SIGNIERTEN Barumsatz.

UStR 2000 Abschnitt 11.1.6.6. Fortlaufende Nummer
1548
Die Rechnung hat eine fortlaufende Nummer mit einer oder mehreren Zahlenreihen, die zur Identifizierung einmalig vergeben werden, zu enthalten. **Im Rahmen der fortlaufenden Nummer sind auch Buchstaben zulässig,** sofern das Erfordernis der fortlaufenden Bezeichnung gewährleistet ist.

1549
Das Erfordernis der Rechnungsnummer gilt sowohl für die Ausstellung von Rechnungen als auch für die Ausstellung von Gutschriften. Die Rechnungsnummern können für Gutschriften auch getrennt erteilt werden. Gutschriften benötigen keine fortlaufende Nummer beim Empfänger der Gutschrift.

1550
In die fortlaufende Nummerierung können auch die Kleinbetragsrechnungen einbezogen werden.

1551
Der Zeitpunkt des Beginnes der laufenden Nummer kann frei gewählt werden, muss jedoch systematisch sein (**auch täglicher Nummernbeginn ist zulässig**).

1552
Es sind verschiedene Rechnungskreise zulässig (zB Filialen, Betriebsstätten, Bestandobjekte, Registrierkassen), die Zuordnung muss jedoch eindeutig sein. Es können auch verschiedene Vertriebssysteme, Warengruppen oder Leistungsprozesse (zB Safe oder Depotleistungen bei Kreditinstituten) als eigene Rechnungskreise angesehen werden.

1553
Bei ausländischen Unternehmern ist für inländische Umsätze ein eigener Nummernkreis erforderlich. Ebenso ist bei Konzernunternehmen (die keine Organschaft sind) für jeden Unternehmer ein eigener Nummernkreis erforderlich.
