### ISSUE TITLE
Monats- und Jahresbeleg

### ISSUE THREAD

**Issue by devobj** [a-sit-plus/at-registrierkassen-mustercode#332]
Hallo,

kann ein Jahresbeleg auch einen Monatsbeleg für einen anderen Monat als Dezember ersetzen, wenn die Geschäftstätigkeit z.B. für den Zeitraum von Februar bis November stattfindet?

Beispiel:
Monatsbeleg 09/2016
Monatsbeleg 10/2016
Jahresbeleg 2016 (ersetzt Monatsbeleg 11/2016)
Monatsbeleg 02/2017
Monatsbeleg 03/2017

**Comment by ErichFreitag** [comment]
Wenn es den Charakter eines Saisonbetriebs hat - ja (bei sogenannten Saisonbetrieben (zB Schwimmbad) kann dieser Vorgang auch zu Saisonende, spätestens jedoch vor Beginn der unternehmerischen Tätigkeit im neuen Jahr erfolgen).

Ansonsten ist auf den eventuellen Zusammenfall mit dem Jahresabschluss und der Jahresbelegs-Prüfung bis spätestens 15.02. zu achten.

**Comment by AxelKutschera** [comment]
Ich würde es sogar so beschreiben: Der Monatsbeleg 11/2016 wird (sofort) als Jahresbeleg geprüft.
