### ISSUE TITLE
X509-Zertifikat im DER-Format dargestellt und BASE64-kodiert

### ISSUE THREAD

**Issue by wolf1312** [a-sit-plus/at-registrierkassen-mustercode#333]
Hallo,

Mein Prüftool schlägt fehl und irgendwie vermute ich meinen Fehler eher in meinem cryptographicMaterialContainer.json als in meinem DEP.

Die Zertifikat-Seriennummer erhalte ich gemäß http://labs.a-trust.at/developer/ShowArticle.aspx?id=113 problemlos. (Windwos - RK CHIP - genau wie im screenshot)
Es ist doch das 'Signaturzertifikat' und nicht das 'Geheimhaltungszertifikat' - oder liege ich da falsch?

Aber wie komme ich auf "X509-Zertifikat im DER-Format dargestellt und BASE64-kodiert".
Ich hab auf den 'In Datei kopieren' button gedrückt und die erhaltene Datei dann BASE64 kodiert - aber ist das wirklich das was ich brauche?

**Comment by ErichFreitag** [comment]
Sie brauchen das Signaturzertifikat, korrekt. Ein Weg das herauszubekommen ist beispielsweise folgender:

A-Trust Verzeichnisdienst - Seriennummer o.ä. eingeben
Zertifikatsinfo downloaden
Konvertieren mit openssl x509 -inform der -in <input.cer> -out <output.pem>

Das ergibt das Zertifikat im .PEM-Format, das sie nach Entfernen von Zeilenumbrüchen verwenden können. Was dort enthalten ist können sie z.B. mit https://certlogik.com/decoder/ ansehen.

**Comment by wolf1312** [comment]
Vielen Dank!
Damit kam ich zwar zum gleichen Ergebnis. Aber es ist mir etwas aufgefallen.

Ich habe auf https://www.a-trust.at/verzeichnisdienst/ entdeckt, dass das von mir als Signaturzertifikat ermittelte Zertifikat, dort als Geheimhaltungszertifikat ausgegeben wird.

Zu meinem Geheimhaltungszertifikat findet sich gar nichts auf der Seite.

Ich denke ich wende mich da mal direkt an A-Trust

**Comment by 01af** [comment]
@wolf1312 - Ich habe haargenau das gleiche Problem. Hast du dazu von A-Trust etwas erfahren können? Im Prinzip muss man ja nur wissen, mit welcher APDU man das Signaturzertifikat auswählen kann.
