### ISSUE TITLE
Verschleiern der Belegnummer

### ISSUE THREAD

**Issue by PeterRumpf** [a-sit-plus/at-registrierkassen-mustercode#334]
Hallo
Ein Kunde von uns hat in seinem alten Kassesnsystem eine Möglichkeit die Belegnummer zu "Verschleiern" bzw. zu Verschlüsseln. Hintergrund ist, dass einem Außenstehenden Dritten aufgrund der Belegnummer keine Rückschlüsse auf die Anzahl der Belege und somit die Anzahl der Kunden möglich sein sollen.

Die Verschlüsselung erfolgt über einen vom Kunden selbst entwickelten Algorithmus und ist umkehrbar.
Vereinfacht gesprochen "Mixt" er die Belegnummer (xor).  Das Resultat ist nach wie vor eindeutig, aber nicht mehr "Fortlaufend", ich würde es als "Durcheinander" bezeichnen.

Ist so etwas unter RKSV denkbar ?

Güsse
Peter

**Comment by ErichFreitag** [comment]
Wie sie selbst schreiben - fortlaufend ist das nicht mehr und könnte zu gröberem Erklärungsbedarf führen. Es widerspricht dem Wortlaut der fortlaufenden Belegnummer und eine Systematik im Sinne von Nummernkreisen oder Datumsangaben o.ä. ist auch nicht erkennbar.

Besser ist z.B. das Datum YYMMTT voranzustellen, dann ist die Anforderung nach außen vielleicht auch erfüllt.

**Comment by Flanelli** [comment]
Das Datum wäre allerdings für jemanden der überhaupt auf den Gedanken kommt aus der Belegnummer Rückscllüsse zu ziehen auf den ersten Blick erkennbar. etwa weniger auffällig wäre das Hintanreihen der "gemixten" Belegnummer und wenn man diese noch durch einen Bindestrich trennt sollte auch jeglicher Erklärungsbedarf glaubwürdig befriedigt werden.

**Comment by PeterRumpf** [comment]
Danke für die Einschätzung.
