### ISSUE TITLE
FON WebService Verhalten Test und Prod Unterschiedlich 

### ISSUE THREAD

**Issue by grazkassa** [a-sit-plus/at-registrierkassen-mustercode#335]
Ich habe eine Frage zum An und Ab melden von SE und RK .
Also im Test Modus lassen sich SE und RK in einem Zug zuerst Entfernen dann Neu Anlegen und anschließend mit einem Startbeleg prüfen .

Im Prod Modus geht das leider nicht mehr obwohl es schon gegangen ist , hat sich hier etwas verändert ?
Im Prod Modus kommt immer die Fehlermeldung das man die SE neu registrieren soll, obwohl sie im FON als In Betrieb erscheint  . 
Hab ich da etwas falsch verstanden  oder kann man eine Kassennummer nur einmal prüfen lassen , ich dachte nach der Außerbetriebnahme müsste die gleiche Kassennummer wieder neu zum registrieren gehen inkl. Startbeleg und Jahresbelegprüfung .

Vielen Dank

**Comment by huste** [comment]
Gleiches Problem hier.

**Comment by grazkassa** [comment]
Hallo ,
Also für uns war es dann so, das das ursprüngliche Zertifikat das wir sozusagen zum Entwickeln und Testen verwendet haben sich NICHT mehr verwenden ließ obwohl der Zustand im FON auf In Betrieb war.Nachdem wir dann ein neues Zertifikat gelöst haben auf die gleiche UID hat alles funktioniert .
Es hat jemand hier im Forum  schon mal geschrieben gehabt ,das es sich empfiehlt bei den Kundentests etc. eine neue SE mit einem neuen Zertifikat einrichten .
Programmatisch dann immer prüfen ob die SE da ist ,wenn nicht dann neu anlegen .
