### ISSUE TITLE
Startbeleg WebService

### ISSUE THREAD

**Issue by ChristianSpath** [a-sit-plus/at-registrierkassen-mustercode#337]
Hallo zusammen!

Irgendwie sehe ich vor lauter Bäumen den Wald nicht mehr ;)

Registrierung der SE und der RK funktionieren über das WebService einwandfrei. Aber wie kann ich den Startbeleg prüfen? Ist das ein normaler Belegcheck?

Vielen Dank und liebe Grüße,

**Comment by AxelKutschera** [comment]
Exakt. 
Der Belegcheck geht über die BMF Belegcheck-App oder über WebService. (eh klar) 
Damit ist die RegK in Betrieb genommen.

**Comment by ChristianSpath** [comment]
Thanks!!!
