### ISSUE TITLE
Anerkennung eines elektronischen Belegs (sorry für die rechtliche Frage)

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#34]
Nachdem ich keine andere sinnvolle Kontaktmöglichkeit zum BMF kenne (der WKO-Verteiler, dem ich kürzlich beigetreten bin, scheint ja entgegen meiner Erwartung keine Diskussionsliste zu sein, sondern nur "read-only"), deponiere ich meine (hoffentlich) letzte offene rechtliche Frage hier - und freue mich über eine Weiterleitung an das BMF.

Die Frage ergab sich erst aus der letzten FAQ des BMF vom 4.2., und ich könnte mir vorstellen, dass sie auch andere Entwickler interessiert:

Dort steht nämlich bei Nr. 75:

> Zur Anerkennung eines elektronischen Belegs ist es erforderlich, dass der Beleg den
> Verfügungsbereich des Unternehmers verlassen und in den Verfügungsbereich des
> Kunden gelangen muss, d.h., dass der Unternehmer nach der Übermittlung keine
> Möglichkeit mehr haben darf, den Beleg abzuändern oder zu entfernen

Quelle: https://communities.wko.at/Kassensoftware/Dokumente/Gesammelte%20FAQ%20Arbeitskreis%20Kassensoftware_20160204.pdf

Nun arbeite ich an einer Kassenlösung für "mobile Gruppen", bei der der Kunde anlässlich des Zahlungsvorganges ein vorproduziertes Kärtchen mit einem individuellen URL auf dem Server des Unternehmers erhält, unter dem er sich den (unmittelbar beim Zahlungsvorgang per Smartphone erfassten) Beleg sofort als PDF-Datei abrufen kann.

Auf einem A-Trust-Workshop im Oktober 2015 wurde diese Lösung von einem BMF-Mitarbeiter als zulässig (bzw. sogar vorbildlich) bezeichnet. Allerdings stellt sich die Frage, ob allein die Existenz der Beleg-Signatur ausreicht, die obige BMF-Forderung nach Unveränderbarkeit zu erfüllen, oder ob der Beleg auf einem externen Server gespeichert werden müsste, bei dem garantiert ist, dass der Unternehmer auf einen einmal erstellten PDF-Beleg keinen Schreibzugriff mehr hat.

Vielen Dank für die Hilfe!

**Comment by Parmenidoxes** [comment]
Bin von einem unserer Entwickler auf die Frage aufmerksam geworden. 
Ich bin zwar kein Jurist, aber solang der Beleg auf dem Server des Unternehmers liegt, hat er dessen Einflußbereich ja nicht verlassen, so klappt das also nicht.
Wir haben in für dieses Problem ein Produkt Marktreif - vielleicht ergeben sich Synergien.
Kontakt:  j.marberger@efsta.org. Würde mich freuen.

**Comment by pteufl** [comment]
Wird geklärt.

**Comment by asitplus-pteufl** [comment]
Ein elektronischer Beleg iSd § 132a Abs. 1 BAO ist ein Beleg, der in einem elektronischen Format ausgestellt und empfangen bzw. unmittelbar für den Leistungsempfänger verfügbar ist (vgl. § 11 Abs. 2 UStG 1994). Er kann zB mittels Email, als Email-Anhang oder Web- Download, in einem elektronischen Format (zB als PDF- oder Textdatei), aber auch in einem strukturierten Dateiformat (zB xml) ausgestellt werden. Der Beleg muss tatsächlich in den Verfügungsbereich des Belegempfängers gelangen. Ob dies elektronisch (per Email, Ablesen mittels Handyapp, etc.) oder in Papierform erfolgt, bleibt dem Belegaussteller überlassen. Die Übermittlung ist eine Bringschuld des Unternehmers, eine bloße Einräumung der Möglichkeit des Ansehens und Abfotografierens des auf einem Bildschirm angezeigten Beleginhaltes erfüllt nicht die Belegerteilungspflicht. Eine spezielle Form der elektronischen Übertragung ist nicht vorgeschrieben. **Ob die Übertragung in den Verfügungsbereich des Belegempfängers durch Aktivität des Leistungserbringers oder des Leistungsempfängers erfolgt, ist für die Erfüllung der Belegerteilungspflicht unerheblich**. Diese Art der Belegerteilung ist im elektronischen Aufzeichnungssystem zu dokumentieren.
