### ISSUE TITLE
Startbelegüberprüfung mit DEP-Prüftool erfolgreich - Fehlerhaft mit BMF App & Receipts Prüftool 

### ISSUE THREAD

**Issue by jPan-SOP** [a-sit-plus/at-registrierkassen-mustercode#342]
Hallo,
ich erhalte beim Einlesen des Startbeleges mittels BMF App sowie mit dem „regkassen-verification-receipts“ Tool folgende Fehlermeldung:
"Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen."
Die Überprüfung mit dem „regkassen-verification-depformat“ Tool klappt aber problemlos. Der Kryptographiecontainer ist bei beiden Tests der selbe. Ich gehe daher davon aus, dass bei der Umwandlung in den maschinenlesbaren Code ein Fehler auftritt, oder kann es auch an etwas anderem liegen? Die Kryptografie an sich sollte ja dem depformat Tool nach in Ordnung sein. 

Der Beleg in kompakter Darstellung (funktioniert) sieht wie folgt aus:

`eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9MQkE1NDUxNTM1NzQ2NTQ0RjQ4MDFfMjcxXzIwMTctMDItMjFUMTQ6NDc6NDJfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX1d0Rm80ZjJBNEtvPV83MDkyY2UyMF9SRTRRWHMxeEM2az0.WYDkxlrUjzjcIcLdF8t-TQUvvxz5c1cEU-wmxXs97QJALMxVXC5d3CA3fHSvgf6xDNB3CtwjPCmQRbVax0YSig`

Die QR-Code Repräsentation sieht wie folgt aus:

`_R1-AT1_LBA5451535746544F4801_271_2017-02-21T14:47:42_0,00_0,00_0,00_0,00_0,00_WtFo4f2A4Ko=_7092ce20_RE4QXs1xC6k=_We+/ve+/ve+/vVrUjzjvv70h77+977+9F++/vX5NBS/vv70c77+9c1cEU++/vSbvv717Pe+/vQJALO+/vVVcLl3vv70gN3x077+977+977+977+9DO+/vXcK77+9Izwp77+9Re+/vVrvv71GEu+/vQ== `

Die Umwandlung findet folgendermaßen statt:
```
String signature=belegKompakt.split("\\.")[2];

String base64Signature=CryptographicUtil.base64Encode(CryptographicUtil.base64Decode(signature.getBytes(),true).getBytes(),false);

return dataToBeSigned+"_"+base64Signature;
```

Die Funktionen zur Base64 Berechnung:

```
public static String base64Encode(byte[] data, boolean isUrlSafe)
{
    Base64 encoder = new Base64(isUrlSafe);
    return new String(encoder.encode(data)).replace("\r\n", "");
}

public static  String base64Decode(byte[] data, boolean isUrlSafe)
{
    Base64 decoder = new Base64(isUrlSafe);
    return new String(decoder.decode(data));//.replace("\n", "");
}

```
Vielen Dank für die Hilfe!

**Comment by ErichFreitag** [comment]
Da gibt es mit Verlaub wo einen großen Fehler in der Umwandlung vom maschinenlesbaren Code in die QR-Code-Repräsentation. Die Base64-Berechnung kann ich nicht nachvollziehen. BASE64URL-decodieren und das Ergebnis BASE64-codieren.

**Comment by jPan-SOP** [comment]
Fehler gefunden, wurde durch die unnötige Umwandlung in das Byte[] verursacht. Danke für Ihre Mühen!
