### ISSUE TITLE
MDE Gerät Sicherheitseinrichtung ausgefallen

### ISSUE THREAD

**Issue by PeterRumpf** [a-sit-plus/at-registrierkassen-mustercode#343]
Hallo
unser Kassensystem verfügt über Mobile Kassen (MDE Geräte). Hierbei handelt es sich um "vollwertige" Kassen mit lokaler Applikation und lokaler Datenspeicherung/Datenbank und Drucker (blue tooth). Also keine Eingabestation im Sinne von 3.1.1. Entsprechend würden wir auch das DEP lokal speichern. 
Leider verfügen die Geräte über keine Anschlussmöglichkeit einer Signaturerstellungseinheit (Chipkarte) allerdings sind die MDE's i.d.R. im WLAN, wir würden daher die Signaturerstellung über einen Service an einer beliebigen stationäre Kasse mit lokaler Signaturerstellungseinheit im Kassenverbund durchführen.

Hierbei ergeben sich nun folgende Fragen:
1. Falls das WLAN ausfällt oder gestört ist würde dies ja einem "Sicherheitseinrichtung ausgefallen" entsprechen. Da bisher die Signatur auf dem MDE von einem beliebigen Gerät (zufällig Auswahl im peer-to-peer Netz) ausgeführt wurde, würden wir für die verkettung den zuletzt signierten Beleg und entsprechende zda und Seriennummern verwenden?

2. Kunden verwenden die MDE System bisher auch um längere Zeit autark (offline) zu arbeiten, z.B. in einem Verkaufsstand in der Fußgängerzone oder in einem mobilen Verkaufsstand auf dem Messegelände.
Wäre dies erlaubt, da ja der Zustand "Sicherheitseinrichtung ausgefallen" quasi bewusst herbeigeführt wird.
Nach dem offline Einsatz werden die MDE's selbstverständlich wieder ins Kassennetz genommen, dann könnte ein "Sammelbeleg" erstellt werden usw.

 Grüsse Peter

**Comment by AxelKutschera** [comment]
Hallo,
es gibt übrigens einen Bluetooth-ChipCard-Reader. 
Wir haben auch eine SignatureBox um die Sicherheitseinrichtung im LAN zur Verfügung zu stellen.
Es kann auch über eine Online-Sicherheitseinrichtung (SignatureCloud) gearbeitet werden.

1. Wir haben diese Szenarien durch den fiskaltrust-Dienst unterstützt und stellen einen eigenen Load-Balancer zur Verfügung.
2. Auch das wollen wir in dieser Weise machen.

**Comment by PeterRumpf** [comment]
Danke für die info. 
Nach einem bluetooth chipreader habe ich noch garnicht gesucht auf die idee bin ich noch nicht gekommen.
Wir haben umfangreiche POS-Services innerhalb unserer peer-to-peer Architektur dort würden wir den Signaturprozess integrieren.

1. Im Fall des Ausfaĺl ist mMn die RKSV Spezifikation etwas unglücklich... da teile ich die Auffassung in Beitrag #281  und nehme mal den letzten Beleg.

2. Es beruhigt mich, dass andere Anbieter ein ähnliches Problem haben und es genauso angehen wollen.
Ich vermute dass es zu Nachfragen kommen wird wenn mehrmals im Monat oder sogar jeden Tag die "SE ausfällt" ?
Wie würden Sie es beurteilen wenn man Mogens bei Arbeitsbeginn mit dem Gerät "offline" geht (evtl noch einen Nullbeleg erstellt) dann den ganzen tag im Modus "Sicherheitseinrichtung ausgefallen" arbeitet und nur zum Schichtende vor der Abrechnung das Gerät wieder online nimmt, also den Sammelbeleg erstellt.... und das jeden Tag?

**Comment by AxelKutschera** [comment]
Bitte Mail an mich senden, dann kann ich zu 2. ein pdf senden...

**Comment by cwimberger** [comment]
@AxelKutschera Ich wär an dem PDF zu Punkt 2 auch interessiert.

**Comment by PeterRumpf** [comment]
Hallo
ist meine Mail bei Ihnen angekommen ?

**Comment by AxelKutschera** [comment]
Mail bitte direkt an axel.kutschera@fiskaltrust.at 
Vielen Dank

**Comment by PeterRumpf** [comment]
Danke
