### ISSUE TITLE
Umsatzzähler über Webservice falsch

### ISSUE THREAD

**Issue by mandihof** [a-sit-plus/at-registrierkassen-mustercode#344]
Hallo Leute,

ich hab ein Problem mit dem verschlüsseln des Umsatzzählers. Wenn ich den Startbeleg über das WebService von FON prüfen möchte bekomm ich immer den Fehler retour, dass der Umsatzzähler nicht entschlüsselt werden konnte. Ich habe folgenden string den ich an FON senden:

_R1-AT1_DemoKassa1_1001_2017-02-22T09:35:54_0,00_0,00_0,00_0,00_0,00_j0QPGDsDKak=_4A166366_Jb6a30PGbX0=_cmEhQGX4zHsSQtSyYT/8vW/OoOcJKQtYw0cRyIgroez6jiRT1BqARtPPcgSix4DufZi+NEMenFufkT3LPDO07w==

_KassenID:_ DemoKassa1
_BelegNr:_ 1001
_Umsatz:_ 0
_AESKey:_ WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=
_=> Umsatzzähler (8Byte):_ j0QPGDsDKak=

Den AESKey hab ich genauso im FON eingegeben, das passt doch oder muss man den dekodierten AESkey eingeben?

Hat jemand eine Idee. bzw könnte jemande den Umsatzzähler mit meinen Daten testen? Ich hab schon einige werte die ich hier im forum gesehen habe mit meiner verschlüsselung getestet und da kam ich eigentlich immer auf das korrekte ergebnis... deshalb bin ich etwas ratlos...?

Gruss Manfred

**P.S.: ich hab gerade bemerkt, dass wenn ich die art der übermittlung auf P (Produktiv) stelle, dann bekomme ich keine Fehlemeldung. Wäre euch aber dankbar, wenn jemand das kurz überprüfen könnte ob mein Umsatzzähler korrekt ist. Danke!**

**Comment by ErichFreitag** [comment]
Der Umsatzzähler ist bei mir 0.

**Comment by mandihof** [comment]
super, dann dürfte das passen!
