### ISSUE TITLE
Frage bezüglich (für mich) unlogischer Fehlermeldungen bei dem Prüftool

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#345]
Guten Tag,
bei der Prüfung meines DEPs mit dem Prüftool bekomme ich in den Dateien:
n_.app.json, n_cashbox.json, n_dep.json und DEP.json überall ein "PASS"

Nur in der Datei n_cashbox_full.json sind einige "FAILS" die für mich aber unlogisch sind:

z.B:
 "verificationName" : "Belegtyp: Startbeleg",
 "verificationTextualDescription" : "Es werden folgende Eigenschaften überprüft: Entschlüsselter Umsatzzähler gleich 0, Verkettungswert zeigt auf die Kassen-ID, alle Werte der Steuersätze sind 0, Signatureinrichtung darf nicht ausgefallen sein.",
 "verificationState" : "FAIL",
 "verificationResultDetailedMessage" : "Der entschlüsselte Umsatzzähler hat einen Wert ungleich 0.",

Eine Fehlermeldung bekomme ich auch in den Feldern :
""verificationName" : "Belegtyp: Trainingsbeleg"
"verificationName" : "Belegtyp: Stornobeleg",
"verificationName" : "Belegtyp: Nullbeleg",

 Wenn ich das recht verstehe wird hiermit beanstandet daß diese Belege  Sonderbelege sind.
Was aber nicht der Fall ist.

Trainingsbelege habe ich gar keine im DEP aber trotzdem steht auch bei bei diesem Wert "FAIL"

Kann ich das ignorieren oder mache ich hier vielleicht noch etwas falsch ?

Danke :)

**Comment by Skerge12** [comment]
anbei das DEP 
[Kassa-LB1_DEP_Export_Gesamt.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/792868/Kassa-LB1_DEP_Export_Gesamt.txt)

**Comment by cmaxmedia** [comment]
Hier werden die verschiedenen Belegeigenschaften "durchgetestet" - zumindest einer sollte auf "PASS" stehen

**Comment by Skerge12** [comment]
Alles klar.
Gottseidank - Dann passt es.
("verificationName" : "Belegtyp: Standardbeleg", ... "verificationState" : "PASS")
Vielen Dank !

**Comment by cmaxmedia** [comment]
Ich glaube, diesen Schock hatten wir alle mal kurz ;)
