### ISSUE TITLE
Kontroll-Nullbeleg bei ausgefallener Signatureinheit

### ISSUE THREAD

**Issue by argetherapie** [a-sit-plus/at-registrierkassen-mustercode#347]
Ich hätte zu diesem Thema Null/Sammelbeleg ein pikantes Szenario:
Zum Beispiel steht am 11.07. 8:00h der Prüfer des BMF im Geschäft und verlangt einen Nullbeleg zur Kontrolle. Die SE der Kasse ist dummer weise seit 10.07. 17:00h ausgefallen und es wurden inzwischen drei Belege "Sicherheitseinrichtung ausgefallen" erteilt, da die Kasse nur über ein Zertifikat verfügt und nicht auf eine andere Kasse ausgewichen werden kann. 
Da das Prüftool Sammelbelege und Nullbelege nicht auseinander halten kann, entsteht eine Aporie:
Entweder wird ein nicht signierter Kontroll-Nullbeleg erstellt welcher im DEP dann als ungültiger Sammelbeleg bemeckert wird 
oder -
Eigentlich kann der Kasseninhaber keinen Nullbeleg aushändigen, weil eine sauber implementierte Kasse einen Nullbeleg als ersten Beleg nur zur Beendigung eines Ausfall zulassen darf.

Ein weiteres "Paradox" in dem Szenario: Hätte der Kasseninhaber keine ausgefallenen Belege produziert, wäre der unsignierte Null-Kontrollbeleg gemäß Prüftool "erlaubt", denn 1 unsignierter Nullbeleg ist als ersten Beleg nach einem bisher gültig signierten Beleg erlaubt.

**Comment by ErichFreitag** [comment]
Ich kann dem nicht ganz folgen... Ein Kontrollbeleg ist ein simpler Nullbeleg, der auch mit "SE ausgefallen" erzeugt werden darf. Dem Prüftool ist das egal und es hat mit einem Sammelbeleg nichts zu tun. Es gibt keine Vorschrift, wo bei ausgefallener SE kein Nullbeleg erzeugt werden darf - siehe auch Startseite 18.11.2016 Signieren von Nullbelegen.

**Comment by argetherapie** [comment]
Danke für die schnelle Antwort.
Das verbesserte Prüftool wird seit Monaten versprochen und es ist (1 Monat vor dem 1. April 2017!) überhaupt nicht klar, wie es sich in Einzelfällen verhalten wird.  Ob es zB eine Serie von unsignierten Nullbelegen/Barbelegen/Nullbelegen akzeptiert oder ob das dann bei der nächsten Kassenprüfung ein Problem sein wird.  Dem kann ich nicht ganz folgen...
