### ISSUE TITLE
Finanzonline Webservice

### ISSUE THREAD

**Issue by smtm** [a-sit-plus/at-registrierkassen-mustercode#348]
Sehe ich das richtig: Wenn ich mit der Testumgebung des FinanzOnline Webservice (https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/BMF_Registrierkassen_Webservice.pdf?5q37o6) interagieren möchte dann muss ich lediglich mit meiner SOAP Library auf https://finanzonline.bmf.gv.at/fonws/ws/regKasseService.wsdl losgehen mit dem Parameter "art_uebermittlung" = T?

Oder muss ich mich bei jemand von der Finanz als Software Hersteller bekannt machen und jemand schaltet dann etwas frei?

Wenn dem so wäre, gibt es auch für die QR-Code-mit-"BMF Belegcheck"-App-scannen Prozedur eine Art Testmodus?

**Comment by cmaxmedia** [comment]
Für FON hab ich Kundenseitig folgendes gemacht:
1) Eigener User für Registrierkassenfunktionen (Anlegen eines Benutzers für Registrierkassen-Webservice)
2) Code für Belegcheck App anlegen (Verwaltung von Authentifizierungscodes für App zur Prüfung der Kassenbelege)

Mit diesen beiden Punkten konnte ich via SOAP alles weitere Abbilden, also die Session holen, 
die Registrierung einer SE und einer Kasse sowie die Startbelegprüfung via Kunden-App.

SOAP Anfragen mit T wurden bei mir im Log nicht angezeigt, worauf ich dann "nur" die T-Übermittlungen auf den Responsecode 0 überprüft habe. Nach der Umstellung auf P wurden diese dann mit einigen Minuten Verzögerung akzeptiert.

Als Softwarehersteller habe ich eine mit meinem Unternehmen identifizierbaren Text verwendet

Die BMF App dient scheinbar auch nur der produktiven Übermittlung und Prüfung des Startbeleges. Für eine einzelne Belegprüfung empfiehlt sich das Java-Tool auf Github...
lg

**Comment by smtm** [comment]
Ok, Mhhm, klingt wie JS debuggen, einst mit IE6...  

Mit dem JAVA-Tool auf Github, nehme ich an, ist dieser Teil gemeint?
`regkassen-demo-1.0.0/regkassen-verification-depformat-1.0.0.jar -f -i dep-export.json -c cryptographicMaterialContainer.json -o output`

Der läuft bei mir schon ohne FAIL durch. Überlege dies als Verifikation in die Produktivumgebung
beim DEP Export miteinzubauen...
