### ISSUE TITLE
Prüfung Startbeleg

### ISSUE THREAD

**Issue by noxe** [a-sit-plus/at-registrierkassen-mustercode#349]
Hallo zusammen,

ich habe aktuell ein Problem mit der Startbeleg Prüfung. Bisherige Tests klappten immer problemlos - alle war OK seitens FON. Heute habe ich die Siatuation das die Prüfung im FON fehlschlägt - während das lokale Prüftool behauptet alles sei ok. Die Hotline konnte uns heute auch nicht weiterhelfen, hat jemand eine Idee was hier das Problem sein könnte?

Fehler FON:

<verificationResult>
            <verificationId>STATE_CONSOLIDATED</verificationId>
            <version>1</version>
            <verificationName>Statusprüfung der Kasse und Signatur-/Siegelerstellungseinheit</verificationName>
            <verificationTextualDescription>In diesem Modul und den dazugehörigen Submodulen werden die Zustände der Kasse und der verwendeten Signatur-/Siegelerstellungseinheit und die Ergebnisse der zuvor durchgeführten Prüfungen (vor allem der Belegtyp) ausgewertet. Handelt es sich um einen Startbeleg, wird überprüft ob eine Inbetriebnahme der Kasse möglich ist.</verificationTextualDescription>
            <verificationState>FAIL</verificationState>
            <verificationTimestamp>2017-02-22T13:52:17.220+01:00</verificationTimestamp>
            <verificationResultList>
              <verificationResult>
                <verificationId>STATE_SIGDEVICE</verificationId>
                <version>1</version>
                <verificationName>Statusprüfung der Signatur-/Siegelerstellungseinheit</verificationName>
                <verificationTextualDescription>Es wird der Status der Signatur-/Siegelerstellungseinheit zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-22T13:52:17.220+01:00</verificationTimestamp>
              </verificationResult>
            </verificationResultList>
          </verificationResult>

Prüftool:

{
      "verificationId" : "STATE_CONSOLIDATED",
      "version" : 1,
      "verificationName" : "Statusprüfung der Kasse und Signatur-/Siegelerstellungseinheit",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die Zustände der Kasse und der verwendeten Signatur-/Siegelerstellungseinheit und die Ergebnisse der zuvor durchgeführten Prüfungen (vor allem der Belegtyp) ausgewertet. Handelt es sich um einen Startbeleg, wird überprüft ob eine Inbetriebnahme der Kasse möglich ist.",
      "verificationState" : "PASS",
      "verificationTimestamp" : "2017-02-22T13:59:54.525+01:00",
      "verificationResultList" : [ {
        "verificationId" : "STATE_CASHBOX",
        "version" : 1,
        "verificationName" : "Statusprüfung der Kasse",
        "verificationTextualDescription" : "Es wird der Status der Kasse zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-02-22T13:59:54.525+01:00"
      }, {
        "verificationId" : "STATE_SIGDEVICE",
        "version" : 1,
        "verificationName" : "Statusprüfung der Signatur-/Siegelerstellungseinheit",
        "verificationTextualDescription" : "Es wird der Status der Signatur-/Siegelerstellungseinheit zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-02-22T13:59:54.525+01:00"
      } ]
    } ]

**Comment by noxe** [comment]
PS: Signaturkarte und Kassa sind natürlich registriert im FON

**Comment by noxe** [comment]
Das ist die verificationResultDetailedMessage vom Webservice:

Obwohl der Startbeleg gesetzeskonform zustande gekommen ist, weist die Ihre Signatur- bzw. Siegelerstellungseinheit im FinanzOnline einen Status auf, bei dem die gesetzlich vorgeschriebene Inbetriebnahme nicht möglich ist. Für eine erfolgreiche Startbelegprüfung muss Ihre Signatur- bzw. Siegelerstellungseinheit über FinanzOnline (neu) registriert werden.

Obwohl sie online ist:

Signaturkarte  AT1 A-TRUST  22.02.2017 13:51  In Betrieb seit 22.02.2017 13:51

**Comment by noxe** [comment]
siehe auch hier: https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/328

**Comment by grazkassa** [comment]
Hallo ,
Was das Timing angeht kann es vorkommen das eure Zeit vom Server oder Client Probleme verursacht bei der Belegprüfung im FON .
Bei uns hat es geholfen zwischen anlegen und Belegprüfung ein Timeout von mindestens 30 Sekunden einzubauen .

Das zweite Problem mit der Gesetzeskonformen SE etc. hatten wir auch , dies ließ sich nur beseitigen indem wir ein zweites Zertifikat eingebunden haben und die Applikationslogik etwas abgeändert haben .

Hoffe es hilft jemanden .

**Comment by noxe** [comment]
Dürfte kein Timing Problem sein - denn die Anwendung funktioniert auf einer anderen Teilnehmer ID problemlos - nur unsere eigene funktioniert anscheinend nicht mehr...

**Comment by grazkassa** [comment]
die andere Teilnehmer ID hat auch ein anderes Zertifikat, ich würde  darauf Tippen das das Zertifikat seitens FON nicht passt oder eben Timingproblem . 
Ihr könnt ein neues Zertifikat für die TeilnehmerID einbinden, wenn es keinen anderen Weg bzw. Lösungsansatz gibt . Aber vielleicht hat jemand eine bessere Idee .

**Comment by noxe** [comment]
Naja - wir haben 2 Zertifikate, 1 Atrust Online - 1 Offline Karte mit Lesegerät. Beide wurden bereits mehrfach an und abgemeldet - und beide funktionieren nun eben nicht mehr. Offensichtlich kann aber keine eine Auskunft darüber geben - die Hotline konnte mir heute auch nicht weiterhelfen!

**Comment by noxe** [comment]
Hatte heute ein Telefonat mit Herrn Ulm - dürfte sich offensichtlich wirklich um einen Fehler im Finanz Online handeln! Ich bekomme Bescheid über den Status - vorerst hilft nur ein neues Zertifikat!

**Comment by grazkassa** [comment]
Danke für die Info !

**Comment by noxe** [comment]
Prüfung funktioniert nun wieder!

**Comment by huste** [comment]
@noxe : Gibt es eine offizielle Rückmledung seitens FinanzOnline auch, oder ist das nur ein "Glück gehabt, es ging!"?

**Comment by noxe** [comment]
Habe von Hr. Ulm (BMF) eine Mail bekommen das es wieder funktioniert!

**Comment by huste** [comment]
Bei uns geht's seit gestern auch wieder problemlos - auch hier ohne Änderungen am Programm...
