### ISSUE TITLE
Kleiner Fehler im Detailfragen-Dokument

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#35]
Im Dokument ist in Abschnitt 3.2. (Seite 41) mehrmals der Text "**Signatur**einrichtung ausgefallen" erwähnt. Dieser sollte aber laut RKSV "**Sicherheits**einrichtung ausgefallen" lauten, wie auch die ebenfalls im Dokument befindliche BASE64-Darstellung "U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg" zeigt.

**Comment by pteufl** [comment]
danke!

**Comment by enengi** [comment]
Hier noch ein Punkt, der m.E. in diesem [Detailfragen-Dokument](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/137544/2016-02-18-Detailfragen-RKSV-V1.0.pdf) besser formuliert werden könnte:

Da steht: "Die summierten Steuersätze der Bruttowerte der Positionen eines zu erstellenden Belegs ..."

Wenn man tatsächlich die Steuersätze summiert, dann sieht das vermutlich so aus:
20 % + 10 % + 13 % + 0 % + 19 % = 62 %

Aber das ist an dieser Stelle wohl eher nicht das gesuchte Ergebnis, oder?  ;-)

**Comment by asitplus-pteufl** [comment]
beide Anmerkungen wurden in V1.1 behoben. Danke!
