### ISSUE TITLE
Startbeleg - Der entschlüsselte Umsatzzähler hat einen Wert ungleich 0

### ISSUE THREAD

**Issue by jirikii** [a-sit-plus/at-registrierkassen-mustercode#350]
Hallo, es gab bereits einen Thread von heute (#344) zu einem Problem mit dem Umsatzzähler beim Startbeleg. Da sich dies aber auf den Webservice bezieht und wohl erledigt hat, da unter Produktivsystem vom Webservice kein Fehler auftritt, ein neues Issue.

Bei der Prüfung des Startbelegs meldet das Prüftool "Der entschlüsselte Umsatzzähler hat einen Wert ungleich 0." als "verificationResultDetailedMessage".

Prüfung mittels App liefert das selbe Ergebnis. Leider sieht man die "verificationResultDetailedMessage" nicht über FON / der dort speicherbaren XML-Datei. Gehe aber davon aus, dass es das selbe Problem ist. 

Habe nun mehrfach geprüft, ob der korrekte AES-Schlüssel beim Prüftool bzw. in FON eingetragen ist und auch bei der eigentlichen Verschlüsselung verwendet wird. Auch der Prüfwert vom AES-Schlüssel ist lt. FON korrekt. Weiterhin habe ich die Werte mit"decryptTurnOverCounter" aus dem Mustercode wieder entschlüsselt und das Ergebnis ist 0.

Die Implementierung ist in Java und die Verschlüsselung wurde anh. dem Mustercode erstellt. Daher stehe ich etwas auf dem Schlauch, warum dieser Fehler auftritt.

Verwendete Werte:
Maschinenlesbarer Code (Zertifikat Serien-Nr. absichtlich entfernt):
_R1-AT1_02K_E1_2017-02-22T13:32:00_0,00_0,00_0,00_0,00_0,00_JiNrfHdn8g8=_19a82872_z9TBnsF8f7E=_V0s/qGDpfj57odRS/AkqKkZc+VR6JxJkmqwS7i/WLbeFdPE/BWxwMjQmsk4fI3cW9DUS/6kh1yElT6cZ6Gcw+g==

Kassen-ID: 02K
Beleg-Nr.: E1
Umsatzzähler: JiNrfHdn8g8= (8 bytes)
AES: Ecz7oI9jNufn4KJCX11o6hztOWSzJMbmbz5ACydS4Sw=

Prüftool Ergebnis:
[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/793598/0000_cashbox_full.json.txt)

**Comment by ErichFreitag** [comment]
Da stimmt wohl tatsächlich was nicht mit der Verschlüsselung. Ich bekomme

Satz normal       =       0,00 EUR
Satz ermässigt 1  =       0,00 EUR
Satz ermässigt 2  =       0,00 EUR
Satz Null         =       0,00 EUR
Satz besonders    =       0,00 EUR
----------------------------------
  Summe           =       0,00 EUR

Turnover counter  = JiNrfHdn8g8=, Länge = 8
  Umsatzzähler    = -22.646.366.119.395.328,00 EUR

**Comment by jirikii** [comment]
Danke schon mal für die schnelle Antwort! Gehe ich auch von aus, aber finde auch keinen Fehler und so langsam sehe ich dem Wald vor Bäumen nicht mehr... 

Vor allem da die Implementierung größtenteils vom Mustercode stammt. Habe eine Testklasse aus den relevanten Funktionen erstellt, die nur den Umsatzzähler anh. fixen Werten verschlüsselt und entschlüsselt. Der resultierende Umsatzzähler in Base64 ist gleich mit dem schon geposteten aus unserer kompletten Implementierung und dieser lässt sich auch wieder auf 0 entschlüsseln...

Angehangen die Testklasse. Kann nur was ganz banales sein, Wald und Bäume...
[TestUmsatzzaehler.java.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/793768/TestUmsatzzaehler.java.txt)

PS: Eine andere Frage noch zum Umsatzzähler: Soll dieser nun als €-Cent oder ganze Hunderter, wie in einem der Dokumente (welches genau weiß ich nicht mehr...) angegeben, verschlüsselt werden? Der Mustercode arbeitet ja mit €-Cent.

**Comment by ErichFreitag** [comment]
Ich kann nur zur letzten Frage etwas sagen - die Angabe ist in Euro-Cent, also "echter Betrag" mit 2 Dezimalstellen mal 100.

**Comment by jirikii** [comment]
Vielen Dank für die Bestätigung!

Das Problem der Verschlüsselung des Umsatzzählers hat sich auch gelöst. Habe wohl ganz einfach einen Copy & Paste Fehler gemacht oder den AES-Schlüssel falsch generiert. Nachdem ich nochmal ganz von vorne inkl. Erstellung eines neuen AES-Schlüssels begonnen habe funktionierte auch die Prüfung. Am Quellcode hat sich dabei nichts geändert...

Prüfung des Maschinenlesbaren Codes / QR-Codes sowie des DEP von verschiedenen Kassen ist nun auf PASS, Umsatzzähler in €-Cent dadurch ebenfalls.
