### ISSUE TITLE
Prüftool meldet FAIL bei CRYPTO_SIGNATURE 

### ISSUE THREAD

**Issue by sub9GmbH** [a-sit-plus/at-registrierkassen-mustercode#351]
Hallo, 

ich implementiere gerade den DEP Export und bekomme vom Prüftool V1.0.0 leider keine gültige Signatur gemeldet.

Ich habe alle hier beschriebenen Fehler und Issues durch und bräuchte ein wenig Unterstützung bei der Fehlersuche. 

Ich bin strikt nach Vorgabe vorgegangen, implementiere allerdings alles in PHP nicht in Java oder C++.

Hash Eingabe für die Signatur passt, Kodierungen sollten auch passen. Das Zertifikat wird auch korrekt aus der Karte ausgelesen.

Eventuell stimmen die Daten in meinen beiden JSON Dateien nicht (cryptographicMaterialContainer.json und dep-export.json), allerdings habe ich auch da schon fast alles durchgetestet.

Vielleicht weiss jemand Rat, ich hänge meine Daten mal als Zip dran.

Vielen Dank!

[Archiv.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/794904/Archiv.zip)

**Comment by cmaxmedia** [comment]
Hab jetzt zwar nicht getestet aber gesehen, das die DEP.json leer ist. Das hatte bei mir meistens mit einem falschen AES Schlüssel zu tun. Entweder ist dieser im Materialcontainer falsch oder es wird schon beim Signieren ein anderer verwendet... 

In der Datei dep-export.json sind die Zertifizierungsstellen leer

Vielleicht mal in PHP sicherstellen, dass auch wirklich die gewünschten Daten herangezogen werden

**Comment by ErichFreitag** [comment]
Lassen sie mal den Zertifikatseintrag im DEP-Export weg, der ist nicht erforderlich (wird über den cryptographicMaterialContainer bereitgestellt).

Was gibt denn das Prüftool selbst aus? Rufen sie es mal so auf, dass das Ergebnis nicht auf die Konsole, sondern in eine danach lesbare Datei geschrieben wird, z.B. mit "java -jar ..... > test_result.txt"

**Comment by sub9GmbH** [comment]
Vielen Dank schon mal für Ihre Antworten.

Das Weglassen des Zertifikats hat nichts gebracht. Den AES Key habe ich überprüft. Die Zertifizierungsstellen kann ich weglassen dachte ich. Ich versuche das mal nachzubessern laut Issue #38 ,

Anbei noch der Output der Konsole:

[result.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/799063/result.txt)

**Comment by sub9GmbH** [comment]
Den AES Schlüssel benötige ich ja nur für die Verschlüsselung des Umsatzes. Der CRYPTO_SIGNATURE Fehler bezieht sich doch auf die Signatur. Also den letzten Wert der kompakten JWS Darstellung. Die Prüfung CRYPTO_TURNOVER_COUNTER ergibt bei mir PASS.

**Comment by ErichFreitag** [comment]
Steht eh in result.txt - sie müssen die unlimited strength policy installieren. Details dazu auf der Startseite hier im Forum.

**Comment by sub9GmbH** [comment]
Verzeihung, das war die falsche result.txt. Anbei die richtige.

[result.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/799990/result.txt)

**Comment by ErichFreitag** [comment]
Mal abgesehen von der fehlerhaften Crypto-Prüfung: in dem DEP-Export fällt mir folgendes auf:

Erster Beleg, payload:
_R1-AT0_hjaDR47RSA_10230000000004_2017-02-22T10:18:31_0,00_17,00_0,00_0,00_0,00_SDVsQkF2Q04zTDA9_64A0C242_YwrLiP94C/s=

AT0 ist kein zulässiger Provider.
Der erste Beleg muss ein Startbeleg sein, sie haben einen Umsatz vom 17,00 EUR.

Vorschlag: stellen sie das mal alles richtig, machen nochmals einen DEP-Export vom Startbeleg weiter und posten alle zusammengehörigen Daten nochmals. Bitte auch inklusive der maschinenlesbaren Codes.

**Comment by sub9GmbH** [comment]
Hallo, 

Vielen Dank erneut für Ihre hilfreichen Antworten. Das Problem lag an der Rückgabe der Signatur von der Karte. Diese war HEX kodiert, da ich die PECL Extension PCSC verwende: https://pecl.php.net/package/pcsc

Die von der PCSC Extension zurückgegebene Signatur musste ich zuerst binär kodieren.

Jetzt klappt es.
