### ISSUE TITLE
WebService Registrierung Signaturerstellungseinheit Seriennummer

### ISSUE THREAD

**Issue by cmartinek** [a-sit-plus/at-registrierkassen-mustercode#352]
Wir haben folgendes Problem:

Beim Auslesen der Seriennummer eines Zertifikats erhalten wir direkt (mittels APDU-Befehlen) die Seriennummer z.B. 0FFFFFF (hex).
Wenn diese Seriennummer mittels WebService beim Registrieren einer Signaturerstellungseinheit übermittelt wird, wird folgende Meldung ausgegeben "Mit der angegebenen Seriennummer konnte beim angegebenen Vertrauensdiensteanbieter kein Zertifikat gefunden werden."
Wenn diese Signaturerstellungseinheit jedoch manuell (über das FinanzOnline-Portal) mit der Seriennummer ohne führende Nullen (in diesem Fall FFFFFF) registriert wird, dann funktioniert einerseits die Registrierung der Signaturerstellungseinheit und andererseits die Kontrolle des Startbeleges (funktioniert auch über das Webservice, wenn im QR-Code des Startbeleges auch die Seriennummer mit führenden Nullen angegeben ist, also 0FFFFFF).

Gibt es hier ein Problem beim WebService von FinanzOnline beim Registrieren einer Signaturerstellungseinheit?
Kann davon ausgegangen werden kann, dass führende Nullen bei einer Zertifikats-Seriennummer grundsätzlich entfernt werden können (in der hex-Darstellung)?

Da wir zum Testen nur eine begrenzte Anzahl von Signaturkarten besitzen und diese nach einem erfolgreichen Registrierungsversuch (z.B. manuell über das FinanzOnline-Portal) im Testmodus für unseren FinanzOnline-Teilnehmer nicht noch einmal registrieren können, wollte ich nachfragen, welche alternative/zusätzliche Möglichkeiten es zum Testen gibt.

Ich danke schon im Voraus für die Beantwortung unserer Fragen!

**Comment by grazkassa** [comment]
Hallo 
habt ihr geschaut ob mein Belegstring die richtige VDA am Anfang steht ? Also zb. AT1 etc... 
Das muss natürlich zum Zertifikatsersteller korrespondieren

**Comment by cmartinek** [comment]
Ja, natürlich stimmt diese mit dem Zertifikatsdiensteanbieter überein.
Ich denke hier dürfte es ein Problem mit den führenden Nullen geben. Bei Seriennummern ohne diesen führenden Nullen funktioniert auch die Registrierung mittels WebService.

**Comment by grazkassa** [comment]
Alles klar , ich habe nur das gefunden im Webservice Dokument des BMF : 

zertifikatsseriennummer Seriennummer des Zertifikates:
Entweder in der Original-Kodierung
( z.B. <zertifikatsseriennummer>123456</rkdb:zertifikatsseriennummer> )
oder in Hexadezimal-Kodierung (der Präfix 0x wird nicht
angegeben) unter Angabe des Attributes hex="true"
( z.B. <zertifikatsseriennummer
hex="true">01E240</rkdb:zertifikatsseriennummer> )

**Comment by cmartinek** [comment]
Diesen Abschnitt habe ich ebenfalls gefunden.
Jedoch hat wie schon oben beschrieben die Registrierung mit der (mit einer führenden Null behafteten) Zertifikatsnummer leider nicht über das WebService durchführen lassen.

**Comment by cmartinek** [comment]
Aber ich danke schon einmal für die ersten, schnellen Hinweise!

Was genau könnte hier das Problem sein?

**Comment by cmartinek** [comment]
Bei Testübermittlungen wird ja 'AT9' für den ZDA angegeben und die Seriennummer der Zertifikats wird hier nicht überprüft.
Das bedeutet, dass das Überprüfen der Seriennummer über das WebService nur im Produktivsystem durchgeführt wird und dort getestet werden kann....

Uns ist dieses Verhalten nur bei einem Kunden im Produktivsystem bereits aufgefallen!!!

**Comment by cmartinek** [comment]
Gibt es zu diesem Thema vielleicht von jemandem noch Erfahrungen bzw. Meinungen?
Vielleicht von **asitplus-pteufl** oder **ErichFreitag**?

Ich danke nochmals für eine Rückmeldung!

**Comment by ErichFreitag** [comment]
Zumindest meinerseits: bei den Feinheiten der Smart-Card-Interfaces und jener des Webservice enden meine Kenntnisse, da ich das im Detail nicht mache.

**Comment by cmartinek** [comment]
Es lag daran, dass bei der Verwendung der .net-Implementierung des FON-WebService die Parameter 'hex' und auch 'hexSpecified' auf 'true' gesetzt werden müssen.

Ich schliesse den Thread auch hiermit ab.
