### ISSUE TITLE
Webservice Finanzonline - Nach Belegprüfung kommt immer Fehlermeldung: Es ist keine steuerliche Vertretungsvollmacht vorhanden.

### ISSUE THREAD

**Issue by jayarm** [a-sit-plus/at-registrierkassen-mustercode#353]
Hallo,

wie oben schon beschrieben kommt immer folgender Returncode 32 mit Msg:

Es ist keine steuerliche Vertretungsvollmacht vorhanden.

Wir haben 
- die Kasse registriert
- die Seriennr und den AES-Schlüssel erfolgreich an den Webservice hochladen können.

Bei der anschliessenden Belegprüfung kommt dann der Fehler.

Für Ideen wäre ich dankbar
Joe

**Comment by cmartinek** [comment]
O-Ton aus 'http://www.pqrst.at/PDFs/PQRST_RKSV_Rechtliche_Anforderungen.pdf':

"Wenn ich über den Webservice mit dem Testflag eine Signatureinheit registrieren möchte, erhalte ich 
als Rückmeldung "32 - Es ist keine steuerliche Vert
retungsvollmacht vorhanden". Eine Registrierung 
einer Kasse funktioniert hingegen. Was bedeutet
 diese Meldung und was muß ich tun, damit der 
Aufruf funktioniert?
Die Meldung bedeutet, dass im Parameter "fastn
r" eine Steuernummer angegeben wurde, für die 
keine steuerliche Vertretungsvollmacht vorhanden ist.
Dieser Parameter ist nur für Parteienvertreter vo
rgesehen. Wenn eigene Meldungen (Signatureinheit 
oder Kasse registrieren, Ausfall, Wiederinbetrie
bnahme, Außerbetriebnahme) durchgeführt werden, 
ist der Parameter "fastnr" wegzulassen"

**Comment by jayarm** [comment]
Danke, das war die Lösung.

Aber beim App-Check bekomme ich immer ein Fehler, nur weiss ich nicht, woran liegt es.

Start_Beleg :
_R1-AT1_MX1_1_2017-02-24T12:32:18_0,00_0,00_0,00_0,00_0,00_OUmILGy1Yo8Wn8fQOeit3A==_518C4EE1_UJki91b6sL4=_P7HjiDHCeKOMTF5UaP6cmkLW/nq3BUEOcJ2XHCzl+X4yeYYu1hk2ZeoJALU0v0k8KPRO/JEflXOl08KofbVq6w

AES-Schlüssel : V0lOSE9URUwtTEFOREhBVVNCUk9NTS1LTEVJTldBTFM=
Umsatz = 0

Bin ich ein bisschen Ratlos...

**Comment by ErichFreitag** [comment]
Wahrscheinlich weil im Signaturteil zwei Padding-Zeichen am Ende fehlen. Der Umsatzzähler ist mit 0 OK.
