### ISSUE TITLE
Unterschied Kassen DEP und RKSV DEP

### ISSUE THREAD

**Issue by andreasschiestl** [a-sit-plus/at-registrierkassen-mustercode#357]
Hallo!

Ich bin mir nicht ganz sicher über den Unterschied zwischen Kassen DEP und RKSV DEP. Muss dieses Kassen DEP auch für neu entwickelte Systeme (=nicht nur um RKSV erweiterte Systeme) geführt werden? Wenn ja, 

- Was ist der Unterschied zum RKSV-DEP?
- Gibt es Vorgaben zu der Struktur dieses DEP?

Vielen Dank im Voraus.

**Comment by norbert2** [comment]
Das Kassen-DEP ist jenes Protokoll, das eigentlich ohnehin schon seit einiger Zeit mitgeführt werden muss.
Muss jede verkaufte Position - also den Beleg im Detail enthalten. Allerdings gibt es dazu KEINE Form-Vorschrift.
Das RKSV-DEP ist das Protokoll, das den Beleg - ohne Detail - enthält. MIT Formvorschrift 
eben laut RKSV. Json-Format, Verschl. Umsatzzähler, Signierung, Verkettung mit vorigem Beleg. Zwingend ab 1.4.2017 vorgeschrieben.
Diese Protokolle sind für jedes Kassensystem nun obligatorisch.
Bin mir sicher,  dass es noch geschliffenere Definitionen  von unsere Profis geben wird.
Jedenfalls habe ich es genauso in meinen bestehenden Kassensystemen realisiert.
Auch nach genügend Tipps, die ich in diesem Forum erhalten habe.

**Comment by andreasschiestl** [comment]
Danke für die Antwort. Die Daten werden in meinen Fall in einer SQL-Datanbank gespeichert. Genügt es wenn als Protokoll diese Daten exportiert werden oder muss dieses Protokoll wirklich extra geführt/gespeichert werden?

Die gleiche Frage für das RKSV-DEP. Dieses wird wenn benötigt aus den in der Datenbank gespeicherten Daten erzeugt. Ist das so in Ordnung oder muss dieses bereits im vorgegebenen Format geführt/gespeichert werden.

**Comment by norbert2** [comment]
Fürs Kassen-DEP genügt ohnehin die formlose Speicherung bzw. Export in z.B. CSV-Format bei Bedarf.

Für RKSV-DEP:
Es muss NICHT in Echtzeit nach jedem Beleg im Json-Format zur Verfügung stehen.
Ich speichere die Beleg-Daten auch am SQL-Server in einer Tabelle, aus der dann ohnehin jedes Quartal dieses RKSV-DEP erstellt wird.
Zusätzlich muss es jedoch jederzeit bei Prüfungen ausgegeben werden.
Und zwar immer ALLE Sätze. 
Es gibt zwar Diskussionen wir praktikabel das im Einzel Fall ist (Betriebskantinen mit Tausenden Belegen am TAG). Ist aber eher ein Problem der Prüfer.

**Comment by andreasschiestl** [comment]
Ja die Frage von dir zum Thema splitten habe ich gelesen. Aber mit einem modernen Datenbankserver sollten da selbst einige Millionen Datensätze kein großes Problem werden. Man sollte dann bei dem Export im JSON Format nur darauf achten dass man nicht alle Datensätze in den Arbeitsspeicher ladet und die Datei nicht unbedingt im Speicher zusammenbaut und dann als ganzes abspeichert.

**Comment by ErichFreitag** [comment]
ad Kassen-DEP - nicht nur Belegdetails, sondern auch "alle anderen Vorgänge" - siehe "Datenerfassungsprotokoll" in der Kassenrichtlinie 2012.

**Comment by ztp-mino** [comment]
Bezügl. Prüfung großer RKSV DEPs: mit einer guten Crypto Library und ein bisschen Code drum herum kann man z.b. ein DEP mit 10 Millionen Belegen in etwa 30 Minuten auf einem modernen Rechner prüfen. Ich vermute, dass man da noch mehr rausholen kann. Ist aber wie gesagt Problem des Prüfers.

**Comment by andreasschiestl** [comment]
@ErichFreitag Vielen Dank für den Hinweis über "alle anderen Vorgänge". Wie speichern bei allen Datensätzen den Erstellungszeitpunkt und Benutzer, gleiches gilt für die Bearbeitung und das Löschen von Datensätzen. Datensätze werden prinzipiell auch nicht gelöscht sondern nur als gelöscht markiert und für gewisse Datensätze ist eine Bearbeitung/Löschung ab einen gewissen Zeitpunkt nicht mehr möglich. Zum Beispiel kann eine Rechnung nur solange bearbeitet/gelöscht werden, solange diese noch ein Entwurf und nicht fertiggestellt (dH automatische Vergabe von Rechnungsnummer und Rechnungsdatum) ist.

**Comment by HeinziAT** [comment]
Ich glaube nicht, dass "immer ALLE Sätze" korrekt ist.

Zitat aus § 19 Abs. 2 der RKSV: "Auf Verlangen [...] hat der Unternehmer das [DEP] **für einen vom Organ der Abgabenbehörde vorgegebenen Zeitraum** [...] zu exportieren."

Das klingt eher danach, als wäre eine von-bis-Zeitpunkt-Filtermöglichkeit verpflichtend.
