### ISSUE TITLE
Zielrechnung stornieren

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#358]
Hallo,

bei meiner Lösung verweissen die Belege auf die Zielrechnungen d.h. die Ust-Aufteilung ist auf den Rechnungen angegeben.

1)
Ist es zulässig die Ust-Aufteilung mit positiven Beträgen auf einer Stornorechnung anzuzeigen? Eine stornierte Rechnung enthält den Schriftzug "storniert", Datum der Stornierung sowie die Begründung für Storno und somit ist ganz klar dass es sich um eine stornierte Rechnung handelt.

Danke im Voraus für die Antwort

**Comment by ErichFreitag** [comment]
Nachdem die angeführten Beträge jenen der Zahlung entsprechen und ein Storno dieses umkehrt kann ich mir das nur schwer vorstellen. Auch wären dann am Beleg andere Beträge als im maschinenlesbaren Code. Ich würde es nicht befürworten.

**Comment by AlgoLinz** [comment]
Danke für die Info.
