### ISSUE TITLE
Startbeleg in FON schlägt fehl - Prüftool OK

### ISSUE THREAD

**Issue by NikolausJaeger2001** [a-sit-plus/at-registrierkassen-mustercode#359]
Hallo ich habe bei einem Kunden das Problem, das die Prüfung des Startbelegs fehlschlägt.
Bei der Prüfung mit dem Prüftool läuft alles fehlerfrei durch.

Fehler:
**Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Möglicherweise liegt auch nur ein Eingabefehler aus der FON-Registrierung vor (z.B.: beim AES-Schlüssel). Sollte dies nicht zutreffen, übermitteln Sie die nachfolgenden Beschreibungen über das Vorgehen bei der Fehlerprüfung an Ihren Kassenhersteller**

Seriennumemr der Signatureinheit und key sind korrekt eingegeben.

Das ist das Prüfergebnis in FON:
`<?xml version='1.0' encoding='UTF-8'?>
<verificationResultList>
  <verificationResult>
    <verificationId>VERIFICATION_FROM_CASHBOX</verificationId>
    <version>1</version>
    <verificationName>Prüfergebnis - Kasse</verificationName>
    <verificationTextualDescription>Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.</verificationTextualDescription>
    <verificationState>FAIL</verificationState>
    <verificationResultDetailedMessage>**Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Möglicherweise liegt auch nur ein Eingabefehler aus der FON-Registrierung vor (z.B.: beim AES-Schlüssel). Sollte dies nicht zutreffen, übermitteln Sie die nachfolgenden Beschreibungen über das Vorgehen bei der Fehlerprüfung an Ihren Kassenhersteller.**</verificationResultDetailedMessage>
    <verificationTimestamp>2017-02-25T13:36:44.785+01:00</verificationTimestamp>
    <verificationResultList>
      <verificationResult>
        <verificationId>RECEIPT_FULL</verificationId>
        <version>1</version>
        <verificationName>Detailprüfung des maschinenlesbaren Codes</verificationName>
        <verificationTextualDescription>Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.</verificationTextualDescription>
        <verificationState>FAIL</verificationState>
        <verificationTimestamp>2017-02-25T13:36:45.392+01:00</verificationTimestamp>
        <verificationResultList>
          <verificationResult>
            <verificationId>TYPE_OF_RECEIPT</verificationId>
            <version>1</version>
            <verificationName>Feststellen des Belegtyps</verificationName>
            <verificationTextualDescription>Dieses Modul und die dazugehörigen Submodule überprüfen unterschiedliche Eigenschaften des maschinenlesbaren Codes und leiten anhand dieser Eigenschaften den Belegtyp ab: Start-, Normal-, Training-, Storno- oder Nullbeleg.</verificationTextualDescription>
            <verificationState>FAIL</verificationState>
            <verificationTimestamp>2017-02-25T13:36:45.433+01:00</verificationTimestamp>
            <verificationResultList>
              <verificationResult>
                <verificationId>TYPE_OF_RECEIPT_START</verificationId>
                <version>1</version>
                <verificationName>Belegtyp: Startbeleg</verificationName>
                <verificationTextualDescription>Es werden folgende Eigenschaften überprüft: Entschlüsselter Umsatzzähler gleich 0, Verkettungswert zeigt auf die Kassen-ID, alle Werte der Steuersätze sind 0, Signatureinrichtung darf nicht ausgefallen sein.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-25T13:36:45.433+01:00</verificationTimestamp>
              </verificationResult>
              <verificationResult>
                <verificationId>TYPE_OF_RECEIPT_STANDARD</verificationId>
                <version>1</version>
                <verificationName>Belegtyp: Standardbeleg</verificationName>
                <verificationTextualDescription>Es werden folgende Eigenschaften überprüft: Mindestens ein Steuersatz-Wert muss ungleich 0 sein, es muss ein Umsatzzähler im maschinenlesbaren Code vorhanden sein (es dürfen nicht die BASE64-kodierten Zeichenketten von "TRA" oder "STO" statt dem Umsatzzähler vorhanden ein), der Verkettungswert darf nicht auf die Kassen-ID zeigen.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-25T13:36:45.433+01:00</verificationTimestamp>
              </verificationResult>
              <verificationResult>
                <verificationId>TYPE_OF_RECEIPT_TRA</verificationId>
                <version>1</version>
                <verificationName>Belegtyp: Trainingsbeleg</verificationName>
                <verificationTextualDescription>Es werden folgende Eigenschaften überprüft: BASE64-kodierter Wert "TRA" steht im Umsatzzähler, der Verkettungswert darf nicht auf die Kassen-ID zeigen.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-25T13:36:45.433+01:00</verificationTimestamp>
              </verificationResult>
              <verificationResult>
                <verificationId>TYPE_OF_RECEIPT_STO</verificationId>
                <version>1</version>
                <verificationName>Belegtyp: Stornobeleg</verificationName>
                <verificationTextualDescription>Es werden folgende Eigenschaften überprüft: BASE64-kodierter Wert "STO" steht im Umsatzzähler, der Verkettungswert darf nicht auf die Kassen-ID zeigen.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-25T13:36:45.433+01:00</verificationTimestamp>
              </verificationResult>
              <verificationResult>
                <verificationId>TYPE_OF_RECEIPT_NULL</verificationId>
                <version>1</version>
                <verificationName>Belegtyp: Nullbeleg</verificationName>
                <verificationTextualDescription>Es werden folgende Eigenschaften überprüft: Die Werte für alle Steuersätze müssen 0 sein, es muss ein Umsatzzähler im maschinenlesbaren Code vorhanden sein (es dürfen nicht die BASE64-kodierten Zeichenketten von "TRA" oder "STO" statt dem Umsatzzähler vorhanden ein), der Verkettungswert darf nicht auf die Kassen-ID zeigen.</verificationTextualDescription>
                <verificationState>FAIL</verificationState>
                <verificationTimestamp>2017-02-25T13:36:45.434+01:00</verificationTimestamp>
              </verificationResult>
            </verificationResultList>
          </verificationResult>
        </verificationResultList>
      </verificationResult>
    </verificationResultList>
  </verificationResult>
</verificationResultList>
`

**Comment by NikolausJaeger2001** [comment]
Kann es ev. sein, das nach der Registrierung in FON einige Stunden vergehen müssen bevor der Startbeleg akzeptiert wird(Aktualisierung FON Server)?

**Comment by NikolausJaeger2001** [comment]
Hatte vielleicht schon jemand ein ähnliches Problem?

**Comment by ErichFreitag** [comment]
Können sie für den Startbeleg den Code, das RKSV-DEP (Export) und den AES-Schlüssel posten?

**Comment by NikolausJaeger2001** [comment]
Danke für die Antwort. Daten nachfolgend.

**Export:**
{"Belege-Gruppe":[{"Signaturzertifikat": "","Zertifizierungsstellen": [ ],"Belege-kompakt":["eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8xXzFfMjAxNy0wMi0yNVQxMzozNDo0NF8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfb040VjJkaGxwSG89XzMxMzM4MEUyX2E0YXljLzgwL09FPQ.BTA3NSwFu5fgrxdMsEnlwir4ZLCuWw9UiT2HntPzy07oi9n8dlaTp3-5VyZOYbZ6ZbA2VfbfC5HbQnzM53DOZw"]}]}

**AES:**
9Dkvhh6oupcaR2tzKC/ABKsH+mgIcTEVQrIA/EqWdfE=

**QRCode**
![image](https://cloud.githubusercontent.com/assets/24911567/23375224/d3fb0a50-fd27-11e6-885c-ef91d0d230f6.png)

Grundsätzlich scheinen die Daten aber korrekt in Finanz-Online eingegeben zu sein. Wenn normale Belege geprüft werden, kommt folgende Meldung:

> Der vorliegende Beleg ist zwar gesetzeskonform zustande gekommen, die Registrierkasse war aber zum Belegerstellungzeitpunkt im FinanzOnline „nur“ registriert

**Comment by NikolausJaeger2001** [comment]
Nach erneutem Versuch gerade eben hat die Registrierung funktioniert!?
Es wurden seit dem letzten Versuch keine Änderungen vorgenommen.
