### ISSUE TITLE
Detailfragen Seite 22, 2.3 Beispiel Stornobeleg

### ISSUE THREAD

**Issue by csokay** [a-sit-plus/at-registrierkassen-mustercode#36]
eine Kleinigkeit:
bei den Betragsätzen ist erwähnt "beim Startbeleg per Definition". Das ist hier wohl falsch.

**Comment by csokay** [comment]
beim Trainingsbeleg ebenfalls

**Comment by pteufl** [comment]
wo sind diese textpassagen genau? danke!

**Comment by pteufl** [comment]
habe es schon gesehen (überschrift. danke).

**Comment by csokay** [comment]
![screen shot 2016-02-19 at 09 25 42](https://cloud.githubusercontent.com/assets/1814899/13170217/cd2c599a-d6ea-11e5-8cdb-6a2c21dab6d6.png)

Zur Sicherheit hier genau markiert :)

**Comment by pteufl** [comment]
wird in Version 1.1 behoben (Release voraussichtlich in der Woche vom 14.03).

Danke für den Hinweis
