### ISSUE TITLE
Exception bei Startbelegprüfung

### ISSUE THREAD

**Issue by ChristianSpath** [a-sit-plus/at-registrierkassen-mustercode#361]
Hallo zusammen!

Ich habe das Problem, dass ich beim Belegcheck eine FaultException mit der Message "Validation Error" erhalte. Mehr Info steht da leider nicht. Hier ist der Code:

```
rkdbRequest req = new rkdbRequest();
req.tid = FonSession.TID;
req.benid = FonSession.BID;
req.id = FonSession.SessionId;
req.art_uebermittlung = art_uebermittlung.T;

rkdb r = new rkdb();
req.Item = r;
r.paket_nr = getRandomNr(9);
r.ts_erstellung = DateTime.Now;

belegpruefung bp = new belegpruefung();
(req.Item as rkdb).Items = new object[] { bp };
bp.beleg = "_R1-AT1_Kasse1_2017/1_2017-02-25T21:03:13_0,00_0,00_0,00_0,00_0,00
                   _re11S+SU6Xo=_4abb09b1_bxDLUwVLSTM=";
bp.kundeninfo = null;
bp.satznr = null;

rkdbResponse resp = client.rkdb(req);

```

In der Exception steht wie gesagt nur "Validation Error" ohne InnerException oder sonstige Info.

Kann mir da bitte jemand helfen?

Vielen Dank und liebe Grüße!

**Comment by norbert2** [comment]
Nur so ein Verdacht: 
Der Schrägstrich zwischen 2017 und 1_2017 schaut mir nicht ganz passend aus.

bp.beleg = "_R1-AT1_Kasse1_2017/1_2017-02-25T21:03:13_0,00_0,00_0,00_0,00_0,00
                   _re11S+SU6Xo=_4abb09b1_bxDLUwVLSTM=";

**Comment by Flanelli** [comment]
Falls der Wert von bp.beleg den QR-String darstellen soll kann das nicht funktionieren denn es fehlt das 13-te Element, also "Sig-voriger Beleg = Verkettungswert."

**Comment by ChristianSpath** [comment]
Hallo Flanelli!

Danke für den Hinweis. Wer lesen kann ist klar im Vorteil ;). Leider hat das nichts geändert. Der bp.beleg hat nun folgenden Wert:

_R1-AT1
_Kasse1
_2017/1
_2017-02-26T10:58:17
_0,00
_0,00
_0,00
_0,00
_0,00
_re11S+SU6Xo=
_4abb09b1
_bxDLUwVLSTM=
_OMWvKJhuILARscyRIDQ2O+3UVUSQLzma/Yk8fjpvETDuQGN9gx2BCGY0Or7IF8A8QI4t0VPJ1wHgz0w/lL+7MA==

Noch eine Idee? Kann es sein, dass das Problem in der Zusammenstellung des Requests liegt und es gar nicht bis zur Prüfung kommt?

Vielen Dank und lg

**Comment by Phoniexk** [comment]
Das .NET-Framework "spuckt" deshalb keine InnerException aus, weil der Validation Error bereits durch das XSD-File ausgelöst wird, d.h. irgendein Parameter erfüllt nicht die Kriterien des XSD-Files.

z.B. wenn eben nur 12 statt 13 underscores vorkommen

Wenn die Signatur jetzt angefügt ist, bleibt nichts anderes über als alle Parameter nochmal neu zu betrachten und ggf. "dummy zuweisungen" zu machen, solange bis der Validation error weg ist.

**Comment by Phoniexk** [comment]
Möglicherweise weil "satznr = null"

**Comment by ChristianSpath** [comment]
Hallo Phoniexk!

Danke für die schnelle Antwort. Kann man das XSD-File irgendwo einsehen. Ich verwende einen ganz normalen WCF Client, der in der Solution über die Service-Referenzen automatisch erstellt wird. 

PS: Das Prüftool von A-Sit sagt, dass der Beleg OK ist.

**Comment by Phoniexk** [comment]
Also für ASP.NET kann ich die Service-Referenzen inkl. XSD files direkt über den Projekt-Explorer einsehen.

Ansonsten BMF-Homepage: https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/softwarehersteller-funktionen.html#Webservices

dort gibts einen Punkt mit XSD.

**Comment by ChristianSpath** [comment]
Phoniexk, Sie sind der Beste. Das wars! Ich hab' satzNr vorher zum Testen gleich null gesetzt!!!

VIELEN LIEBEN DANK

**Comment by Phoniexk** [comment]
Freut mich dass ich helfen konnte :)
