### ISSUE TITLE
Umsatzzähler: Änderung der Länge

### ISSUE THREAD

**Issue by andreasschiestl** [a-sit-plus/at-registrierkassen-mustercode#362]
Hallo!

Der Umsatzzähler kann ja zwischen 5 und 8 Bytes sein, sollte jedoch möglichst kurz sein um den maschinenlesbaren Code so kurz wie möglich zu halten. Nun wird der Maximalwert von ca 5,5 Mrd. € bei 5 Byte für die meisten Kassen sicher ausreichen.

Die Frage ist nun was passiert wenn die Länge nicht ausreicht? Spricht etwas dagegen die Länge des Umsatzzählers zu erhöhen? Unter Umständen auch automatisch dH intern werden 8 Byte für den Zähler verwendet und je nach Wert wird für die Kodierung zwischen 5 und 8 Bytes verwendet.

Vielen Dank im Voraus.

**Comment by ErichFreitag** [comment]
Da ja der Umsatzzähler unabhängig von der Länge immer gleich entschlüsselt werden kann wüsste ich nichts was dagegen sprechen würde, außer dem zusätzlichen Testaufwand. 6 Bytes ist übrigens auch eine gute Länge, da wird die BASE64-Codierung kürzer.

Allerdings: wenn sie 8 Bytes immer verwenden ist es auch gut. Manche VDAs haben Seriennummern, die sehr lang sind und mit Kassen-ID und Belegnummer können sie den Code ganz schön verlängern - da ist dann der Umsatzzähler auch schon fast egal.

**Comment by andreasschiestl** [comment]
Das habe ich mir auch überlegt einfach 8 Byte zu verwenden (aktuell ist es so umgesetzt).

**Comment by andreasschiestl** [comment]
Ich lass das Ticket trotzdem noch offen, da mich trotzdem interessieren würde ob eine variable Länge zulässig wäre. Eventuell gibt es ja eine Stellungnahme von offizieller Seite :)

**Comment by ztp-mino** [comment]
in #144 steht dazu etwas

**Comment by andreasschiestl** [comment]
Vielen Dank für den Verweis

https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/144#issuecomment-255786335
> Gegen eine Änderung der Länge des Umsatzzählers spricht eigentlich nichts (ob es sinnvoll ist, ist eine andere Frage), daher ist diese Prüfung nicht inkludiert.
