### ISSUE TITLE
FinanzOnline Webservice C#-Integration

### ISSUE THREAD

**Issue by RyamBaCo** [a-sit-plus/at-registrierkassen-mustercode#363]
Hallo,

ich versuche gerade den Registrierkassa Webservice in C# anzubinden. Den Webservice selber kann ich aufrufen, allerdings erhalte ich bei Aufruf noch einen Validation Error:
"cvc-complex-type.2.4.b: The content of element 'rkdbRequest' is not complete. One of '{"https://finanzonline.bmf.gv.at/rkdb":erzwinge_asynchron, "https://finanzonline.bmf.gv.at/rkdb":status_kasse, "https://finanzonline.bmf.gv.at/rkdb":status_see, "https://finanzonline.bmf.gv.at/rkdb":status_ggs, "https://finanzonline.bmf.gv.at/rkdb":rkdb}' is expected."

Mein Code dafür schaut momentan so aus:
```
at.gv.bmf.finanzonline.rkdbService service = new at.gv.bmf.finanzonline.rkdbService();
at.gv.bmf.finanzonline.rkdbRequest req = new at.gv.bmf.finanzonline.rkdbRequest();
req.erzwinge_asynchron = false;
req.tid = "meineTID";
req.benid = "Registrierk1";
req.art_uebermittlung = at.gv.bmf.finanzonline.art_uebermittlung.T;
req.id = "12312312312312123";
at.gv.bmf.finanzonline.rkdbResponse resp = service.rkdb(req);
```

Beim Request-Objekt gibt es noch ein Items-Object, das in C# ein einfaches object ist. Ich vermute, dass ich mit den Items irgendwie hantieren muss, um noch spezifische Registrierkassenparameter festzulegen. Wie mache ich das in diesem Fall? Und wo liegt im Moment mein genereller Fehler?

Für jede Hilfe bin ich äußerst dankbar!

**Comment by ChristianSpath** [comment]
Hi!

Mit diesem registriere ich die Sicherheitseinrichtung. Die anderen Requests sind ähnlich aufgebaut:

```
rkdbRequest req = new rkdbRequest();
req.tid = FonSession.TID;
req.benid = FonSession.BID;
req.id = FonSession.SessionId;
req.art_uebermittlung = art_uebermittlung.T;

rkdb r = new rkdb();
req.Item = r;
r.paket_nr = getRandomNr(9);
r.ts_erstellung = DateTime.Now;

registrierung_se se = new registrierung_se();
(req.Item as rkdb).Items = new object[] { se };
se.satznr = getRandomNr(9);
se.kundeninfo = "Test TrendFox SE";
se.art_se = art_se.SIGNATURKARTE;
se.vda_id = "AT1";
            
zertifikatsseriennummer zse = new zertifikatsseriennummer();
se.Item = zse;
zse.hex = false;
zse.Value = serialNumber;

rkdbServicePortClient client = new rkdbServicePortClient();
rkdbResponse resp = client.rkdb(req);
```

LG Chri

**Comment by RyamBaCo** [comment]
Danke! Das hilft mir sehr weiter!
Eine kleine Frage hab ich noch: Ich habe jetzt versucht, einen Request mit status_kasse loszuschicken (mit einem Fehlercode als erwartete Antwort, weil ich noch keine RK registriert habe) und krieg folgende Fehlermeldung beim Absetzen des Requests:

> {"The type WebserviceTest.at.gv.bmf.finanzonline.status_kasse was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically."}

Wenn ich ein SoapInclude oder XmlInclude nach dem Schema
```
[System.Xml.Serialization.SoapInclude(typeof(at.gv.bmf.finanzonline.status_kasse))]
```
vor die Klassendeklaration hänge hilft mir das leider nicht weiter. Und auch Herr Google war bisher nicht mein Freund. Was muss ich konkret noch anstellen, damit spezifische Request-Klassen aufgelöst werden können?

Ich schätze mal, dass es noch an einer Kleinigkeit hakt, die für all die SOAP-Experten da draußen nicht unbedingt fordern dürften 😸

**Comment by Josma** [comment]
Hi!
Eventuell ist folgendes die Ursache (war zumindest bei mir so) 
Die Statusabfragen kommen direkt in das Item Objekt des requests.
Ohne dem rkdb Teil. 
Also:
rkdbRequest req = new rkdbRequest();
....
status_kasse regKassaStatus = new status_kasse();
...
req.Item = regKassaStatus;

**Comment by RyamBaCo** [comment]
Danke für den Stubser in die richtige Richtung! Läuft jetzt!

**Comment by Artsakh1980** [comment]
Ist es überhaupt möglich das man den Service über CURL aufruft?
Ich habe versucht den Session Webservice aufzurufen, ich weiß aber nicht wie ich die Parameters (tid, benid, pin, herstellerid) übergeben kann!!
