### ISSUE TITLE
Darf die JSON-DEP-Export-Datei auch zusätzliche Felder enthalten?

### ISSUE THREAD

**Issue by HeinziAT** [a-sit-plus/at-registrierkassen-mustercode#366]
§ 19 Abs. 2 der RKSV sieht ja eine Filtermöglichkeit beim DEP-Export (zumindest nach Zeitraum) vor.

Daher wäre es doch sinnvoll, in der ausgegebenen JSON-Datei zu dokumentieren, wonach das DEP gefiltert wurde - das macht dann die Fehlersuche viel einfacher, wenn z.B. kein Startbeleg enthalten ist.

Sind zusätzliche Felder erlaubt und werden von den BMF-Prüftools ignoriert, oder ist die Datei nur dann gesetzeskonform, wenn nur exakt die in Z 3 der Anlage erwähnten Felder vorkommen?

**Comment by ErichFreitag** [comment]
RKSV § 19 (2) ist der unstrukturierte (!) Export des Kassenjournals, nicht der RKSV-DEP-Export nach § 7. Damit ist nicht festgelegt in welchem Format das erfolgen soll. Da ein Zeitraum angegeben werden soll wird meist auch der Startbeleg nicht enthalten sein - das ist aber auch nicht der Sinn des Kassenjournal-Exports.

**Comment by ErichFreitag** [comment]
P.S. zusätzliche Felder sind laut Spezifikation im § 7-Export erlaubt, das hat aber wie gesagt mit dem § 19-Export zunächst nichts zu tun.

**Comment by HeinziAT** [comment]
ad § 19: Ich verstehe, das würde Sinn machen. Ganz 100%-ig eindeutig ist es meiner Meinung nach nicht, daher werde ich die Filteroption wahrscheinlich trotzdem drinnen lassen.

ad § 7: Wo lesen Sie das heraus, das zusätzliche Felder erlaubt sind? § 7 Abs. 5 verweist auf Z 3 der Anlage, und dort steht nur "entspricht folgender Datenstruktur"....

**Comment by ErichFreitag** [comment]
ad § 19: wenn man die Anforderungen der RKSV und die Ergänzungen aus dem Erlass verbindet, erhält man einen Ansatz, was zumindest enthalten sein muss, am Ende unter Umständen auch "alles". Ein Filter ist da durchaus sinnvoll.

ad § 7: in Punkt 11 der RKSV-Anlage: "Übergabeformat für Datenerfassungsprotokoll: Belege, die an das Datenerfassungsprotokoll übergeben werden, entsprechen einer JSON-Datenstruktur die mindestens folgende Werte/Daten enthalten müssen. Der Hersteller kann hier optional weitere Daten hinzufügen. Pro Beleg müssen mindestens folgende in einer JSON-Datenstruktur gespeicherten Daten verwenden werden...". Das kann beispielsweise so aussehen (aus Unterlagen BMF/A-SIT):

![grafik](https://cloud.githubusercontent.com/assets/18228048/23401428/f05c0a84-fda7-11e6-8961-5da977d0f5ae.png)

**Comment by HeinziAT** [comment]
Oh, hübsch - ja, das ist wohl eindeutig. Vielen Dank!
