### ISSUE TITLE
regkassen-verification-receipts-1.0.0 kann Beleg nicht lesen

### ISSUE THREAD

**Issue by kralan** [a-sit-plus/at-registrierkassen-mustercode#367]
Liest meinen mit a-trust Chip signierten Startbeleg nicht:  "Error while parsing the input files."
regkassen-verification-depformat-1.0.0 hingegen liest ein DEP, das (nur) den gleichen Beleg enthält und bewertet mit "PASS".
Beiden Tools wurde der gleiche cryptographicMaterialContainer gegeben.

Ein abschließender Test mit den Beispieldaten aus example-output-1.0.0 ergab, dass auch die Beispieldaten (open system/TESTSUITE_TEST_SZENARIO_1) von regkassen-verification-receipts-1.0.0 nicht akzeptiert werden.

Was könnte die etwas unspezifische Fehlermeldung "Error while parsing the input files." auslösen?

**Comment by ErichFreitag** [comment]
Meistens fehlt beispielsweise in Parameter im crypto-File. Wenn das eine geht und das andere nicht ist es aber seltsam. Können sie die Daten hier posten?

**Comment by kralan** [comment]
Wie gesagt, die Beispieldaten aus https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/V1.0.0/example-output-1.0.0.zip (open system/TESTSUITE_TEST_SZENARIO_1) zeigen bei mir das gleiche Verhalten.

**Comment by kralan** [comment]
Achja, die konkreten Daten:
`
{"Belege-Gruppe": [
{    "Signaturzertifikat" : "",
    "Zertifizierungsstellen" : [ ], "Belege-kompakt": [ "eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9QWVRUSTAxXzM3XzIwMTctMDItMjVUMjI6NDQ6MzZfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX1lpTWhSWTgwV0pZPV80OTVmNDhkY19zNjRweUhwL1VDUT0.CgGUlVeOPicZIF56I7_G_ENiuZ6vs-oRgZEQwKGCtPZJgpKZvzZ1wMypGfG_akKZW5pbHBIm_rL2IVNdEe5tqg"]}]}
`
wird als DEP akzeptiert.

`[ "_R1-AT1_PYTTI01_37_2017-02-25T22:44:36_0,00_0,00_0,00_0,00_0,00_YiMhRY80WJY=_495f48dc_s64pyHp/UCQ=_CgGUlVeOPicZIF56I7/G/ENiuZ6vs+oRgZEQwKGCtPZJgpKZvzZ1wMypGfG/akKZW5pbHBIm/rL2IVNdEe5tqg==" ]`
als QR-code führt zu "Error while parsing the input files."

**Comment by ErichFreitag** [comment]
Da brauche ich den crypto-File auch dazu bitte.
Und bitte den ganzen Output vom Tool. Rufen sie es mit redirect auf, z.B. java -jar regkassen-verification-receipts-1.0.0.jar -f -i .\Tests\rec_a-sit_356.txt -c .\Tests\cryptographicMaterialContainer_a-sit_356.json -o .\Tests\rec_test_out > .\Tests\rec_test_out\rec_test_summary.txt, dann sehen sie in rec_test_summary die Ausgabe des Prüftools (und können es auch hier posten).

**Comment by kralan** [comment]
Der ganze, vollständige und einzige output vom Tool regkassen-verification-receipts-1.0.0.jar ist:  `Error while parsing the input files`.
Es werden auch keine Dateien erzeugt wie beim erfolgreichen Lauf von regkassen-verification-depformat-1.0.0.jar.

Beispieldaten, die das gleiche Verhalten an den Tag legen, gibt es wie gesagt hier:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/V1.0.0/example-output-1.0.0.zip (open system/TESTSUITE_TEST_SZENARIO_1)

Können Sie bestätigen, dass die "offiziellen" Beispieldaten bei Ihnen keine Probleme machen?

**Comment by kralan** [comment]
Oh, silly me! Ich hatte den `-o` Parameter anzugeben vergessen.
Danke ErichFreitag für die Zeit und Mühe.

`Error while parsing the input files` als Ausdruck eines fehlenden Kommandozeilenparameters ist allerdings auch eine Herausforderung.
