### ISSUE TITLE
Fehler beim Prüfung Startbeleg

### ISSUE THREAD

**Issue by jayarm** [a-sit-plus/at-registrierkassen-mustercode#368]
Bekomme ich folgende Fehler beim Belegprüfung:

<ns5:verificationResult>
<ns5:verificationId>**VERIFICATION_FROM_CASHBOX**</ns5:verificationId>
<ns5:version>1</ns5:version>
<ns5:verificationName>**Prüfergebnis - Kasse**</ns5:verificationName>
<ns5:verificationTextualDescription>**Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt**.</ns5:verificationTextualDescription>
<ns5:verificationState>**FAIL**</ns5:verificationState>
<ns5:verificationResultDetailedMessage>**Der vorliegende Beleg kann nicht gültig geprüft werden, da nur die eigenen Belege geprüft werden dürfen bzw. vor der Belegprüfung die belegerstellende Registrierkasse und Signaturkarte beim zugehörigen Unternehmen über FON vollständig registriert sein müssen. Außerdem müssen die Kassenidentifikationsnummer, der VDA und die Seriennummer des Signaturzertifikates im maschinenlesbaren Code mit den Daten aus der FON-Registrierung übereinstimmen**.</ns5:verificationResultDetailedMessage>
<ns5:verificationTimestamp>2017-02-27T16:20:38.967+01:00</ns5:verificationTimestamp>
<ns5:verificationResultList>
<ns5:verificationResult>
<ns5:verificationId>**MATCH_COMPANY**</ns5:verificationId>
<ns5:version>1</ns5:version>
<ns5:verificationName>**Überprüfung ob angemeldetes Unternehmen mit Unternehmen des Belegs übereinstimmt**</ns5:verificationName>
<ns5:verificationTextualDescription>**Es wird überprüft ob das angemeldete Unternehmen mit dem Unternehmen, das den Beleg ausgestellt hat, übereinstimmt. Das Ergebnis sagt aus ob das angemeldete Unternehmen berechtigt ist den vorliegenden Beleg zu prüfen**.</ns5:verificationTextualDescription>
<ns5:verificationState>**FAIL**</ns5:verificationState>
<ns5:verificationTimestamp>2017-02-27T16:20:40.553+01:00</ns5:verificationTimestamp>
</ns5:verificationResult>

Kassenidentifikationsnummer, Seriennummer, AES-Schlüssel, ATU-Nummer sind in FON schon eingetragen. 
Hat jemand Idee?

**Comment by mandihof** [comment]
Hi,
Hatte das selbe Problem.

Ist die Seriennummer der Signaturkarte auch wirklich auf die UID Nummer registriert? Bei mir war die Kassa auf eine andere UID (andere FON Zugang) registriert als die Signaturkarte-

lg

**Comment by ErichFreitag** [comment]
Falsche UID zum Zertifikat, ...

**Comment by jayarm** [comment]
Mea culpa....
Lösung : 
<art_uebermittlung>P</art_uebermittlung> 
statt
<art_uebermittlung>T</art_uebermittlung>
