### ISSUE TITLE
Fehler gültige BASE64-Zeichen

### ISSUE THREAD

**Issue by mandihof** [a-sit-plus/at-registrierkassen-mustercode#369]
Hallo Leute,
ich bekomm beim Belegcheck über FON Webservice folgende fehlermeldung retour (xml anbei)

ns5:verificationName>Formatprüfung: Gültige BASE64-Zeichen</ns5:verificationName>
<ns5:verificationTextualDescription>Es wird in diesem Modul überprüft ob die gegebene Zeichenkette nur Zeichen beinhaltet die für die BASE64-Kodierung verwendet werden dürfen.
</ns5:verificationTextualDescription>
<ns5:verificationState>FAIL</ns5:verificationState>
<ns5:verificationTimestamp>2017-02-28T11:53:22.838+01:00</ns5:verificationTimestamp>

Mein String den ich an FON sende lautet wir folgt:
_R1-AT1_DemoKassa1_1001_2017-02-28T11:54:10_0,00_0,00_0,00_0,00_0,00_j0QPGDsDKak=_4A166366_Jb6a30PGbX0=_U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg

Hat jemand eine idee was da für Zeichen vorkommen die nicht verwendet werden dürfen? Der Umsatzzähler und die Sigantur des vorheigen Beleges dürften soweit passen (Startbeleg), also kann es nur an der Signaturwert liegen. 

Grüße Manfred

**Comment by jayarm** [comment]
Nur Tipp : 
Im Signaturteil zwei Padding-Zeichen am Ende fehlen : 
U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg**==**

**Comment by ErichFreitag** [comment]
Sehe ich auch so. Außerdem - das ist ein Startbeleg (?) mit "Sicherheitseinrichtung ausgefallen"? Das wird auch nicht gut gehen...

**Comment by mandihof** [comment]
stimmt, ist der ausfall, dachte dass totzdem geprüft wird ob zumindest der aufbau passt.

wenn ich aber nun folgenden wert schick (startbeleg)
_R1-AT1_DemoKassa1_1001_2017-02-28T12:37:00_0,00_0,00_0,00_0,00_0,00_j0QPGDsDKak=_4A166366_Jb6a30PGbX0=_8XKzmdsDwbxEdtbVlQ6x6YOUY-R5P50yqVAMoooScGrAht8wczIODWf3SoQDl_UjAij0cJud9o8FieiRdGBNJg==

bekomm ich eine fehlermelung vom webservice. für die base64 url codierung muss man ja nur + und / durch - und _ ersetzt oder?

**Comment by ErichFreitag** [comment]
Schon, nur ist im QR-Code BASE64 und im DEP BASE64URL, das sieht genau verkehrt aus.

**Comment by mandihof** [comment]
okay, verstehe, danke!
leider bekomme ich nun bei diesem string
_R1-AT1_DemoKassa1_1001_2017-02-28T12:48:05_0,00_0,00_0,00_0,00_0,00_j0QPGDsDKak=_4A166366_Jb6a30PGbX0=_rm5CZWLNl7PE6XoxTv6Wd6tAAPZ9+lMYAs53r6H5qo2QP6n7/q5r2ESyjZ/q0IHxr8qKMkz8lO02+i8+pOD0Cg==

folgenden fehler
<ns5:verificationResult>
<ns5:verificationId>**CRYPTO_SIGNATURE**</ns5:verificationId>
<ns5:version>1</ns5:version>
<ns5:verificationName>
**Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur**
</ns5:verificationName>
<ns5:verificationTextualDescription>
**In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.**
</ns5:verificationTextualDescription>
<ns5:verificationState>**FAIL**</ns5:verificationState>
<ns5:verificationResultDetailedMessage>
**Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.**
</ns5:verificationResultDetailedMessage>
<ns5:verificationTimestamp>2017-02-28T12:49:37.327+01:00</ns5:verificationTimestamp>
</ns5:verificationResult>

auch die belegapp meldet mir bei diesem einen fehler, noch jemand eine idee?

**Comment by ErichFreitag** [comment]
Nur, dass es jetzt für sie ans eingemachte geht, sprich step-by-step anhand der Anleitung unter https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf den Vorgang durchgehen (Dokument ist auf der Startseite verlinkt).

**Comment by mandihof** [comment]
ich habs befürchtet, danke!
