### ISSUE TITLE
Hexadezimaldarstellung der Zertifikats-Seriennummer

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#37]
Laut Detailfragen-Dokument sind Zertifikats-Seriennummern hexadezimal darzustellen.

Nun kann es sein, dass man eine dezimale Seriennummer (wie sie z.B. von der derzeitigen Testversion der A-Trust-Mobil-Signatur geliefert wird) in das hexadezimale Format umwandeln muss. Dabei stellt sich die Frage nach der Anzahl der zu benutzenden Hex-Digits.

Gemäß RFC 5280 (<https://tools.ietf.org/html/rfc5280#section-4.1.2.2>) ist die Zertifikats-Seriennummer ein positiver Integer mit einer Länge von bis zu 20(!) Bytes. Vornullen darf man wohl weglassen, allerdings steht nirgends, ob die Zahl als _signed_ oder als _unsigned_ integer zu betrachten ist. Wird sie nämlich als _signed_ interpretiert, müsste darauf geachtet werden, dass das höchstwertige Bit (MSB) auf jeden Fall Null ist (da es sich ja um eine positive Zahl handelt). Dadurch würde bei Zahlen, deren erstes Hex-Digit >=8 ist, eine zusätzliche Vornull erforderlich. Bei Interpretation als _unsigned_ wäre dies jedoch unerheblich.

Außerdem wäre noch interessant, ob immer nur ganze Bytes dargestellt werden sollen, d.h. die Anzahl der Hex-Digits (inkl. Vornullen) immer gerade sein soll.

Beide Fragen auf den Punkt gebracht:

Nehmen wir an, die Zertifikats-Seriennummer lautet dezimal 65534. Soll sie dann als FFFE oder als
0FFFE oder als 00FFFE dargestellt werden?

Mit der im Dokument beispielhaft angegebenen Seriennummer A431623BEDF wären eigentlich beide Fragen beantwortet (keine Vornullen auch bei gesetztem MSB, ungerade Digit-Anzahl). Ich möchte aber sichergehen, dass dies tatsächlich so passt.

**Comment by A-Trust** [comment]
Hallo Lebail,

wir haben die A-Trust Registrierkasse Mobile angepasst und liefern in der neuen Schnittstelle jetzt zusätzlich auch den HEX-Wert der Zertifikatsseriennummer zurück. Somit können Sie einfach den zurückgelieferten Wert verwenden und wir passen diesen entsprechend den Anforderungen an. 

Aktuelle Dokumentation: http://labs.a-trust.at/developer/pdf/RegistrierkasseMobileDev.pdf

**Comment by lebail** [comment]
Vielen Dank!

Allerdings hat sich dadurch meine Frage dennoch nicht erledigt.

Denn ich speichere die Seriennummer nicht als Text, sondern "providerunabhängig" im Binärformat, da diese von anderen Signaturerstellungseinheiten wie z.B. der A-Trust-Chipkarte ja bereits binär geliefert wird (und ich nicht für jede Type von Signaturerstellungseinheit ein eigenes Datenformat haben möchte).

Somit geht die Information über die ursprüngliche Formatierung (z.B. ob am Beginn des Hex-Wertes eine Null stand oder nicht) verloren, und ich muss das bei der Ausgabe wieder passend formatieren.
