### ISSUE TITLE
Monatsbeleg - Belegerstellungszeitpunkt Fehler bei der Überprüfung

### ISSUE THREAD

**Issue by cmartinek** [a-sit-plus/at-registrierkassen-mustercode#375]
Hallo!

Wir haben folgendes Problem bei einem Kunden:
Registrierung der Registrierkasse und der Signaturerstellungseinheit am 22.02.2017. Startbeleg ebenfalls erfolgreich am 22.02.2017 erstellt und geprüft.

Am 28.02.2017 Erstellung eines Monatsbelegs mit folgendem Prüfergebnis:

>         <verificationState>FAIL</verificationState>
        <verificationTimestamp>2017-02-28T16:42:07.338+01:00</verificationTimestamp>
        <verificationResultList>
          <verificationResult>
            <verificationId>TIMEOFRECEIPT_WITHIN_PERIOD</verificationId>
            <version>1</version>
            <verificationName>Belegerstellungzeitpunkt innerhalb des gültigen Prüfzeitraums</verificationName>
            <verificationTextualDescription>Es wird überprüft ob der Belegerstellungszeitpunkt innerhalb des gültigen Prüfzeitraums liegt. Der Belegerstellungszeitpunkt muss größer oder gleich dem 01.09.2015 sein und darf nicht in der Zukunft liegen.</verificationTextualDescription>
            <verificationState>FAIL</verificationState>
            <verificationTimestamp>2017-02-28T16:42:07.339+01:00</verificationTimestamp>
          </verificationResult>
        </verificationResultList>

Ich werde daraus nicht schlau.
Ich bitte hier dringend um Hilfe!

Danke!!!

**Comment by ErichFreitag** [comment]
Was steht denn im Monatsbeleg bzw. im maschinenlesbaren Code?

**Comment by cmartinek** [comment]
Danke für die rasend schnelle Antwort!!!

_R1-AT1_2_13_2017-02-28T16:43:27_0,00_0,00_0,00_0,00_0,00_km7ghw4MxoWe1nUt45UIxQ==_638BEFD1_KZPeXoPTkec=_yeQPC4DO/0Uo0mS7dVfYl2lDMUv7Hz7qpbrVtCthwdVxpK16UmzcShMRmfK2qG/8DpHnLPB24EhVvUbAM8xchg==

**Comment by cmartinek** [comment]
<ts_erstellung>2017-02-28T16:44:06</ts_erstellung>

**Comment by ErichFreitag** [comment]
Ich sehe nur, dass der Beleg um 16:43:27 erstellt wurde und das Prüfergebnis etwas mit 16:42:07.339+01:00 meint (deswegen vielleicht "Beleg in der Zukunft"). Haben sie es z.B. heute nochmals versucht?

**Comment by cmartinek** [comment]
Nachdem ich jetzt alle Daten direkt im Thread untereinander sehe, kann ich mir anscheinend auch selber die Antwort geben:

Prüfzeitpunkt: 2017-02-28T16:42:07
Monatsbelegerstellungszeitpunkt: 2017-02-28T16:43:27
Übermittlung: 2017-02-28T16:44:06

Anscheinend dürfte das Datum der Kasse nicht korrekt eingestellt sein!

Sorry für die Umstände und danke für die Beantwortung!!!
