### ISSUE TITLE
Fehler in der Kryptographischen Gültigkeit 

### ISSUE THREAD

**Issue by aecoraIT** [a-sit-plus/at-registrierkassen-mustercode#379]
Hallo, 

wir bekommen leider immer wieder die selbe Fehlermeldung im Prüftool (1.0.0) zur Kryptographischen Gültigkeit der Signatur, und kommen hier leider nicht mehr weiter. 

Maschinenlesbarer Code: 
`_R1-AT1_K2_R23_2017-03-03T09:48:47_0,00_0,00_0,00_0,00_0,00_vtpxYXDoc+4=_6b432273_nj1aQBiDQds=_l/WuLeoR8DWADI0AVQD8SyoOtIXrZK2/qtI0sihGMAibsIYCAaaVpIjNKMt5kUfC9etoQa0JmwImqf465KckbA==`

CMF
```
`{
  "base64AESKey" : "ChhbDS7j5ifrbdtOg4CmqD+KZwt9CIPTt2r/3EdH568=",
					
  "certificateOrPublicKeyMap" : {
    "6b432273" : {
      "id" : "6b432273",
      "signatureDeviceType" : "PUBLIC_KEY",
      "signatureCertificateOrPublicKey" : "BNaXYo6LP6R0jBsTCOEqHgDOTOsy669Av40Bz4v4UuyMtE6alIo9kR60U-tLLHUMWsNNpMcv0E_YUUscvGjNlzQ="
    }
  }
}`
```

Prüfergebnis des Tools: 

```
`{
  "verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.",
  "verificationTimestamp" : "2017-03-03T09:55:18.478+01:00",
  "verificationResultList" : [ {
    "verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",
    "verificationTimestamp" : "2017-03-03T09:55:18.553+01:00",
    "verificationResultList" : [ {
      "verificationId" : "CRYPTO",
      "version" : 1,
      "verificationName" : "Kryptographische Prüfungen",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-03-03T09:55:18.568+01:00",
      "verificationResultList" : [ {
        "verificationId" : "CRYPTO_SIGNATURE",
        "version" : 1,
        "verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
        "verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.",
        "verificationTimestamp" : "2017-03-03T09:55:18.569+01:00"
      } ]
    } ]
  } ]
}`

```
Die Checkliste für die Signaturerstellung sind wir durchgegangen, können jedoch keinen Fehler bei der Verarbeitung oder Erstellung der Signatur finden. (https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf)

Anyone Ideas? 

Vielen Dank,

**Comment by jayarm** [comment]
Public Key ist nicht zu kurz?

**Comment by aecoraIT** [comment]
Naja, die BMF Beleg-Prüfapp liefert auch einen Fehler (Kasse ist mit den Korrekten Daten im FON registriert)

**Comment by aecoraIT** [comment]
D.h. es müsste irgendwo einen Fehler im Maschinenlesbaren Code geben?

**Comment by aecoraIT** [comment]
Wie bekommt man aus dem Zertifikat den Public Key sonst raus? Windows zeigt uns diesen wirklich so kurz an.

**Comment by jayarm** [comment]
Zertifikat -> Details -> Öffentlicher Schlüssel -> In Datei kopieren -> Base-64-codiert X.509(.CER) -> Speichern
Zwischen den "-----BEGIN CERTIFICATE-----" und "-----END CERTIFICATE-----" ist die Public Key.

**Comment by TimoKunze** [comment]
Ich habe hier das selbe Problem. Der Key, den ich mit C# auslese, ist der, den mir Windows auch anzeigt. Und dieser ist offenbar der falsche, da viel zu kurz. Exportiere ich den Key wie von jayarm beschrieben, komme ich auf einen, der die richtige Länge zu haben scheint. Aber wie komme ich programmatisch da ran?

**Comment by lebail** [comment]
X509Certificate2.RawData liefert das gesamte Zertifikat, nicht nur den Public Key. Könnte es sein, dass Ihr CryptographicMaterialContainer noch einen Fehler enthält?

"_R1-AT1" in Ihrem maschinenlesbaren Code deutet auf ein offenes System hin.

Ihr Container enthält aber:
`"signatureDeviceType" : "PUBLIC_KEY"`

Der Wert "PUBLIC_KEY" (und die Angabe nur des öffentlichen Schlüssels) ist laut Detailfragen-Dokument, Punkt 8.2, nur bei _geschlossenen Systemen_ zulässig. Bei offenen Systemen muss bei "signatureDeviceType" nicht "PUBLIC_KEY", sondern "CERTIFICATE" stehen, und es muss dann auch das gesamte Zertifikat angegeben werden (nicht nur der Public Key). In diesem Fall würde X509Certificate2.RawData tatsächlich passen.

**Comment by aecoraIT** [comment]
Hallo, 
in der Tat lag der Fehler nur im CMC. 
Lösung: signaturDeviceType auf CERTIFICATE umändern, und das ewig lange Zertifikat reinschreiben. 
Dann geht die Prüfung auf. 
Vielen Dank und Lg,
