### ISSUE TITLE
Liste der Zertifizierungsstellen

### ISSUE THREAD

**Issue by webITSol** [a-sit-plus/at-registrierkassen-mustercode#38]
Gemäß RKVS, Detailspezifikation Abs. 3 verlangt der Gesetzgeber im Exportformat des DEPs eine Liste der Zertifizierungsstellen. Wie bekommt man die über die Web Services der mobilen Signatur bzw. über APDU?

**Comment by A-Trust** [comment]
Hallo webITSol,

für die A-Trust Registrierkasse Mobile ist eine Abfrage vorhanden, diese ist im Dokument beschreiben http://labs.a-trust.at/developer/pdf/RegistrierkasseMobileDev.pdf unter "2.5 Zertifikatsinformationen abfragen". Es wird das im DEP erwartete Format zurückgeliefert. 

Für die A-Trust Registrierkasse Chip mit Zugriff über die APDU Kommandos gibt es leider keine einfache Möglichkeit. Die Zertifizierungsstellen sind nicht auf der Karte gespeichert, daher müssten Sie diese mitliefern oder aus dem Internet nachladen. Die Zertifizierungsstellen bestehen derzeitige aus einem CA-Zertifikat welches unter http://www.a-trust.at/certs/A-Trust-Registrierkasse-CA.cer erreichbar ist.

**Comment by webITSol** [comment]
Ok, danke!

**Comment by pteufl** [comment]
Bitte dazu unbedingt den Abschnitt 5 im Dokument "FESTLEGUNGEN DES BMF ZU DETAILFRAGEN DER REGISTRIERKASSENSICHERHEITSVERORDNUNG (RKSV)" https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/137544/2016-02-18-Detailfragen-RKSV-V1.0.pdf beachten.

**Comment by webITSol** [comment]
Danke für den Hinweis! Zur Ermittlung der Zertifizierungsstellen hab ich darin allerdings keine weiteren Hinweise gefunden.
Daher hier noch die Frage: Das Webservice liefert zwei Zertifizierungsstellen. Sind das nicht die selben wie jene im Falle der Verwendung der APDU? Also könnte man eine Kopie der beiden Zertifizierungsstellen auch für den Export von mittels APDU signierten Belegdaten verwenden?
Sie sagen, die Zertifizierungsstellen bestehen derzeit aus einem CA-Zertifikat. Warum liefert dann das Web Service zwei zurück?

**Comment by pteufl** [comment]
Mein Hinweis bezieht sich auf die Anmerkung und das Beispiel (...wenn kein Signaturzertifikat vorhanden...). Es ist auch zulässig - wenn die Infos nicht vorhanden sind - die Zertifikate wegzulassen. 
Die Prüfung des DEP-Protokolls ist auch ohne der Zertifikate möglich, da die Seriennummer/Ordnungsbegriffe (geschlossenes Gesamtsystem) auch im Beleg vorhanden sind.

**Comment by A-Trust** [comment]
Hallo webITSol,

sie haben recht das Testsystem für A-Trust Registrierkasse Mobile liefert derzeit noch zwei Stammzertifikate, im Echtsystem wird es dann nur eines sein. 

Für  A-Trust Registrierkasse Chip ist es (Echtsystem) nur ein Stammzertifikat. 

Somit ergibt sich auch die Frage ob die Zertifizierungsstellen von Mobile zu CHIP übernommen werden können, derzeit nicht.

**Comment by webITSol** [comment]
Ok, danke! Sollten sich noch weitere Fragen ergeben, würde ich hier anschließen.

**Comment by treh1966** [comment]
Hallo,
wir arbeiten mit APDU (eigene dll ),
wenn es ans DEP geht braucht man offenbar 2 werte:
Signaturzertifikat:
OK das kann ich mittels APDU als base64 string aus dem chip auslesen ( ist das richtig so ? )
und eben Zertifizierungsstellen: OK da habe ich aus dem obigen link eine cert datei heruntergeladen.
Was ist nun in dieser Datei enthalten ??
Reicht es wenn ich die datei in einen Binärpuffer einlese, und dann den base64 string davon ins jason einfüge ????
das wär dann in etwa:
MIIF9TCCA92gAwIBAgIDGbMrMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYDVQQGEwJBVDFIMEYGA1UECgw/QS1UcnVzdCBHZXMuIGYuIFNpY2hlcmhlaXRzc3lzdGVtZSBpbSBlbGVrdHIuIERhdGVudmVya2VociBHbWJIMSMwIQYDVQQLDBpBLVRydXN0IFJlZ2lzdHJpZXJrYXNzZS5DQTEjMCEGA1UEAwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0EwHhcNMTUwOTE3MTM1MjUyWhcNNDgwOTE3MTE1MjUyWjCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEA0AJ5s1rbkAGjvkFQp2ZVTmL9WCudNpvuuQlbWtZ/vk68hXsQhR+5T0aUtngLka7NiFBUcr3yGsGEroryK5Uk7UROqY/+uTKXPGCA5Quh/ISNXPITU2ZOJWcQOpaS/qqB+1PHBR7RY3xNlujwYtLDfH35wcwnyFBKF3Mbtl1DIf2RVpHigKQ30fD7bSZI9wOtmR1vdNZdCNMfV193CkhYe7BUHG1zuiLp2JqC0+XyUvu0890LB71SSSo4qRrSEdtSdfkq33LC5HbgjDEnu1/Kn8zGDiiA2dLU7NKzaut2OEx+HsuvY2w2mEdLnwsYLXH3aooXu3d4r3Kd38kYbDaCJUN3Mz7hGN1ng4m97u/peFUs55C+DSDKgj3LTofy8+PI/9wZr6mxhOZAMKlFH34SdRtVYHyaeHSIBWYim1ILi2aLwrx2My8iwSuGzd+PJqxhASS+rAFCghV/d+t2gql0L+4kLhiM/TDMyBvX9tdTgU0WrmnXod6BSe+QSN8ARmikoHPwTI5m+L9EiBsOPhBpZ+FyM5gDK8gE8B0LFV9g2D2u4pQYLD6iqD4Z51AJp06uVXvYy6zi/Uqw7WKBkNrvOodwezqMuBofjz24vJsa16sBkTMBzLPn42OLvYDa2gY0cLDopQYp42y3NZrXlPV6fB4krhb1pkty75aCR/xk0IMCAQOjNjA0MA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0OBAoECEBHnq7jkN+2MA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAgEATp+jNVR53dEqgaU9JDG3YcsTFJ+wBadW7g7XUJ48BzS1dN9E6SzJEJh1qH6K1pGRkgT/cW87WJYwcjHfkbqmNc+l/i1GcLnf8n0w/tu72WWuzGNMQgSMzJsZCdhp3BA5FgK1y1PVKltyrootiqUQp3BgMIEAplOAGTMp2BypZa7+gYFt2D/D/NM0mlPjKsiq9t31dVOpIKrS2WVi7WmrweGAMwiV3p2wzMIcMm9wbd2nUsjjupC18LwpUlwtcRIKmGq9kv08dQQRBA6mo9MhK7Na4dPBB5z0vdSdwXTdkupJC00iVBEutehlTgZFZ0WvEpPTUo8QJC3JTX5+4oHeoo5vypgvWbUuaNyFAoxzgeQY7G1X6BkGgTL0Hg27+XNdPDPNbl6zXpvE+KJ7vHYV68/+Vg5Ngn4jYR1OVQ7p5bIX1EhBnxvGDXxhMBdN7Ol4/JFa27l8UfCjomf6ueTfwzpuuvSko9j09lcMWp7luCJxTaUM7DMsZNPO2+SSP2pZKbWyHVK11LAlwX1DeL/3jUstoQOvEVU9LanF59hG1q42r6IxlAwrOqtDfitC/LeyuWD2AEINBj7TeRMD+yZ8UYzGaX38aGuwwgqRyhP9iZ2BjttWLRXiVEwAysmf8ym+TMbZ/PtAeLoWJXn/4JbbBVLfYp7n0P0Z4iBE3LglpCE=

Danke, BTW natürlich brennt der Hut und es ist dringend

**Comment by lebail** [comment]
Die DEP-Einträge "Zertifizierungsstellen" und "Signaturzertifikat" sind optional. Ich empfehle, dass Sie sie weglassen (so wie das hier auch viele andere tun). Das erspart viele Schwierigkeiten.

Das Signaturzertifikat brauchen Sie aber eventuell trotzdem - nämlich dann, wenn Sie Ihren DEP-Export mit dem Prüftool testen wollen. Sie können das Signaturzertifikat per APDU aus der Karte auslesen. Es kommt üblicherweise binär daher. Die BASE64-Kodierung müssen Sie dann selbst machen.

**Comment by treh1966** [comment]
Danke für den Hinweis,
Das Zertifikat der Karte kann ich auslesen, also fürs Prüftool ( sollte ich wohl anwenden bevor wir in Produktion gehen ) dann die Zertifizierungsstellen frei lassen, und die Base64 repräsentation des chip Zertifikates eintragen ?

**Comment by lebail** [comment]
Im DEP lassen Sie beide Einträge komplett weg.

Das BASE64-kodierte Zertifikat kommt in den 'CryptographicMaterialContainer.json' , das ist die Konfigurationsdatei des Prüftools. Das ist alles in dem Detailfragen-Dokument beschrieben, welches hier auf der Startseite verlinkt ist.

**Comment by treh1966** [comment]
OK, dort habe ich es ohnehin schon eingetragen,
dann also recht einfach das DEP,
die gespeicherten Signaturen ( wie man sie auch für das verketten braucht) einfach zeilenweise unter den Header hängen.
Und inm Realbetrieb beide Felder leer lassen.

**Comment by treh1966** [comment]
Ach ja im Detailfragen dokument steht eben leider nicht, daß man die Felder bei einem offenen System einfach leer lassen kann, so bin ich überhaupt erst hierher gekommen.

**Comment by asitplus-pteufl** [comment]
@treh1966 Das Weglassen gilt für beide Systeme. Es steht im Detailfragen Dokument dass die beiden Felder (Sig-Zertifikat, Zert-Stellen) optional sind. Da das Dokument mit dem BMF abgestimmt ist, einfach weglassen, es passt so.

Am besten Sie prüfen die DEPs dann mit dem Prüftool, dann sind Sie auch sicher, dass alles korrekt ist.

**Comment by treh1966** [comment]
Das Prüftool ergibt aber immer fails,
welchsn Certificate muß ich in der CryptographicMaterialContainer.json eintragen ?
das ohnehin ständig zum signieren verwendeten "Signaturzertifikat", oder das laut a-trust client "Geheimhaltungszertifikat genannte ?
Wenn zweiteres, hab ich versucht es über windows in eine .cert datei zu schreiben, aus der dann die Strings "-----BEGIN CERTIFICATE----" und "----END CERTIFICATE---" sowie die Zeilenschaltungen und "=" Zeichen entfernt und als Bse64 codierten String eingesetzt >>> Fail

**Comment by lebail** [comment]
Das Signaturzertifikat. Denn dieses ist nötig, um die Korrektheit der Signatur zu prüfen.

**Comment by treh1966** [comment]
Ich bekomme im Hauptprozess ein FAIL,
in der 000cashbox_full.json sind aber alle Unterprozesse PASS

{
  "verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Die Prüfung des Belegs konnte nicht vollständig durchgeführt werden. Vermutlich konnte das Zertifikat oder der Schlüssel mit der im Beleg angegeben Seriennummer bzw. dem angegebenen Ordnungsbegriff des Unternehmens und der Schlüssel-ID nicht in der cryptographicMaterialContainer.json Datei gefunden werden. Bitte überprüfen Sie diese Datei und die darin hinterlegten Informationen. Diese Fehlermeldung ist nur im Prüftool relevant und wird in dieser Form nicht bei der Echtprüfung über FinazOnline vorkommen.",
  "verificationTimestamp" : "2017-03-23T16:26:26.831+01:00",
  "verificationResultList" : [ {
    "verificationId" : "CONSTRAINTS_PRE_DB",
    "version" : 1,
    "verificationName" : "Minimalanforderungen an den maschinenlesbaren Code vor Detailprüfungen",
    "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden verschiedene Minimalanforderungen an den maschinenlesbaren Code überprüft bevor weitere Detailprüfungen durchgeführt werden.",
    "verificationState" : "PASS",
    "verificationTimestamp" : "2017-03-23T16:26:26.893+01:00",
    "verificationResultList" : [ {
      "verificationId" : "BASICCONSTRAINTS",
      "version" : 1,
      "verificationName" : "Minimale Formatanforderungen an den maschinenlesbaren Code",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die minimalen Formatanforderungen an den maschinenlesbaren Code überprüft.",
      "verificationState" : "PASS",
      "verificationTimestamp" : "2017-03-23T16:26:26.893+01:00",
      "verificationResultList" : [ {
        "verificationId" : "BASICCONSTRAINTS_RECEIPT_LENGTH",
        "version" : 1,
        "verificationName" : "Formatprüfung: Länge des maschinenlesbaren Codes",
        "verificationTextualDescription" : "Es wird überprüft ob der maschinenlesbare Code eine Länge von minimal 100 bis maximal 1000 Zeichen hat.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-03-23T16:26:26.893+01:00"
      }, {
        "verificationId" : "BASICCONSTRAINTS_NUMBER_OF_ELEMENTS",
        "version" : 1,
        "verificationName" : "Formatprüfung: 13 Elemente im maschinenlesbaren Code vorhanden",
        "verificationTextualDescription" : "Es wird überprüft ob 13 Elemente (Trennung durch _) im maschinenlesbaren Code vorhanden sind.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00"
      } ]
    }, {
      "verificationId" : "RKSUITE",
      "version" : 1,
      "verificationName" : "Überprüfung des Registrierkassenalgorithmuskennzeichen",
      "verificationTextualDescription" : "Es wird überprüft ob das erste Element des maschinenlesbaren Codes - das Registrierkassenalgorithmuskennzeichen - korrekt formatiert ist.",
      "verificationState" : "PASS",
      "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00",
      "verificationResultList" : [ {
        "verificationId" : "FORMAT_RK_STRING",
        "version" : 1,
        "verificationName" : "Formatprüfung: Registrierkassenalgorithmuskennzeichen",
        "verificationTextualDescription" : "Es wird überprüft ob das erste Element des maschinenlesbaren Codes - das Registrierkassenalgorithmuskennzeichen - korrekt formatiert ist.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00"
      } ]
    }, {
      "verificationId" : "FORMAT_SERIAL_NUMBER",
      "version" : 1,
      "verificationName" : "Formatprüfung: Seriennummer/Ordnungsbegriff im maschinenlesbaren Code",
      "verificationTextualDescription" : "Es wird das Format der im maschinenlesbaren Code angegeben Seriennummer des Zertifikats oder des angegebenen Ordnungsbegriffs des Unternehmens/Key-ID (geschlossenes System) überprüft.",
      "verificationState" : "PASS",
      "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00",
      "verificationResultList" : [ {
        "verificationId" : "FORMAT_HEX_CHARS",
        "version" : 1,
        "verificationName" : "Formatprüfung: Für die Seriennummer des Zertifikats wurde die korrekte Hexadezimaldarstellung verwendet.",
        "verificationTextualDescription" : "Es wird überprüft ob die Seriennummer des Zertifikats mit der korrekten Hexadezimaldarstellung kodiert ist. Diese Prüfung wird nur durchgeführt, wenn es sich um kein geschlossenes Gesamtsystem handelt.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00"
      } ]
    }, {
      "verificationId" : "FORMAT_CHECK_TIMEANDDATE",
      "version" : 1,
      "verificationName" : "Formatprüfung: Format des Belegerstellungszeitpunktes",
      "verificationTextualDescription" : "Es wird überprüft ob der Belegerstellungszeitpunkt im korrekten Format im maschinenlesbaren Code abgebildet ist.",
      "verificationState" : "PASS",
      "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00"
    }, {
      "verificationId" : "TIMEOFRECEIPT_WITHIN_PERIOD",
      "version" : 1,
      "verificationName" : "Belegerstellungzeitpunkt innerhalb des gültigen Prüfzeitraums",
      "verificationTextualDescription" : "Es wird überprüft ob der Belegerstellungszeitpunkt innerhalb des gültigen Prüfzeitraums liegt. Der Belegerstellungszeitpunkt muss größer oder gleich dem 01.09.2015 sein und darf nicht in der Zukunft liegen.",
      "verificationState" : "PASS",
      "verificationTimestamp" : "2017-03-23T16:26:26.909+01:00"
    } ]
  }, {
    "verificationId" : "MATCH_COMPANY",
    "version" : 1,
    "verificationName" : "Überprüfung ob angemeldetes Unternehmen mit Unternehmen des Belegs übereinstimmt",
    "verificationTextualDescription" : "Es wird überprüft ob das angemeldete Unternehmen mit dem Unternehmen, das den Beleg ausgestellt hat, übereinstimmt. Das Ergebnis sagt aus ob das angemeldete Unternehmen berechtigt ist den vorliegenden Beleg zu prüfen.",
    "verificationState" : "PASS",
    "verificationTimestamp" : "2017-03-23T16:26:26.924+01:00"
  } ]
}
