### ISSUE TITLE
Kunde mit wechselnden Zertifikaten

### ISSUE THREAD

**Issue by Martin78** [a-sit-plus/at-registrierkassen-mustercode#380]
Wir bieten Verleihkassen an.
Ein Beispiel könnte so aussehen:
- Kunde X bekommt beim ersten mal 5 Signaturkarten von A-Trust, alle mit der gleichen Steuernummer
- Kunde leiht 5 Kassen von uns. Es werden die 5 Startbelege erstellt, Signaturkarten eingetragen usw.
- Der einfachheithalber nehmen wir 1 AES Key für diesen Kunden für alle 5 Kassen.
- jetzt leiht dieser Kunde zu einem späteren Zeitpunkt wieder Kassen von uns und wir spielen die alten DEPs wieder ein und machen weiter.

FRAGE: Müssen die A-Trust Karten genau wieder mit den DEPs der Kassen zusammenstimmen? Oder Kann ich Karte 2 für Kassa 1 mal verwenden und mal umgekehrt?

Im DEP ist Kassen ID gespeichert. 

Akzeptiert das Prüftool ein gesamten DEP Export wo unterschiedliche Zertifikate verwendet wurden? Info: wir lassen das Feld "Signaturzertifikat" und "Zertifizierungsstellen" im Json Export weg da sie ja optional sind.

Ich frage deshalb da wir den Aufwand bei Verleihkassen so gering und einfach wie nur möglich halten wollen. Also DEP auf irgendeiner Kasse aufspielen, irgendeine Karte des Kunden einstecken und geht schon.

**Comment by ErichFreitag** [comment]
Bezüglich Zertifikaten ist es egal. 

Empfehlen würde ich vielleicht noch, bei/nach der Auslieferung einen Kontroll-Null-Beleg zu erstellen und diesen via Belegcheck-App zu prüfen. Dann sind sie auch sicher, dass sie ein richtiges Kundenzertifikat verwenden und dass die Kasse ordnungsgemäß in Betrieb ist. Gegebenenfalls auch einen zur Dokumentation bei Rückgabe.

Mit der Prüfung der Jahresbelege und der DEP-Sicherung pro Kasse und Kunde müssen sie sich halt was überlegen.

**Comment by Martin78** [comment]
Das heißt ich muss immer das gleiche Zertifikat verwenden?

Bei Verleihkassen ist der Arbeitsaufwand schon eine menge mit der Sigantur! 
Jeden nur irgendwie unnötigen Schritt wie protokolieren der Karten möchten wir uns sparen!

**Comment by ErichFreitag** [comment]
Nein, sie müssen nur ein dem Kunden zugeordnetes, registriertes und funktionierendes Zertifikat verwenden.

**Comment by Martin78** [comment]
ok, super. danke für die rasche klärung!
