### ISSUE TITLE
DEP Prüftool Fehlermeldung

### ISSUE THREAD

**Issue by Martin78** [a-sit-plus/at-registrierkassen-mustercode#382]
Ich habe bei einem Kunden einen Startbeleg erstellt ein paar normale Belege und Storno belege.
Dann einen DEP Export und mit dem Prüftool verifiziert.
Das Ergebnis schlägt beim ersten Beleg fehl, die restlichen passen.

Wie kann ich diese Fehlermeldung interpretieren?

Den Crypto Container mit Serial Number, AES Code usw. möchte ich hier nicht öffentlich posten da es sich um ein Realsystem handelt.

Fehlermeldung siehe Output File.

[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/818801/0000_cashbox_full.json.txt)

**Comment by aecoraIT** [comment]
Was sag die Belegprüf-App des BMF dazu? 
Die Fehlermeldung `      "verificationResultDetailedMessage" : "Die Input-Parameter sind unvollst‰ndig. Mindestens ein Parameter ist leer: {1}",` weisst eher darauf hin, dass im CMC was falsch angegeben wurde. 
Und sonst, handelt es sich um ein geschlossenes System oder ein offenes System? 
Geben Sie im CMC den Public Key an, oder das gesamte Zertifikat? 
Interessant für die Fehleranalyse wäre schon auch das DEP und das CMC gewesen, da wird sonst nur raten können..

**Comment by Martin78** [comment]
Es handelt sich um ein offenes System.
im CMC ist der Public Key drinnen:
sieht so aus (AES Key geändert)
`{
  "base64AESKey": "hier steht der AES Key",
  "certificateOrPublicKeyMap": {
    "251ca73b": {
      "id": "251ca73b",
      "signatureDeviceType": "CERTIFICATE",
      "signatureCertificateOrPublicKey": "MIIFNzCCAx+gAwIBAgIEJRynOzANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDMwNDEyMjY1M1oXDTIyMDMwNDExMjY1M1owPjELMAkGA1UEBhMCQVQxGDAWBgNVBAMMD1VJRCBBVFU2MTMxMjY5OTEVMBMGA1UEBRMMNTQxMDM1NDM2NTQ1MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHEn1Gjigd3nbuG20o2CG8FK4cWonobeLfJpdBdo4mFdYvWTbic+Yn9sleORqJWM88Kn1fcleFI0pgOKMK6XAEKOCAaIwggGeMH8GCCsGAQUFBwEBBHMwcTBGBggrBgEFBQcwAoY6aHR0cDovL3d3dy5hLXRydXN0LmF0L2NlcnRzL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlLUNBLmNlcjAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQEAwIGwDARBgNVHQ4ECgQIT6ZwHV+0bUowRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybC5hLXRydXN0LmF0L2NybC9BLVRydXN0LVJlZ2lzdHJpZXJrYXNzZS5DQTAJBgNVHRMEAjAAMFgGA1UdIARRME8wTQYGKigAEQEYMEMwQQYIKwYBBQUHAgEWNWh0dHA6Ly93d3cuYS10cnVzdC5hdC9kb2NzL2NwL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlMBMGA1UdIwQMMAqACEBHnq7jkN+2MBkGA1UdEQQSMBCBDnN0by4xMDBAZ214LmF0MBwGByooAAoBCwEEEQwPVUlEIEFUVTYxMzEyNjk5MA0GCSqGSIb3DQEBCwUAA4ICAQAc5iWJDEaFZryNycsIz3R+sdRnC4vKlVUnINdtqAoz0fDKSOjrfsPRmiozGJKGiF5FDGjM/6xDYvpYEzSz9v99aMPocn1vT61bOrk1oqfHKcE2G+dj+I6mu9DpcvvVx909pZiDFrW5i6Lgintb9N9QY41e5S9ErfIFfxDIgta+WQqtBGhZ249sEnn2nD2GnxU5zFgeQn9Mn0rvAgYhZQycpOEaES1H5hNScN2LZeL5AbBXvwrEfyL21lZJW8JXAMyG9pKCfYKQ6oLu13bBE02tSSgWC8FNC/mUV7x9rxdVPpK+DLpeqDX4YI19O7oJhPVuZXUuD4Tx09hABBJHWNEAECUVb/no5J/DVKeiYSJuqZcgXyO4d7JArwcYflu5/5pCY3q/4awSbdmFQiyIO8Eno4Krkf+SG1xpV177Bus/z46WtILR9mT/ZQkPy/yoG/Pu/hacaFE5PAd8KWfJGCDksQy28+8ZuEXdltE6iGroTEFFaHA2Hz1V0a/KNnM2EXDaf4GGDXuoR8TrbKshwp2NPt1ptXlBAJaNYcgnK3ecO86EU2s//bkO4yclFyd++PHFCg534L+NoqWcSy8B3PZNhTOlh5M0f9MSU2L/uE31fek3o7MY3fhhSR6/9+sh2i2XjAPy+zf9p393DxKRRa7Na+KdmGkAsDh50ZGtyHTh0A=="
    }
  }
}`

Das DEP befindet sich im Anhang:
[DEP.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/819244/DEP.json.txt)

Interessant wäre der Source Code des Prüftools bzw die detailierte Beschreibung der Checks da ich mit den Fehlermeldungen oft nicht viel anfangen kann...

**Comment by ErichFreitag** [comment]
Der erste Beleg ist ein Startbeleg und wurde mit "Sicherheitseinrichtung ausgefallen" erstellt - das ist nicht zulässig.

**Comment by Martin78** [comment]
ok, das stimmt. das wusste ich nicht das das nicht zulässig ist. der 2te beleg ist nämlich der korrekte startbeleg...
Sowas könnte das Prüftool schon etwas genauer beschreiben...
