### ISSUE TITLE
Anwendung des Prüftools bei SE ausgefallen

### ISSUE THREAD

**Issue by wpichler** [a-sit-plus/at-registrierkassen-mustercode#383]
Hallo,

ich habe gerade folgendes versucht:
- Startbeleg
- Jahres Null Beleg
- Monats Null Beleg
- Standard Beleg

dann mit dem Prüftool geprüft - alles in Ordnung

Jetzt SE raus - Kasse in den Ausfall SE Modus geschalten

- Standard Beleg

Jetzt habe ich wieder geprüft - und habe einen kompletten Fail bekommen

Lange gesucht - nichts gefunden

Also SE wieder rein - System erstellt

- Null Beleg

Wieder Export der Daten

Prüftool prüft den DEP - alles Ok

Kann das Prüftool nicht mit dem DEP umgehen wenn das aktuell im Ausfall Status sich befindet ?

**Comment by ErichFreitag** [comment]
Siehe Startseite - derzeit werden noch alle Nullbelege als signierpflichtig angesehen. Beantwortet das die Frage?

**Comment by wpichler** [comment]
Nicht ganz - ich hatte das schon gelesen. Mein Fall ist ja anders - der nicht signierte Beleg ist ja kein Null Beleg - sondern ein Standard Beleg (nur halt mit Signatureinheit ausgefallen - also header.payload.base64url(Signatureinheit ausgefallen).

**Comment by ErichFreitag** [comment]
Dann posten sie bitte mal die Fehlermeldung, eventuell auch die geprüften Daten.

**Comment by wpichler** [comment]
Ich habe mir das entsprechende DEP leider nicht aufbehalten - und konnte es jetzt nicht mehr reproduzieren. Ich schließe das Issue damit - falls ich es wieder reproduzieren kann öffne ich es wieder
