### ISSUE TITLE
Gutscheine

### ISSUE THREAD

**Issue by wpichler** [a-sit-plus/at-registrierkassen-mustercode#384]
Hallo,

es gibt dazu schon das Issue #9 - hier also nur nochmals um sicher zu gehen.

Lt. dem Issue darf ein Gutschein den Umsatzzähler nicht erhöhen - da der Umsatzzähler erst mit der Einlösung des Gutscheins (Gutschein = Zahlungsmittel) erhöht wird (dann natürlich auch mit den richtigen Steuer Werten.

Ich habe das jetzt also so implement - es wird ein Gutschein um 100€ verkauft - Kunde kauft sonst nichts - also 100€ Barumsatz minus den 100€ Gutschein - ergibt natürlich keine Erhöhung des Umsatzzählers - somit wertet das Prüftool den Beleg als Null Beleg.

Kann das so belassen werden ?

**Comment by ErichFreitag** [comment]
So einfach ist es leider nicht.

Wertgutschein: ist beim Kauf ein Zahlungsmittel, daher kein Barumsatz. Darf freiwillig im 0% Steuersatz signiert werden, muss im 0%-Steuersatz mitgeführt werden, wenn gemeinsam mit anderen Artikeln verkauft. Einlösung = Zahlungsmittel wie Bargeld.

Leistungsgutschein: USt beim Verkauf = Barumsatz, bei Einlösung kein Barumsatz.

Damit auch immer bei Mitführung Änderung des Umsatzzählers.

**Comment by wpichler** [comment]
Danke für die rasche Antwort - mir ist es leider immer noch nicht klar (Programmierer halt...)
Das habe ich aus den anderen Issues auch schon rausgelesen - was mir aber nicht ganz eindeutig da hervorkommt ist:

Der Wertgutschein darf freiwillig im 0% Steuersatz mitsigniert werden - d.h. der Umsatzzähler wird beim Verkauf des Wertgutscheins erhöht - und erhöht sich nochmals bei der Einlösung des Wertgutscheins. Mir ist klar das das für das Finanzamt kein Problem ist - da eh 0% - und in der Buchhaltung muss man das sowieso extra Buchen - aber der Umsatzzähler soll doch auch für weitere Kontrollen verwendet werden, oder ?
Zweiter offener Punkt dazu - wenn ich mich jetzt entscheide den Wertgutschein nicht mit zu signieren - und einfach diesen abziehe - dann entsteht (wenn sonst nichts verkauft wurde) ein Null Beleg. Soll dieser Null Beleg so erstellt werden ? Oder soll das dann gar nicht signiert werden - Oder - am Besten einfach immer mit signieren ?

Beim Leistungsgutschein ist die Sache klar - ist im Endeffekt wie ein normales Produkt zu behandeln

**Comment by ErichFreitag** [comment]
Zunächst zählt der Umsatzzähler den Umsatz nicht exakt, sondern ist Teil der Sicherheitseinrichtung. Das wohl bessere und auch hin und wieder zu lesende Wort stattdessen ist "Summenspeicher". Dann wird auch klarer, dass Umsätze, die beispielsweise im 0%-Steuersatz freiwillig mitsigniert werden, auch den Umsatzzähler erhöhen, aber nicht den eigentlichen Umsatz betreffen.

Und dann wird das vielleicht auch mit den Gutscheinen ein wenig klarer. Ein Wertgutschein ist nur ein Tausch eines Zahlungsmittels, wo noch nicht klar ist, wofür er genau verwendet/eingelöst wird. Es erhöht sich zwar der Bargeldbestand, aber nicht der Umsatz. Man darf den Verkauf eines Wertguscheines alleine freiwillig signieren, man muss ihn im 0%-Steuersatz signieren, wenn er gleichzeitig mit anderen Artikel gekauft wird. Bei der Einlösung ist er lediglich Zahlungsmittel und wird genauso behandelt, wie wenn mit Bargeld bezahlt wird. Zusätzlich kommen meist Informationen wie "mit welchem Gutschein wurde bezahlt" (vergleichbar mit der Nummer einer Bankomat- oder Kreditkarte) und dem eventuellen Restwert hinzu.

Am einfachsten ist es daher, Wertgutscheine beim Verkauf immer im 0%-Steuersatz anzuführen, da ansonsten nochmals eine Entscheidungslogik benötigt wird, ob alleine oder gemeinsam mit anderen Artikeln verkauft wird. Es wird damit auch nichts abgezogen oder ähnliches.

Mit dem "Leistungs"-Gutschein wird schon beim Verkauf präzisiert, wofür man diesen einlöst. Dann ist auch der Verkauf ein Umsatz in den entsprechenden Steuersätzen. Bei der Einlösung findet daher kein Umsatz mehr statt, sondern es wird lediglich die Leistung dafür erbracht - beispielsweise eine Eintrittskarte in ein Theater.

**Comment by wpichler** [comment]
Besten Dank für die ausführliche Erklärung - jetzt ist alles klar (ich hatte es mit dem Umsatzzähler alias Summenspeicher wohl ein wenig zu gut gemeint...)

**Comment by Flanelli** [comment]
Ich erlaube mir einmal die wohl allereinfachste Lösung bzgl. Berkauf von Wertgutscheinen zu skizzieren.
Voraussetzung ist natürlich eine Software die diesen Vorgang ermöglicht aber das sollte wohl - einerlei wie
komplex eine Applikation konzipiert ein Klacks sein.
a) Wertgutscheinverkauf wird generell nicht mit anderen Produkten in einem Beleg gemischt
b) Wertgutscheinverkauf wird generell nicht signiert
c) Wertgutscheinverkauf wird in detailiierten DEP wie ansonsten auch ausgewiesen
e) Wertgutscheinverkauf wird beim Einlösen als Barzahlung behandelt und signiert.
Fazit:
Nie ein Problem mit der RKSV
Ist der Gutschwert höher als die Kaufsumme kann somit auch ohne weiteres Nachdenken
ein Folgegutschein mit dem Restbetrag ausgedruckt werden der wiederum natürlich nicht signiert ist.

**Comment by wpichler** [comment]
Die Lösung finde ich jetzt nicht einfacher - da muß man ein komplettes eigenes Handling für die Gutscheine erstellen - und man bricht auch den Arbeitsablauf an der Kasse.
Wenn der Wertgutschein einfach als Produkt mit 0% erfasst wird - dann benötigt es keine weiteren Programmierungen - und auch für den Kassierer ändert sich nichts

**Comment by lebail** [comment]
Auch wenn man das Erstellen getrennter Belege natürlich automatisieren könnte, würde dann auf keinem der beiden Belege die Gesamtsumme des Einkaufes stehen.

Das könnte an der Supermarktkasse problematisch werden. Zumal ich davon ausgehe, dass recht viele Produkte als Wertgutscheine zu betrachten sind (Mobilfunk-Ladebons, Gutscheine für Amazon, iTunes etc.).

**Comment by Flanelli** [comment]
@lebail 
Mit Verlaub gesagt - Sie sollten den Begriff des Wertgutscheines noch einmal überdenken.
Gutscheine für Handys, Amazpn, ect. also für Leistungen die Sie ja nicht beim Unternehmen das
ihnen diese Gutschein verkauft hat sondern bei jenem das die Leistung dafür erbringt haben mit
einem Wertgutschein des Geschäftes in dem sie diesen kaufen absolut nichts zu tun.
Würde also eine Trafik oder ein Schuhgeschäft ihnen einen Handyaufladebon verkaufen und dieser
Cerkauf würde nicht signiert und nicht als echter Umsatz und nicht cersteuert werden - na dann Gute Nacht.

**Comment by wpichler** [comment]
Gutscheine für Amazon und Co. sind da ein guter Punkt - mit welchem Steuersatz werden solche Gutscheine eigentlich behandelt ? Ich konnte auch die schnelle da nichts finden

**Comment by ErichFreitag** [comment]
Ein wenig als Leitfaden:

Bon für Handyaufladung - "Leistungs"-Gutschein, da die zu erbringende Leistung festgelegt ist

Gutschein für Amazon - vermutlich Wertgutschein, wenn sie damit beliebige Artikel in unterschiedlichen Steuersätzen kaufen können.

**Comment by lebail** [comment]
@ErichFreitag: Danke. Ich weiß, es ist off-topic, aber ich muss trotzdem noch einmal nachfragen:

Ist beim Bon für Handyaufladung die Leistung wirklich festgelegt? Man kann damit verschiedene Dienste mit unterschiedlichsten Preisen in Anspruch nehmen (Telefonie Inland/Ausland, SMS, Daten, Zusatzleistungen des Anbieters, Mehrwertdienste von Fremdanbietern). Die meisten Leistungen unterliegen 20% USt., aber z.B. bei Mehrwertdiensten kann man andere USt.-Sätze wohl nicht im Vorhinein ausschließen.

Ein Handy-Ladebon, den ich vor kurzem gekauft habe, wurde jedenfalls mit 0% USt. ausgewiesen, also wohl als Wertgutschein.

**Comment by ErichFreitag** [comment]
Das kann ich für diesen Fall nicht konkret sagen. Ich dachte an einen Bon, mit dem ich z.B. 20 EUR Guthaben auf ein Wertkartenhandy aufladen kann und damit die Leistung präzisiert ist . Welche USt-Sätze Mehrwertdienste haben ist mir auch nicht bekannt.

Wenn die Leistung jedoch nicht festgelegt ist, dann ist es ein Wertgutschein.

Und jetzt kommt noch hinzu, dass das möglicherweise auch ein durchlaufender Posten mit Vereinnahmung und Verausgabung in fremden Namen und auf fremde Rechnung ist und daher im 0%-Steuersatz ausgewiesen wird - gerade eben ein Handyaufladebon in einer Trafik beispielsweise.

**Comment by lebail** [comment]
Vielen Dank!

Dass es sich bei allen von mir genannten Beispielen eventuell um durchlaufende Posten handeln könnte, ist mir mittlerweile ebenfalls bewusst geworden. In diesem Fall wären sie dann auch aus _diesem_ Grund nicht signierungspflichtig (oder eben freiwillig im 0%-Satz anzugeben).
