### ISSUE TITLE
Nullbeleg nach Ausfall der Signatureinheit

### ISSUE THREAD

**Issue by ggoelles** [a-sit-plus/at-registrierkassen-mustercode#389]
Wenn eine Rechnung erfasst wird und davor die Sigatureinheit ausgefallen war (Signatur jetzt wieder möglich):
Erhält der Sammelbeleg dann quasi die Belegnummer der erfassten Rechnung und die Rechnung rückt eine Belegnummer vor?

**Comment by ErichFreitag** [comment]
Nein, der Sammelbeleg wird wie jeder andere Beleg behandelt - hier eingeschoben - und erhält seine eigene laufende Belegnummer. Das kann vor dem ersten wieder-signierbaren Beleg erfolgen (technisch meist schwieriger) oder nach dem ersten wieder-signierbaren Beleg.

**Comment by ggoelles** [comment]
Danke!
