### ISSUE TITLE
Kryptographische Gültigkeit

### ISSUE THREAD

**Issue by webITSol** [a-sit-plus/at-registrierkassen-mustercode#39]
Bei der Ermittlung der Signatur für den ersten Beleg über das WebService "Plain" bekomme ich bei der Überprüfung die Meldung, dass die Kryptographische Gütigkeit nicht gegeben ist. Was kann da das Problem sein?

```
String aesKey = "qmc1H0Zp34dFe5q5ai7au5JUovH2Ip78B8YMsawIx/g=";
String kassenId = "1";

String encTurn = belegDto.getBase64EncryptedTurnover(aesKey, kassenId);
// Umsatz: 0  => encTurn: wBuMAAdZM4c=

String certId = "963246667"; // von Web Service

String jwsFragPrev = RksvBusiness.calculateSignatureValuePreviousReceipt(RKSuite.R1_AT0, kassenId); // 1. Beleg => jws=kassenId="1" => jwsFragPrev: qdXooXdnO+I=

String dataToBeSigned = belegDto.getDataToBeSigned(RKSuite.R1_AT0, aesKey, kassenId); // dataToBeSigned: eyJhbGciOiJFUzI1NiJ9._R1-AT0_1_1_2016-02-24T10:42:13_0,00_0,00_0,00_0,00_0,00_wBuMAAdZM4c=_963246667_qdXooXdnO+I=

String signature = jwsModule.signMachineCodeRepOfReceipt(dataToBeSigned); // WS plain
// jwsCompact = jwsHeaderBase64Url + "." + jwsPayloadBase64Url + "." + signature
// jwsCompact: eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMF8xXzFfMjAxNi0wMi0yNFQxMDo0MjoxM18wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfd0J1TUFBZFpNNGM9Xzk2MzI0NjY2N19xZFhvb1hkbk8rST0.gH1s97FvcWvBp+BhZMQb0Eb2d1NgSP0XqGsW+P0vLWL6No8cDq1e2VX3R884Kb600qMZkUN6ksENbsBzFrof0g==

```

**Comment by A-Trust** [comment]
Hallo webITSol,

im Handbuch zur A-Trust Registrierkasse mobile (http://labs.a-trust.at/developer/pdf/RegistrierkasseMobileDev.pdf) im Kapitel 5.3 Signatur Plain ist der Vorgang beispielhaft dargestellt. 

In den Kommentaren zu ihrem Code wäre der Wert dataToBeSigned falsch, der Wert nach dem Punkt (JWS Payload) müsste vor dem signieren ebenfalls Base64-URL codiert sein.

**Comment by webITSol** [comment]
Danke für die Rückmeldung! Es funktioniert leider immer noch nicht. (Kryptographische Gültigkeit nicht gegeben.)
Das Ergebnis, das das WS Plain zurückliefert ist ja schon BASE64 codiert, oder nicht?
Dass die Zertifikatsseriennummer als Integer in der Payload ist (nicht als Hex), stimmt auch, oder?

**Comment by pteufl** [comment]
Haben sie bei der Java VM die Sie für das Prüftool verwenden, die Unlimited Strength Policy Files installiert?

**Comment by webITSol** [comment]
Ja, die Prüfung eines mit der Signatur aus dem Musterbeispiel signierten Belegs liefert auch ein positives Ergebnis.
Haben Sie vielleicht ein über das Web Service signiertes einfaches Beispiel nach dem obigen Schema, wo die Prüfung der kryptographischen Gültigkeit der exportierten Daten ein positives Ergebnis liefert?

**Comment by A-Trust** [comment]
Wir sind gerade dabei das Problem zu rekonstruieren und zu beseitigen. Ich melde mich sobald wir eine Lösung gefunden haben.

**Comment by webITSol** [comment]
Super, danke!

**Comment by A-Trust** [comment]
Bei uns funktioniert die Signaturprüfung jetzt, versuchen Sie es bitte noch einmal.

Noch zwei Anmerkungen zu ihrem Code-Beispiel: 
* Sie verwenden R1-AT0 welches für geschlossene Systeme reserviert ist. Die A-Trust Registrierkasse mobile bietet einen Befehl ZDA-Informationen abfragen (Kapitel 2.6), dieser liefert den richtigen Wert für Ihre Signatur zurück. Derzeit AT1 -> R1-AT1
* Der Aufruf WS plain liefert die Daten bereits in base64_url kodierter Form zurück. Falls Sie in der QR-Code Repräsentation prüfen müssen Sie die Signatur einmal in Base64 (normal) umkodieren.

**Comment by webITSol** [comment]
Hat funktioniert, danke!
