### ISSUE TITLE
Monatsbeleg Fehlerhaft - was nun?

### ISSUE THREAD

**Issue by marioboehm** [a-sit-plus/at-registrierkassen-mustercode#392]
Hallo A-Sit, hallo Community!

Wie ist zu verfahren, wenn die Belegprüfung (welche ja verpflichtend ist) eines Monats- / Jahresbeleges fehlerhaft ist.
Die Behandlung von Fehlersituationen bei der Starbelegprüfung ist im Erlass vom 08.04.2016 unter 3.5.3.3 genau geklärt, jedoch nicht bei den restlichen 0-Belegen.

Mich als Softwarehersteller interessiert hier hauptsächlich, ob dann die Kasse zu sperren ist, oder dann auch einfach mit "SigEinheit ausgefallen" weitergearbeitet ist, oder oder....

danke!

Mario

**Comment by Phoniexk** [comment]
Erstmal ist die Belegprüfung nur für den Start- und Jahresbeleg verpflichtend, "normale Monatsbelege" müssen nicht geprüft werden.

Naja zuerst sollten Sie schauen warum die Belegprüfung des Jahresbeleges fehlschlägt.

Wenn sich der Fehler beheben lässt > Fehlerkorrektur > Belegprüfung erneut > PASS > weiterarbeiten. z.B. fehlerhafte Daten im FinanzOnline , weil z.B. der Kunde fälschlicherweise durch herumklicken die Kasse/Zertifikat außer Betrieb genommen hat.

Kann der Fehler nicht mehr behoben werden, dann Kassa außer Betrieb nehmen und es muss eine neue eingrichtet werden.

Solange die SEE korrekt funktioniert, ist "Sicherheitseinrichtung ausgefallen" ist in meinen Augen komplett falsch. Es ist ja kein Fehler der SEE sondern der Beleg ist fehlerhaft.

**Comment by marioboehm** [comment]
Hallo @Phoniexk !

Danke erstmal. Komischer Weise hatte ich irgendwo gelesen, dass auch der Monatsbeleg geprüft werden muss. Finde aber dazu jetzt keine rechtliche Grundlage mehr. Vl. hat sich das die letzten Monate geändert? oO

Na dann wäre mal das größte Problem erledigt. Weil dann wäre theoretisch 12x im Jahr die Situation möglich, dass die Belegsprüfung fehlerhaft ist und ich dem Kunden das Weiterarbeiten verbieten muss. Das würde den z.B. am 01.07.2017 nicht freuen, wenn die Kasse sagt "nein nein". 1x im Jahr ist das schon zumutbar. Speziell wenn man sich mit den Feiertagen den Jahresabschluss einplanen kann.

Dann wäre das so einmal geklärt. Lasse das noch 1 day offen falls jemand ne Kluge antwort reinposten will, ansonsten close ich es.

lg mario

**Comment by Phoniexk** [comment]
Nein da hat sich nichts geändert. 

> § 8. (1) Die in der Registrierkasse erfassten Barumsätze sind laufend aufzusummieren (Umsatzzähler). Trainingsbuchungen dürfen sich nicht auf den Umsatzzähler auswirken.

> (2) Zu jedem Monatsende sind die Zwischenstände des Umsatzzählers zu ermitteln (Monatszähler) und als Barumsatz mit Betrag Null (0) und elektronischer Signatur bzw. Siegel der Signatur- bzw. Siegelerstellungseinheit (Monatsbeleg) im Datenerfassungsprotokoll der Registrierkasse zu speichern.

> (3) Mit Ablauf jedes Kalenderjahres ist der Monatsbeleg, der den Zählerstand zum Jahresende enthält (Jahresbeleg), auszudrucken, zu prüfen und gemäß § 132 BAO aufzubewahren. Bei der Prüfung des Jahresbeleges ist § 6 Abs. 4 sinngemäß anzuwenden.

**Comment by marioboehm** [comment]
Gut danke, dann ist mal alles geklärt :D

lg mario
