### ISSUE TITLE
CRYPTO_SIGNATURE: FAIL

### ISSUE THREAD

**Issue by themelektaus** [a-sit-plus/at-registrierkassen-mustercode#394]
Hallo,

wir haben ein Problem mit der kryptografischen Gültigkeit der Signatur (mittlererweile ein Klassiker).

Szenario:
```json
{
  "cashBoxId" : "KASSA-1",
  "base64AesKey" : "UGFzc3dvcnRNaXQzMlN0ZWxsZW5TdHJlbmdHZWhlaW0=",
  "companyID" : "U:ATU10248203",
  "simulationRunLabel" : "TESTSUITE_TEST_SZENARIO_20",
  "numberOfSignatureDevices" : 1
}
```

Cryptographic Material Container:
```json
{
  "base64AESKey" : "UGFzc3dvcnRNaXQzMlN0ZWxsZW5TdHJlbmdHZWhlaW0=",
  "certificateOrPublicKeyMap" : {
    "6F2E47D2" : {
      "id" : "6F2E47D2",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : "MIIFPDCCAySgAwIBAgIEby5H0jANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDMwMTE1NDk1NFoXDTIyMDMwMTE0NDk1NFowPjELMAkGA1UEBhMCQVQxGDAWBgNVBAMMD1VJRCBBVFUxMDI0ODIwMzEVMBMGA1UEBRMMODE5OTM5MTUxMzA3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvzW2s1zDUdXR5gASjO2W7GmWss7gc8LQfSOK9mgrJnjMAC/3o2G3joG95BnFAsksoSvzZ3KTKbS1RZK9GjSYiaOCAacwggGjMH8GCCsGAQUFBwEBBHMwcTBGBggrBgEFBQcwAoY6aHR0cDovL3d3dy5hLXRydXN0LmF0L2NlcnRzL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlLUNBLmNlcjAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQEAwIGwDARBgNVHQ4ECgQISQXoJi78AigwRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybC5hLXRydXN0LmF0L2NybC9BLVRydXN0LVJlZ2lzdHJpZXJrYXNzZS5DQTAJBgNVHRMEAjAAMFgGA1UdIARRME8wTQYGKigAEQEYMEMwQQYIKwYBBQUHAgEWNWh0dHA6Ly93d3cuYS10cnVzdC5hdC9kb2NzL2NwL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlMBMGA1UdIwQMMAqACEBHnq7jkN+2MB4GA1UdEQQXMBWBE29mZmljZUBoYWFzLWhhYXMuYXQwHAYHKigACgELAQQRDA9VSUQgQVRVMTAyNDgyMDMwDQYJKoZIhvcNAQELBQADggIBABfEXqZJ9jG3w9xtOpNKLIo7dbNXi1FaELnCdWwmwElvDE3efDv/P0ZRYzkTFInQtohEDJ770BHkUvL/1Nk8Y3p196NAHzPMIdrmZNDD0xGoTBRTLutF5rmbmANv8Zf82A0VP3m+kFJpvYAGtIyDbrenBMLseTa/CEZBHqXQeSdP0IZrR/6Iy3kV0TQv6bOCjPasygFhQ7kN0ZeKsPPhMNh969qhjHUn4sjDjzh38H3RhAYcjc4SujsYld5pI31wVTqlkZHvP3mQVZFAWMYkaQ1TgLVSRcvFiYDAJjp0x00O07mDm8Pb0gDb4KiKP68E/dZDntg4+k1u/JuxoEMENV1dQ4eGNLTgZTfeIpA6kEs4xq98MO9+HKD2CUq+g7y0bMfpxNNQFqQw42fBi4LMs7PzagCiXOD9xsXoXKZu6OF2/+Tlo7cSNs3kym579P3QJZVridlw3khXzQoCHBb5b2SvdbMg4bTuFBGgRmU22CRXZJj3cEmeAB72MJXEto3JoYy/tB0sZkojDrIeWSexPOIKXyOyWMIB1swuNOBR8U+VdLTubTQR0odBFdkaZtijzB04gjyhfgfhpcuU6iwy0vyIsLx/E1381xx0Ybm3bsL6HfHyN2Z4kXjUtXfCK/pTqikEYTdRdMxgwN7j07qNfYqqoL0eB2jcF1kE+SxH1zri"
    }
  }
}
```

QR-Code:
```json
[ "_R1-AT1_KASSA-1_2017-98765_2017-01-01T08:00:00_0,00_0,00_0,00_0,00_0,00_yx0GDkWQfzicsaVTJ8Ucuw==_6F2E47D2_Eq/+OfFQSMQ=_07H5YDSUaEY7TXoRE3WGZHvvdPX3QCVuyTwduwVIwqLKQbFGsHYbXDPssBHdizYjmb/Rc5Fc4Vaug3ModjVEBA==" ]
```

Zum Signieren versuchten wir es mit 2 verschiedenen .NET-Bibliotheken (bei beiden hatten wir leider keinen Erfolg):
- [RKWrapper](https://labs.a-trust.at/developer/ShowSource.aspx?id=125)
- [PC/SC](https://github.com/danm-de/pcsc-sharp)

Ich weiß nicht, ob man daraus schon eine mögliche Fehlerquelle erkennen kann. Falls genauere Informationen benötigt werden, kann ich diese gerne nachtragen.

Bitten um Hilfe, herzlichen Dank im Voraus.

**Comment by ErichFreitag** [comment]
Fehler Nr. 1 ist mal, dass der Umsatzzähler nicht 0 ist bzw. einen Fantasiewert aufweist. Bringen sie das bitte mal in Ordnung, vielleicht hängt es damit zusammen.

**Comment by themelektaus** [comment]
Ups, da hat sich ein kleiner Fehler eingeschlichen.
Der IV war nicht korrekt.

Neuer Umsatzzähler (0): `X85Ja71kaWw2Q6CHQvXQHA==`
Jetzt müsste es passen:
```json
[ "_R1-AT1_KASSA-1_2017-98765_2017-01-01T08:00:00_0,00_0,00_0,00_0,00_0,00_X85Ja71kaWw2Q6CHQvXQHA==_6F2E47D2_Eq/+OfFQSMQ=_edDgPeIq3P1SAemfdfdZORA4ExbE4ApcQjh39W+sejQv5AmGjIjwVM5I3bMgWT5EVttjSTweCwc2QkLoo6sMfg==" ]
```

Fehler bleibt trotzdem noch bestehen (kryptographische Gültigkeit).

**Comment by ErichFreitag** [comment]
Alles was ich jetzt ersehen kann ist in Ordnung. Da bleibt leider nur, die Signaturerstellung anhand der Listen step-by-step durchzugehen...

**Comment by FriNagy** [comment]
nur als Info...

ich habe gestern auch das gleiche Problem gehabt, 
zig mal kontrolliert, Dateien neu erstellt, Zertifikat bei 
https://certlogik.com/decoder/
geprüft, alles wie sein sollte, trotzdem die Prüfung blieb fehlerhaft.

Heute sehe ich, 
dass ich das Geheimhaltungszertifikat verwendet habe und nicht das Signaturzertifikat, 
geändert und jetzt passt es, 
... wie immer mein Schuld

**Comment by themelektaus** [comment]
Hier ein Auflistung der Vorgehensweise zur Erstellung des Verkettungswertes:
```text
--- VERKETTUNGSWERT ---
Kassa ID:               KASSA-1
Bytes:                  new byte[] { 75, 65, 83, 83, 65, 45, 49 }
Hash:                   new byte[] { 18, 175, 254, 57, 241, 80, 72, 196, 206, 49, 7, 43, 92, 214, 152, 97, 150, 249, 82, 229, 76, 143, 83, 210, 47, 20, 103, 195, 223, 144, 60, 189 }
Ergebnis:               Eq/+OfFQSMQ=
```

Das gleiche für **Daten die signiert werden sollen** (header.payload)
```text
--- JWS ---
Header:                 {"alg":"ES256"}
Header (Base64-URL):    eyJhbGciOiJFUzI1NiJ9
Payload:                KASSA-1
Payload (Base64-URL):   S0FTU0EtMQ
Ergebnis:               eyJhbGciOiJFUzI1NiJ9.S0FTU0EtMQ
```
Danach verwende ich die [Sign-Funktion des RKWrappers](https://labs.a-trust.at/developer/ShowSource.aspx?id=125)
`rkw.Sign(tbsBytes, out signature);`

```text
--- SIGNATUR (Base64) ---
MdRFC7WssrIM+c/8fTVsnn/ZjZLt4U9cSsn/YIThbEN4zxGeEyXH3gsDlFIjRuN1KDCPvIZRHFqLpx6j4TlcKw==
```

Ich will soweit nur sichergehen, ob alles richtig ist. Wo könnte es noch haken?

@FriNagy Danke für die Info. Dies war jedoch eines der ersten Dinge, die wir überprüft haben.

**Comment by FriNagy** [comment]
Hallo!

also wenn ihr testen wollt dabei gezippt mein regkp.exe,
das ein startbeleg ausgibt, signiert und  die json Dateien für das Prüftool ausgibt

bei mir funktioniert es, mit a-sign RK Chip Karte einwandfrei
es ist nur ein exe Programm, ohne dll's und ohne installation
USB Reader mit gültige Karte muss natürlich angesteckt sein...

so wird es gestartet ( siehe ts.bat in ZIP Datei)

```
rem REGKP.Test (START-Beleg) 
rem wir brauchen zwei steuerungs Dateien 
rem zuerst .\kpar.txt, mit kassen-ID AES-Key und. Cert_Ser_Nr

echo CASHBOX-DEMO-1 > kpar.txt
echo WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU= >>kpar.txt
echo 126e174a >>kpar.txt

rem und die zweite: .\bel2dep.txt, für die einzelne Belege 
rem mit Beleg-Nummer, Beleg-Art, und die Cent-Beträge (pro tax)

echo CASHBOX-BELEG-ID0 > .\bel2dep.txt
echo START >>.\bel2dep.txt
echo 0 >>.\bel2dep.txt

rem signieren
REGKP.EXE

rem und die *.json Dateien für das java Prueftool exportieren ...
REGKP.EXE -xj

PAUSE
rem java prueftool starten
copy *.json C:\java\regkassen-demo-1.0.0
cd C:\java\regkassen-demo-1.0.0
java -jar regkassen-verification-depformat-1.0.0.jar -i dep-export.json -c crypto.json -o TestOUT


```

[RKTEST.ZIP](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/841042/RKTEST.ZIP)

**Comment by themelektaus** [comment]
@FriNagy Wow, der Wahnsinn, es klappt: **PASS!**

Es scheitert also rein am Signieren selbst.
Wir haben es schon mit dieser Bibliothek probiert: https://labs.a-trust.at/developer/ShowSource.aspx?id=114 jedoch ohne Erfolg...

Uns würde brennend interessieren, wie du es geschafft hast, eine Prüftool-gültige Signatur zu erstellen.

Im Prinzip wäre uns schon mit einer DLL geholfen, die eine Funktion zu Verfügung stellt, bei der man Signatureinheit (Index: 0?) + Header + **Payload** übergeben kann und die signierten Daten bspw. im Base64-Format zurückgegeben werden.

Vielen herzlichen Dank.

**Comment by FriNagy** [comment]
Super!  freut mich, 

> Im Prinzip wäre uns schon mit einer DLL geholfen


aber das macht eben das REGKP.exe
Du fütterst es mit die Belegnummer und Betrag 
und es liefert die  Datei: deplog.txt  zurück,
aber man könnte auch ein "nur signieren" funktion einbauen 

vleicht schaut ihr den Source doch noch an: #414 
( in debugger )

**Comment by FriNagy** [comment]
PS. anderseits, für eine kiste Bier kann ich auch als DLL kompilieren ...

**Comment by themelektaus** [comment]
@FriNagy Ich muss mich nochmal **herzlichst bedanken.** Ich habe es schon geschafft eine DLL zu basteln, die ausschließlich für die Signatur zuständig ist.

**C#** Beispiel-Programm
```c#
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace RKSV
{
	class SignTest
	{
		[DllImport("RegKP.dll", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Unicode)]
		private static extern bool Sign(byte[] jws, byte[] result, ref int resultSize);
		public static bool Sign(string jwsData, out byte[] result, out string base64Result, out string base64urlResult) {
			return Sign(Encoding.UTF8.GetBytes(jwsData), out result, out base64Result, out base64urlResult);
		}
		public static bool Sign(byte[] jwsData, out byte[] result, out string base64Result, out string base64urlResult) {
			result = null;
			base64Result = null;
			base64urlResult = null;
			byte[] bytes = jwsData;
			byte[] jws = new byte[1024];
			byte[] temp = new byte[512];
			int resultSize = 0;
			Array.Copy(bytes, jws, bytes.Length);
			if (Sign(jws, temp, ref resultSize)) {
				byte[] finalResult = new byte[resultSize];
				Array.Copy(temp, finalResult, resultSize);
				base64Result = Encoding.UTF8.GetString(finalResult);
				result = Convert.FromBase64String(base64Result);
				base64urlResult = EscapeBase64url(base64Result);
				return true;
			}
			return false;
		}

		private static string ByteArrayToString(byte[] input) {
			string result = "";
			for (int i = 0; i < input.Length; i++) {
				if (!string.IsNullOrEmpty(result)) {
					result += ", ";
				}
				result += input[i].ToString();
			}
			return "new byte[] { " + result + " }";
		}

		private static string EscapeBase64url(string base64) {
			StringBuilder result = new StringBuilder(base64.TrimEnd('='));
			result.Replace('+', '-');
			result.Replace('/', '_');
			return result.ToString();
		}

		static void Main() {
			string jwsData = "eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9LYXNzYS0xXzIwMTctMV8yMDE3LTAzLTE1VDEwOjQ2OjE3XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF9hUEUzbjZlL3JJST1fMUNCMjAyRjZfZVlLd3NhYm5ncEE9";
			byte[] result;
			string base64Result;
			string base64URLResult;
			bool signatureOK = Sign(jwsData, out result, out base64Result, out base64URLResult);
			if (signatureOK) {
				Console.WriteLine("Signature:");
				Console.WriteLine(ByteArrayToString(result));
				Console.WriteLine();
				Console.WriteLine("Base64:     " + base64Result);
				Console.WriteLine("Base64 URL: " + base64URLResult);
			} else {
				Console.WriteLine("SIGNATUREINHEIT-AUSGEFALLEN");
			}
			Console.ReadKey(true);
		}
	}
}
```

**RegKP.dll** Source-Code
```c++
#include "stdafx.h"
#include "wins_APDU.h"
#include "wins_BCRYPT.h"

extern "C" {
  __declspec(dllexport)
  bool __cdecl Sign(char *jws, char *result, int *resultSize)
  {
    // --- Definition --------------------------------------
    char hash[166];
    char temp[512];
    
    // --- SHA 256 erstellen -------------------------------
    hash_SHA256((BYTE*) jws, strlen(jws), hash);
    
    // --- Glorreiche Signatur -----------------------------
    if (APDU_Sign(hash) == 64) {
      ToBase64Crypto(hash, 64, temp, 300);
    } else {
      return false;
    }
    
    strncpy(result, temp, strlen(temp));
    *resultSize = strlen(result);
    
    // --- OK ----------------------------------------------
    return true;
  }
}
```

Anbei noch die kompilierte DLL (vielleicht kann es jemand brauchen)
[RegKP.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/844098/RegKP.zip)

Wo darf ich mit der Kiste Bier vorbeikommen? Innsbruck wäre schon ein bisschen weit für mich... 😃

**Comment by FriNagy** [comment]
fein das es funktioniert...

und wegen das Bier, es ist leider fasten Zeit :(

**Comment by StefanKDS** [comment]
@FriNagy Ich habe dein Tool mal ausprobiert. Klappt Prima, aber ich habe ein Problem.
Wenn ich den AES Key "U3RlZmFuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" nehme ( Stefan mit Füllzeichen ) dann bekomme ich einen AES Schlüssel Fehler von deinem Tool. Wieso ?

ich habe es in der TS.BAT angepasst..
echo Testkasse> kpar.txt
echo U3RlZmFuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=>>kpar.txt

und in der crypton.json
"base64AESKey" : "U3RlZmFuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",


Gruß

**Comment by FriNagy** [comment]
Hallo!

das Programm prüft ob Base64 Decodiert es ein 32 Zeichen langes Password ist,
wenn nicht kommt die Fehlermeldung

probier zB mit _ auffüllen

> 			anzread = FromBase64Crypto(fname, (strlen(fname)), AES_KEY, 33);
> 			if ((strlen(AES_KEY)) != 32) printf("AES KEY Check Fehler: %s!\n", fname);
>
