### ISSUE TITLE
Detailfrage zu maschienenlesbaren Code bei ausgefallener Signatureinheit

### ISSUE THREAD

**Issue by Josma** [a-sit-plus/at-registrierkassen-mustercode#395]
Ich konnte leider kein Thema finden, das meine Frage beantworten würde.

Ich stehe vor dem Problem, das ich mir nicht sicher bin, wie bei ausgefallener Sigantureinheit der maschienenlesbare Code  erstellt werden kann bzw darf.

Im Grunde geht es um das Feld Zertifikat-Seriennummer. (Offenes System)
Wenn die Signatureinheit ausgefallen ist, welchen Wert darf man hier einsetzen? 
Ich kann ja die Seriennummer nicht mehr ermitteln.

Folgendes Bsp.: Kassa erstellt Startbeleg und dieser wird erfolgreich signiert sowie über FOn geprüft -> OK
Weitere Belege werden erstellt, alles funktioniert wie gewünscht -> OK

Dann zieht jemand aus versehen den Kartenleser vom PC.
Jetzt möchte ich aber natürlich weiterhin Belege erstellen können stelle mir aber gerade die Frage, welchen Wert man dann für Zertifikat-Seriennummer einsetzen muss/darf.

Sobald die Signatureinheit wieder am PC hängt, kann ich die Zertifikat-Seriennummer wieder ermitteln (kann ja auch eine andere sein, wenn andere Siganturkarte verwendet wird) und alles ist wieder OK. (Sammelbelg erstellen nicht vergessen - klar).

nur solange ich ohne Signatureinheit bin bin ich mir nicht sicher was ich hier eintragen muss.

weis hier jemand wie man in so einem Fall vorgehen darf? Ich konnte das leider auch nicht aus den diversen Doks herauslesen...

**Comment by ErichFreitag** [comment]
Sie verwenden bei einem SE-Ausfall die zuletzt verwendete Seriennummer. Alternativ eine beliebige dem Unternehmen zugeordnete Seriennummer, je nach Architektur.

**Comment by mbloechl** [comment]
Beim Ausfall der Signatureinheit ist ja nicht nur die Seriennummer, sondern auch der ZDA nicht auslesbar. Am effektivsten wird es wohl sein, diese beiden Parameter intern zu "cachen"

**Comment by Josma** [comment]
Danke euch beiden! 
An den ZDA habe ich noch gar nicht gedacht. Stimmt natürlich ebenfalls.

Ja, das war auch mein erster Gedanke, das ganze 'wegzumerken' und im Falle eines Ausfalles eben die zuletzt bekannten Daten zu verwenden.
