### ISSUE TITLE
Monatsbeleg beim mehrere Monate ausser Betrieb

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#396]
Hallo,
kann mir bitte jemand helfen:
Unsere Kunde fragt, wie genau ist die Vorgehensweise bei eine Kasse die z.B. 3 Monate ausser betrieb wahr:
letze Transaktionen gemacht im Januar, danach Februar und März keine, im April wieder in Betriebnahme.
Für welche Monate muss man dann Monatsbelege erstellen?
Muss man dann Monatsbelege für alle diese inzwischen Monate erstellen, oder nur Januar und danach wieder am Ende April?

vielen dank im Voraus

**Comment by ErichFreitag** [comment]
In der Zeit, wo die Kasse nicht in Betrieb ist, müssen auch keine Monatsbelege erstellt werden. Der nächste wäre als Anfang April = Ende März, je nach Implementierung.
