### ISSUE TITLE
Initialisierungsvektor

### ISSUE THREAD

**Issue by bonus7771** [a-sit-plus/at-registrierkassen-mustercode#398]
Gemäß Z 9 der Detailspezifikationen darf niemals der gleiche IV (gebildet aus Kassen-ID und Belegnummer) verwendet werden. Darf dann die Belegnummer mit Beginn eines neuen Jahres überhaupt wieder auf 1 gestellt werden? 
Ansonsten wäre etwa die Belegnummer mit Jahresangabe (zB 2017-1) denkbar. Wird aber beim Startbeleg auch eine andere Belegnummer als 1 akzeptiert?

**Comment by ztp-mino** [comment]
Das Prüftool akzeptiert jede beliebige Belegnummer, nur wiederholen darf sie sich nicht. Rechtlich gibt es afaik mehr Einschränkungen.

**Comment by lebail** [comment]
Die Belegnummer darf (eben wegen der Forderung der Eindeutigkeit und Fortläufigkeit) _nicht_ am Jahresbeginn zurückgesetzt werden. Nummern der Art 2017-1 sind ok - und werden natürlich auch beim Startbeleg akzeptiert.

**Comment by ChristianSpath** [comment]
Ich nehme an, dass beim Startbeleg auch "2017/134" ok ist? Er muss hoffentlich nicht 2017/1 sein?

Danke, lg

**Comment by lebail** [comment]
Natürlich ist das ok. Es steht nirgends, dass bei 1 begonnen werden muss. Das System der Nummerierung sollte lediglich nachvollziehbar sein.
