### ISSUE TITLE
FAQ Eintrag DEP-Export Format 2016

### ISSUE THREAD

**Issue by pteufl** [a-sit-plus/at-registrierkassen-mustercode#4]
Wie geht man mit nicht vorhandener Signatur um?

**Comment by Ka0o0** [comment]
Gibt es da schon Neuigkeiten?

**Comment by pteufl** [comment]
Ja, leider hier nicht das Issue geschlossen. Diese Frage wurde im Rahmen der UBIT Gruppe vom BMF beantwortet. Bitte auch diese Seite für weitere Details, Fragen besuchen die nicht unmittelbar technischer Natur sind: 

https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/Registrierkassenpflicht.html

Copy und Paste der Frage/Antwort:
Auf Verlangen der Organe der Abgabenbehörde hat der Unternehmer das Datenerfassungsprotokoll für einen vom Organ der Abgabenbehörde vorgegebenen Zeitraum auf einen externen Datenträger zu exportieren und zu übergeben. Der Datenträger ist vom Unternehmer bereitzustellen. Für welchen Zeitraum muss das Datenerfassungsprotokoll wirklich für den unmittelbaren Export in der Filiale vorhanden sein und für welchen Zeitraum die Bereitstellung über die Zentrale mit entsprechender Verzögerung zulässig ist?

Antwort:
Das BMF sieht ein unmittelbares Exporterfordernis ab dem 1.1.2016 als gegeben; für 2016 mit den Daten des § 7 Abs. 1 RKSV, ohne vorgegebene Struktur.
Ab 1.1.2017 gilt für den Export der im Datenerfassungsprotokoll festzuhaltenden Inhalte des maschinenlesbaren Codes die Strukturvorgabe der Z 3 der Anlage zur RKSV. Ob ab 1.1.2017 auch Bereitstellungen über eine Zentrale erlaubt werden, wird zurzeit geklärt.

**Comment by Ka0o0** [comment]
Okay das war auch meine Annahme. Danke für die Antwort!
