### ISSUE TITLE
regkassen-verification-depformat-0.5.jar "Signatur kryptographisch": FEHLERHAFT

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#40]
Gibt es eine Möglichkeit nähere Information zu erhalten, warum die Prüfung fehlschlägt?

java -jar regkassen-verification-depformat-0.5.jar -i test-dep-export.txt -k aes-key.txt

```
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen: Dekodierter Signaturwert: 0E! ?¡¹YCSlE??×]¡ ]??¨ÁÞ_?¼ìN ?Óè?ÏÐ ¸fÞek×4?HðIÞMî?«?±º¢rÖe
STACKTRACE: java.lang.NullPointerException
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.SignatureVerificationModuleJWSFormat.verify(SignatureVerificationModuleJWSFormat.java:108)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.SignatureVerificationModulePlainFormat.verify(SignatureVerificationModulePlainFormat.java:49)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.MachineCodeVerificationModulePlainFormat.verify(MachineCodeVerificationModulePlainFormat.java:70)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.MachineCodeVerificationModuleJWSFormat.verify(MachineCodeVerificationModuleJWSFormat.java:50)
        at at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule.verify(DEPExportFormatVerificationModule.java:161)
        at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:70)
```

Anbei die beiden Eingabe-Test-Files

[test-dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/148144/test-dep-export.txt)

[aes-key.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/148145/aes-key.txt)

**Comment by pteufl** [comment]
Haben Sie die Unlimited Strength Policies von Java installiert? (Leider überprüft das Tool das nicht und dürfte da dann erst bei irgendwo mit dieser Nullpointerexception rausfliegen).

**Comment by lebail** [comment]
Da mir gerade das selbe Problem untergekommen ist:

Ich könnte mir vorstellen, dass es daran liegt, dass die derzeitige Version des Prüftools noch davon ausgeht, dass die Zertifikats-Seriennummer _dezimal_ angegeben wird. Im gegenständlichen File wird aber bereits das _Hexadezimal_-Format benutzt.

**Comment by pteufl** [comment]
an der seriennummer kann es nicht liegen, die wird bei der kryptographischen prüfung nicht berücksichtigt. Bitte die Unlimited Strength Policies prüfen/installieren. Ich überprüf das auch noch.

**Comment by anzun** [comment]
Ja, die Unlimited Strength Policies ist installiert.

Ich konnte das DemoCashbox Beispiel erfolgreich prüfen

```

C:\temp\a-sit-regkassen-demo-release-0.5>java -jar regkassen-verification-depformat-0.5.jar  -i C:\Users\x\workspace\regkassen-democashbox\CashBoxDemoOutput2016-02-10T12-58-47\dep-export.txt -k C:\Users\x\workspace\regkassen-democashbox\CashBoxDemoOutput2016-02-10T12-58-47\aesKeyBase64.txt
------------------Ergebnisse------------------
Verifikationsmodul: at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule

-----------Detailresultate fuer Paket-------------------
DEP Export Format Überprüfung

ÜBERPRÜFUNG: "DEP Export Format": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung von DEP-Export-Beleg-Gruppe 1

ÜBERPRÜFUNG: "Lesen von Signatur Zertifikat": ERFOLGREICH
ÜBERPRÜFUNG: "Lesen von Zertifikatskette": ERFOLGREICH
ÜBERPRÜFUNG: "Überprüfung ob Kassen-ID und Belegnummer einmalig": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 1

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": ERFOLGREICH
ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": ERFOLGREICH
++++++++++++++++++++++++++++++
```

**Comment by pteufl** [comment]
lebail hat Recht, hier gibt es im Prüftool einen Fehler, der einmal dezimal/einmal hexadezimal die seriennummer verwendet. Dadurch findet man das Zertifikat nicht und es kommt zu diesem Fehler, der im Stacktrace zu sehen ist. 
Wir sind gerade dabei das Prüftool generell zu überarbeiten, werden aber schnell eine Version rausgeben die dieses Problem behebt (Workaround, die Seriennummer als Integer im Beleg ablegen).

ABER: ich hab die Daten jetzt mit dem korrekten Prüftool geprüft: Signaturen sind dennoch fehlerhaft. Haben Sie ein Code-Snippet wie die Signatur erstellt wird?

**Comment by pteufl** [comment]
Hier das Ergebnis: Es dürfte auch ein Problem mit der Verkettung geben, erster Beleg korrekt, weitere Belege nicht korrekt
-----------Detailresultate fuer Paket-------------------
DEP Export Format Überprüfung

ÜBERPRÜFUNG: "DEP Export Format": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung von DEP-Export-Beleg-Gruppe 1

ÜBERPRÜFUNG: "Lesen von Signatur Zertifikat": ERFOLGREICH
ÜBERPRÜFUNG: "Lesen von Zertifikatskette": ERFOLGREICH
ÜBERPRÜFUNG: "Überprüfung ob Kassen-ID und Belegnummer einmalig": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 1

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
~j+q�	�!� $\���u�냋�U�%���O\��f

ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 2

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
� �DR��g4!֦��������pڲ^�F

ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": FEHLERHAFT
DETAILS: Gültigkeit der kryptographischen Kette ist nicht gegeben.

++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 3

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen: Dekodierter Signaturwert: 0F!��F�VO����J�YAJ]�y�5U����=�!�P�i«�)뼁$H6pk��'�N1��?V��

ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": FEHLERHAFT
DETAILS: Gültigkeit der kryptographischen Kette ist nicht gegeben.

++++++++++++++++++++++++++++++

**Comment by anzun** [comment]
Ich sehe in A-SIT_PLUS Code folgende Zuweisung

`inputForChainCalculation = receiptPackage.getJwsCompactRepresentation();`

also zum Beispiel:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMF8xXzJfMjAxNi0wMi0yOVQxNTozMzowMl8wLDAwXzAsMDBfMCwwMF8wLDAwXzIsNDVfVTFSUF84MDY2ODI4MjUwODk0NjM0NTkwNDQ4Mjk5Mjk4Ml8xQng0aVl0VEpZQT0.U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg

und weiter...

```
            //set hash algorithm from RK suite, in this case SHA-256
            MessageDigest md = MessageDigest.getInstance(rkSuite.getHashAlgorithmForPreviousSignatureValue());

            //calculate hash value
            md.update(inputForChainCalculation.getBytes());
            byte[] digest = md.digest();

            //extract number of bytes (N, defined in RKsuite) from hash value
            int bytesToExtract = rkSuite.getNumberOfBytesExtractedFromPrevSigHash();
            byte[] conDigest = new byte[bytesToExtract];
            System.arraycopy(digest, 0, conDigest, 0, bytesToExtract);

            //encode value as BASE64 String ==> chainValue
            return CashBoxUtils.base64Encode(conDigest, false);
```
Ich hatte es so verstanden, dass **nur die Signatur** verwendet wird um die **Signatur-Verkettung** zu berechnen....

Siehe auch:
https://www.ris.bka.gv.at/Dokumente/BgblAuth/BGBLA_2015_II_410/COO_2026_100_2_1163254.html

**6. Ergebnis der Signaturerstellung**
Das Ergebnis der JWS-Signatur ist die nach dem JWS-Standard definierte kompakte Repräsentation. Diese Zeichenkette besteht dabei aus drei BASE64-URL-kodierten Elementen, die durch das Zeichen „.“ voneinander getrennt sind. Die drei Elemente entsprechen den Elementen in der gegebenen Reihenfolge
  1. den Metainformationen über den verwendeten Hash bzw. Signaturalgorithmus
  2. den signierten Daten (JWS Payload) und
  3. **dem berechneten Signaturwert.**

Kann aufgrund des Ausfalls der Signaturerstellungseinheit keine digitale Signatur erstellt werden, wird **statt dem berechneten Signaturwert (drittes Element der kompakten JWS Repräsentation)** die UTF-8 kodierte Zeichenkette „Sicherheitseinrichtung ausgefallen“ BASE64-URL-kodiert eingetragen.

**Comment by anzun** [comment]
Ich sehe, diese Frage ist bereits beantwortet:
Input für Sig-Voriger-Beleg #17

Dies ist auch im Dokument Festlegungen des BMF zu Detailfragen der RKSV https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/137544/2016-02-18-Detailfragen-RKSV-V1.0.pdf

**2.4.2 Verkettung bei allen Belegen außer dem Startbeleg**

Eingabewert für Hashalgorithmus: Als Eingabewert wird die kompakte Repräsentation der ** JWS-Signatur** des vorhergehenden Beleges herangezogen (siehe Ausgabewert der Prozesse 3.1 oder 3.2).
Wobei mit JWS-Signatur nicht nur der Signaturwert, sondern die gesamte JWS-kompakt-Representation des Beleges gemeint ist.

**Comment by pteufl** [comment]
ich hab den jetzt mal geschlossen, oder gibt es da noch offene Punkte?

**Comment by pteufl** [comment]
konnten Sie die Signatur bereits verifizieren?

**Comment by anzun** [comment]
Nein leider auch mit der Seriennummer in dezimaler Schreibweise ist die Signatur nicht verifiziert. 

[aes-key.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/152419/aes-key.txt)
[test-dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/152421/test-dep-export.txt)

Und dies obwohl ich sehen kann, dass die Signatur-Vorheriger-Beleg korrekt übergeben wird.
Eventuell habe ich einen Fehler in der Erstellung dieses String strSigShort 

```
//Zusammensetzen JWS-String:
string strJWScompact = base64urlencode(Encoding.UTF8.GetBytes(strHeader)) + "." + base64urlencode(utf8DataToSign) + "." + strBase64UrlSignature;

//Umwandeln in UTF-8
byte[] utf8ToHashJWScompact = Encoding.UTF8.GetBytes(strJWScompact);

// Hash berechnen und 8 Bytes extrahieren
strSigShort = hashAndExtractBytesToBase64String(utf8ToHashJWScompact, numberOfBytesExtractedFromPrevSigHash);

 private static string hashAndExtractBytesToBase64String(byte[] byteArrayInput, int numberOfBytesToExtract)
{
            SHA256 mySHA256 = SHA256Managed.Create();
            byte[] hashedInput = mySHA256.ComputeHash(byteArrayInput);

            byte[] byteArrayExtractedOutput = new byte[numberOfBytesToExtract];
            Buffer.BlockCopy(hashedInput, 0, byteArrayExtractedOutput, 0, byteArrayExtractedOutput.Length);
            return Convert.ToBase64String(byteArrayExtractedOutput);
}
```

**Comment by pteufl** [comment]
können Sie den Code für die Signaturberechnung (verwenden Sie eine Karte) posten?
Ich konnte die Signatur (nach Korrektur des SN Problems) bei Ihrem BSP auch nicht prüfen. Es könnte damit zusammenhängen dass der Signaturwert falsch kodiert ist, dazu müsste ich aber den Code für die Ansteuerung der Karte/HSM etc. sehen.

**Comment by anzun** [comment]
```
string strStringToSign;
                strStringToSign = "_" + strRKA
                    + "_" + this.KassenId
                    + "_" + this.BelegNr
                    + "_" + this.DatumUhrzeit
                    + "_" + strBetragSatzNormal
                    + "_" + strBetragSatzErmaessigt1
                    + "_" + strBetragSatzErmaessigt2
                    + "_" + strBetragSatzNull
                    + "_" + strBetragSatzBesonders
                    + "_" + strBase64VerschluesseltStandUmsatzZaehler
                    // 2016-02-29 Prüftool Seriennummer Dezimal / Hexadezimal
                    // Zertifikat Nr derzeitiges Prüftool BigInteger-String anstelle Hex-String
                    // + "_" + this.ZertifikatNr
                    + "_" + strSerialnumberSmartCardDecimal
                    // Ende 2016-02-29 Prüftool Seriennummer Dezimal / Hexadezimal
                    + "_" + this.SigPrev
                    ;
byte[] utf8DataToSign = Encoding.UTF8.GetBytes(strStringToSign);
byte[] byteHashedDataToSign = mySHA256.ComputeHash(utf8DataToSign);
byteSignature = smartCard.sign(bytePIN, byteHashedDataToSign);

public byte[] sign(byte[] PIN, byte[] SHA256HASH)
        {
            Response response = sendSelectGlobaltrustAID(SELECT_QES); 
           CommandApdu apdu3 = generateCase3ShortDataAPDU(isoReader, 0x00, 0x20, 0x00, 0x81, PIN); // PIN Verify
            Response response3 = isoReader.Transmit(apdu3); // response3 = 9000 (144 0)
            byte[] byteToSignLC = { 0x00, 0x00, 0x20 };
            byte[] byteToSignLE = { 0x01, 0x02 };
            int intLe = Convert.ToInt32(byteToSignLE[0]) * 255 + Convert.ToInt32(byteToSignLE[1]);
            //Signieren
            CommandApdu apdu5 = generateCase4ExtendedResponseAPDU(isoReader, 0x00, 0x2A, 0x9E, 0x9A, byteToSignLC, SHA256HASH, intLe);
            Response response5 = isoReader.Transmit(apdu5);
            byte[] signature = response5.GetData();
            return signature;
        }

        private static byte[] SELECT_QES = new byte[] { 0x1F, 0xFF }; // Signaturfunktion AID Atos Signaturapplikation QES

        private Response sendSelectGlobaltrustAID(byte[] fileId)
        {
            CommandApdu apdu = generateCase3ShortDataAPDU(isoReader, 0x00, 0xA4, 0x08, 0x04, fileId); // Globaltrust APDU_SELECT fuer QES 0x1F 0xFF (31,255) und DF 0x11 0x60 (17,96) OK
            Response response = isoReader.Transmit(apdu);
            return response;
        }

        private static CommandApdu generateCase3ShortDataAPDU(IsoReader isoReader, byte cla, byte ins, byte p1, byte p2, byte[] data)
        {
            CommandApdu toReturn = new CommandApdu(IsoCase.Case3Short, isoReader.ActiveProtocol)
            { //Lc is valued from 1 to 255.Le is valued to 0.Lc data bytes are present.
                CLA = cla,
                INS = ins,
                P1 = p1,
                P2 = p2,
                Data = data
            };
            return toReturn;
        }

        private static CommandApdu generateCase4ExtendedResponseAPDU(IsoReader isoReader, byte cla, byte ins, byte p1, byte p2, byte[] lc, byte[] data, int le)
        {
            CommandApdu toReturn = new CommandApdu(IsoCase.Case4Extended, isoReader.ActiveProtocol)
            {
                CLA = cla,
                INS = ins,
                P1 = p1,
                P2 = p2,
                Data = data,
                Le = le
            };
            return toReturn;
        }

```

**Comment by pteufl** [comment]
nein, genau das wäre mein Punkt gewesen. Die DER/ASN1 Kodierung darf bei der JWS-Signatur NICHT durchgeführt werden.
Ich muss mir Ihre restlichen Infos noch genauer anschauen.

**Comment by pteufl** [comment]
In der Nachricht mit den Code Snippets führen Sie folgendes durch;

strStringToSign = "_" + strRKA
                    + "_" + this.KassenId
                    + "_" + this.BelegNr
                    + "_" + this.DatumUhrzeit
                    + "_" + strBetragSatzNormal
                    + "_" + strBetragSatzErmaessigt1
                    + "_" + strBetragSatzErmaessigt2
                    + "_" + strBetragSatzNull
                    + "_" + strBetragSatzBesonders
                    + "_" + strBase64VerschluesseltStandUmsatzZaehler
                    // 2016-02-29 Prüftool Seriennummer Dezimal / Hexadezimal
                    // Zertifikat Nr derzeitiges Prüftool BigInteger-String anstelle Hex-String
                    // + "_" + this.ZertifikatNr
                    + "_" + strSerialnumberSmartCardDecimal
                    // Ende 2016-02-29 Prüftool Seriennummer Dezimal / Hexadezimal
                    + "_" + this.SigPrev
                    ;
byte[] utf8DataToSign = Encoding.UTF8.GetBytes(strStringToSign);
byte[] byteHashedDataToSign = mySHA256.ComputeHash(utf8DataToSign);

Das ist aber falsch, im JWS Standard werden als Payload die ersten beiden Elemente der kompakten Repräsentation gesehen: header.payload , darauf wird der Hash gerechnet und dann die Signatur erstellt (ohne der DER Kodierung).
siehe https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-core/src/main/java/at/asitplus/regkassen/core/modules/signature/jws/ManualJWSModule.java

**Comment by anzun** [comment]
Vielen Dank für den Hinweis.
Ich sehe, das dies nun in 3.1 "Der Eingabewert für die JWS-Signaturerstellung ist header.payload" definiert ist.

Ein Frage zum Mustercode: 
java: getBytes()
entspricht dem Encoding.UTF8.GetBytes(string) in C# ,oder?
machineCodeRepOfReceipt.getBytes()

in Zeile 54
String jwsPayloadBase64Url = CashBoxUtils.base64Encode(machineCodeRepOfReceipt.getBytes(), true);

**Comment by pteufl** [comment]
Ja, getBytes sollte dem entsprechen (Strings sind in Java per default UTF8).

wichtig noch, da Sie es oben nennen, JWS ist BASE64-URL (safe) kodiert und nicht normal BASE64 (das ist das true in CashBoxUtils.base64Encode(machineCodeRepOfReceipt.getBytes(), true)..);

**Comment by anzun** [comment]
Nochmals vielen herzlichen Dank für Ihre Unterstützung.

Der Test ist nun erfolgreich:
Offenes ToDo Umstellen auf Seriennummer-Zertifikat Hexadezimal, wenn Prüftool verfügbar.

```
------------------Ergebnisse------------------
Verifikationsmodul: at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule

-----------Detailresultate fuer Paket-------------------
DEP Export Format Überprüfung

ÜBERPRÜFUNG: "DEP Export Format": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung von DEP-Export-Beleg-Gruppe 1

ÜBERPRÜFUNG: "Lesen von Signatur Zertifikat": ERFOLGREICH
ÜBERPRÜFUNG: "Lesen von Zertifikatskette": ERFOLGREICH
ÜBERPRÜFUNG: "Überprüfung ob Kassen-ID und Belegnummer einmalig": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 1

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": ERFOLGREICH
ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 2

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": ERFOLGREICH
ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": ERFOLGREICH
++++++++++++++++++++++++++++++

-----------Detailresultate fuer Paket-------------------
Überprüfung für Beleg 3

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": ERFOLGREICH
ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": ERFOLGREICH
++++++++++++++++++++++++++++++
```
   
[test-dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/153134/test-dep-export.txt)
[aes-key.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/153136/aes-key.txt)

**Comment by pteufl** [comment]
Wunderbar! freut mich! danke auch an lebail für den Hinweis bezüglich HEX/INT.
Dann schließe ich das Thema.
