### ISSUE TITLE
Zertifikat nicht in cryptographicMaterialContainer.json gefunden

### ISSUE THREAD

**Issue by franzhauser** [a-sit-plus/at-registrierkassen-mustercode#401]
Sieht für mich aber in der codieren fassung in ordnung aus (`75aaf3c2`).

[cryptographicMaterialContainer.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/831671/cryptographicMaterialContainer.json.txt)

[dep.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/831676/dep.json.txt)

**Comment by ztp-mino** [comment]
Das `75aaf3c2` object im cmc muss noch in ein `certificateOrPublicKeyMap`. Der gepostete CMC ist nicht korrekt.

**Comment by franzhauser** [comment]
Vielen Dank, @ztp-min. Es hat der `certificateOrPublicKeyMap` gefehlt. Nun bin ich einen Schritt weiter.
