### ISSUE TITLE
Stornobeleg - Artikelstorno - gemischter Beleg

### ISSUE THREAD

**Issue by aortner** [a-sit-plus/at-registrierkassen-mustercode#402]
Wann muss ich genau einen Stornobeleg mit STO markieren,

bzw ist eine Vermischung von + und - überhaupt auf einem Beleg erlaubt?

Fall 1) alle Beträge im Plus - würde im dep gar nicht auffallen

3 Große Bier a 4 =12 €
-5 Pfandflaschen ,20 = -1 €

Gesamt € 11.-

Fall2) Einzelner Betrag pro Steuersatz auf Minus   

3 Große Bier a 4 =12 €
-1 Wiener Schnitzel  9 = -9 €

Gesamt € 3,00

Fall 3)
3 Große Bier a 4 =12 €
-2 Wiener Schnitzel  9 = -18 €

Gesamt € - 6,00

Danke Andreas

**Comment by ErichFreitag** [comment]
Storno und Verkäufe dürfen sie grundsätzlich nicht in einem Vorgang vermischen. Grund ist, dass bei einem Storno der Umsatzzähler mit "STO" codiert wird und damit der gesamte Barumsatz nicht mehr rekonstruierbar wäre.

Storno ist Storno, sprich das Rückgängig-machen eines Geschäftsvorfalls. Vielleicht als Denk-Leitfaden: bei Storno ist noch kein Geldfluss erfolgt, bei einer Retoure schon. Ein Storno erfolgt typisch sofort (z.B. durch Irrtum oder fehlender Zahlungsmöglichkeit), eine Retoure erfolgt typisch später (z.B. bei Umtausch oder Rückgabe).

Denken sie an den Hintergrund der RKSV in Richtung Gastronomie - ein Beleg wird ordnungsgemäß erstellt und dann storniert, um den Barumsatz wieder zu reduzieren. Offensichtlich war das sehr wichtig, Stornos eindeutig identifizieren zu können.

**Comment by AxelKutschera** [comment]
Das Mischen von + und - ist erlaubt. Es kann sogar null ergeben und es ist trotzdem zu signieren.
Die fiskaltrust-Schnittstelle rechnet das entsprechend dem Geschäftsvorfall korrekt aus.
Storno ist nur dazu da, einen konkreten Beleg zu "löschen".
Ich persönlich bin eher dafür, Stornos zu vermeiden und eher einen Minusumsatz zu machen.

**Comment by aortner** [comment]
Danke! Dann gehe ich davon aus:

Ein Storno dient dazu einen gesamten Beleg (vorigen) zu stornieren.




Fall 1-3 könnten als Standard - Belege behandelt und signiert werden.

**Comment by ErichFreitag** [comment]
Wie oben geschrieben - ein Storno ist ein Rückgängig-machen eines Geschäftsfalls.

Sie können 1...3 als Standard-Belege abbilden, wobei sie vielleicht mal den Vorgang Minus 1/2 Schnitzel irgendwem erklären müssen.

**Comment by aortner** [comment]
Danke! In der Gastro gibt es leider oft Verschiebungen beim Zahlen durch kleine Mißgeschicke.

Wie zb ein Salat wurde boniert, aber vom Service vergessen. Beim Zahlen bemerkt der Kunde den Fehler erst beim Prüfen der Rechnen das etwas zuviel  auf der Rechnung ist....

Naturlich  sind das Extrembeispiele. Für einen Artikelrücklauf wie zb -1 gemischter Salat würde ich dann
einen extra Geschäftsfall erstellen.
