### ISSUE TITLE
Zertifikatsseriennummer. Ident. Nr. Schlüssel ?

### ISSUE THREAD

**Issue by StefanKDS** [a-sit-plus/at-registrierkassen-mustercode#405]
Hallo,
Was ist die Ident. Nr. des Schlüssels ?
Wer legt diesen fest ?
Gibt es pro Kasse einen Schlüssel ?

Fragen über Fragen ;-)

Danke im voraus.
Gruß
Stefan

**Comment by lebail** [comment]
Was Sie mit "Ident. Nr." meinen, weiß ich nicht. Der Unternehmer kann den Schlüssel jedenfalls selbst festlegen, und ein Schlüssel kann für eine oder mehrere Kassen benutzt werden.

Derartige Fragen werden übrigens im Detailfragen-Dokument beantwortet: https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.2-DOK/2016-09-05-Detailfragen-RKSV-V1.2.pdf

**Comment by StefanKDS** [comment]
Es geht um die Zertifikats-Seriennummer bei geschlossenen Systemen.
Diese setzt sich ja wie folgt zusammen: {S|U|G}:ID-KID

Meine Frage bezieht sich auf das KID.
In den Unterlagen steht:
"KID: Die Identifikationsnummer des jeweiligen Schlüssel....."

Was ist dort mit Ident.Nr. des Schlüssels gemeint ?

Gruß
Stefan

**Comment by ErichFreitag** [comment]
Das ist die Kennung des jeweiligen offenen Schlüssels, vom Unternehmen selbst gewählt und zur Identifikation der Schlüssel eindeutig mit typisch 2 oder 3 Zeichen zu vergeben.

**Comment by StefanKDS** [comment]
Diese Kennung wird dann pro Kasse vergeben, wenn ich das richtig verstehe ?

**Comment by ErichFreitag** [comment]
Pro Schlüssel wird sie vergeben.

**Comment by StefanKDS** [comment]
Mit Schlüssel ist der AES Schlüssel gemeint, oder ?

**Comment by ErichFreitag** [comment]
Nein, der offene Schlüssel der Signaturerstellung - dessen Kennung plus Ordnungsbegriff anstelle der Zertifikats-Seriennummer eingetragen werden.

Sind sie sicher, dass wir beide vom Gleichen, nämlich von geschlossenen Gesamtsystemen reden, die nur unter bestimmten Voraussetzungen zum Einsatz kommen dürfen?

**Comment by StefanKDS** [comment]
Ja, wir reden von geschlossenen Gesamtsystemen.
Wenn ich es richtig verstanden habe, dann handelt es sich hierbei um Kassensysteme mit mehr als 30 Kassen. Korrekt ?

**Comment by StefanKDS** [comment]
Leider habe ich keine vernünftigen Infos zum unterschied zwischen geschlossenen und offenen Kassensystemen gefunden.

**Comment by ErichFreitag** [comment]
Die geschlossenen Gesamtsysteme sind in der RKSV § 20ff beschrieben.

Die Voraussetzungen sind
- mehr als 30 Kassen im Sinne der RKSV
- eine lückenlose Verbindung zwischen Kasse, Buchhaltung und Warenwirtschaft

Dann darf die Signaturerstellung in Software erfolgen. Das ganze ist inklusive Überprüfung der technischen und organisatorischen Voraussetzungen für die Manipulationssicherheit durch ein Gutachten eines Gerichtssachverständigen zu beurteilen und von einer Bestätigungsstelle zu überprüfen.

**Comment by StefanKDS** [comment]
Das hat mir sehr weiter geholfen.

Der Punkt "eine lückenlose Verbindung zwischen Kasse, Buchhaltung und Warenwirtschaft" trifft nämlich auf uns gar nicht zu. 

Vielen Dank für die Hilfe
