### ISSUE TITLE
Erstellung des JWS-Payloads - Betragswerte

### ISSUE THREAD

**Issue by goosefraba** [a-sit-plus/at-registrierkassen-mustercode#406]
Hallo,

Ich habe eine Frage bezüglich des JWS Payload beziehungsweise der Betrag-Sätze.
Die Beispiel-Belege hier im Repo weisen Beträge für alle Steuersätze auf und eventuell habe ich in den Dokumenten etwas überlesen, aber welche Beträge sind für 

Betrag-Satz-Normal (20%), Betrag-Satz-Ermaessigt-1 (10%), Betrag-Satz-Ermaessigt-2 (13%), Betrag-Satz-Null (0%), Betrag-Satz-Besonders (19%)

zu verwenden?
Ich meine zB bei einem Beleg:

**1x Massage (Einzelpreis Netto € 100 / Einzelpreis Brutto € 110 / Steuersatz: 10% / Steuerbetrag: € 10)**

Welchen Wert würde ich hier für **Betrag-Satz-Ermaessigt** verwenden?

**Comment by lebail** [comment]
Es muss der Brutto-Betrag angegeben werden, also Betrag-Satz-Ermaessigt-1 = € 110,-

**Comment by goosefraba** [comment]
Herzlichen Dank für die Antwort!
