### ISSUE TITLE
Fehlermeldungen der SmartCard

### ISSUE THREAD

**Issue by Alex1130** [a-sit-plus/at-registrierkassen-mustercode#407]
Mit einer A-Trust CardOS 5.3 Smartcard bekomme ich im Echtbetrieb Test
durchschnittlich etwa alle 100 Signaturen:
"The smart card has been reset, so any shared state information is invalid."
und durchschnittlich etwa alle 1000 Signaturen
"Protocol not supported"
Beim nächsten Signaturversuch klappt es dann wieder.
Ich signiere mit Code aus den C# APDU Examples von A-Trust und reinitialisiere vor jeder Signatur neu. (Reinstanzierung des Readers und sign (inkl.prepare Signature))
Frage: ist das ein Anzeichen einer defekten Karte , einer fehlerhaften Verwendung der Karte meinerseits oder eh normal?

**Comment by Alex1130** [comment]
Antwort vom A-Trust Support:
 _"Guten Tag,
die Karte scheint definitiv nicht defekt zu sein. Weitere Unterstützung können Sie von unserem kostenpflichtigen techn. Support beanspruchen.
MfG
Francois Plaiasu"_

**Comment by Flanelli** [comment]
Sehr kundenfreundlich und vor allem höchst aufschlußreich wenn etwas **_defiinitiv_ scheint** ....

**Comment by cmaxmedia** [comment]
Wird Ihnen zwar nicht weiterhelfen, aber aufgrund Ihres Posts hab ich mal einen Gemalto USB Stick von A-Trust mit 500 Anfragen, mit jeweils 1 Sekunde Bedenkzeit dazwischen, bombardiert - ohne Probleme.
Werde gleich nochmal auf 5000 erhöhen, vermute aber dasselbe Ergebnis...

**Comment by wjjw73** [comment]
Stresstest im Automatenmodus - 5000 Belege signiert im 1/2 Sekunden Takt - keine Probleme.
Signierung via ADPUs.

/Werner

**Comment by andreasschiestl** [comment]
Es könnte auch sein dass der Kartenleser nicht ganz funktionstüchtig ist, Ist eventuell ein Ersatzgerät oder eine Ersatzkarte zum testen vorhanden?

**Comment by Alex1130** [comment]
Danke für die bisherigen Antworten und Vorschläge, ich werde morgen Nachmittag einen Stresstest mit diversen Kombinationen (Kartenlesern und Karten) machen.

**Comment by Alex1130** [comment]
Mit 3 Kartenlesern getestet
2xGemalto CT40
1xCHERRY TC 1100
1x CARDOS 5.3 Karte
1x ACOS Karte (die Vergleichsgruppe-leider steht mir keine 2te CARDOS zur Verfügung)
Die Fehler traten mit der CARDOS Karte bei allen drei Readern auf - ein typisches Muster konnte ich nicht erkennen (bei einem Durchgang wurde zunächst über 1300 mal ohne Fehlermeldung signiert! Im Schnitt trat der Fehler "The smart card has been reset, so any shared state information is invalid." bei diesem Durchlauf alle 280 Signaturen auf. Der andere Fehler "Protocol not supported" kam bei den gestrigen Tests gar nicht.
Aufgrund der geringen Verarbeitungsgeschwindigkeit der ACOS Karte bin ich mir nicht sicher wie relevant es ist das diese keine Fehler produziert.
Ich halte es für unwahrscheinlich, dass alle drei Reader defekt sind und werde mich nochmals an A-Trust wenden.

**Comment by samuel4711** [comment]
Hallo,
wollte nochmal vorsichtig nachfragen wie die Sache bei dir ausgegangen ist ?
Ich habe das gleiche Problem. 
Ich nutze den pcsc-sharp .net wrapper.
