### ISSUE TITLE
Notfallszenarien bei Inbetriebnahme (RK Online, PHP)

### ISSUE THREAD

**Issue by daJedi** [a-sit-plus/at-registrierkassen-mustercode#408]
Nachdem ich nun (fast) alle 400 Issues durchgelesen habe, hätte ich noch eine grundlegende Frage an die Community. (falls dergleichen schon beantwortet sein sollte, sorry fürs Übersehen und bitte um URL)

Angenommen ich aktiviere am Montag meine 1. RK im FO, nehme die RK in Betrieb (Signierung über RK Online) und entweder die Verifizierung vom Startbeleg, oder einer der folgenden Belege, schlägt fehl (aus welchem Grund auch immer), kann ich:

1.) das nochmal gerade biegen (korrekte Folgebelege die sich mit dem BMF Tool auch prüfen lassen; Vermerk bei fehlerhaftem Beleg) oder ist diese Kassa (bzw. der Zugang) gänzlich verloren?

2.) notfalls umgehend die Kassa im FO abmelden, neuen Datensatz (neue Kassenbezeichnung, Key, etc.) anlegen, neues Zertifikat ausstellen lassen, alles im FO eintragen und einen 2. Anlauf mit neuer Konfiguration starten? (nach Beheben des Softwarefehlers + Nachtragen sämtlicher Rechnungen in der neuen Kassa)

Es geht um ein Legacy PHP Tooling, bei dem ich in der Anfangsphase den ein oder anderen Fehler befürchte, und mir durchaus schlaflose Nächte bescheren könnte.

Danke schon mal im Voraus!

PS:
etwas off-topic, aber darf ich einen RK Online Zugang als Testzugang verwenden, oder ist dies ausschließlich für tatsächlich erteilte Belege erlaubt? In diversen Issues wurde von unterschiedlichem Verhalten zwischen "Testzugängen" und Zugängen am realem System berichtet und das verunsichert mich ein bisschen.

**Comment by andreasschiestl** [comment]
Ich kann dir nicht alle Fragen beantworten, aber zumindest einen Teil:
Neues Zertifikat (egal ob Smartcard oder Cloud-Lösung) ist nicht nötig, Die Signaturerstellungseinheit kann sowieso von mehreren Kassen verwendet werden. Wird also eine Kasse außer Betrieb genommen (warum auch immer) kann die Signaturerstellungseinheit in einer anderen Kasse weiter verwendet werden (gleiches Unternehmen natürlich vorrausgesetzt).

In §6 Abs (4) steht:
> (4) Der Unternehmer hat unmittelbar nach der Registrierung (§ 16) die Erstellung der Signatur bzw. des Siegels (§ 9 Abs. 3) und die Verschlüsselung des Umsatzzählers (§ 9 Abs. 2 Z 5) unter Zuhilfenahme des Startbeleges zu überprüfen. Entspricht die Erstellung der Signatur bzw. des Siegels oder die Verschlüsselung des Umsatzzählers nicht den Erfordernissen des § 9, so ist die Registrierkasse unmittelbar als Registrierkasse mit ausgefallener Signatur- bzw. Siegelerstellungseinheit im Sinne des § 17 Abs. 4 zu behandeln. Das Prüfergebnis ist zu protokollieren und mit dem Startbeleg gemäß § 132 BAO aufzubewahren.

Ob man das reparieren kann oder nicht kann ich nicht definitv sagen. Ich denke jedoch eher nein, da man aus dem DEP ja nichts löschen darf und somit das DEP ungültig bleibt.

**Comment by daJedi** [comment]
danke für die umfangreiche Antwort! eigentlich ist die Sachlage eh vollkommen klar, aber in der früh hatte ich einen Knoten im Hirn.
