### ISSUE TITLE
Kassen-ID: "beliebiger" UTF8-String?

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#41]
Laut RKSV und Detailspezifikation ist die Kassen-ID eine beliebige UTF8-Zeichenkette, also z.B.  "Kassa_1". Der Unterstrich in diesem Beispiel würde aber ziemliche Probleme beim Auftrennen der Daten der Kompakt-Darstellung verursachen, denn im Gegensatz zu anderen Feldern (Umsatzzähler, Signatur) wird die Kassen-ID _nicht_ BASE64-kodiert.

Abgesehen davon, dass sich das Problem lösen lässt, indem man bei der Eingabe der Kassen-ID einfach keine Unterstriche zulässt, bringt mich das aber dennoch auf die Frage, ob in der Kompakt-Darstellung Escape-Sequenzen erlaubt sind (da es sich laut RKSV um JSON-Strings handelt, müsste man gemäß RFC 7159 sämtliche Zeichen "escapen" dürfen - z.B. mit "\u005F" für den Unterstrich). Das wäre vor allem ein Thema für die Prüftools …

**Comment by pteufl** [comment]
Prinzipiell UTF-8, also auch mit den Escape-Sequenzen, wie sie auch in JSON verwendet werden. Im Sinne des Unternehmens das die Kasse verwendet, muss man wohl aber darauf achten hier eine Registrierung über FinanzOnline sinnvoll möglich ist (Escape-Sequenzen abtippen, oder führende Leerzeichen etc. wären wohl nicht Kundenfreundlich). Esc Sequenzen sind sicher noch ein Thema des Prüftools, bzw. muss man hier noch überlegen ob man Best-Practive BSPs vorgibt (im Sinne der Kundenfreundlichkeit).
Das BSP von oben: Kassa_1 ist zwar ein gültiger UTF-8 String (auch ohne Escape-Sequenz) fällt aber automatisch raus, weil das Trennzeichen eben als solches definiert ist. Solle solchen IDs vergeben werden, würde dies aber gleich beim Prüftool als fehlerhaft markiert werden, bzw. würde damit kein gültiger Startbeleg erstellt werden können.

**Comment by lebail** [comment]
Danke für die ausführliche Antwort.

Auch ich dachte an eine Einschränkung der zulässigen Zeichen und des Formates der Kassen-ID auf ein "vernünftiges" Maß durch die Kassensoftware.
