### ISSUE TITLE
Prüftool pass, FinanzOnline Fail

### ISSUE THREAD

**Issue by xandi1987** [a-sit-plus/at-registrierkassen-mustercode#412]
Hallo,
ich habe versucht eine Registrierkasse zu registrieren und stoße dabei auf Problem. Die Prüftools sagen meine Implementierung passt, FinanzOnline nein passt nicht.

Kann mich jemand unterstützen und mir sagen was hier falsch ist?

Anbei meine Export files für das Testtool,
[qr-code-rep.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/836170/qr-code-rep.txt)
[dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/836171/dep-export.txt)

**Comment by xandi1987** [comment]
Hier AES Schlüssel:
ZGshNDU5MzlEc1prQWY2OWRrZ1Q1ODNKa2Q5MzhJamQ=

Meine Checksumme: SY1w

**Comment by xandi1987** [comment]
Hier der OUput vom FinanzOnline. Wie es aussieht passt meine Base64-Kodierung nicht. 

[OUTPUT_FON.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/836197/OUTPUT_FON.txt)

**Comment by ErichFreitag** [comment]
Ich kann nach Prüfung der obigen Dateien so leider nichts erkennen. Was ist an dem anders, was sie an FON senden?

**Comment by xandi1987** [comment]
Das ist genau der dem wir mit dem App überprüft hätten. 
Wenn mich mir ein Bsp. von der DEMO-Cashbox ansehe, sehe ich dass wir beim verschlüsselten Umsatzzähler ein "Padding" anhängen:

- Mein verschlüsselter Umsatz: fL2Udg7k3XLbeMoNcLtSjw==
- DemoCashBox: 4r1iIdZG

**Comment by ErichFreitag** [comment]
Ihr Umsatzzähler verwendet 16 Bytes (?), der Demo-Code 5 Bytes. Das ist OK und der Umsatzzähler ist auch OK.

Ein weiterer Fehler kann der QR-Code selbst sein. In den Daten erkenne ich so nichts, das heißt aber nicht, dass der grafische QR-Code selbst korrekt ist.

**Comment by cmaxmedia** [comment]
Im Zuge der QR Erstellung ist mir aufgefallen, dass der Generator von Google nicht funktioniert hat. Auch bei der Implementation des Offline Generators (https://www.codeproject.com/Articles/20574/Open-Source-QRCode-Library) funktionierte nur die QR Version ab 13 aufwärts.

Versuchen Sie mal diesen QR Generator Online für den FON App Scan: http://goqr.me/de/

**Comment by xandi1987** [comment]
Das war der korrekte Hinweis danke! Anbei mein Beleg (dieser QR Code wird durch Epson Android SDK erstellt) und einem von einem Generator. 

Die Epson SDK gibt anscheinend einen Zeilenumbruch zur Zeichenkette hinzu.  Das selbe Verhalten habe ich meinem PDF Export+QR Code Generator erhalten. 

Der QR Generator Online (http://www.qrcode-generator.de/) Hat das nicht gemacht. Ich habe mit QR Code-Generierung noch wenig Erfahrung. Hat jemand noch einen Hinweis was genau ich falsch mache?

![20170312_100013](https://cloud.githubusercontent.com/assets/16978514/23830553/cd87c7e0-070d-11e7-965f-5672b9d290f7.jpg)
![static_qr_code_without_logo](https://cloud.githubusercontent.com/assets/16978514/23830554/d080e166-070d-11e7-8481-c9fa13e4b655.jpg)

**Comment by xandi1987** [comment]
Meine Herren, ich muss mich bei Ihnen für diese verschwendete Zeit entschuldigen:

Bei der Standard Encoding in Android gibt die SDK Zeilenumbrüche hinzu:
Base64.encodeToString(encoded,Base64.DEFAULT );

Das hier gefehlt hat war folgende Konfiguration:
Base64.encodeToString(encoded,Base64.DEFAULT | Base64.NO_WRAP);

Leider habe ich beim Abscannen und Überprüfen diese Zeilenumbrüche rausgenommen (sehr tückisch)

Herzlichen Dank für den Einsatz (und das am Sonntag Vormittag)

**Comment by ErichFreitag** [comment]
Bitte gerne - dann war die Zeit verwendet und nicht verschwendet.

**Comment by xandi1987** [comment]
So kann man es auch sehen :) . Herzlichen Dank
