### ISSUE TITLE
Notfallszenario während des Betriebes

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#413]
Hallo, ich möchte ab morgen bei drei der Kunden die RKSV-Lösung "pilotieren" und täglich DEP und den Betrieb kontrolieren. 

Wenn z.B. nach dem zweiten, dritten Tag  festegestellt wird, dass die Registrierkasse nicht funktioniert z.B. Summenspeicherprobleme, Beleg-Nr Probleme wie auch immer dann kann man die Kasse abmelden, Fehler beheben und erneut anmelden.

Bei der Abmeldung der Kasse wird das bisherige DEP und andere wichtige Daten gesichert und eine Beschreibung/Erklärung für das Problem im gleichen Verzeichnis für die eventuelle, spätere Kontrolle abgespeichert.

Genügen diese Massnahmen oder sollte man vielleicht noch etwas zusätzliches tun? bzw. müssen die Belege erneut eingegeben werden oder nicht? oder gibt es bisher Aussagen von Finanzamt wie die Prüfer in solchen Fällen vorgehen werden, weil trotz umfangreichen manuellen- und Unittests schwerwiegende Fehler auftreten können.

Danke

**Comment by ErichFreitag** [comment]
Konkrete Aussagen dazu kenne ich nicht, aber ich würde genau so vorgehen.

Die Belege sind ja nicht verschwunden (bleiben im Kassenjournal) und RKSV-konform müssen sie erst mit 01.04.2017 sein. Was noch sinnvoll sein wird ist, die Kassen mit entsprechenden Namen zu bezeichnen (Pilot-..., Test-...). Und zum Ende hin entscheiden, ob sie vor dem 01.04. die Kassen nochmals außer und neu in Betrieb nehmen oder nicht - je nach Namensgebung und Testverlauf.

**Comment by AlgoLinz** [comment]
Danke Erich
