### ISSUE TITLE
Kleinunternehmer

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#417]
Hallo,

kann mir jemand vielleicht antworten wie funktioniert die Steueraufteilung bei den Kleinunternehmer (Ust wird nicht ausgewiesen)?

Werden die Umsätze dem Nullsatz zugewiesen? Und wie ist es mit dem Umsatzzähler? Umsatzzähler enthält eigentlich die Bruttowerte. Bei den Kleinunternehmer gibt es eigentlich keine Steuer. Wie ist hier vorzugehen?

...und müssen auf den Belegen/Zielrechnungen immer alle Steuersätze aufgeführt werden - auch dann wenn sie im jeweiligen Beleg nicht verwendet werden z.B. alle Positionen enthalten nur Produkte mit 20% Ust oder genügt es nur die wirklich vorhandene Steuersätze darzustellen?

Danke

**Comment by lebail** [comment]
Umsätze der Kleinunternehmer sind unecht steuerbefreit und kommen dementsprechend zum 0%-Steuersatz (siehe Erlass Punkt 4.6.6). In diesem Fall ist Brutto = Netto, und ebendieser Betrag wird zum Umsatzzähler addiert.

Steuersätze auf dem Beleg: Im maschinenlesbaren Code müssen (auf Grund des "starren" Datenformates) zwangsläufig alle USt.-Felder vorhanden sein. Für die Klartextdarstellung sagt §11 (1) RKSV "Betrag der Barzahlung getrennt nach Steuersätzen". Eine "Trennung" bedeutet meiner Meinung nach (aus sprachlicher Sicht), dass nur die tatsächlich vorhandenen Steuersätze berücksichtigt werden müssen; denn Dinge, die ursprünglich nicht vorhanden sind, können auch nach einer "Trennung" nicht auftauchen.

**Comment by Phoniexk** [comment]
Bezüglich Kleinunternehmer: Ich finde das ist aber eine Sache die prinzipiell der Unternehmer mit seinem Steuerberater (oder wem auch immer) klären muss. Es hat ja auch mit den Registrierkassenfunktionen an sich nichts zu tun, ob der Kunde seine Beträge jetzt mit oder ohne UST eintippt.

Also schön wenn man es als Kassenhersteller weiß, aber bei solchen Fragen verweise ich immer an den Steuerberater... wenn meine Auskunft nämlich falsch war, dann bin sozusagen ich der Schuldige bzw. werde zum Schuldigen gemacht. Deshalb bin ich der Meinung, dass ist eine Frage die den Kassenhersteller absolut nicht betrifft.

**Comment by AlgoLinz** [comment]
@lebail: ich habe es auch so implementiert, war mir aber nicht ganz sicher ob es ok ist.
@Phoniexk: stimmt, ob Kleinunternehmer oder nicht, kann ich nicht beurteilen, verweise ich auch immer an den Steuerberater. War mir aber nicht ganz sicher im welchen Steuersatz die Beträge zu speichern sind.

Danke für die Antworten.
