### ISSUE TITLE
DEP-Export

### ISSUE THREAD

**Issue by StefanKDS** [a-sit-plus/at-registrierkassen-mustercode#419]
Hallo,

ich hätte mal eine Frage zum DEP-Export.
Dort ist folgendes anzugeben:
- Signaturzertifikat
- Zertifizierungsstellen

Wir haben nun eine Karte von A-Trust, wo ich ja das Zertifikat selber von der Karte abrufen kann.
Die abgerufenen Daten sollten ja dann meiner Meinung nach dem "Signaturzertifikat" entsprechen, oder ?
Was käme denn dann in das Feld "Zertifizierungsstellen" ?

Ich habe die Seite 56 des Detailfragen Dokuments schon gelesen, aber leider bringt mich das nicht weiter.

Kann mir da jemand auf die Sprünge helfen ?

Danke und Gruß
Stefan

**Comment by ztp-mino** [comment]
Beides ist optional, einfach leer lassen ist ok. In "Zertifizierungstellen" gehört denke ich die Kette an Zertifikaten von Ihrem Signaturzertifikat bis hinauf zur A-Trust Root CA.

**Comment by StefanKDS** [comment]
Leer lassen klingt gut ;-)

Vielen Dank für die schnelle Hilfe.

**Comment by asitplus-pteufl** [comment]
Damit sie es auch offziell von A-SIT Plus haben (damit auch abgestimmt mit BMF). Einfach weglassen wie @ztp-mino das schon beschreibt.
