### ISSUE TITLE
Seriennummer bei ausgefallener Sicherheitseinrichtung

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#42]
Was steht bei ausgefallener Sicherheitseinrichtung im Feld "Zertifikatsseriennummer" der kompakten Darstellung?

Insbesondere dann, wenn die Seriennummer nicht bekannt ist, weil die Sicherheitseinrichtung dermaßen stark beschädigt ist, dass sie nicht einmal ihre Seriennummer mitteilen kann?

**Comment by pteufl** [comment]
Sie meinen jetzt den "Plaintext" der JWS-Darstellung (im Prinzip eh egal, ist eh das gleiche wie im QR-Code bis auf den Signaturwert)?
Da muss trotzdem die Seriennummer stehen, nur dann kann der Beleg auch geprüft werden (Zuordnung Unternehmen). Es sollte hier schon möglich sein, die vorhandenen Sicherheitseinrichtungen zu kennen (auch wenn ein Pool vorhanden ist) und daher die jeweilige Seriennummer eintragen zu können. 
Da definitiv auch ein Pool von Sig-Einrichtungen möglich ist, kann einfach auch auf eine funktionierende umgeschaltet werden. Sollten alle Sicherheitseinrichtungen in diesem Pool ausgefallen sein, dann muss man wohl eine Seriennummer der ausgefallenen Sicherheitseinrichtungen (des Pools) verwenden. Welche ist dann wohl nicht so wichtig, weil ja in dem Fall alle ausgefallen sind und wenn es sich um einen nicht-temporären Ausfall handelt alle Sicherheitseinrichtungen als beschädigt gemeldet werden müssen.

**Comment by lebail** [comment]
Auch hier: danke für die ausführliche Antwort.

Da die Registrierkasse die Seriennummern der ihr zugeordneten Sicherheitseinrichtungen normalerweise speichern wird, war meine Frage zugegebenermaßen eher überflüssig …
