### ISSUE TITLE
Testtool

### ISSUE THREAD

**Issue by StefanKDS** [a-sit-plus/at-registrierkassen-mustercode#420]
Hallo, 
ich habe gerade einmal versucht Beispieldateien durch das Prüftool zu jagen und bekam folgende Fehlermeldung:
Your JVM does not provide the unlimited strength policy. However, this policy is required to enable strong cryptography. Please install the required policy files.

Kann mir da jemand weiterhelfen ?

**Comment by ckvsoft** [comment]
Funktioniert Google nicht mehr?

http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

**Comment by Skerge12** [comment]
Hatte das selbe Problem
Hier die Lösung: 
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/244
