### ISSUE TITLE
Barbeleg immer als extra Beleg zu Rechnung

### ISSUE THREAD

**Issue by andreasschiestl** [a-sit-plus/at-registrierkassen-mustercode#421]
Hallo!

Die Anfrage betrifft nicht meine Software sondern die Zweitkasse von einen meiner Kunden. Dieser hat eine Gastro-Kasse (KR 2012 konform) für welche es laut Hersteller kein Update mehr für die RKSV gibt. Eine Neuanschaffung einer gleichwertigen Kasse ist finanziell nicht möglich und eine billigere Option hätte erhebliche Nachteile durch höheren Arbeitsaufwand.

Nun ist es ja möglich, dass ein Kunde der eine Zielrechnung (zB Zahlung per Überweisung, nicht signierungspflichtig) erhält sich entscheidet diese per Barzahlung beim Unternehmer vor Ort zu bezahlen. In diesem Fall ist ein Barbeleg (mit Verweis auf Rechnung) auszustellen und der Rechnungsbetrag bzw. Betrag der Barzahlung mit 0% USt zu erfassen (da USt bereits auf der Zielrechnung ausgewiesen). Wäre es nun möglich alle Rechnungen der nicht updatefähigen Kasse als Zielrechnungen zu sehen und mit einer billigen Kasse signierte Barbelege zu erstellen um die RKSV zu erfüllen und diese 2 Belege (Rechnung + Barbeleg) dem Kunden zusammengeheftet auszuhändigen?

Danke im Vorraus für eure Meinungen und Ideen.

**Comment by Flanelli** [comment]
Sollte grundsätzlich wohl m.E. möglich sein und auch dem Gesetz nicht wiedersprechend
**WENN**
wirklich jeder Beleg dieser sogenannten Zweitkassa zu 100& dem Rechnungslegungsgesetz entspricht
und somit auch als Ausgangsrechnung in der FIBU als solche verbucht wird.

Im Prinzip ist es auch nichts anders als eine unsignierte Rechnung in der RJSV-Kassa da man die
Rechnung an sich ja nicht signieren muß wenn auf dieser Rechnung kein BAS-Zahlungsvorgang aufscheint.
Der lesbare Zusammengang zwischen unsignierten rechnungen und den später folgenden signierten Zahlungen zu dieser Rechnung muß in bneiden Fällen jedenfalls über eine eindeutige Rechnungsnummer
gegeben sein.

**Comment by andreasschiestl** [comment]
Gerade mit der WKO telefoniert:
Das ist eine beliebte Lösung zu der bestehenden Kasse einfach eine billige RKSV-Kasse zu stellen und damit signierte Barbelege zu erstellen. Laut WKO wird das in vielen Unternehmen gemacht, da teilweise auch Kassensysteme aus den Ausland (z.B. Deutschland) verwendet werden, wo die Kassenhersteller aufgrund der geringen Nachfrage kein RKSV-Update anbieten oder der Preis dafür zu hoch ist.

Vorgehen ist wie schon beschrieben, der Zahlungsbetrag wird mit 0% USt verbucht mit Referenz auf Rechnungsnummer.
