### ISSUE TITLE
DEP Export immer vollständig? Über mehrere jahre hinweg? 

### ISSUE THREAD

**Issue by Josma** [a-sit-plus/at-registrierkassen-mustercode#425]
Ich habe in einem Issue hier gelesen, das der DEP Export immer vollständig sein muss.
Ist das korrekt? 

Wenn die Kassen mal 4 - 5 Jahre laufen wird das spannend werden.. Warum immer das ganze DEp exportieren? das ist doch Sinnlos!

Oder kann man sich das sparen, wenn man so wie bei uns alles sowieso auf 3 Standorten gespeichert hat?
einmal in der Filiale, einmal in der Zentrale und diese wird noch gespiegelt...

Muss man dann trotzdem auch noch exportieren?

Das macht irgendwie keinen Sinn und kostet einiges an Zeit und Speicher (nicht gelich - aber über die Jahre)

Unsere Filialen haben zwischen 200MB und 2 Gb Belegdaten in 5 Jahren angeammelt... 2 GB exportieren ist nicht mehr ganz so lustig... (OK - im DEP ist weniger Info als in unseren Belegdaten) 

Es geht ja nur darum, das keine Umsatzdaten der Kassa verlorengehen. meines erachtens ist das in unserem fall mehr als gegeben und ein Export wäre eigentlich gar nicht mehr nötig. (es müssten schon zeitgleich die Filiale, die zentrale und der backupstandort abbrennen) 

Ich befürchte aber, das man es trotzdem so machen wird müssen, oder?

**Comment by ErichFreitag** [comment]
Gemäß RKSV ist das RKSV-DEP zumindest vierteljährlich zu sichern. Die Sicherung entspricht technisch einem Export ab dem Startbeleg und hat immer vollständig zu sein. Sinn ist eine finanztechnische Absicherung, damit die Barumsätze zumindest bis zum letzten Vierteljahr nachvollziehbar sind. Eine Zeile im RKSV-DEP hat rund 300 Zeichen.

**Comment by Josma** [comment]
Danke nochmal für die Bestätigung.
Wie gesagt, halte das aber für völlig übertrieben, wenn man unser Szenario betrachtet. (Das DEP steht ja auch in der DB bei uns) 
Das ist dann die 4te Sicherung. Also das Backup vom Backup vom Backup.

Ich weiß nicht, ob es was bringt, wenn man das hier in diesem Forum anmerkt ;-) 

Aber gut, um da mal auf der sicheren Seite zu sein werden wir das immer komplett exportieren. und bis es größenmäßsig ein Problem werden wird vergeht ja sowieso einige zeit und bis dahin kann sich ja noch einiges ändern. bin mir sicher, dass sich dieser punkt ändern wird. Kann mir nicht vorstellen, das wir die einzigen sind, die das als (zukünftiges) Problem sehen. 

300 zeichen bedeutet also immer 1KB (Standard blockgröße) oder 3 DEP Einträge passen in 1 KB...
Hmmm naja wie gesagt bei 300 - 400 Belegen in einer Kassa pro tag... also rund 2,7 MB pro Monat.

Hört sich nicht so schlimm an. aber wenn man dann insgesammt 25 Kassen hat....

**Comment by ep27** [comment]
Mir stellt sich die Frage, ob man nicht in einem solchen Fall einfach die Kassa außer Betrieb stellt und neu anfängt.

Auch im Hinblick darauf, dass man zwar die Belege 7 Jahr aufheben muss, aber wenn man die Kasse zB. 10 Jahre in Betrieb hat (wenn ich mal von der naiven Annahme ausgehe, dass sich so lange das Gesetz nicht ändert und wir alles anders machen müssen), sind die ersten Daten in der RK schon 17 Jahre alt, wenn man das DEP endlich entsorgen darf, und das kommt mir dann doch übertrieben vor...
