### ISSUE TITLE
Vorgehensweise bei Ausfall / Innbetriebnahme der Signatureinrichtung

### ISSUE THREAD

**Issue by aortner** [a-sit-plus/at-registrierkassen-mustercode#427]
Fallbeispiel:

Karte nicht eingesteckte / Lesegerät ausgesteckt usw....

im dep wird Signatureinrichtung ausgefallen codiert als Signatur gespeichert.

Kann/muß ich den QR Code auch so drucken - bzw . fällt er dann weg?

Im dep und in der kasse sind die umsätze und belege vollständig vorhanden muss ich beim
Wiederfunktionieren einen Sammelbeleg erstellen - das würde den Summenspeicher dadurch für diesen Zeitraum verdoppeln?

Danke

**Comment by Flanelli** [comment]
Ein Sammelbeleg ist ein Nullbeleg, dieser erhöht nicht den Umsatzspeicher.
Der Qr-Code beinhaltet als Sigantur den codierten Wert des Strings
"Sicherheitseinrichtung ausgefallen"  also
U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==
Wenn Sie keinen QR-Code mehr erstellen können und den auch nicht am Beleg andrucken
können ( also auch einen mit der sogenannten "Ersatzsignatur" dann ist die Kassa komplett
ausgefallen und wäre wohl außer Betrieb zu nehmen,

**Comment by aortner** [comment]
Danke die Erstellung des Nullbeleges ist mir klar.  

Ich kämpfe mit dem Satz:

Nach Wiederinbetriebnahme der Signatur- bzw. Siegelerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern.


Was soll auf dem Sammelbeleg aber draufstehen?

**Comment by Phoniexk** [comment]
>§ 17 (4) Bei jedem Ausfall der Signatur- bzw. Siegelerstellungseinheit sind die Barumsätze auf einer anderen Registrierkasse zu erfassen, die über eine aufrechte Verbindung zu einer Signatur- bzw. Siegelerstellungseinheit verfügt. Sollte dies nicht möglich sein, hat der Unternehmer bei der Aufbereitung und Verwendung des maschinenlesbaren Codes (§ 10) an Stelle des Signatur- bzw. Siegelwertes des betreffenden Barumsatzes (§ 10 Abs. 2 Z 8) die Zeichenkette „Sicherheitseinrichtung ausgefallen“ im Ergebnis der Signatur- bzw. Siegelerstellung laut Z 6 der Anlage zu verwenden. Der Hinweis „Sicherheitseinrichtung ausgefallen“ ist zusätzlich gut sichtbar am Beleg (§ 11) anzubringen. Nach Wiederinbetriebnahme der Signatur- bzw. Siegelerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern.

Also Anstelle der Signatur wird überall "Sicherheitseinrichtung ausgefallen" verwendet (maschinenlesbarer Code sowie DEP). Sprich DEP (inkl. Umsatzzähler) läuft ganz normal weiter, und zusätzlich muss der Ausfall gut sichtbar am Beleg zu sehen sein.

**Wichtig**: Sicherheitseinrichtung ausgefallen, darf erst gemacht werden, wenn keine Registrierkasse mit funktionierender SEE mehr vorhanden ist. Solange es noch eine Registrierkasse mit funktionierender SEE gibt, DARF nur mehr auf diesen einen Kasse gebucht werden, sprich alle anderen Kassen müssen gesperrt sein, erst wenn die letzte ausfällt, dürfen wieder alle mit Sicherheitseinrichtung ausgefallen betrieben werden, sobald wieder eine funktioniert, müssen die anderen wieder gesperrt sein.

**Comment by aortner** [comment]
Danke Phoniexk ist mir klar!

Aber was soll auf dem Sammelbeleg  draufstehen?

Oder reicht einfach ein Nullbeleg?

**Comment by Flanelli** [comment]
@aortner 
Wenn Sie es einrichten können wäre z.B. folgender Text am Sammelbeleg empfehlenswert.
SAMMELBELEG 100237 - 100251 ( 4.988,58 )  2017-03-14 14:42 -  2017-03-14 17:18"
Erste Belegnummer bis letzte Belegnummer des Ausfalles 
Die Summe dieser ausgefallenen Belege
Erster Belegnummer-Datum-Zeitstempel bis letzte BelegnummerDatum-Zeitstempel des Ausfalles

**Comment by Phoniexk** [comment]
> Kann/muß ich den QR Code auch so drucken - bzw . fällt er dann weg?

Deshalb hatte ich das Gefühl, es ist nicht ganz klar ;)

Der Rest wurde von Flanelli beantwortet. Obwohl wir nur die erste Belegnummern bis letzte belegnummer aufdrucken (so wie im Erlass erläutert). Über unsere Auswertungen kann der Prüfer jederzeit Zeitraum, summen, etc. auswerten.

**Comment by aortner** [comment]
Ok. Qr  Code und DEP wird wie beschrieben erstellt und ausgedruckt (Sig... ausgefallen + QR Code)

Beim Wiederfunktionieren wird ein Nullbeleg erstellt. Eigentlich müsse es auch möglich sein die Daten händisch auf dem Nullbeleg einzutragen und zu archivieren.

**Comment by Flanelli** [comment]
DeSammelbeleg muß zwar nicht ausgedruckt werden aber er steht ja nicht nur im RKSV-DEP sondern
auch im Detail-DEP da es letzendlioch ja auch ein Beleg ist und da wird es sich n icht sehr gut machzen
wenn Sie auf einem Druck irgendetwas händisch ergänzen das nicht ident mit dem Text im Detail-DEP ist.
Zumindest nicht was die eindeutige Identifizierung der ausgefallenen beleg betrifft.

**Comment by Flanelli** [comment]
Im Erlass steht unter 3.6.1 der Hinweis dass auf dem Sammelbelg ersichtlich sein muß welche Belege 
davon betroffen waren ( z.B. durch nummer bon bis )

**Comment by aortner** [comment]
Ganz verstehe ich den Sinn zwar nicht. Der Nullbeleg ist OK.

Eigentlich habe ich ein vollständiges RKSV-DEP (nur ohne Signatur) und ein vollständiges DEP meiner Kasse.
Eigentlich fehlt kein Beleg. Beim Verketten der 2. sieht man das alles in Ordnung und vollständig ist.

**Comment by Flanelli** [comment]
@aortner 
Ganz unter uns - es liest ja sonst keiner mit :-)
Je weniger man über den Sinn nachdenkt umso schneller kommt man zu einem positiven Ergebnis, :-)

**Comment by aortner** [comment]
Weil es ja keiner mitbekommt!

Das ganze ist eine Anpassung einer Internationalen Version eines Apps für IOS.
Versuchen sie mal jemand das auf englisch jemanden zu erklären.

Ich bin auf das Prüftool der Finanz gespannt welches die beiden DEP dann verknüpft und das für mind. 100 verschiedenen Kassensysteme.......

**Comment by Flanelli** [comment]
@aortner 
Nunja, wer weiß warum man darauf verzichtet hat das format der beiden DEP'S nicht zwingend
zu vereinheitlichen. Am Zeitdruck bzw, einem Entgegenkommen an Kassengersteller kann es wohl
nicht gelegen sein. Aber wie Herr Dr. Teufl ja schon vielfach angemerkt hat sollten wir dieses Forum
nicht zu sehr für organisatorische Diskusssionen heranzoehen sondern uns auf technische Details
beschränken. Somit klinke ich mich dann mal aus dem Thema vorerst aus :-)
