### ISSUE TITLE
Inbetriebnahme

### ISSUE THREAD

**Issue by webITSol** [a-sit-plus/at-registrierkassen-mustercode#43]
1.) Es ist ja vorgesehen, dass die Inbetriebnahme mit der Erstellung eines "Null Belegs" und der Initialisierung des Umsatzzählers auf 0 beginnt.
Das ist jedoch nicht praktisch wenn Kunden die Registrierkasse schon vor 2017 in Betrieb nehmen aber erst Anfang 2017 die Kasse(n) in Finanz Online (FON) anmelden. Soll dann der Umsatzzähler wirklich benutzergesteuert (nämlich erst nachdem die Anmeldung in FON erfolgt ist) zurückgesetzt werden?
2.) Der Schlüssel zum Verschlüsseln des Umsatzes soll ja ebenfalls über FON kommuniziert werden. Da der Schlüssel eine bestimmte Länge haben soll und Base64 codiert ist, ist der Austausch aber eher umständlich, und eine freie Schlüsselwahl ist praktisch ausgeschlossen. Wie genau soll das in der Praxis ablaufen? Wird der Schlüssel über FON vorgegeben oder wählen sich die Benutzer einen Schlüssel? Oder müssen sie sich einen generieren lassen und ihn aufschreiben?

**Comment by enengi** [comment]
Meine Frage zu 1.):
Wo steht denn geschrieben, daß der Umsatzzähler bei der Inbetriebnahme auf 0 gesetzt werden soll?

**Comment by webITSol** [comment]
Das steht nicht so im Verordnungsentwurf, aber dass ein Null Beleg zur Inbetriebnahme erstellt werden soll steht drin.

**Comment by enengi** [comment]
Hmm, ich würde es so verstehen, daß der Zahlbetrag für den Startbeleg 0,00 Euro sein soll.
Eine Vorschrift, daß der Umsatzzähler auf 0 gesetzt werden soll, habe ich bislang nicht gesehen ...

Hier einige Textstellen, die zum Thema passen:

[RKSV](https://www.bmf.gv.at/steuern/BGBLA_2015_II_410.pdf) § 6:
> (1) Die Inbetriebnahme der Sicherheitseinrichtung für die Registrierkasse besteht aus der Einrichtung des Datenerfassungsprotokolls (§ 7) und der Ablage der Kassenidentifikationsnummer als Bestandteil der zu signierenden Daten des ersten Barumsatzes mit Betrag Null (0) (Startbeleg) im Datenerfassungsprotokoll.

RKSV § 8:
> (2) Zu jedem Monatsende sind die Zwischenstände des Umsatzzählers zu ermitteln (Monatszähler) und als Barumsatz mit Betrag Null (0) und elektronischer Signatur der Signaturerstellungseinheit (Monatsbeleg) im Datenerfassungsprotokoll der Registrierkasse zu speichern.

[EB_RKSV](https://www.bmf.gv.at/steuern/EB_RKSV.pdf) (habe keine Ahnung, ob dieser Entwurf noch Gültigkeit hat):
> Zu § 6:
> Eine erfolgreiche Inbetriebnahme der Sicherheitseinrichtung einer Registrierkasse liegt mit Vorliegen eines erfolgreich geprüften Belegs des ersten Barumsatzes der Registrierkasse (Startbeleg) vor. Davor müssen die Signaturerstellungseinheit dieser Registrierkasse über FinanzOnline gemeldet, das Datenerfassungsprotokoll in der Registrierkasse eingerichtet und die Kassenidentifikationsnummer als Verkettungswert für die Signaturerstellung des Startbeleges im Datenerfassungsprotokoll abgelegt sein. Der Startbeleg kann durch Eingabe eines Barumsatzes mit Betrag 0 ausgelöst oder programmgesteuert angelegt werden. Der Startbeleg hat als fortlaufende Nummer „eins (1)“, als Tag der Belegausstellung das Datum der Inbetriebnahme der Sicherheitseinrichtung (§ 6), als Menge „Null (0)“, als handelsübliche Bezeichnung „Startbeleg“ und als Betrag der Barzahlung „Null (0)“ zu enthalten. Der Startbeleg ist als Grundaufzeichnung zumindest sieben Jahre aufzubewahren (§ 132 BAO). Bis zum 31. Dezember 2016 kann eine Sicherheitseinrichtung auch ohne Prüfung des Startbeleges in Betrieb genommen werden, die Prüfung des Startbeleges ist dann bis zum 31. Dezember 2016 nach Registrierung der Signaturerstellungseinheit nachzuholen. Für die Prüfung des Startbeleges wird das BMF eine Prüfsoftware (z.B.: Mobile App, Web-Sevice) zur Verfügung stellen, die den am Beleg ausgegebenen maschinenlesbaren Code auslesen und die darin enthaltenen Daten (Seriennummer des Zertifikates, Signaturwert, Verschlüsselung des Umsatzzählers, etc.) mit den in der Datenbank über Sicherheitseinrichtungen für Registrierkassen gespeicherten Daten auf Plausibilität überprüfen kann.

**Comment by asitplus-pteufl** [comment]
Umsatzzähler 0 ist z.B. (damit Sie auch eine offizielle Stelle haben (BMF) im Erläuterungsdokument unter der Startbeleg Erstellung definiert.
Inbetriebnahme: Es wird dazu sehr bald noch zusätzliche Erläuterungen geben, sowohl auf technischer Seite als auch auf organisatorischer Seite. Die Fälle für 2016/2017 werden dort noch genau behandelt, Allgemeine Antwort schon dazu, es werden alle diese Aspekte berücksichtigt (und auch etwaige Unklarheiten, Schwierigkeiten die oben genannt wurden).
