### ISSUE TITLE
Signaturrückgabe der Karte entspricht nicht dem Aufabu in der Doku

### ISSUE THREAD

**Issue by StefanKDS** [a-sit-plus/at-registrierkassen-mustercode#430]
Hallo,

die Rückgabe der Signatur von der Karte entspricht nicht dem Aufbau den ich erwartet habe.

Laut Doku soll ein dreiteiliger Wert ( getrennt durch einen Punkt ) herauskommen.

Mein Ergebnis ist das:
- 64 Zeichen

»BX~þZ”ŽÑ:\x14\0     usw. Keine Punkte und das sieht mir recht falsch aus

Irgendeine Idee ?

Gruß

**Comment by StefanKDS** [comment]
Die Ausgabe kommt übrigens von dem Beispiel von A-Trust:

BYTE pbRecvBuffer[258];
	BYTE Hash[32 + 6];
	DWORD dwRecvLength;

	LONG rv;

	Hash[0] = 0x00;
	Hash[1] = 0x2A;
	Hash[2] = 0x9E;
	Hash[3] = 0x9A;
	Hash[4] = 32;

	for (int i = 0; i < 32; i++)
		Hash[5 + i] = i;
	Hash[37] = 0xFF;


	dwRecvLength = sizeof(pbRecvBuffer);
	unsigned char cmd1[] = { 0x00 , 0xA4 , 0x00 , 0x0C, 0x02, 0xDF, 0x01 };
	unsigned char cmd2[] = { 0x00 , 0x20 , 0x00 , 0x81 , 0x08,  0x26, 0x12, 0x34, 0x56, 0xFF, 0xFF, 0xFF, 0xFF };

	dwRecvLength = sizeof(pbRecvBuffer);
	rv = SCardTransmit(hCard, &pioSendPci, (unsigned char*)&cmd1, sizeof(cmd1), NULL, pbRecvBuffer, &dwRecvLength);

	dwRecvLength = sizeof(pbRecvBuffer);
	rv = SCardTransmit(hCard, &pioSendPci, (unsigned char*)&cmd2, sizeof(cmd2), NULL, pbRecvBuffer, &dwRecvLength);
	dwRecvLength = sizeof(pbRecvBuffer);
	rv = SCardTransmit(hCard, &pioSendPci, (unsigned char*)&Hash, sizeof(Hash), NULL, pbRecvBuffer, &dwRecvLength);

	std::vector<unsigned char> sig;
	for (size_t i = 0; i < dwRecvLength - 2; i++)
		sig.push_back(pbRecvBuffer[i]);

    std::string signature (sig.begin (), sig.end ());

**Comment by lebail** [comment]
Das passt so. Die Karte liefert die "rohe" Signatur, und die ist binär und 64 Byte lang. Die Weiterverarbeitung müssen Sie selbst machen.

**Comment by ErichFreitag** [comment]
Bezüglich einem dreiteiligen Wert kann ich nichts sagen.
64 Zeichen Signatur sind gut. Die sind aber binär und müssen noch BASE64-codiert werden, damit sie lesbar werden.

**Comment by StefanKDS** [comment]
Ich gehe mal davon aus, dass es sich mit dem Zertifikat genau so verhält wenn ich es abrufe

**Comment by lebail** [comment]
Ja, nur dass es wesentlich länger ist und daher in mehreren Etappen abgerufen werden muss (da die Karte nur 256 Byte auf einmal liefern kann). Die nötige Schleife ist aber in dem A-Trust-Beispielcode schon enthalten.

**Comment by StefanKDS** [comment]
Jetzt verstehe ich das erst.....
Da ich keine JWS fähige Bib benutze muss ich jetzt den generellen aufbau selber vornehmen.
ich habe von der Karte nur den "payload" bekommen

**Comment by FriNagy** [comment]
kannst bei mein Source nachscahuen,  #414 
ich verwende auch das APDU von A-Trust, dabei auch das fertige regkp.exe 

mit "REGKP -xc" kannst das Zertifikat auf .\cert.hex  ausgeben
und bei https://certlogik.com/decoder/  testen lassen
