### ISSUE TITLE
A-SIT Prüftool OK aber Startbeleg FAIL

### ISSUE THREAD

**Issue by OskarSniper** [a-sit-plus/at-registrierkassen-mustercode#432]
Hallo zusammen !

Frage: Fiskalbox, Chip mit Steuernummer, Prüftool zeigt:

APP.JSON = VERIFICATION_FROM_APP = PASS
DEP.JSON = überall PASS
VERIFICATION_FROM_CASHBOX = pass

Benutzerschlüssel, Seriennumer DEC und KassenID wurden kopiert und nicht abgeschrieben (auch FON sagt alles ok, man weiß nicht warum die App einen fehlerhaften Startbeleg meldet und es nicht geht). In FON ist die KassenID allerdings 3 x angelegt (davon 2 x Außerbetriebnahme, da die erste Chipkarte fehlerhaft war). Hat jemand schon einmal dieses Problem gehabt und wie könnte man das lösen (außer eine andere Box nehmen und neuerlich Starbeleg erstellen) ? Kann es sein, daß mehrere gleiche KassenID diesen Fehler auslösen ?

**Comment by ErichFreitag** [comment]
Ein System mit einer Chipkarte kann kein geschlossenes (Gesamt-)System sein.

**Comment by OskarSniper** [comment]
R1-AT1 ... soll mir recht sein, ändert aber nichts daran, daß der Startbeleg lt. Prüftool OK ist, die APP aber einen Fehler meldet.

**Comment by cmaxmedia** [comment]
Versuchen Sie es mal mit diesem QR Generator: http://goqr.me/de/

**Comment by OskarSniper** [comment]
Es hat nichts mit dem QR Code zu tun, der Inhalt vom Code entspricht genau dem vom A-SIT Tools Wert RECEIPT aus dem RKSV_DEP_EXPORT (keine Zeilenumbrüche, etc etc). Auch KassenID usw ist völlig korrekt. Aus meiner Sicht ist der Startbeleg völlig in Ordnung, trotzdem meckert die APP.

**Comment by ztp-mino** [comment]
Was im QR Code stehen soll ist nicht das gleiche wie was im DEP steht. Im DEP steht ein JWS String mit Header.Payload.Signature, im QR-Code soll `_R1-AT...._<signature>` stehen.

**Comment by OskarSniper** [comment]
@ztp-mino ... das ist klar; im A-SIT Tool kann man das im /RESULT/DEP.JSON selbstverständlich auslesen.
...unter  "verificationId" : "RKSV_DEP_EXPORT", enthlt der Wert "RECEIPT" : "_R1-AT1_usw...blabla genau den Inhalt des QR Startbelegs (sofern man natürlich alles richtig gemacht hat...

**Comment by OskarSniper** [comment]
@ErichFreitag ... leider wie immer (soweit ich weiß) Fehler in der Kryptographie ... der Fehler ist im FON leider nicht unbedingt sehr aussagekräftig und gibt keinen Rückschluss auf das Problem.

**Comment by ErichFreitag** [comment]
Dann posten sie bitte den QR-Code, den zugehörigen cryptographicMaterialContainer und die Fehlermeldung.

**Comment by OskarSniper** [comment]
Gerne - QR aus dem Startbeleg:

`_R1-AT1_1609001141_0000001_2017-03-14T09:10:36_0,00_0,00_0,00_0,00_0,00_ttH1IgGDvb0=_49f88543_JT5hHfgXtz8=_5KvR26lD95J653h8qM65hT8F/XbdaR6VQGnmOFaA1NLgvPfA3olflazK+DlR+MCXJ/bDZgTAWkXffQots5EjGA==
`
CMC:

```
{
  "certificateOrPublicKeyMap":  {
    "49f88543":  {
    "id": "49f88543",
    "signatureDeviceType": "CERTIFICATE",
    "signatureCertificateOrPublicKey": "MIIFTTCCAzWgAwIBAgIESfiFQzANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDMxMzExMTcxOVoXDTIyMDMxMzEwMTcxOVowRjELMAkGA1UEBhMCQVQxIDAeBgNVBAMMF1N0ZXVlcm51bW1lciAxMjM1MC83NzkwMRUwEwYDVQQFEwwzOTk5MzQwNjY5MTcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQYZT5d0zkhaqmR+kKXS7KtZOdf8zjDHRjVQe8DB3k7er4uJBe6Ae3d+SIKQsa/evtgoZDINibHz2E95sq5pci5o4IBsDCCAawwfwYIKwYBBQUHAQEEczBxMEYGCCsGAQUFBzAChjpodHRwOi8vd3d3LmEtdHJ1c3QuYXQvY2VydHMvQS1UcnVzdC1SZWdpc3RyaWVya2Fzc2UtQ0EuY2VyMCcGCCsGAQUFBzABhhtodHRwOi8vb2NzcC5hLXRydXN0LmF0L29jc3AwEwYDVR0jBAwwCoAIQEeeruOQ37YwHwYDVR0RBBgwFoEUc2VydmljZUB3b2xsbWVpbGUuYXQwEQYDVR0OBAoECEdM8HKS5DfRMA4GA1UdDwEB/wQEAwIGwDAkBgcqKAAKAQsBBBkMF1N0ZXVlcm51bW1lciAxMjM1MC83NzkwMAkGA1UdEwQCMAAwWAYDVR0gBFEwTzBNBgYqKAARARgwQzBBBggrBgEFBQcCARY1aHR0cDovL3d3dy5hLXRydXN0LmF0L2RvY3MvY3AvQS1UcnVzdC1SZWdpc3RyaWVya2Fzc2UwRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybC5hLXRydXN0LmF0L2NybC9BLVRydXN0LVJlZ2lzdHJpZXJrYXNzZS5DQTANBgkqhkiG9w0BAQsFAAOCAgEATet9Ca6+GPId3oKH7wmIJ7IMTteURVZxqyqkiunlDNdKFLNVCqFatPOLj0uRZyGaUDZOVsX125P4YbHJcjfBrqK+I8h1vrPy8G/DbxYL1Y02R4Fhwspcyj53aCC21nY30IUgsLuQGKvK3ZtcJVG+v3IU4j+KIqV0g4BuSxScfYDMH9ycAaD07G99eJSR/9MtQK6L5nMHL3zpbAJpgDgqmJGCee2lekcWJvHAhLv1YJnL2iZy68TaIj0XDy1Q45DCYQFNnd4LeQOVxQrxDVr3hhI+gjPgY8j22+dwN/slkUvBceeLUln7arnBfJqi3qqxwZGF+oFYjVlVkd+3QmYtR3ndtoY5QcJuOefjjBFZ7HLVcrDJtMX5MwJY+SVPaKJ66IjMAqXCn6/5RsOwSASd6gyGSq09xrYkHeZUgF9yseDyhcyY/MCdRnFSiTsSBL+3wivymBC7sx2gm6NINtIeuCjx9+mhZMfv9/ACYbwDLTGCGnvx+DHOUMgXi1R1rcTd6usYAsRkVY6dGf11/eQdc9Qn+jed6LZ8NYLO7I/LA8IN81H7irf/02YH65e1ScBuF9zSlOYQkrEbBIFbCy8nYEc2x1bpgzCkWzyAmZArYVkdqJiQ+y6xZZy9X6ZzzTIgFllSrFLAdNNq244p4UIGeLgyHoWeeFZCEmZ/IIMJqZM="
    }
  }
}

```

**Comment by OskarSniper** [comment]
Benutzerschlüssel auch dazu ?

**Comment by ErichFreitag** [comment]
Der Vollständigkeit halber ja bitte. Signaturprüfung ist bei mir OK.

**Comment by OskarSniper** [comment]
Benutzerschlüssel 
`eVm6ON8pQuxKOWQsL6I8eiJIR5hvBU6Md/Y2U1YDe58=
`

**Comment by OskarSniper** [comment]
Kleiner Nachtrag: Es wurde zwischenzeitlich die Fiskalbox getauscht und ein neuer Startbeleg gedruckt. Somit ist das Problem zwar erledigt (weil jetzt alles ok ist), dennoch bleibt die Unsicherheit warum ein "vorgeprüfter" OK Startbeleg als fehlerhaft bei FON behandelt werden kann.

**Comment by ErichFreitag** [comment]
Bei mir sind alle Prüfungen OK. Falls noch erforderlich bitte den QR-Code als Grafik posten.

**Comment by OskarSniper** [comment]
QR als Grafik ... was soll das bringen ? Auch bei mir sind alle Prüfungen mit dem A-Sit OK, dennoch wurde dieser Startbeleg in der BMF APP (und somit auch in FON) als fehlerhaft erkannt. Es wäre wirklich schön, wenn hier jemand aus dem BMF mitliest und nachsehen kann, aus welchem Grund das möglich ist.

**Comment by ErichFreitag** [comment]
Weil sich manchmal im QR-Code Fehler in der Grafik einschleichen.

**Comment by OskarSniper** [comment]
In dem Fall ist der Inhalt des QR Codes aus der Kassa ident mit dem gelesenen Code sowie dem tatsächlichen Inhalt. Praktisch ein 100% einwandfreier Startbeleg aber dennoch nicht OK in FON. Wie gesagt - lt. Rückmeldung Kassenhersteller und auch aus dem Support des BMF hat man dafür keine Erklärung. Erst nach Tausch der Box und neuerlichem OK Beleg war die App zufrieden und der neue Startbeleg wurde als OK erkannt. Ich persönlich kann mir nur vorstellen, daß mehrere gleiche KassenIDs in FON (1 aktive und 2 außer Betrieb) irgendeine Auswirkung auf die Prüfung hatten, wenngleich der Support vom BMF das verneint hat.
