### ISSUE TITLE
Wechsel von Zertifikaten

### ISSUE THREAD

**Issue by robongit** [a-sit-plus/at-registrierkassen-mustercode#434]
Habe hier mehrfach gelesen, dass die abwechselnde oder wechselweise Verwendung von Zertifikaten (SmartCards) zulässig ist, solang sie auf das entsprechende/selbe Unternenhem ausgestellt sind.

Auch die Testsuites machen ja davon redlich Gebrauch. 

Jetzt lese ich gerade im RSI Dokument (RKSV, Fassung vom 01.04.2017.pdf) auf Seite 14 unter

**7. Anmerkung zum Wechsel des Signatur- bzw. Siegelzertifikats** 

> Bei einem Wechsel des Signatur- bzw. Siegelzertifikats muss garantiert sein, dass weitere Belege nicht mehr mit dem vor dem Wechsel verwendeten Zertifikat signiert werden dürfen

Jetzt bin ich total verunsichert!
Was ist nun korrekt?

**Comment by ErichFreitag** [comment]
Das (7.) gilt nicht mehr, siehe z.B. https://www.xing.com/communities/posts/wechsel-des-signatur-bzw-siegelzertifikats-1012596953.

**Comment by robongit** [comment]
Vielen Dank für die turboschnelle Antwort!!

**Comment by Flanelli** [comment]
UNFASSSBAR
(RKSV, Fassung vom 01.04.2017.pdf) ???
Anscheinend leben wir alle in der Vergangenheit wenn diese Fassunf aus der Zukunbft stammt.
Wenn das BMF aber damit sagen will dass diese Fassung erst ab dem 01.04.2017 gilt dann sind
alle bisherigen Zeetifikatswechsel ohne den entsprechenden Eintrag im DEP ungülig.
Anscheinend sind dem Gesetzgeber aber alle selbstproduzierten Widersprüche vollkommen egal!

**Comment by lebail** [comment]
Die RKSV wurde zuletzt am 3.8.2016 geändert (mit BGBl. II Nr. 210/2016). Von einer Änderung mit 1.4.2017 weiß ich nichts; die Bestimmungen, die erst ab diesem Datum gelten, sind bereits jetzt enthalten.

"Fassung vom 01.04.2017" steht nur dann im abgerufenen Dokument, wenn man im RIS-Abfrage-Link ebendieses Datum angibt (was beim Link auf der BMF-Website offenbar getan wurde, warum auch immer). Man kann aber auch jedes andere Datum angeben.

Hier z.B. die Fassung vom 1.4.2100: 
https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=20009390&FassungVom=2100-04-01

**Comment by Flanelli** [comment]
Was das Ganze nur noch umso fragwürdiger erscheinen läßt wenn so ein Link existiert und wenn
man offebar durch eine Änderung des Datumseintrages damit auch das Dolument bzgl. dieses
Datums verändern kann. Tut mir leid, aber das ist einfasch nur ............

**Comment by ErichFreitag** [comment]
Das ist schon OK so, man muss es nur richtig anwenden und lesen. Der Grund ist, dass Bestimmungen beim Erlass eines Gesetzes oft erst zu einem bestimmten Tag in der Zukunft in Kraft treten oder andere Bestimmungen außer Kraft treten. 

Will man daher den gültigen Stand zu einem bestimmten Stichtag kann man das über das Datum der Fassung machen. Das ist auch für die Vergangenheit wichtig, wenn sie beispielsweise die Rechtslage zu einem bestimmten füheren Zeitpunkt beurteilen müssen.

**Comment by Flanelli** [comment]
Das kann ich im Prinzip nachvollziehen aber es bleibt dennoch ein höchst bedenkliches Faktum.
Wenn im Link das Datum geändert wird ( es steht nicht zur Debatte warum das jemand tun soll )
dann hat das Dokument bis auf den Hinweis < Fassung von > immer den gleichen Inhalt aber eben
jedesmal das Datum das im Link eingetragen wird und das ist einfach durch Nichts zu rechtfertigen.
Wenn ich ein Dokument bzw. die offizielle Webseite auf der der Inhalt abgebildet ist herunterlade, sprich
die Seite lokal speichere und ich das Datum der Fassung einfach über die Linkeingabe ändern kann,
also nicht den Inhalt des Dokumentes selbst direkt manipuliere dann ist das einfach ........
Egal wie man es anwenden kann oder sol und es lesen kann oder soll, es bleibt eine außerdentlich 
dil......ische Handhabung des BKA-RIS

**Comment by lebail** [comment]
Das angegebene Datum hat sehr wohl eine Auswirkung auf den Inhalt: Es wird nämlich diejenige Fassung angezeigt, die zum angegebenen Zeitpunkt gültig war bzw. (voraussichtlich) sein wird.

Meiner Meinung nach ist allerdings die _Formulierung_ ("Fassung vom …") ungünstig gewählt. Besser wäre vielleicht "Fassung gültig am …" oder so. Aber nachdem das sicherlich von Juristen stammt, wird es Gründe geben, dass der Text so lautet.
