### ISSUE TITLE
Signatur ändert sich bei identischem Payload

### ISSUE THREAD

**Issue by germanchiefprogrammer** [a-sit-plus/at-registrierkassen-mustercode#435]
Hallo zusammen,

wir sind soweit mit der Umsetzung der RKSV durch. Ein spannendes Thema ;-)

Eine Frage ergibt sich noch für uns. Wir haben festgestellt, die Signatur ändert sich bei selbem Payload (A-Trust).
Wenn wir die Beispiel Payload Daten aus der Doku verwenden, erhalten wir nicht das erwartete Signatur-Ergebnis aus der Doku.
Sowohl im Live-System als auch im Demo-System.

Beispiel:
Payload:
_R1-AT0_DEMO-CASH-BOX524_366596_2015-12-17T11:23:44_0,00_0,00_3,64_-2,60_1,79_VFJB_47be737cb1f6d1f1_ZvNxJw6a1A4

Laut Doku zu erwartende Signatur:
_J7YC28zquHfHzMpx02TqElbXOTSgXQu5JAA9Xu1Xzzu5p8eUYT+sgmyhzRps5nYyEp5Yh8ATIa9130zmuiACHw

Zum einen erhalten wir nicht diese Signatur, sondern jedes mal eine andere (gültig aussehende) Signatur.

Ist dies korrekt, dass sich die Signatur ständig ändert?

Doku:
https://www.bmf.gv.at/egovernment/projekte/registrierkassen/Detailfragen-RKSV-V1.1-110316.pdf

Viele Grüße,
CP

**Comment by lebail** [comment]
Ja, das ist korrekt. Das Thema hatten wir hier vor kurzem: https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/410

Ich würde aber dennoch empfehlen, das Prüftool zu benutzen, um sicherzustellen, dass alles passt.

**Comment by ErichFreitag** [comment]
Und sie verwenden eine alte Version des Dokuments, siehe Startseite im Forum.

**Comment by ErichFreitag** [comment]
R1-AT0 ist für den Echtbetrieb auch nicht korrekt.

**Comment by germanchiefprogrammer** [comment]
Danke für die schnellen Antworten. Freut uns sehr!
Dass die Frage schonmal gestellt wurde hatten wir übersehen. Sorry.

> Und sie verwenden eine alte Version des Dokuments, siehe Startseite im Forum.
Danke für den Tipp. 

> R1-AT0 ist für den Echtbetrieb auch nicht korrekt.
Das ist bekannt. Danke.
