### ISSUE TITLE
QR-Code mit Leerzeichen am Anfang oder Ende

### ISSUE THREAD

**Issue by TimoKunze** [a-sit-plus/at-registrierkassen-mustercode#439]
Servus,

Wir haben ein Problem, auf den Bondruckern eines bestimmten Herstellers QR-Codes zu drucken, wenn der Inhalt des Codes eine bestimmte Länge hat, die in der Realität leider des öfteren auftreten wird.
Im Detail: Man muss zum Druck eines QR-Codes u.a. die Länge des Inhalts übergeben. Zusammen mit dem vorherigen Zeichen ergibt diese Länge aber einen bestimmten Steuerbefehl für diesen Drucker, welcher den Drucker veranlasst, keinen QR-Code zu drucken, sondern stattdessen Teile des QR-Codes im Klartext auszugeben.
Der Drucker wird bei unseren Kunden in nicht unerheblicher Anzahl eingesetzt. Ihn gegen ein anderes Modell auszutauschen, geht also nicht so einfach. Unsere Idee ist nun, ggf. ein Leerzeichen anzuhängen oder voranzustellen, um die Länge zu ändern. Das verändert aber natürlich auch den QR-Code selbst.
Deshalb wüsste ich gern, ob das eine zulässige Auslegung der Spezifikationen wäre.

**Comment by ErichFreitag** [comment]
Das wird wohl weder formal möglich sein noch von der Belegcheck-App akzeptiert werden - probieren sie letzteres mal aus. Vielleicht hilft auch https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/98

**Comment by geraldsix** [comment]
Wir hatten das selbe Problem. Nicht der Drucker war bei uns schuld, sondern die eingesetzte Software konnte in einem String Feld keine char(0) darstellen, dass eben bei bestimmten Längen des Barcodes notwendig ist. 
Bei uns war die Lösung den Datentyp blob für die Ausgabe der Druckersteuerzeichen zu verwenden.

**Comment by TimoKunze** [comment]
Danke für die Antworten, wir konnten das Problem anders lösen. Wie sich herausgestellt hat, haben wir bei der Ansteuerung des Druckers eine LowLevel-Funktion unserer Software falsch verwendet.
