### ISSUE TITLE
Verschlüsselung Umsatz PHP

### ISSUE THREAD

**Issue by nn1234** [a-sit-plus/at-registrierkassen-mustercode#44]
Gibts es auch einen PHP Samplecode für die Umsatzverschlüsselung?

**Comment by pteufl** [comment]
nein, leider. Würde folgende Vorgehensweise vorschlagen: 
1. Am besten auf Stackoverflow (oder ähnlichen Quellen) nach PHP und AES Verschlüsselung suchen (z.B. MCRYPT Extension, beim schnellen Suchen)
2. Welchen AES Modus bietet die Bibliothek? ICM, CTR oder CFB am einfachsten, ECB auch möglich, muss man aber mehr tun... (Sie müssen darauf achten welcher Modus von der ausgesuchten Bibliothek unterstützt wird, bei MCRYPT seh ich schnell CFB und ECB).
3. Je nach Modus, schauen Sie die dazu passenden Methoden im Java Demo Code an, sie sehen dort wie die Verschlüsselung durchgeführt wird, und wie die Eingabeparameter (IV, Padding) aufbereitet werden. Sie sollten das dann recht schnell auf PHP transferieren können.
https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-core/src/main/java/at/asitplus/regkassen/core/base/util/AESUtil.java

**Comment by lebail** [comment]
Ich habe mich interessehalber einmal an einer PHP-Variante versucht (Achtung: ich bin nicht von der Fa. A-Sit, nur ganz normaler User):

```
<?php
$cashreg_id = 'DEMO-CASH-BOX817';
$receipt_nr = 83470;
$turnover_counter = 8733;
$key_base64 = 'RCsRmHn5tkLQrRpiZq2ucwPpwvHJLiMgLvwrwEImddI=';

$tc_bin = pack("J", $turnover_counter);
$key_bin = base64_decode($key_base64);
$iv_bin = substr(hash('sha256', $cashreg_id . $receipt_nr, true), 0, 16);
$tc_encrypted = openssl_encrypt($tc_bin, 'AES-256-CTR', $key_bin, true, $iv_bin);

printf("%s\n", base64_encode($tc_encrypted));
?>
```
Ausgabe: **vXvqlWy0zcM=**
Dies ist identisch mit dem Demo-Output des Mustercodes V 0.5.

Achtung:

- Es muss die PHP-OpenSSL-Extension installiert sein.
- Je nach PHP-Version und Betriebssystem-Version sind Integer unter PHP eventuell nur 32 Bit lang. Dies könnte zu Problemen beim Umsatzzähler führen.

Die Benutzung der Mcrypt-Extension wird übrigens generell nicht empfohlen, da diese seit 2003 nicht mehr gepflegt und weiterentwickelt wird.

**Comment by asitplus-pteufl** [comment]
danke für den hinweis.

**Comment by duxthefux** [comment]
Danke für den Code. Aber wie komme ich jetzt auf den "verkürzten verschlüsselten Umsatzzähler"?

> Unabhängig vom vorher durchgeführten Prozess (ICM/CTR, CFB, ECB) entspricht das Ergebnis einem 16 Bytes/128 Bits langem Wert (der verschlüsselte Umsatzzähler). Um die Länge des in weiterer Folge aufbereiteten maschinenlesbaren Codes möglichst gering zu halten, werden vom verschlüsselten Umsatzzähler nur die Anzahl der im vorigen Prozess definierten „Länge des verschlüsselten Umsatzzählers“ (siehe Prozess [2]) extrahiert.
> Dabei wird wie folgt vorgegangen: Das Resultat des Verschlüsselungsprozesses (Prozess 2.5.3 oder Prozess 2.5.4) entspricht dem verschlüsselten Umsatzzähler (16-Bytes/128 Bits langer Wert). Startend mit Byte 0 werden N Bytes aus dem Array extrahiert und BASE64-kodiert. N entspricht dabei der im vorigen Prozess definierten Länge des verschlüsselten Umsatzzählers. Der Minimalwert für N ist 5. Dies entspricht 5 Bytes/40 Bits, die aus dem verschlüsselten Umsatzzähler extrahiert werden.
> Das Ergebnis ist der „Verkürzter verschlüsselter Umsatzzähler für die Ablage im Feld „Stand- Umsatz-Zaehler-AES256-ICM“.

**Comment by lebail** [comment]
Entweder Sie bleiben bei einem 8 Byte langen Umsatzzähler (das wäre ja zulässig), dann liefert der obige Code direkt Ihren verschlüsselten Umsatzzähler.

Oder Sie möchten für den Umsatzzähler nur weniger Bytes (N = 5, 6 oder 7) nutzen; in diesem Fall müssten Sie:

- bei der openssl_encrypt()-Funktion als vierten Parameter "true" statt "false" angeben (dann wird das Ergebnis _nicht_ BASE64-kodiert)
- vom Resultat per substr() nur die letzten N Bytes nehmen
- diese dann mit base64_encode() kodieren

Dies liefert auch bei negativen Werten ein korrektes Resultat, solange der Zahlenbereich, den das Zielformat vorzeichenrichtig darstellen kann, nicht überschritten wird.

**Comment by duxthefux** [comment]
Vielen Dank für die Info!

Komischerweise failed der Umsatzzähler-Entschlüsselungstest der TestSuite?

Wenn ich den verschlüsselten Wert mit
`unpack("J",openssl_decrypt($tc_encrypted_base64, $method, $key_bin, false, $iv_bin))`
entschlüssele, bekomme ich aber richtigerweise 0 retour. Komischerweise gibt unpack() aber einen Array in Form [ 1 => 0 ] retour.


Anbei der Output des Tests:
```
"verificationId" : "CRYPTO",
      "version" : 1,
      "verificationName" : "Kryptographische Prüfungen",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-01-19T10:39:42.165+01:00",
      "verificationResultList" : [ {
        "verificationId" : "CRYPTO_SIGNATURE",
        "version" : 1,
        "verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
        "verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-01-19T10:39:42.166+01:00"
      }, {
        "verificationId" : "CRYPTO_TURNOVER_COUNTER",
        "version" : 1,
        "verificationName" : "Kryptographie: Entschlüsselung des Umsatzzählers",
        "verificationTextualDescription" : "Es wird die Entschlüsselung des Umsatzzählers überprüft. Eine Aussage über die Korrektheit kann nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Der Umsatzzähler konnte nicht entschlüsselt werden.",
        "verificationTimestamp" : "2017-01-19T10:39:42.268+01:00"
      } ]

```


cryptoContainer:
`{"base64AESKey":"dXV6SGR1ZUJSWXpUMUFWdVFa","certificateOrPublicKeyMap":{"1569718536":{"id":"1569718536","signatureDeviceType":"CERTIFICATE","signatureCertificateOrPublicKey":"MIIEvTCCA6WgAwIBAgIEXZABCDANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBgwCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaYS1zaWduLVByZW1pdW0tVGVzdC1TaWctMDIxIzAhBgNVBAMMGmEtc2lnbi1QcmVtaXVtLVRlc3QtU2lnLTAyMB4XDTE3MDExOTA5MDE0MVoXDTIyMDExOTA5MDE0MVowYzELMAkGA1UEBgwCQVQxGTAXBgNVBAMMEFVJRDogQVRVMjIyMjIyMjIxFDASBgNVBAQMC0FUVTIyMjIyMjIyMQwwCgYDVQQqDANVSUQxFTATBgNVBAUMDDcyOTI4Njg5OTY1NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBHn+XCaz1hVRiWlLPWTLQLbY07lhpGo7AFYMJnKri+IidY64MMFj8\/MNi8OG8fx37w+Eyg+xrOnot680Ov9LOijggIDMIIB\/zCBhAYIKwYBBQUHAQEEeDB2MEYGCCsGAQUFBzAChjpodHRwOi8vd3d3LmEtdHJ1c3QuYXQvY2VydHMvYS1zaWduLVByZW1pdW0tVGVzdC1TaWctMDIuY3J0MCwGCCsGAQUFBzABhiBodHRwOi8vb2NzcC10ZXN0LmEtdHJ1c3QuYXQvb2NzcDAOBgNVHQ8BAf8EBAMCBsAwJwYIKwYBBQUHAQMBAf8EGDAWMAgGBgQAjkYBATAKBggrBgEFBQcLATCBrgYDVR0fBIGmMIGjMIGgoIGdoIGahoGXbGRhcDovL2xkYXAtdGVzdC5hLXRydXN0LmF0L291PWEtc2lnbi1QcmVtaXVtLVRlc3QtU2lnLTAyIChTSEEtMjU2KSxvPUEtVHJ1c3QsYz1BVD9jZXJ0aWZpY2F0ZXJldm9jYXRpb25saXN0P2Jhc2U\/b2JqZWN0Y2xhc3M9ZWlkQ2VydGlmaWNhdGlvbkF1dGhvcml0eTAJBgNVHRMEAjAAMFkGA1UdIARSMFAwCAYGBACLMAEBMEQGBiooABEBCzA6MDgGCCsGAQUFBwIBFixodHRwOi8vd3d3LmEtdHJ1c3QuYXQvZG9jcy9jcC9hLXNpZ24tUHJlbWl1bTATBgNVHSMEDDAKgAhGBp+OQY4VvTARBgNVHQ4ECgQITnlwE0E3pGswDQYJKoZIhvcNAQELBQADggEBAF4fMk8BIRpfyJQLNcU7k4iZeMMYkE8HZx25mEYwKd31ej+MpqQrofDkK+uiCns4TROSxlNvpTxCmkAr3qv05XCZUNl5VDXajX6WRU22t7VNhiEjzmm6ytPxucF1SMPf1GWUFBbzuFZKoOrJcB\/XI9LIbjkferq2OrkHP+oppr5vdCJTYxU\/VYTbObTVJ3xclBvF1qP\/MbBrZ+cCzQlA6rYgsV6Ts3myZjUTpg1HvpJxxK6O9+hBiLQBD5ct4i2B+J7wXHpRAxkoYEV2jwo5+JtTQOjhKsYdUfW4cVzxNihitHJJhaNydB7XzBi6leaKFCes5ICseBv0\/bszbzd1EZY="}}}`


QR-Code:
`["_R1-AT1_200001a_200001a_2017-01-19T10:39:39_0,00_0,00_0,00_0,00_0,00_BkSo4dZB_1569718536_jwj4K9a+Km8=_VM8t5OFPQEwiNYGe43fQPA51UyUYBeu5rSFd9hHkeOejQ6gTMdEKJM5jv9+c9YwFmeI42QiuBYYRLqhET5bltw=="]`

**Comment by lebail** [comment]
Der AES-Key in Ihrem CryptoContainer kann nicht stimmen, der ist zu kurz. Außerdem fällt mir auf, dass in Ihrem QR-Code KAssen-ID und Belegnummer identisch sind. Das wäre natürlich zulässig, vielleicht ist es aber dennoch ein Fehler.

**Comment by duxthefux** [comment]
Danke!
Hab den Fehler gefunden!

Hab den Key nicht Base64 enkodiert gespeichert.

Generierung vom AES Key sieht jetzt so aus:

`base64_encode(openssl_random_pseudo_bytes(32)); // ZUM SPEICHERN IN DER DB`

Jetzt passen die Tests!

Vielen Dank!

**Comment by ludi81** [comment]
Hallo,

Gibt es in der zwischenzeit ein PHP Registrierkassen-Library welche man verwenden kann? Oder ist jemand Bereit seine zu Teilen.

Danke

**Comment by Tom-KK** [comment]
Noch eine Frage zu dem Thema:

In dem PHP Code Beispiel von lebail steht nun folgende Zeile:
$key_base64 = 'RCsRmHn5tkLQrRpiZq2ucwPpwvHJLiMgLvwrwEImddI=';

Das ist der Frei zu definierende AES-Schlüssel zum Verschlüsseln des Summen-zählers, 
und das Base64 codiert ! – Richtig ?

Dieser muss ja dem Finanzamt gemeldet werden!
Nun aber den base64 codiert, oder der offene Text ?

**Comment by ErichFreitag** [comment]
Gemeldet wird der BASE64-codierte, damit 44 Zeichen lange AES-Schlüssel.

**Comment by Scaenicus** [comment]
Zum Beispiel von lebail wenn pack('J', $turnover_counter) nicht verfügbar ist kann man sich den 64bit-Integer auch zusammenbasteln. Der Code unten erkennt selber auf welchem System er läuft.

```php
        if (8 == PHP_INT_SIZE) {
            $tc_bin = pack('J', $turnover_counter); // pack integer into 64-bit big-endian binary string
        } else { //usually: 4 == PHP_INT_SIZE

            // Only 32-bit available. Build 64-bit integer
            // http://stackoverflow.com/a/41060369/2982543

            // base_convert() will treat your value as a string here,
            // converting it from decimal to hexadecimal
            $hexStringValue = base_convert($turnover_counter, 10, 16);

            // Pad with zeros to the left, until pack()'s output length is matched
            $hexStringValue = str_pad($hexStringValue, 16, '0', STR_PAD_LEFT);

            // Convert to binary
            $tc_bin = hex2bin($hexStringValue);
        }
```

**Comment by embeddedprojects** [comment]
Wie sieht es denn aus? Hat jemand Interesse an einer Open-Source Bibliothek. Ich implementiere auch gerade alles frisch. Wäre eingentlich taktisch besser, wir machen das was gemeinsames? 

Neben meiner Arbeitszeit kann ich auch Geld mit ins Spiel bringen. Vielleicht macht das Sinn?

Also das wir jemanden gemeinsam zum Pflegen auf Dauer bezahlen können?

**Comment by lebail** [comment]
In PHP?

Meine Implementierung (die ich vorwiegend für meine eigene Verwendung entwickelt habe) ist nämlich in C geschrieben, läuft unter Linux (gut geeignet für embedded projects ;-), und ich habe ebenfalls vor, sie als Open Source zu veröffentlichen.

Sie ist zwar von der Kernfunktionalität bereits fertig (und ich benutze sie auch schon erfolgreich), aber noch nicht öffentlichkeitstauglich. Denn es ist noch einiges "hardcoded", was der Benutzer sicherlich gerne konfigurieren würde (z.B. seinen Firmennamen, das Layout der Belege, …).

**Comment by embeddedprojects** [comment]
Ich bin mitten drin. Natürlich ist es auch etwas Chaos und Hardcoded noch. Ich habe es auf C++ und PHP gerade gemacht. Ich würde auch alles am Schluss Open-Source machen. So dass man das zentral pflegen kann.

Können wir die Quelltexte zusammenschmeissen?  Mein aktueller Stand ist hier.
http://journal.embedded-projects.net/APDU_CPP.tar.gz 

Da suche ich aber grad auch noch einer Struktur.
Ich bin gerade am überlegen was besser ist für die webbasierten Lösungen. Wie man die Aufteiling macht.

Aufjedenfall auf unterster Ebene eine Bibliotek.

Dann ist die Frage, ob ich die Kassendaten für die Kasse extra in einer Textdatei oder einem Speicher (kann auch DB sein) lokal sammel und die regelmäßig übertrage oder ob ich nur die Signatureinheit über die Ferne steuer.

Für den Anfang wäre es wohl am Besten man hat autonome Datenstrukturen. So das man z.B. per Kommandozeilen Tool oder Bibliothek iterativ einfach den Beleg dazu machen kann.

Wie hast du das gemacht?

**Comment by lebail** [comment]
Ich arbeite bereits seit Herbst 2015 an meinem Projekt, und dieses enthält nicht nur die "Registrierkasse" selbst, sondern ist ein komplettes Abrechnungssystem, welches sowohl Rechnungen mit integriertem RKSV-Barbeleg als auch Zielrechnungen (ohne Barbeleg, dafür mit QR-Code zum automatischen Ausfüllen einer Onlinebanking-Überweisung) erstellen kann. Kunden- und Artikeldatenbank sind auch dabei, und man kann für einen Kunden über längere Zeit Rechnungsposten zusammensammeln und, wenn er dann bezahlen soll, eine Gesamtrechnung erstellen. Stornos sind natürlich auch möglich.

Zur Signierung der Barbelege kann sowohl eine Smartcard (per APDU) als auch ein Onlineservice (per cURL-Library) benutzt werden (auch mehrere davon - mit automatischem Failover). Es gibt ein "Ticketsystem" für elektronische Belege - d.h. der Kunde erhält anlässlich der Zahlung ein vorproduziertes Kärtchen mit einem URL, unter dem er sich den Beleg abholen kann. Das richtet sich vor allem an mobile Dienstleister.

Das Ganze ist (zwecks größtmöglicher Flexibilität) als Kommandozeilenprogramm konzipiert, speichert alle Daten in einer SQLite-Datenbank und sollte sich recht einfach in eine Library überführen lassen (was ich auch geplant habe). Ein GUI und ein Webinterface müssten sich dann auch machen lassen. Ich arbeite unter Linux, Portierungen auf andere Systeme sollten relativ einfach möglich sein (in der Anfangsphase hatte ich erfolgreich per Cross-Compiler und MinGW einen Windows-Port erstellt, mich dann aber nicht mehr darum gekümmert, weil es Wichtigeres zu tun gab).

Das Programm besteht mittlerweile aus 20 C-Source-Dateien (und den zugehörigen Headerfiles). Es wurde schon zweimal vollständig refactored, sodass die Struktur nun halbwegs passen sollte. Allerdings ist noch kaum Dokumentation vorhanden (weder für Entwickler noch für Benutzer), daher möchte ich es jetzt noch nicht veröffentlichen. So kennt sich damit ohnehin niemand aus, und das Fehlen von Dokumentation kann das Projekt (das sich im Echtbetrieb bereits als problemlos und praxistauglich erweist) leicht in ein schlechtes Licht rücken.

Ich mache das nur nebenbei (und vor allem deshalb, weil ich es selbst brauche), versuche nun aber dennoch, so schnell wie möglich eine veröffentlichungsfähige Version zu produzieren, an der dann auch andere mitarbeiten können.

**Comment by dabonzo** [comment]
Ich wäre an einer Open-Source PHP Implementierung interessiert. Es wäre aber ein "Projektleiter" notwendig der sich mit den Abläufen auskennt und zumindestens grob die Prozesse definiert. SO einer bin ich nicht aber ich kann Zeit in die PRogrammierung investieren. Sollte sich eine Gruppe bilden, ich bin dabei.

**Comment by dergraf1010** [comment]
Hallo, wir würden ganz dringend eine PHP-Implementierung für eine Kassa benötigen. Könnte uns wer (gegen Entgelt natürlich) helfen?

**Comment by supereight2** [comment]
Ich habe eine fertige Bibliothek! Diese ist in einem Shop-System integriert und läuft bereits am Produktivsystem, der Startbeleg wurde ebenfalls akzeptiert. Die Bibliothek lässt sich sicher auch in andere Shop-Systeme integrieren. Bei Interesse einfach melden.

**Comment by ArminsRadl** [comment]
Herr Lebail,
könnten Sie mich kontaktieren unter bike@arminsradlwerkstatt.at
Ich finde leider keine Kontaktadresse.

.. bin neu hier auf github
lg Armin

**Comment by lebail** [comment]
Bitte die Frage hier im Forum zu stellen. Ich bin kein Mitarbeiter von A-SIT und habe nicht immer Zeit, um zu antworten. Hier im Forum kann aber bei Bedarf auch jemand anderer antworten ...

**Comment by dabonzo** [comment]
@supereight2, diese Bibliothek ist kostenpflichtig ?

**Comment by supereight2** [comment]
Ja, diese ist kostenpflichtig. Hat einfach zu viel Zeit beansprucht diese zu erstellen, daher kann ich diese nicht einfach weitergeben.

**Comment by perler-at** [comment]
Hallo!
Ich konnte mit dem obigen Beispielen die Verschlüsselung korrekt durchführen, vielen Dank.
Ich habe aber eine vielleicht etwas seltsam anmutende Frage: Woher bekomme ich den AES Schlüssel? Die Base64 kodierten Schlüssel bestehen sind in uncodierter Form ja Binärdaten wenn ich das richtig erkannt habe. Wie erzeuge ich zu einem gültigen Schlüssel, den ich in Base64 codierter Form für die Verschlüsselung der Daten verwenden kann?

**Comment by asitplus-pteufl** [comment]
@perler-at das ist nichts anderes als 256 zufällige bits, die Sie über einen Zufallszahlengenerator (gibt es in jeder Programmiersprache) erstellen. 
z.B. bei openssl für 32 bytes an Daten: openssl rand 32

**Comment by perler-at** [comment]
Danke.

Da ich mit Perl arbeite habe ich das Modul Crypt::Random verwendet
http://search.cpan.org/~vipul/Crypt-Random-1.25/lib/Crypt/Random.pm

Ich bekomme mit
`
use Crypt::Random qw( makerandom ); 
my $r = makerandom ( Size => 256, Strength => 1 ); 
`
das Ergebnis
72600690656371598597375430637004932814459191850983033730971683358271809203666

Base64 codiert
NzI2MDA2OTA2NTYzNzE1OTg1OTczNzU0MzA2MzcwMDQ5MzI4MTQ0NTkxOTE4NTA5ODMwMzM3MzA5
NzE2ODMzNTgyNzE4MDkyMDM2NjY=

Wo liegt mein Fehler?

Das ist je ledigleich eine Nummernkette.

**Comment by asitplus-pteufl** [comment]
Sie bräuchten jetzt noch eine Binärrepräsentation der Zahl. Sie bekommen ja in dem Beispiel diese Daten als Dezimalzahl repräsentiert.

**Comment by perler-at** [comment]
Alles klar. Geschafft.
Ich könnte aber auch das Ergebnis von "openssl rand 32" direkt verwenden oder?

**Comment by ErichFreitag** [comment]
BASE64 codieren müssen sie es noch, macht aus 256 Bits = 32 Zeichen -> 44 Zeichen.

**Comment by Alex1130** [comment]
@lebail @dabonzo @embeddedprojects 
Falls die Opensource Idee noch besteht würde ich gerne mithelfen !
