### ISSUE TITLE
Wie wird die Verkettung beim Startbeleg verschlüsselt in PHP?

### ISSUE THREAD

**Issue by Sta-Sandro** [a-sit-plus/at-registrierkassen-mustercode#442]
Hallo,
in der Dokumentation Detailfragen RKSV wird als Eingabewert die Kassen-ID 
in diesem Fall A12347 angegeben.
In PHP komme ich hier aber nie in der Kodierung auf OeSKQjO4zKI= ?
Wird nun nur die Kassen-ID kodiert oder _RK1_KassenID?
Wird die Kassen ID erst base64_encode unterzogen oder
nur hash('sha256', $kassenid, true) ?
Bitte um Hilfe, ich finde leider keine hilfreiche Antwort.
Danke.

**Comment by lebail** [comment]
Das stimmt schon so. Es wird nur die Kassen-ID benützt. Vom Hash werden die ersten 8 Bytes genommen und Base64-kodiert:
```
<?php
$result =  base64_encode(substr(hash('sha256', 'A12347', true), 0, 8));
echo "Ergebnis: " . $result . "\n";
?>
```
Ergebnis: OeSKQjO4zKI=

**Comment by Sta-Sandro** [comment]
Vielen Dank. 
Funktioniert - ich hatte einen Fehler bei der Gegenprüfung mit anderen Beispielen.

Daher folgender Hinweis für alle denen es gleich ergeht:
Bei den Beispielen example-output-0.5 von asit wird der ocr code und der
qr code zur Verfügung gestellt.
Die qr Code Werte vom z.B. Startbeleg sind hier in der Form 
base64_encode(substr(hash('sha256', 'DEMO-CASH-BOX817', true), 0, 8)); kodiert und
ergeben daher: d3YUbS4CoRo=
Leider hatte ich nicht den qr Code sondern den ocr Code offen mit
foglendem Wert: O53BI3JOAKQRU===
Daher konnte die base64_encode Variante nicht funktionieren. 

Nun zur Aufklärung: 
Der OCR Code Wert ist base32 konvertiert! Daher die Beispiele nur mit QR Code vergleichen..
Als Konvertierung auf base32 in PHP hilft:  
https://github.com/ademarre/binary-to-text-php/blob/master/Base2n.php

Hoffe ich kann damit auch anderen Zeit ersparen.
