### ISSUE TITLE
Belege bevor StartBeleg

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#446]
Hallo,

wie ist es von Gesetzt her in dem Fall dass da schon Belege erstellt geworden sind und erst danach der StartBeleg kreirt wurde?

Ist es verboten bzw was genau passiert dann?

MfG

**Comment by ErichFreitag** [comment]
Das kommt darauf an, was sie mit diesen Belegen gemacht haben. Am besten sichern und eine neue Kasse in Betrieb nehmen.

Die Kasse wird mit dem Startbeleg in Betrieb genommen, der muss bis zum 01.04.2017 erstellt werden. Da das der erste Beleg sein muss sind ohnedies alle vorherigen nicht Teil des Lebenszyklus dieser Kasse.

**Comment by espeitslo** [comment]
ok, aber ist es ok wenn man diese vorige Belege ( normalbelege oder testbelege) einfach lässt, wird dann die Funktionalität des StartBelegs korrekt übernommen bzw werden die vorige Belege ignoriert und dürfen einfach auf der Kasse gelassen werden?

**Comment by ErichFreitag** [comment]
Kommt darauf an, was sie mit "in der Kasse lassen" meinen.

Wenn es normale Beleg sind dürfen die sowieso nicht entfernt werden.

"Die Kasse" im Sinne der RKSV startet mit dem Startbeleg -> RKSV-Umsatzzähler auf 0 -> RKSV-DEP einrichten -> als ersten Beleg im RKSV-DEP ablegen.

Vor dem Startbeleg für eine bestimmte Kasse kann es beliebig viele Kassenbelege geben, aber keinen RKSV-Beleg.

**Comment by espeitslo** [comment]
na ja eignetlich RKSV Belege. Das heisst dann dass es die Einzige möglichkeit wäre die Kasse auserbertiebnehmen und eine neue erstellen, wie Sie am Anfang geschrieben haben

**Comment by ErichFreitag** [comment]
So ist es.

**Comment by ckvsoft** [comment]
Sprich wenn eine Kasse schon in Betrieb ist und zb. durch ein Software Update RKSV fähig wird.
Dann ein Startbeleg als ersten Beleg im RKSV-DEP erstellt wird. Dürfen/müssen alle vorhergehenden, "nicht RKSV - Beläge" im Journaling bleiben?

**Comment by ErichFreitag** [comment]
MÜSSEN. Sie dürfen ja keine Vorgänge "radieren".

**Comment by ckvsoft** [comment]
Alles Klar, danke
