### ISSUE TITLE
Testtool: "FAIL" beim Entschlüsseln des Umsatzzählers bei Startbeleg – Grundsätzlicher Fehler beim Verschlüsseln des Umsatzzählers?

### ISSUE THREAD

**Issue by hjgwenex** [a-sit-plus/at-registrierkassen-mustercode#447]
Werte Kollegen,

Habe versucht, nach bestem Wissen und Gewissen die Verschlüsselung des Umsatzzählers entsprechend dem Java Beispiel Coding in Harbour und C nachzuprogrammieren. Dabei habe ich sowohl eine CTR als auch eine CFB Verschlüsselung sowie eine Entschlüsselung realisiert.

Leider liefert das Testtool für den Startbeleg mit Umsatzzähler 0
...
_R1-AT1_FLIX00_2428_2017-03-20T16:11:16_0,00_0,00_0,00_0,00_0,00_iiu0okM=_76B9AA8B_ZaMir+hiNS0=
...
codiert in EXP20170320_161301.JSON (hochgeladen als .TXT) mit cryptographicMaterialContainer.JSON (hochgeladen als .TXT) ein "FAIL" bei CRYPTO_TURNOVER_COUNTER (und CRYPTO_SIGNATURE – aber das ist vielleicht ein Folgeproblem) => Log 0000_cashbox_full.txt
Ich habe ein detailliertes Trace programmiert, um die Verschlüsselung des Umsatzzählers zu dokumentieren. 
Könnten Sie vielleicht einen Blick auf das entsprechende Trace File RKSV_NULLBELEG_TRACE_FLIX00_2428.TXT werfen? Vielleicht ist es so möglich, den Fehler in der Verschlüsselung zu finden ...

Besten Dank!

Grabner Joerg

Dateien:
[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/855511/0000_cashbox_full.txt)

[EXP20170320_161301.TXT](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/855506/EXP20170320_161301.TXT)

[RKSV_NULLBELEG_TRACE_FLIX00_2428.TXT](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/855507/RKSV_NULLBELEG_TRACE_FLIX00_2428.TXT)

[cryptographicMaterialContainer.TXT](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/855504/cryptographicMaterialContainer.TXT)

**Comment by ErichFreitag** [comment]
Da scheint mehr falsch zu sein. Nach kurzem Blick:
- Prüftool liefert Fehler im Umsatzzähler UND in der Signatur
- ihr obiger Auszug kann bezüglich Verkettung und Signatur nicht sein
- die Signatur im DEP-Eintrag ist BASE64-codiert und nicht BASE64URL-codiert
- alle BASE64-codierten AES-Schlüssel, die ich bis jetzt gesehen habe, haben im letzten Zeichen ein "=", ihrer nicht
Mit dem Trace kann ich so nichts anfangen.

**Comment by rolandro** [comment]
Was mir auffällt ist, dass die Schlüssellänge zu lang ist, in deinem Fall 33 Bytes statt 32 Bytes "Y2587 HK4FL IXLIF TKARN IESEN BENUT ZER". Ich hab mal das erste "Y" im Schlüssel weggelassen und komme mit deinen Daten dann zu folgendem Ergebnis :

_R1-AT1_FLIX00_2428_2017-03-20T16:11:16_0.00_0.00_0.00_0.00_0.00_pmAfNvXegPg=_76B9AA8B_ZaMir+hiNS0= 

Ich habe die Kassa ebenfalls in Harbour programmiert, sie lauft bereits seit 1.3. erfolgreich im Echtbetrieb. 
.
Harbour-AES256-Code für Regkassa (für Harbour 3.4.0-Dev Version mit AES) :

[crypt-test2.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/856054/crypt-test2.txt)

**Comment by FriNagy** [comment]
Du kannst es mit mein Testprogramm auch selber testen  #433

jetzt auch on git 
https://github.com/FriNagy/Reg_KP

**Comment by hjgwenex** [comment]
Vielen, Vielen Dank für die prompte und spezifische Hilfestellung an Alle!!! 
Der AES Key, die Aufbereitung und Codierung der Signatur (Base64URL) im .JSON file passen jetzt.

Ganz besonders hilfreich war "crypt-test2.txt" von rolando – die Verschlüsselung des Umsatzzählers ist jetzt basierend auf einem sehr ähnlichen Coding (HMG 3.4.3, Verschlüsselung mit hbssl) für den Startbeleg ok.
