### ISSUE TITLE
a-trust Server Antwort: 400 - Bad request

### ISSUE THREAD

**Issue by hg7799** [a-sit-plus/at-registrierkassen-mustercode#450]
Zur Signatur gesendete Zeichenkette:
X1IxLUFUMV9DYXNzYTg4OF8yXzIwMTctMDMtMjFUMTA6NTI6NDhfMCwwMF8wLDAwXzAsMDBfMCwxMF8wLDAwX0U3YWN4Z3l1d1NzPV81NGUwMzc3M19JUzVFRkhVSWVxST0

Klartext:
_R1-AT1_Cassa888_2_2017-03-21T10:52:48_0,00_0,00_0,00_0,10_0,00_E7acxgyuwSs=_54e03773_IS5EFHUIeqI=

HTTP 400 laut Dokumentation: invalid base64

Sieht von Euch vielleicht jemand wo der Fehler sein könnte?
Die Kasse ist bei FON angemeldet, Startbeleg noch nicht gelungen ...

Vielen Dank!

**Comment by ErichFreitag** [comment]
Zur Signatur sind die Klartextdaten zu übergeben.

**Comment by hg7799** [comment]
Vielen Dank für die schnelle Antwort - löst aber leider das Problem nicht!

Wenn die Zeichenkette (in Base64-Kodierung) für eine RK gesendet wird, die noch **nicht** bei FON angemeldet ist, antwortet der Server mit der Signatur und 200 (alles OK).

Wird das Gleiche für eine **bei FON angemeldete** Kasse gesendet, ist die Antwort 400 (invalid Base64)

Wenn die Zeichenkette **im Klartext** gesendet wird, antwortet der Server **immer** mit 400 (invalid Base64).

Vielen Dank

**Comment by ErichFreitag** [comment]
Bitte nochmals von vorne:
a) die zu signierenden Daten sind JWS-Header.JWS-Payload - oben sehe ich nur die Payload
b) welcher Server antwortet mit der Signatur? Was hat das mit FON zu tun?

**Comment by lebail** [comment]
Ob BASE64-kodiert werden muss oder nicht, hängt vom gewählten Kommando ab. Die Schnittstelle von A-Trust unterstützt sowohl die Übergabe des Plaintextes (Kommando "Sign/Plain") als auch die Übergabe des BASE64-kodierten Textes (Kommando "Sign").

Ob die Kasse bei FON angemeldet ist, hat keine Auswirkung auf das Resultat. Das "weiß" der Server gar nicht. Wenn es bei einer Kasse geht und bei einer anderen nicht, tippe ich darauf, dass Sie das Kommando "Sign" verwenden (welches BASE64 erwartet) und einen Fehler in der BASE64-Kodierung haben, der sich nur bei manchen Eingabewerten auswirkt (BASE64URL statt BASE64, fehlendes Padding etc.).

**Comment by hg7799** [comment]
danke für die super-schnellen und super-nützlichen Hinweise!

**Comment by hg7799** [comment]
'Bad Request Error 400' zeigt sich hartnäckig:

Hier die versuchten Aufrufe:

https://www.a-trust.at/asignrkonline/v2/u765638488/Sign
POST: {"password":"hmxxxx","to_be_signed":"eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9DYXNzYVRFU1RfMV8yMDE3LTAzLTI2VDEzOjE1OjM5XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8zSlhBZUtKQWlZaz1fNWNiMWE5NmVfSDZiZnhzSmpBY0k9"}

Alternativ:
https://www.a-trust.at/asignrkonline/v2/u765638488/Sign/Plain
POST:
{"password":"hmxxxx","to_be_signed":"{"alg":"ES256"}._R1-AT1_CassaTEST_1_2017-03-26T13:18:03_0,00_0,00_0,00_0,00_0,00_3JXAeKJAiYk=_5cb1a96e_H6bfxsJjAcI="}

Falls jemand ein scharfes Auge hat und erkennt, wo mein Unsinn liegt, wird das sehr geschätzt!

**Comment by lebail** [comment]
Da ist immer eine BASE64-Ebene zu wenig drinnen. Beim Kommando "Sign" müsste Ihr "to_be_signed" passen (soferne die Bestandteile korrekt BASE64**URL**-kodiert sind, das ist in diesem Beispiel nicht ersichtlich); es muss dieser ganze String aber zusätzlich nochmals (normal) BASE64-kodiert werden.

Beim Kommando "Sign/Plain" ist das "to_be_signed" genauso wie beim ersten Beispiel zu erstellen (also auch mit BASE64URL), der sich ergebende String aber **nicht** mehr BASE64 zu kodieren.

Siehe die Beispiele im A-Trust Developer Manual unter 6.1 und 6.3.

**Comment by lebail** [comment]
Oder anders gesagt: Wenn Sie den Request aus Ihrem **ersten** Beispiel an "Sign/**Plain**" schicken, müsste es funktionieren.

Wenn das dann allerdings für diesen Beleg funktioniert, für einen anderen aber nicht, würde dies daran liegen, dass Sie BASE64 statt BASE64URL benutzt haben (denn bei dem hier gezeigten Beleg kommen die "interessanten" Zeichen zufällig nicht vor, sodass sich die beiden Kodierungen hier nicht unterscheiden).

**Comment by hg7799** [comment]
connection response==200 - Alles OK (kaum zu glauben)
Herzlichen Dank für die sonntägliche Hilfe!!
