### ISSUE TITLE
Seriennr dec -> hex

### ISSUE THREAD

**Issue by mandihof** [a-sit-plus/at-registrierkassen-mustercode#452]
Hallo,

ich hab das Problem, dass ich die Seriennr nur als decimal Zahl zurückbekomme, zb 2472348585010001
wie kann ich mir daraus die hex darstellung "berechnen"?

lg manfred

**Comment by ErichFreitag** [comment]
Mit dem Windows-Rechner im Modus "Programmierer" z.B.
Online-Tools gibt es wohl auch.

**Comment by mandihof** [comment]
naja, ich hab ja die oben angebenen seriennr, laut atrust aclient ist meine seriennr in hex 4A166366 was mit onlinetools / windowsrechner usw die zahl 1242981222 ergibt. wie komme ich aber nun von der Zahl 2472348585010001 auf diese zahlen?
diese zahl sehe ich auch im atrust client wenn ich auf "zertifikat anzeigen" klicke, dann auf details und dort unter "Antragsteller"
SERIALNUMBER = 247234858501
CN = UID ATU67.....
C = AT

**Comment by ErichFreitag** [comment]
Es gibt zwei Seriennummern.
Die 4A... schaut nach der Zertifikats-Seriennummer und OK aus.
Die 2472... wird die Vertragsseriennummer sein und die 0001 ist eine laufende Nummer dazu.
Sie finden das im A-Trust-Verzeichnisdienst.

**Comment by mandihof** [comment]
d.h. von der Vertragsseriennr. kann ich per programmierung eigentlich nicht auf die Zertifikatssnr. rückrechnen

**Comment by ErichFreitag** [comment]
So ist es.

**Comment by mandihof** [comment]
thx
