### ISSUE TITLE
RK Online in Mustercode

### ISSUE THREAD

**Issue by Thomas233** [a-sit-plus/at-registrierkassen-mustercode#454]
Hallo,

ich möchte RK Online als Signatur-Modul in den Mustercode integrieren (statt den dort verwendeten _NEVER_USE_xyz Beispielmodulen bzw. selbstgenerierten Zertifikaten).

Folgendes Code-Snippet habe ich für RK Online in Java gefunden:
http://labs.a-trust.at/developer/ShowSource.aspx?id=120

Gibt es evtl. für RK Online evtl. schon eine fertige Implementierung für den Mustercode (also eine Implementierung die von _SignatureModule_ aus _at.asitplus.regkassen.core.modules.signature.rawsignatureprovider_ erbt) ?

Sonst muss ich hier wahrscheinlich noch das ein oder andere Fragen :-)

Danke !

PS: Wie lauten die aktuellen URLs von RK Online (Live/Test), die aus der Doku gehen beide nicht ?

**Comment by theshadowtwentyseven** [comment]
Hi Thomas,

die URLs in der Doku fand ich auch etwas versteckt, aber folgende funktionieren:

Test: https://hs-abnahme.a-trust.at/asignrkonline/v2/
Live: https://www.a-trust.at/asignrkonline/v2/

Wir haben das Handling von RK Online gänzlich selbst implementiert.

**Comment by robertpic71** [comment]
Die Doku zum A-Trust Webservice ist unter:

[RegistrierkasseMobileDev.pdf](https://labs.a-trust.at/developer/pdf/RegistrierkasseMobileDev.pdf)
gespeichert.

Dort stehen auch etwas aktuellere Beispielsourcen. Eigentlich war die Webservice-Signierung als Backup von uns angedacht. Zumindest aktuell funktioniert das aber recht flott (< 100 ms, bei angemeldeter Session), dass wir jetzt die Karte als Backup haben. 

Wider erwarten lässt sich durch den Webservice alles direkt am IBM-Host erledigen....

 Zum A-Trust Beispielcode: Eine fertige Implementierung dazu hätte ich auch nicht gefunden. Der richtige Gegenspieler für den Webservice ist das JWSModule (also AbstractJWSModule erweiern) - da wird auf höhere Ebene gearbeitet (ohne PrivateKey...).

**Comment by Thomas233** [comment]
Hallo,

vielen Dank für die sehr hilfreichen Antworten.

Ich hab es mittlerweile geschafft ein eigenes JWSModule und ein eigenes SignatureModule für die RKOnline zu implementieren (v1), das auch mit dem Service kommuniziert. Das ganze funktioniert mal soweit, Signatur kommt auch an.

Ob es valide ist wird noch geprüft. Kann ich dafür auch das Verification-Tool vom Mustercode einsetzen, auch wenn ich zB den Private Key nicht kenne ?

RKOJwsModule:
http://pastebin.com/RPSW1DR0

RKOSignatureModule:
http://pastebin.com/1j0jcPjR

**Comment by ErichFreitag** [comment]
Die Signaturvalidierung erfolgt "naurgemäß" über den öffentlichen Schlüssel. Was meinen sie mit Einsatz ohne Kenntnis des private keys?

**Comment by robertpic71** [comment]
Ja man kann das auch gegen das Prüftool laufen lassen, die **crypto.json** musste ich dafür aber "manuell" bearbeiten, da ich diesen Teil des ASit-Demos nicht überschrieben haben.

Den PrivateKey (der Signatur) braucht man im echten Leben nicht bzw. hat ihn auch gar nicht. 

BTW: es gibt auch eine URL für .../Sign/JWS/ welche die komplette Abwicklung für dich macht.

**Comment by Thomas233** [comment]
Hallo,

ok danke habe es nun verstanden und alles gefunden.

Ich bin mittlerweile - da der Aufruf des Java-Mustercodes aus PHP heraus leider von der Performance her sehr lange dauern würde - auf eine eigene PHP-Variante umgestiegen.
Dort verwende ich die JWS-Signatur der RK Online, funktioniert super.

Nur habe ich folgendes Problem mit dem Umsatzzäher:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/501

Dieses Thema hier wäre aber erledigt, vielen Dank nochmal !
