### ISSUE TITLE
"FAIL" bei Gültigkeitsüberprüfung der Signatur

### ISSUE THREAD

**Issue by Ancaron** [a-sit-plus/at-registrierkassen-mustercode#455]
Hallo beisammen,

Bei den Überprüfungen der von uns implementierten Signierung mithilfe der RKS-CARD von Globaltrust tritt leider immer noch der Fehler 
>         "verificationResultDetailedMessage" : "Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen."
auf.

Da nach mehrmaliger Überprüfung von unserer Seite aus (inklusive Verifizierung der Schritte aus dem Dokument "2016-12-12 SIG-Check.pdf") nun die Ideen ausgegangen sind, und ich auch bei der Suche in den bisherigen Issues nichts weiteres finden konnte, bitte ich nun hier um mögliche Hilfestellungen.
Der Einfachheit halber gehen wir von der einfachen Belegüberprüfung (mittels "regkassen-verification-receipts-1.0.0.jar") aus und nicht vom DEP-Export.

 Die Vorgehensweise zur Signierung ist momentan wie folgt: 

Zusammenfügen der kompakten JWS-Repräsentation 
 Base64URL(Header).Base64URL(Payload)

Hashen von diesem Wert (SHA256) und übertragen des Hashwertes an die Karte zur Signierung.
Von dort erhalten wir 64Byte RawDaten zurück, die wir Base64Kodieren und so auf dem Kassenbeleg(QRCODE) als letztes Element ausgeben.

Im Anhang befinden sich, die von mir bisher verwendete CMC/QRCodeRep Datei.

[cryptographicMaterialContainer .txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/858759/cryptographicMaterialContainer.txt)
[qr-code-rep.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/858760/qr-code-rep.txt)

**Comment by Flanelli** [comment]
Was gleich auffällt:
Erster Beleg
_CashBox01_0000001
_2016-10-01T15:38:50

Zweiter Beleg - gleiche Belegnummer und Zertifikatnummer fehlerhaft es ist zwischen C,A ein Veistrich
_CashBox01_0000001
_2016-10-01T16:41:38
_014**C,A**F45CB91EEF7A9D61B3C58

**Comment by Ancaron** [comment]
Entschuldigen Sie, ich hatte die kurze Erläuterung zu den Testdaten vergessen.
Die ersten beide Belege wurden mit festgelegten Testdaten erstellt. Daher die gleiche Belegnummer/gleicher Umsatzzähler. 
Die Belege 3+4 wurden mit Daten erstellt, wie sie später im Live-System auftreten werden.

Es handelt sich dabei jeweils um einen Beleg mit intakter Signatureinrichtung und um einen mit Ausfall der Signatureinrichtung. Dies wurde durchgeführt um die sonstigen Punkte der Erstellung des maschinenlesbaren Codes zu überprüfen, da das Prüftool bei der Signatur jedes mal schon gestoppt hat.

**Comment by Flanelli** [comment]
Irre ich mich oder tritt das Problem nur bei den Belegen mit ausgefallener SE auf?
Dann könnte es aber doch an dem Handling des Vorganges liegen, an der Karte
selbst zwangsläufig nicht denn die wäre ja ausgefallen ....
Aus den QR-Sexquenzen selbst kann ich nichts wirkliches ergründen aber ich denke 
Hr. Ing Freitag hat da sicher einen Top-Tip oder gar die Lösung

**Comment by Ancaron** [comment]
Sofern ich bei mir den Aufruf nicht verpatzt habe, ergeben die Bons 1 und 4, bei denen eine gültige Signatur da sein sollte den FAIL. 
Mein Aufruf sieht dabei wie folgt aus : 
`java -jar regkassen-verification-receipts-1.0.0.jar -v -f -i qr-code-rep.json -c cryptographicMaterialContainer.json -o .`

Und als Ergebnis bekomme ich in der Ausgabe die beiden Protokolle im Anhang.
[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/859773/0000_cashbox_full.txt)
[0003_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/859775/0003_cashbox_full.txt)

**Comment by ErichFreitag** [comment]
Eine unmittelbare Lösung habe ich nicht, die Daten schauen soweit ersichtlich OK aus, das Zertifikat ist auch OK.

Vielleicht hilft es, die Signaturerstellung nochmals mit folgender Grafik durchzugehen und da und dort einen Trace einzubauen.

![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/24183863/1b3c6378-0ecb-11e7-8e37-56b2b3e5cd63.jpg)

**Comment by Ancaron** [comment]
Vielen Dank für die Unterstützung. Auch wenn es nichts direkt mit der Signaturerstellung zu tun hatte, sondern in der Datenübermittlung zur Signatureinheit lag, konnten wir durch die Bestätigung, dass sowohl Zertifikat als auch die Daten in Ordnung zu sein scheinten den Fehler ermitteln und die Überprüfung klappt nun.
