### ISSUE TITLE
Aktueller Stand zum Inhalt eines Sammelbelegs?

### ISSUE THREAD

**Issue by robongit** [a-sit-plus/at-registrierkassen-mustercode#456]
unter https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/78 ist zu lesen:

> Zum Inhalt eines Sammelbelegs: siehe Erläuterungen zur RKSV § 17:
Für den Sammelbeleg sind die Belegdaten gemäß § 132a Abs. 3 BAO maßgeblich, wobei sämtliche Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“
versehen wurden, in den Sammelbeleg aufzunehmen und dabei je Beleg, als Menge die fortlaufende Nummer des jeweiligen Barumsatzes, als handelsübliche Bezeichnung der maschinenlesbare Code des jeweiligen Barumsatzes und als Betrag der Barzahlung „Null (0)“ einzutragen sind.

Gilt das noch?
Auf welchem Bon soll der "maschinenlesbare Code" (der Länge nach) Platz haben?

Im Erlass unter "3.6.1. Ausfall der Signatur- bzw. Siegelerstellungseinheit oder der Registrierkasse" finde ich lediglich:

> Aus dem Beleg muss der Beginn und das Ende des Ausfalles der Signatur- bzw. Siegelerstellungseinheit (z.B: durch Angabe der jeweiligen laufenden Nummer) hervorgehen.

**Comment by ErichFreitag** [comment]
Der Sammelbeleg wird nicht gedruckt. Das im Erlass ist letzt-relevant.

**Comment by robongit** [comment]
Danke für die schnelle Antwort.

**Comment by theshadowtwentyseven** [comment]
Mhm, wir erstellen einen Sammelbeleg mit 0,- Summe und:

* über den Ausfall den Start Zeitpunkt (Timestamp wann die Signierung erstmal fehlschlug) sowie
* Endzeitpunkt (Zeitpunkt ab dem Signierung wieder funktionierte)
* Bon# die dazwischen nicht signiert werden konnte

Dies sollte die Anforderungen des Erlasses abdecken oder verstehe ich es falsch?

Danke schön!

**Comment by ErichFreitag** [comment]
Sammelbeleg mit Anzeige des Beginns und des Endes des Ausfalls, also entweder Timestamp oder jeweilige Belegnummer oder beides. Jene dazwischen sind nicht erforderlich weil ja jederzeit rekonstruierbar.
