### ISSUE TITLE
Wechsel der Signaturkarte

### ISSUE THREAD

**Issue by aortner** [a-sit-plus/at-registrierkassen-mustercode#458]
Wie ist beim Wechsel einer Signaturkarte (defekt) vorzugehen?

**Comment by ErichFreitag** [comment]
Neue besorgen, alte abmelden, neue anmelden.
Zur Sicherheit eine Belegprüfung durchführen.

**Comment by aortner** [comment]
OK, danke. DEP läuft mit neuer Karte einfach weiter.

**Comment by ErichFreitag** [comment]
So ist es. Am einfachsten sequentiell ohne Gruppierung von Belegen im DEP-Export.
