### ISSUE TITLE
Was muss ein Sammelbeleg enthalten?

### ISSUE THREAD

**Issue by avosskoetter** [a-sit-plus/at-registrierkassen-mustercode#46]
Welche Bestandteile muss der Sammelbeleg nach der wieder Inbetriebnahme einer defekten Signaturerstellungseinheit beinhalten und wie sehen die zu signierenden Daten des Sammelbelegs dann aus?

Lt. Verordnung muss der Sammelbeleg den Text "Sammelbeleg" mit dem Faktor 0,00 und dem Wert 0,00 enthalten. Müssen noch zusätzliche Daten aufgenommen werden?

Fließt in die Signatur nur der verschlüsselte Umsatzzähler ein und die einzelnen Werte für die Steuerumsätze sind 0 oder müssen in den Werte für die Steuerumsätze die aufsummierten Werte für die Zeit des Ausfalls angegeben werden?

**Comment by asitplus-pteufl** [comment]
Der Sammelbeleg ist ein Nullbeleg (Details siehe Erläuterungen zu Nullbeleg in V1.0).
D.h. alle Steuersätze = 0
Verkettung zu vorigem Beleg ohne Signatur (also markiert mit Sicherheitseinrichtung ausgefallen) gleich wie sonst.
Umsatzzähler ist in einem Nullbeleg vorhanden, ändert sich aber nicht (zu vorher) da ja alle Beträge 0 sind.

**Comment by avosskoetter** [comment]
D.h. also, dass die Belege mit der Markierung "Sicherheitseinrichtung ausgefallen" auch über diese immer gleiche Signatur verkettet werden!?

<Korrekte Signatur> --> <Sicherheitseinrichtung ausgefallen> --> ...  --> <Sicherheitseinrichtung ausgefallen> --> <Korrekte Signatur>

Wäre es nicht sinnvoller, den Sammelbeleg mit der letzten korrekt erstellten Signatur zu verketten?

**Comment by asitplus-pteufl** [comment]
Was meinen Sie mit "auch über diese immer gleiche Signatur verkettet werden!?"? Die Verkettung wird ja über die HASH-Wert Bildung des letzten Belegs durchgeführt und nicht über den Signaturwert.
Für Details dazu verweise ich auf das Erläuterungsdokument.

**Comment by avosskoetter** [comment]
Stimmt, da habe ich falsch gedacht!

Danke für die schnelle Antwort.

**Comment by asitplus-pteufl** [comment]
Dann schließ ich das. Noch als Hinweis, diese "Use Cases" oder Abläufe werden in V1.2 und V0.7 Des Prüftools noch im Detail behandelt (inklusive passender Testfälle). V1.1 des Dokuments und V0.6 des Prüftools mit Basistestfällen werden diese Woche zur Verfügung stehen.
