### ISSUE TITLE
QR-Code Standards, Probleme mit iOS und Jasperreports

### ISSUE THREAD

**Issue by florian-aistleithner** [a-sit-plus/at-registrierkassen-mustercode#460]
Hallo,

wir haben das Problem, dass unsere QR-Codes nicht vom iOS-BMF-App als QR-Codes erkannt werden. Auf Android hatten wir noch nie Probleme (sofern die QR-Code-Größe mit der Druckqualität zusammenpasst), auch mit allen anderen QR-Code-Lese-Apps auf iOS können wir die QR-Codes lesen.

Jetzt schreibt das Dokument zu den Detailfragen folgenden Standard vor:
JIS X 0510:2004

Wir erzeugen unsere Bons mit Jasperreports 6.2.1, welches für die QR-Codes die Bibliothek barcode4j in der Version 2.1 verwendet. Wenn ich beim barcode4j-Projekt auf der Homepage nachsehe, steht dort, dass sie den Standard "ISO/IEC 18004:2006(E)" verwenden, der eine Erweiterung des oben genannten JIS-Standards ist. Kann es dadurch Probleme in der iOS-BMF-App geben oder sollte das kompatibel sein?

Ich habe alle Error-Correction-Levels ausprobiert, die BMF-App am IPhone konnte keinen unserer QR-Codes erkennen.

Wir können die Kassen unserer Kunden zwar mit einem Android-Handy in Betrieb nehmen, allerdings bekommen wir vmtl. Probleme, wenn die Finanz-Prüfer bei einer Prüfung nur ein IPhone besitzen?

**Comment by lebail** [comment]
ISO/IEC 18004:2006(E) unterstützt im Vergleich zu JIS X 0510:2004 einige zusätzliche Features (spiegelbildliche Anordnung, Hell-/Dunkel-Vertauschung, Definition von Character sets). Wenn Sie diese Features nicht nützen, müssten die erzeugten QR-Codes zu JIS X 0510:2004 (Model 2) kompatibel sein.

Einige Infos zu den Unterschieden finden sich auf der letzten Seite von:
https://shop.austrian-standards.at/Preview.action;?preview=&dokkey=225899

**Comment by Flanelli** [comment]
Also wenn es daran hapert dass der Finanzprüfer nur ein IPhone besitzt dann tritt meines Erachtens
der, vom BMF schriftlich festgekegte Passus für all jene die kein Handy oder eines mit einer veralteten  OS-Version in Kraft der da lautet:

 SIE MÜSSEN KEIN EIGENES HANDY BESITZEN, DIE KÖNNEN SICH NATÜRLICH AUCH EIN HANDY AUSBORGEN :-)

**Comment by florian-aistleithner** [comment]
Schon, aber wenn im Gesetz steht, dass JIS X 0510:2004 zu verwenden ist und wir verwenden etwas neueres, ist unsere Kassenlösung dann nicht RKSV-Konform? Dass es in der Android-Version dennoch geht ist dann quasi nur Glück?

**Comment by Flanelli** [comment]
@florian-aistleithner Natürlich wird der, in den Begriffsbestimmungen der Verordnung
 definierte Standard letztendlich Gültigkeit haben - mein vorheriger Post war primär Ironie - sorry about.

**Comment by andreasschiestl** [comment]
Ich vermute, dass es irgendein Detail gibt, dass für die in der Android-App verwendete QR lib kein Problem ist, in iOS aber schon.

Eventuell gibt es eine Möglichkeit den QR-Code zu analysieren und so den verwendeten Standard festzustellen.

**Comment by florian-aistleithner** [comment]
Dann wird mir wohl nichts anderes übrig bleiben unserem jasperreports beizubringen die richtige Version des QR-Codes zu erzeugen, wie auch immer das dann passieren soll (eigenes lib für qr-codes, neue Features deaktivieren o.ä.).

**Comment by florian-aistleithner** [comment]
@andreasschiestl Gute Idee, ich habe nur noch kein App gefunden, welches mir die "Header"-Daten des QR-Codes ausliest und anzeigt. Vielleicht kann ich mir mit zxing da selbst was bauen.

**Comment by andreasschiestl** [comment]
Wir verwenden auch JasperReport (aber Version 6.4.0) mit barcode4j für die QR Codes. Wenn es aber stimmt verwendet Jasper Report für die QR-Code generierung iText und nicht barcode4j 😮 
http://jasperreports.sourceforge.net/sample.reference/barcode4j/index.html

**Comment by florian-aistleithner** [comment]
@andreasschiestl Du hast vmtl. recht. barcode4j kann in Version 2.1 gar keine QR-Codes erzeugen, das geht erst in der aktuellen "In Development"-Version.

**Comment by andreasschiestl** [comment]
Bin mir aber nicht wirklich sicher ob dieses Dokument zu 100% stimmt. Stimmen dürfte zumindest, dass der QR-Code nicht von barcode4j erzeugt wird (weil es Version 2.1 nicht kann), bin aber nicht sicher ob es iText ist, denn Jasper Report hat eine Dependency auf com.google.zxing:core

**Comment by florian-aistleithner** [comment]
Ich habe gerade folgende Klasse QRCodeRasterizedImageProducer im jasperreports.jar gefunden:
Hier wird die zxing-Klasse QRCodeWriter verwendet um das image zu erzeugen.

**Comment by andreasschiestl** [comment]
warst schneller :D
https://github.com/Jaspersoft/jasperreports/blob/master/jasperreports/src/net/sf/jasperreports/components/barcode4j/QRCodeRasterizedImageProducer.java

**Comment by andreasschiestl** [comment]
Da ja spiegelbildliche Anordnung oder Hell-/Dunkel-Vertauschung offensichtlich nicht genutzt wird, kann es fast nur das Encoding sein, in diesem Fall wird anscheinend UTF-8 verwendet. Ich weiß aber nicht das nun gut oder nicht gut ist. bzw. ob das einen Unterschied zu JIS X 0510:2004 ausmacht.

**Comment by florian-aistleithner** [comment]
Ich werds wohl ausprobieren müssen und einen QR-Code mal ohne den CHARACTER_SET-hint erzeugen und schauen obs die iPhone-App lesen kann. (bzw. die zxing-doku mal etwas genauer ansehen) Zur Not muss ich halt Änderungen im Jasperreports (genauer: im QRCodeRasterizedImageProducer) machen, das wollte ich eigentlich vermeiden, weil  das auch von anderen Programmen verwendet wird.

Jedenfalls sag ich erstmal vielmals Danke für die Unterstützung! Ich melde mich, wenn ich neue Erkenntnisse habe.

**Comment by florian-aistleithner** [comment]
Genau das wars. Wenn ich den CHARACTER_SET-hint mitgebe, kanns das iOS-BMF-App nicht lesen, wenn ich das nicht mache dann gehts! Das heißt ich muss den QRCodeRasterizedImageProducer ändern.

Danke für die Hilfe!

**Comment by andreasschiestl** [comment]
Ich würde vielleicht auch mal versuchen festzustellen ob der QR-Code gemäß JIS X 0510:2004 ist, habe leider nicht wirklich etwas gefunden wie man das am besten macht, denn ich würde nicht ausschließen, dass die Belegchecker-App fehlerfrei ist.

Ich kann das Problem leider bei mir auch reproduzieren :/ 

Als Alternative zu Source ändern und selbst kompilieren, könnte man den Wert von `QRCodeComponent.PROPERTY_DEFAULT_ENCODING`  auf `"ISO-8859-1"` (Default Wert, wenn keiner gesetzt) über Reflection ändern.

**Comment by florian-aistleithner** [comment]
Ich glaube Reflection funktioniert auf manchen Servern unserer Kunden nicht. Zumindest beim Versuch das Unlimited-Strength zu umgehen bekomme ich auf manchen Systemen eine SecurityException.

Ist das der Default-Wert im zxing?

**Comment by andreasschiestl** [comment]
Ja kann sein dass ein eingerichteter Security-Manager dazwischen funkt. http://stackoverflow.com/questions/3301635/change-private-static-final-field-using-java-reflection

Ja das ist der Default-Wert aus zxing (zxing/core/src/main/java/com/google/zxing/qrcode/encoder/Encoder.java)
```
static final String DEFAULT_BYTE_MODE_ENCODING = "ISO-8859-1";
...
public static QRCode encode(String content,
                              ErrorCorrectionLevel ecLevel,
                              Map<EncodeHintType,?> hints) throws WriterException {
....
    if (encoding == null) {
        encoding = DEFAULT_BYTE_MODE_ENCODING;
    }

...

    if (mode == Mode.BYTE && !DEFAULT_BYTE_MODE_ENCODING.equals(encoding)) {
        CharacterSetECI eci = CharacterSetECI.getCharacterSetECIByName(encoding);
        if (eci != null) {
            appendECI(eci, headerBits);
        }
    }
....
}
```

Das zweite `if`-Statement ist vermutlich der entscheidende Unterschied

**Comment by andreasschiestl** [comment]
Als Alternative könntest du auch zxing modifizieren.

**Comment by florian-aistleithner** [comment]
Hashtable<DecodeHintType, Object> hintMap = new Hashtable<DecodeHintType, Object>();
		hintMap.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
		try {
			BufferedImage img = null;
		    img = ImageIO.read(new File("c:\\temp\\qr2.png"));
			BufferedImageLuminanceSource source = new BufferedImageLuminanceSource(img);
			HybridBinarizer binarizer = new HybridBinarizer(source);
			BinaryBitmap bitmap = new BinaryBitmap(binarizer);
			QRCodeReader reader = new QRCodeReader();
			Result result;
			result = reader.decode(bitmap, hintMap);
			BarcodeFormat barcodeFormat = result.getBarcodeFormat();
			System.out.println("barcode format: " + barcodeFormat);
			byte[] rawBytes = result.getRawBytes();
	
			Map<ResultMetadataType, Object> resultMetadata = result.getResultMetadata();
			Set<Entry<ResultMetadataType,Object>> entrySet = resultMetadata.entrySet();
			for(Entry<ResultMetadataType,Object> entry : entrySet) {
				ResultMetadataType key = entry.getKey();
				Object value = entry.getValue();
				System.out.print(key+ ": ");
				System.out.println(value);
			}
			System.out.println("############## " + result);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}



Das ist alles was das Result vom zxing-Reader ausspuckt. Man könnte jetzt die ersten paar bytes der rawBytes interpretieren, wenn man die Normen hätte. Die raw-Daten sind nämlich um ein paar Bytes länger als der Text, wenn ich das jetzt richtig interpretiere.

Ansonsten ist das Issue für mich fixed.

**Comment by andreasschiestl** [comment]
Kurz zur Info falls noch jemand darüber stolpert. Ändern des Werts mit Reflection geht scheinbar nicht. Also die Änderung selbst funktioniert, aber anscheinend wird durch Code-Optimierung der String dort direkt eingesetzt und nicht mehr eine Referenz auf das static final Field.

Ich habe nun auch die betroffene Klassen manuell überschrieben (aber nur die eine Klasse), die hat in meinen Fall (hängt von Prioritäten der Classloader ab) eine höhere Priorität als die von jar.

Es gibt auch ein Ticket im Jasper Bugtracker http://community.jaspersoft.com/jasperreports-library/issues/9166 Eventuell wird es ja mal ergänzt.
