### ISSUE TITLE
Gesetze nicht erfüllt bis 01.04.

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#462]
Hallo,

ist die Information zufällig bekannt, in dem Fall dass die gesetzliche Herausforderungen ab 01.04. nicht erfüllt sind, mit welche Straffen wird die Firma dann bestraft, bzw gibt es zufällig noch einen Zeitraum
bis wann dann das doch strafefrei eingerichtet werden kann?

mit andere Worten, wie hoch sind die Geldstrafen?

MfG

SPIT

**Comment by Flanelli** [comment]
Zu finden znter 
https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Registrierkassen.html
