### ISSUE TITLE
Bereits in Betrieb genommene Kasse: Prüftool meldet einen einzigen fehlerhaften Datensatz. Bitte um Hilfe bei Interpretation der Fehlermeldung

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#465]
Guten Tag an Alle.
Ich hatte gehofft es wird nicht passieren - aber leider doch...

Wir haben mehrere PC-Kassen im Einsatz die bereits vor Wochen angemeldet wurden.
Es schien alles problemlos zu laufen.
Nun habe ich alle DEPs, mit hunderten Einträgen, sicherheitshalber mit dem Prüftool getestet.
Bei einer der Kassen meldet das Prüftool einen fehlerhaften Datensatz - aber ich kann mit der Fehlermeldung nichts anfangen.
Vor allem deshalb nicht weil die Software auf ja allen Kassen ident ist und nur ein einzelner Datensatz eines einzigen DEPs beanstandet wurde.
Ich bitte daher um Hilfe damit ich eine Idee bekomme wo ich suchen könnte:

Die "DEP.Json" zeigt überall "PASS"
Nur in der 00xx_Cashbox_full.json des beanstandeten Beleges sind 3 Bereiche mit FAIL:

FAIL 1:
  "verificationId" : "VERIFICATION_FROM_CASHBOX",
  "version" : 1,
  "verificationName" : "Prüfergebnis - Kasse",
  "verificationTextualDescription" : "Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.",
  "verificationState" : "FAIL",
  "verificationResultDetailedMessage" : "Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Am besten, Sie  übermitteln zur Problembehandlung die nachfolgende Fehlerbeschreibung an Ihren Kassenhersteller.",
 
FAIL 2:
  "verificationId" : "RECEIPT_FULL",
    "version" : 1,
    "verificationName" : "Detailprüfung des maschinenlesbaren Codes",
    "verificationTextualDescription" : "Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.",
    "verificationState" : "FAIL",

FAIL 3:
      "verificationId" : "CRYPTO",
      "version" : 1,
      "verificationName" : "Kryptographische Prüfungen",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-03-22T16:26:59.732+01:00",
      "verificationResultList" : [ {
        "verificationId" : "CRYPTO_SIGNATURE",
        "version" : 1,
        "verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
        "verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.",
        "verificationState" : "FAIL",

Was kann die Ursache sein ?
Nachdem alle Belege mit der gleichen Methode signiert werden kann ich mir nicht vorstellen daß es ein Softewarefehler ist .

Dies ist die beanstandete Signatur:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9LYXNzYS1MQjFfMjAxNzAwMjgxM18yMDE3LTAzLTIxVDA5OjQzOjM0Xzk5LDI1XzAsMDBfMCwwMF8wLDAwXzAsMDBfb2dWOXVseDQzQ009XzAxRDdDMEZGNkJBMTU0MUM2REUyODc0NTU3Xy8vcER4NWZobUFnPQ.B0MuVOK4VhVwd9Jc_AVnvOvprzxjx70LzRiRqvR3pHQ6_OT_eeLXVx3manKhBXRh0Xicp-A21CLeF8gJ1Q2yqg

1000 Dank für jede Hilfe.

**Comment by andreasschiestl** [comment]
Also der Fehler bedeutet, dass die Signatur fehlerhaft ist. Warum genau ist schwer fest zu stellen. Ich hatte vor einer weile auch ein Problem, dass ein Teil der Signaturen fehlerhaft war. Bei mir war der Grund dass der Zeitstempel beim speichern in der Datenbank gerundet wurde (also der Sekundenbruchteil) und bei einem erneuten Abrufen aus der Datenbank die Zeit um 1s anders war.

Ob so etwas bei dir in Frage kommt, hängt davon ab wie die Daten gespeichert werden, eventuell wird etwas anderes gespeichert als signiert wird.

**Comment by Skerge12** [comment]
Hallo Andreas,
vielen Dank für Deinen Hinweis.
Ich erstelle die Signatur sofort und speichere das Ergebniss erst dann in der Datenbank.
Aus dieser werden die Signaturen bei Bedarf in die DEP.Json exportiert.
Somit können eigentlich zur Signierung übergebene Belegdaten den Fehler nicht verursachen ?
Was könnte sonst noch einen Fehler verursachen bzw. wie könte ich beanstandete Signaturen prüfen um den Fehler zu finden ?
Das Prüftool ist hier leider nicht sehr hilfreich.

**Comment by andreasschiestl** [comment]
Das Prüftools ist desshalb nicht sehr hilfreich weil man hier nicht mehr Informationen bekommen kann, die Signatur ist gültig oder nicht. Die siegnierten Daten lassen sich aus der Signatur nicht rekonstruieren und somit kann man auch nicht so leicht sagen warum die Signatur ungültig ist.

Ohne mehr Informationen kann schwer etwas sagen und da der Fehler scheinbar selten auftritt wird du vermutlich keine Zwischenwerte des Signaturprozess zur Verfügung stellen können.

Wenn du sagst du erstellst die Signatur und speicherst das Ergebnis, wie speicherst du das Ergebnis genau, wie speicherst du die Payload? Die ganze Zeichenkette als String oder die einzelnen Felder (verschiedene Beträge, Zeitstempel usw.) in nativen Datentypen?

**Comment by Skerge12** [comment]
Hallo Andreas,
da ich mit Kryptograpie nicht auskenne verwende ich zur Signierung ein externes COM Modul von ITG consulting (www.itgconsulting.at) das als DLL in mein Programm eingebunden ist.
Dabei werden alle signaturrelevanten Daten an die Funktion übergeben und ich erhalte einen fertigen JWS String zurück den ich in einer SQLite Datenbank speichere.
Bei einem DEP Export lese ich die Daten aus der Datenbank aus und erstelle eine  DEP JSON Datei damit.
Ich nehme nicht an dass der Fehler in der DLL liegt da diese ja von Experten erstellt wurde, zumindest klammere ich das mal aus.
Eventuell speichert die SQLite Datenbank nicht alle Zeichen korrekt oder ich mache einen Fehler beim Erstellen des JSON Exportes.

Was mich wundert ist dass das Prüftool nur einen einzigen Datensatz als ungültig meldet.
Oder wird nach dem ersten Fehler die Prüfung abgebrochen ?
Dann hätte ich eventuell noch mehr fehlerhafte Datensätze und weiss es nur nicht.

Gibt es eine Möglichkeit einen fehlerhaften Signaturstring zu zerlegen und dann die einzelnen Elemente auf Korrektheit zu prüfen ?

**Comment by lebail** [comment]
Ja, das Prüftool bricht nach einem Fehler ab.

Im Output des Prüftools befindet sich unter anderem der maschinenlesbare Code der geprüften Belege im Klartext (unter "RECEIPT"). Eventuell besteht bei der fehlerhaften Kasse in diesen Daten eine Auffälligkeit (z.B. Unterstrich in der Kassen-ID oder Belegnummer; falsche Darstellung der Seriennummer; Betrag mit Tausendertrennzeichen, der aber ohne Tausendertrennzeichen signiert wurde etc.)?

Die Signatur selbst kann man leider prinzipiell nicht analysieren, denn in ihr ist keine strukturierte Information enthalten.

**Comment by theshadowtwentyseven** [comment]
Hi Skerge12,

Du könntest einfach die Signatur "merken", danach in die SQLite persistieren, von dort wieder in eine zweite Variable auslesen und vergleichen. Das wird Dir etwaige Unterschiede aufzeigen.

**Comment by Skerge12** [comment]
Vielen Dank für die Hinweise.
Ich mache mich auf die Fehlersuche und melde mich wenn ich fündig werde.
DANKE AN ALLE :)

**Comment by Flanelli** [comment]
@Skerge12 Vermutung ...  daher Frage = Ist bei diesem Beleg ein Betragswert >=1000,00 ?

**Comment by andreasschiestl** [comment]
Dass das Prüftool nach einem Fehler abbricht ist nicht ganz richtig. 
Die DEP-Prüfung bricht ab, also die Prüfung der Verkettungswerte und Umsatzzählerentwicklung.

Die Einzelbelegsprüfung (wie eben Signaturüberprüfung) wird auch bei einem fehlerhaften Beleg für alle Belege durchgeführt.

Da in dem Fall anscheinend die verwendete SW-Bibliothek einen Großteil der Arbeit abnimmt würde ich eventuell auch versuchen mit dem Hersteller dieser in Kontakt zu treten. Muss nicht zwingend sein, dass der Fehler dort liegt, aber der Soppurt kann Ihnen eventuell gezielter helfen, da die genau wissen welche Werte übergeben werden müssen und wo eventuell Stolpersteine und mögliche Fehlerquellen sein können.

**Comment by Skerge12** [comment]
@Skerge12 Vermutung ... daher Frage = Ist bei diesem Beleg ein Betragswert >=1000,00 ?
Nein - der Betrag 99,25

**Comment by Skerge12** [comment]
Guten Tag,
bin wieder da :)

Ich habe jetzt eine Gemeinsamkeit bei allen Signaturen die vom Prüftool beanstandet wurden gefunden:
Der dritte Teil (also nach dem zweiten "." ist immer: "NmE4OA"

Hier 2 der beanstandeten Signaturen:

eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9LYXNzYS1MQjFfMjAxNzAwMjgxNF8yMDE3LTAzLTIxVDEwOjAyOjI2XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF9naEYxa002WHNCWT1fMDFEN0MwRkY2QkExNTQxQzZERTI4NzQ1NTdfNUw1UEMwd2xyRlE9.NmE4OA

eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9LYXNzYS1MQjFfMjAxNzAwMjk2OV8yMDE3LTAzLTI0VDA5OjI0OjA0XzYsMjFfMCwwMF8wLDAwXzAsMDBfMCwwMF9RTUhJOHBNbURYbz1fMDFEN0MwRkY2QkExNTQxQzZERTI4NzQ1NTdfTVd3TmZaWHVENjg9.NmE4OA

Diese Signaturen unterscheiden sich im dritten Teil deutlich von denen die ein "PASS" bekommen.
Da ich mich mit Kryptographie bzw. mit dem Erstellen der Signatur nicht auskenne (sondern dazu, wie gesagt, eine zugekaufte DLL von ITG Consulting verwende bitte ich diesbezüg um Hilfestellung damit ich weiß wie ich den Fehler am Besten beheben kann.

Wodurch könnte so eine fehlerhafte Signatur entstehen ?

Dankeschön :)

**Comment by ErichFreitag** [comment]
Die Signatur muss 88 Zeichen haben, da stimmt etwas grundsätzlich nicht. Was ist bei diesen Einträgen anders?

Die Belegnummer geht mir in der Payload ab.

**Comment by Skerge12** [comment]
Sehr geehrter Herr Dr. Freitag,
danke für die Info.
Ich werde jetzt nachprüfen ob die Übergabe der Parameter von meinem Programm an die DLL bei diesen Belegen korrekt war.
Falls ja hat eventuell die DLL einen Bug.
Da ich aber jetzt weiß daß die Signatur immer 88 Zeichen lang sein muss kann ich hier zumindest eine Fehlerroutine einbauen und den Signaturvorgang wiederholen.

**Comment by Flanelli** [comment]
@Skerge12 Welche Version der RKSVComComplete.dll verwenden Sie?

**Comment by Skerge12** [comment]
>>> Welche Version der RKSVComComplete.dll verwenden Sie?
1.74

**Comment by ErichFreitag** [comment]
Ich bin kein Dr. Deshalb darf ich auch jetzt ganz wild spekulieren:
- sie übergeben bei den beiden Belegen keine Belegnummer
- die DLL prüft die Inhalte der Payload
- und gibt einen Fehler retour, den sie nicht abfangen

Zur Präzisierung: die binäre Signatur ist 64 Bytes lang, die BASE64-codierte Signatur 88 Zeichen.

**Comment by Flanelli** [comment]
@Skerge12 Dann ist alles klar. Die V 1.74 retourniert fallweise einen verkürzten Signaturstring der
stets  NmE4OA lautet.  Sie erhalten aber dabei keinen expliziten Fehlerhinweis und daher müßten Sie
selbst überprüfen ob die Signatur auch zumindest die gültige Länge innehat wobei man dies ohnehin
und unabhängig des benutzen Tools bzw. Libraries und Sprachen machen sollte.

Nachdem Sie lt. Ihrem Eingangposting die DLL ja nicht mehr im Testmodus verwenden sondern 
bereits mehrere Kassen bei Kunden im Einsatz haben müßten Sie ja dafür auch gültige Lizenzen erworden haben und daher vom Hersteller bzw. Lieferanten auch eine aktuelle Versionen bekommen. So weit ich weiß sollte das 1.77 sein aber ich bin da möglicherweise auch nicht am letzten Wissensstand da ich mehrere Lösungen für die RKSV im Checklauf habe.

**Comment by Skerge12** [comment]
Sehr geehrter Herr Freitag,
- Ich bin kein Dr. ....
Bitte um Entschuldigung :)

- sie übergeben bei den beiden Belegen keine Belegnummer
Bin dzt. nicht im office und werde das aber morgen prüfen, bin mir aber doch ziemlich sicher daß dies in Ordnung ist (aber sag' niemals nie ...)

- den sie nicht abfangen
Die Funktion gibt trotz fehlerhafter Signatur ' true' zurück.
Ich werde aber die Prüfung nun auf die Länge der Signatur erweitern

**Comment by Skerge12** [comment]
- müßten Sie ja dafür auch gültige Lizenzen erworden haben 
Korrekt
- und daher vom Hersteller bzw. Lieferanten auch eine aktuelle Versionen bekommen. 
Leider nein. Bis dato musste ich jedesmal selbst nachfragen und hatte dies auch für nächste Woche vor.
- So weit ich weiß sollte das 1.77 sein aber ich bin da möglicherweise auch nicht am letzten Wissensstand da ich mehrere Lösungen für die RKSV im Checklauf habe.
Dankeschön für diese Info

**Comment by Flanelli** [comment]
@Skerge12 Wenn Sie gestatten erlaube ich mir noch folgende Hinweise auch wenn dies Ihnen sicher
bekannt ist aber möglicherweise nicht beachtet wird.

... Die Funktion gibt trotz fehlerhafter Signatur ' true' zurück.
Ich werde aber die Prüfung nun auf die Länge der Signatur erweitern ....
Nicht nur der Boolsche Rückgabewert der Fuinktion ist zu checken sondern auch der Rückgabestring des
letzen Parameters "sAntwort". Dieser String lautet z.B. auch "Sicherheitseinrichtung ausgefallen" aber 
es können auch diverse Problem- bzw. Konflikthinweise enthalten sein die im Falle eines Fehlers auch
weiterhelfen könnten. Das "true" bedeutet leider nicht dass die Signatur auch wirklich absolut korrekt ist.

Es wäre auch generell empfehlenswert wenn Sie nach der Erstellung der Signatur diese durch einen Gegencheck auch gleich selbst in der Appllikation nochmal überprüfen.
Geht ganz einfach über die Funktion VerifyJWS(sJWSCompactresult, certificateBase) 
1000 %tige Sicherheit werden Sie dadurch zwar auch nicht erlangen aber es beruhigt doch ein wenig ...

PS: Rein interessehalber - in welcher Sprache entwickeln sie Ihre Inhouse-Lösung?

**Comment by ErichFreitag** [comment]
Dann ziehe ich meine Spekulation zurück, ich habe beim Decodieren zuvor warum auch immer keine Belegnummer gesehen. Wenn das Verhalten des Rückgabewerts in jener Version von @Flanelli bekannt ist wird es wohl das sein.

**Comment by Skerge12** [comment]
@Flanelli 
1000 Dank :)
- PS: Rein interessehalber - in welcher Sprache entwickeln sie Ihre Inhouse-Lösung?
PowerBasic (www.powerbasic.com)

@Erich Freitag
Vielen Dank ebenfalls für das geduldige Abarbeiten und Erklären.

Ich wünsche einen wunderbaren Sonntag :)
