### ISSUE TITLE
Testen mit möglichst realen Testdaten

### ISSUE THREAD

**Issue by ep27** [a-sit-plus/at-registrierkassen-mustercode#466]
Hallo, 

ich würde gerne vor der eigentlichen Inbetriebnahme der Kassa einige Tests mit dem realen Zertifikat durchführen. Also das in FinanzOnline gemeldete mit gemeldeter Kassen-ID usw.

Darf ich einen Startbeleg erstellen, die Testrechnungen auf einem Testrechner durchführen, wenn alles klappt das ganze löschen und dann einen Startbeleg im Produktivsystem mit den gleichen Daten anlegen?

**Comment by ErichFreitag** [comment]
Jein. 
Die Kasse "Testxxx" benennen (damit klar ist, dass es sich um ein Testsystem handelt).
Löschen dürfen sie nichts, sobald die Kasse in Betrieb ist. 
Die Kasse ist nach Testende ordnungsgemäß außer Betrieb zu nehmen.
Der ganze Vorfall sollte dokumentiert werden.

**Comment by ep27** [comment]
Hui, das ging ja schnell - vielen Dank!
