### ISSUE TITLE
Problem mit Gemalto Reader mit Linux

### ISSUE THREAD

**Issue by eauth** [a-sit-plus/at-registrierkassen-mustercode#467]
Ich verwende den Gemalto CT40 mit einer A-Trust Signaturkarte. Mit der C++  Source in adpuExamples werden zunächst zum Test Signaturen erzeugt. Das scheint grundsätzlich zu funktionieren, es werden 66 Bytes an Signaturdaten erzeugt. Es kommt aber gelegentlich vor dass beim Aufruf die Signatur erst nach einer langen Verzögerung geliefert wird, nämlich nach ziemlich genau 60 Sekunden. 

Die nötigen Pakete wurden wie in der gemalto Anleitung beschrieben installiert (Ubuntu 16.04). Wenn der pcscd Daemon im Debug-Modus gestartet wird (pcscd -d) dann tritt diese Verzögerung nur sehr selten auf.  
Die selbe Signaturkarte habe ich auf einem anderen PC mit Ubuntu 14.04 getestet, hier tritt diese Verzögerung nicht auf. 

Das Problem ist nur die Verzögerung, es treten bei den APDU Aufrufen keinerlei Fehler auf. Auch im Systemlog ist kein Fehler zu sehen. Hat jemand Erfahrungen/ähnliche Probleme mit diesem Reader in Linux?

**Comment by ckvsoft** [comment]
Ich habe den gleichen reader zum testen.
Verwende die alte und die neue Karte.
Habe gestern 11000 Signaturen in einem Schub gemacht ohne Aussetzer. Connect mit SCARD_SHARED_EXCLUSIVE ubuntu 16.04 Windows und Mac. Vielleicht hat die Karte einen Defekt.

**Comment by ckvsoft** [comment]
Welche Pakete? Ich hab keinerlei Pakete außer pcsc-light zusätzlich installiert.

**Comment by Alex1130** [comment]
Ich hatte einige Probleme unter Ubuntu 12.04 und viele unter 16.04 ;)
Der pcsd 1.8.16 der bei 16.04 dabei ist hat einige bugs. Diese sind ab 1.8.19 behoben vor allem:
 _Changelog:1.8.19: Ludovic Rousseau 9 December 2016 SCardGetStatusChange(): Fix a (rare) race condition_
Installieren Sie [>=1.8.20 Source](https://alioth.debian.org/frs/download.php/latestzip/39/pcsclite-latest.zip) 
danach noch einen softlink auf das Installationsverzeichnis
`cd usr/sbin
 ln -sf /usr/local/sbin/pcscd
`
einfrieren der bei Ubuntu mitgelieferten pcscd Version (zB  mit Synaptic-Paket-Version sperren) um ein überschreiben des Links durch Ubuntu updates verhindern.
Bei der Gelegenheit können Sie auch gleich die [CCID Treiber](https://alioth.debian.org/frs/download.php/latestzip/112/ccid-latest.zip) aktualisieren. 
Dadurch konnten leider nicht alle meine Probleme gelöst werden #407 (auf Applikationsebene abgefangen) siehe auch #457 . Auch bei mir kommen manchmal ungewöhnliche Wartezeiten vor! Bisher dachte ich, dass diese auch auf das (nicht-)Zusammenspiel von vmware usbccid und pcsd/ccid zurück zu führen sind.

**Comment by lebail** [comment]
Da habe ich ja anscheinend richtig Glück gehabt ;-)

Ich verwende Debian Jessie (pcscd 1.8.13), arbeite schon seit Herbst 2015 am RKSV-Projekt (ich mache das nur nebenbei, für den Eigenbedarf und ein zukünftiges Open-Source-Projekt), und hatte bis jetzt kein einziges Problem mit Smartcard und Leser (auch nicht im Stresstest mit tausenden Signaturen).

Ich habe allerdings einen anderen Cardreader (Marke "manhattan", ca. 15 €, lsusb sagt "058f:9540 Alcor Micro Corp."), und eine "alte" (ACOS) A-Trust-Smardcard.

**Comment by eauth** [comment]
Ich habe jetzt auch SCARD_SHARE_EXCLUSIVE versucht, das Problem tritt damit genauso auf.
Die Ausführung des Testprogramm dauert normalerweise 0,15sec, wenn ein "Hänger" auftritt dauert es 1:00:15 (also genau 1 Minute).
Der Debug-Modus von pcscd hilft auch nicht weiter, denn damit tritt das Problem nicht auf.

Die installierten Pakete:
_libpcsclite1
libpcsclite-dev
pcscd + libccid_

**Comment by rolandro** [comment]
Meine Kassa lauft auf einem Raspberry Pi3 mit Debian, pcscd 1.8.3, CT40 und A-Trust Karte seit 3 Monaten ohne Probleme

**Comment by Alex1130** [comment]
Interessant @eauth @ckvsoft : _Der Debug-Modus von pcscd hilft auch nicht weiter, denn damit tritt das Problem nicht auf._  Vielleicht können Sie das [Ludovic Rousseau](https://github.com/LudovicRousseau) rückmelden. Ein 60 Sekunden Timeout welches im Debug-Modus nicht auftritt hört sich nach bug an.
Ich verbinde mit  SCARD_SHARE_SHARED und habe manchmal timeouts von 3 Sekunden ist aber in /ccid-1.4.26/src/defs.h so definiert.
`/* Default communication read timeout in milliseconds */
#define DEFAULT_COM_READ_TIMEOUT (3*1000)`

**Comment by eauth** [comment]
@Alex: ich glaube ich habe das Problem gefunden. Ich habe versucht pcscd + neue libccid zu verwenden, beim Start hat der neue pcscd sofort mit einer Fehlermeldung wegen eines fehlenden libusb Symbols abgebrochen. 
Ich bin dann draufgekommen dass eine spezielle libusb verwendet wurde die ich vor längerer Zeit für ein Projekt in _/usr/local/lib_ installiert hatte, mittlerweile hatte ich das total vergessen. Nach dem Entfernen dieser libusb funktionierten beide pcscd Versionen einwandfrei. Ich bin jetzt mit dem "alten" pcscd schon bei 8000 Signaturen ohne Verzögerung.

Vielen Dank an alle für die Unterstützung!!

**Comment by ckvsoft** [comment]
Mit Standard Kubuntu 16.04 Installation auf einen I7 nicht virtuell und aktuellen Updates

```
libccid 1.4.22-1ubuntu0.1 amd64 PC/SC driver for USB CCID smart card readers
libpcsclite1:amd64 1.8.14-1ubuntu1.16.04.1 amd64 Middleware to access a smart card using PC/SC (library)

```
funktioniert es ohne Probleme.
