### ISSUE TITLE
Sicherheitseinrichtung ausgefallen

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#468]
Hallo,

kann mir bitte jemand die Information geben wo es gesetzlich geschrieben ist wie genau sind die Vorgehensweisse beim Signatur Ersetellung ausgefallen, wie schnell mueste die Signatur wieder verfuegbar sein, soweit mir bekannt ist, sollte es innerhalb 48 Stunden wieder eingerichtet sein...was passiert wenn man es nicht schafft innerhalb 48 Stunden wieder einzurichten?

Danke im voraus

**Comment by Flanelli** [comment]
Unter anderem finden Sie hier die Antworten auf die meisten Fragen...
https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/registrierkassen_startseite.html
