### ISSUE TITLE
BASICCONSTRAINTS_NUMBER_OF_ELEMENTS FAIL?

### ISSUE THREAD

**Issue by rrusshardt** [a-sit-plus/at-registrierkassen-mustercode#469]
Wir haben leider immernoch ein Problem mit der RKSV, und zwar bekommen
wir beim Prüftool den Fehler

```
      "verificationResultList" : [ {
        "verificationId" : "BASICCONSTRAINTS_NUMBER_OF_ELEMENTS",
        "version" : 1,
        "verificationName" : "Formatprüfung: 13 Elemente im
maschinenlesbaren Code vorhanden",
        "verificationTextualDescription" : "Es wird überprüft ob 13
Elemente (Trennung durch _) im maschinenlesbaren Code vorhanden sind.",
        "verificationState" : "FAIL",
        "verificationTimestamp" : "2017-03-23T10:57:31.119+01:00"
      } ]
```

leider sagt und das Prüftool aber nichts genaueres. Wir verwenden den
Aufruf bei A-Trust

/asignrkonline/v2/{Benutzername}/Sign/JWS

da kommt ja direkt die kompakte JWS-Repräsentation zurück, die geben wir
im DEP dann aus.

[cmc.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/864378/cmc.json.txt)
[DEP.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/864380/DEP.json.txt)

Weiß jemand wo hier das Problem liegt und kann uns weiterhelfen?

**Comment by andreasschiestl** [comment]
Aslo das gibt es einige Fehler:

- scheinbar ist Ihre Payload 2 mal mit Base64 kodiert
- dekodiert man nun das ganze 2 mal bekommt man:
`{"alg":"ES256"}_R1-AT1_IBELSAROOMS_1000001_2017-03-23T11:25:35_0,00_0,00_0,00_0,00_0,00_13gly2GTHvE=_7C8F2B5_ZGYzODY5Nzk=`

Das ist falsch, `{"alg":"ES256"}` darf dort nicht stehen, dafür gibt es in JWS die Header-Sektion.

**Comment by rrusshardt** [comment]
Oh ja vielen Dank, ich hatte erst umgestellt von Zertifikaterstellung über Hash auf JWS und da war die base64-Kodierung des Payload fälschlicherweise noch drin. Ich stand da zu sehr auf dem Schlauch.
