### ISSUE TITLE
Prüftool 0.6: Verschlüsselung des Umsatzzählers

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#47]
Danke für die Veröffentlichung von Version 0.6! Eine Frage zum DEP-Format-Prüftool:

Wenn ich im cryptographicMaterialContainer.json einen falschen (oder auch gar keinen) AES-Key bereitstelle, generiert das DEP-Format-Prüftool keinerlei Fehlermeldung. Die Verschlüsselung des Umsatzzählers wird also offenbar nicht überprüft, und der übergebene AES-Key wird vom Prüftool nicht benutzt (auch die Version 0.5 verhält sich analog).

Sehe ich das richtig oder unterliege ich einem Denkfehler?

**Comment by asitplus-pteufl** [comment]
wird überprüft. melde mich hier.
allgemein:
-prüftool wird mit 0.7 überarbeitet: fokus qualität, testfälle
-AES key müsste aber jetzt schon übernommen werden, da überprüft wird ob der umsatzzähler zu dem errechneten wert aus der dep folge passt.

**Comment by asitplus-pteufl** [comment]
Danke für den Hinweis! Es gab hier einen Fehler im Prüftool, können Sie bitte die aktualisierte Version (in Release 0.6 aktualisiert) überprüfen? Bei falschem Umsatzzähler kommt diese Meldung:

ÜBERPRÜFUNG: "Verschlüsselter Umsatzzähler": FEHLERHAFT
DETAILS: Previous turnover (decrypted or 0 if not present): 0
Current turnover (decrypted): 7212811548753831906
Rounded sum of taxsets: 0
Current Tax Set Normal: 0.0
Current Tax Set Ermeassigt1: 0.0
Current Tax Set Ermaessigt2: 0.0
Current Tax Set Besonders: 0.0
Current Tax Set Null: 0.0
Difference between calculated and actual turnover: -7212811548753831906

++++++++++++++++++++++++++++++

**Comment by lebail** [comment]
Vielen Dank, jetzt funktioniert es perfekt!
