### ISSUE TITLE
Test-Kassenbon mit BMF App testen

### ISSUE THREAD

**Issue by germanchiefprogrammer** [a-sit-plus/at-registrierkassen-mustercode#470]
Hallo zusammen,

gibt es die irgendwie die Möglichkeit die App des BMF mit den Testdaten zu nutzen.
Die Vorgehensweise mit der Registrierung über FinanzOnline ist mir bekannt. Aber unsere Entwicklerfirma kann sich ja nicht bei FinanzOnline registrieren und sich daher auch nicht bei der App anmelden.

Wie kann ich dann den QR-Code testen? Ich kann ihn natürlich mit freien Tools scannen aber ich sehe da natürlich nur das was ich auch drucke.

**Comment by ErichFreitag** [comment]
Ein Umweg ist, den QR-Code zu scannen und das Prüftool für Belegdaten einzusetzen.

**Comment by germanchiefprogrammer** [comment]
Stimmt, das würde gehen. Bei dem ganzen Aufwand hätte ich mir von den zugehörigen Stellen eine Variante der App für Entwickler gewünscht. Oder durch die Eingabe eines Testtokens eine Freigabe in der realen App. Es geht mir dabei auch um so Dinge wie Qualität des Drucks, Demonstration beim Kunden (Messen), usw.
