### ISSUE TITLE
Könnt Ihr Eure Trainings und Storno Belege erfolgreich prüfen?

### ISSUE THREAD

**Issue by larifari** [a-sit-plus/at-registrierkassen-mustercode#472]
Der Versuch einen Trainings oder Storno-Beleg mit dem Prüftool oder BMF-App zu verifizieren schlägt bei mir immer fehl. Ich erhalte einen einen wenig aussagekräftigen
CRYPTO_SIGNATURE: FAIL.

CRYPTO_TURNOVER_COUNTER: PASS, alle anderen Test sind PASS, die Detailprüfung des Belegtyps hat das Tool nicht gemacht. Test und Trainingsbelege werden auf genau gleichem Weg erzeugt wie die START, NULL und STANDARD Belege die sehr wohl validieren. 

An der Form des MLC sehe ich nicht auffälliges und die Formprüfung war auch erfolgreich.:
Training:
_R1-AT1_02_193_2017-03-22T20:30:10_54,55_50,00_0,00_45,45_0,00_VFJB_57FFFF5F_bHsixioIY2I=_sHDnRnknydh9SgkmX/zDzhNs5cCWLZFTprMyBGSrYXEZm2y0U4N0BG+1MfvGHc0DF2rk5bWsGj8yjctViexs/A==
Storno:
_R1-AT1_02_190_2017-03-22T17:46:52_54,55_50,00_0,00_45,45_0,00_U1RP_57FFFF5F_ZiG4WTpn52s=_MJ16RkI0xDvbIkqvpm3QXKa4HBMXzGdLupbfkkUO9FmEpMNsYtAHLAaNItX00TGpv4K5g6RONJs0WcfMRjSUHQ==

Ich habe die Signatur nicht manuell geprüft, sehe jetzt allerdings keine Grund warum die Signatur selektiv auf Trainings und Stornobelegen falsch sein sollte.

Könnte es sein, dass die Prüfung von Storno und Trainingsbelegen nicht unterstützt ist?

**Comment by ErichFreitag** [comment]
Die Prüfung von Storno- und Trainingsbelegen wird definitiv unterstützt.
Mit welchem Prüftool prüfen sie (DEP oder receipts)?

P.S. positive Beträge bei Storno sind unwahrscheinlich, haben aber mit der Prüfergebnis nichts zu tun.

**Comment by larifari** [comment]
Es war das Base64Url Encoding padding in der JWS Payload. Aber danke für den Hinweis mit den positiven Stornobeträgen, hatten die Gesamtsumme wzar abgezogen, aber den Payload String nicht angepasst.
