### ISSUE TITLE
Fehler in der Kryptographischen Gültigkeit

### ISSUE THREAD

**Issue by daiNc** [a-sit-plus/at-registrierkassen-mustercode#474]
Hallo,

ich bin mitlerweile Ratlos, hab die Checkliste schon ein Paarmal durchgegangen aber ich fühl mich Betriebsblind.
Keine ahnung warum meine Prüfung immer fehlschlägt.

Kann mir vlt jemand weiterhelfen?

Maschinenlesbarer Code:
EDIT hatte das falsche kopiert:
`_R1-AT1_0_1_2017-03-23T16:46:50_0,00_0,00_0,00_0,00_0,00_/medKciMnu9GqdlvIVRs1Q==_59EF324E_X+zrZv/Ibzg=_BUPvSSIBpRMbaGceK4z3vhxLohFRreDQ+4T8Fy7bjmcTLnwQnkOEhVmZgi7vRArZsG9bHpTi3M71b1Cffk7RYQ==`

JWS:

`eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8wXzFfMjAxNy0wMy0yM1QxNjo0Njo1MF8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfL21lZEtjaU1udTlHcWRsdklWUnMxUT09XzU5RUYzMjRFX1grenJadi9JYnpnPQ.BUPvSSIBpRMbaGceK4z3vhxLohFRreDQ-4T8Fy7bjmcTLnwQnkOEhVmZgi7vRArZsG9bHpTi3M71b1Cffk7RYQ`
CMF

`{ 
"base64AESKey": "KrtMqm4iEUuWbKuYqU6/qyq7TKpuIhFLlmyrmKlOv6s=",
 "certificateOrPublicKeyMap": 
{ "59EF324E": 
{ "id": "59EF324E",
 "signatureDeviceType": "CERTIFICATE",
 "signatureCertificateOrPublicKey": "MIIFNDCCAxygAwIBAgIEWe8yTjANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1c3QgR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDEwMjEzMDU0MFoXDTIyMDEwMjEyMDU0MFowPjELMAkGA1UEBhMCQVQxGDAWBgNVBAMMD1VJRCBBVFUzNTU4MTgwMjEVMBMGA1UEBRMMOTEzNDkxNzg4OTc2MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBbM8ryTe6r3aDEltqA58F6xBOnyC5Bo1xk9wZ8P6HzDJiwPupbLOK318u0xOFhDII4WIiCnWYHsJTk4jQE4j/aOCAZ8wggGbMH8GCCsGAQUFBwEBBHMwcTBGBggrBgEFBQcwAoY6aHR0cDovL3d3dy5hLXRydXN0LmF0L2NlcnRzL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlLUNBLmNlcjAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQEAwIGwDARBgNVHQ4ECgQITzybnqLDDJ0wRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybC5hLXRydXN0LmF0L2NybC9BLVRydXN0LVJlZ2lzdHJpZXJrYXNzZS5DQTAJBgNVHRMEAjAAMFgGA1UdIARRME8wTQYGKigAEQEYMEMwQQYIKwYBBQUHAgEWNWh0dHA6Ly93d3cuYS10cnVzdC5hdC9kb2NzL2NwL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlMBMGA1UdIwQMMAqACEBHnq7jkN+2MBYGA1UdEQQPMA2BC3plY2hAaXZmLmF0MBwGByooAAoBCwEEEQwPVUlEIEFUVTM1NTgxODAyMA0GCSqGSIb3DQEBCwUAA4ICAQAKdKHQSav9qvTqAoPocY6UJ3aAIKfRzL/dvJSQLIytF9E5hdtjuspjNfad8OOchiucZvf86AhJctwdHcnJCpDuyzwgDUSoAlAF8Z6LozH2KwkJYJBJbQJLnhrX+3KCDZplhsAkD141I75SuFBQGkow6BTBZDRx3xZjgQWYaWdYJ1SILu9gMsm0o4SkEpcfNjDQgG3kPk29bgCRts83Nkww86rSm2acu1irXBbAYDWyGXDjyXeWVLMfsrNVzmoQVrflDancPdyEAeHntz/W+iQrmd25efBF3CXRKCX+IFSZ+l0d+HzHIpvf14KRIvT66z6ll5n/T5OBxhpMYeUMJz/eY1IqOkuayoV0GQznpJZSQaHnY4BlG0cHdnfozcJE/diNEzhHWNbz5MDCyUe54dO37N8ktHdmj2DE3l44e5+LLiLrGBesAJF9VUZOe6UhEd4K4JxUkTmkCbHhCnj1jpR+QIS4fhS6DL2OgwIrbxuQak7cxRYY5lMJJn3RP15SUaVRubuEIUDX03YfgOymvhSJPbr5gEIThBYZETjD/kcdGHZJsh73uqzJvGQ8YtQxuAw0ANaRNDsf9QX2fB5sM622FRSnHHlTMjCIY8d2AKbtn+ejcPdXdRSVeC85a5FBBqCUKnQqe9H3o361nadtQeCzExXD6S0e/VlhtAJvt610uA==" } } }`

Gruss

**Comment by andreasschiestl** [comment]
Warum die Signatur nicht stimmt ist schwer zu sagen, da man mit der Signatur nur sagen kann ob diese gültig ist oder nicht. Die signierten Daten zurück zu rechnen ist nicht möglich.

Sind alle erstellten Signaturen ungültig oder nur einzelne (wenige)?
Wenn alle ungültig sind, dann passt etwas mit den Daten nicht die an die Signaturerstellungseinheit zum signieren übergeben werden. 

Sind nur einzelne (wenige) Signaturen ungültig. Gibt es mehrere Fehlerquellen. Ein Beispiel wäre, dass die Daten beim DEP Export anders sind als die beim signieren. 

Für beide Fälle ist aber mehr Information notwendig wie die Daten signiert werden und wie die ganzen Daten gespeichert werden.

**Comment by daiNc** [comment]
es sind alle ungültig, ich komme einfach nicht drauf was ich falsch übergebe... in der "rohversion" ist es laut checkliste base64 und für die jws representation muss ich das ganze dann nochmal base64url kodieren
habe ich das richtig verstanden??

**Comment by andreasschiestl** [comment]
nicht nochmal kodieren sondern umkodieren, also dekodieren und neu kodieren. Zu siegnieren ist
 `<JWS-Header>.<JWS-Payload>` beide Teile müssen Base64URL kodiert und ohne `=` Padding-Zeichen sein. In deinem Beispiel heitß das du musst `eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV8wXzFfMjAxNy0wMy0yM1QxNjo0Njo1MF8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfL21lZEtjaU1udTlHcWRsdklWUnMxUT09XzU5RUYzMjRFX1grenJadi9JYnpnPQ` siegnieren. Was genau an die SEE übergeben wird hängt davon ab welche du verwendest bzw. welche Funktion der Einheit (gibt meist mehrere Möglichkeiten)

verwendest du A-Trust Karten oder den online Dienst?

**Comment by larifari** [comment]
Schau mal was die genaue Fehlermeldung im outputverzeichnis unter 0000_cashbox_full.json ist. Vermute aber, dass die Prüfung des verschlüsselten Umsatzzähler fehlgeschlagen hat: "medKciMnu9GqdlvIVRs1Q=="  ist zu lange. Es sind nur 5 bytes aus dem verschlüsselten Umsatzzähler zu extrahieren und base64 zu codieren. Das funktionniert, weil der der AES durch Verwendung in des ICM/CRT mode in eine Stromchiffre verwandelt wird.

**Comment by daiNc** [comment]
`{
      "verificationId" : "CRYPTO",
      "version" : 1,
      "verificationName" : "Kryptographische Prüfungen",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-03-23T18:52:28.837+01:00",
      "verificationResultList" : [ {
        "verificationId" : "CRYPTO_SIGNATURE",
        "version" : 1,
        "verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
        "verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.",
        "verificationTimestamp" : "2017-03-23T18:52:28.837+01:00"
      }, {
        "verificationId" : "CRYPTO_TURNOVER_COUNTER",
        "version" : 1,
        "verificationName" : "Kryptographie: Entschlüsselung des Umsatzzählers",
        "verificationTextualDescription" : "Es wird die Entschlüsselung des Umsatzzählers überprüft. Eine Aussage über die Korrektheit kann nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-03-23T18:52:28.914+01:00"
      } `


sieht also nicht nach umsatzzähler aus.
im jws.payload stehen ja base64 kodierte sachen wie zB. turnovercounter oder signatur des vorigen belegs.
muss ich die auch umkodieren? sonst hab ichs shchon so wie du gemeint hast 
https://github.com/andreasschiestl
ich verwende karten

**Comment by daiNc** [comment]
kann ich mir sicher sein das die daten ok sind wenn die prüfung des ersten teils durch geht?? format etc.

**Comment by larifari** [comment]
Das ist die Frage die ich mir auch stelle. Bei mir gehen die START, STANDARD und NULL Belege, bei den TRAINING und STORNO sehe ich den gleichen Fehler wie Du. Geht Dein START-Beleg?

**Comment by andreasschiestl** [comment]
nein der Umsatzzähler und Verkettungswert sind nicht von Base64 auf Base64URL umzukodieren. Nur für die Teile der JWS-Repräsentation ist Base64 URL zu verwenden.

Der Umsatzzähler ist auf jeden Fall zu lange, dieser muss zwischen 8 und 5 Bytes lang sein. Warum es hier keinen Fehler anzeigt kann ich nicht sagen, ist aber definitiv nicht richtig so.

**Comment by larifari** [comment]
Im Fall des Prüftools muss der Umsatzzähler 5 bytes lang sein. Eine diesbezügliche Fehlermeldung spuckt aber aber nur beim NULL-Beleg aus, deshalb hab ich nach dem NULL Beleg gefragt. Das Muss man dann aber bei den Details auch ziemlich zwischen den Zeilen lesen.

**Comment by ErichFreitag** [comment]
Für das Prüftool ist die Länge des Umsatzzählers egal - der kann 5, 6, 8 oder 16 Bytes lang sein.

**Comment by daiNc** [comment]
Bei mir geht kein Start oder Null Beleg eigentlich einfach garnichts :(

**Comment by daiNc** [comment]
macht es einen unterschied ob man die x509certificate oder di ex509certificate2 class verwendet in c#

**Comment by daiNc** [comment]
Habe auch eine anderes Zertifikat verwendet. Aber keine Änderung

**Comment by andreasschiestl** [comment]
ohne mehr Informationen kann man nur raten. Am ehesten kann dir jemand helfen wenn du zu einem Signaturvorgang verschiedene Werte des Vorgangs hier postest, und nicht Werte wie sie sein sollten sondern wirkliche Debug-Werte.

**Comment by daiNc** [comment]
hier das log mit den files die ich dann benutze um zu prüfen

[crypto.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/867538/crypto.txt)
[test.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/867539/test.txt)
[logfile.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/867535/logfile.txt)

danke für die mühe

**Comment by andreasschiestl** [comment]
Ich würde mal bei den bekannten Fehlern anfangen: dein Umsatzzähler ist definitv zu lange, erlaubt sind nur 5-8 Byte. Auch wenn das Prüftool die Länge nicht prüft, sind erstmal bekannte Fehler zu beheben um eventuelle Nebeneffekte auszuschließen.

Bis zum Hashwert sieht es soweit in Ordnung aus. Wie genau sieht die Erstellung der Signatur aus? Eventuell kannst du den relevanten Code-Teil hier posten.

**Comment by daiNc** [comment]
nochmal danke fürs helfen
hab jetzt den turnovercounter kürzer gemacht, leider immernoch selbes ergebniss
[logfile.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/867615/logfile.txt)
[test.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/867616/test.txt)
[crypto.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/867617/crypto.txt)

Code der zum Signieren verwendet wird:
`  Private Function HashAndSign(facade As BillPaymentReceipt2017Facade, headerPayLoad As String) As Byte()
            Dim ret As Integer
            Dim rkw = New Registrierkasse.RKWrapper
            Dim tobeSignedBytes As Byte()
            Dim signature As Byte() = Nothing

            facade.HashedText = RKAesIcm.HashBytesSha256(Encoding.UTF8.GetBytes(headerPayLoad))
            tobeSignedBytes = facade.HashedText
            ret = rkw.Sign(tobeSignedBytes, signature)
            If ret = 0 Then
                facade.SignatureBase64String = System.Convert.ToBase64String(signature)
                facade.SignatureBase64UrlString = EncodingHelper.Base64url(signature)
            Else
               '...
            End If
            Return facade.HashedText
        End Function`

die Sign Methode hab ich vom DotNet Wrapper von a-trust
http://labs.a-trust.at/developer/ShowSource.aspx?id=125

**Comment by larifari** [comment]
Eine Idee hab ich noch: das Base64Url encoding. Bei dem Fehler würdest Du aber normalerweise  intermittierende PASS und FAIL Ergebnisse erhalten (aber vll. hast du außerordentliches Pech und alle deine Versuche fallen ins FAIL Schema).
Da ich nicht für Windows programmiere kann ich nichts über die Base64Url Methode sagen die Du benützt. Meistens wird base64 und base64Url Encoding mit einem oder zwei '=' gepadded wenn das Ergebnis zu kurz ist. Wenn Du die Payload für den kompakten JWS Signatur input allerdings base64Url encodest und das ergebnis ist gepadded, dann musst du die Paddings strippen bevor du den String signierst.

**Comment by andreasschiestl** [comment]
Das scheint es nicht zu sein, zumindest ist in dem logfile.txt für die Base64URL kodierten Teile kein = als Padding-Zeichen.

Ich selbst nutze weder die A-Trust Karten noch C#, aber ich hab mal kurz in das Code-Beispiel von A-Trust geschaut:
```
string toBeSignedStr = string.Format("{0}.{1}", JWS_Protected_Header, JWS_Payload);
byte[] tbsBytes = System.Text.Encoding.UTF8.GetBytes(toBeSignedStr);
byte[] signature;
 
ret = rkw.Sign(tbsBytes,out signature);
```

Dort wird nicht der Hash an den Wrapper übergeben sondern Header.Payload als UTF-8 kodiert, sieht also aus als würde der Wrapper das bilden des Hash übernehmen.

**Comment by daiNc** [comment]
vielen dank
das war exakt das problem doppeltes hashen
danke nochmals
