### ISSUE TITLE
Prüfung von TRAINING & STORNO Belegen

### ISSUE THREAD

**Issue by larifari** [a-sit-plus/at-registrierkassen-mustercode#475]
Der Versuch einen Trainings oder Storno-Beleg mit dem Prüftool oder BMF-App zu verifizieren schlägt bei mir immer fehl. Ich erhalte einen einen wenig aussagekräftigen
CRYPTO_SIGNATURE: FAIL.

CRYPTO_TURNOVER_COUNTER: PASS, alle anderen Test sind PASS, die Detailprüfung des Belegtyps hat das Tool nicht gemacht. Test und Trainingsbelege werden auf genau gleichem Weg erzeugt wie die START, NULL und STANDARD Belege die sehr wohl validieren.

An der Form des MLC sehe ich nicht auffälliges und die Formprüfung war auch erfolgreich.:
Training:
_R1-AT1_02_193_2017-03-22T20:30:10_54,55_50,00_0,00_45,45_0,00_VFJB_57FFFF5F_bHsixioIY2I=_sHDnRnknydh9SgkmX/zDzhNs5cCWLZFTprMyBGSrYXEZm2y0U4N0BG+1MfvGHc0DF2rk5bWsGj8yjctViexs/A==
Storno:
_R1-AT1_02_190_2017-03-22T17:46:52_54,55_50,00_0,00_45,45_0,00_U1RP_57FFFF5F_ZiG4WTpn52s=_MJ16RkI0xDvbIkqvpm3QXKa4HBMXzGdLupbfkkUO9FmEpMNsYtAHLAaNItX00TGpv4K5g6RONJs0WcfMRjSUHQ==

Ich habe die Signatur nicht manuell geprüft, sehe jetzt allerdings keinen Grund warum die Signatur selektiv auf Trainings- und Stornobelegen falsch sein sollte.

Könnte es sein, dass die Prüfung von Storno und Trainingsbelegen nicht unterstützt ist?

**Comment by ztp-mino** [comment]
Das Prüftool kann definitiv Trainings- und Storno-Belege. Eventuell wird die Signatur mit normalen verschlüsselten Umsatzzähler erstellt?

**Comment by larifari** [comment]
Gilt das mit dem Prüfen von Trainings- und Storno belegen nur für das ztp eigene Prüftool, oder auch das semi-offizielle von der a-sit? Hab das ztp tool auf dem mac nicht zumlaufen gebracht, muss mir eine vm aufsetzen.

Der String der zur Signatur übergeben wird enthält defintiv das 'U1RP' bzw. 'VFJB' anstelle des Umsatzzählers.

**Comment by lebail** [comment]
Das offizielle Tool von A-SIT kann Storno- und Trainingsbelege prüfen. Bei mir funktioniert das bestens.

**Comment by theshadowtwentyseven** [comment]
Yep, Storno und Training funktionieren bei mir ebenfalls im A-SIT Prüftool korrekt.

**Comment by ztp-mino** [comment]
Ja, hab auch das von der A-SIT gemeint, geht natürlich in beiden.

**Comment by larifari** [comment]
Danke! geht jetzt bei mir auch. Der Base64Url padding entferner war bei einem merge entschwunden.
