### ISSUE TITLE
Zusätzlicher Text bei QR-Code

### ISSUE THREAD

**Issue by germanchiefprogrammer** [a-sit-plus/at-registrierkassen-mustercode#477]
Hallo!

Neben dem QR-Code auf dem Kassenbon ist noch Platz.
Druckt ihr da irgendwas hin? Also sowas wir "Registrierkassenverordnung" o.ä.
Die sonstigen Pflichtangaben wie Rechnungsnr, Beträge usw. stehen ja darüber.
Wie handhabt ihr das?

Viele Grüße

**Comment by Flanelli** [comment]
Der Platz bietet sich wunderbar an für die üblichen Floskeln wie

Wir danken für den Einkauf.
Umtausch nur mit Beleg.
Bei Aktionsware kein Umtausch

und schon ist der Bon vertikal nicht mehr durch den QR nur <halbbdruckt"
