### ISSUE TITLE
Differenzbesteuerung

### ISSUE THREAD

**Issue by ep27** [a-sit-plus/at-registrierkassen-mustercode#478]
In welches Feld kommen differenzbesteuerte Umsätze? Ich würde ja sagen ins Feld Betrag-Satz-Null, könnte mir aber theoretisch auch Betag-Satz-Besonders vorstellen, für das ich keine anderweitige Verwendung sehen würde, wenn Betrag-Satz-Null Kleinunternehmerrechnungen oder innergemeinschaftliche Leistungen vorbehalten sein solte.

**Comment by lebail** [comment]
Laut Erlass, Punkt 4.6.6, kommen differenzbesteuerte Umsätze tatsächlich ins Feld "Betrag-Satz-Null". 

Das Feld "Betrag-Satz-Besonders" ist für 19%-Umsätze reserviert (siehe Erlass, Punkt 3.3.4). Diese gelten in den Zollausschlussgebieten Jungholz (Tirol) und Mittelberg (Vorarlberg).

**Comment by ep27** [comment]
Vielen Dank!

**Comment by theshadowtwentyseven** [comment]
Mhm, entschuldigt die Frage, aber was sind differenzbesteuerte Umsätze?

**Comment by ep27** [comment]
siehe https://www.jusline.at/24_Differenzbesteuerung_UStG.html

Oder kurz und vielleicht nicht ganz 100% korrekt: Unternehmer kauft bei einem Privaten ein Ding und verkauft es dann weiter - dann zahlt er nur die MWSt. für die Differenz zw. VK u. EK.
