### ISSUE TITLE
Barentnahme

### ISSUE THREAD

**Issue by wpichler** [a-sit-plus/at-registrierkassen-mustercode#479]
Hallo alle miteinander,

mir ist nicht ganz klar wie mit Barentnahmen umgegangen werden soll / muß.

Müssen oder dürfen Barentnahmen im DEP aufgeführt werden / signiert werden ?

**Comment by ErichFreitag** [comment]
Dürfen -> signieren im 0 %-Steuersatz.

**Comment by wpichler** [comment]
Besten Dank
