### ISSUE TITLE
Tippfehler Detailfragen v1.1 Seite 50

### ISSUE THREAD

**Issue by csokay** [a-sit-plus/at-registrierkassen-mustercode#48]
eine kleiner Tippfehler (autocorrect läßt grüßen?)
Seite 50, Punkt 4.4 -> Konstruktion des Links ->Als Parameter

> Auch hier gilt, dass die Länder der URL möglichst klein gehalten werden sollte. Der
Name des Parameters spielt keine Rolle (hier wurde „value“ verwendet).

statt "Länder" gehört wohl "Länge"?

![screen shot 2016-03-16 at 17 17 25](https://cloud.githubusercontent.com/assets/1814899/13819768/fd4065b2-eb9a-11e5-83a1-65b9f54427c9.png)

**Comment by csokay** [comment]
zwei Seiten weiter (52) wird auf  §91 Abs. 2 Z1 RKSV verwiesen. Wohl eher §9?

![screen shot 2016-03-16 at 17 21 17](https://cloud.githubusercontent.com/assets/1814899/13819920/87fe63ca-eb9b-11e5-87b2-1b0da8c7defa.png)

**Comment by asitplus-pteufl** [comment]
Vielen Dank für die Hinweise! Werden in der nächsten Version korrigiert.

§ 11 Abs. 2 Z 1 RKSV ist korrekt.

**Comment by asitplus-pteufl** [comment]
Wurde in V1.2 behoben. Diese Version wird in Kürze freigegeben.
