### ISSUE TITLE
Umsatzzähler

### ISSUE THREAD

**Issue by msickl** [a-sit-plus/at-registrierkassen-mustercode#487]
Ist der für den Umsatzzähler nur der Steuerbetrag des jeweiligen bons zu addieren ?
Bin ein bisschen verwirrt. über den beispiel code

/**
     * update turnover counter
     *
     * @param SimplifiedReceipt
     */
    protected void updateTurnOverCounter(SimplifiedReceipt SimplifiedReceipt) {
        //if we have a receipt for training purposes, we don't change the turnover counter
        double sumTaxTypeNormal = Precision.round(SimplifiedReceipt.getTaxSetNormal(), 2);
        double sumTaxTypeErmaessigt1 = Precision.round(SimplifiedReceipt.getTaxSetErmaessigt1(), 2);
        double sumTaxTypeErmaessigt2 = Precision.round(SimplifiedReceipt.getTaxSetErmaessigt2(), 2);
        double sumTaxTypeNull = Precision.round(SimplifiedReceipt.getTaxSetNull(), 2);
        double sumTaxTypeBesonders = Precision.round(SimplifiedReceipt.getTaxSetBesonders(), 2);

        //add all taxset sums
        long tempSum = 0;
        tempSum += Precision.round(sumTaxTypeNormal*100,0);
        tempSum += Precision.round(sumTaxTypeErmaessigt1*100,0);
        tempSum += Precision.round(sumTaxTypeErmaessigt2*100,0);
        tempSum += Precision.round(sumTaxTypeNull*100,0);
        tempSum += Precision.round(sumTaxTypeBesonders*100,0);

        //convert sum to â‚¬-cent and add to turnover counter
        turnoverCounter += (tempSum);
    }

**Comment by lebail** [comment]
Es wird die Summe der Brutto-Zahlbeträge des Bons gebildet und diese dann zum Umsatzzähler addiert.

**Comment by msickl** [comment]
Danke für die rasche Antwort.
Ganz zufrieden bin ich jedoch nicht, wenn ich mir die "act Aufbereitung zur Signaturerstellung" von Erich Freitag ansehe dann fällt mir auf das hier nur die Steuersätze addiert werden und in den Summenspeicher abgelegt werden. 

![img_1229](https://cloud.githubusercontent.com/assets/15203116/24322956/df6c7dd8-116d-11e7-975d-bdcbfa87957a.JPG)

**Comment by lebail** [comment]
Ich weiß nicht, woraus Sie das schließen.

Mit "Betrag-Satz-Normal", "Betrag-Satz-Ermaessigt1" bzw. sumTaxTypeNormal, sumTaxTypeErmaessigt1 etc. sind die dem jeweiligen Steuersatz unterliegenden _Brutto-Beträge_ gemeint, nicht die Steuersätze selbst und auch nicht die USt.-Beträge.

Das steht übrigens so in §9 (1) der RKSV ("Betrag der Barzahlung getrennt nach Steuersätzen"), und im Erlass (Punkt 3.3.4) ist nochmals ausdrücklich angegeben, dass es sich um die Brutto-Beträge handelt.

**Comment by msickl** [comment]
danke ich kenn mich nun aus



Von meinem Samsung Gerät gesendet.


-------- Ursprüngliche Nachricht --------
Von: lebail <notifications@github.com>
Datum: 25.03.17 15:40 (GMT+01:00)
An: a-sit-plus/at-registrierkassen-mustercode <at-registrierkassen-mustercode@noreply.github.com>
Cc: Martin Sickl <office@sickl.at>, Author <author@noreply.github.com>
Betreff: Re: [a-sit-plus/at-registrierkassen-mustercode] Umsatzzähler (#487)


Ich weiß nicht, woraus Sie das schließen.

Mit "Betrag-Satz-Normal", "Betrag-Satz-Ermaessigt1" bzw. sumTaxTypeNormal, sumTaxTypeErmaessigt1 etc. sind die dem jeweiligen Steuersatz unterliegenden Brutto-Beträge gemeint, nicht die Steuersätze selbst und auch nicht die USt.-Beträge.

Das steht übrigens so in §9 (1) der RKSV ("Betrag der Barzahlung getrennt nach Steuersätzen"), und im Erlass (Punkt 3.3.4) ist nochmals ausdrücklich angegeben, dass es sich um die Brutto-Beträge handelt.
