### ISSUE TITLE
Belegdatum und -uhrzeit oder kasseninterne verwenden?

### ISSUE THREAD

**Issue by ep27** [a-sit-plus/at-registrierkassen-mustercode#488]
In #399 wird erwähnt, dass es OK ist, wenn man Sprünge in der Uhrzeit hat - etwa wenn ein PC keine genaue Uhrzeit hat.

Jetzt stellt sich mir die Frage, was ich bei großen Abweichungen - wenn ich einen externen Beleg habe, auf dem Datum und Uhrzeit stehen, wäre es dann sinnvoll, das Datum und Uhrzeit von der tatsächlichen Zahlung zu nehmen oder sage ich, dass der Signaturbeleg ja ein eigenes Dokument ist und mit der eigentlichen Zahlungszeit nichts zu tun hat, und nehme den Belegerstellungszeitpunkt.

Ich denke dabei zB. an einen Außendienstler, der beim Kunden was kassiert hat, und erst am nächsten Tag wieder in der Firma ist und den Betrag in die Registrierkasse eingeben kann. Womit ich sogar zwei verschiedene Tage habe und ich würde für beide Datumsoptionen Gründe finden.

**Comment by ErichFreitag** [comment]
Das wird von der Implementierung abhängen, wieviele Datums- und Uhrzeitangaben sie haben (Erstellung, Änderung, Abschluss, ...).

Die RKSV verlangt Datum und Uhrzeit der Belegausstellung.
Bei einer Nacherfassung gilt das ebenso, nämlich Datum und Uhrzeit der Erfassung.

**Comment by ep27** [comment]
Vielen Dank. Ich habe eh nur zwei Zeiten: Zahlung und Belegerstellung - aber die können eben unterschiedlich sein. Wenn Datum/Uhrzeit der Zahlung sich eben von der Belegerstellungszeit unterscheidet.
