### ISSUE TITLE
Beträge in Cent

### ISSUE THREAD

**Issue by ep27** [a-sit-plus/at-registrierkassen-mustercode#489]
Ich gehe davon aus, dass man Beträge nicht in Cent angeben darf, weil überall steht, dass man alle Beträge mit 0,00 zu formatieren hat. Nachdem aber der Umsatzzähler in Cent gerechnet wird, wäre es doch sinnvoll, bei der Centdarstellung zu bleiben, wo man doch den String möglichst kurz halten will und

19,40_0,00_0,00_0,00_0,00
vs.
1940_0_0_0_0

ist schon ein großer Unterschied - im Beispiel nicht mal halb so lang. Das wäre meiner Meinung nach ein tolles Update der Spezifikation, wenn man das auch in Cent zuließe...

**Comment by andreasschiestl** [comment]
es wäre auch schon wesentlich kürzer wenn man Dezimaltrennzeichen und Kommastellen weglässt wenn diese Null sind.

Aber das ganze hat unzählige Stellen wo man nur den Kopf schütteln kann, darf man nicht zuviel drüber nachdenken und einfach umsetzen ;)

Denke mal grundlegende Änderungen wird es so schnell nicht mehr geben (wenn überhaupt) da sonst vermutlich die Unternehmer Amok laufen werden ;)

**Comment by ep27** [comment]
Naja man könnte ja beide Varianten zulassen - ist ja auf einen Blick ersichtlich, ob Beträge in Cent oder in Euro angegeben wurden.

**Comment by andreasschiestl** [comment]
Möglich schon, nur wird es nicht passieren. Da wäre mir lieber es kommt mal eine neue Version des Prüftools (die alle erlaubten Dinge als gültig erkennt) und Detailspezifikation (ohne Tippfehler).

Und selbst wenn es kommen sollte, wer wird es implementieren? Der Kunde wird kaum dafür zahlen da er praktisch keinen Nutzen davon hat.

**Comment by ep27** [comment]
Ich würde es schon implementieren, weil das Update ja minimal wäre
