### ISSUE TITLE
Error while parsing the input files.

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#49]
Leider kann ich die genaue Fehlerursache nicht eruieren:

Error while parsing the input files.

Können Sie mir helfen?
[aes-key.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/181760/aes-key.txt)
[test-dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/181761/test-dep-export.txt)

Vielen Dank im Voraus

**Comment by asitplus-pteufl** [comment]
Bitte die Informationen in der Readme Datei und dem Hersteller Dokument 1.1 durchlesen. Das Format für den AES Key und die Sig-Einrichtungen hat sich geändert (Stichwort: cryptraphicmaterialcontainer.json")
Gründe für die Änderung:
-Abbildung von geschlossenen/offenen Systemen beim Prüftool und im Demo-Code
-Sig-Zertifikate im DEP-Export nicht mehr verpflichtend (daher die Notwendigkeit diese extern zu speichern)
-Daraus wurde dann die cryptographicmaterial.json Datei, die AES-Schlüssel und Infos zu den Sig-Einrichtungen erhält. Am besten neben der Doku einfach die Beispiele die in der Release enthalten sind anschauen.

**Comment by anzun** [comment]
Vielen Dank für die schnelle Info
