### ISSUE TITLE
Vorgehensweise: Nullbeleg kann nicht verifiziert werden (SE ausgefallen) - Prüftool fail

### ISSUE THREAD

**Issue by MichaelLod** [a-sit-plus/at-registrierkassen-mustercode#492]
Hallo liebes Team,

ich habe jetzt genau diesen Fall bei einem Kunden, bei dem kurze Zeit die SE ausgefallen ist und zugleich ein Nullbeleg erstellt wurde.

Ich weiß, dass dieser Case im Prüftool noch nicht berücksichtigt worden ist, dennoch stellt sich für mich jetzt grundlegend die Frage, ob bei diesem Kunden jetzt etwas zu tun ist oder nicht.

Ich kann ja jetzt auch keine weiteren Belege von diesem Kunden prüfen, weil das Tool ja immer wieder diesen Fehler ausgibt. Soll ich diesen Case jetzt grundsätzlich abfangen und bei diesem Kunden die Reg. Kasse neu in Betrieb nehmen oder wie wird hier vorgegangen?

Danke,
Viele Grüße,

**Comment by Phoniexk** [comment]
Nein die Registrierkasse einfach normal weiterlaufen, insofern es sich nicht um Sonder-Nullbeleg handelt (Starbeleg, Jahresbeleg oder Sammelbeleg) . Wie schon selbst erwähnt, das Prüftool erkennt derzeit Nullbelege mit Ausfall noch fehlerhaft. Diese Umstand sollte mit der nächsten Version behoben sein. Für die Kasse selbst ist dies aber ein zulässiger Vorgang, weshalb ein neue Inbetriebnahme absolut unnötig ist.

Das vollständige DEP lässt sich halt mit der derzeitigen Version nicht prüfen, sie können einfach nur auf die nächste Version warten und erst ab dann wieder prüfen.

Die Kasse ist auf jeden Fall ganz normal weiterzuführen. Sie brauchen diesen Fall nicht programmtechnisch abfange, wie gesagt mit der nächsten Version gehts dann. (Obwohl ich es schon sehr kurios finde, dass dieser Umstand seit Ende Jahres bekannt ist und man nicht in der Lage ist, dies innerhalb von drei Monaten im Prüftool zu beseitigen).

**Comment by MichaelLod** [comment]
Super, dann hat sich das geklärt. Danke Phoniexk für die schnelle und kompetente Antwort!

**Comment by lebail** [comment]
@Phoniexk 

> (Obwohl ich es schon sehr kurios finde, dass dieser Umstand seit Ende Jahres bekannt ist und man nicht in der Lage ist, dies innerhalb von drei Monaten im Prüftool zu beseitigen).

Ja, früher ging sowas noch schneller.

Als ich anlässlich des Releases von Version 0.6 anscheinend der einzige war, dem auffiel, dass die Verschlüsselung des Umsatzzählers weder in dieser damals neuen Version, noch in der Vorversion 0.5 geprüft wurde (und somit der im CryptographicMaterialContainer angegebene AES-Key vom Programm überhaupt nicht benutzt wurde, siehe https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/47), wurde umgehend (noch am selben Tag) eine korrigierte Version des Tools nachgeliefert.
