### ISSUE TITLE
Barankäufe bzw. negative Barbelege

### ISSUE THREAD

**Issue by steefanfuchs** [a-sit-plus/at-registrierkassen-mustercode#493]
Liebe Kollegen,

Ich hätte gerne gewusst wie ihr Barankäufe bzw. negative Barbelege verarbeitet. Müssen diese signiert werden bzw. beeinflussen diese den Umsatzzähler oder reicht es, wenn sie im Kassajournal aufscheinen? 
Wenn sie signiert werden, könnte auf der Fall eintreten, dass der Umsatzzähler negativ ist. Z.b. wenn der erste Beleg nach dem Startbeleg ein Negativer ist. Ist das überhaupt zulässig?

Danke für eure Antworten.

**Comment by ErichFreitag** [comment]
Bareinnahmen und Barausgaben dürfen, müssen aber nicht signiert werden.
Wenn sie signiert werden dann im 0%-Steuersatz.
Entsprechend beeinflussen sie auch den Umsatzzähler.
Im Kassenjournal müssen sie enthalten sein.
Ein negativer Umsatzzähler ist entsprechend zulässig.

**Comment by steefanfuchs** [comment]
Vielen Dank für die schnelle Antwort !
