### ISSUE TITLE
Signatur und Rechnungsduplikat / Kopie

### ISSUE THREAD

**Issue by aortner** [a-sit-plus/at-registrierkassen-mustercode#495]
Wie gehe ich bei einer nachträglichen Kopie einer Rechnung vor?

Kann ich den QR duplizieren (nochmal ausdrucken)
Brauche ich einen QR Code auf der Kopie?
Muss ich neu signieren?

**Comment by ErichFreitag** [comment]
Ich nehme an, sie meinen einen Barumsatz-Beleg.

Dann dürfen sie eine Kopie nicht signieren.
Entsprechend darf sich auch der Umsatzzähler nicht ändern.
Der Beleg muss als Duplikat gekennzeichnet sein.
Ansonsten ist es eine 1:1-Kopie des Originalbelegs.

**Comment by aortner** [comment]
Das heißt auf der Kopie steht Duplikat !
Ist klar! Muss ich den qr Code dann drauf haben? 
Bzw darf ich überhaupt einen Code darauf haben?

**Comment by ErichFreitag** [comment]
"Ein Duplikat ist als solches zu kennzeichnen". Wenn "Belegkopie" drauf steht wird es auch OK sein.

Ob ein QR-Code enthalten sein muss oder nicht ist meiner Ansicht nach nicht exakt spezifiziert. Nachdem aber a) der Beleg eine 1:1-Kopie ist (obgleich auch das nicht exakt spezifiziert ist) und b) ich ja meist dann eine Kopie brauche, wenn ich den originalen Beleg nicht mehr habe, bin ich für einen QR-Code auch am Duplikat.
