### ISSUE TITLE
Die kryptographische Gültigkeit der Signatur ist nicht gegeben

### ISSUE THREAD

**Issue by brainformance-cledeg** [a-sit-plus/at-registrierkassen-mustercode#496]
Sehr geehrter Damen und Herren,

wir haben noch Probleme beim DEP-Export und bereits alle ähnlichen Issues durchgesehen. Wir verwenden RK.Online von A-Trust, welche das Hashing mit SHA256 serverseitig durchführt.

Wir haben bereits folgende Punkte überprüft/berücksichtigt:

- Hashingfunktion wird wie gesagt Serverseitig aufgerufen
- Sämtliche "heiklen" Funktionen aus dem Beispielcode kopiert und nicht selbst geschrieben
- Länge der Signatur = 64 Bytes
- Keine problematischen Zeichen in der Base64-Codierung
- Jeden Einzelschritt von https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/Dokumente/2016-12-12%20SIG-Check.pdf durchgesehen

Ich weiß nicht was wir übersehen habe, aber ich komme nicht mehr weiter.

Folgendes File enthält input und output des Prüftools.

[debug.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/873234/debug.zip)

Eventuell haben Sie einen Tipp für uns.

Vielen Dank und Liebe Grüße

**Comment by ErichFreitag** [comment]
Die Decodierung des Zertifikatseintrags im cryptographicMaterialContainer.json ist nicht möglich.

Geben sie die Zertifikatsdaten einmal unter https://certlogik.com/decoder/ ein. Bzw. wo haben sie die Daten her?

**Comment by brainformance-cledeg** [comment]
Vielen Dank für die schnelle Antwort und den Hinweis!

Ich habe das Zertifikat von A-Trust erhalten. Habe auch extra schon ein produktives genommen, damit es nicht zu Problemen kommt. Ich bin wie folgt vorgegangen:

1. Ich habe einen Download mit dem Zertifikat von A-Trust erhalten.
2. Das Zertifikat unter Windows geöffnet und sowohl das Zertifkat selbst, als auch das CA-Zertifikat basee64 exportiert. 
3. Alle Zeilenumbrüche und kommentare (---Begin ---End) entfernt und dann verwendet

Wie Sie aber richtig bemerkt haben, kann ich das Zertifikat auf certlogic.com nicht decodieren, somit habe ich anscheinend etwas missverstanden oder einen Fehler gemacht.

**Comment by ErichFreitag** [comment]
Machen sie z.B. folgendes:

A-Trust Verzeichnisdienst aufrufen
Zertifikats-Seriennummer eingeben
Zertifikat downloaden (.DER-Format)
openssl x509 -inform der -in <input.cer> -out <output.pem> aufrufen (muss wohl zuvor installiert werden)

Dann erhalten sie das Zertifikat im .PEM-Format und das können sie mit https://certlogik.com/decoder/ prüfen bzw. im crypto-File direkt (nach entfernen von Zeilenumbrüchen etc.) eintragen.

**Comment by brainformance-cledeg** [comment]
Vielen Dank!!! 
Hat funktioniert => Der vorliegende Beleg wurde gesetzeskonform von einer erfolgreich in Betrieb genommenen Registrierkasse erstellt. Bundesministerium für Finanzen.
