### ISSUE TITLE
Startbeleg wird abgewiesen

### ISSUE THREAD

**Issue by YanivYon** [a-sit-plus/at-registrierkassen-mustercode#498]
Hallo an alle
bitte um eure Unterstützung
mein Startbeleg wird beim BMF-App abgewiesen

_R1-AT1_HaMa21101_1_2017-03-27T17:00:24_0,00_0,00_0,00_0,00_0,00_j3qs9vh1v4RrQrYhaZ3vfg==_65c83d4d_SGFNYTIxMTAx_ar2oBW/hQ65LvcjTxm+HawLu0MWVb8zlR8W2TMlyTfbaCbpQ0hnp+dEuXWJWzmHOvAKAePWSQ6Xah4WBKplYvw==

könnte das bitte jemand durch das Prüftool jagen
oder weiß jemand was das sein kann?

**Bezeichnung:Prüfergebnis - Kasse**
Beschreibung:Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.
Meldung:Der vorliegende Beleg weist Fehler im maschinenlesbaren Code auf. Die Fehlerursachen sind nachfolgend angeführt:

**Bezeichnung:Detailprüfung des maschinenlesbaren Codes**
Beschreibung:Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.

**Bezeichnung:Detailformatprüfung des maschinenlesbaren Codes**
Beschreibung:Dieses Modul und die dazugehörigen Submodule überprüfen die Korrektheit des Formats der Elemente des maschinenlesbaren Codes.

**Bezeichnung:Formatprüfung: Verkettungswert**
Beschreibung:In diesem Modul und den dazugehörigen Submodulen werden unterschiedliche Prüfungen im Zusammenhang mit der BASE64-Kodierung (gültige Zeichen, Länge) des Verkettungswerts durchgeführt.

AES
+XqOAIJYYOsJzVRajuRqE7Bon6LAZKZTctkzAadvmsU=
KassenID HaMa21101
Zertifikat 65C83D4D

**Comment by YanivYon** [comment]
inzwischen hab ich es selbst durch das prüftool geschickt
mit diesem ergebnis

        "verificationName" : "Formatprüfung: Verkettungswert",
        "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden unterschiedliche Prüfungen im Zusammenhang mit der BASE64-Kodierung (gültige Zeichen, Länge) des Verkettungswerts durchgeführt.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Die Länge des Verkettungswertes ist ungleich 64 Bit.",
        "verificationTimestamp" : "2017-03-27T21:01:34.725+02:00"

Ideen?

**Comment by lebail** [comment]
Sie verwenden als Verkettungswert die Kassen-ID selbst - anstatt deren SHA256-Hash zu berechnen und davon die ersten 8 Byes zu nehmen.

**Comment by YanivYon** [comment]
tatsächlich
danke vielmals
jetzt sagt das prüftool schon mal PASS
aber FinanzOnline ist wieder unzufrieden

Fehler bei
Bezeichnung:
Statusprüfung der Kasse
Beschreibung:
Es wird der Status der Kasse zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.
