### ISSUE TITLE
Prüftool: Seriennummer Hex Format

### ISSUE THREAD

**Issue by TMF42** [a-sit-plus/at-registrierkassen-mustercode#499]
Ich komme einfach nicht auf den Fehler. 

Wenn ich einen Beleg mit dem Prüftool (siehe Anhang prüfe) bekomme ich ständig den Fehler dass er die Seriennummer gegen ein geschlossenes System prüft anstatt gegen ein offenes. Und natürlich schlägt es fehl.

Vielleicht bin ich einfach schon betriebsblind aber ich habe die Seriennummer im CMC.json File mit der Seriennummer im Dep_export.json gegen geprüft und die sind gleich aber dennoch erkennt das Prüftool nicht dass es sich hierbei um ein offenes System handelt und das HEX Format geprüft werden muss. 

Weiß jemand woran es liegen kann? 

[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/873515/0000_cashbox_full.json.txt)
[CMC.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/873517/CMC.json.txt)
[dep-export.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/873516/dep-export.json.txt)

**Comment by lebail** [comment]
Im Beleg im DEP-Export steht "_R1-AT0" - und das steht eben für ein geschlossenes System. Bei einem offenen System müsste da je nach Anbieter AT1, AT2 oder AT3 stehen.

**Comment by TMF42** [comment]
ah danke! Hab's ja fast gewusst dass ich blind bin :)
