### ISSUE TITLE
Frage: gibt es einen Trainings-Beleg, der gleichzeitig ein Stornobeleg ist?

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#50]
laut Mustercode ist dies so gelöst:

https://github.com/a-sit-plus/at-registrierkassen-mustercode/blob/master/regkassen-core/src/main/java/at/asitplus/regkassen/core/DemoCashBox.java

else if (typeOfReceipt == TypeOfReceipt.STORNO_BELEG) {

else if (typeOfReceipt == TypeOfReceipt.TRAINING_BELEG) {

theoretisch könnte man aber einen Stornobeleg zusätzlich als Trainingsbeleg markieren, und somit wäre es dann in erster Linie ein Trainingsbeleg (also müsste man zumindest die Reihenfolge der else if Klauseln umdrehen) oder sehe ich das falsch?

**Comment by asitplus-pteufl** [comment]
Im Sinne der RKSV kann es Storno/Trainingsbeleg nicht gleichzeitig geben, da entweder STO oder TRA statt dem Umsatzzähler genannt wird. Allerdings: Ein mit TRA markierter Beleg kann ja sowohl STO als auch normaler Beleg sein: 
Storno/Normale Belege unterscheiden sich nicht anhand der Beträge in den Steuersätzen, weil ja auch negative Positionen storniert werden können (natürlich werden die meisten Stornobelege negative Positionen haben), daher wurde explizit die Kennzeichnung STO eingeführt.
Sie können also im Trainingsbeleg damit eh alles simulieren, nur die Kennzeichnung ist nicht möglich.
Hilft das weiter?

**Comment by anzun** [comment]
ja, danke
