### ISSUE TITLE
kryptographischen Gültigkeit der Signatur

### ISSUE THREAD

**Issue by TMF42** [a-sit-plus/at-registrierkassen-mustercode#500]
Hallo,

Ich würde Hilfe brauchen um festzustellen warum ich nach wie vor ein FAIL vom Prüftool bekomme bezüglich der kryptografischen Gültigkeit.

Um es einfach zu machen prüfe ich nur einen Startbeleg

Ich habe die SIG-Checkliste mehrmals durchgesehen und alles scheint zu passen. Andere Issues zu dem Thema scheinen nicht weiter zu helfen bzw. wurde alles kontrolliert worauf die hinweisen

  - CMC.json -> ist in Ordnung 
  - Zertifikat über -> certlogik.com/decoder/ geprüft
  - header.payload scheint zu passen
  - HASH sind 32 Byte
  - Signatur liefert 64 Byte zurück
  - dies wird Base64URL codiert und in die header.payload.signature Struktur übergeführt
  - Dennoch bekomme ich den Fehler dass die Signatur kryptografisch nicht ok ist

Im Anhang mein Test-Beispiel

JWS-header-payload:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9DQVNIQk9YLURFTU8tMV9DQVNIQk9YLURFTU8tMS1SZWNlaXB0LUlELTFfMjAxNi0wMy0xMlQwNDo1ODowOV8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfRkpXbXAxTWlyd1U9XzNDQUJFODlBX2NnOGhOVTVpaHRvPQ

HASH:
B5EF0CB1B355C91F242139E1299BA414CC128740376B656C5720393403FAAB97

Signatur-Ergebnis:
Z8BCVM3OiIAKC5nqxNjQSDwnSdvjYTAp4S3z5skItDYmV1b6P/FDosgedvelKZuHQwfubYFMjiCs5SJ4EBTsag==

JWS-header-payload-signatur:
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9DQVNIQk9YLURFTU8tMV9DQVNIQk9YLURFTU8tMS1SZWNlaXB0LUlELTFfMjAxNi0wMy0xMlQwNDo1ODowOV8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfRkpXbXAxTWlyd1U9XzNDQUJFODlBX2NnOGhOVTVpaHRvPQ.Z8BCVM3OiIAKC5nqxNjQSDwnSdvjYTAp4S3z5skItDYmV1b6P_FDosgedvelKZuHQwfubYFMjiCs5SJ4EBTsag

Könnte mir jemand einen Tip geben an was das liegen könnte? 

[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/875064/0000_cashbox_full.json.txt)
[CMC.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/875065/CMC.json.txt)
[dep-export.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/875066/dep-export.json.txt)

**Comment by ErichFreitag** [comment]
Wenn ich die Daten in _R1-AT1_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-1_2016-03-12T04:58:09_0,00_0,00_0,00_0,00_0,00_FJWmp1MirwU=_3CABE89A_cg8hNU5ihto=_Z8BCVM3OiIAKC5nqxNjQSDwnSdvjYTAp4S3z5skItDYmV1b6P/FDosgedvelKZuHQwfubYFMjiCs5SJ4EBTsag== umwandle und damit prüfe ist die Signatur bei mir OK.

**Comment by ErichFreitag** [comment]
Ich habe manuell die Payload extrahiert, decodiert und ihr Signaturergebnis angehängt und das als maschinenlesbaren Code geprüft.

**Comment by TMF42** [comment]
ok - jetzt bin ich verwirrt. Ich habe jetzt genau das gleiche gemacht und den Beleg alleine geprüft und bekomme nach wie vor den gleichen Fehler mit der kryptografischen Gültigkeit.

Kann es sein dass das Prüftool bei mir falsche negative liefert?

**Comment by ErichFreitag** [comment]
Glaub ich nicht, dass es am Prüftool liegt. Haben sie die zweite Variante verification-receipts auch probiert oder nur die dep-export-Variante? Ich prüfe den maschinenlesbaren Code mit einem eigenen Tool.

**Comment by TMF42** [comment]
ich habe beide versucht. 

Jetzt hab ich aber aus Paranoia auf einem anderen Rechner es ausgeführt und dort kam das richtige dabei raus.

Nach weiterem Troubleshooting bin ich dann auf die Ursache gestoßen - der Rechner mit dem falschen negativen hatte bouncycastle Libraries installiert die für's kompilieren des A-Trust Demo Codes notwendig waren. Diese vertrugen sich aber nicht mit dem Prüftool. 

Nachdem ich die entfernt hab und das Prüftool erneut durchgeführt habe - funktioniert es natürlich.

Trotzdem vielen Dank!! - die Bestätigung dass die Signatur OK ist hat mir bereits sehr viel geholfen.
