### ISSUE TITLE
Startbeleg kann keinem Belegtyp zugewiesen werden

### ISSUE THREAD

**Issue by brainformance-cledeg** [a-sit-plus/at-registrierkassen-mustercode#502]
Sehr geehrte Damen und Herren,

meine Standardbelege werden vom DEP-Prüftool erfolgreich validiert, allerdings kommt bei meinem Startbeleg immer bei allen 4 Belegarten FAIL und es wird somit nicht als Startbeleg erkannt. Die 8-Byte-Hash extraktion habe ich bereits mit dem Wert aus einem anderen Ticket verglichen und dieser stimmt auch. 

Anbei finden Sie ein DEP mit dem fehlerhaften Startbeleg.

Vielen Dank.
[debug.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/875531/debug.zip)

**Comment by ErichFreitag** [comment]
Der Startbeleg muss einen Barumsatz von 0 haben, bei ihnen gibt es 20 EUR Umsatz.

**Comment by ErichFreitag** [comment]
P.S. AT100 ist auch kein zulässiger VDA, das ist jedoch vom Prüftool unabhängig.

**Comment by brainformance-cledeg** [comment]
Peinlicher Fehler, hatten noch Debug configs aktiv. Vielen Dank für den Hinweis!
