### ISSUE TITLE
Frage Sammelbeleg

### ISSUE THREAD

**Issue by daiNc** [a-sit-plus/at-registrierkassen-mustercode#504]
Hallo,

ich habe hier gesucht aber leider nichts zu dem Thema gesucht. Aber ich bin nicht Richtig schlau geworden.
Wenn die Signaturerstellungseinheit ausgefallen ist und ich Belege mit dem Aufdruck drucke, muss ich dann den Umsatzzähler erhöhen? Und danach einen Nullbeleg/Sammelbeleg erstellen wenn es wieder funktioniert. Oder muss ich die Belege nacherfassen?
Ich bin verwirrt zwischen diesen zwei Punkten:

> (4) Bei jedem Ausfall der Signatur- bzw. Siegelerstellungseinheit sind die Barumsätze auf einer anderen Registrierkasse zu erfassen, die über eine aufrechte Verbindung zu einer Signatur- bzw. Siegelerstellungseinheit verfügt. Sollte dies nicht möglich sein, hat der Unternehmer bei der Aufbereitung und Verwendung des maschinenlesbaren Codes (§ 10) an Stelle des Signatur- bzw. Siegelwertes des betreffenden Barumsatzes (§ 10 Abs. 2 Z 8) die Zeichenkette „Sicherheitseinrichtung ausgefallen“ im Ergebnis der Signatur- bzw. Siegelerstellung laut Z 6 der Anlage zu verwenden. Der Hinweis „Sicherheitseinrichtung ausgefallen“ ist zusätzlich gut sichtbar am Beleg (§ 11) anzubringen. Nach Wiederinbetriebnahme der Signatur- bzw. Siegelerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern.
(5) Bei jedem Ausfall einer Registrierkasse sind die Barumsätze auf anderen Registrierkassen zu erfassen. Sollte dies nicht möglich sein, sind die Barumsätze händisch zu erfassen und Zweitschriften der Belege aufzubewahren. Nach der Fehlerbehebung sind die Einzelumsätze anhand der aufbewahrten Zweitschriften nach zu erfassen und die Zweitschriften dieser Zahlungsbelege aufzubewahren (§ 132 BAO).

**Comment by ErichFreitag** [comment]
Wenn die Sicherheitseinrichtung ausfällt
- auf eine andere Kasse wechseln
- wenn das nicht möglich ist
-- Am Beleg und anstelle der Signatur "Sicherheitseinrichtung ausgefallen" aufbringen
-- ansonsten ganz normal weiterarbeiten, Umsatzzähler erhöhen etc.
-- Fehlerbehebung einleiten
-- > 48 Stunden Ausfall in Finanz-Online melden

- nach Wiederverfügbarkeit einen Sammelbeleg einfügen
- dazu Beginn und Ende des Ausfalls vermerken

Wenn die Kasse ausfällt -> händische Belege ausstellen, ...

**Comment by daiNc** [comment]
Vielen dank
