### ISSUE TITLE
Die Verkettung zwischen dem vorigen Beleg und dem aktuellen Beleg ist ungültig

### ISSUE THREAD

**Issue by brainformance-cledeg** [a-sit-plus/at-registrierkassen-mustercode#507]
Ich bekomme vom DEP-Prüftool noch die Fehlermeldung: 

Die Verkettung zwischen dem vorigen Beleg und dem aktuellen Beleg ist ungültig.

Folgende Punkte habe ich überprüft:

Die 

- Einzelbelegprüfungen funktionieren
- Es dürfte kein Problem des =Paddings sein (ich habe extra die Base64 Kodierung geändert und habe vom Prüftool eine entsprechende Fehlermeldung erhalten)
- Habe die Checkliste durchgearbeitet, wobei ein Großteil von dem A-Trust Webservice gemacht wird.

Anbei finden Sie  ein vereinfachtes DEP (Nur Start und Nullbeleg)

[debug.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/875812/debug.zip)

Vielen Dank und Lg

**Comment by ErichFreitag** [comment]
Die Verkettung beim Startbeleg ist OK.

Die Verkettung im zweiten Beleg ist wP6o0xR6nl4=, sollte nach meiner Rechnung 16Cljryrwms= sein.

AT100 stimmt auch noch nicht, hat aber mit der Verkettung zunächst nichts zu tun.

**Comment by brainformance-cledeg** [comment]
Vielen Dank!

Konnte das Problem mit ihrem Hinweis lösen. Hatte beim zweiten Beleg nur die Signatur des ersten statt der gesamten JWS-Comp. Repräsentation übergeben.

Mein DEP kann nun vollständig validiert werden
