### ISSUE TITLE
CMC-File: signatureCertificateOrPublicKey

### ISSUE THREAD

**Issue by ChristianSpath** [a-sit-plus/at-registrierkassen-mustercode#508]
Hallo zusammen!

Irgendwie komm ich nicht klar. Hier mein CMC File.

{
  "base64AESKey": "IfM5o8UCiXJfhHw5Y5W/9eER4pbeW74JQMnfZ6T1GDY=",
  "certificateOrPublicKeyMap": {
    "47a9a723": {
      "id": "47a9a723",
      "signatureDeviceType": "CERTIFICATE",
      "signatureCertificateOrPublicKey": "BPGlGX0lJsBqoVeYOIhvfR1SSM1jGamZtx/AMsGualhVlICYHJNzqRm5yXnZWJKFhXXIIO6Vx5Jg6go3qg9K/0U="
    }
  }
}

Kann es sein, dass "signatureCertificateOrPublicKey" falsch ist? Mir kommt das irgendwie kurz vor. Ich bin in C# so vorgegangen:

`SmartCard.readCertificate().GetPublicKey().Base64Encode(false) //false = nicht URL Save
`
GetPublicKey() retourniert ein Byte-Array.

Gibt es eigentlich eine Möglichkeit das DEP File vom FON-Webservice überprüfen zu lassen?

Wie holt ihr euch in C# das Signaturzertifikat bzw. den Public Key für das CMC File?

Vielen Dank und liebe Grüße

**Comment by ErichFreitag** [comment]
Das Zertifikat ist definitiv falsch. Zu C# kann ich konkret nichts sagen.

Wie sie beispielsweise zu einer Zertifikatsinfo kommen sehen sie in https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/496.

Das DEP-File hat mit dem FON-Webservice nichts zu tun.

**Comment by ErichFreitag** [comment]
P.S. habe gerade gesehen, dass sie GetPublicKey() aufrufen - sie müssen das Zertifikat auslesen, nicht den öffentlichen Schlüssel.

**Comment by ChristianSpath** [comment]
Hallo Erich!

Vielen Dank für den Tipp. Das hat geholfen 👍 

LG, Chri
