### ISSUE TITLE
Starbeleg geht durch Prüftool, in FON jedoch nicht (kryptographische Signatur)

### ISSUE THREAD

**Issue by Thomas233** [a-sit-plus/at-registrierkassen-mustercode#509]
Hallo,

ich versuche meinen Startbeleg gerade durch FON durch zu bekommen, nachdem im Prüftool der Startbeleg und einige weitere als "gut" befunden wurden.

Leider wird in FON die Prüfung der kryptographischen Signatur bemängelt, im Prüftool jedoch nicht (alles auf "PASS").

Ich habe folgende **Signatureinheit** (=> RK Online) in FON registriert:

Seriennummer:
649947EF (hex)
1687767023 (dez)	

Art:
Signaturkarte	

Vertrauens­diensteanbieter:
AT1 A-TRUST

Und folgende (Test)-**Registrierkasse**:

Kassen-ID:
CASHBOX-SCANNER-TEST1-7

AES-Schlüssel:
YUwRNbQIPwrBcIpZlfY8WnWoyEA4QWfL5+KT3pEdRl8=

Folgende Plaintext-Daten werden über **RK Online** signiert:

> _R1-AT1_CASHBOX-SCANNER-TEST1-7_CASHBOX-SCANNER-TEST1-7-Receipt-ID-9001_2017-03-28T21:58:11_0,00_0,00_0,00_0,00_0,00_jLeBb/EKi28=_649947EF_yn81tQEtVCw=

Ergebnis der Signatur:

>eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9DQVNIQk9YLVNDQU5ORVItVEVTVDEtN19DQVNIQk9YLVNDQU5ORVItVEVTVDEtNy1SZWNlaXB0LUlELTkwMDFfMjAxNy0wMy0yOFQyMTo1ODoxMV8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfakxlQmIvRUtpMjg9XzY0OTk0N0VGX3luODF0UUV0VkN3PQ.ncUuweoIh1nZz3Hcm_mV3s93E7Z_PQEWgA9oRh12badTswk8OvVHM6MjcpI1JkF63zC0aat402c4-LxQbkjk8A

Folgender Prüfungs-Fehler kommt in FON:

> Bezeichnung:Kryptographie: Überprüfung der kryptographischen Gültigkeit der SignaturBeschreibung:In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.Meldung:Bei der Überprüfung des maschinenlesbaren Codes wurde ein Fehler beim Abgleich des Signaturwertes mit dem öffentlichen Schlüssel festgestellt. Bitte überprüfen Sie, ob die verwendete Signatur- bzw. Siegelerstellungseinheit korrekt in FinanzOnline registriert wurde.

Ich habe jeweils bei den Eingaben in FON darauf geachtet, dass am Ende und Anfang keine Leerzeichen versehentlich dazu kommen.

Bitte, was kann da unterschiedlich sein ich weiß nicht mehr weiter.

Vielen Dank !

Edit: Anbei auch noch meine Outputs der Tests. Hab gerade bemerkt das da bei dem Test "STATE_CONSOLIDATED" ein FAIL drinnen steht, ist das normal ?

[cmc.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/876952/cmc.txt)
[0000_cashbox_full.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/876953/0000_cashbox_full.txt)

**Comment by Thomas233** [comment]
Ich vermute es liegt am QR-Code selbst, hier auch noch die Daten von diesem:
> _R1-AT1_CASHBOX-SCANNER-TEST1-7_CASHBOX-SCANNER-TEST1-7-Receipt-ID-9001_2017-03-28T21:58:11_0,00_0,00_0,00_0,00_0,00_jLeBb/EKi28=_649947EF_yn81tQEtVCw=_ncUuweoIh1nZz3HcmmV3s93E7ZPQEWgA9oRh12badTswk8OvVHM6MjcpI1JkF63zC0aat402c4LxQbkjk8A=

Im Prüftool kommt dann beim Prüfen des QR auch der Fehler (bei der DEP-Prüfung aber nicht siehe oben):
[0000_cashbox_full_qr.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/877046/0000_cashbox_full_qr.txt)

**Comment by ErichFreitag** [comment]
Sie verlieren bei der Umcodierung der Signatur im DEP-Eintrag ein paar Zeichen:
ncUuweoIh1nZz3Hcm_mV3s93E7Z_PQEWgA9oRh12badTswk8OvVHM6MjcpI1JkF63zC0aat402c4-LxQbkjk8A müsste 
ncUuweoIh1nZz3Hcm/mV3s93E7Z/PQEWgA9oRh12badTswk8OvVHM6MjcpI1JkF63zC0aat402c4+LxQbkjk8A== ergeben (88 Zeichen Länge).

**Comment by Thomas233** [comment]
Hallo Herr Freitag,

also wenn ich das richtig verstehe wäre dies die Base64-URL-kodierte Variante:

> ncUuweoIh1nZz3Hcm_mV3s93E7Z_PQEWgA9oRh12badTswk8OvVHM6MjcpI1JkF63zC0aat402c4-LxQbkjk8A 

Und dies die normale Base64-Variante, die dann auch in den QR kommt:

>ncUuweoIh1nZz3Hcm/mV3s93E7Z/PQEWgA9oRh12badTswk8OvVHM6MjcpI1JkF63zC0aat402c4+LxQbkjk8A==

D.h. beim dekodieren in der Zeile
`$signature = base64_encode(base64_decode($jwsSignatureEncoded));`

müsste ich statt _base64_decode_ eine Art _base64_url_decode_ haben wäre das korrekt ?

Vielen Dank !

**Comment by ErichFreitag** [comment]
Je nachdem wie sie die Daten aufbereiten. Z.B. DEP-Eintrag BASE64URL-decodieren und für den maschinenlesbaren Code BASE64-codieren. Oder umgekehrt. Oder ... Siehe im folgenden Diagramm:

![pqrst_rksv_datenmodell_signaturerstellung](https://cloud.githubusercontent.com/assets/18228048/24462484/5d993136-14a4-11e7-8ab1-e88adafd796e.jpg)

**Comment by Thomas233** [comment]
Na bumm :-D

Vielen Dank !

So hab ich es nun hinbekommen (es war tatsächlich die eigentlich fehlende Base64-Url-Dekodierung):

```
function base64url_decode($data) {
    return base64_decode(strtr($data, '-_', '+/'));
}

function getQr($jwsSignature)
{
    //$jwsSignature = "eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMF9ERU1PLUNBU0gtQk9YNTI0XzM2NjU5Nl8yMDE1LTEyLTE3VDExOjIzOjQ0XzAsMDBfMCwwMF8zLDY0Xy0yLDYwXzEsNzlfVkZKQl80N2JlNzM3Y2IxZjZkMWYxX1p2TnhKdzZhMUE0PQ.J7YC28zquHfHzMpx02TqElbXOTSgXQu5JAA9Xu1Xzzu5p8eUYTsgmyhzRps5nYyEp5Yh8ATIa9130zmuiACHw";
    
    $tokens = explode(".",$jwsSignature);
    $jwsPayloadEncoded = $tokens[1];
    $jwsSignatureEncoded = $tokens[2];

    if(!isset($jwsPayloadEncoded) || !isset($jwsSignatureEncoded))
        throw new Exception("QR Error");
    
    $payload = base64_decode($jwsPayloadEncoded);
    $signature = base64_encode(base64url_decode($jwsSignatureEncoded));
    
    if(empty($payload) || empty($signature))
        throw new Exception("QR Error");
 
    return $payload . "_" . $signature;
}
```

**Comment by csokay** [comment]
`function base64url_decode($data) {
    return base64_decode(strtr($data, '-_', '+/'));
}`

aufpassen, da wird kein Padding hinzugefügt. 
Bsp https://brockallen.com/2014/10/17/base64url-encoding/
