### ISSUE TITLE
Startbeleg FON fehlerhaft

### ISSUE THREAD

**Issue by alexrksv** [a-sit-plus/at-registrierkassen-mustercode#511]
Hallo,
wir haben die Fehlermeldung bei der Gültigkeit der Signatur.

Bezeichnung:
Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur
Bei der Überprüfung des maschinenlesbaren Codes wurde ein Fehler beim Abgleich des Signaturwertes mit dem öffentlichen Schlüssel festgestellt. Bitte überprüfen Sie, ob die verwendete Signatur- bzw. Siegelerstellungseinheit korrekt in FinanzOnline registriert wurde.

Diese Meldung kommt beim Prüftool von BMF. (App)

Der Startbeleg: _R1-AT1_0-1_1_2017-03-28T15:10:00_0,00_0,00_0,00_0,00_0,00_wxPYPUUVnXFfGd/wF/qiJw==_6A0768D8_OJ9/vI4FjWE=_oMbrKs2p9+8KvuG6elDtIBQIlL3P7rCgKPKIU/UoYY9rEOkU9czu9HtCCT2vRKLXz1F4NSGsXeUmhhdoodU2oA==

Und im FON wurde alles richtig registriert.

Bitte um euere Unterstützung.

**Comment by ErichFreitag** [comment]
Die Fehlermeldung sagt, dass mit der Zuordnung des Zertifikats etwas nicht passt. Aus dem QR-Code alleine kann man nichts weiter ersehen.

**Comment by Phoniexk** [comment]
Ich würde empfehlen das Problem im WKO-Forum zu posten, das BMF kann dort gezielt im jeweiligen FON-Account nachsehen und mitteilen warum es zu diesem Fehler kommt.

**Comment by alexrksv** [comment]
Danke für die schnelle Antworten.

Also die Zuordnung sollte laut A-Trust passen.
Seriennummer mit der UID usw.

Hab die daten nochmals kontrolliert, die ich im FON eingegeben habe.

@Phoenixk haben wir da einen Link von WKO Forum ?

**Comment by Phoniexk** [comment]
https://communities.wko.at/Kassensoftware/Lists/BMF%20BelecheckApp%20Belegprfung/AllItems.aspx

Dafür muss man freigeschaltet werden, per Mail via ubit@wko.at

**Comment by alexrksv** [comment]
@Phoenixk Dankeschön
