### ISSUE TITLE
Prüfungsergebnis bei APP > Allgemeiner Fehler

### ISSUE THREAD

**Issue by SchwarzerKaterRolandWeber** [a-sit-plus/at-registrierkassen-mustercode#512]
Hallo !

Muss für eine einzelne Webseite die RK Funktionen in PHP dazuprogrammieren. Bekomme in der PrüfApp für den Startbeleg jedoch immer nur die Meldung
"Allgemeiner Fehler
Belegprüfung fehlgeschlagen. Bitte überprüfen Sie den Beleg."
Laut Beschreibung sollte es hier nur die Meldung ok (grüner Haken) oder fehlerhaft (Rotes X) geben.

Anbei meine generierten Daten:
Vertrauensdiensteanbieter: AT1 A-TRUST
Seriennummer des Signatur- bzw. Siegelzertifikates: 2457E10C

FON: Registrierkassen
Kassenidentifikationsnummer: SchwarzerKatersTestKasse
Benutzerschlüssel AES-256: RnVja1lvdVJlZ2lzdHJpZXJrYXNzZW5TaWNoZXJoZWl0

FON: Belegprüfung
Authentifizierungscode für PrüfApp: 8Q2 CR9 2QY XEX

Inhalt des QR Codes
_R1-AT1_SchwarzerKatersTestKasse_1_2017-03-29T11:06:24_0,00_0,00_0,00_0,00_0,00_52ei4E+/TGg=_2457E10C_F+qS1K/7B8I=
![qr php](https://cloud.githubusercontent.com/assets/26762766/24447287/b2a3ebdc-1470-11e7-8c31-ac5c9342567a.png)

In welchen Bereich des Codes liegt hier noch der Fehler ?

**Comment by alexrksv** [comment]
Hallo,

wir hatten auch die Fehlermeldung. Bei uns war es der Fall, dass die Kassen-ID im FON nur als "1" eingetragen war.

Eigentlich sollte es 0-1 sein. Vielleicht ist bei euch auch der Fall.

Dann war der Startbeleg online, aber trotzdem Fehlerhaft. Aber zumindest steht eine ausfürhliche Fehlerbeschreibung.

**Comment by Alex1130** [comment]
Wenn der Fehler schon von der App erkannt wird, erfolgt keine Übermittlung ans FON. Bei Ihrem QR Code fehlt ein Feld.

**Comment by SchwarzerKaterRolandWeber** [comment]
ok danke Alex1130 ... QR code hatte die + verschluckt. Dies wurde korrigiert. Fehlermeldung bleibt jedoch leider die gleiche.
alexrksv eine Änderung bei der KassenID hat leider auch nichts gebracht.

Kann mir jemand bitte den String durch das Prüftool durchschicken. Bekomme auf meinen Win10 Rechner das java Prüfungstool leider nicht korrekt zum laufen (Your JVM does not provide the unlimited strength policy)

**Comment by Alex1130** [comment]
@SchwarzerKaterRolandWeber ich meinte es **fehlt** ein Feld. Ihr machinenlesbarer Code hat nur 12 Felder, oberflächlich betrachtet fehlt die Signatur...

**Comment by SchwarzerKaterRolandWeber** [comment]
danke ... jetzt wird die Überprüfung an FON gesendet.
