### ISSUE TITLE
Startbeleg: FON-Webservice sagt PASS, BMF-App schlägt fehl

### ISSUE THREAD

**Issue by duxthefux** [a-sit-plus/at-registrierkassen-mustercode#513]
Hallo,

wir haben den komischen Fall, dass die BMF-App den Startbeleg als ungültig abstempelt obwohl wir die Startbelegsprüfung übers Webservice erfolgreich durchgeführt haben?

Was kann da sein? Liegt es daran, dass man einen Startbeleg nicht zweimal prüfen kann?

Diesen Wert haben wir im Startbeleg (maschinenlesbarer Code) stehen:
`_R1-AT9_200001a_200001a_2017-03-29T11:55:50_0,00_0,00_0,00_0,00_0,00_UXE+jfDy8hk=_15ce416d2e2af_Dpfoea1H3og=_KTttxTNcchrpnQWn+9CSKaEgWHxhCR5GIXTYE++M+Ce5KjyrmpkppDL8lcyNJNG6WNuLRJTXNDQy5pIu83UJkA==`

Und diesen haben wir per Webservice übermittelt und der passt:
`_R1-AT9_200001a_200001a_2017-03-29T11:55:50_0,00_0,00_0,00_0,00_0,00_UXE+jfDy8hk=_15ce416d2e2af_Dpfoea1H3og=_KTttxTNcchrpnQWn+9CSKaEgWHxhCR5GIXTYE++M+Ce5KjyrmpkppDL8lcyNJNG6WNuLRJTXNDQy5pIu83UJkA==`

Also komplett der selbe Wert. Was könnte damit nicht stimmen?

Danke!

**Comment by TKast** [comment]
... der Webservice war vorhin wegen Wartungsarbeiten offline (die Meldung kam zumindest bei einer versuchten Kassenanmeldung zurück), vielleicht erzeugt das den Fehler in der App.

Ev. später nochmal probieren.

**Comment by TKast** [comment]
Webservice geht seit etwa 13:20 wieder.
Bei mir kommt kein Fehler in App, wenn zuvor per Webservice der Beleg geprüft wurde.

In dem Fall erscheint auch grünes Häkchen mit dem Hinweis, dass der Beleg bereits geprüft wurde.
(gerade im Echtbetrieb getestet)

**Comment by duxthefux** [comment]
habe den fehler gefunden...war auf meiner seite...hab den QR über eine url erzeugt:
qr.png?content={MACHINE_CODE} und da im maschinenlesbaren Code "+" sind, hauts mit die URL auf.
Danke trotzdem für die Hilfe!
