### ISSUE TITLE
Maschinenlesbaren Code an Prüftool senden

### ISSUE THREAD

**Issue by alexrksv** [a-sit-plus/at-registrierkassen-mustercode#515]
Hallo,
beim Prüftool bei den Test-Szenario bekomme ich auch Fehler.

Könnte bitte jemand diesen maschinenlesbaren Code mal überprüfen ?

_R1-AT1_0-1_1_2017-03-29T09:47:00_0,00_0,00_0,00_0,00_0,00_wxPYPUUVnXFfGd/wF/qiJw==_6A0768D8_OJ9/vI4FjWE=_AHH5xkVxF0/i+roprNur2OyLLoSzknFE1wyk+CEP0Y0XnXesK/SfRXBQeSWbUUfWvPU9ickZY89HmVgU7mSuTw==

danke Vorab für die Hilfe.

**Comment by rjungbeck** [comment]
Der encryptete Umsatzzähler (vor base64) ist 16 Bytes lang. Erlaubt sind 5-8 Bytes. (Macht auch keinen Sinn da bereits 5 Bytes für Umsätze von 5 Millarden reichen),

**Comment by alexrksv** [comment]
@rjungbeck danke für die schnelle Antwort. Aber wo sieht man es dass es 16Bytes lang ist ?

Haben Sie es über den Prüftool bekommen ?

Weil wir die werde genauso wie beim Demotool übernommen haben.

Danke für die Unterrstützung.

**Comment by rjungbeck** [comment]
Python 2 Zeiler:

    import base64
    print len(base64.b64decode("wxPYPUUVnXFfGd/wF/qiJw="))

**Comment by alexrksv** [comment]
danke für die Antwort. Wir werden es gleich ausprobieren. Melde dann das Ergebniss hier.

**Comment by alexrksv** [comment]
Bezeichnung:
Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur
Beschreibung:
In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.
Meldung:
Bei der Überprüfung des maschinenlesbaren Codes wurde ein Fehler beim Abgleich des Signaturwertes mit dem öffentlichen Schlüssel festgestellt. Bitte überprüfen Sie, ob die verwendete Signatur- bzw. Siegelerstellungseinheit korrekt in FinanzOnline registriert wurde.

_R1-AT1_AKEAD-1_1_2017-03-29T16:55:00_0,00_0,00_0,00_0,00_0,00_xRIPKUY+3Vs=_6A0768D8_86oM4ZWpRDQ=_KGXVGRstYgv8LbpD1cZFu4GLvWgDmHi1Amhq2SmwV+F0Prze0n04N/Od1RbOCLF6SH8qXAgK3jngZq0PjxKRdQ==

AES-Schlüssel: 1z1vgkOTF6l3Cs/dro0v5rLwbNMP7CIFSKktcJERGH8=

**Comment by FriNagy** [comment]
kannst auch mit mein regkp testen

https://github.com/FriNagy/RegKP/blob/master/RegKP.exe

mit RegKP -?c certificate ausgeben nach .\cert.as1 dort Seriennummer und UID kontrollieren,

bzw. mit RegKP -tsb einen Startbeleg erstellen (ertellt: .\lastqr.txt f. QR Code )

( in .\kpar.txt AES Key und  Ser.Nr. anpassen )

**Comment by alexrksv** [comment]
Hallo @FriNagy danke für die regkp.

Wie muss ich den ausführen ? Wenn ich die Exe öffne kommt kurz das Kommandozeilenfenster dann passiert nichts.

kannst du etwas genauer beschreiben ?

**Comment by alexrksv** [comment]
ich lade mal das ganze von deiner seite herunter.

und führe es mit dem mal aus.

**Comment by alexrksv** [comment]
Ich kann leider den RegKP nicht ausführen :(

**Comment by FriNagy** [comment]
Hallo!

es ist nur ein exe (zuerst),
gestartet wird im command Fenster
mit regkp -? zeigt die mögliche Parameter

mit RegKp -tsb macht einen Test Startbeleg, und erstellt einige Dateien
unter anderem .\kpar.txt wo die ganze Parameter sind 
(die sind dann zu ändern, und dann nochmal mit -tsb starten)
im .\lastqr.txt immer die letzte QR Code

mit RegKP -?r zeigt die angeschlossene Reader und prüft die Karten

mit RegKP -?c gibt die Karten Zertifikat nach .\cert.as1 aus

aber hauptsächlich ist natürlich für Signieren via cmdline gedacht

**Comment by alexrksv** [comment]
Hallo nochmals, 

funktioniert es auch mit RK Online ? Weil wir haben die Online-Lösung. Also nicht mit der Chipkarte.

Falls ja , wo muss ich den im Code ändern ? 

danke für deine Unterstützung.

**Comment by FriNagy** [comment]
sorry!

das Programm ist nur für Card.Reader :(
sogar dort nur mit Karten von A.Trust getestet

wir planen zwar auch RK online als Backup f. notfälle
aber zuerst muss es so laufen ....

**Comment by alexrksv** [comment]
alles klar, danke vielmals..

**Comment by alexrksv** [comment]
Es hat soweit funktioniert.

danke für die Hilfe.

**Comment by alexrksv** [comment]
es hat funktioniert. danke.

**Comment by Phoniexk** [comment]
@rjungbeck: das mit den 5-8 bytes für den Umsatzzähler ist nicht korrekt. Die RKSV schreibt nur vor dass die minimale Länge 5 Bytes beträgt. Eine Begrenzung von maximal 8 Bytes gibt es nicht (nicht mit dem Verkettungswert verwechseln).

Punkt 9 der RKSV-Detailspezifikation im Anhang:

> Kodierung des Umsatzwertes: Die Block-Größe von AES-256 entspricht einem Byte-Array der Länge 16. Für die Kodierung des Umsatzzählers im Klartext wird dabei ein Byte-Array der Länge 16 erstellt. Jedes Element des Byte-Arrays wird mit 0 initialisiert. Der Umsatzzähler mit der Byte-Anzahl „N“ wird startend mit Byte 0 im BIG-ENDIAN Format als Zweier-Komplement Darstellung („signed“) gespeichert. „N“ entspricht der Anzahl der Bytes die für die Kodierung des Umsatzzählers notwendig sind. **Es müssen mindestens 5 Byte lange Umsatzzähler verwendet werden**.

Minimal müssen es 5 sein, das Maximum liegt aber ganz klar bei 16 Bytes. Nur hier auf github im Detailfragendokument wird erwähnt, dass man den Umsatzzähler so kurz wie möglich halten soll, damit der QR-Code so kurz wie möglich ist.

Prüftool sowie die Startbelegprüfung im FON-Webservice haben kein Problem mit 16 Bytes.

Die meisten Hersteller verwenden so lange Kassen-ID's bzw. Belegnummern, VDA's wie Globaltrust haben extrem lange Seriennummern, da kommt es auf die paar zusätzlichen Zeichen auch schon nicht mehr an. Es bringt jedenfalls weniger Probleme wenn man gleich die ganzen 16 Bytes nimmt.

**Comment by FriNagy** [comment]
@alexrksv 
Hallo! 
ich habe in RegKP doch das On-Line Untersützung einbauen müssen,
und wir können jetzt mit RegKP auch die Zertifikate ausgeben siehe:
https://github.com/FriNagy/RegKP/blob/master/regkp_all.7z

Karte (in Reader 0):
`RegKP -si`

RK-Online Konto (Username: u123...):
`RegKP -ou u123456789 -si`
 
vleicht habt ihr Zeit mal ausprobieren, es ist und bleibt free

**Comment by pasalpha** [comment]
Hallo finde das Tool super,

Aber (da ich Neuling auf dem Gebiet bin bitte verzeiht die Frage) wo kommt denn da der PIN Code ins Spiel?
