### ISSUE TITLE
Startbeleg Prüfung schlägt fehl

### ISSUE THREAD

**Issue by intellisec** [a-sit-plus/at-registrierkassen-mustercode#522]
Hi
Ich hab folgendes Problem: Ich habe mehrere Startbelege, welche bei der Prüfung fehlschlagen. Ich bin mittlerweile etwas ratlos. Wir benutzen die A-Trust RK Online Zertifikate, welche auch richtig bei FON hinterlegt sind. Die Kassenplätze sind auch richtig hinterlegt, und die Schlüssel weisen auch keine Fehler auf.

Wäre um jede Hilfe dankbar.

Das ist der QR-Code:
![img_7518 004](https://cloud.githubusercontent.com/assets/1464673/24503397/37db8e18-1552-11e7-994e-9831f44e6a54.jpg)
Der QR-Code spuckt das aus:
`_R1-AT1_1_00321-001-0001_2017-03-22T11:47:01_0,00_0,00_0,00_0,00_0,00_NMpS1osQrpo=_c91b882_a4ayc/80/OE=_KzUAnkwhAITjmzZaGnkdtDXRpqKIDQNh7ndxfeBfNDJEFr+UxdRoTFuu6yOpcuYBDlkPGdZp0qo8dlgQdCJA3Q==`

Und der Schlüssel lautet:
`YzI5NWU5YmEzYTZmOWJiZjIwNzQzZDA0YjNmOGM4NTM=`

**Comment by ErichFreitag** [comment]
Was ist die Fehlermeldung?

**Comment by intellisec** [comment]
[Beleg_1555070.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/882235/Beleg_1555070.txt)
Das kommt beim FON raus

**Comment by ErichFreitag** [comment]
Heißt, dass insbesondere die Startbelegprüfung fehlschlägt. Also die Verkettung mit der Kassen-ID falsch ist oder der Umsatzzähler nicht auf 0 entschlüsselt werden kann.

**Comment by MichaelSchustereder** [comment]
Oder, was wir schon hatten, dass der Steuerberater beim manuellen Eintragen der Daten im FON sich im AESKey vertippt hat.

**Comment by intellisec** [comment]
Den AES-Key haben wir kontrolliert, der stimmt mit ziemlich hoher Wahrscheinlichkeit.
Dann bleiben nur noch die Stellen Verkettung oder Umsatzzähler übrig. Das ist doch schon mal was...

**Comment by rolandro** [comment]
Nach meinen Berechnungen mit deinen Daten steht der Umsatzzähler auf 26900, sollte aber 0 sein beim Startbeleg. Ich komme auf folgendes Ergebnis (ohne Signatur)

_R1-AT1_1_00321-001-0001_2017-03-22T11:47:01_0.00_0.00_0.00_0.00_0.00_NMpS1osQx4
4=_c91b882_a4ayc/80/OE=

**Comment by Phoniexk** [comment]
@rolandro: Achtung der von Ihnen angegebene maschinenlesbare Code weißt formale Fehler auf. Die einzelnen Beträge der Steuersätze weißen ein "." (Punkt) als Kommastelle auf, die RKSV fordert "0,00" also ein "," (Komma/Beistrich) anstelle des Punktes.

**Comment by rolandro** [comment]
sorry, die "Kommapunkte" sind durchs Kopieren aus einem US-Linux System entstanden.

**Comment by eauth** [comment]
Stimmt die Zertifikat-Seriennummer? Ich dachte die ist bei A-Trust 8-stellig!?

**Comment by Phoniexk** [comment]
@rolandro: das stimmt schon, das Prüftool erkennt es nicht fehlerhaft an, dennoch ist es formal fehlerhaft, weil in der RKSV extra als "," spezifiert ;) ... aber egal soweit, brauchen wir nicht weiter drüber diskutieren :D

**Comment by intellisec** [comment]
War Benutzerfehler ... Sie hatten den falschen Beleg genommen.
