### ISSUE TITLE
Sicherheitseinrichtung ausgefallen

### ISSUE THREAD

**Issue by alexrksv** [a-sit-plus/at-registrierkassen-mustercode#523]
Hallo ,

wir haben die Überprüfung des Startbelegs soweit geschafft.

Jedoch haben wir jetzt weiteres Anliegen. Und zwar wenn die Sicherheitseinrichtung ausfällt bzw. Verbindungsprobleme gibt wird es ja drauf stehen "Sicherheitseinrichtung ausgefallen".

Bei uns wird es in den QR-Code (Maschinenlesbare Code) eingebaut. Muss dieser Text auch für den Kunden (Unternehmer) als normaler Text auf dem Beleg ersichtlich sein bzw. gedruckt werden ?

Im Dokument habe ich nur den QR-Code gefunden.

Danke für die Hilfe.

**Comment by Flanelli** [comment]
3.5.3.3. Behandlung von Fehlersituationen bei der Startbelegprüfung 
Bei fehlgeschlagener Startbelegprüfung ist so rasch wie möglich die Fehlerursache zu klären 
und zu beheben. Kassenherstellern steht dafür unter https://github.com/a-sit-plus/at-
registrierkassen-mustercode ein passendes Prüftool zur Verfügung. Auch auf der BMF 
Homepage wird dieses Prüftool ebenfalls zur Verfügung gestellt. Der Betrieb der 
Registrierkasse kann bis zur Klärung der Fehlerursache fortgesetzt werden, **am Beleg muss 
aber gemäß § 6 Abs. 4 RKSV der Hinweis „Sicherheitseinrichtung ausgefallen“ angebracht 
werden.**

**Comment by alexrksv** [comment]
danke für die rasche Antwort.

Aber es ist nicht der Startbeleg betroffen. Angenommen Nach X beliebege Belege ist Sicherheitseinrichtung nicht da. Es ist ja hier so definiert in dem Detailfragen-RKSV-V1.2.pdf auf der Seite 45.

sicherheitseinrichtung-ausgefallen: Statt dem Signaturwert, der in diesem Fall nicht berechnet werden kann, wird die Zeichenkette Sicherheitseinrichtung ausgefallen BASE64-URL kodiert und als drittes Element anstelle des Signaturwertes in der kompakten Darstellung der JWS-Signatur verwendet. In der BASE64-URL Kodierung entspricht dies dem Wert U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg.6

**Comment by ErichFreitag** [comment]
Der Text muss codiert anstelle der Signatur enthalten sein und im Klartext am Beleg aufgedruckt werden.

**Comment by Flanelli** [comment]
@alexrksv Der Auszug aus dem Erlass gilt ja auch nicht nur für den Startbeleg.
Sie sollten eventuell doch in Erwägung ziehen den gesamten Erlass im Detail zu lesen.
Den String den Sie gepostet haben isz niocht korrekt aber möglicherweise nur ein Tipfehler U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg**.6**

**Comment by alexrksv** [comment]
@Flanelli ach sorry, es war mein Fehler beim kopieren :)

@ErichFreitag danke für die Erklärung

**Comment by alexrksv** [comment]
Danke für die Hilfe.
