### ISSUE TITLE
Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.

### ISSUE THREAD

**Issue by ndrischmann** [a-sit-plus/at-registrierkassen-mustercode#524]
Guten Tag,

ich habe gerade einen Beleg mit dem Prüftool überprüft und dabei die Fehlermeldung aus dem Titel erhalten.
Die Datei mit den Belegdaten und der CryptographicMaterialContainer hängen an.

Ich habe hier schon diverse Einträge zu diesem Thema durchgesehen, habe aber bisher nichts passendes gefunden. Aus der Fehlermeldung des Prüftools werde ich auch nicht recht schlau.
Kann mir jemand weiterhelfen?

[cryptographicMaterialContainer.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/882347/cryptographicMaterialContainer.json.txt)
[qr-code-rep.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/882346/qr-code-rep.json.txt)

**Comment by ErichFreitag** [comment]
Der Eintrag des Zertifikats muss im .PEM-Format vorliegen.

**Comment by FriNagy** [comment]
kann nur anbieten:

https://github.com/FriNagy/RegKP/blob/master/RegKP.exe
downloaden

in cmd Fenster mit "RegKP -tsb" einen Test-Startbeleg mit Demo-Daten erstellen
in .\kpar.txt AES Key und Ser.Nr. anpassen
nochmal  "RegKP -tsb"  starten jetzt mit deine Daten 

erstellt crypto.json und dep-export.json
kannst sofort in Prüftool testen

**Comment by ndrischmann** [comment]
Vielen Dank für die schnelle Hilfe! Das Zertifikat im richtigen Format anzugeben hat tatsächlich schon geholfen.
