### ISSUE TITLE
Signaturkarte bei Windows Server

### ISSUE THREAD

**Issue by YanivYon** [a-sit-plus/at-registrierkassen-mustercode#526]
Hallo
ich habe 2 Kunden bei denen ich nicht auf die Signaturkarte zugreifen kann.
Einer hat Windows Server 2012, der andere Server 2016
ich habe zum testen auch den a.sign client installiert
der hat auch keine Karte gefunden.
Bei allen anderen Kunden (Win 7,8,10) funktioniert alles einwandfrei
Gibt es eine Berechtigung oder Einstellung dafür?

Danke im Voraus

**Comment by ThomasBeckBerlin** [comment]
Wenn auf die Server Via Remote-Desktop zugegriffen wird, verlieren Sei automatisch den Zugriff auf die Karte

**Comment by Phoniexk** [comment]
Wir haben ebenfalls einen Kunden der in einer Außenstelle (einmal pro Woche, geringe Frequenz) nur via Remote auf den Hauptserver zugreift und so die Registrierkasse bedient. Soweit ich mich erinnern kann, mussten wir den A-Trust-Stick (RK Chip) am Client-PC installieren, damit es funktionierte. Bei der Installation des Sticks am Server hat ebenfalls nichts funktioniert. Der Kunde ist via VPN mit dem Netz verbunden und dann via Remote-Verbindung zum Server. Der Server erkennt dann den Stick der am Client installiert ist. Allerdings kann ich gerade nicht mehr sagen ob hier die normale Windows Remote Desktop Verbindung genutzt wird oder Zusatzsoftware, die den Stick "durchschleift".

**Comment by YanivYon** [comment]
Danke
über Teamviewer hat es funktioniert
