### ISSUE TITLE
Verschlüsselung USZ - Prüftool PASS: qr-code-rep.json vs. implementation with differences

### ISSUE THREAD

**Issue by tomw1808** [a-sit-plus/at-registrierkassen-mustercode#528]
So, my implementation produces PASS everywhere, although my Turnovercounter (Verschlüsselter Umsatzzähler) is slightly different than in the regkassen-demo-1.0.0/qr-code-rep.json

Line Number 6 (official) qr-code-rep.json
```
_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-6_2016-03-16T09:02:13_120,34_21,49_135,72_34,39_193,07_k8wUAFWM_495b0098121676e3_AGrKYU8+MOs=_U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg==
```

vs.

```
_R1-AT100_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-6_2016-03-16T09:02:13_120,34_21,49_135,72_34,39_193,07_k8wUAJDJ+Ro=_1480372172_+b8hT975YwE=_CMATVl+Yxh0Tvz+Z9bskpSCVkioPuH7sBOSP29gZmlTf7Kd37UcERFKYy7rfJxLsOyIdP9xrjjZWOc6XVNDduA==
```

Have a look at the turnover counter:

official:
```
k8wUAFWM
```
vs mine:
```
k8wUAJDJ+Ro=
```

It seems like I am not the only one with this turnover counter:
#91 
#235 

base64_decode and decrypt with the AES Key works for both perfectly. Language is PHP. 

Any hints
* Where that problem could possibly come from
* If both of them are valid for the FinanzOnline

would be nice.

Thanks,
Thomas

**Comment by andreasschiestl** [comment]
The two turnover counter have different lengths. The allowed length is between 6 and 8 Bytes.

Maybe it is a better idea to read the document "Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV)" rather than studying the demo code. This document is a detailed technical specification of the whole process.

**Comment by tomw1808** [comment]
@andreasschiestl hey thanks, I know that document from the inside out. The allowed length is between 5 and 8 bytes, as far as I know. (Seite 36, " Die minimale Länge ist mit 5 Bytes definiert.").

To my best knowledge, my turnovercounter is 8 bytes long. Any other ideas?

**Comment by tomw1808** [comment]
@andreasschiestl perfectly right, thanks for pointing it out!

The one is 6bytes long and mine is 8bytes long.

Closing.

**Comment by andreasschiestl** [comment]
Sorry, you are right. The mininum length is 5 Bytes.
