### ISSUE TITLE
Startbelegprüfung "Signatur kann nicht mit öffentlichem Schlüssel abgeglichen werden"

### ISSUE THREAD

**Issue by Pixelworker** [a-sit-plus/at-registrierkassen-mustercode#529]
Ein freundliches Hallo erstmal an alle,

Ich habe wie so viele andere hier das Problem, dass mir beim Überprüfen des Startbelegs ein rotes Kreuz präsentiert wird. Auf der Finanzonline-Seite kriege ich dann zu diesem Fehler inhaltsgemäß die Erklärung, dass die kryptographische Gültigkeit nicht gegeben ist und die Signatur nicht mit dem öffentlichen Schlüssel abgeglichen werden kann. Wir verwenden ein (gültiges) RK-Online-Zertifikat (Seriennummer: `70D7514C`) von A-Trust.

Der AES-Schlüssel lautet `BgoTRQsEE1MUBhQJBggUDgkKE2AfKTsaNTphG7ZRUlQ=` (Achtung, vor dem letzten Q steht ein kleines L, das haben wir bereits fälschlicherweise als großes i eingegeben), dieser wurde inklusive Prüfziffer (`wFEj`) in Finanzonline erfolgreich eingetragen.

Hier noch eine paar weiter Daten zum Beleg:
KassenID: WB-112V
Datum/Uhrzeit:  31.03.2017 11:10:59
Belegnr.: 000000000

Zu guter Letzt hier noch der Inhalt des QR-Codes:

`_R1-AT1_WB-112V_000000000_2017-03-31T11:10:59_0,00_0,00_0,00_0,00_0,00_Y6q0pJQ=_70D7514C_trFomMFNIBk=_ugziQoZDVhvoOYMpN67OQKnI/bRO7XLy54ssyzihaIwZdO9OprXe5bv5DQT5SEa3/LJgOeV6e3YocGGPiytHEA==`

Wir sind jetzt etwas ratlos, da wir jetzt x-mal die einzelnen Prozesse für die jeweiligen Felder durchgegangen sind (alles wird brav nach Vorschrift von a-sit gemacht) und einfach keinen Fehler erkennnen konnten.

Ich bin jedenfalls für jeden Hinweis dankbar!

**Comment by rolandro** [comment]
Woher kommt dein Verkettungswert?
Beim Startbeleg sollte es SHA256 von der Kassa ID sein:
Kassa Id : WB-112V  -> SHA 256 -> 6v2mwKJojCY= (bei dir aber trFomMFNIBk=)

**Comment by ErichFreitag** [comment]
a) was ergibt die Prüfung mit dem A-SIT-Prüftool?
b) wie sieht das z.B. unter https://certlogik.com/decoder/ decodierte Zertifikat aus?
c) ist das tatsächlich der Inhalt des QR-Codes (aus der Grafik gescannt) oder soll er das sein?

**Comment by Pixelworker** [comment]
@rolandro Danke für den Hinweis, jetzt wo ich den Hash manuell berechnen lasse, erhalte ich tatsächlich denselben Hash, das muss ich mir auf jeden Fall näher anschauen. 

@ErichFreitag 
a) Das Ergebnis habe ich leider im Moment nicht in der Hand, da ich nicht mehr im Haus bin, ich werde aber in etwa 2 ½ - 3 Stunden zurückkommen und das dann testen.
b) Leider auch im Moment kein Zertifikat bei der Hand
c) Das ist der Inhalt des gescannten QR-Codes.

Allen auf jeden Fall vielen Dank für die schnelle Antwort, jetzt habe ich wieder einige Ideen, wo wir angreifen müssen

**Comment by Pixelworker** [comment]
Der Fehler mit dem Verkettungswert wurde jetzt behoben (Dummerweise wurde der Verkettungswert vom nächsten überschrieben, bevor er in den QR-Code codiert wurde). Ich habe jetzt in obiger Signatur den richtigen Hash eingegeben und habe es durch das Prüftool laufen lassen, mit folgendem Ergebnis:

[0000_app.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/886497/0000_app.json.txt)
[0000_cashbox_full.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/886498/0000_cashbox_full.json.txt)
[0000_cashbox.json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/886499/0000_cashbox.json.txt)

In der Datei "0000_cashbox_full.json" findet die Suchfunktion des Texteditors 11 Vorkommnisse von "FAIL", oben wird aber geschrieben, die Registrierung sei erfolgreich gewesen. Was stimmt nun ?

**Comment by Flanelli** [comment]
@Pixelworker 
Das sollte so schon OK sein,
Es wurde zwar schon vor geraumer Zeit angekündigt dass diese verwirrende "falsche" Anzeige
in der nächsten Version beseitigt wird aber es kam bis dato nichts dergleichen.
Diese Thema wurde bereits in einigen Issues diskutiert, ich finde aber gerade die entsprechenden
Links nicht.

**Comment by rolandro** [comment]
Sieht eigentlich gut aus, sollte funktionieren wenn auch die Signatur passt

**Comment by Pixelworker** [comment]
Startbeleg wurde jetzt gedruckt und tatsächlich erfolgreich überprüft! Vielen Dank euch allen für die rasche Hilfe!
