### ISSUE TITLE
Belegerstellung ohne QR-Code

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#53]
Wenn man den maschinenlesbaren Code nicht als QR-Code auf den Beleg drucken will oder kann, sieht das Gesetz vor:
"Sofern ein maschinenlesbarer Code nicht als QR-Code am Beleg aufgedruckt werden kann, sind die Daten nach Abs. 1 entweder
•	als ein vom Signaturwert des betreffenden Barumsatzes abhängiger Link in maschinenlesbarer Form als Barcode oder OCR zum Abruf der Daten bereitzuhalten und am Beleg auszuweisen oder 
•	entsprechend der in Z 14 der Anlage festgelegten Codierung am Beleg auszuweisen."

Bisher hatten wir die Variante Link zum Abruf der Daten ins Auge gefasst, bis ich die Ausführungen in den Detailfragen gelesen habe, wo sich diese Variante rein auf Bereitstellung im Internet bezieht.
Ich hatte eigentlich gedacht, dass der "Link" ein Link zum Beleg innerhalb des Kassensystems ist, also ein Abruf der maschinenlesbaren Daten aus dem DEP.

Weiterhin hatte ich bisher angenommen, dass der maschinenlesbare Code für den Prüfer von Bedeutung ist und weniger für den Bürger. Wenn ich nun per Link den maschinenlesbaren Code aus dem Internet abrufen kann - schön und was macht man dann damit? EIne Überprüfung auf evtl. Manipulation geht doch eigentlich nur mit Hilfe des DEP, wo ich die Korrektheit der Verkettung prüfen kann. EIne solche Prüfung wird doch sicher im Laden durchgeführt.

Über Aufklärung würde ich mich sehr freuen.

**Comment by asitplus-pteufl** [comment]
Ich kann Ihnen hier nur technische Auskünfte geben, eine Verlinkung auf einen internen Bereich ist nicht vorgesehen.
