### ISSUE TITLE
Gemalto IDBridge CT40 Treiber

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#531]
Hallo,

für meine Lösung verwende ich die Kartenleser Gemalto IDBridge CT40 Treiber + die Chipkarte (A-Trust) und bei ein paar Kunden kommt nach der Installation des Treibers (beim erstmaligen anstecken des Lesers) die Meldung dass der Treiber nicht installiert ist.

Im Geräte Manager beim Smartcard ist folgende Meldung vorhanden: Die Treiber für dieses Gerät wurden nicht installiert. (Code 28)

Die Signierung funktioniert problemlos, die Starbelege aller Kunden wurden problemlos beim Finanazamt angenommen (Webservice).

Hat jemand vielleicht ähnliche Probleme im Feld?

**Comment by norbert2** [comment]
Ja. Hab das selbe Problem gehabt und mit folgenden Links lösen können.

Prinzipiell kann die Meldung ignoriert werden. 
Aber irgendwann gibt's dann doch eine Meldung, die der Anwender dann schon melden soll.
Also natürlich versuchen, diese Meldung abzuschalten.

Das Problem hängt mit der Plug&Play-Funktion von bzw. für Smartcards zusammen.
Wenn die aktiv ist, versucht Windows, Treiber zu installieren, was nicht nötig bzw. nicht möglich ist.
Die Artikel beziehen sich auf Windows 7, gilt aber auch für Windows 10.

Ein Artikel beschreibt das Ausschalten über ein entsprechendes Control-Panel. Nur bei Prof-Versionen von Windows anscheinend verfügbar.

Der andere Artikel beschreibt das Ausschalten via Regedit. Überall verfügbar

http://blog.knecht-ruprecht.info/2009/12/windows-7-und-fehlende-smartcard.html

http://blog.knecht-ruprecht.info/2010/01/windows-7-und-fehlende-smartcard.html

**Comment by Phoniexk** [comment]
Ja das Problem ist uns nur bei W7 aufgefallen. Haben A-Trust diesbezüglich schonmal kontaktiert:

> der fehlende Treiber ist für Registrierkassenkarten irrelevant. Es handelt sich um den Minitreiber, der für Funktionen wie Smartcard Login verwendet wird. Wir machen gerade eine Minitreiberzertifizierung mit Microsoft. Nach der Zertifizierung wird der Treiber automatisch durch Windows Update geliefert und die Meldung sollte nicht mehr erscheinen.

**Comment by AlgoLinz** [comment]
vielen Dank für die Antworten.
