### ISSUE TITLE
Software für Kartenprogrammierung

### ISSUE THREAD

**Issue by ggoelles** [a-sit-plus/at-registrierkassen-mustercode#533]
Wo genau findet man die Software um die Signaturkarten zu programmieren?
Bin auf der HP von A-Trust nicht wirklich fündig geworden.

**Comment by lebail** [comment]
Falls Sie mit "programmieren" das "Aktivieren" (also die Personalisierung der Karte) meinen, dann hier:

https://www.a-trust.at/AktivierungRegistrierkasseChip.aspx

Falls es Ihnen hingegen um den Zugriff auf die Karte durch Ihre Regsitrierkase geht, gibt es hier Codebeispiele:

http://labs.a-trust.at/developer/ShowSource.aspx?id=114

**Comment by ggoelles** [comment]
Meinte die Aktivierung. Danke!
