### ISSUE TITLE
StartBegeg korrekt übernommen ohne Belegnummer

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#536]
Hallo,
eine von unsere Kunden hat fehlerweise einen StartBeleg ohne die Belegnummer erstellt und damit die Kasse initialisiert, ohne einen Fehlermeldung. Darf man jetzt weiter solche Kasse verwenden, oder muss man die dereg und reg mit andere ID Nummer? kann man das irgendwie beim Finanzonline anrufen und das klären?

Wenn man jetzt die Belegnummern einfach weiter consequent verwendet, sollte ja doch OK sein wenn da keinen Fehlermeldung aufgetretten ist beim Startbeleg ohne die Belegnummer?

MfG

**Comment by ErichFreitag** [comment]
Mir fehlt noch die Fantasie, wie das möglich sein soll - die Belegnummer ist ein Bestandteil des maschinenlesbaren Codes und wenn die fehlt, kann die Prüfung nicht funktioniert haben.

**Comment by espeitslo** [comment]
hahaha, ja leider doch. Sonnst wurde ich das hier nicht schreiben. Aber ok, MIT Fantasie, darf man dann solche Kasse verwenden? es wurde je korrekt initializiert?

**Comment by ErichFreitag** [comment]
Rein formal: wenn die Prüfung OK ergibt kann der Ersteller annehmen, dass alles OK ist.

Rein technisch: wenn ihnen ein Fehler bekannt ist, ist er zu beheben. Ich würde auch die Kasse außer Betrieb nehmen und eine neue Kasse in Betrieb nehmen, sonst wird der DEP-Export immer einen Fehler liefern.

**Comment by germanchiefprogrammer** [comment]
> Rein technisch: wenn ihnen ein Fehler bekannt ist, ist er zu beheben. Ich würde auch die Kasse außer Betrieb nehmen und eine neue Kasse in Betrieb nehmen, sonst wird der DEP-Export immer einen Fehler liefern.

Dies ist rein technisch ein guter Vorschlag. Aber wie wird das in der Praxis gehandhabt. Es ist ja im laufenden Betrieb unmöglich den Kunden eine neue Kasse zu übergeben. Dann sind ja alle seine Eintragungen, Statistiken, usw. weg. Oder wie machen das andere?

**Comment by ErichFreitag** [comment]
Die Prozedur ist generell wie folgt:

- Schlussbeleg generieren (soferne technisch möglich)
- Gesamtes DEP exportieren und aufbewahren
- Kasse abmelden
- neue Kasse in Betrieb nehmen = Startbeleg etc. erzeugen
- Vorfall dokumentieren

Es kann auch die selbe physische Kasse sein und bleiben - sie müssen nur den einen RKSV-Lebenszyklus sauber beenden und den nächsten RKSV-Lebenszyklus sauber beginnen.

**Comment by andreasschiestl** [comment]
Ich frag mich wie der Anwender die Belegnummer "vergessen" kann. Muss man bei der Kasse die Belegnummer selbst mitzählen?

**Comment by espeitslo** [comment]
Sehr lustig, Das hat der Software feherhaft über webservice an Finanzonline übermittelt

**Comment by Flanelli** [comment]
Also wenn lt. @espeitslo  die Software das fehlerhaft übermittel hat warum schreibt dann @espeitslo 
dass der Kunde den Fehler machte? 
Zitat:
eine von unsere Kunden hat fehlerweise einen StartBeleg ohne die Belegnummer erstellt
