### ISSUE TITLE
Html escapes in DEP - Export

### ISSUE THREAD

**Issue by ntsjsh** [a-sit-plus/at-registrierkassen-mustercode#54]
Im aktuellen detailfragen dokument ist bei den DEP beispielexports ersichtlich, dass HTML zeichen, in diesem Fall "=" als Unicode Steuerzeichen exportiert werden (\u003d). Siehe Seite 55 im dokument.

Vermultich wird hier Gson verwendet und ohne .disableHtmlEscaping() aufgerufen.
Ist das so in Ordnung, oder sollten die Zeichen nicht escaped werden?

**Comment by asitplus-pteufl** [comment]
es wird beides kein Problem darstellen, da aber kein HTML Escaping benötigt wird, ist es wohl sinnvoller dieses nicht zu verwenden.
wird in der nächsten Version des Dokuments auch berücksichtigt (danke für die Information).

**Comment by ntsjsh** [comment]
vielen dank für die Klarstellung.

**Comment by asitplus-pteufl** [comment]
ich lasse das offen, damit man sieht dass es im dokument noch so ist (wird auch von der startseite verlinkt)

**Comment by asitplus-pteufl** [comment]
Wurde in V1.2 behoben. Diese Version wird in Kürze freigegeben.
