### ISSUE TITLE
RKSV ab 01.04. nicht eingerichtet

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#544]
Hallo,
was muss man machen in dem Fall dass es nicht gelingen ist die Kassen nach RKSV bis 01.04. einzurichten?
Warscheinlich an FON melden?

**Comment by ciscllc** [comment]
Wenn die Bestellung der Kasse / RKSV  Einheit vor dem 15.3. passiert ist, sollte nichts weitere gebraucht werden.  Auch eine Meldung an FON sehe ich nirgends als notwendig. Aber es sollte extra vermerkt werden, wenn es in 5 Jahren eine Kontrolle gibt, muss man es sicher erklären, warum man es nicht geschafft hat.

**Comment by espeitslo** [comment]
vielen dank, gibt das irgendwo ofiiziel gesetzlich geschreieben dass ich es auch so weiter geben kann?

**Comment by ciscllc** [comment]
Nachweisliche Bestellungen von Kassen bzw. Umrüstungen bis 15.3.2017, die der Lieferant nicht zeitgerecht erfüllen konnte, verbleiben vorerst straffrei.

Wenn du der "Lieferant" bist, musst dir halt etwas überlegen.

http://rksv-express.wkoratgeber.at/

**Comment by espeitslo** [comment]
Danke vielmals, das hilft viel. eigentlich haben wir als Lieferant alle bedienungen ausgefüllt, aber es gibt Probleme beim integration von unseren fiskal Software mit POS Software, da funktioniert dann nicht wie es soll. man weiss nicht was die Kunden da machen bzw installieren.

MfG
