### ISSUE TITLE
Vorgehensweise bei Neuinbetriebnahme nach fehlhafter Signaturverkettung

### ISSUE THREAD

**Issue by senton82** [a-sit-plus/at-registrierkassen-mustercode#545]
Unser Setup besteht aus einer MySQL-Datenbank, die Multikassen-Systeme abbilden kann. Die Kassen werden durch den Namen eindeutig indentifziert, schreiben Belegdaten verteilt über mehrere Tabellen und alle RKSV/DEP relevanten Daten in eine gemeinsame Tabelle, deren Einträge durch den Namen der Kasse eindeutig zugeordnet werden.

Nun hat sich leider der Fehlerteufel in die Signatur eingeschlichen, der dafür sorgt, dass in bestimmten Fällen der Einzelbeleg zwar korrekt geprüft wird, die Verkettung bzw. die Überprüfung der Verkettung mit dem A-Sit Tool nicht mehr komplett durchgeführt werden.

Wir überlegen nun, welches der richtige Weg ist, eine Neuinbetriebnahme zu machen und gleichzeitig einen minimalen Aufwand für unsere Kunden zu verursachen. Wir möchten nicht, dass historische Belege und Auswertungen verloren gehen, daher denken wir über folgenden Ansatz nach.

1) Schlussbeleg für Kasse mit Namen "XYZ" erzeugen
2) Kasse "XYZ" im FON abmelden
3) DEP für Kasse "XYZ" exportieren und sicher aufbewaren
4) DEP für Kasse "XYZ" zurücksetzen (löscht betreffende Zeilen aus der DEP-Tabelle)
5) Kasse "XYZ" mit gleichen AES-Key und Namen wieder im FON anmelden
6) Startbeleg für Kasse "XYZ" erstellen

Zusätzliche Informationen über die interne Funktionsweise:
Das DEP weist eine eigene fortlaufende Nummer auf, womit die Inbetriebnahme der Kasse mit gleichem Namen und der durch sie erstellten Belege immer zuordenbar bleibt. Die Belegnummer verfügen ebenfalls immer über eine aufsteigende eindeutige Belegnummer (vermeidet also, dass der Initialisierungsvektor im Rahmen der Signierung mit gleicher Kassen-ID und Belegnummer initialisiert werden kann).

Was haltet ihr von dieser Vorgehensweise?

Danke && LG

**Comment by Alex1130** [comment]
Punkt 4. finde ich nicht so gut : elektronische Radierbarkeit...

**Comment by MichaelSchustereder** [comment]
Den Ablauf finde ich Ok. Bei "Punkt 4" löschen wir nicht die Einträge aus der Tabelle, sondern setzen einen Archivstatus. Somit bleibt das alte DEP weiterhin exportiertbar.

**Comment by senton82** [comment]
Danke @Alex1130 und @MichaelSchustereder für eure Kommentare. Mir war bewusst, dass das Löschen wohl den heikelsten Punkt darstellt, daher war ich auf eure Kommentare gespannt - ich denke, wir werden auch die Richtung einschlagen, die Daten in der DB persistiert zu behalten und dennoch ein "neues" DEP mit gleichem Kassen-Namen weiterzuführen.

GLG

**Comment by Phoniexk** [comment]
Naja ich finde Punkt 4 nicht so kritisch. Unter Punkt 3. wird das DEP aus der alten Kasse exportiert und dann sicher aufbewahrt (Ich würde nicht nur das RKSV-DEP exportieren, sondern ALLES (Kassenjournal)).

Wenn man sich vorstellt, dass z.B. an der Kasse (Registrierkassengerät) ein Defekt in der Hardware auftritt (Eingabeeinheit wird defekt) der nicht repariert werden kann, dann muss man ja auch das alte DEP + Kassenjournal exportieren und aufbewahren... man wird ja wohl kaum die alte Kasse aufbehalten und im Abstellraum für eine Prüfung aufheben (kann man schon, aber die geht nach 5-6 Jahren sicher noch super). Deshalb finde ich das "Löschen" nicht weiter tragisch, weil ja ohnehin alle Daten exportiert wurden und jederzeit eingesehen werden können.

Herr Freitag empfiehlt hier im Forum immer wieder, dass man eine neue Kassen-ID verwenden soll. Einfach um den Lebenszykulus der neue Kasse von der alten Kassen sauber zu trennen. Wenn Sie eine neue Kassen-ID verwenden, dann kann das alte DEP problemlos im System bestehen bleiben, weil man die alte "Kasse" ja so und so außer Betrieb nimmt. Der Aufwand ist so und so der selbe. Außerdem dürfen Sie damit dann auch mit den Belegnummer wieder neu starten. 

Ich würde - wie es auch Herr Freitag immer tut - diesen Weg empfehlen. Sie trennen beide "Kassen" sauber von einander und der Kunde tut sich bei einer Prüfung mit dem Erklären leichter. Auch der Prüfer tut sich leichter wenn er zwei Kassen sieht, bei der eine davon außer Betrieb ist, als er sieht auf den ersten Blick nur eine Kasse, die aber in Wahrheit schonmal außer Betrieb genommen wurde und wieder mit selben Namen erneut läuft.

**Comment by senton82** [comment]
Danke @Phoniexk für Ihren Kommentar - ich muss eventuell dazu erwähnen, dass das Umbenennen der Kasse-Id auch meine bevorzugte Art und Weise wäre, da wie von Ihnen angeführt alle Daten vorhanden bleiben, allerdings binden wir Lizenzchecks bzw. Keys an den Kassen-Namen, womit hier ein höherer Aufwand auf unsere Kunden zukommen würde diese zu extra zu ändern. Daher auch die Idee, die alten Daten aus der Tabelle zu entfernen, nachdem diese selbstverständlich vollständig exportiert und sicher gespeichert worden sind.

**Comment by ztp-mino** [comment]
Das Problem mit neu registrieren unter gleicher Kassen-ID und mit gleichem AES-Key ist, dass man dann darauf achten muss, dass keine Belegnummer, die von der alten Kassa verwendet wurde von der neuen verwendet wird, da sonst die Sicherheit der AES Verschlüsselung des Umsatzzählers nicht mehr gegeben ist.

**Comment by Flanelli** [comment]
Wenn man das Thema EINDEUTIGE Belegnummern wirklich ernst nimmt dann kann es nie zu einem Konflikt mit identen Belegnummer geben, einerlei wie oft man eine Kassa neu einrichten muß oder will.
Man sollte eben generell eine eindeutige Belegnummer nicht als Eigenschaft einer Kassa betrachten sondern  als Eigenschaft in einem Unternehmen. Es sollte und dürfte in einem Unternehmen auf ewig und immer keine identen Belegnummern geben. Das läßt einen einfach gut schlafen und eleminiert jeglichen Erklärungsbedarf in dieser Hinsicht.

**Comment by senton82** [comment]
@Flanelli da bin ich ganz Ihrer Meinung und genauso haben wir auch das Requirement bei unserer Kasse definiert - wir hatten einige Kunden, die von anderen Systemen ungestiegen sind und jedes Jahr die Nummer zurück gesetzt haben - das hat bei uns dann einiges an Überzeugungsarbeit gebraucht :-)

Ich möchte mich nochmals bei allen Beteiligten für Ihre den Gedankenaustausch bedanken!
