### ISSUE TITLE
ECB-Mode STARTBELEG in der BMF Belegcheck-App nicht akzeptiert

### ISSUE THREAD

**Issue by icjcs** [a-sit-plus/at-registrierkassen-mustercode#547]
Bitte um Hilfe, mein QR-Code des STARTBELEGes wird in der BMF Belegcheck-App nicht akzeptiert.

FEHLER: 
"Bei der Überprüfung des maschinenlesbaren Codes wurde ein Fehler beim Abgleich des Signaturwertes mit dem öffentlichen Schlüssel festgestellt. Bitte überprüfen Sie, ob die verwendete Signatur- bzw. Siegelerstellungseinheit korrekt in FinanzOnline registriert wurde."

Ich habe zwei Varianten getestet:
Für 1.Version gab es ein Beispiel im A-Sit Forum welches bei mir korrekt funktionierte.
Version 2 wäre eigentlich genau nach Spezifikation mit Veroderung zweier 16Byte Strings und Extraktion der 5 wesentlichen Bytes daraus.
Für Umsatzzähler und IniVektor konnten alle Beispiele korrekt nachvollzogen werden! Natürlich sind auch alle bei finanzonline gemeldeten Daten überprüft worden und dort auch vorhanden.

Idee: Ev. funktioniert das AesCrypt meiner Entwicklungsumgebung nicht korrekt? Habe Ergebnisse im ASCII beigefügt, damit das geprüft werden kann.

QR Version 1 (8-Byte Usatzzähler):
_R1-AT1_01_1_2017-04-05T08:59:10_0,00_0,00_0,00_0,00_0,00_8Tkj9eNMLxo=_51A1F14A_k424yfgsjLU=_HJBffkZnKUBEKHJJYW0B/SQnJpACeh96weozNo1v8okpPcumxHzY6LpfVBzqaSNjuZ3Vbt0wVLfkT+EIK+RiiQ==

QR Version 2 (5-Byte Usatzzähler, anders verschlüsselt):
_R1-AT1_01_1_2017-04-05T09:22:13_0,00_0,00_0,00_0,00_0,00_hUn8HyA=_51A1F14A_k424yfgsjLU=_9IEdv10xLHlzB7j5rrL6MaIj96ZVmLyyqb86hKdhp2WNCxRhmGPV+ro2gClHiFmZOp9zD4D9ayf1PlGUGwOo9A==

GRUNDDATEN:
Zertifikat hex: 51A1F14A
Kassenidentifikationsnummer: "01"
Belegnummer: "1"
AES-Schlüssel (32 Zeichen): "Mein32ZeichenKassaTestschluessel"
= Benutzerschlüssel AES-256 (44 Zeichen): TWVpbjMyWmVpY2hlbkthc3NhVGVzdHNjaGx1ZXNzZWw=

QUELLCODE:
  c8Umsatz:= ::UmsZaeKod(nUmsatz_)                               // ASCII: 0, 0, 0, 0, 0, 0, 0, 0.
  c16IniVektor:= ::DEPIniV(cKassanr_, cBonnr_)                   // ASCII: 138, 8, 12, 234, 128, 157, 51, 181, 65, 243, 73, 139, 17, 99.
 // Verschlüsseln des Initialisierungsvektor im ECB-mode
  oAes:= AesCrypt():new(c32Schluessel_, CRYPT_OP_ECB)
  oAes:prepareBuffer(@c16IniVektor)  // prepare input buffer length
  c16UmsSchluessel:= oAes:encrypt(c16IniVektor)  // gibt neuen Schlüssel f. d. Verschlüsselung des Umsatzes. ASCII: 241, 57, 35, 245, 227, 76, 47, 26, 133, 4, 196, 133, 73, 252, 31, 32.

 // Verschlüsseln des Umsatzes
  // 1.Version NOK obw. Beispiel OK -->  https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/291
  //cCrypted:= charxor(c8Umsatz, c16UmsSchluessel)  // --> c,8  von c16UmsSchluessel werden die ERSTEN 8 Byte verwendet
 // So sollte es laut Spezifikation funktionieren:
  // 6.Version NOK -->
  cCrypted:= substr(charxor(replicate(chr(0),8) + c8Umsatz, c16UmsSchluessel),12,5)  // --> c,5  ASCII: 133, 73, 252, 31, 32.

  cCrypted:= bin2base64(cCrypted)   // /!\ Base64URL = nOK = b64cod(cCrypted)  // --> hUn8HyA=

Danke für jegliche Hilfe!

**Comment by rolandro** [comment]
Umsatzzähler bei 8 Byte  (8Tkj9eNMLxo=) und Verkettungswert (k424yfgsjLU=) sind korrekt.

Der Fehler hat laut Fehlermeldung mit dem Signaturwert zu tun, also ev. was falsches an die Signatureinheit gesendet (Fehler beim Generieren des Payloads), was Falsches ausgelesen oder Serienummer bei FON falsch eingetragen.

**Comment by icjcs** [comment]
@rolandro Vielen Dank!!! Konnte mit diesem Tipp, den Fehler finden. Ich habe anstatt des hash-es von header.payload diesen Wert fälschlicher Weise direkt an die Signatureinheit geschickt.
Aus der Doku V1.2, S.42, Kap. 3.1 kann man das aber auch nur schwer erahnen. Java verstehe ich aber leider nicht um die Beispiel-Sourcen zu analysieren.
