### ISSUE TITLE
Fehler in der BASE64-Kodierung

### ISSUE THREAD

**Issue by status3065** [a-sit-plus/at-registrierkassen-mustercode#548]
Hallo,

ich bekomme immer eine Fehlermeldung beim Scannen mit den BMF APP
"Fehler in der BASE64-Kodierung"

Und das ist meine Sendung (Startbeleg)

**_R1-AT2_Registrierkasse1_1_2017-04-05T14:01:16_0,00_0,00_0,00_0,00_0,00_nv0Z6p2DHk1J4enMqZpqag==_013A7F5F9AFC45EE353A6BBE58_GH5LCIc1SbY=_eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9SZWdpc3RyaWVya2Fzc2UxXzFfMjAxNy0wNC0wNVQxNDowMToxNl8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbnYwWjZwMkRIazFKNGVuTXFacHFhZz09XzAxM0E3RjVGOUFGQzQ1RUUzNTNBNkJCRTU4X0dINUxDSWMxU2JZPQ.8mP5iGDEy1/zpK-009IwqYYHYyaewrLVxbY4LBYoLWydxCmAdgMtoDeVmv7C8-AJxKds9Dz1Tnt7s22XoYR4Mw**

1. Ob '/' Zeichen erlaub ist - ich kann natürlich das nicht auf "_" wechseln (So wie bei Base64URL sein muss),  oder wo noch kan das Fehler sein
2. Falls jeman ein Beispiel auf c# hat, dann habe ich Glück
3. Falls jemand GlobalTrust mit .Net verwendet, bitte ich um Signierung Code - alles, was ich von e-commerce bekommen habe, kann ich auch euch schenken

Danke im Voraus!

**Comment by FleiTec** [comment]
Du hängst ja das ganze JWS dran.
Müsstet 
das auftrennen beim "."
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9SZWdpc3RyaWVya2Fzc2UxXzFfMjAxNy0wNC0wNVQxNDowMToxNl8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbnYwWjZwMkRIazFKNGVuTXFacHFhZz09XzAxM0E3RjVGOUFGQzQ1RUUzNTNBNkJCRTU4X0dINUxDSWMxU2JZPQ.8mP5iGDEy1/zpK-009IwqYYHYyaewrLVxbY4LBYoLWydxCmAdgMtoDeVmv7C8-AJxKds9Dz1Tnt7s22XoYR4Mw

und der dritte Teil ist das zert - also:
8mP5iGDEy1/zpK-009IwqYYHYyaewrLVxbY4LBYoLWydxCmAdgMtoDeVmv7C8-AJxKds9Dz1Tnt7s22XoYR4Mw

das musst Du base64_url_decode und dann nochmal base64_decode (ohne url)
das ergebniss dann statt dem eyJ..... dran also:


_R1-AT2_Registrierkasse1_1_2017-04-05T14:01:16_0,00_0,00_0,00_0,00_0,00_nv0Z6p2DHk1J4enMqZpqag==_013A7F5F9AFC45EE353A6BBE58_GH5LCIc1SbY=_ERGEBNIS

Lg

**Comment by lebail** [comment]
Ergänzung: In obiger Signatur (also nach dem letzten '.') liegt eine Vermischung von BASE64 und BASE64URL vor, denn es kommt sowohl das Zeichen '/' als auch das Zeichen '-' vor. Richtig wäre hier BASE64, welches neben Buchstaben und Ziffern nur '/' und '+' enthalten darf.

**Comment by status3065** [comment]
Bin gleich gekommen
Danke Kollegen!
Ich mache dann einen Bericht )

**Comment by status3065** [comment]
FleiTec
Sie haben vielleicht die Punkte im Signierten Teil übersehen

lebail
Sie haben recht
aber nun alles korrekt (meiner Meinung nach)

trotzdem Fehlermeldung ist 1:1

_R1-AT2_Registrierkasse1_1_2017-04-06T06:11:49_0,00_0,00_0,00_0,00_0,00_nv0Z6p2DHk1J4enMqZpqag==_013A7F5F9AFC45EE353A6BBE58_GH5LCIc1SbY=_eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9SZWdpc3RyaWVya2Fzc2UxXzFfMjAxNy0wNC0wNlQwNjoxMTo0OV8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbnYwWjZwMkRIazFKNGVuTXFacHFhZz09XzAxM0E3RjVGOUFGQzQ1RUUzNTNBNkJCRTU4X0dINUxDSWMxU2JZPQ.AuXMt5m4CUHmpOc2vD9+aXwqJ2YRT3i1yD3SPZHkudEubYuhRe7qx8Urk5RnEslsPY/5/PrOqAY6bokU73Fzww

Wenn Ihr mir sagen könntet, dass BASE64 korrekt ist, dann muss ich auf einen anderen Grund überlegen

**Comment by FleiTec** [comment]
Wies aussieht ist die Certid in Hex nicht korrekt?
013A7F5F9AFC45EE353A6BBE58
Kann diese nicht in Nummern umwandeln siehe http://www.binaryhexconverter.com/hex-to-decimal-converter

**Comment by FleiTec** [comment]
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9SZWdpc3RyaWVya2Fzc2UxXzFfMjAxNy0wNC0wNlQwNjoxMTo0OV8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbnYwWjZwMkRIazFKNGVuTXFacHFhZz09XzAxM0E3RjVGOUFGQzQ1RUUzNTNBNkJCRTU4X0dINUxDSWMxU2JZPQ._AuXMt5m4CUHmpOc2vD9+aXwqJ2YRT3i1yD3SPZHkudEubYuhRe7qx8Urk5RnEslsPY/5/PrOqAY6bokU73Fzww_

nur den letzten Teil verwenden
also AuXMt5m4CUHmpOc2vD9+aXwqJ2YRT3i1yD3SPZHkudEubYuhRe7qx8Urk5RnEslsPY/5/PrOqAY6bokU73Fzww
und eben noch codieren und dann den codierten teil anhängen--
OHNE die ersten beiden Teile
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9SZWdpc3RyaWVya2Fzc2UxXzFfMjAxNy0wNC0wNlQwNjoxMTo0OV8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbnYwWjZwMkRIazFKNGVuTXFacHFhZz09XzAxM0E3RjVGOUFGQzQ1RUUzNTNBNkJCRTU4X0dINUxDSWMxU2JZPQ

**Comment by status3065** [comment]
Danke, FleiTec!

Aber ich hab verwirrt.

Ich kriege gleich nach Signieren byte[64] array

diese codiere ich in Base64url (kurz "abc12-3_d")
dann base64Url codiere ich in Base64 (kurz "abc12/3+d==")
dann beise "=" am Ende (abc12/3+d)
und hänge als einen 3. Teil zur header und payload

fürchte, dass das schon falsch ist, und ich habe etwas verloren

Sag mir bitte, was meinst du unter "und eben noch codieren "
auf was codieren?

Danke, ich fühle mich echt dumm

**Comment by status3065** [comment]
jetzt was nicht passt - verstehe [berhaupt nicht

hex certificateid ist tüpisch globaltrast certificate 

_R1-AT2_Registrierkasse1_1_2017-04-06T12:39:42_0,00_0,00_0,00_0,00_0,00_nv0Z6p2DHk1J4enMqZpqag==_013A7F5F9AFC45EE353A6BBE58_GH5LCIc1SbY=_eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9SZWdpc3RyaWVya2Fzc2UxXzFfMjAxNy0wNC0wNlQxMjozOTo0Ml8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfbnYwWjZwMkRIazFKNGVuTXFacHFhZz09XzAxM0E3RjVGOUFGQzQ1RUUzNTNBNkJCRTU4X0dINUxDSWMxU2JZPQ.alRBRVhrNUprNjlHZFRXTHhjT2Q3OUdsM3NlVEY4dkViSkNXY09obkJmYUdfeU9iYjFwZ2pWLTFfTDJicy1HYjBfR2ZHX0loS3d0RUhNSkIwT2tsQkE

kann vielleicht FIN einfach die Signatur nicht decodieren?

**Comment by ErichFreitag** [comment]
Der Inhalt der Signatur ist falsch. Sie haben hier den kompletten DEP-Eintrag in das Signaturfeld geschrieben. Hierher gehört die Signatur über die davor liegenden Inhalte des maschinenlesbaren Codes.

**Comment by status3065** [comment]
Danke Erich!!!
Das ist weil ich ManualJWSModule verwende. Die Module schieckt header.payload.footer und ich war verwirrt

Ich wusste nicht, was returniert eine externe JWS biblioteke (so wie jose). Hab gedacht, dass genau so wie ich in meinem Beispiel gezeigt habe. Jetzt klar. Das ist Falsch gewesen.

Nun versuche ich das wieder

Danke!

**Comment by status3065** [comment]
Hallo alle!

Ich würde das Thema schliessen
Der Grund des Gesprächs ist folgende:
ich verwende ManualJWSModule, wo ich alles selber bearbeiten muss.
Von here kommt mein Unverständnis, welche Inhalt hat Signierteteil, weil die Methode signMachineCodeRepOfReceipt returniert den ganzen String vom Signaur

Aber ich brauche nur **byte[] CryptoUtil.convertDEREncodedSignatureToJWSConcatenated(byte[] signatureResult)** - byte[64] Array

Dann kodiere ich das in base64string und hänge als der letzte Teil von Startbeleg QR Code

Danke alle!
Hoffe, hilft das Thema noch Jemanden
