### ISSUE TITLE
Umsatzzähler bei Storno einer gemischten Gutschrift

### ISSUE THREAD

**Issue by tomw1808** [a-sit-plus/at-registrierkassen-mustercode#549]
Ich weiß, die Issues hier dienen hauptsächlich technischen Probleme, trotzdem kann mir jemand vielleicht weiterhelfen...

Man nehme an...

Produkt 1: 100€ mit 10% MwSt.
Produkt 2: 100€ mit 20% MwSt.
Gesamtrabatt: 100€.

USZ: 10%: 100, 20%: 100, 0%: -100. USZ-gesamt: 100 

Warum 0% -100? Seite 33 von https://www.bmf.gv.at/egovernment/projekte/registrierkassen/20160905-Detailfragen-RKSV-V1.2.pdf?5te3qd

So... Nun kommt der Kunde zurück und will Produkt 1 nicht mehr und will es gerne zurückgeben.
Er bekommt Geld zurück, nämlich 50€ zu %20 (hoffe ich) ... und jetzt kommts: 50€ zu 0% oder nicht, da:
Gutschriften nicht im USZ eingetragen sein dürfen.

https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/Registrierkassen.html#heading_Wie_sind_der_Verkauf_und_das_Einloesen_von_Gutscheinen_im_Zusammenhang_mit_der_Registrierkasse_zu_behandeln_

Wie ist der USZ hier zu befüllen bei diesem Storno?

Danke!

**Comment by rolandro** [comment]
-50 bei USZ und -50 bei 10% wenn er Produkt 1 (das hat 10% Mwst in deinem Beispiel) zurück gibt und eben 50.- ausbezahlt bekommt.

**Comment by tomw1808** [comment]
10% meinte ich... war ein langer tag.

danke jedenfalls. Ich nehme mit: wird aliquot gleich wieder auf die steuersätze zurückgerechnet. Danke!
