### ISSUE TITLE
Rechnung und Beleg auf einem Ausdruck

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#551]
Hallo,

aus diversen Gründen habe ich mich entschieden in meiner Lösung die Rechnungen (Ziel) und Belege immer als  getrennte Objekte und getrennte Dokumente zu führen. Die Zielrechnungen werden meistens mit mehreren Belegen beglichen (verweiss auf die Zielrechnung). Es gibt aber eine kleinere Anzahl an Kunden die überwiegend Rechnungen sofort und vollständig bezahlt bekommen und in diesem Fall wäre günstig wenn man nicht zwei Dokumente drücken wurde, sondern die Rechnung und Beleg auf einem Zettel wären.

Spricht etwas dagegegen wenn in solchen Situationen auf einer Rechnung (enthält alle Rechnungsmerkmale) noch QR-Code, Beleg-Nr, Datum+Uhrzeit usw. ausgegeben werden. Das Dokument würde dann die Bezeichnung BELEG tragen? Gespeichert werden die Informationen nach wie vor getrennt in Rechnungs- bzw. im Belegobjekten, nur auf dem Zettel werden sie zusammen erscheinen.

Die Software wurde praktisch Belege in zwei Formen ausgeben können, einmal als eigenständiges Dokument mit einem Verweiss auf die Zielrechnung (enthält Steueraufteilung) und als Teil der Zielrechnung.

Danke

**Comment by theshadowtwentyseven** [comment]
Wir machen das bereits heute so: abhängig von der Kundenkonfiguration kann entweder nur ein Bon oder Bon & Rechnung in einem gedruckt werden. Solange alle für eine Rechnung notwendigen Angaben vorhanden sind spricht nichts dagegen.

Obiges ist natürlich eine unverbindliche Aussage gemäß unserer Recherche, Rechtsanwälte oder Steuerberater sind wir einfach nicht :)

**Comment by andreasschiestl** [comment]
Machen wir auch so. Im Einzelhandel ist meistens so das der Kassenbon gleichzeitig Beleg und Rechnung ist. Hier ein Beispiel wie es bei uns aussieht:

![rechnung](https://cloud.githubusercontent.com/assets/8170218/24727039/d929afdc-1a54-11e7-91c6-c256be74978b.png)

Wird die Rechnung nicht oder nicht zur gänze bezahlt und der Kunde zahlt den Rest später wird einen Zahlungsbeleg. Ist die Zahlungsart dabei als Barzahlung zu werten kommt wieder ein RKSV Beleg unten dran. Ist bei uns intern auch als eigenes Objekt gespeichert. Wobei wir aber nie einen RKSV Beleg alleine ausdrucken (Start-, Monats- und Jahresbelege ausgenommen) sondern immer in Verbindung mit einer Rechnung oder einem Zahlungsbeleg (was die meisten einfach als Beleg bezeichnen würden)

**Comment by AlgoLinz** [comment]
Danke für die Antworten

mfg
