### ISSUE TITLE
Frage bezüglich Datenexport der Belegdetails

### ISSUE THREAD

**Issue by Skerge12** [a-sit-plus/at-registrierkassen-mustercode#554]
Guten Tag,
soweit mir bekannt ist müssen zusätzlich zu den Signaturen des DEPs im JWS Format noch 
die einzelnen Belegdetails exportiert werden.
Wie kann / soll dieser Export aussehen ?

Wäre eine CSV Datei erlaubt wo die Datensätze  z.B. wie folgt aufgebaut sind:

Record 1: 
Verkaufsdatum , Verkaufszeit , Menge1 , Produktbezeichnung1 , Produktpreis1 ,  Menge2 , Produktbezeichnung2,  Produktpreis2 ,  Menge3 , Produktbezeichnung3,  Produktpreis3  ;

Record 2: 
Verkaufsdatum , Verkaufszeit , Menge1 , Produktbezeichnung1 , Produktpreis1 ; 

usw ...

Danke für die Info

**Comment by andreasschiestl** [comment]
Ich nehme an du meinst das Kassenjornal das laut den Kassenrichtlinien 2012 vorgeschrieben ist. Hierbei ist prinzipiell alles zu exportieren was die Kasse aufzeichnet. Gibt aber große Unterschiede von Kasse zu Kasse, nicht zuletzt weil kein Format für diesen Export vorgeschrieben ist.

Was ich so hier im Forum gelesen habe, hängt es auch immer ein wenig vom Finanzprüfer ab. Manche sind wohl besser ausgestattet und können mit allen möglichen was anfangen und andere beharren auf einer CSV-Datei.

Auch was in der CSV-Datei steht ist oft sehr unterschiedlich. Ich habe schon Kassen gesehen (eine macht in letzter Zeit viel Werbung auf Pro7/Sat1/Puls4) bei welchen der CSV-Export prinzipell die Daten aus dem maschinenlesbaren Code (Also Beträge nach Steuersätzen, Belegnummer, Datum/Uhrzeit usw.) aber in extra Spalten ergänzt um eine einzige zusätzliche Spalte mit den Artikelbezeichnungen, ohne irgendwelche Information über Mengen oder Stückpreise.

**Comment by Skerge12** [comment]
Vielen Dank für die Info :)

**Comment by Flanelli** [comment]
Natürlich wäre es sinnvoll wenn man - falls es nicht ohnehin schon so besteht - im Zuge der RKSV-Adaptierungen auch das 2012-er DEP sprich 2016-er DEP oder wie auch immer man das "normale" DEP nun bezeichnen möchte im JSON-Format erstellt auch wenn das Format dafür DEFINITIV NICHT
vom Gesetzgeber vorgeschrieben wird. Es ist bis dato ein FREI wählbares Format.

Nachdem aber der Gesetzgeber das RKSV-DEP im JSON-Format verlangt sollte sich ein Finanzprüfer dcoh lieber 3 Mal überlegen ob er auf einer CSV-Datei "beharrt". Auch wenn man sich mit den Prüfern nicht unbedingt anlegen sollte - was diesen Punkt betrifft haben auch Finanzprüfer schlicht und einfach die gültigen Gesetze zu befolgen und daher JEDES, mit gängigen EDV-Technischen Werkzeugen lesbares Format zu akzeptieren - und schon ganz besonders wenn dieses sogar dem Format des neuen RKSV-DEP entspricht.

Weitaus relevanter sind die Inhalte des 2013/2016/noemalen DEP.
Da sollte sich der Hersteller doch auch alle Fälle an die Vorgaben halten aber wenn man ein wirklich ernstzunehmendes DEP erstellt dann beinhaltet das ohnehin weitaus mehr Informationen und Daten als die minimalst vorgegebenen lt. BMF

**Comment by Flanelli** [comment]
@Skerge12 Ihr skizzierter Dateninhalt sollte m.E.  zumindest unbedingt noch die Kassa-ID und die Belegnummer enthalten.

**Comment by Skerge12** [comment]
Vielen Dank für die Infos.
Dann werde ich auch das gleich im JSON Format erledigen.

**Comment by andreasschiestl** [comment]
JSON hat gegenüber CSV auch den Vorteil, dass es sich besser strukturieren lässt.
