### ISSUE TITLE
Java Fehlermeldung

### ISSUE THREAD

**Issue by marvintappauf** [a-sit-plus/at-registrierkassen-mustercode#557]
Hallo,

ich bekomme immer eine Fehlermeldung beim Scannen des Startbeleges
mit der BMF Belegcheck app

Prüfergebnis

Der verloegende Belg kann nicht gegrpüft werden, da zur Erstellung eine nicht zu Ihrem Unternehmen registrierte Signatur- bzw. sieglerstellungseinheit verwendet wurde oder Fehler aufweist, die über FinanzOnline unter dem Punkt: Eingabe > Registrierkassen > Liste aller übermittelten Belege abgerufen werden können.

Und das ist meine Sendung (Startbeleg)

_R1-AT1_Android1_10100000_2017-04-11T12:23:59_0,00_0,00_0,00_0,00_0,00_9r6JXUk1Jf4=_139980772_Zi75EYkABqA=_qVyqsEgt119KPZ6WTp9qCsM0nsBl2rJE/WHiOOywZ+An2LAEwIoY1IagUzmeS8Nc4q7XJ2l+AF2AJT//mBj/3g==

 Ich benutzte Java und A-Trust Smartcard

Danke im Voraus!

**Comment by lebail** [comment]
Könnte es sein, dass Sie die Zertifikats-Seriennummer **dezimal** angegeben haben? Für diese ist nämlich das **Hexadezimal**-Format vorgeschrieben (ohne Vornullen).

**Comment by WienerroitherM** [comment]
Ist genau, wie lebail sagt. Laut A-Trust Verzeichnisdienst ist das die dezimale Angabe der Zertifikatsseriennummer. Hier sollte in diesem Fall "857EFE4" im maschinenlesbaren Code als Zertifikatsserienummer enthalten sein.

**Comment by marvintappauf** [comment]
Danke für die schnelle Antwort

Hat jetzt funktioniert.

Wünsche noch einen schönen Tag.

mit freundlichen grüßen
