### ISSUE TITLE
Umsatzzaehler Problem

### ISSUE THREAD

**Issue by McCodie** [a-sit-plus/at-registrierkassen-mustercode#558]
Kann hier mal wer mit dem Umsatzzaehler weiterhelfen?

Ich verstehe nicht was hier nicht passen sollte

      "DECRYPTED_TURNOVER_VALUE" : "20100446949960",

Wenn ich diverse Werte aus den Beispielen verwende stimmt der Turnover counter aber

[cryptographic_container_json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/918736/cryptographic_container_json.txt)
[DEP_json.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/918737/DEP_json.txt)
[test_dep.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/918738/test_dep.txt)

**Comment by ErichFreitag** [comment]
Ich verstehe nicht, warum das passen sollte.

Sie machen einen Umsatz von 46,80 EUR nach dem Startbeleg (Stand Umsatzzähler 0) und der entschlüsselte Umsatzzähler ergibt im Prüftool 20100446949960 Cent anstelle des Sollwerts 4680 Cent. Entweder ihre Verschlüsselung ist falsch oder der AES-Key ist falsch.

**Comment by McCodie** [comment]
Und ich verstehe nicht warum es nicht passen sollte.
Nehme ich folgende Werte aus dem anderen Beitrag dann bekomme ich die gleichen Ergebnisse wie in dem anderen Beitrag.
Ich frage mich wirklich was zum Teufel da los ist. Selbst wenn ich den AES Key hart kodiere stimmt es nicht. 

04-12 21:23:34.485 26482-26482/com.accounting V/ANDROID: HASH INPUT: CashBox0100000001
04-12 21:23:34.485 26482-26482/com.accounting V/ANDROID: USING AES KEY WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=
04-12 21:23:34.487 26482-26482/com.accounting V/ANDROID: LONGVALUE+ 5509
04-12 21:23:34.487 26482-26482/com.accounting V/ANDROID: Length: 4
04-12 21:23:34.488 26482-26482/com.accounting V/ANDROID: Generated Turnover counter: ByWsK8idWYI=
04-12 21:23:34.488 26482-26482/com.accounting D/ANDROID: Umsatzzaehler: ByWsK8idWYI=

----

https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/91

KassenID: "CashBox01"
Belegnr: "00000001"
Umsatz: 55,09
AES-Key (base64 encoded): "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU="

IV (ersten 16 byte): 3e 04 75 88 e2 0f 53 f9 2b bd f4 a9 c0 12 40 0d
Umsatz als Byte Array: 00 00 00 00 00 00 15 85
Ergebnis: "ByW5rsidWYI="

**Comment by lebail** [comment]
Nur zur Info: Die beiden Werte, die Sie in Ihrem letzten Beitrag vergleichen, sind **nicht** gleich.

ByW**sK8**idWYI=
ByW**5rs**idWYI=

**Comment by McCodie** [comment]
Danke das hat geholfen!

Und schon kommt das naechste Problem

"CHAINING_INPUT" : "eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9LYXNzZTY2Nl9LYXNzZTY2Ni1STi0xXzIwMTctMDQtMTNUMTE6Mjk6MDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwXzQvQ2ZUdDlHMkk4PV80MjBhNWNmOF9wMS9XQlN3NGlTZz0.12ggE3o_s7LiMsazT-J0MvwHSy0LboHeyGyzd20PZGpFzvSnZIuSF3xO7DT0dyVgJMph__ywsTvj4KkzSlQpspA"

Wobei der Input eigentlich folgendes sein sollte:
"eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9LYXNzZTY2Nl9LYXNzZTY2Ni1STi0xXzIwMTctMDQtMTNUMTE6Mjk6MDBfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwXzQvQ2ZUdDlHMkk4PV80MjBhNWNmOF9wMS9XQlN3NGlTZz0.12ggE3o/s7LiMsazT+J0MvwHSy0LboHeyGyzd20PZGpFzvSnZIuSF3xO7DT0dyVgJMph//ywsTvj4KkzSlQpspA=

Muss + durch - ausgetauscht werden und / durch underscore?

Ich sehe das auch auf Seite 31/69 in den Detailfragen RKSV V1.2

Frage mich nur warum ich dort nichts davon erwaehnt sehe.

**Comment by ErichFreitag** [comment]
Sie müssen auch die Grundlagen dazu lesen, sprich die RKSV und deren Detailspezifikation.

Der QR-Code ist BASE64 codiert, der DEP-Export ist BASE64URL codiert. Im DEP-Export sind gemäß JWS-Standard die Padding-Zeichen zu entfernen.

**Comment by McCodie** [comment]
ok super jetzt funktioniert alles. Vielen Dank fuer die Hilfe!
