### ISSUE TITLE
 Detailfragen page 55, chapter 5, Gruppierung der Belege nach Signaturzertifikaten

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#56]
In the text on the page 55, there is small mistake, at first there is mentioned that for documents 21 - 30  is used certificate 1 and in following text is used certificate 3. Probably there should be certificate 3 in both places in the text.

![mistakeaustria](https://cloud.githubusercontent.com/assets/16401050/14157449/59f3adec-f6cb-11e5-87cc-a6e1a1ec1cfe.jpg)

**Comment by asitplus-pteufl** [comment]
Thanks for the hint, the "Signaturzertifikat 3" should be replaced with "Signaturzertiikat 1" (could also be the other way round, both options are possible).
As stated in the other answer, it is perfectly fine to switch between signature creation devices (please read the details in this other answer).

**Comment by asitplus-pteufl** [comment]
I will keep that open as long as it is not fixed within the document.

**Comment by slavok1** [comment]
OK, I am sorry for early closing.

**Comment by asitplus-pteufl** [comment]
This is fixed in V1.2, which will be release very soon.
