### ISSUE TITLE
FON Webservice art_uebermittlung T(est :( 

### ISSUE THREAD

**Issue by FriNagy** [a-sit-plus/at-registrierkassen-mustercode#560]
Hallo!
ich versuche mal die RegKassen-Webservice zu nützen, mit curl und teste es mit SOAP UI

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rkdb="https://finanzonline.bmf.gv.at/rkdb">
   <soapenv:Header/>
   <soapenv:Body>
      <rkdb:rkdbRequest>
         <rkdb:tid>61779540b308</rkdb:tid>
         <rkdb:benid>WSBEN1957</rkdb:benid>
         <rkdb:id>HSR4EsbgIakmTli1CkLLgBf3</rkdb:id>
         <rkdb:art_uebermittlung>P</rkdb:art_uebermittlung>
         <rkdb:rkdb>
            <rkdb:paket_nr>1</rkdb:paket_nr>
            <rkdb:ts_erstellung>2017-04-14T19:38:27</rkdb:ts_erstellung>
            <rkdb:belegpruefung>
               <rkdb:satznr>2</rkdb:satznr>
               <rkdb:beleg>_R1-AT1_RegK-IBK-D9C_BEL2_2017-04-14T19:38:27_1,20_0,00_0,00_0,00_0,00_dWkJ20uDszo=_47E1F53C_..........wsIdA==</rkdb:beleg>
           </rkdb:belegpruefung>
         </rkdb:rkdb>
      </rkdb:rkdbRequest>
   </soapenv:Body>
</soapenv:Envelope>
```
bitte wie kann es sein, 
dass wenn es in "<rkdb:art_uebermittlung>"  T  (also Test steht) ich eine menge Fehler bekomme, 

```
                 <ns5:verificationName>Prüfergebnis - Kasse</ns5:verificationName>
                  <ns5:verificationTextualDescription>Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren 
                  <ns5:verificationState>FAIL</ns5:verificationState>
                  <ns5:verificationResultDetailedMessage>Der vorliegende Beleg konnte nicht gültig geprüft werden, da die zur Belegerstellung verwendete Signatur- bzw. Siegelerstellungseinheit laut FinanzOnline nicht auf Ihr Unternehmen registriert wurde. Bitte überprüfen Sie die korrekte Registrierung der                                     <ns5:verificationResultList>
                     <ns5:verificationResult>
                        <ns5:verificationId>MATCH_COMPANY</ns5:verificationId>
                        <ns5:version>1</ns5:version>
                        <ns5:verificationName>Überprüfung ob angemeldetes Unternehmen mit Unternehmen                         <ns5:verificationTextualDescription>Es wird überprüft ob das angemeldete Unternehmen 
                        <ns5:verificationState>FAIL</ns5:verificationState>

```

wenn ich auf P (Produktion) umstelle, funktioniert es aber?! 

```
                  <ns5:verificationId>VERIFICATION_FROM_CASHBOX</ns5:verificationId>
                  <ns5:version>1</ns5:version>
                  <ns5:verificationName>Prüfergebnis - Kasse</ns5:verificationName>
                  <ns5:verificationTextualDescription>Bei der Belegprüfung wird untersucht, ob die Vo...hrt.</ns5:verificationTextualDescription>
                  <ns5:verificationState>PASS</ns5:verificationState>
                  <ns5:verificationResultDetailedMessage>Der vorliegende Beleg wurde gesetzeskonform von einer erfolgreich in Betrieb genommenen Registrierkasse erstellt.</ns5:verificationResultDetailedMessage>
                  <ns5:input>
                     <ns5:RECEIPT xmlns="https://finanzonline.bmf.gv.at/rkdb">_R1-AT1_RegK-IBK-D9C_BEL2_2017-04-14T19:38:27_1,20_0,00_0,00_0,00_0,00_dWkJ20uDszo=_47E1F53C_LEt0mE......DwsIdA==</ns5:RECEIPT>
                  </ns5:input>

```

ist es nicht erlaubt zu testen wenn schon Startbeleg erstellt???

**Comment by Phoniexk** [comment]
Beim FON-Webservice ist das Testsystem vom Produktivsystem vollständig getrennt. Sprich alle Eingaben im Testsystem sind unabhängig von den Eingaben im Produktivsystem. D.h. Auch wenn die Kasse+Zertifikat+Startbeleg bereits im Produktivsystem laufen, dann kann man trotzdem nochmal im Testsytem prüfen. Also nein: Testen können Sie auch wenn der Startbeleg im Produktivsystem getestet wurde.

Wichtig ist dabei, dass Sie alle Schritte auch im Testsystem durchführen, sprich eine im Produktivsystem registrierte Kasse/Zertifikat hilft nichts für das Testsystem. Sie müssen im Testsystem nochmals Kasse + Zertifikat registrieren, erst dann geht der Startbeleg durch. Im Zweifel nochmals Kasse + Zertifikat im Testsystem außer Betrieb nehmen.

**Comment by FriNagy** [comment]
vielen Dank! es erklärt einiges...

es würde mir zwar besser gefallen, wenn wir auch in Produktivsystem Testübermittlungen prüfen könnten...  ( wie zB. bei FON UVA-Meldung, Dateiübermittlung WebService <fil:uebermittlung>T</fil:uebermittlung>) 
aber es ist halt mal so...

gibt es eine möglichkeit ein Testsystem direkt im FinanzOnline anlegen, oder geht es nur mit Web-Service?

**Comment by Phoniexk** [comment]
Nein die Testübermittlungen sind nur mit dem Webservice möglich. Man braucht ja aber nur 1:1 alle Vorgänge mit dem "T" Flag machen, d.h. Kasse/Zertifikat identisch im Test/Produktivsystem anmelden, dann lassen sich alle Prüfungen sowohl im Test- als auch im Produktivsystem durchführen.

**Comment by FriNagy** [comment]
Danke
