### ISSUE TITLE
Pay in fehlerhaft fiskalisiert

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#564]
Hallo,

eine von unsere Kunden hat fehlerhaft (Software Fehler) die Geldlade Aufladung die erste 10 Tage fiskalisiert und zwar mit 0% MwSt.

Der Fehler wurde soweit aufgehoben, dies wird jetzt korrekt gepflegt, aber die Frage die sich jetzt erstellt ist:
Müssen jetzt alle Kassen erneut mit eine neue Identifikationsnummer registriert werden (selbstverstendlich mit eine vorherige Datensicherung) oder kann man es so lassen und die Kassen normal weiter verwenden?

Vielen dank im voraus

MfG

**Comment by ErichFreitag** [comment]
Die Einlage von Wechselgeld (= Geldlade Aufladung?) darf freiwillig im 0%-Steuersatz signiert werden, es ist daher kein Fehler. Wenn sie es dokumentieren und auch in einigen Jahren noch wissen und begründen können, lassen sie die Kasse weiterlaufen. Wenn sie einen sauberen Schnitt machen möchten nehmen sie die Kassen außer Betrieb und neu in Betrieb. Sie dürfen dabei die selben Kassen-ID verweden, ich empfehle immer die Verwendung einer neuen Kassen-ID, um die Lebenszyklen sauber zu trennen.

**Comment by espeitslo** [comment]
Danke vielmals für die Antwort!

MfG
