### ISSUE TITLE
Verifizierungstool und mehrere Zertifikate

### ISSUE THREAD

**Issue by Muhlich** [a-sit-plus/at-registrierkassen-mustercode#566]
Hallo,

wir wollen gerade den Fall des Zertifikatwechsels nachstellen. Laut Anlage , Abschnitt 3 dürfen wir für verschiedene Zertifikate die Inhalte der Belege-Kompakt in die Belege-Gruppe-arrays schreiben. Der Materialcontainer erlaubt derzeit nur die Konfiguration von einem AES-256  Key samt Zertifikat. Damit wird natürlich das Datenexportformat nie vollständig verifiziert. Gibt es da eine Möglichkeit das zu beheben?

viele Grüße

**Comment by ErichFreitag** [comment]
a) AES-Schlüssel dürfen sie pro Kasse nur einen haben, das ist schon so OK

b) Zertifikate können sie mehrere eintragen, indem sie den Abschnitt duplizieren

**Comment by Muhlich** [comment]
Hallo,

vielen Dank für die rasche Antwort. Das heißt wir würden für das andere Zertfikat einen weiteren

certificateOrPublicKeyMap-Eintrag im Container

setzen und müssten nur sicher stellen, dass das selbe Passwort verwendet wird?

**Comment by ErichFreitag** [comment]
Zertifikat: korrekt, siehe A-SIT-Detailspezifikation V1.2 Seite 65/66.

Was meinen sie mit Passwort?

**Comment by Muhlich** [comment]
Hallo,

vielen Dank! Zu dem Passwort: Bisher haben wir zu Testzwecken neben dem Kartentausch auch das Passwort geändert, das muss dann natürlich ausgesetzt werden.

**Comment by ErichFreitag** [comment]
Sie meinen den PIN für eine SmartCard? Der hat aber mit dem Prüftool nichts zu tun und ist auch bezüglich Zertifikatsverwendung egal.

**Comment by Muhlich** [comment]
Nur zur Erklärung: Wir haben den AES Key für unsere Testanwendungen pro Signaturkarte geändert. D.h der AES-Key für den Umsatzzähler ist pro Karte neu erzeugt worden, das wird dann ertsmal ausgeschaltet.
