### ISSUE TITLE
Startbeleg fehlerhaft

### ISSUE THREAD

**Issue by taich001** [a-sit-plus/at-registrierkassen-mustercode#567]
Die Kasse hat einen Startbeleg erstellt, der von FON als fehlerhaft abgelehnt wird.

Fehlermeldung in FON ist: 
Belegnummer nicht ermittelbar

Hier sind die Daten des Startbeleges:
_R1-AT1_1_1_2017-04-19T09:40:33_0,00_0,00_0,00_0,00_0,00_3r6Bx+Pwpz2tQWMqilD9Fw==_50E94351_a4ayc/80/OE=_HJRDEXFjvOYxLSPwm/xxYwWUnBLv3G52ofopwEEAFJR22MURm660rK0AoC5UJCMYWLKZx79UzhxCkA6sheARkg==

Hat jemand eine Ahnung wo hier das Problem liegt?
Vielen Dank für die Hilfe
Thomas Aichinger

**Comment by WienerroitherM** [comment]
Die genaue Fehlermeldung in FON wäre noch hilfreich (Bekommt man mit Klick auf "Belegnummer nich ermittelbar".
Hier dürfte die Prüfung schon im BASICCONSTRAINTS Teil scheitern - beim maschinenlesbaren Code fällt mir mit freiem Auge jetzt aber nichts auf. Kann es sein, dass der Belegerstellungszeitpunkt nach dem Prüfzeitpunkt liegt? Wenn der Belegerstellungszeitpunkt in der Zukunft (ausgehend von Prüfzeitpunkt) oder vor 1.9.2015 liegt, scheitert auch die BASICCONSTRAINTS Prüfung.

**Comment by taich001** [comment]
Ja stimmt, die Uhr der Kasse ist um 2 Minuten vor gegangen.
Danke für den Hinweis.
