### ISSUE TITLE
Detailfragen-RKSV-V1.1.pdf  - not trivial Examples in chapter 2.5.1

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#57]
It would be nice to have some better explanations for several Examples which are included inside the document and are not trivial. Especially for Sales counter update.

In chapter 2.5.1 there are several examples which need some better description.
**Beispiel – Standardbeleg – Buchungen mit Rabatt/Gutschrift**
- in this example there are value -5,00 in 4th VAT group; 
- I know only one way, when may be negative VAT group in a transaction (repurchase of the returnable packaging e.g. bottles)
Do I understand this example correct or there are any other possibilities how it can be explained?

**Beispiel – Stornobeleg – Storno einer Gutschrift/eines Rabatts**
 - this example is for me unknown at all in the real practice. It seems to be as Refund of previous Refund which seems it can be replaced by Standardbeleg as it is shown at example "Beispiel – Standardbeleg – typische Buchungen" (the rule 2 negativ are 1 positive can be applied in my opinion).
Is any better explanation for this examples?  Is my understanding correct?

Other examples in 2.5.1 chapter are clear.

**Comment by asitplus-pteufl** [comment]
**Beispiel – Standardbeleg – Buchungen mit Rabatt/Gutschrift**
yes that was exactly the "bottle" example.

**Beispiel – Stornobeleg – Storno einer Gutschrift/eines Rabatts**
This example will not often occur in real situations, your are right, this simulates the refund of a refund. 

In theory all possible combinations of tax-values (negative/plus) could be combined on "Standardbelegen" and "Stornobelegen". It might even be possible that the turnover counter is negative (e.g. when you do a refund on a newly initialised cash register). However, as you mention many of these scenarios will not occur in real situations. The test-suites of V0.6 also focus on all possible transitions between different receipt types, but of course might not cover realistic scenarios. For version 0.7 additional examples (registration, etc.) will be explained in detail (also the test cases will be adapted). For know, if your cash register manages to create the test-case receipts in the same manner, then it should already cover all possible scenarios of the RKSV.

Regarding the explanation of the examples: The document you are referring to is only intended to cover the technical aspects of the RKSV. All organisational and legal aspects are covered in the FAQs of the BMF/WKO and the BMF "Erlass-Dokumente".
