### ISSUE TITLE
Karten / Zertifikate

### ISSUE THREAD

**Issue by FriNagy** [a-sit-plus/at-registrierkassen-mustercode#572]
Hallo!

ich habe da einige Karten (a.sign RK Chip) die ich leider schon registriert habe, die aber jetzt nicht mehr brauche, weil die Kunden doch lieber RK-Online verwenden.

Kann mann die Karten irgendwie löschen um neu zu verwenden oder sind die zu vergessen?

-------------------------------------------------------------------------

wenn ich die Zertifikate anschaue zB. mit mein RegkP -si https://github.com/FriNagy/RegKP sieht mann dass sie spätestens in 5 Jahren ablaufen, werden wir da wieder neue Karten bzw. ON_Line Konten kaufen und installieren müssen ??? weißt da jemand was?

-------------------

**Comment by andreasschiestl** [comment]
Die RK Online Konten haben eine Laufzeit von 5 Jahren und sind auf jedenfall zu erneuern, das heißt 4€ Kosten (sofern die Kosten gleich bleiben) und neuer Username und neues Passwort.

Die Karten können über die 5 Jahre hinaus verwenden werden, da die RKSV ausdrücklich abgelaufene Zertifikate erlaubt (ändert sich aber möglicherweise).

Was das Löschen der Karten betrifft kann ich leider nicht weiter helfen da wir keine verwenden. Am besten bei A-Trust selbst fragen.

**Comment by FriNagy** [comment]
Danke!

> da die RKSV ausdrücklich abgelaufene Zertifikate erlaubt

steht es irgendwo?

**Comment by FriNagy** [comment]
Danke nochmals...
