### ISSUE TITLE
Public Key auslesen

### ISSUE THREAD

**Issue by seblau** [a-sit-plus/at-registrierkassen-mustercode#576]
Gibt es eine Schnittstelle um den Public Key, der für die Verifizierung der Signatur verwendet wird, aus einem Registrierkassensystem auszulesen? Ich möchte damit dann in weiterer Folge die Signatur eines Belegs überprüfen.
Oder ist es möglich den Public Key in Finanz Online einzusehen?

**Comment by Phoniexk** [comment]
Ich vermute Sie sind aufgrund der Fragestellung kein Kassenhersteller. Prinzipiell kommt es auf das jeweilige Registrierkassensystem an. Möglicherweise bietet das Kassensystem eine Möglichkeit zur Anzeige der Zertifikatinformationen, kommt aber darauf an ob der Hersteller eine entsprechende Abfrage zur Verfügung steht (vorgeschrieben ist es nicht).

Wenn eine Smartcard verwendet wird und diese nicht fest verbaut ist, sondern über einen Cardreader angeschlossen ist, dann können Sie diese an einem PC anschließen und die Daten mit entsprechender Software auslesen. Wenn die Kasse kein eigenes Gerät ist, sondern als Software am PC läuft, können Sie die Daten direkt auf diesem PC mit einer Software auslesen.

Sollte ein Online-HSM (Cloud-Service z.B. RK Online) verwendet werden, ist es nicht direkt möglich zum Auslesen (außer Sie kennen die Zugangsdaten und haben eine entsprechende Software zum Auslesen).

Im FinanzOnline konnte ich das Public-Zertifikat nicht finden. Allerdings haben - soweit ich informiert bin - alle Signaturanbieter (VDA's) einen Verzeichnisdienst mit dem man die Zertifikate online abrufen/prüfen kann. z.B. A-Trust-Verzeichnisdienst http://www.a-trust.at/Verzeichnisdienst/ hier müssen Sie nur die Seriennummer (erhalten Sie vom QR-Code) eingeben, oder wenn Sie den Ordnungsbegriff, auf den das Zertifikat registriert wurde, wissen (z.B. UID-Nummer) dann können Sie hier abfragen: http://www.a-trust.at/RKSVSeriennummer/?l

**Comment by seblau** [comment]
Danke für die Antwort. Ich konnte mein gesuchtes Zertifikat im Verzeichnisdienst von A-Trust finden!
