### ISSUE TITLE
Prüfwerkzeug: RK-Suite

### ISSUE THREAD

**Issue by ct-graz** [a-sit-plus/at-registrierkassen-mustercode#58]
ÜBERPRÜFUNG: "Format: RK-Suite": FEHLERHAFT
DETAILS: Das Registrierkassenalgorithmuskennzeichen ist ungültig: RK1-AT1. Korrektes Format abhängig von Suite und ZDA: BSP: RK1-AT1

RK1-AT1 ist also ungültig, man soll RK1-AT1 verwenden ???
Was ist da gemeint?

**Comment by asitplus-pteufl** [comment]
Können Sie den maschinenlesbaren Code hier posten? Fängt die RK-SUITE mit "_" an?

**Comment by ct-graz** [comment]
_RK1-AT1_A00123456_2016-400_2016-03-22T16:24:36_0,00_0,00_0,00_0,00_0,00_QFVBo7Y=_1B4BCC_sE//2sJXhC0=_G7wxof8OZrJfULSQQyEpzhRfO4xjwTj6PPOCFQcwPq8A50ISTAEBB4mmF8TfXaKofmZsIMLZoUnIywDxix1ICw==

[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/199048/cryptographicMaterialContainer.txt)
[A00123456-DEP.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/199049/A00123456-DEP.txt)
[test.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/199058/test.txt)

**Comment by asitplus-pteufl** [comment]
Ein triviales Problem. Die Suite beginnt ja nicht mit RK sondern mit R, also z.B. _R1-AT1_
Das Prüftool gibt hier die falsche Information zurück. Für Version 0.7. wird es hier eine überarbeitete Version geben, die solche Probleme nicht mehr hat.
Es gibt aber in Ihren Belegen noch andere Probleme (Umsatzzähler, Signatur).

**Comment by ct-graz** [comment]
Danke. einfach nicht gesehen, Ich verwende die A-Trust-Lib. Da heißt alles RK... Daher verstehe ich aber auch nicht, dass die Signatur falsch sein soll. Umsatzzähler wird mit CFB verschlüsselt.

**Comment by ct-graz** [comment]
Ich habe nun das Testbeispiel mit CFB-Verschlüsselung ausgeführt:
KassenID = DEMO-CASH-BOX932
Belegnummer = 222858
Umsatzzähler = 0
aesKey = vKAPeUsPJWATuLBRKR0rFJoLyfnF7iDKJWZ9jJJhVdY=
Dann erhalte ich:
Daten: 00000000000000
IV: M0J3SEMzRTN0ZWxPU2FPTQ==
Umsatz 0 verschüsselt: u2JeyB3t7AI=
Es sollte aber sein: jTBqW2Jwi6c= 
Nachdem ich keine CTR-Verschlüsselung habe, kann ich das nich damit ausprobieren.

**Comment by A-Trust** [comment]
Hallo ct-graz, 
welche A-Trust Lib verwenden Sie? 
Damit wir den Fehler auf unserer Seite korrigieren können.

**Comment by ct-graz** [comment]
Das Verschlüsseln erfolgt über die interne Funktion der Programmierumgebung.

Verwende nur C_RKSign aus "asignp11" zum Signieren: EInige Signaturen passen dem Test, andere nicht.

    ASSIGN lv_data     = base64url_encode_C('~{"alg":"ES256"~}') + "." + base64url_encode_C(v_rlnr)
           lv_data_len = LENGTH(lv_data).

    SET-SIZE(mp_data)       = lv_data_len.
    PUT-STRING(mp_data, 1, lv_data_len) = lv_data.
    
    SET-SIZE(mp_signat)     = 256.
    
    SET-SIZE(mp_signat_len) = 4.
    PUT-UNSIGNED-LONG(mp_signat_len, 1) = 256.
    
    RUN C_RKSign(INPUT        mp_data, 
                 INPUT        lv_data_len,
                 INPUT-OUTPUT mp_signat,
                 INPUT-OUTPUT mp_signat_len,
                 OUTPUT       lv_ret).

**Comment by asitplus-pteufl** [comment]
Wie lange ist der Umsatzzähler den Sie verschlüsseln? Nehmen Sie hier die Minimallänge von 5 Bytes?

Zur Signatur: Sie verwenden = Zeichen im Payload Teil der JWS Repräsentation. = ist in BASE64-URL-Encoding nicht erlaubt. Es scheint auch dass dort die Signaturen brechen. Können Sie verifizieren dass Sie dort BASE64 URL Encoding verwenden?

**Comment by ct-graz** [comment]
Der Umsatzzähler ist mit 5 Bytes verschlüsselt. Ich kann auch alles wieder entschlüsseln. Aber nachdem die von mir verwendete CFB-Verschlüsselungsfunktion etwas anderes liefert als laut Testvorgabe, muss der Fehler hier sein.
Ich muss mir eine andere Lib suchen, die CTR kann.

Danke für den Hinweis, meine selbstgestrickte BASE64-URL-Funktion hat beim = abgeschnitten, nicht davor. Daher haben
 auch alle Signaturen ohne = im Text gestimmt. Nun passen alle.
[A00123456-DEP.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/201938/A00123456-DEP.txt)

**Comment by asitplus-pteufl** [comment]
ok, dann mal ein Problem gelöst, wegen 5 Bytes, ich muss noch das Prüftool anschauen, kann sein, dass es hier mit Längen <8 Probleme gibt. Das Prüftool wird mit Version 0.7 überarbeitet, um solche Probleme zu vermeiden. Ich schau das für Version 0.6 an und melde mich.

**Comment by asitplus-pteufl** [comment]
Müssen das Schritt für Schritt angehen, da nicht ganz klar ob Fehler von Verschlüsselung oder falscher Kodierung des Wertes kommt. Das Prüftool hat mit Umsatzzählern die kürzer als 8 Bytes sind ein Problem, aber auch bei der neuen Version die das berücksichtigt komme ich nicht auf das korrekte Ergebnis:

Ich schlage folgendes vor:
-Können sie (temporär) den Umsatzzähler auf 8 Bytes kodieren? Dann würd ich mal überprüfen wie sich das ganze verhält und dann weiter im Bereich Verschlüsselung suchen, wenn das gelöst ist (falls da überhaupt ein Problem) dann wieder auf die 5 Bytes zurückgehen.

**Comment by ct-graz** [comment]
Nun habe ich auf 8 Bytes umgestellt. Der Umsatzzähler passt noch immer nicht.
Schon beim Startbeleg, wo kein falsch aufbereiteter Umsatzzähler möglich ist.
Trotz einer anderen Verschlüsselungsfunktion bekomme ich aber auch noch immer ein anderes Ergebnis als im Testbeispiel, wenigstens das selbe wie mit der internen ENCRYPT-Funktion..

Seltsam auch:
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine **Stornobuchung** (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Verschlüsselter Umsatzzähler": FEHLERHAFT

Wie kann der fehlerhaft sein, wenn es bei der Stornobuchung keinen gibt?

[A00123456-DEP.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/204103/A00123456-DEP.txt)
[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/204104/cryptographicMaterialContainer.txt)

**Comment by asitplus-pteufl** [comment]
Können Sie den Code für die Verschlüsselung posten?

**Comment by ct-graz** [comment]
lv_rka_n = 8.    /* N = 8   min. 5 */
lv_umsatz = STRING(kasproto.saldo * 100).  /* in Cent */

/* Für die Kodierung des Umsatzzählers im Klartext wird dabei ein Byte-Array der Länge 16 erstellt. 
   Jedes Element des Byte-Arrays wird mit 0 initialisiert. Der Umsatzzähler mit der Byte-Anzahl N 
   wird startend mit Byte 0 im BIG-ENDIAN Format als Zweier-Komplement Darstellung („signed“) gespeichert. 
   N entspricht der Anzahl der Bytes die für die Kodierung des Umsatzzählers notwendig sind. 
   Es müssen mindestens 5 Bytes/40 Bits für den Umsatzzähler verwendet werden. */

PUT-LONG(lv_raw0, 1) = INTEGER(lv_umsatz). /* 4 Bytes */
    
/* die 4 Integerstellen Umdrehen auf 5 Bytes ABCD -> 0DCBA00000000000 */
/* die 4 Integerstellen Umdrehen auf 8 Bytes ABCD -> 0000DCBA00000000 */
DO i = 1 TO 16:
  IF i > (lv_rka_n - 4) AND i <= lv_rka_n THEN DO:
        lv_byte = GET-BYTE(lv_raw0, (lv_rka_n + 1 - i)).
        PUT-BYTE(lv_umsraw, i) = lv_byte.
  END.
  ELSE
    lv_byte = 0.
        
   PUT-BYTE(lv_umsraw, i) = lv_byte.
END.

lv_aeskey = BASE64-DECODE(kassa.aeskey64).

PUT-STRING(lv_ivraw, 1, 16) = sha256_digest(lv_regnr + lv_belegnr, 16).

lv_raw0 = ENCRYPT(lv_umsraw, lv_aeskey, lv_ivraw, lv_algor).
lv_umsraw = GET-BYTES(lv_raw0, 1, lv_rka_n).

**Comment by asitplus-pteufl** [comment]
und die ENCRYPT Funktion?

**Comment by asitplus-pteufl** [comment]
Noch ein Hinweis zu Ihren Angaben von weiter oben (wo Sie die Werte für die unterschiedlichen parameter nennen). Auszug:
KassenID = DEMO-CASH-BOX932
Belegnummer = 222858
IV: M0J3SEMzRTN0ZWxPU2FPTQ==

Diesen IV kann ich nicht nachvollziehen:
-Input für SHA-256 Hash: UTF-8 encoded byte[] von "DEMO-CASH-BOX932222858"
-Hashen ergibt 32 bytes langes []
-Vom Hash 16 Bytes nehmen
-Base64-kodiert ist das: 3BwHC3E3telOSaOMF5ulKw==

**Comment by ct-graz** [comment]
Vielen, vielen Dank!
Ich habe schon vermutet, dass der IV nicht passt, daher habe ich ihn oben gepostet.

Der IV war bei der Verwendung bereits base64-kodiert, was in sha256_digest() passierte, weil die Verkettung das so benötigt.
M0J3SEMzRTN0ZWxPU2FPTQ== ist somit Base64 von 3BwHC3E3telOSaOMF5ulKw==

Jetzt stimmt das Testbeispiel.

P.S. ENCRYPT ist ein interner Progress-Befehl.

**Comment by ct-graz** [comment]
Nun passt der Testbericht.
Nachmals danke für die Fehlersuche.
