### ISSUE TITLE
Problem Smartcard aktivieren A-Trust a.sign RK CHIP, Fiskaltrust

### ISSUE THREAD

**Issue by Mr-Get** [a-sit-plus/at-registrierkassen-mustercode#580]
Die Aktivierung meiner Smartcard mithilfe der Software a.sign RK CHIP v.1.7.6.1 von A-Trust schlägt fehlt.

Das Program liefert folgenden Output:
![grafik](https://cloud.githubusercontent.com/assets/22959496/25580799/0677c396-2e84-11e7-9a43-0c101dd07b95.png)

Den Einträgen im Logfile nach kann kein contract auf den Servern von A-Trust erstellt werden. 
[ATrustRegistrierkasseChip_2017-05-01-14-55-15.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/967927/ATrustRegistrierkasseChip_2017-05-01-14-55-15.txt)

Ich habe das Programm mit unterschiedlichen UIDs, Steuernummern und Mailadressen getestet, aber es tritt immer der gleiche Fehler auf. Auch auf verschiedenen PCs ist das Ergebnis immer gleich.

Den a.sign Client und die Aktivierungssoftware habe ich direkt von der A-Trust Website https://www.a-trust.at/AktivierungRegistrierkasseChip.aspx

Der Smartcardreader und die Smartcard sind von Fiskaltrust. 

Hat irgendjemand eine Idee wie man das Problem lösen könnte?

**Comment by AxelKutschera** [comment]
Zu fiskaltrust: Der Smartcard ist von der A-Trust; der SmartCard-Leser ist vermutlich der Gemalto K30
Für die Verwendung im fiskaltrust-Portal sollte das Personalisierungs-Tool von fiskaltrust aus dem Portal verwendet werden. Dann wir die Karte automatisch für die Konfiguration angelegt. Diese Software verwendet jedoch auch die A-Trust-Komponenten im Hintergrund.

Zum Logfile:
2017-05-01 14:56:01        ERROR error create contract
2017-05-01 14:56:01        ERROR error create contract on server
Hier konnte der Contract mit der A-Trust nicht erstellt werden. 

Wir haben auch immer wieder Fehlermeldungen zB bei schlechter Internet-Verbindung und es hat dann aber trotzdem funktioniert.

Um das zu kontrollieren kann man unter http://www.a-trust.at/RKSVSeriennummer/?l abfragen, ob das Zertifikat angelegt wurde. Vielleicht ist die Karte bereits vorhanden? Zu dieser UID sind schon zwei Zertifikate gespeichert.

**Comment by A-Trust** [comment]
Hallo Mr-Get,
im Logfile steht leider nur, dass zu der Karte schon ein Aktivierungsversuch fehlgeschlagen ist.
Da die Karte noch nicht beschrieben wurde habe ich Status der Karte am Server auf „noch nicht aktiviert“ gesetzt, damit ist ein Neustart der Aktivierung jetzt möglich.

**Comment by Mr-Get** [comment]
Vielen Dank für die Hilfe! Nachdem der Status am Server auf „noch nicht aktiviert“ zurückgesetzt wurde konnte ich die Karte problemlos aktivieren.
