### ISSUE TITLE
Finanzamt Kontrolle Fragen

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#586]
Hallo,

ich hab schon paar mal erfolglos an Finanzonline per Email (hotline.finanzonline@bmf.gv.at) geschrieben, ohne einen ausreichenden Antwort zu bekommen und frag deswegen hier nach ob mir jemadn paar Fragen bezüglich Finanzamt Kontrolle beantworten kann:

1. Wie wird der DEP export verlangt? Weil viele von unsere Kunden (100 oder mehr RegistrierKassen) haben das Zentral eingerichtet und davon aus kann man es nicht in jeden Moment an jede Kasse exportieren und zum verfügung stellen, sondern in der Zentrale oder Finanz/Buchhaltung..

2. In dem fall dass man es nicht erreicht hat die RKSV Vorraussetzungen zu erfüllen, sollte eine Firma nachweissen müssen dass die bis 15.03. alles dafür unternohmen haben. Z.B. reicht dazu dann eine Aussage der Kassensoftware Hersteller? bzw wie kann eine Firma das nachweisen? Gibt es welche Formulare dafür?

Vielen dank im voraus

PeterM

**Comment by ErichFreitag** [comment]
Sie müssen einen RKSV-DEP-Export nach § 7 und einen DEP-Export nach § 19 pro Kasse erstellen können. Im Erlass sind die Umstände dazu beschrieben - bis zu 48 Stunden Zeit, Übergabe auch per Link auf Server möglich etc., also auch zentral gesteuert.

Eine Nur-Aussage wird nicht genügen. Der Betreiber wird zweifelsfrei nachweisen müssen, dass er die Bestellung vor dem 15.03. getätigt hat. Formulare sind mir nicht bekannt.

**Comment by Phoniexk** [comment]
Zu Punkt 2: Aus liefertechnischen Gründen konnten wir nicht alle Kassen rechzeitig umstellen. Die Bestellungen unserer Kunden haben wir schon zu Jahresbeggin (schon bevor die Info mit dem 15.03. rauskam) eingefordert, um den nötigen Aufwand abschätzen zu können. Wir haben daher den Kunden, welche unserseits nicht rechzeitig umgestellt werden konnten, eine schriftliche Bestägigung inkl. Auftragsbestätigung zugesendet - in dieser wurde das Bestelldatum des Kunden angeführt.

Damit kann der Kunde nachweisen, dass er bereits zu Jahresbeginn bestellt hat.

**Comment by espeitslo** [comment]
Vielen dank an beide für die Informationen!

MfG

PeterM

**Comment by espeitslo** [comment]
Vielen dank an beide für die Informationen!

MfG

PeterM
