### ISSUE TITLE
Firmenumgründung neuer Startbeleg?

### ISSUE THREAD

**Issue by manfred78** [a-sit-plus/at-registrierkassen-mustercode#587]
Hallo zusammen,

ich hab folgendes zu lösen?
Firma hat eine Registrierkasse (Software/PC) auch auf FON registriert. Jetzt hat sie die Firmenform geändert und somit eine neue UID. Somit muss sie auch eine neue Signatur erhalten und die Kassa neu auf FON registrieren. 
Nun hab ich folgende Frage. Die Kassa hat ja bereits einen Umsatzzähler ungleich 0 - der Startbeleg muss da ja aber 0 haben oder? Oder darf beim Startbeleg der Umsatzzähler ungleich 0 sein und nur die KassaID muss anstatt der Verkettung drinnen sein?
Alternativ kann ich natürlich auch alles Sichern und eine neue "leere" Kassa anlegen - mit neuem DEP.

Danke für die Aufklärung.

Manfred

**Comment by ErichFreitag** [comment]
Wenn das Unternehmen eine neue UID hat ist alles neu, somit hat die alte Kasse ihren Lebenszyklus beendet und ist abzumelden und die Daten sind zu sichern.

Die neue Kasse ist neu anzumelden mit Umsatzzähler 0 und einem neuen DEP. Egal ob sie etwas bestehende leeren oder neu aufsetzen. Neues Unternehmen - neue Kasse bei 0 und beim Startbeleg beginnend.

Beim Leeren achten sie nur darauf, dass sie auch alles während der Aufbewahrungsfrist im Bedarfsfall rekonsturieren können.

**Comment by manfred78** [comment]
Ok - DANKE.
Dann ist alles klar!
