### ISSUE TITLE
MonatsBeleg / JahresBeleg nicht erstellt

### ISSUE THREAD

**Issue by espeitslo** [a-sit-plus/at-registrierkassen-mustercode#588]
Hallo,

kann mir jemand bitte sagen was muss gemacht werden in dem Fall dass MonatsBeleg oder JahresBeleg nicht erstellt wurde?

Vielen dank im voraus

PeterM

**Comment by Phoniexk** [comment]
Wenn ich hier Herrn @AxelKutschera aus dem WKO-Forum zitieren darf:

> Sobald es geht nach machen.

**Comment by espeitslo** [comment]
Ja aber bedutet das dass man es in die mitte des Monats erstellen soll, oder Ende des Monats abwarten un dann regelmaßig einen MonatsBeleg erstellen? Bzw einfach den ausgefallenen lassen und am Ende des Monats den nächsten MonatsBeleg erstellen?

**Comment by Phoniexk** [comment]
Ich verstehe nicht ganz was an diesem (einfachen) Satz mit 5 Wörtern unklar ist.
Anders formuliert: **So schnell als möglich nach machen.** Sobald man bemerkt, dass der Monatsbeleg nicht gemacht wurde -> nachholen. Wenn es der Geschäftsbetrieb zulässt unmittelbar, ansonsten nach Geschäftsende.

Am besten wäre eine Warnung in der Kassensoftware schon am ersten Arbeitstag des neuen Monats, idealerweise mit einer Blockade der Software bis der Monatsbeleg erstellt wurde (noch vor dem ersten Beleg).

**Comment by espeitslo** [comment]
Ich war nicht sicher ob das explizit genau so gemeint war, deswegen die Nachfrage.

Ich bedanke mich für die Information und Ihre prompte Antwort!

**Comment by espeitslo** [comment]
Ich war nicht sicher ob das explizit genau so gemeint war, deswegen die Nachfrage.

Ich bedanke mich für die Information und Ihre prompte Antwort!
