### ISSUE TITLE
Prüfwerkzeug Ver.0.6: Kryptographische Gültigkeit der Signatur nicht gegeben

### ISSUE THREAD

**Issue by newdeal30** [a-sit-plus/at-registrierkassen-mustercode#59]
Hallo!
Ich habe das Problem, dass das Prüfwerkzeug meldet, dass die Kryptographische Gültigkeit der Signatur nicht gegeben ist. 
Die restlichen Tests scheinen in Ordnung zu sein.
Ich verwende Karten von A-Trust und habe die Einbindung nicht über die Registrierkasse.dll sondern direkt gemacht.
Im Anhang befinden sich der maschinenlesbare Code, der signierte Code, das DEP und der Crypto-Container.
Vielen Dank für die Hilfe!

![image](https://cloud.githubusercontent.com/assets/6523553/14231109/4c2c0692-f977-11e5-9405-c634cb46a031.png)

[Export.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/201208/Export.zip)

**Comment by asitplus-pteufl** [comment]
es schaut so aus als ob Sie im cryptomaterialcontainer file die falsche Seriennummer verwenden (deswegen kann die korrekte Sig-Einheit nicht gefunden werden.
zumindest finde ich in den Belegen nicht die Seriennummer 1AFA33.

**Comment by newdeal30** [comment]
Hallo Herr Teufl,
Danke, ist mir nicht aufgefallen!
Habe den maschinenlesbaren Code nun abgeändert und übergebe die Seriennnummer als HEX statt als Decimal. 
Bekomme allerdings immer noch die selbe Meldung.
Eine Frage zur Funktionsweise des CryptographicMaterialContainers:
Ich lege in dem Feld "signatureCertificateOrPublicKey" den Export des X509 Zertifikates wie folgt ab:
  X509Certificate SigCertX509 = GetCertificate();
  SigCertB64 = Convert.ToBase64String(SigCertX509.Export(X509ContentType.Cert));
Im Vergleich zu den Example Outputs ist mein Zertifikat der Karte mindestens doppelt so lang.
Könnte hier der Fehler liegen?
Im Anhang nochmals der aktualisierte Output.

        
[Daten.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/201914/Daten.zip)

**Comment by newdeal30** [comment]
Habe nun auch probiert die Seriennummer wie im Example Output auf ToLower() zu formatieren. 
Ist allerdings das selbe Ergebnis.

**Comment by asitplus-pteufl** [comment]
Bitte nochmal das DEP-Export posten. Dann kann ich das leichter nachvollziehen. Zert schaut auf den ersten Blick normal aus, obwohl mich die Größe schon sehr irritiert. Aber das klär ich dann wenn ich die Daten haben.
Danke!

**Comment by newdeal30** [comment]
Anbei ein neuer Export nach Nullstellung (neuer AES, selbes Zertifikat)
[dep-export.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/202025/dep-export.zip)

**Comment by asitplus-pteufl** [comment]
Hmm, jetzt kann das passende Zertifikat gefunden werden, die Signatur ist aber nicht korrekt.
Jetzt ist es ohne weitere Infos schwierig. Wie signieren Sie denn? Haben Sie da ein Code Snippet?

**Comment by newdeal30** [comment]
Ich signiere wie in dem Beispiel von ATrust 
(http://labs.a-trust.at/developer/ShowSource.aspx?id=114) (C# Code)
Ich habe die signierten Daten auch mit Verify überprüft und bekomme ein erfolgreiches Ergebnis.

public string Sign(string strToSign) {
      byte[] bytesToSign = Encoding.Unicode.GetBytes(strToSign);
      SHA256Managed crypt = new SHA256Managed();
      byte[] hash = crypt.ComputeHash(bytesToSign, 0, bytesToSign.Length);
      string hashString = Convert.ToBase64String(hash);

      byte[] pin = new byte[] { 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x00, 0x00 };
      byte[] signature = Sign(pin, hash);
      bool isOK = Verify(signature, bytesToSign);
      if (isOK)
        return Crypto.Base64UrlEncode(signature);
      else
        return string.Empty;
}

private byte[] Sign(byte[] PIN, byte[] SHA256HASH) {
    SendSelectFID(DF_SIG);
    CommandApdu apdu2 = GenerateDataAPDU(isoReader, 0x00, 0x22, 0x41, 0xb6, TLV);
    Response response2 = isoReader.Transmit(apdu2);
    CommandApdu apdu3 = GenerateDataAPDU(isoReader, 0x00, 0x20, 0x00, 0x81, PIN);
    Response response3 = isoReader.Transmit(apdu3);
    CommandApdu apdu4 = GenerateDataAPDU(isoReader, 0x00, 0x2A, 0x90, 0x81, SHA256HASH);
    Response response4 = isoReader.Transmit(apdu4);
    CommandApdu apdu5 = GenerateResponseAPDU(isoReader, 0x00, 0x2A, 0x9E, 0x9A);
    Response response5 = isoReader.Transmit(apdu5);
    byte[] signature = response5.GetData();
    return signature;
}

**Comment by asitplus-pteufl** [comment]
was ist denn str2sign konkret? (als BSP für einen Beleg).

**Comment by newdeal30** [comment]
Beispiel des Aufrufs:
strToBeSigned = "_R1-AT1_NOTEBOOK_6_2016-04-04T11:30:00_4,00_6,00_0,00_0,00_0,00_F/WdcNA+4tnmA3+jCs1kyw==_1afa33_TxRk5Wx5WOM=";
string strToBeSignedB64 = "eyJhbGciOiJFUzI1NiJ9." + Crypto.Base64UrlEncode(strToBeSigned);
string signResult = Sign(strToBeSignedB64);
string jwsSignature = strToBeSignedB64 + "." + signResult;

**Comment by newdeal30** [comment]
Haben Sie schon eine Idee was nicht stimmen kann?

**Comment by asitplus-pteufl** [comment]
Nein. Bitte unbedingt Zertifikat überprüfen (vor allem welches Sie zum Signieren verwenden und dann in den CryptoContainer ablegen). Die Größe kann nicht stimmen (sind da mehrere Zertifikate drinnen)?
Auf den ersten Blick scheint oben alles korrekt zu sein (daher wäre es am sinnvollsten noch mal zu prüfen ob überhaupt mit dem korrekten Zert geprüft wird).

**Comment by newdeal30** [comment]
Das Zertifikat exportiere ich wie in den Beispielen der A-Trust. 
Ich nutze das SigCertBytes als Base64 formatiert.
Ich setze mich mit A-Trust in Verbindung.

**Comment by newdeal30** [comment]
Ich habe nun das Beispiel von A-Trust (http://labs.a-trust.at/developer/ShowSource.aspx?id=125)
um den Export des DEPs erweitert.
Das Problem sollte so sehr einfach nachzuvollziehen sein.
[TestRKDLL.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/206895/TestRKDLL.zip)

**Comment by asitplus-pteufl** [comment]
legen sie die Signatur im maschinenlesbaren code BASE64 kodiert oder BASE64-URL kodiert ab?

BASE64 für den maschinenlesbaren code
BASE64-URL für die JWS-Repräsentation.

**Comment by newdeal30** [comment]
So, es funktioniert nun. 
Ich bin vom Beispiel http://labs.a-trust.at/developer/ShowSource.aspx?id=114 ausgegangen und dort wird der Signieren-Funktion ein Byte Array übergeben. Dieses ist im Beispiel als Unicode und nicht als UTF8 formatiert.
Nach der Änderung auf UTF8 passts nun. 
Ich habe der A-Trust das auch geschickt, dass es eventuell im Sample geändert wird.
Vielen Dank an A-Sit und A-Trust für die Hilfe

**Comment by asitplus-pteufl** [comment]
Danke für die Detailinfos. Dann schließe ich das.
