### ISSUE TITLE
Freiwillig

### ISSUE THREAD

**Issue by ckvsoft** [a-sit-plus/at-registrierkassen-mustercode#593]
Hallo
Gehört hir wohl nicht her.  Doch weder die WKO noch das BMF kann mir das beantworten. 

Ein Kunde braucht gesetzlich keine RKSV Registrierkasse da er unter den Grenzen bleibt.
Möchte aber die Belegerstellung mit einer Kasse machen. Darf er das ohne DEP /  Signatur oder muss dann die Kasse trotzdem RKSV konform sein? Sprich muss er ein Zertifikat kaufen.

LG chris

**Comment by ErichFreitag** [comment]
Wenn keine Registrierkassenpflicht besteht, dann darf zB die Belegerteilungsverpflichtung auch mit einer RegK ohne Manipulationsschutz erfüllt werden (vergleiche ähnliche Fragen unter https://www.xing.com/communities/groups/registrierkassenpflicht-oesterreich-a25f-1078578).

**Comment by ckvsoft** [comment]
Danke
nur gilt das auch wenn die Kasse es könnte?

Denke so an diverse Österreichische Gesetze in anderen Bereichen. "Wenn was vorhanden ist muss es auch funktionieren"  auch wenn man es nicht haben muss.

**Comment by ErichFreitag** [comment]
Ich zitiere Markus Knasmüller aus https://www.xing.com/communities/posts/einsatz-einer-registrierkasse-ohne-registrierkassenpflicht-1012692563:

"Das BMF hat dazu Stellung genommen, in diesem Falle muss die Kasse nicht der RKSV entsprechen: Jemand, den keine gesetzliche Verpflichtung zur Verwendung einer elektronischen Registrierkasse nach § 131b BAO trifft, kann die Losungsermittlung durch Kassasturz bzw. weiterhin mit einer bisher verwendeten Registrierkasse, die den §§ 131 und 132 BAO bzw. der KRL 2012 entspricht, durchführen.
siehe: https://findok.bmf.gv.at/findok?execution=e100000s1&segmentId=1716800b-8cec-452a-8245-7b35c3c33277".

-> 4. Anforderungen an eine freiwillig geführte Registrierkasse:  4.4. Lösung: Jemand, den keine gesetzliche Verpflichtung zur Verwendung einer elektronischen Registrierkasse nach § 131b BAO trifft, kann die Losungsermittlung durch Kassasturz bzw. weiterhin mit einer bisher verwendeten Registrierkasse, die den §§ 131 und 132 BAO bzw. der KRL 2012 entspricht, durchführen.

Wenn jemand allerdings freiwillig eine Registrierkasse iSd BAO führt und dafür eine Signaturerstellungseinheit verwendet, unterwirft er sich freiwillig dem Registrierkassenregime. Bei der behördlichen Registrierung der Signaturkarte handelt es sich um einen Hoheitsakt. Wenn jemand seine Registrierkasse und seine Signaturerstellungseinheit freiwillig über FinanzOnline registriert, erfüllt er die Voraussetzungen des § 131b BAO".

Fazit: nein. Es ist nicht von der Fähigkeit der Kasse abhängig.

**Comment by ckvsoft** [comment]
Ok. Danke
Alles klar
