### ISSUE TITLE
Übermittlung DEP-Protokolle - wie?

### ISSUE THREAD

**Issue by akordowski** [a-sit-plus/at-registrierkassen-mustercode#594]
Hallo,

ich stehe vor der Aufgabe die Übermittlung der DEP Protokolle (json) an FinOn zu implementieren, finde aber allerdings nirgends einen Hinweis wie bzw. mit welchem Webservice man das machen kann. Hat jemand einen Tipp für mich? Danke im voraus!

**Comment by ErichFreitag** [comment]
Sie finden deshalb nichts, weil eine Übermittlung der DEPs an Finanz-Online nicht vorgesehen und nicht erforderlich ist.

**Comment by akordowski** [comment]
Vielen Dank für die schnelle Antwort. Realisiere ich es dann über die Belegprüfung?

**Comment by ErichFreitag** [comment]
Das kommt darauf an, was sie vorhaben.

Als Kassenhersteller werden sie die DEP-Exporte im RKSV-Format gründlich mit dem A-SIT-Tool überprüfen, um ihre Implementierung zu testen.

Eine Prüfung der RKSV-DEPs erfolgt im Betrieb normalerweise nur bei Kontrollen durch die Finanzbehörden und dann auch mit deren eigenen Werkzeugen.

Was sicher nicht schadet ist, sich als Hersteller dahingehend zu vergewissern, dass die DEP-Exporte auch im tatsächlichen Betrieb korrekt sind. Also beispielsweise nach ein, zwei, drei, sechs Monaten nochmals einen DEP-Export herzunehmen und diesen mit dem A-SIT-Prüftool zu testen.

**Comment by akordowski** [comment]
Ich versuche unseren Stand der Kenntnis und das was Sie beschrieben zusammen zu fassen:
Die Übermittlung der DEP-Protokolle an FinOn ist nicht vorgesehen und nicht notwendig. Mit der Belegprüfung über den Webservice/A-SIT-Prüftool/App erfolgt nur eine Prüfung der Implementierung und keine Übermittlung an FinOn. Die DEP's müssen nur bei Kontrollen der Finanzbehörden bereitgestellt werden (als Ausdruck oder als Datei?) und sie müssen 7 Jahre gesichert werden. Haben wir das korrekt verstanden?
Vielen Dank für die Hilfe!

**Comment by ErichFreitag** [comment]
So ähnlich :-)

Die Übermittlung der DEP-Protokolle erfolgt nicht an Finanz-Online, korrekt.

Mit der Belegprüfung wird ein einzelner Beleg geprüft und an Finanz-Online übermittelt. Das brauchen sie für die Inbetriebnahme der Kasse (Startbeleg), für die Prüfung der Jahresbelege und für sonstige beliebige Prüfungen eines Belegs. Das gilt für Webservice und für die Belegcheck-App.

Mit dem A-SIT-Prüftool können sie Belege und RKSV-DEPs überprüfen. Dabei wird nichts übermittelt.

Die DEPs müssen als Datei bei Kontrollen zur Verfügung gestellt werden. Daten und Aufzeichnungen sind generell 7 Jahre lang aufzubewahren.

**Comment by akordowski** [comment]
Vielen herzlichen Dank für die Hilfe! Jetzt ist uns einiges klarer ;)
