### ISSUE TITLE
Fehler bei Prüftool

### ISSUE THREAD

**Issue by StefanKDS** [a-sit-plus/at-registrierkassen-mustercode#596]
Hallo,
ich bekomme folgenden Fehler wenn ich das Prüftool ausführe:

**_Die Prüfung des Belegs konnte nicht vollständig durchgeführt werden. Vermutlich konnte das Zertifikat oder der Schlüssel mit der im Beleg angegeben Seriennummer bzw. dem angegebenen Ordnungsbegriff des Unternehmens und der Schlüssel-ID nicht in der cryptographicMaterialContainer.json Datei gefunden werden._**

Mein Aufruf:
"C:\Program Files (x86)\Java\jre1.8.0_131\bin\java.exe" -jar regkassen-verification-depformat-1.0.0.jar -v -f -i dep-export.json -c cryptographicMaterialContainer.json -o output

Meine cryptographicMaterialContainer.json:

{
  "base64AESKey" : "YUdGc2FXd3hPVGMwYkhWbGRHWnBNVGszTnpFd01Ea3k=",
  "certificateOrPublicKeyMap" : {
    "60C5502C" : {
      "id" : "60C5502C",
      "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : "MIIFPDCCAySgAwIBAgIEYMVQLDANBgkqhkiG9w0BAQsFADCBoTELMAkGA1UEBhMCQVQxSDBGBgNVBAoMP0EtVHJ1czggR2VzLiBmLiBTaWNoZXJoZWl0c3N5c3RlbWUgaW0gZWxla3RyLiBEYXRlbnZlcmtlaHIgR21iSDEjMCEGA1UECwwaQS1UcnVzdCBSZWdpc3RyaWVya2Fzc2UuQ0ExIzAhBgNVBAMMGkEtVHJ1c3QgUmVnaXN0cmllcmthc3NlLkNBMB4XDTE3MDMwNjA4NDE0NloXDTIyMDMwNjA3NDE0NlowPjELMAkGA1UEBhMCQVQxGDAWBgNVBAMMD1VJRCBBVFUzODI0NjcwNTEVMBMGA1UEBRMMMTMzNjA5MzExMTYxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEaMweuE1TwBjVDUKvvkS8quVPSJiFBzFxRQh69ltnDBu8EqWHXrGZRIFYtQs2gDpj7gUnFgM7/B0saIinSV0tHqOCAacwggGjMH8GCCsGAQUFBwEBBHMwcTBGBggrBgEFBQcwAoY6aHR0cDovL3d3dy5hLXRydXN0LmF0L2NlcnRzL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlLUNBLmNlcjAnBggrBgEFBQcwAYYbaHR0cDovL29jc3AuYS10cnVzdC5hdC9vY3NwMA4GA1UdDwEB/wQEAwIGwDARBgNVHQ4ECgQITkjdOKXZRGkwRQYDVR0fBD4wPDA6oDigNoY0aHR0cDovL2NybC5hLXRydXN0LmF0L2NybC9BLVRydXN0LVJlZ2lzdHJpZXJrYXNzZS5DQTAJBgNVHRMEAjAAMFgGA1UdIARRME8wTQYGKigAEQEYMEMwQQYIKwYBBQUHAgEWNWh0dHA6Ly93d3cuYS10cnVzdC5hdC9kb2NzL2NwL0EtVHJ1c3QtUmVnaXN0cmllcmthc3NlMBMGA1UdIwQMMAqACEBHnq7jkN+2MB4GA1UdEQQXMBWBE3dydUBzYW5kZXItZG9sbC5jb20wHAYHKigACgELAQQRDA9VSUQgQVRVMzgyNDY3MDUwDQYJKoZIhvcNAQELBQADggIBABYZvVh9pZ+xs/E+SfbJESy1MRmi4J1xmMlrcXURVqM+H47wFe/PrHIXp02K878LVKzsPqtSE1qGbayK1pZwptMM3jL1DbNQtbDpJGSZTXy+jbT1hfGfaJ5auPIgGaGj2twPWND7yRmhh2h8LpEwxOYsAjPDgYer8PffinapOBVA1A43agkFraRIWz2p4e4+1U1sySm/s6HQGgTUHfS0IumQaPKMg/v45zj1q9hvdKZnF+Es2997yWrT6Zv3DYPcBs5zka+7bnX+J0sCwVsUcRrb6tEGr/zaoAMPXUuBYP7es0TbE+VO36Utek/rPGraMP7xC8cxd8qmpp2UlhbPfnRI+j4+Mn1ho5pnIEgEjWqj71T9FLXcLy1coG+dr4ORK4cHhYqNFth2BGxF40xir46jLGeiU2D1VnZd0/7E/tKrnJvRhAsyoR7LgJ+KEq6ABXuTB1GfDTGBz4xIlmiFQzRW7UURi4kN/kNl2Ti4qwdKsyu64OjoE/EgXhN4QLr9tacCIhkqAGMnh+Me54lVobvflOI4Jb2A2CNTRPaYkBkzsurM46gKxDMsFgFeYBbA7boMMMwruJ/FuN2EUtCUh+nvbkSHhyUwQRbKzE4aSht+/+IXLtxjyP6habTm5TFCqKYO97oQTmDSA+WLd77WytfcuI6AVmJ2clx7rK9JQpth"
    }
  }
}

Ich sehe da spontan keine Fehler.
Kann mir jemand helfen ?

**Comment by Phoniexk** [comment]
Zertifikat und Seriennummer sollten soweit passen, lässt sich auch im Verzeichnisdienst von A-Trust finden. In diesem Fall liegt der Fehler vermutlich am Beleg selber, eventuell ist im betreffenden Beleg keine oder eine fehlerhafte Seriennummer in Verwendung, oder die Seriennummer ist nicht im HEX-Format.

**Comment by StefanKDS** [comment]
Hatte ich auch schon vermutet, allerdings kann ich keinen entdecken:

Startbeleg
Als QRCode
_R1-AT1_Kasse 2_17-00087-KA_2017-05-11T10:30:53_0,00_0,00_0,00_0,00_0,00_SxM3BFBnOzQ=_60C5502_8pzMPqWWPsw=_Ue7UW9EBkeFSV3e3IIOFrozRO304AVozLyU2YgDyL3xFo3b7aGE4P44tZmeNjrLqeAN7A74E3nSDF3AKSgT65g==

Als Signatur
eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9LYXNzZSAyXzE3LTAwMDg3LUtBXzIwMTctMDUtMTFUMTA6MzA6NTNfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX1N4TTNCRkJuT3pRPV82MEM1NTAyXzhwek1QcVdXUHN3PQ.Ue7UW9EBkeFSV3e3IIOFrozRO304AVozLyU2YgDyL3xFo3b7aGE4P44tZmeNjrLqeAN7A74E3nSDF3AKSgT65g

**Comment by Phoniexk** [comment]
Doch im Beleg fehlt die letzte Stelle von der Seriennummer:

Beleg: 60C5502
Zertifikat: 60C5502C

**Comment by StefanKDS** [comment]
Manchmal sieht man den Wald vor lauter Bäumen nicht.

Danke
