### ISSUE TITLE
Anfordern der vollen Information des Zertifikats von A-Trust

### ISSUE THREAD

**Issue by intellisec** [a-sit-plus/at-registrierkassen-mustercode#598]
Hallo
Ich habe eine sehr spezifische Frage:
Man kann sich ja ein RK-Online Zertifikat ausstellen lassen und bekommt alle Informationen inklusive Passwort, damit man seine Belege signieren kann. Man kann auch via GET die Information abrufen, wenn man den "username" hat, welcher zu dem Zertifikat gehört.
Kann man aber auch das Passwort erneut holen, im Falle, dass das Zertifikat erneut angefragt werden muss und die Passwort-Informationen verloren gegangen sind.

**Comment by lebail** [comment]
Bei A-Trust geht das, soweit ich weiß, nicht. Zumindest wurde im A-Trust Webshop, als ich zuletzt ein "RK Online"-Zertifikat erstellt habe, ausdrücklich darauf hingewiesen, dass das Passwort nicht erneut angefordert werden kann.

**Comment by intellisec** [comment]
Das heißt also, dass, wenn das Zertifikat erneut angefragt wird, ich keine Chance habe, die Passwortinformationen anzufordern... das ist gut zu wissen 👍 
Danke für die Hilfe
