### ISSUE TITLE
Beispiel "Verschlüsselung Umsatzzähler" (Bezugnahme auf Issue 91)

### ISSUE THREAD

**Issue by Harbauer** [a-sit-plus/at-registrierkassen-mustercode#599]
Habe dieses Beispiel verwendet, um mein Programm (programmiert in RPG auf System ibm i) zu testen:

Aus Issue 91:

KassenID: "CashBox01"
Belegnr: "00000001"
Umsatz: 55,09
AES-Key (base64 encoded): "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU="

IV (ersten 16 byte): 3e 04 75 88 e2 0f 53 f9 2b bd f4 a9 c0 12 40 0d
Umsatz als Byte Array: 00 00 00 00 00 00 15 85
Ergebnis: "ByW5rsidWYI="  (RICHTIG)

Ist-Daten aus meinem Programm:

Algorithmus         =  ICM/CTR Modus

IV HEX                  = 3E047588 E20F53F9 2BBDF4A9 C012400D

AES HEX               = 59046D8A 2C9ADE16 21FD4CF8 E01BF7C7 
                                C1139759 EB1FA9C2 744AE7EB D839FE55 

Klartext-Daten     = 0000158500000000
(HEX EBCDIC)       = F0F0F0F0 F1F5F8F5 F0F0F0F0 F0F0F0F0 (wird konvertiert auf UTF-8)
(HEX UTF-8)         = 30303030 31353835 30303030 30303030

Ergebnis BASE64  = NxWJnvmodDI= (FALSCH)
Ergebnis HEX       = 3715899E F9A87432 FA4266FC E9D71616 (FALSCH)

Eventuell sind AES-HEX oder Umsatz-HEX fehlerhaft ? 
Falls jemand einen Fehler lokalisieren kann, oder mir einen Tipp geben kann, wäre ich sehr dankbar.

**Comment by bombel59** [comment]
Ich komme bei der Umsatz-Encodierung nach hex auf 00 00 00 00 00 00 21 133.... warum auch immer...

vielleicht hilft dir das weiter.....

private static byte[] EncodeUmsatz(long umsatz)
        {
            // This gives an 8-byte array
            byte[] umsatzBytes = BitConverter.GetBytes(umsatz);
            // Pad with zeroes to get 16 bytes
            Array.Resize(ref umsatzBytes, 16);
            // reverse to get big-endian array
            Array.Reverse(umsatzBytes, 0, umsatzBytes.Length);
            return umsatzBytes;
        }

Ist zwar C#, aber vielleicht hilft es beim Verständnis.....

lg
Gerhard

**Comment by Harbauer** [comment]
Hallo Gerhard, 
Ja das war schon eine große Hilfe. 
Fehler war: Übergabe "0000000000001585" an AES-Algo erfolgte als String und nicht Aufgelöst im Binärformat.
Jetzt bin ich fast am Ziel:
Zwischen-Ergebnis: ByW5rsidjoI=   (Noch FALSCH)
Soll                        : ByW5rsidWYI= (RICHTIG)
die letzten 3 Stellen im Ergebnis sind noch falsch - da bin jetzt noch beim Prüfen.
Aber Danke für Dein Weiterhelfen. Lg Helmut

**Comment by Harbauer** [comment]
Zur Info für alle Interessierten (hat mit der Zeichencodierung zu tun): 
Ursache für falsches Ergebnis (die letzten 4 Stellen von BASE64-String noch nicht korrekt): im Input-String für den AES-Algorithmus wurden HEX'40' (Blanks in der IBM-EBCDIC-Welt) nach der Ziffern-Portion übergeben. Wurde ersetzt mit HEX'00'. Jetzt passt das Ergebnis (ByW5rsidWYI=).
