### ISSUE TITLE
Export Datenerfassungsprotokoll

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#60]
In Kapitel 5 der Detailfragen wird beschrieben, wie das DEP exportiert werden soll. Unter anderem wird dort angegeben, dass die Belege nach Signaturzertifikaten gruppiert werden sollen.
Belege, die im Zeitraum eines Ausfalls der Signaturerstellungseinheit erstellt wurden, besitzen kein Signaturzertifikat und würden in einer zweiten Gruppe exportiert werden.
Wird dadurch nicht die Kette "zerrissen"? Also der letzte Beleg vor dem Ausfall der Signatureinheit und der erste Beleg nach Wiederinbetriebnahme sind doch nicht korrekt verkettet, weil die Einträge dazwischen in der zweiten Liste des Exportcontainers gelandet sind.

**Comment by asitplus-pteufl** [comment]
Wichtigste Infos dazu zuerst: Es steht Ihnen auch frei die Signaturzertifikate wegzulassen (und auch die Zertifizierungsstellen), das ist mit den Detailfragen auch so geklärt worden (und damit offiziell auch vom BMF so festgelegt). Ist vor allem dann wichtig wenn Sie die Sig-erstellungseinheiten oft ändern. Ist wohl der beste/einfachste Weg.

Falls Sie die Zertifikate mitspeichern wollen, dann müssen Sie die Gruppierung im Sinne der verwendeten Sig-Erstellungseinheit sehen, auch bei einer ausgefallenen Sig Einheit muss die Seriennummer/Ordnungsbegriff bei geschlossenen Systemem angegeben werden. Damit fallen ja diese automatisch in die gleiche Gruppe wie die die eine funktionierende Signatur erhalten.

Aber wie gesagt, ich würde einfach die Option "ohne Zertiifkate" wählen.

**Comment by michaelkorb** [comment]
Vielen Dank für die Ausführungen.
Wenn ich die Option "ohne Zertifikate" wähle, ist doch eine Prüfung der Signatur eigentlich nicht möglich oder?
Bei der Variante mit Zertifikaten bekomme ich im Ausfallszenario die Informationen zum Zertifikat nicht, da in diesem Fall kein Zugriff auf die Signaturkarte möglich ist. Ich könnte also nur die bisher verwendeten Daten verwenden. Wir bei der Fehlerbehebung z.B.: die Signaturkarte gewechselt, würde auch in diesem Fall die Kette "zerrissen", da die Folgedaten in einer anderen Containerliste landen.
Mir stellt sich eine generelle Frage: Wie ist in all diesen Fällen eine Prüfung der Verkettung und der Signatur noch möglich?

**Comment by asitplus-pteufl** [comment]
Signaturprüfung ist ohne Zertifikate leicht möglich, da sowohl Seriennummer als auch ID des ZDAs vorhanden sind. Bei den einzelnen Belegen muss sowieso so vorgegangen werden, da dort kein Platz für die Zertifikate ist.

Ohne Seriennummer dürfen Sie keinen Beleg erstellten, da ja der Ausfall der Signatureinrichtung auch (nach einer bestimmten Zeit) auch Meldepflichten mit sich zieht. D.h. das "zerreißen" der Kette ist so nicht möglich, weil Sie ja in der gleichen Gruppe landet.

In der Praxis stellt sich das wohl so dar: Wenn Sie eine Sig-Einheit verwenden, ja dann muss die Seriennummer schon bekannt sein, wenn die Karte mal nicht steckt. Wenn Sie einen Pool aus Sig-Einrichtungen verwenden, dann wird man wohl eh jene nehmen die funktionsfähig ist, wen alle ausfallen wohl einfach eine der Seriennummern

**Comment by michaelkorb** [comment]
Vielen Dank für die Ausführungen.
Bei erster Verwendung einer Karte merke ich mir die Daten der Karte an einem separaten Ort, damit nicht jeder DEP-Eintrag die Zertifikatsdaten speichern muss. Bei Ausfall der Karte werde ich dann die letzte bekannte Seriennummer verwenden. Damit bleiben alle Daten beim Export in einer Gruppe.

**Comment by asitplus-pteufl** [comment]
ja, wenn sie nur wenige Karten/Sig-Einrichtungen verwenden durchaus so sinnvoll, soabald Sie auf mehrere wechseln wird das Gruppieren im DEP durchaus mühsam, daher ist es dann wohl besser einfach die sig-zerts weglassen und nur "eine gruppe" erstellen.

**Comment by michaelkorb** [comment]
Wir werden für jede Kasse eine eigene Signatureinheit verwenden, um die netzwerkseitige Unabhängigkeit der Kassen zu bewahren. D.h. wir verwenden für jeden DEP-EIntrag die Seriennummer des zuletzt verwendeten Zartifikates bei Ausfall und die des aktuellen zertifikates bei Normalbetrieb. Beim Export lassen wir die Zertifikatsdaten weg und somit gelangen alle in eine Gruppe und die Verkettung ist lückenlos. Auch bei Wechsel der Karte bleiben somit alle Einträge des DEP in einer Gruppe. Lediglich in den kompakten Daten steht dann eine andere Seriennummer.
