### ISSUE TITLE
Kasse mit Abschlussbeleg wieder reaktivieren

### ISSUE THREAD

**Issue by StefanKDS** [a-sit-plus/at-registrierkassen-mustercode#600]
Hallo,

wenn ich es in den Unterlagen richtig verstanden habe, dann ist es möglich eine Kasse die deregistriert wurde ( und somit ein Abschlussbeleg erstellt wurde ) wieder zu registrieren.
Wenn das geschieht wird ein neuer Startbeleg erstellt und der Umsatzzähler beginnt wieder bei 0.

Wenn ich dann aber für diese Kasse das DEP exportieren und durch das Testtool laufen lasse bekomme ich eine Fehlermeldung weil Belege vor einem Startbeleg vorhanden sind.

Ist der Export falsch oder darf man eine Kasse nicht reaktivieren ?

Gruß
Stefan

**Comment by Flanelli** [comment]
Wenn eine Kassa geschlossen wird, also komplett außer Betrieb genommen, müssen die DEP für diese Kassa separat gespeichert werden - Also als klares DEP nur für diese Kassa,

Mit der Erstellung des neuen Startbeleges erfolgt auch die erstellung eine neuen DEP.
Das DEP beginnt IMMER mit dem Startbeleg der entsprechenden Kassa denn jedes Kassa hat ihr eigenes DEP und somit wird das Prüftool zwangsläufig einen Fehler anzeigen wenn irgendwann nach dem ersten Startbeleg plötzlich ein weiterer Startbeleg auftaucht.

**Comment by andreasschiestl** [comment]
Einfach beschrieben kann der RKSV-Teil der Kasse nicht wieder in Betrieb genommen werden. Die Kasse selbst kann wieder in Betrieb genommen werden, aber alle RKSV relevanten Bestandteile (DEP, Umsatzzähler usw.) müssen neu initialisiert werden als wäre es eine neue Kassa. Es empfiehlt sich auch eine neue Kassen-ID zu verwenden.
