### ISSUE TITLE
DEP-Prüfung HSM-GlobalTrust

### ISSUE THREAD

**Issue by Spanky2** [a-sit-plus/at-registrierkassen-mustercode#603]
Wir haben folgendes Problem:

Beim Prüfen eines Mini-DEPs (Startbeleg und normaler Beleg) kommt es bei der Prüfung 'DEP_CHAINING_VALUE' zu einem Fehler:
Die Verkettung zwischen dem vorigen Beleg und dem aktuellen Beleg ist ungültig. Bitte überprüfen Sie die Berechnung des Verkettungswerts oder die Abfolge der maschinenlesbaren Codes im exportierten RKSV-DEP.

Dies tritt jedoch NUR bei HSM-GlobalTrust auf. Wir verwenden die selbe Routine für die Verkettung, wie bei den anderen Signaturmöglichkeiten (Global-Trust-Karte, ATrust-HSM, ATrust-Karte).

Die Prüfung der QR-Darstellungen funktionieren jedoch mit dem Prüftool. Hier werden m.M. ebenfalls die Verkettungen geprüft.

Ich hänge die Ergebnisse von der DEP-, als auch der QR-Prüfung an (output_dep.zip, output_qr.zip).
[output_qr.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1021391/output_qr.zip)
[output_dep.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1021390/output_dep.zip)

Zusätzlich auch die Input-Dateien (crypt.json, dep.json, qr.json).
[Input.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1021395/Input.zip)

Wir würden uns sehr über eine Hilfe zu diesem Thema freuen!!!

**Comment by Spanky2** [comment]
`{
    "verificationId" : "DEP_CHAINING_VALUE",
    "version" : 1,
    "verificationName" : "Verkettung der maschinenlesbaren Codes im RKSV-DEP-Export",
    "verificationTextualDescription" : "In diesem Modul wird überprüft, ob die Belege im exportierten RKSV-DEP korrekt verkettet sind.",
    "verificationState" : "FAIL",
    "verificationResultDetailedMessage" : "Die Verkettung zwischen dem vorigen Beleg und dem aktuellen Beleg ist ungültig. Bitte überprüfen Sie die Berechnung des Verkettungswerts oder die Abfolge der maschinenlesbaren Codes im exportierten RKSV-DEP.",
    "input" : {
      "CHAINING_VALUE_PREVIOUS_RECEIPT" : "6uM2Vzpz3GE=",
      "RK_SUITE_ID" : "R1",
      "CHAINING_INPUT" : "eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9EZWZhdWx0LUNhc2hib3hfMV8yMDE3LTA1LTIzVDA5OjI2OjU0XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF9DZ3B1YVNjcDB0eGJhWHNTeThrSnhRPT1fMDE0NDU3RDUxRjY4RDAxN0Y5MjMyMkI0NTdfWlVXMDJYQXIwOFE9.aIYLolI8nBj-M3SO5t7KWC-F_X45UizJb57uVapQr0y4EUAyG6qh-I_ZtwZDsilX_f_tUjSaIxlFe4HprM6seg"
    }`

**Comment by Spanky2** [comment]
> {
    "verificationId" : "DEP_CHAINING_VALUE",
    "version" : 1,
    "verificationName" : "Verkettung der maschinenlesbaren Codes im RKSV-DEP-Export",
    "verificationTextualDescription" : "In diesem Modul wird überprüft, ob die Belege im exportierten RKSV-DEP korrekt verkettet sind.",
    "verificationState" : "FAIL",
    "verificationResultDetailedMessage" : "Die Verkettung zwischen dem vorigen Beleg und dem aktuellen Beleg ist ungültig. Bitte überprüfen Sie die Berechnung des Verkettungswerts oder die Abfolge der maschinenlesbaren Codes im exportierten RKSV-DEP.",
    "input" : {
      "CHAINING_VALUE_PREVIOUS_RECEIPT" : "6uM2Vzpz3GE=",
      "RK_SUITE_ID" : "R1",
      "CHAINING_INPUT" : "eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMl9EZWZhdWx0LUNhc2hib3hfMV8yMDE3LTA1LTIzVDA5OjI2OjU0XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF9DZ3B1YVNjcDB0eGJhWHNTeThrSnhRPT1fMDE0NDU3RDUxRjY4RDAxN0Y5MjMyMkI0NTdfWlVXMDJYQXIwOFE9.aIYLolI8nBj-M3SO5t7KWC-F_X45UizJb57uVapQr0y4EUAyG6qh-I_ZtwZDsilX_f_tUjSaIxlFe4HprM6seg"
    }

**Comment by ErichFreitag** [comment]
Die Einträge im DEP-Export sind insoferne falsch, als dass der Signaturteil nicht BASE64URL-codiert ist und Padding-Zeichen enthalten sind. Bei der QR-Code-Prüfung kann kein Verkettungswert geprüft werden, da immer nur ein Code geprüft wird, aber keine Abfolge.

**Comment by Spanky2** [comment]
Danke vielmals für die Rückmeldung!!!

Ich werde dies prüfen und gebe dann Bescheid!

**Comment by Spanky2** [comment]
Ich habe nun immer (aus Testzwecken) den Signaturteil auf 'U2ljaGVyaGVpdHNlaW5yaWNodHVuZyBhdXNnZWZhbGxlbg' ('Sicherheitseinrichtung ausgefallen') gesetzt, um diesen Fehler auszuschliessen.

Trotzdem erhalte ich die selbe Fehlermeldung.

Könnten Sie mir bitte hier nochmals weiterhelfen!
Danke!!!
[Output.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1035005/Output.zip)
[Input.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1035006/Input.zip)

**Comment by Spanky2** [comment]
Ich bräuchte nochmals Ihre Hilfe!

Wenn der Signaturteil Base64Url encode, dann kommt beim Startbeleg folgender Fehler:
Woran erkennen Sie die Padding-Zeichen?
DANKE!

> {
      "verificationId" : "CRYPTO",
      "version" : 1,
      "verificationName" : "Kryptographische Prüfungen",
      "verificationTextualDescription" : "In diesem Modul und den dazugehörigen Submodulen werden die kryptographische Validität des Umsatzzählers und des Signaturwerts überprüft. Für den Umsatzzähler kann eine detaillierte Prüfung nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
      "verificationState" : "FAIL",
      "verificationTimestamp" : "2017-05-29T10:09:09.546+02:00",
      "verificationResultList" : [ {
        "verificationId" : "CRYPTO_SIGNATURE",
        "version" : 1,
        "verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
        "verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.",
        "verificationState" : "FAIL",
        "verificationResultDetailedMessage" : "Die kryptographische Gültigkeit der Signatur ist nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen.",
        "verificationTimestamp" : "2017-05-29T10:09:09.546+02:00"
      }, {
        "verificationId" : "CRYPTO_TURNOVER_COUNTER",
        "version" : 1,
        "verificationName" : "Kryptographie: Entschlüsselung des Umsatzzählers",
        "verificationTextualDescription" : "Es wird die Entschlüsselung des Umsatzzählers überprüft. Eine Aussage über die Korrektheit kann nur beim Startbeleg durchgeführt werden, da nur in diesem Fall der entschlüsselte Wert bekannt ist (Umsatzzähler = 0).",
        "verificationState" : "PASS",
        "verificationTimestamp" : "2017-05-29T10:09:09.669+02:00"
      }

**Comment by ErichFreitag** [comment]
Die Padding-Zeichen sind die "=" am Ende, die müssen im DEP-Export entfernt werden - siehe A-SIT-Dokumentation. 
Ihr DEP-Eintrag von oben input.zip, letzter Teil der Sigantur: ...wZDsilX/f/tUjSaIxlFe4HprM6seg==

**Comment by Spanky2** [comment]
Diese Padding-Zeichen habe ich ebenfalls entfernt.
Trotzdem erhalte die angegebenen Fehlermeldung mit dem folgenden Input.
[Input.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1035277/Input.zip)
[Output.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1035278/Output.zip)

Danke nochmals!

**Comment by Spanky2** [comment]
Wenn die Signatur, welche ich vom HSM GlobalTrust mit folgendem Code bekomme, Base64Url kodiere oder/und die Padding-Zeichen '=' entfernen, dann funktioniert die Überprüfung der kryptographischen Gültigkeit der Signatur nicht.

Wenn die Signatur, wie am Anfang beschrieben, verwendet wird, dann funktioniert die Verkettung nicht.

Wie gesagt, wir haben erfolgreich ATrust-Karte, ATrust-HSM, GlobalTrust-Karte eingerichtet.
GlobaltTrustHSM macht jedoch Schwierigkeiten.

Ich bitte nochmals um einen Tipp, damit ich den Fehler finden kann.

Wäre das ZTP-Prüfwerkzeug von Herrn Prentner für die Fehlersuche besser geeignet?

DANKE für einen Tipp!
