### ISSUE TITLE
Überprüfung der kryptographischen Gültigkeit der Signatur

### ISSUE THREAD

**Issue by Harbauer** [a-sit-plus/at-registrierkassen-mustercode#604]
Schönen Nachmittag,

leider kann ich den bekannten Fehler nicht auflösen:

"verificationName" : "Kryptographie: Überprüfung der kryptographischen Gültigkeit der Signatur",
"verificationTextualDescription" : "In diesem Modul wird die kryptographische Gültigkeit der Signatur mit Hilfe des öffentlichen Schlüssels überprüft.","verificationState" : "FAIL"

Ich übergebe folgenden Klartext (START-Beleg) an HSM(PrimeSign):

_R1-AT3_KASSA01_25_20170523T14:03:11_0,00_0,00_0,00_0,00_0,00_D6S7nVluSN4=_1529C15CCF83_ypi5pEcqgd8=

und erhalte als JWS dann zurück:

eyJhbGciOiJFUzI1NiJ9.L2hvbWUvZmFpZS9QcmltZVNpZ24vUjAwMDAwMjkwMS50eHQ.GulUkPS97Exb0CjwwCD3joZ61xjpdLeNzHq2ol8wo1DBmMnwe4TI_MTO9MoG88DCf6pLmL2o-9epIvCjJY3P8w

Habe schon viele Einträge zu diesem Thema durchgesehen und Checkliste verwendet, bin aber jetzt ratlos -  kann jemand weiterhelfen ? 

[CMF.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1022281/CMF.txt)
[DEP.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/1022282/DEP.txt)

**Comment by Harbauer** [comment]
Hallo Hr. Freitag, entschuldigen Sie bitte

es geht um diesen JWS:

eyJhbGciOiJFUzI1NiJ9.X1IxLUFUM19LQVNTQTAxXzI1XzIwMTctMDUtMjNUMTQ6MDM6MTFfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX0Q2UzduVmx1U040PV8xNTI5QzE1Q0NGODNfeXBpNXBFY3FnZDg9.061rjv8f-fVhqq0XOJxiLzDwPNZ-dMoV0dTsyzwsyG5yuahOxg3Ekwo3xny6z_e9Tl_eV6nkviZqulX6GXszxA   

(die restlichen Angaben beziehen sich auf diesen Fall)

**Comment by ErichFreitag** [comment]
Da kann ich dann leider auch nicht weiterhelfen - die Länge der Signatur ist korrekt, mehr lässt sich nicht sagen.

**Comment by cmaxmedia** [comment]
Könnte das am falschen Datumsformat liegen?

**Comment by Harbauer** [comment]
Danke für den Hinweis, aber daran liegt es nicht - wird so übergeben:

_R1-AT3_KASSA01_25_2017-05-23T14:03:11_0,00_0,00_0,00_0,00_0,00_D6S7nVluSN4=_1529C15CCF83_ypi5pEcqgd8=

**Comment by cmaxmedia** [comment]
Um Ihnen helfen zu können, sei die Frage gestattet, ob die restlichen Daten auch korrekt sind:
Typ: Startbeleg
Beleg-Nr.: 25
Umsatz: 0
Kassen-ID: KASSA01
AES Schlüssel: FI+C8G3NrEEgdA5xBFdxfwraDgAWFvG2lWKCV9D0Wlc=
dann kommt bei mir der folgende verschlüsselte Umsatz raus:
Ungekürzt: D6S7nVluSN5UOL4f/cvykw==
Gekürzt: D6S7n

Vielleicht versuchen Sie mal mit dem ungekürzten AES-Umsatz zu signieren...

**Comment by cmaxmedia** [comment]
Die Eingaben können Sie hier verifizieren: http://tatutata.at/_sites/rksv/

**Comment by Harbauer** [comment]
Danke "cmaxmedia", aber noch kein Fortschritt:
Wenn ich Länge 16 (oder auch  05 getestet) vom Encrypted-BASE64-Umsatz-Zähler nehme, ändert sich nichts (im \OUTPUT-Ergebnis vom Prüftool). Werde morgen das FON-APP-Ergebnis gegenprüfen, ob von dort die gleiche Fehlermeldung kommt.

**Comment by Harbauer** [comment]
Start-Beleg wurde mit anderer Beleg-Nummer neu erstellt:
Die BMF-APP akzeptiert jetzt den Start-Beleg, 
die "CRYPTO-Verification" vom Prüftool geht nach wie vor auf "FAIL".
Versuche das noch zu klären und lasse den Fall noch offen.

**Comment by ErichFreitag** [comment]
Dann bleiben nicht mehr viele Fehlermöglichkeiten offen, konkret alles, was zwischen Prüfapp und Prüftool unterschiedlich ist, also wohl Signatur-Eintrag im DEP oder Zertifikatseintrag im cryptoMaterial.

**Comment by Harbauer** [comment]
Ich kann den Fehler nicht erkennen:

Zertifikat aus CMF wurde geprüft: mit Copy und Paste (https://redkestrel.co.uk/products/decoder/). Wird richtig erkannt.

Habe die Daten verglichen:

(Zeilenumbrüche nur hier zusätzlich eingefügt)

Daten-Input für das BMF-APP (AKZEPTIERT; mit QR-Reader ausgelesen)
_R1-AT3_KASSA01_2896_2017-05-19T07:37:00_0,00_0,00_0,00_0,00_0,00_zxq0rcJIOkk=_1529C15CCF83_ypi5pEcqgd8=_
4UFtgwle9gVDpHS+
CC8ey4DhOVewMEMQsMQ5qKUUFpz8PpQuZsRaJ9pbamPFilQ60GvhqXneinID/xN/AqtxNg==

Daten-Input für das Prüftool (FAIL)
eyJhbGciOiJFUzI1NiJ9.
X1IxLUFUM19LQVNTQTAxXzI4OTZfMjAxNy0wNS0xOVQwNzozNzowMF8wLDAwXzAsMDBfMCwwMF8wLDAwXzAsMDBfenhxMHJjSklPa2s9XzE1MjlDMTVDQ0Y4M195cGk1cEVjcWdkOD0.
4UFtgwle9gVDpHS-CC8ey4DhOVewMEMQsMQ5qKUUFpz8PpQuZsRaJ9pbamPFilQ60GvhqXneinID_xN_AqtxNg

Für die QR-Code-Aufbereitung wird der 3.String aus der JWS von BASE64 nach BASE64URL konvertiert. Ist in diesem Step ein Fehler ?

**Comment by ErichFreitag** [comment]
Soweit sehe ich keinen Fehler.

Was wir auch schon hatten waren (mit einem üblichen Editor nicht sichtbare) Sonderzeichen im Zertifikatsstring (Zeilenumbrüche, dez. 209 oder ähnliches).
