### ISSUE TITLE
Eigenverbrauch

### ISSUE THREAD

**Issue by wpichler** [a-sit-plus/at-registrierkassen-mustercode#611]
Hallo alle miteinander,

kann mir jemand verraten wie der Eigenverbrauch Umsatztechnisch und von der RKSV her zu bewerten ist ?

Meiner Ansicht nach - ist Eigenverbrauch nichts anderes als ein normaler Verkauf. Da aber da natürlich kein Bar Umsatz gemacht wird, hätte ich das einfach in einem eigenen Journal mitgeführt.
Der Summenspeicher wird aber trotzdem erhöht.

Ist das soweit korrekt ?

**Comment by Flanelli** [comment]
Rein auf die RKSV bezogen ist ein Eigenverbrauch kein verpflichtend zu signierender Umsatz.
Wenn Sie das freiwillig signieren dann ist das aber nauch in Ordnung.
Ansonsten sollten EV immer penibelst dokumentiert werden damit die Prüfer auch Freude daran haben :-)

**Comment by ErichFreitag** [comment]
Eigenverbrauch unterliegt der Umsatzsteuer, ist aber kein Barumsatz. Das im 0%-Steuersatz freiwillig mitzuführen wird nicht schaden. Wenn sie den Umsatzzähler erhöhen, müssen sie es auch so machen.

**Comment by wpichler** [comment]
Also den Brutto Wert im 0% Steuersatz ins RKSV rein - aber Umsatzsteuertechnisch wie einen normalen Verkauf behandeln. Habe ich das richtig verstanden ?
Ist es auch erlaubt den Eigenverbrauch freiwillig wie einen normalen Barumsatz zu behandeln - oder muss der Eigenverbrauch - wenn er schon freiwillig ins RKSV kommt als 0% Umsatz reinkommen ?

**Comment by ErichFreitag** [comment]
Erster Absatz - ja. Das ist praktisch immer möglich.

Zweiter Absatz - dazu gibt es meines Wissens nach keine Detailaussage. Sie könnte es  wohl in Analogie zu einer Möglichkeit der Barzahlung von Rechnungen behandeln - also die Beträge in den tatsächlichen Steuersätzen anführen und über das Kassenjournal nachvollziehbar machen, dass es sich um einen Eigenverbrauch handelt, damit die Umsatzsteuer nicht doppelt anfällt bzw. vermutet wird. Und am Beleg einen entsprechenden Hinweis anbringen.

Eine Entscheidungslogik und Herausrechnung in der Buchhaltung braucht es wohl immer, egal wie sie es lösen.

**Comment by wpichler** [comment]
Besten Dank - ich werde dann die zweite Variante wählen.
