### ISSUE TITLE
Behandlung von Kaution

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#613]
Hallo,

habe einen Kunden (Autovermietung) der für die Vermietung eine Kaution verlangt. Die Kaution wird nach der Rückgabe des Fahrzeuges retourniert. Dannach wird die Leistung verrechnet.

Wie soll die Kaution behandelt werden? Ist es ein BAR-Umsatz und soll in diesem Fall ein Beleg im Sinne von RKSV ausgestellt werden oder? Wie soll die Rückgabe der Kaution behandelt werden? Ist es dann eine Gutschrift?

Kaution beträgt: 500 EUR (Dieser Betrag dienst als Kaution für die ordnungsgemäße Rückgabe des Fahrzeugs und wird somit wieder üblicherweise retourgegeben.)

Danke für die Rückmeldung

Mit freundlichen Grüßen

**Comment by ErichFreitag** [comment]
Ein Kaution ist kein Barumsatz, daher nicht RKSV-pflichtig, sondern nur ein Depot-Wert. Freiwillig kann es im 0%-Steuersatz mitgeführt werden, bei der Retournierung als Gutschrift oder als Storno (bei Storno allerdings in einer eigenen Transaktion).

**Comment by AlgoLinz** [comment]
Danke Herr Freitag :)
