### ISSUE TITLE
Belegnummernkreis der Kasse nachträglich ändern

### ISSUE THREAD

**Issue by BernhardMaier** [a-sit-plus/at-registrierkassen-mustercode#616]
Hallo,

ich habe eine Frage zum Belegnummernkreis innerhalb der Kasse (nicht zum Rechnungsnummernkreis): ist es möglich, diesen nachträglich zu ändern? Einem Kunden gefällt die Nummerierung innerhalb der Kasse nicht, deshalb besteht der Wunsch, den Belegnummernkreis zu ändern.
Laut § 9 Absatz 2 Ziffer 2 der RKSV ist eine "fortlaufende Nummer des Barumsatzes" vorgesehen, diese wäre dann ja nicht mehr vorhanden? Kann man eventuell mit einem Geschäftsjahreswechsel eine Änderung vornehmen?

# Beispiel

Aktueller Nummernkreis: 2017000x
Neuer Nummernkreis: x

**Comment by ErichFreitag** [comment]
"Nachträglich ändern" - (in bestehenden Belegen) nein; aber sie können z.B. zum Jahreswechsel einen neuen Nummernkreis einführen, das begründen und dokumentieren. Was sie verhindern müssen, ist, dass es jemals zu identen Belegnummern kommt (also in z.B. 10 Jahren die Belegnummer x auf 2017000x hochklettert).

Die Belegnummern müssen zwar fortlaufend sein, dürfen aber Lücken haben und dürfen nach RKSV -> BAO -> UStR 2000 Abschnitt 11.1.6.6 auch einer Systematik folgen (also z.B. eine Jahreszahl zu Beginn haben).

**Comment by BernhardMaier** [comment]
Vielen Dank für Ihre rasche und hilfreiche Antwort.
