### ISSUE TITLE
Trainingsbeleg

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#62]
Trainingsbelege entstehen in der Praxis z.B.: während Einweisungen von Kassierern / Kassiererinnen.
Normalerweise werden während solcher EInweisungen besonders auch Stornobuchungen trainiert, weil das ein alltäglicher Vorgang an einer Kasse ist.
Leider kann die Kombination aus Trainingsbeleg und Stornobeleg nicht abgebildet werden. In beiden Fällen wird im verschlüsselten Feld des Umsatzzählers ein Sonderwert eingetragen (TRA oder STO).
Was muss im beschriebenen Fall eingetragen werden? Vielleicht beides?

**Comment by asitplus-pteufl** [comment]
Ich verweise Sie dazu auf dieses "Issue".
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/50
Ich lasse dieses hier offen, bei weiteren Fragen einfach hier posten, sonst schließe ich dieses Issue nachher.

**Comment by michaelkorb** [comment]
Danke, das war sehr hilfreich.
