### ISSUE TITLE
Timestamp in der Signatur?

### ISSUE THREAD

**Issue by mandihof** [a-sit-plus/at-registrierkassen-mustercode#621]
Hallo,
ich stell mir schon seit längerem die Frage ob ein Timestamp beim Signieren mitprotokolliert wird.

Im Belegkey wird ja Datum und Uhrzeit der Belegerstellung angegeben
_R1-AT1_2_1006460_**2017-04-11T11:42:57**_0,21_0,00_.....

Wird beim Signieren nochmals irgendwo ein Timestamp geseichert? Also kann überprüft werden, ob der Beleg auch zu diesem Zeitpunkt signiert wurde?

danke,
lg Manfred

**Comment by Ralf-Friedl** [comment]
Im Text oben bewirken die Unterstriche eine kursive Schrift statt dass die Unterstriche dargestellt werden.

Beim Signieren wird nicht überprüft, ob Datum/Zeit des Belegs korrekt ist. Zum einen hat die Signaturkarte keine Uhr und kennt daher das korrekte Datum nicht. Zum anderen weiß die Signaturkarte nichts über den Inhalt und die Bedeutung des Strings, sie bekommt nur einen Hash übergeben und signiert diesen. Weiterhin wäre ein Test mit den Beispieldaten nicht möglich, da diese ein Datum in der Vergangenheit haben.

Ein externer Signatur Anbieter könnte die Angaben überprüfen, es ist jedoch wahrscheinlicher, dass der Anbieter den Beleg automatisch mit der aktuellen Zeit erstellt.

Es würde aber beim Überprüfen auffallen, wenn im DEP ein späterer Eintrag eine frühere Zeit hat als ein vorheriger. Ausgenommen bei Betrieben, die in der Nacht geöffnet haben, wenn die Zeit von Sommerzeit 03:00 wieder auf Winterzeit 02:00 umgestellt wird.

Andererseits, wer hätte etwas davon, einen falschen Zeitpunk anzugeben?

**Comment by mandihof** [comment]
ah, dachte mir schon, dass bei meinem ausschnitt etwas nicht passt.
haben tut davon wahrscheinlich niemand etwas, war rein interesse halber.

danke!
