### ISSUE TITLE
Vorgangsweise nach Rücksicherung

### ISSUE THREAD

**Issue by HeinziAT** [a-sit-plus/at-registrierkassen-mustercode#627]
Angenommen ich habe eine Computerkassa, die nächtlich gesichert wird. Nun kommt es unter Tags zu einem Problem, das eine Rücksicherung erforderlich macht (Festplatte geht ein, Virenbefall, etc.).

Im rückgesicherten DEP fehlen nun natürlich die Belege vom Tag des Crashes, d.h. würde man mit dieser rückgesicherten Kassa weiterarbeiten, würde man "fortlaufende Nummern" wiederverwenden. Wenn keine Durchschrift der Belege in Papierform existiert, lässt sich ja nicht einmal feststellen, wie viele Nummern fehlen.

D.h. die einzige rechtskonforme Lösung in so einem Fall scheint mir zu sein, eine Außerbetriebnahme der alten Kassenidentifikationsnummer zu melden und die Computerkassa mit einer neuen Kassenidentifikationsnummer und einem leeren DEP neu in Berieb zu nehmen.

Stimmt das so oder habe ich irgendeine alternative Lösung übersehen?

**Comment by ErichFreitag** [comment]
Das stimmt so. Sobald sie das DEP und den letzten Beleg nicht mehr rekonstruieren können bleibt nichts anderes übrig. Sie könnten einzig mit der selben Kassen-ID wieder neu anmelden, das empfehle ich aber nicht, um die Lebenszyklen sauber trennen und dokumentieren zu können.

Was sie auch machen sollten: DEP rückspielen, Schlussbeleg erzeugen, DEP sichern und dokumentieren, dass es tagsüber xx Belege gegeben hat, die wegen des Defekts verloren gingen.

**Comment by HeinziAT** [comment]
Alles klar, danke für die Bestätigung!
