### ISSUE TITLE
DEP export interval selection

### ISSUE THREAD

**Issue by slavok1** [a-sit-plus/at-registrierkassen-mustercode#63]
I would like to ask one question about defining the range of the DEP export operation. 

Is it sufficient define the scope of the DEP data export by boundary days in a way from - to ?
(e.g. user can select 1st and last day of the daily interval and cash register creates the DEP export file, which includes all documents issued from first to last day in the selected interval)

I am asking because it is unclear whether it is required more detailed interval selection for DEP export (from document to document e.g with number from document to document 156 with number 879). Hope the daily interval selection is enough. (e.g from 2nd May to 10th June)

**Comment by asitplus-pteufl** [comment]
you need to guarantee that an interval can be selected (...vorgegebenen Zeitraum auf einen externen Datenträger). This interval could go back to the creation of the initial receipt (Startbeleg).

**reference:**
https://www.ris.bka.gv.at/Dokumente/BgblAuth/BGBLA_2015_II_410/BGBLA_2015_II_410.html

§ 7. (1) Jede Registrierkasse hat ein Datenerfassungsprotokoll zu führen, in dem jeder einzelne Barumsatz zu erfassen und abzuspeichern ist. Für jeden Barumsatz sind zumindest die Belegdaten gemäß § 132a Abs. 3 BAO festzuhalten.

**(1 to 4) skipped...**

(5) Das Datenerfassungsprotokoll einer Registrierkasse muss ab 1. Jänner 2017 jederzeit auf einen externen Datenträger im Exportformat Datenerfassungsprotokoll laut Z 3 der Anlage exportiert werden können.


**And**

§ 19.
(2) Auf Verlangen der Organe der Abgabenbehörde hat der Unternehmer das Datenerfassungsprotokoll für einen vom Organ der Abgabenbehörde vorgegebenen Zeitraum auf einen externen Datenträger zu exportieren und zu übergeben. Der Datenträger ist vom Unternehmer bereitzustellen.

**Comment by slavok1** [comment]
Thanks for answer.
You have written that (...vorgegebenen Zeitraum auf einen externen Datenträger) so my question is what is the smallest time unit for selection of the time period? Is it day, hour, minute or second? 
Hope the day is enough. 

Second problem is that DEP-export file does not contain all data prescribed in § 132a Abs. 3 BAO like following:

1. identification of the entrepreneur 
2. description and price of the selling item (goods or service)

and one information which can be derived from DEP
3. total value of the transaction which will be paid (so we can take this value as included in the DEP as sum of all VAT groups)

So information in point 3 is OK, as it can be derived from DEP-file content for every document. 

Information in point 1. is static and it is not changeable during long time, so at creating the DEP-export 
file there is no problem to create one more file with such information like name, address, VAT ID and some other identification data about cash register owner.

But there is still problem with point 2 which is information about every sold item (price and item's name) which is not contained in the DEP-export file.

Is there any interpretation or commentary how this information/data should be provided (if at all) and in what form?
