### ISSUE TITLE
Problem mit dem CRYPTOGRAPHIC-MATERIAL-FILE

### ISSUE THREAD

**Issue by cotasgmbh** [a-sit-plus/at-registrierkassen-mustercode#630]
Hallo, 
ich habe eine Frage zum CRYPTOGRAPHIC-MATERIAL-FILE.

Unser Zertifikat liegt bei Primesign. Folgende Werte setze ich ein:

1. AES-Key (AAA)

2. Hex Seriennummer vom Zertifikat (BBB)

3. öffentlicher Schlüssel vom Zertifikat (CCC)

Ich bekomme immer die Meldung: Error while parsing the Input File. Oder kommt dort ein anderer Schlüssel rein?

Das Zertifikat rufe ich über folgenden Befehl ab:

https://rs-xxx.ps.prime-sign.com/rs/keys/yyy/certificate.pem

Wobei xxx und yyy natürlich durch die echten Werte ersetzt wurden.

{
  "base64AESKey" : "AAA",
  
"certificateOrPublicKeyMap" : {
    
"BBB" : {
      
"id" : "BBB",
      
"signatureDeviceType" : "PUBLIC_KEY",
      
"signatureCertificateOrPublicKey" : "CCC"
    
    
}

}
}

**Comment by ErichFreitag** [comment]
Es gehört das Zertifikat eingetragen, nicht der Public Key. Beispiel:

 "signatureDeviceType" : "CERTIFICATE",
      "signatureCertificateOrPublicKey" : "MIIFUDCCAzigAwIBAgIEf02H..."

**Comment by cotasgmbh** [comment]
Ok, die Meldung bleibt die gleiche. Vielleicht habe ich einen Denkfehler. Das Zertifikat bekomme ich doch über die *.pem Datei?

**Comment by ErichFreitag** [comment]
So ist es. Sie müssen nur alle Zeilenumbrüche daraus entfernen.

**Comment by cotasgmbh** [comment]
Das war es. Danke...
