### ISSUE TITLE
Übermittlung der Belege an Finanzamt

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#633]
Hallo,

habe heute ein Anruf einer Steuerberaterin (Steuerberaterin einen der Kunden) bekommen mit der folgenden, verzweifelten Frage/Anforderung:

_Die Kasse übermittelt keine Belege an das Finanzamt, es sind keine Belege im FinanzOnline zu sehen. Vorschlag von Finanzamt war die Kasse abzumelden und eine neue anmelden._

Im FinanzOnline sind außer dem Startbeleg tatsächlich keine weiteren Belege - soll auch so sein.

Meine Frage: habe ich da etwas übersehen oder?
Eigentlich sollten nur Start- und Jahresbelege verpflichten entweder mit der App oder mittels WebService übermittelt werden.

Alle anderen Belege (zwischen dem Start- und Jahresbeleg) bleiben offline auf der Maschine gespeichert. 

Hat jemand ähnliche Gespräche mit Steurberatern bzw. Finanzamt geführt :)

Mit freundlichen Grüßen

**Comment by ErichFreitag** [comment]
Gespräche habe ich keine geführt.

Außer dem Startbeleg, den Jahresbelegen (ab 2018) und eventuell freiwillig geprüften Belegen wird es sonst in Finanz-Online auch nichts an Belegen geben. Ab- und anmelden ist daher sinnlos.

**Comment by eczach** [comment]
wieder einmal ein steuerberaterIn, die sich leider nicht auskennt :-(

**Comment by AlgoLinz** [comment]
Danke für die Rückmeldungen.
Mir war klar dass sich die Steuerberaterin nicht augekannt hat, aber die Aussage der FA-Mitarbeiterin (Steuerprüferin) hat mich überrascht und deshalb mein Post hier :)
