### ISSUE TITLE
Belegnummer Alphanumerisch und in AES-Verschlüsselung (HEX-Auto-Wert?)

### ISSUE THREAD

**Issue by SEHellFire** [a-sit-plus/at-registrierkassen-mustercode#64]
Im Dokument steht zur Belegnummer:

Beschreibung: Hierbei handelt es sich um die Belegnummer des Belegs. Die Belegnummer entspricht einer alphanumerischen Zeichenkette die UTF-8 kodiert wird.
Im Beispiel - Standardbeleg steht dann:
Belegnummer: 366585AB

Nun meine 2 Fragen dazu:
====================
1. Sehe ich das richtig das die Belegnummer immer als Alphanumerische aufsteigende HEX-Zahl in die Belege-Folge sollte?

2. Die HEX-Zahl wird dann auch als HEX-String mit der Kassen-ID zusammen als IV für die AES-Verschlüsselung benutzt oder?

Edit: Bonusfrage :-)  Der HEX-String der Buchungsnummer soll dann immer kleine (abcdef) oder immer große (ABCDEF) UTF-8-Hex-Werte haben?

**Comment by anzun** [comment]
Belegnummer ist als String zu behandeln

**Comment by asitplus-pteufl** [comment]
Es wird nur von einer alphanumerischen Zeichenkette gesprochen die UT8-kodiert wird. Dass es sich um einen HEX-Wert handelt wird nicht erwähnt. D.h. auch Buchstaben ungleich (A-F) sind erlaubt (auch Klein/Großschreibung).

**Comment by anzun** [comment]
Im Detail auf Seite 10:
Anmerkung zu UTF-8 Kodierung: Diese Anmerkung betrifft vor allem die Elemente Kassen-ID und Belegnummer: Um hier keine wesentlichen Einschränkungen zu haben, wird UTF-8 für die Kodierung dieser Elemente verwendet. Es sollte dennoch beachtet werden, dass diese Daten – vor allem bei der manuellen Registrierung einer Kasse – vom Unternehmer eingegeben werden müssen. Es empfiehlt sich daher eine für den Unternehmer möglichst benutzerfreundliche Zeichenmenge zu verwenden, die z.B. UTF-8 Escape Sequenzen vermeidet

**Comment by SEHellFire** [comment]
Und die Belegnummer sollte möglichst kurz sein um den Maschinenlesbaren Code klein zu halten. Ok, Danke.
