### ISSUE TITLE
Jahresbeleg Datum 

### ISSUE THREAD

**Issue by xa79** [a-sit-plus/at-registrierkassen-mustercode#640]
Hallo!

Ich hätte eine Frage betreffend Datum des Jahresbelegs:

Bei uns werden der Monat- und Jahresbeleg automatisch generiert.
Vor jeder Rechnungserstellung wird geprüft ob ein Monats bzw. Jahresbeleg gedruckt werden muss.

Wir haben nun einen Kunden der sein Geschäft Mitte Dezember zu und erst Ende Jänner (oder sogar noch später) wieder aufsperrt. Der Jahresbeleg würde daher am z.B. 31.01.2018 vor der ersten Rechnung gedruckt. 

Die Signatur des Jahresbeleg würde daher mit dem Belegdatum 31.01.2018 erstellt. Ist dies erlaubt oder muss ich den Jahresbeleg mit Belegdatum 31.12.2017 23:59:59 erstellen?

lg

**Comment by ErichFreitag** [comment]
Sie können
- den Jahresbeleg als letzten Beleg Mitte Dezember generieren (wird wohl wegen der Automatik schwierig)
- als ersten Beleg im Jänner generieren

Was sie auf alle Fälle machen müssen ist, den Jahresbeleg bis zum 15.02. zu prüfen. Wenn also nicht sichergestellt ist, dass Ende Jänner aufgesperrt wird, ist eventuell eine händische Erstellung (im Dezember) zu überlegen.

**Comment by xa79** [comment]
Besten Dank für Ihre prompte Antwort!!

Verstehe ich das richtig das ich (nur rein theoretisch) den Jahresbeleg auch erst am 14.02 erstellen kann (wenn vorher nicht aufgesperrt wurde)?

**Comment by ErichFreitag** [comment]
Bitte gerne. Rein theoretisch auch am 15.02.

Nachdem es klingt, als wäre es nicht sicher, wann genau aufgesperrt wird, macht die händische Erstellung des Jahresbelegs im Dezember gemeinsam mit dem Jahresabschluss vielleicht mehr Sinn.

**Comment by xa79** [comment]
Besten Dank für die Info!

**Comment by AxelKutschera** [comment]
Zusammenfassung auch unter https://www.xing.com/communities/posts/jahresendebeleg-wann-darf-der-gemacht-werden-1014253531?comment=35619960
