### ISSUE TITLE
Frage zum Jahresbeleg

### ISSUE THREAD

**Issue by MichaelLechthaler** [a-sit-plus/at-registrierkassen-mustercode#642]
Bei unserer Registrierkassenimplementierung werden alle Monatsbelege vor dem erstellen eines beliebigen Belegs im neuen Monat erstellt. Findet beispielsweise der erste Verkauf im Januar am 8. Januar statt, wird der Monatsabschluss Dezember ebenfalls am 8. Januar erstellt. Bei einem Workshop bei A-Trust wurde mir das als gültiges Vorgehen beschrieben und lässt sich meines Erachtens ohne Benutzeraktion auch nicht anders lösen.

Da der Jahresbeleg dem Monatsbeleg für Dezember entspricht, würde im obigen Beispiel nun der Jahresbeleg 2017 erst am 8. Januar erstellt werden und wird auch erst dann an FON übermittelt. Im Moment sehe ich nun überall den Hinweis, dass der Jahresbeleg zwingend bis zum 31.12.2017 zu erstellen ist. Das schlägt sich nun natürlich mit unserem Vorgehen. Meine Frage ist nun: Ist der 31.12.2017 tatsächlich der letztmögliche Tag für den Jahresbeleg 2017 oder darf der Jahresbeleg wie beschrieben einfach der erste Beleg 2018 sein?

Danke und schöne Grüße
Michael

**Comment by ErichFreitag** [comment]
Es gibt Normalfälle und einige Sonderfälle (Saisonbetriebe, ...). Ich möchte daher "zwingend" nicht verwenden, weil es nicht auf jede Situation passt.

Ihr Vorgehen ist OK. Sie müssen nur sicherstellen, dass der Jahresbeleg bis 15.02. geprüft wird.

**Comment by MichaelLechthaler** [comment]
Hallo Herr Freitag,

vielen Dank für die Klärung. Wir haben mittlerweile unseren Kunden gesagt, sie sollen am 31.12. einfach manuell einen Nullbeleg erstellen, prüfen und ablegen. Damit sollten wir dann auf jeden Fall auf der sicheren Seite sein.

Schöne Grüße
Michael
