### ISSUE TITLE
Frühest möglicher Prüfungszeitpunkt des Jahresbeleges via APP

### ISSUE THREAD

**Issue by Flanelli** [a-sit-plus/at-registrierkassen-mustercode#643]
Eigentlich sollte man annehmen, dass diese Frage überflüssig ist aber
angesichts der teilweise recht nebulös verfaßten Gesetzes- bzw. Erlaßtexte stelle ich sie dennoch ...

Der Zeitpunkt der Erstellung des Jahresbeleges ist unstrittig aber der frühest zugelassene
Prüfzeitpunkt in FON ist nicht so eindeutig definiert.
Es wird lediglich vom SPÄTESTEN Zeitpunkt, also dem 15. Feber des FOLGEJAHRES gesprochen aber nicht vom FRÜHEST MÖGLICHEN Zeiitpunkt der Prüfung. So könnte man eventuell annnehmen, dass die Prüfung FRÜHESTENS erst ab 01. Jänner des FOLGEJAHRES erlaubt ist.

Eigentlich sollte nichts dagegensprechen wenn im Zuge des Jahresabschlußes in der Reg-Kassa
nach Erstellung des Jahresbeleges dieser auch gleich in FON gepüft werden kann.
Das wäre dann z.B, am 30.12.2017 um 19 Uhr nach Geschäftschluß und  Jahresabschlußes der Kassa
Stellt sich eben die Frage, ob bei der Prüfung moniert wird weil das **_Prüfdatum_** des 
Jahresbeleges mit Erstelldatum 30.12.2017 _**nicht 2018**_ ist sondern auch noch **_2017_**

**Comment by ErichFreitag** [comment]
Ich sehe das entspannt.

a) für Saisonbetriebe muss/sollte auch eine Prüfung des Jahresbelegs z.B. im September 2017 möglich sein

b) was ich nicht weiß, ist ob tatsächlich auf Jahresbeleg geprüft wird (also auf Barumsatz 0) oder nur auf einen gültigen Beleg mit valider Signatur. Für zweiteres würde sprechen, dass sie ja grundsätzlich jeden Beleg jederzeit prüfen können, also der Sinn des Jahresbelegs ja nur der ist, einmal im Jahr auf eben "alles OK" zu prüfen.

**Comment by Flanelli** [comment]
Sehr geehrter Herr Ing. Freitag,
wie immer erachte ich Ihre kompetenten Aussagen und auch die klaren Äußerungen zu eventuell zweifelhaften Passagen der RKSV als das Maß der Dinge und entspanne mich gerne. :-)
DANKE!

**Comment by AxelKutschera** [comment]
Der erste Nutzen des Jahresbeleges ist, das mit Stichtag 15.2. kontrolliert wird, ob bei jeder aktiven Registrierkasse irgend ein Nullbeleg - seit dem Startbeleg - positiv geprüft wurde. 
Alle Steuerpflichtigen die keine positive Prüfung haben, werden (wenn das Finanzamt Zeit hat?) überprüft.
Vielleicht wird es ein Schreiben an den Steuerpflichtigen geben, in dem er auf die fehlende Prüfung hingewiesen wird.
