### ISSUE TITLE
1 von 160 Kassen Problem mit Status bei Jahresbelegprüfung

### ISSUE THREAD

**Issue by Obritzberger** [a-sit-plus/at-registrierkassen-mustercode#645]
Wir haben rund 160 Kassen in Betrieb.
Bei 1 haben wir offenbar irgendein Problem mit dem Status der Registrierkasse bei FON.
ich denke da ist irgendein "Durcheinander" mit dem Registrierkassenstatus bei FON.
ich wäre für jeden Tip sehr dankbar.

ALLE QR-Codes und das DEP wurden mit dem ASIT Tool OHNE Fehler geprüft.

Aber egal welchen Beleg wir jetzt bei FON via WebService prüfen erhalten wir folgende Fehlermeldung

02.01.2018 14:24:54.087  INFO at.daskellerbuch.dww.Tests.TestBMFCommunicator.belegPruefung (91) - Der übermittelte Beleg ist fehlerhaft.
	verificationId: VERIFICATION_FROM_CASHBOX
	version: 1
	verificationName: Prüfergebnis - Kasse
	verificationTextualDescription: Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.
	verificationState: FAIL
	verificationResultDetailedMessage: Der vorliegende Beleg ist zwar gesetzeskonform zustande gekommen, die Registrierkasse war aber zum Belegerstellungzeitpunkt  noch nicht mittels Startbelegprüfung in Betrieb genommen. Bitte überprüfen Sie, ob in der Zwischenzeit die erforderliche Startbelegprüfung stattgefunden hat.
	verificationTimestamp: Tue Jan 02 14:24:53 CET 2018
		verificationId: RECEIPT_FULL
		version: 1
		verificationName: Detailprüfung des maschinenlesbaren Codes
		verificationTextualDescription: Dieses Modul und die dazugehörigen Submodule überprüfen die Gültigkeit des Belegs. Dabei werden sowohl Formatprüfungen, kryptographische Prüfungen (verschlüsselter Umsatzzähler, Signatur) als auch Prüfungen im Zusammenhang mit dem Status der Kasse bzw. der Signatur-/Siegelerstellungseinheit durchgeführt.
		verificationState: FAIL
		verificationResultDetailedMessage: null
		verificationTimestamp: Tue Jan 02 14:24:53 CET 2018
			verificationId: STATE_CONSOLIDATED
			version: 1
			verificationName: Statusprüfung der Kasse und Signatur-/Siegelerstellungseinheit
			verificationTextualDescription: In diesem Modul und den dazugehörigen Submodulen werden die Zustände der Kasse und der verwendeten Signatur-/Siegelerstellungseinheit und die Ergebnisse der zuvor durchgeführten Prüfungen (vor allem der Belegtyp) ausgewertet. Handelt es sich um einen Startbeleg, wird überprüft ob eine Inbetriebnahme der Kasse möglich ist.
			verificationState: FAIL
			verificationResultDetailedMessage: null
			verificationTimestamp: Tue Jan 02 14:24:53 CET 2018
				verificationId: STATE_CASHBOX
				version: 1
				verificationName: Statusprüfung der Kasse
				verificationTextualDescription: Es wird der Status der Kasse zum Belegerstellungszeitpunkt und zum Prüfzeitpunkt ausgewertet. Die extrahierten Informationen werden im Zusammenhang mit weiteren Beleginformationen betrachtet.
				verificationState: FAIL
				verificationResultDetailedMessage: Bei der Überprüfung des Status der Kasse zum Belegerstellungszeitpunkt bzw. Prüfzeitpunkt wurde ein Fehler festgestellt.
				verificationTimestamp: Tue Jan 02 14:24:53 CET 2018

die Abfrage des Status der Registrierkasse und der Signatureinheit via WebService zeigt REGISTRIERT bzw. IN_BETRIEB.

der Versuch den Startbeleg erneut zu prüfen ergibt:
	verificationId: VERIFICATION_FROM_CASHBOX
	version: 1
	verificationName: Prüfergebnis - Kasse
	verificationTextualDescription: Bei der Belegprüfung wird untersucht, ob die Vorgaben der RKSV in Bezug auf den maschinenlesbaren Code am Beleg und auf die meldepflichtigen Metadaten der Sicherheitseinrichtung befolgt werden. Im Fehlerfall sind die genauen Fehlerinformationen nachfolgend angeführt.
	verificationState: PASS
	verificationResultDetailedMessage: Der vorliegende Beleg wurde bereits zu einem früheren Zeitpunkt erfolgreich geprüft.
	verificationTimestamp: Tue Jan 02 14:24:52 CET 2018

**Comment by ErichFreitag** [comment]
Das ist ein bisschen schwierig nachzuvollziehen. Ich versuche es mal:

Fangen wir hinten an: "der Beleg wurde bereits geprüft" könnte heissen, dass beim Versuch, den Startbeleg erneut zu prüfen von FON erkannt wird, dass es diesen Beleg schon gab.

Nachdem der Status der Registrierkasse auf "registriert" steht dürfte noch keine erfolgreiche Startbelegprüfung stattgefunden haben. Ist der Startbeleg tatsächlich ein korrekter? (also Umsatz 0, ...).

Fazit für mich: es gab für diese Kasse noch keinen korrekten Startbeleg zur Prüfung - warum auch immer.

Nachdem die Kasse somit noch nicht in Betrieb ist können sie diese vielleicht neu aufsetzen und einen neuen Startbeleg erzeugen.

**Comment by Obritzberger** [comment]
Das wird aber dann problematisch mit der Belegverknüpfung - wenn ich JETZT erst einen Startbeleg erstelle passt das ja nicht mehr im DEP.
Der Startbeleg wurde meiner Meinung nach damals OK geprüft - ich nehme aber Kontakt mit unserem Kunden auf um gemeinsam mit Ihm über den FinanzONLINE Zugang MEHR Details erkennen zu können

**Comment by ErichFreitag** [comment]
Darum meinte ich Kasse neu aufsetzen, da sie ja in FON ohnedies noch nicht in Betrieb zu sein scheint.

In FON sehen sie zumindest, was da für Belege geprüft wurden.

**Comment by Obritzberger** [comment]
.... aber nur irrtümlich - kann es da nicht wegen Registrierkassenpflicht zu "unanhemlichkeinten" kommen?
der Kunde ist definitiv registrierkassenpflichtig und wir alle waren der Meinung es ist alles OK

**Comment by ErichFreitag** [comment]
Schauen sie sich mal den Beleg/die Belege in FON an, dann kennen sie wahrscheinlich die Ursache.

Wenn die Kasse in Echtbetrieb war dann machen sie es wie bei jedem gröberen Fehler: DEP sichern, dokumentieren was passiert ist, Kasse abmelden und eine neue Kasse anmelden. Fehler dürfen passieren und die Jahresbelegsprüfung ist unter anderem dazu da, um solche Themen aufzuzeigen und sauber zu lösen.

Wenn sie (ihr Kunde) das DEP nachweisen können und die Kasse irrtümlich betrieben wurde, aber in FON nicht in Betrieb war, dann ist ja "nichts passiert", wenn sie (ihr Kunde) das nachvollziehbar dokumentieren (die Umsätze sind ja bei Bedarf über das DEP vorhanden).

**Comment by Obritzberger** [comment]
Vielen Dank !!!!!!!
