### ISSUE TITLE
Jahresbeleg Erstellung

### ISSUE THREAD

**Issue by AlgoLinz** [a-sit-plus/at-registrierkassen-mustercode#646]
Hallo,

habe im November 2017 einen Fehler in der Software entdeckt, behoben und Update bereitgestellt. Durch diesen Fehler werden drei Jahresbelege hintereinander erstellt.

Ein der Kunden hat die Information über Fehler und auch das Update ignoriert und jetzt habe ich eine Reg-Kasse im Feld mit drei Jahresbelegen (hintereinander erstellt).

Wie soll man jetzt vorgehen? Kann man das ignorieren oder soll man alles dokumentieren, die Kasse abmelden und eine neue anmelden?

Danke im Voraus für die Informationen.

**Comment by eczach** [comment]
nach meiner meinung: der jahresbeleg ist nicht viel mehr als ein nullbeleg, der sicherstellt, dass vor ihm alle umsätze des abgeschlossenen jahres erfasst wurden. nach dem jahresbeleg folgen die umsätze des nächsten jahres. somit ist aus meiner sicht einfach EINER der 3 nullbelege als jahresbeleg zu melden.

**Comment by eczach** [comment]
den fehler zu dokumentieren kann sicher nicht schaden. abmelden würde ich nicht, da ja die verkettung nicht gebrochen ist.

**Comment by AxelKutschera** [comment]
Ich meine: Es ist kein Fehler.

**Comment by ErichFreitag** [comment]
Es ist ein Fehler (?), drei Jahresbelege zu erzeugen, weil es formal nur einen gibt. Insbesondere dann, wenn vielleicht auch noch "Jahresbeleg" aufgedruckt wird. Aus dieser Sicht ist es sicher nicht falsch, dies zu korrigieren.

Es ist aber auch kein Fehler, weil es in jeder Hinsicht völlig egal ist, ob sie einen, zwei oder drei Nullbelege hintereinander erzeugen, solange der Jahresbeleg korrekt generiert und geprüft wird.

Fazit für mich: "Fehler" beheben - ja, warum nicht, aber mit geringer Priorität, da es keinerlei Auswirkungen hat. 

Etwas sonst tun müssen (abmelden, ...): nein, rein gar nichts. Dokumentieren schadet nichts, ist aber mangels jeglicher Auswirkung nicht erforderlich.

**Comment by Flanelli** [comment]
Rein formal kann es m.E. jedenfalls mehr als nur einen Jahresbeleg in gleichen Jahr geben und natürlich auch mit einem Aufdruck "Jahresbeleg" etc.,  so wie es auch mehr als nur einen Monatsbeleg im gleichen Monat mit Aufdruck "Monatsbeleg" etc. 
wie komme ich zu dieser Meinung...
Wenn man z.b. am letzten Tage des Monats den Tagesabschlu0 und danach den Monatsabschluß
durhcgeführt hat und sodann, aus welchen Gründen immer, noch weitere Belege in diesem
Monat buchen möchte/muß dann wird man an dieser Kassa auch einen weiteren Tagesabschluß und
einen Monatsabscgluß machen. Da der letzte Beleg des Monats ein Monatsbelöeg sein muß, ist also
bei einer Nacherfassung in diesem Monat auch ein weiterer Monatsbeleg zu erstellen.
Daher z.b. 2 Monatsbelege für Dezember 2017 und das ist formal jedenfalls nicht falsch.
Gleiches gilt im Falle eines bereits erfolgten Jahresabschlußes samt Jahresbeleg wenn danach noch
weitere Buchungen im aktuellen Jahr erfolgen müssen..
Nimmt man den Monatsbeleg 12 zugleich als Jahresbeleg hat man so gesehen aich 2 "Jahresbelege"

Wie auch immer, wer alles aus der Norm fallende gut dokumentiert wird bei einer Prüfung eher
Wohlgefallan als harsche kritik erfahren.

**Comment by ErichFreitag** [comment]
Ja eh... es ist auch im Erlass explizit darauf hingewiesen, dass - wenn nach einem Jahresbeleg noch Umsätze gemacht werden - noch ein Jahresbeleg danach erstellt werden muss. Drei Jahresbelege hintereinander, vielleicht noch mit selbem Datum und selber Uhrzeit schauen halt komisch aus, sonst nichts.

Ich bin nur immer der Meinung, dass man Themen, die auftreten, auch so dokumentiert und/oder ausbessert, dass man sich auch noch in zehn Jahren auskennt, was damals passiert ist.

Also sind wir uns wohl alle einig, dass es alles andere als tragisch ist, drei Jahresbelege zu haben. Die eigentlich Frage "ob etwas zu tun ist" (Kasse abmelden, ...) ist damit auch eindeutig mit "nein" beantwortet.

**Comment by AlgoLinz** [comment]
Vielen Dank für die ausführlichen Antworten. Werde die Situation mit dem Kunden entsprechend dokumentieren.

Hinweis:
Das "Problem" mit der mehrfachen Erstellung der Belege wurde bereits im November 2017 entdeckt, sofort behoben und die neue Version allen Kunden zur Verfügung gestellt. Dieser Kunde hat die allgemeine Update-Information, 2 persönliche, nur an ihn gerichtete Mails und drei telefonische Anforderungen das Update zu installieren, ignoriert. Aus welchen Grund auch immer :)

Auf jeden Fall danke.

**Comment by AxelKutschera** [comment]
Wieso meine ich, dass es kein "rechtlicher Fehler" ist: 
Man darf beliebig viele Nullbelege - auch mit Aufdruck "Jahresbeleg" - produzieren.
Doch nur einer muss geprüft werden. -- Dieser wird für mich der Jahresbeleg sein.
Zudem ist auch die Prüfung von weiteren Belegen zulässig.

Die Regel lautet: Zumindest ein Nullbeleg muss als Jahresbeleg mit einem positiven Ergebnis geprüft werden.

Daher meine ich, dass es nicht einmal speziell als "Fehler" dokumentiert werden muss.
