### ISSUE TITLE
Finanzonline-Verifikation Aes-Schlüssel, Kassen-ID, Karten-Seriennummer

### ISSUE THREAD

**Issue by anzun** [a-sit-plus/at-registrierkassen-mustercode#65]
Können Sie uns schon einen Ausblick darauf geben, was bei der Finanzonline-Verifikation für KO-Kriterien schlagend werden können?

Die Karten-Seriennummer ist klar.
Bei der Kassen-ID kann ich mir vorstellen, dass geprüft wird, dass nicht zwei verschiedene Kassen beim gleichen Unternehmen mit unterschiedlichen Karten-Seriennummern die gleiche Kassen-ID haben können.
Aber wird es z.B. eine inhaltliche Überprüfung bgzl. Aes-Schlüssels geben? Welche Schlüssel würden abgelehnt werden.

Welche Kombinationen kann es sonst noch geben?

**Comment by asitplus-pteufl** [comment]
Ich kann Sie da nur auf den ersten Abschnitt des Detaildokuments verweisen, dort stehen alle Relationen/Anforderungen an Kassen-ID/AES/Sig-Einheit Kombinationen.

Generell:
-Startbeleg/Jahresbeleg: Müssen natürlich alle Eigenschaften erfüllen (im Wesentlichen die Eigenschaften eines Belegs die auch über das Prüftool geprüft werden.
-Kassen-ID/AES/Sig-Einrichtung: Nach den Kriterien im ersten Abschnitt (z.B. eine Kasse-ID pro Unternehmer...)
-AES: Schlüssel, Inhaltliche Prüfung ist nicht möglich (es gibt keine gültigen/ungültigen Schlüssel). (Längenprüfung kann durchgeführt werden).

**Comment by michaelkorb** [comment]
Ich häng meine Frage mal einfach hier an, da sie thematisch passt.
Wie muss der AES-Key gemeldet werden - Base64-kodiert?

**Comment by asitplus-pteufl** [comment]
Ja, BASE64, dazu wird es aber bald Ankündigungen seitens des BMF geben (für die manuelle, automatisierte Registrierung einer Kasse/Sig-Einrichtung, und das automatisierte Prüfen eines Startbelegs/Jahresbelegs).
