### ISSUE TITLE
Kürzung Umsatzzähler

### ISSUE THREAD

**Issue by st0ne-dot-at** [a-sit-plus/at-registrierkassen-mustercode#66]
Im Absatz 2.5.5 (Aufbereitung des verschlüsselten Umsatzzählers) des Dokuments 2016-03-11-Detailfragen-RKSV-V1.1.pdf wird erklärt, dass nur die ersten 5 Bytes des Verschlüsselten Umsatzzählers verwendet werden können. Genau das ist ja durch Verwendung von AES im CTR/ICM-Modus (stream cipher) möglich. 

Auch in Ihrem Beispielcode wird darauf hingewiesen:
Zeile 347 (CryptoUtil.java):

    byte[] encryptedTurnOverValue = new byte[8]; // or 5 bytes if min.

Nun ist es so, dass im Absatz 2.5.2 (Aufbereiten der Daten für den Verschlüsselungsprozess) erläutert wird, dass die Aufbereitung im BIGENDIAN-Format (Zweierkomplement) erfolgen muss.

D.h.:
Der Umsatzzähler (z.B.: 500 Cent) wird wie folgt in das 16 Byte grosse Byte-Array geschrieben:

    [0, 0, 0, 0, 0, 0, 1, 244, 0, 0, 0, 0, 0, 0, 0, 0]

Wenn Sie nun nur die ersten 5 Bytes für die Verschlüsselung nehmen wäre das:

    [0, 0, 0, 0, 0]

... was nach Ver- und Entschlüsselung natürlich einen Umsatzzähler von 0 Cent ergibt.

Mir ist jetzt unklar wie diese Verkürzung funktioniert.
Also entweder der Umsatzzähler wird im LITTLE-ENDIAN-Format gespeichert:

    [244, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

... was nach der Verkürzung ...

    [244, 1, 0, 0, 0]   ... = 500 (litle endian)
... ergeben würde.

Oder es dürfen nur die 5 least significant Bytes des Umsatzzählers in das mit 0 initalisierte 16 byte Daten-Array kopiert werden. Es müsste dann so vor der Verschlüsselung aussehen:

    [0, 0, 0, 1, 244, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Vielleicht ist es möglich den „Verkürzter verschlüsselter Umsatzzähler" in den Beispielcode einzuarbeiten.

LG,
Rob

**Comment by lebail** [comment]
> Oder es dürfen nur die 5 least significant Bytes des Umsatzzählers in das mit 0 initalisierte 16 byte Daten-Array kopiert werden. Es müsste dann so vor der Verschlüsselung aussehen:
> 
>      [0, 0, 0, 1, 244, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> 
> 

Das ist meiner Meinung nach die einzig sinnvolle Interpretation. Wenn man einen 5-Byte-Umsatzzähler benutzt, dann besteht dieser eben aus genau 5 Bytes (und nicht 8) und sieht im Big-Endian-Format, ergänzt auf 16 Bytes, daher wie oben dargestellt aus.

Ihr erster Vorschlag benutzt ja einen 8-Byte-Umsatzzähler, den Sie nachträglich auf 5 Byte verkürzen. Die RKSV geht hingegen davon aus, dass der Umsatzzähler von Anfang an die gewählte Länge (z.B. 5 Byte) hat.

Achtung: Ich bin nicht von der Fa. A-Sit, das hier ist nur meine persönliche Meinung.

**Comment by st0ne-dot-at** [comment]
@lebail: Sehe ich auch so. Ich befuerchte nur Verwirrung bei der Entschluesselung, da man dort auf alle Faelle wieder von 5 Byte auf 8 Byte richtig prefixen muss um auf Long zu konvertieren.

     500 = [0, 0, 0, 1, 244] => 
                muss mit [0, 0, 0] geprefix werden = [0, 0, 0, 0, 0, 0, 1, 244]
    -500 = [255, 255, 255, 254, 12] => 
                muss mit [255, 255, 255] geprefix werden = [255, 255, 255, 255, 255, 255, 254, 12]

**Comment by lebail** [comment]
Genau so habe ich das implementiert.

**Comment by st0ne-dot-at** [comment]
... alles klar. hab ich jetzt auch so!

**Comment by st0ne-dot-at** [comment]
Hab mir erlaubt im wiki 2 Referenzwerte einzutragen. https://github.com/a-sit-plus/at-registrierkassen-mustercode/wiki/Umsatzz%C3%A4hler-AES-Verschl%C3%BCsselung-Referzwerte 

@lebail : waere toll, wenn sie die Werte bestaetigen koennten.

LG,
Rob

**Comment by pteufl** [comment]
@stOne-dot-at
Danke, ich habe die Seite aber inzwischen wieder gelöscht, zum einen werden wir die Thematik in der nächsten Version des Mustercodes bzw. im Detaildokument behandeln, zum anderen hätte das ohne AES Schlüssel (der nicht angegeben war keinen Sinn).
Auf jeden Fall ist es ein wichtiges Thema das definitiv noch in den Beispielen gezeigt wird. Mehr Infos hier.

**Comment by st0ne-dot-at** [comment]
... ja klar! ;) oops ... AES - Schluessel waere: "supergeheim123" gewesen.

**Comment by wolfgangstiegler** [comment]
> D.h.:
> Der Umsatzzähler (z.B.: 500 Cent) wird wie folgt in das 16 Byte grosse Byte-Array geschrieben:
> 
> [0, 0, 0, 0, 0, 0, 1, 244, 0, 0, 0, 0, 0, 0, 0, 0]
> Wenn Sie nun nur die** ersten 5 Bytes für die Verschlüsselung** nehmen wäre das:
> 
> [0, 0, 0, 0, 0]

Für die Verschlüsselung wird doch das 16 Byte Array genommen und erst das Ergebnis für den Export des DEP folgendermaßen auf 5 bzw. 8 Bytes gekürzt:

> Das Resultat des Verschlüsselungsprozesses (Prozess 2.5.3 oder Prozess 2.5.4) entspricht dem verschlüsselten Umsatzzähler (16-Bytes/128 Bits langer Wert). Startend mit Byte 0 werden N Bytes aus dem Array extrahiert und BASE64-kodiert. N entspricht dabei der im vorigen Prozess definierten Länge des verschlüsselten Umsatzzählers. Der Minimalwert für N ist 5. Dies entspricht 5 Bytes/40 Bits, die aus dem verschlüsselten Umsatzzähler extrahiert werden.

Oder hab ich das falsch verstanden ?

**Comment by lebail** [comment]
Das war hier vielleicht etwas ungünstig formuliert. Es ging hier um die Frage, wie man einen als 8-Byte-Wert gespeicherten Umsatzzähler korrekt auf 5 Byte verkürzen kann, bevor man ihn in das 16-Byte-Array schreibt.

Diese Verkürzung ist natürlich nicht notwendig, sie verkleinert aber den maschinenlesbaren Code etwas.

**Comment by asitplus-pteufl** [comment]
Wir werden das Thema noch in den nächsten Versionen des BSP-Codes und auch des Detaildokuments aufnehmen.
@st0ne-dot-at Ein wichtiger Hinweis bezüglich AES- Schlüssel:
supergeheim123 kann kein 256 BIT AES Schlüssel sein (aufgrund der Länge), d.h. sie müssten noch irgendeine Ableitung vornehmen (oder halt einige Stellen auf 0 setzen). Im Sinne der Sicherheit ist das gefährlich (viel weniger Möglichkeiten, leichter zu erraten) und auch nicht notwendig da ja keine Passwörter zum Einsatz kommen die man dann auf einen Schlüssel umwandeln müsste. Für die Erstellung des AES-Schlüssels muss ein zufälliger 256-BIT Wert genommen werden (32 Byte Array), der mit einem sicheren Zufallsgenerator erstellt wird. Es biete auch für die Kunden keinen Vorteil wenn Sie hier etwas kürzeres nehmen, da ja sowieso der ganze AES-Schlüssel gemeldet werden muss (manuell oder automatisch).

Auch die Initialisierung wird noch im MusterCode und im Detaildokument "betont" werden.

**Comment by st0ne-dot-at** [comment]
@asitplus-pteufl: :+1: Danke fuer die ausfuehrliche Erklaerung. Habe jetzt auf 32 Byte urandom umgestellt.

Die Wikiseite haette unter Beruecksichtigung Ihrer Informationen wie folgt aussehen sollen:

    positiver Umsatz:
    Kassen ID: KASSE_1
    Bon Nummer: 16000001
    Umsatz: 500
    Key: vVDNZwk4clYsbK96R6KOnqVmgc5zf0lWF/7yGPGhumg=

    verschluesselt (gekuerzt auf 5 Byte): xO5v/9Q=

    negativer Umsatz:
    Kassen ID: KASSE_1
    Bon Nummer: 16000001
    Umsatz: -500
    Key: I2Wi48rZQ9BkUu87jrqyGvp94yQK4pfjRPIehAVkVwA=

    verschluesselt (gekuerzt auf 5 Byte): 8i95sJY=

**Comment by asitplus-pteufl** [comment]
Gerne, und danke. Wir werden das Thema für die nächste Release noch aufarbeiten.

**Comment by asitplus-pteufl** [comment]
In Version 0.7 des Muster-Codes und des Prüftools werden nun kürzere Umsatzzähler berücksichtigt.
