### ISSUE TITLE
Beleg- / DEP-Test Testtool 0.6

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#67]
Für das Testtool verwende ich identische Werte  im MaterialContainer.

Die Belegprüfung funktionierrt ohne Fehler, z.B.:
Überprüfung von Beleg 1

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine Trainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": Beim Erstellen des Belegs war die Sicherheitseinrichtung nicht funktionsfähig. (INFORMATION)

--------------------------------------------------------------

Bei der DEP-Prüfung bekomme ich bei jedem Eintrag folgenden Fehler:

ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": FEHLERHAFT
DETAILS: Gültigkeit der kryptographischen Kette ist nicht gegeben.
ÜBERPRÜFUNG: "Verschlüsselter Umsatzzähler": FEHLERHAFT
DETAILS: Ergebnis für Umsatzzähler ist nicht korrekt.
STACKTRACE: java.security.InvalidKeyException: Key length not 128/192/256 bits.
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1368)
	at javax.crypto.Cipher.init(Cipher.java:1301)
	at at.asitplus.regkassen.core.base.util.CryptoUtil.decryptTurnOverCounter(CryptoUtil.java:448)
	at at.asitplus.regkassen.core.base.util.CryptoUtil.decryptTurnOverCounter(CryptoUtil.java:398)
	at at.asitplus.regkassen.verification.core.verification.verificationmodules.TurnOverCounterVerificationModule.verify(TurnOverCounterVerificationModule.java:102)
	at at.asitplus.regkassen.verification.core.verification.verificationmodules.DEPExportFormatVerificationModule.verify(DEPExportFormatVerificationModule.java:172)
	at at.asitplus.regkassen.verification.cmdline.CheckDEPExportFormat.main(CheckDEPExportFormat.java:85)

Woran kann das liegen?

**Comment by asitplus-pteufl** [comment]
Hab hier leider nicht alle Details, aber der Stacktrace sagt aus, dass der AES-Cipher nicht initialisiert werden kann, da der Schlüssel nicht die passende Länge hat. Können Sie nochmal überprüfen ob der Schlüssel wirklich korrekt ist? Bzw. auch ob die Seriennummer des Zertifikats im Beleg mit dem im CryptoContainer übereinstimmt (sonst findet das Prüftool nicht den korrekten Schlüssel).

**Comment by michaelkorb** [comment]
Ich habe mal meine verwendeten daten angehangen.
[daten.zip](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/214643/daten.zip)

**Comment by asitplus-pteufl** [comment]
Sie verwenden keine BASE64-URL Kodierung im JWS-Format (= ist kein gültiges Zeichen für BASE64-URL), das könnte ein Problem sein...

**Comment by michaelkorb** [comment]
Das hatte ich schon vermutet.
Das Problem ist, dass die Funktionen comBase64.Encode und EncodeUrl das gleiche Ergebnis liefern.
Auch Encode und anschließend ReencodeNormalToUrl liefern identische Werte.
Beispiel: Nach dem Zusammensetzen der Werte ergibt sich:
_R1-AT1_BBSL-KASSE-001_1_2016-04-11T17:44:36_0,00_0,00_0,00_0,00_0,00_sTLRA5hEX0x/KXmcuJv94w==_79D9651A_705qTUYOOto=
comBase64.EncodeUrl ergibt
X1IxLUFUMV9CQlNMLUtBU1NFLTAwMV8xXzIwMTYtMDQtMTFUMTc6NDQ6MzZfMCwwMF8wLDAwXzAsMDBfMCwwMF8wLDAwX3NUTFJBNWhFWDB4L0tYbWN1SnY5NHc9PV83OUQ5NjUxQV83MDVxVFVZT090bz0=
Das = am Ende hat mich schon stutzig gemacht
comBase64.Encode ergibt das gleiche.
Auch im Testprogramm der Komponente ist das so.
Lediglich beim SigJWS kommt eine BASE64URL raus.
Woran kann das liegen?

**Comment by asitplus-pteufl** [comment]
Ich kenne die verwendeten Funktionen/Plattformen nicht, BASE64-URL erlaubt das Padding Zeichen "=" aber nicht. Ich weiß nicht welche Platform sie verwenden aber es gibt sicher Drittbibliotheken die BASE64 und BASE64-URL korrekt abbilden. Bin mir nicht sicher ob EncodeURL wirklich BASE64-URL abbildet...

**Comment by michaelkorb** [comment]
Ich verwende  von A-Trust die Komponente "ATrustRegistrierkasseCom".

**Comment by asitplus-pteufl** [comment]
Bitte den Hersteller (A-Trust) kontaktieren (oder für das BASE64-URL encoding einfach eine andere Bibliothek verwenden, die gibt es für alle Plattformen/Architekturen).

**Comment by asitplus-pteufl** [comment]
noch ein kurzer Workaround: entfernen sie mal alle = aus der Kodierung... was passiert dann im Prüfmodul?

**Comment by A-Trust** [comment]
Ich werde heute erst Nachmittags dazukommen die = in der Funktion zu entfernen, spätestens morgen   Vormittag wird es eine neue Version der ATrustRegistrierkasseCom geben.

**Comment by michaelkorb** [comment]
Hurraaaahhh.
Jetzt funktioniert alles. Alle Belege im EInzeltest und auch im DEP-Test sind OK.

**Comment by asitplus-pteufl** [comment]
wunderbar!
