### ISSUE TITLE
Prüfung Startbeleg

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#68]
In §6 Abs. 4 steht:
"Der  Unternehmer  hat  vor  Inbetriebnahme  die  Erstellung  der  Signatur  (§9  Abs.3)  und  die Verschlüsselung des Umsatzzählers (§9 Abs.2 Z5) unter Zuhilfenahme des Startbeleges zu überprüfen. 
Entspricht   die   Erstellung   der   Signatur   bzw.   die   Verschlüsselung   des   Umsatzzählers   nicht  den Erfordernissen  des  §9,  so  ist  die  Registrierkasse  unmittelbar  als  Registrierkasse  mit  ausgefallener Signaturerstellungseinheit im Sinne des §17 Abs.4 zu behandeln. 
Das Prüfergebnis ist zu protokollieren und mit dem ausgedruckten Startbeleg gemäß §132 BAO aufzubewahren."

Hier stellt sich die Frage, wie der Unternehmer das anstellen soll. Ist damit eine inhaltliche Analyse gemeint oder was soll die Prüfung beinhalten?
Gibt es Vorgaben über den Inhalt des "Prüfprotokolls"?

**Comment by csokay** [comment]
Die Prüfung des Startbelegs wird mittels einer App, die mit FinanzOnline verbunden ist, vonstatten gehen. Es soll vor allem auch die Entschlüsselung des Umsatzzählers überprüft werden. Laut BMF steht dieses Tool gemeinsam mit den Änderungen im Finanzonline (An/Abmeldung Registrierkassa etc) ab Juli 2016 zur Verfügung.
Quelle: SItzung AK Kassensoftware vom 12. April 2016
(Disclaimer: keine offiziele Meinung, bin kein MItarbeiter der A-SIT)

**Comment by michaelkorb** [comment]
Diese App wird hoffentlich nicht für jedermann zugänglich sein. Obwohl der Umsatz meines Ladens , bei dem ich gerade eingekaut habe, wäre ja schon interessant.:-)

**Comment by silence87** [comment]
Das setzt wohl den Besitz eines Smartphones voraus. 
Wie stellt sich das BMF eigentlich die Prüfung ohne Smartphone vor? Diensttelefone gibts bei uns keine.

**Comment by michaelkorb** [comment]
Vielleicht gibt es die ja gratis bei der Anmeldung.:-)
Aber auch ohne eine App wird es schwierig. Nicht jeder Kassenscanner ist 2D tauglich. Man müßte ja den QR-Code scannen und dann mit vorhandener Sicherungseinrichtung gegen prüfen.

**Comment by csokay** [comment]
> Wie stellt sich das BMF eigentlich die Prüfung ohne Smartphone vor? Diensttelefone gibts bei uns keine.

Über die FinanzOnline-Webseite.

**Comment by asitplus-pteufl** [comment]
Nur ein paar kurze technische Übersichtsinfos damit hier keine "Gerüchte" entstehen:
-App wird für alle zur Verfügung stehen, aber natürlich können nur Belege des eigenen Unternehmens geprüft werden (authentifizierung dazu). Umsatzzähler nicht in Gefahr, auch werden Detailergebnisse nie der App zurückgegeben.
-Startbelege/Jahresbelege etc. werden auch automatisiert an eine Schnittstelle von FinOnline übermittelt werden können (von der Kasse z.B.). Alternative Meldung ohne App/Schnittstelle auch vorgesehen.
-Vorgaben/Infos dazu werden demnächst vom BMF über den Arbeitskreis WKO/UBIT (Schnittstellen,Prüfergebnis etc.) veröffentlicht. Link dazu dann auch auf dieser Seite.
-Die Prüftools hier werden danach auch auf diese Ergebnisstruktur angepasst.

**Comment by asitplus-pteufl** [comment]
Nur ein paar kurze technische Übersichtsinfos damit hier keine "Gerüchte" entstehen:
-App wird für alle zur Verfügung stehen, aber natürlich können nur Belege des eigenen Unternehmens geprüft werden (authentifizierung dazu). Umsatzzähler nicht in Gefahr, auch werden Detailergebnisse nie der App zurückgegeben.
-Startbelege/Jahresbelege etc. werden auch automatisiert an eine Schnittstelle von FinOnline übermittelt werden können (von der Kasse z.B.). Alternative Meldung ohne App/Schnittstelle auch vorgesehen.
-Vorgaben/Infos dazu werden demnächst vom BMF über den Arbeitskreis WKO/UBIT (Schnittstellen,Prüfergebnis etc.) veröffentlicht. Link dazu dann auch auf dieser Seite.
-Die Prüftools hier werden danach auch auf diese Ergebnisstruktur angepasst.

**Comment by michaelkorb** [comment]
Von einer Übermittlung von Start - und Jahresbelegen an FinOnline steht aber nichts im Gesetz, lediglich von Ausdruck, Prüfung und ordnungsgemäßer Aufbewahrung. Womit die Frage nach dem Inhalt der "Prüfung" noch nicht geklärt ist. Im Prinzip könnten wir eine inhaltliche Prüfung ja durchführen im Sinne von:
- Einscannen des QRCode
- decodieren
- Inhalt neu signieren und das Ergebnis mit der Signatur aus dem maschinenlesbaren Code vergleichen
- Umsatzzähler entschlüsseln und auf sinnvollen Wert prüfen
Das Ergebnis würde auf einen Bon ausdruckt und zusammen mit dem Bon aufbewahrt werden.

**Comment by asitplus-pteufl** [comment]
Bitte um Verständnis, aber ich kann hier nur technische Themen beantworten.
