### ISSUE TITLE
Ausfall der Signatureinheit - Sammel / Nullbeleg nach Ausfall

### ISSUE THREAD

**Issue by newdeal30** [a-sit-plus/at-registrierkassen-mustercode#69]
Hallo!

In der Dokumentation "Detailfragen-RKSV-V1.1" steht, dass nach dem Ausfall der Signatureinheit ein Nullbeleg gedruckt werden muss.
Ich möchte in der Software unter anderem die Online-Signierung von Belegen vornehmen. 
Wenn nun die Internetverbindung ausfällt und dadurch die Signierung durch das Webservice nicht möglich ist, müsste - wie ich das verstehe - bei wieder funktionierender Internetverbindung ein Nullbeleg ausgedruckt werden. 
Nun ist von den KassiererInnen nicht zu verlangen immer auf dem Drucker nach einem solchen Bon Ausschau zu halten und diesen der Abrechnung beizulegen.
Ich würde den Vorgang gerne automatisieren und beispielsweise beim Monatsbericht alle Nullbelege (Sammelbelege) nachdrucken.
Ist dies zulässig?

**Comment by michaelkorb** [comment]
Lt. Gesetzestext müsen die Nullbelege nach Wiederinbetriebnahme nicht ausgedruckt werden. Wir erzeugen diese Belege automatisch ohne Zutun der Kassierer. Lediglich Startbeleg und Jahresbeleg müssen gedruckt und aufbewahrt werden. Monatsbelege erzeugen wir auch automatisch.

**Comment by asitplus-pteufl** [comment]
Es muss nur gewährleistet sein, dass die Verkettung in Ordnung ist, sprich Sie müssen den Beleg schon zu dem korrekten Zeitpunkt erstellen. Aber,  ausgedruckt müssen diese nicht werden. Ein "Sammeldruck" beim Monatsbericht ist natürlich möglich (abgesehen davon dass solche Nullbelege ja sowieso nicht ausgedruckt werden müssen).

**Comment by ct-graz** [comment]
Es kann ja sein, dass erst beim Signieren eines neuen Beleges erkannt wird, dass die Einheit wieder funktioniert. Dann muss also diese Signatur verworfen werden, ein Sammelbeleg erstellt werden und dann der Beleg nochmals neu verkettet und signiert werden. Macht man den Sammelbeleg danach, beklagt sich das Prüftool.

**Comment by michaelkorb** [comment]
Wir lösen das so, dass wir vor jeder Belegerstellung prüfen, ob die Einheit funktioniert, um im Fall der wieder hergestellten Funktionsbereitschaft erst den Nullbeleg automatisch zu erstellen und danach den eigentlichen Beleg.

**Comment by norbert2** [comment]
Frage zum "Sammelebeleg" nach Signaturausfall, wenn Signatur wieder funktioniert.
Habe ich soweit in die Software eingebaut. Prüftool sagt auch OK.
Wieso ist aber vom "Sammelbeleg" die Rede? Bei mit ist es einfach ein normaler 0-er-Beleg.
Was würde da "gesammelt"?

**Comment by ct-graz** [comment]
Stimmt, das ist ein seltsamer Name dafür. In der Signatur wird ja wirklich nichts gesammelt. Bei uns werden die betroffenen Belegnummern aber textalisch in Form einer Liste im Belegtext gesammelt.

**Comment by norbert2** [comment]
Danke für die prompte Stellungnahme. In der Tabelle meiner SQL-Datenbank sind natürlich auch alle Belege mit dem entsprechenden Status (Sign.Einheit OK Ja/nein) gespeichert.
Dann sehen wir die Bezeichnung "Sammelbeleg" einfach als eine eher unglückliche Bezeichnung des Begriffs.
