### ISSUE TITLE
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT

### ISSUE THREAD

**Issue by Sparti123** [a-sit-plus/at-registrierkassen-mustercode#70]
Hallo!

Leider werde ich aus der Fehlermeldung 'DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen: Dekodierter Signaturwert:...' nicht ganz schlau.

Es geht konkret um die Signierung mithilfe einer ATrust-Smartcard, wobei direkt die Signierung direkt über die APDU-Schnittstelle funktioniert (C#-Codeabschnitte aus ATrust-Beispielen verwendet):

string PlainText_Header = "{\"alg\":\"ES256\"}";
string PlainText_Payload = "_R1-AT0_DEMO-CASH-BOX524_366588_2015-12-17T11:23:44_0,00_0,00_0,00_26,05_0,00_m8LGyyY4UAA=_20f2ed172daa09e5_5HjRCx+XIz4=";

Daraus wird der zu signierende String erzeugt:
string JWS_Protected_Header = RKSVUtil.Base64url(PlainText_Header);
string JWS_Payload = RKSVUtil.Base64url(PlainText_Payload);
string toBeSignedStr = string.Format("{0}.{1}", JWS_Protected_Header, JWS_Payload);

Danach wird der Hash-Wert erzeugt:
byte[] tbsBytes = System.Text.Encoding.UTF8.GetBytes(toBeSignedStr);
SHA256Managed crypt = new SHA256Managed();
byte[] hash = crypt.ComputeHash(tbsBytes, 0, tbsBytes.Length);
string hashString = Convert.ToBase64String(hash);

Danach wird die Signatur erzeugt und daraus Base64Url-kodiert:
byte[] signature = smartCard.sign(pin, hash);
JWS_SignatureResult = RKSVUtil.Base64url(signature);

Ebenfalls wird der Header und Payload Base64Url-kodiert und diese drei Teile durch '.' getrennt zusammengefügt.

Leider bekomme ich immer den oben erwähnten Fehler.
Woran kann dies liegen?

Ich danke vielmals im Voraus!!!

LG

**Comment by asitplus-pteufl** [comment]
Bitte das berücksichtigen.
https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/67#issuecomment-209245907

Falls es das nicht war, bitte wieder posten.

**Comment by Sparti123** [comment]
Danke für die schnelle Antwort!!!

Es befinden sich jedoch keine '='-Zeichen in der Signatur.

LG

**Comment by asitplus-pteufl** [comment]
Warum ist denn diese Zeile in Verwendung?
string hashString = Convert.ToBase64String(hash);

Können Sie den Code von Smartcard.Sign posten (die APDUS sind nicht wichtig, aber etwaige weitere Operationen die in der Methode ausgeführt werden)?

**Comment by Sparti123** [comment]
Sorry, dies ist eine reine Debug-Zeile; die Variable hashString wird nicht mehr verwendet.

In smartcard.sign() werden reine APDU-Befehle ausgeführt:
            sendSelectFID(DF_SIG);
            CommandApdu apdu2 = generateDataAPDU(isoReader, 0x00, 0x22, 0x41, 0xb6, TLV);
            Response response2 = isoReader.Transmit(apdu2);
            CommandApdu apdu3 = generateDataAPDU(isoReader, 0x00, 0x20, 0x00, 0x81, PIN);
            Response response3 = isoReader.Transmit(apdu3);
            CommandApdu apdu4 = generateDataAPDU(isoReader, 0x00, 0x2A, 0x90, 0x81, SHA256HASH);
            Response response4 = isoReader.Transmit(apdu4);
            CommandApdu apdu5 = generateResponseAPDU(isoReader, 0x00, 0x2A, 0x9E, 0x9A);
            Response response5 = isoReader.Transmit(apdu5);
            byte[] signature = response5.GetData();
            return signature;

Danke vielmals für Ihre Hilfe!!!

LG

**Comment by asitplus-pteufl** [comment]
Ich kann Sie hier nur auf den Hersteller verweisen, so weit sehe ich ich keine Probleme (es gab noch die Vermutung dass die Signatur falsch kodiert wird).

**Comment by Sparti123** [comment]
Der Fehler tritt ebenfalls auf, wenn der zu signierende String (Header und Payload in Base64Url-Format)

'eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9ERU1PLUNBU0gtQk9YNDI2XzM2NjYwMF8yMDE2LTA0LTE5VDA3OjIwOjQ3XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF83QVlxODcyTGJDWWFFVXlYOXFEeldRPT1fMTcwOTY5N180N0RFUXBqOEhCUT0'

mit dem Kartenverwaltungstool (a.sign Client) von ATrust signiert wird

'3ubxNB0ZzJHhCn5aenLiI4So7RmFzziFfnt8s2/9wmLRvmZc1aoYp5p0Pjvybx9uq4wrofyqpST1
GHvZ/3QJGQ=='

und diese Signatur im Anschluss Base64Url kodiert wird 

'M3VieE5CMFp6SkhoQ241YWVuTGlJNFNvN1JtRnp6aUZmbnQ4czIvOXdtTFJ2bVpjMWFvWXA1cDBQanZ5Yng5dXE0d3JvZnlxcFNUMUdIdlovM1FKR1E9PQ'

und (durch '.' getrennt) an den ersten String (Header und Payload in Base64Url-Format) angehängt wird.´:

'eyJhbGciOiJFUzI1NiJ9.X1IxLUFUMV9ERU1PLUNBU0gtQk9YNDI2XzM2NjYwMF8yMDE2LTA0LTE5VDA3OjI1OjA3XzAsMDBfMCwwMF8wLDAwXzAsMDBfMCwwMF83QVlxODcyTGJDWWFFVXlYOXFEeldRPT1fMTcwOTY5N180N0RFUXBqOEhCUT0.M3VieE5CMFp6SkhoQ241YWVuTGlJNFNvN1JtRnp6aUZmbnQ4czIvOXdtTFJ2bVpjMWFvWXA1cDBQanZ5Yng5dXE0d3JvZnlxcFNUMUdIdlovM1FKR1E9PQ'

Wo kann der Fehler liegen, wenn sogar die Signatur mit dem Signierungstool von ATrust fehlschlägt?

Ich danke wieder im Voraus für Ihre Hilfe!!!

LG

**Comment by asitplus-pteufl** [comment]
Noch eine triviale Frage, sie geben aber schon den korrekten cryptographicmaterialcontainer.json beim Prüftool an? Sprich, Sie legen dort Ihr Zertifikat ab das sie zum Signieren verwenden?

**Comment by asitplus-pteufl** [comment]
achtung noch etwas: sie kodierten schon den RAW-Signature wert (sprich ohne BASE64-Kodierung) in BASE64-URL? (oder kodieren Sie den BASE64-Wert, das wäre falsch)?

**Comment by asitplus-pteufl** [comment]
gerade nachgeprüft, da liegt der Fehler... Sie kodieren das BASE64 Ergebnis in BASE64-URL, das ist falsch, sie müssen das Byte-Array das sie aus der Karte bekommen direkt BASE64-URL kodieren.

**Comment by Sparti123** [comment]
Zu cryptographicmaterialcontainer.json:
Ja, ich habe durch das ATrust-Tool das Signierungszertifikat als Base64 abgespeichert und dies in die cryptographicmaterialcontainer.json eingetragen.

"Sie kodieren das BASE64 Ergebnis in BASE64-URL, das ist falsch, sie müssen das Byte-Array das sie aus der Karte bekommen direkt BASE64-URL kodieren."
Dies wird auch so durchgeführt: Das Byte-Array, welches aus den APDU-Kommandos zurückkommt wird BASE64-URL kodiert:
JWS_SignatureResult = RKSVUtil.Base64url(signature); (wobei signature das RAW-Byte-Array ist)

Über den ATrust-Client:
Signatur:
'3ubxNB0ZzJHhCn5aenLiI4So7RmFzziFfnt8s2/9wmLRvmZc1aoYp5p0Pjvybx9uq4wrofyqpST1
GHvZ/3QJGQ=='

BASE64-URL kodiert:
'3ubxNB0ZzJHhCn5aenLiI4So7RmFzziFfnt8s2_9wmLRvmZc1aoYp5p0Pjvybx9uq4wrofyqpST1GHvZ_3QJGQ'

**Comment by asitplus-pteufl** [comment]
in dem BSP oben haben Sie aber direkt den BASE64 Wert BASE64-URL kodiert (beim dekodieren kommt der BASE64 Wert raus), deswegen die anmerkung

**Comment by asitplus-pteufl** [comment]
im cryptocontainer geben sie auch die richtige seriennummer an (ihres Zertifikats)?

**Comment by Sparti123** [comment]
Ja, ich habe dies in hex und in dec ausprobiert.
Wenn das Zertifikat im cryptocontainer nicht vorhanden ist ( "signatureCertificateOrPublicKey": ""), erhalte ich den gleichen String als 'Dekodierter Signaturwert: 0F☻! æÅ ëj!J⌂*±→', als wie bei vorhandenem Zertifikat.

**Comment by asitplus-pteufl** [comment]
bitte die dateien (dep-export, cryptograpicmaterial container posten).

**Comment by Sparti123** [comment]
Dateien sind upgelodet.

DANKE!!!

[cryptographicMaterialContainer.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/225303/cryptographicMaterialContainer.txt)
[dep-export.txt](https://github.com/a-sit-plus/at-registrierkassen-mustercode/files/225304/dep-export.txt)

**Comment by asitplus-pteufl** [comment]
Ihr Beleg enthält eine Dezimalseriennummer, damit kann keine Zuordnung gefunden werden:
_R1-AT1_DEMO-CASH-BOX426_366600_2016-04-19T08:01:17_0,00_0,00_0,00_0,00_0,00_7AYq872LbCYaEUyX9qDzWQ==_1709697_47DEQpj8HBQ=

dort muss auch die Hex-Repräsentation stehen.

ich hab nur testweise den Dezimalwert in den cryptocontainer eingetragen, dann funktiioniert die sig prüfung eh (darf aber so nicht gemacht werden). Also einfach auf Hex austauschen, das wars dann.

**Comment by Sparti123** [comment]
DANKE! DANKE! DANKE!
Das war der Fehler!!!
DANKE! DANKE! DANKE!

**Comment by asitplus-pteufl** [comment]
gerne, dann schließ ich das.

**Comment by Sparti123** [comment]
Könnten Sie bitte ihren Eintrag vor meinem Dankes-Post löschen.

Danke
LG

**Comment by asitplus-pteufl** [comment]
Ich hab den Beleg entfernt, wollten Sie auf das hinaus? Ich würde gerne die Nachvollziehbarkeit des Threads beibehalten.
