### ISSUE TITLE
Englische Übersetzung

### ISSUE THREAD

**Issue by strozzi** [a-sit-plus/at-registrierkassen-mustercode#71]
Guten Tag,

würde gerne wissen, ob eine Übersetzung des Dokumentes "FESTLEGUNGEN DES BMF ZU DETAILFRAGEN DER RKSV" in der Englischen Sprache geplant ist.

Vielen Dank im Voraus

**Comment by AndreErb** [comment]
Dieser Frage möchten wir uns als international tätiges Unternehmen anschließen, da eine rein deutschsprachige Fassung die Umsetzung für Firmen multilingualer Zusammensetzung deutlich erschwert und somit gleichzeitig zu einem Wettbewerbsnachteil führt.

**Comment by Perni1984** [comment]
unter https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/Registrierkassenpflicht.html

gäbe es einen Link zu den englischen Dokumenten, der allerdings nicht funktioniert. Evtl. kann die Bundessparte Handel der WKO weiterhelfen.

**Comment by AndreErb** [comment]
Vielen Dank für die Informationen @Perni1984. Ich habe entsprechend mit der **Wirtschaftskammer Österreich** Kontakt aufgenommen, um auf den Sachverhalt hinzuweisen. 

Möglicherweise kann @pteufl hierzu vorab weitere Informationen liefern ob eine englische Übersetzung zu [ Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV) V1.1](https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.1-DOK/2016-03-11-Detailfragen-RKSV-V1.1.pdf) existiert bzw. wo diese zu finden ist.

Besten Dank im Voraus!

**Comment by asitplus-pteufl** [comment]
Antwort bis 15.06.

**Comment by asitplus-pteufl** [comment]
Frage wurde ans BMF weitergeleitet, kann im Moment nicht beantwortet werden.

**Comment by AndreErb** [comment]
@pteufl: Danke für die Mühe. 
Dennoch bleibt das ganze nun ja noch unbeantwortet. Wäre es deshalb nicht möglich diesen Thread wieder zu öffnen um ihn zu einem späteren Zeitpunkt beantworten zu können? 

Nebenbei:
Die englischen Dokumente der **Wirtschaftskammer Österreich** sind nun wieder online, jedoch **deutlich weniger detailliert** als [Festlegungen des BMF zu Detailfragen der Registrierkassensicherheitsverordnung (RKSV) V1.1 ](https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases/download/1.1-DOK/2016-03-11-Detailfragen-RKSV-V1.1.pdf)
- [englische Übersetzung der RKSV (Cash Register Security Regulation)](https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/BGBLA-2015-II-410-EN.PDF)
- [englische Übersetzung der Anlage zur RKSV (Appendix - Detailed Specifications)](https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/BGBLA-2015-II-410-Anlage-EN.PDF)

**Comment by asitplus-pteufl** [comment]
Ja, sicher ist besser wenn er offen bleibt

**Comment by AndreErb** [comment]
@asitplus-pteufl: genau. Können Sie ihn also wieder öffnen :-) ?

**Comment by asitplus-pteufl** [comment]
nach meinem Informationsstand ist keine englische Version geplant. Bitte aber für detaillierte Informationen direkt beim BMF anfragen.
