### ISSUE TITLE
DEP Prüfung

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#73]
Bei der Prüfung eines exportierten Datenerfassungsprotokolls (DEP) mit regkassen-verification-depformat-0.6.jar muss in der mit -c angegebenen Containerdatei der AES-Key angegeben werden.
Der Tag heisst zwar "base64AESKey", es muss aber der normale Key eingetragen werden (nicht BASE64), damit die Prüfung funktioniert.

**Comment by asitplus-pteufl** [comment]
Da kann was nicht stimmen, die Datei ist die JSON Repräsentation des CryptoContainers der den AES Schlüssel enthält. Beim Export nach JSON kann dort nur BASE64 verwendet werden, sonst würde dort ein recht unschöner JSON Array stehen. (Man sieht es ja auch wenn man die Datei im Texteditor anschaut, dort liegt ein BASE64 Wert)
In welchem Zusammenhang kommen Sie zu dem Schluss, oder hab ich das etwas missverstanden?

**Comment by michaelkorb** [comment]
Ich verwende eine Funktion des A-Trust-COM-Moduls zur Generierung des AES-Keys.Offensichtlich kommt da schon ein BASE64codierter Wert raus. Da werd ich mal nachfragen.

**Comment by asitplus-pteufl** [comment]
dann müsste dieser Wert einfach im cryptocontainer eingetragen werden.

**Comment by michaelkorb** [comment]
Ok, die Funktion liefert bereits einen Base64codierten Wert.
Damit ist das Problem erledigt.
Danke
