### ISSUE TITLE
Beispiel für Rechnung die mit Erlagschein ausgestellt - später BAR bezahlt

### ISSUE THREAD

**Issue by Obritzberger** [a-sit-plus/at-registrierkassen-mustercode#74]
Gibt es dazu auch ein Beispiel WIE die Umsatzzähler, USt-Aufstellung nun richtig erfolgen muss?
Meine derzeitige "Auffassung"
Keine Aufteilung auf dei USt%-Sätze aber den Bruttobetrag im Umsatzzähler berückschtigen

ist das korrekt?

**Comment by michaelkorb** [comment]
Der Umsatzzähler zählt den Gesamtumsatz - brutto. Die USt.-Gruppierung wird für den Beleg benötigt. Weitere Hinweise stehen in Kapitel 2.5.1 der Detailfragen.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.

**Comment by asitplus-pteufl** [comment]
Ich schließe mich meinem Vorposter an, für technische Details dazu, bitte das Detailfragen Dokument beachten. Für rechtliche/organisatorische Fragen bitte den folgenden Hinweis beachten:

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.

**Comment by asitplus-pteufl** [comment]
Antwort des BMF:

Eine Zielrechnung (Rechnung mit Erlagschein) ist grundsätzlich nicht in die Registrierkasse aufzunehmen. Wird eine Zielrechnung allerdings ungeplant doch bar bezahlt, ist sie in der Registrierkasse zu erfassen. Es genügt die Bezugnahme auf die Rechnungsnummer der Zielrechnung, es muss nicht noch einmal auf die Einzelinhalte eingegangen werden. Es wird weiters nur der Bruttogesamtbetrag in der Steuerklasse „0 %“ erfasst, da der Beleg aus der Registrierkasse nicht noch einmal Steuerpflicht auslösen soll/darf (es ist davon auszugehen, dass die ursprüngliche Zielrechnung bereits Steuerpflicht ausgelöst hat). Der Beleg der Registrierkasse ist gemeinsam mit der Zielrechnung zu übergeben.
