### ISSUE TITLE
Registrierkassenbeleg für Barentnahmen aus der Kasse?

### ISSUE THREAD

**Issue by Obritzberger** [a-sit-plus/at-registrierkassen-mustercode#75]
Sind BAR-Entnahmen aus der Kassa zur Bezahlung z.B.: Briefträger, Postgebühren, schnell mal Tanken fahren auch Registrierkassenpflichtig?
Man spricht immer nur von Zahlungen - und Kassasturzfähigkeit 
da müssen dann doch auch Ausgaben erfasst werden oder?

**Comment by michaelkorb** [comment]
EIgentlich fallen diese Dinge nicht in diesen bereich. Wenn man Bargeld aus der Kasse entnimmt, macht man einen Entnahmebeleg, für das Restgeld einen Einzahlungsbeleg. Am Abend folgt der Kassensturz (Z-Bon), in dem auch zur Bank gebrachtes Geld erfasst wird. All diese Vorgänge haben eigentlich nichts mit der RKSV zu tun.

**Comment by ErichFreitag** [comment]
@Obritzberger: viele solcher Fragen und auch Antworten dazu finden Sie unter https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/Registrierkassenpflicht.html -> FAQ-Sammlung.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
