### ISSUE TITLE
einige Fragen...

### ISSUE THREAD

**Issue by poschinger** [a-sit-plus/at-registrierkassen-mustercode#78]
Guten Tag,

wir sind beim entwickeln einer Webbasierten Registrierkassa für unseren Partner auf einige Fragen gestoßen. Vielleicht kann mir hier ja geholfen werden, bzw. vielleicht kann jemand mitteilen, wo ich sonst Antworten auf diese Fragen erhalte. 

--

-->Bei Ausfall der Signatureinheit: Zählen solche "nicht signierten" Rechnungen zum Summen/Umsatzzähler?

--

-->Bei Totalausfall einer Kassa gegen Monatsende: Die Belege werden dann ja per Hand geschrieben.
Annahme: die Kassa ist erst wieder ab dem 5. des Folgemonats einsatzbereit.
Wie geht man mit den manuell geschriebenen Belegen des Vormonats um?
Diese müssen dann ja einzeln in der Kassa nacherfasst werden. Allerdings haben diese dann ja ein "falsches" Datum. Der Monatsbeleg des Vormonats beinhaltet dann ja diese Belege, welche eigentlich noch zum Vormonat gehört hätten nicht. 

Solche nachgetragenen Belege sollten ja irgendwie als "Nachgetragener Beleg" markiert werden und auch der eingescannte ORiginalbeleg sollte wahrscheinlich dem nachgetragenen Beleg hinzugefügt werden.

Vielleicht kann mir jemand kurz anführen, wie soetwas dann gehandhabt werden muss.

--

Welches Belegdatum bzw. welche Uhrzeit muss ein Monatsbeleg eigentlich genau haben? Wir gehen davon aus, dass das Kassensystem den Monatsbeleg automatisiert erstellen sollte.

--

Was muss ein Sammelbeleg, welcher nach Ausfall einer Signatureinheit erstelle werden muss, alles im Ausdruck beinhalten?

Vielleicht kann hier die ein oder andere Frage beantwortet werden. ICh bedanke mich bereits im Vorhinein dafür

mfg
Y.Poschinger

**Comment by asitplus-pteufl** [comment]
Eine sehr schnelle Antwort zum Thema Umsatzzähler, der wird auch bei einer ausgefallenen Sig Einrichtung erhöht. Die Prozesse dabei sind gleich wie bei "signierten Belegen" außer dass eben keine Signatur angebracht wird.

**Comment by ErichFreitag** [comment]
Zum Inhalt eines Sammelbelegs: siehe Erläuterungen zur RKSV § 17:

Für den Sammelbeleg sind die Belegdaten gemäß § 132a Abs. 3 BAO maßgeblich, wobei sämtliche Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“
versehen wurden, in den Sammelbeleg aufzunehmen und dabei je Beleg, als Menge die fortlaufende Nummer des jeweiligen Barumsatzes, als handelsübliche Bezeichnung der maschinenlesbare Code des jeweiligen Barumsatzes und als Betrag der Barzahlung „Null (0)“ einzutragen sind.

**Comment by ErichFreitag** [comment]
Zum Monatsbeleg: siehe Erläuterungen zur RKSV § 8:

Bei über Mitternacht hinausgehenden Betriebszeiten ist der Monats- bzw. Jahresbeleg spätestens vor dem ersten Beleg des neuen Monats bzw. Jahres zu erstellen.

**Comment by ErichFreitag** [comment]
Zum Monatsbeleg des Vormonats: siehe RKSV § 17 Zi. 5:
Bei jedem Ausfall einer Registrierkasse sind die Barumsätze auf anderen Registrierkassen zu erfassen. Sollte dies nicht möglich sein, sind die Barumsätze händisch zu erfassen und Zweitschriften der Belege aufzubewahren. Nach der Fehlerbehebung sind die Einzelumsätze anhand der aufbewahrten Zweitschriften nach zu erfassen und die Zweitschriften dieser Zahlungsbelege aufzubewahren (§ 132 BAO).

Das heißt für mich:
a) die Zweitbelege müssen aufbewahrt werden - nicht mehr (gescannt) und nicht weniger

b) die Einzelumsätze müssen nacherfasst werden. Im allgemeinen wird das bedeuten, dass Tag und eventuell Monat oder sogar das Jahr nicht mehr mit dem originalen Belegdatum übereinstimmen - das ist aber auch nicht zu verhindern. Wichtig ist meines Erachtens nach, dass die Belegverkettung aufrecht bleibt und der Umsatzzähler richtig fortgeschrieben wird, was ja bei einer Nacherfassung der Fall ist

c) die Belege zu markieren ist nicht vorgesehen, kann aber auch nicht schaden (sonst wäre es nicht nachvollziehbar, dass eine Nacherfassung stattgefunden hat)

d) ob ein Monatsbeleg in dem skizzierten Fall erstellt wird oder nicht hängt ja auch davon ab, ob sie die Kasse wieder in Betrieb nehmen können oder ob sie eine neue Kasse installieren müssen (-> unter Umständen Neuinbetriebnahme - Startbeleg, kein Monatsbeleg)

P.S. zwecks Übersicht finde ich es einfacher, ein Issue pro Thema zu öffnen - danke!

**Comment by aunterlu** [comment]
Zum Nacherfassen: Das Datum auf dem Beleg beim Nacherfassen sollte das Datum des manuellen Belegs sein. Das Erstellungsdatum des Belegs sollte Datum und Uhrzeit der Nacherfassung sein.
d.h. es gibt hier zwei verschiedene Zeitpunkte. 

Damit man die nacherfassten Belege auch beim richtigen Monatsbeleg dazurechnen kann, kann man eigentlich nur folgenden Hinweis verwenden:
laut https://findok.bmf.gv.at/findok?execution=e1s1 Punkt 3.3.4
"... Der Jahresbeleg muss jedenfalls vor Beginn der unternehmerischen Tätigkeit im neuen Jahr hergestellt werden. "

Wenn man sich aber den ganzen Punkt 3.3.4 ansieht, dann ist der für mich sehr unklar definiert. Aber um sinnvolle Monatsbelege (vorallem auch bei mobilen Diensten) zu bekommen, kann man den Monatsbeleg erst nach allen Nachbonierungen erstellen.

**Comment by areiter** [comment]
@ErichFreitag bzgl. des Sammelbelegs: Ich sehe die Thematik etwas anders. Die RKSV sagt dazu nur 

> Nach Wiederinbetriebnahme der Signaturerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern.

"...über die Belege..." heißt meines erachtens nach dass ein signierter Beleg erstellt wird, der die Verkettung fortsetzt.
Der Sammelbeleg muss also keine Barumsatznummer, Maschinenlesbare Codes oder Wert des Barumsatzzählers der unsignierten Belege enthalten (falls ich ihre Anmerkung richtig verstanden habe). Sie können das natürlich machen, aber:

1. es hat keine Auswirkung aufs DEP
2. die Daten wie Menge bzw. handelsübliche Bezeichnung werden ohnedies nicht signiert

Der Sammelbeleg dient nur dazu  um den aktuellen Stand des Umsatzzählers, die Barumsatznummer,... nach einem Ausfall vor Manipulationen zu schützen.

**Comment by ErichFreitag** [comment]
@aunterlu: Zum Nacherfassen: bezüglich des Datums der Belege gibt die RKSV keine Auskunft, auch nicht die Erläuterungen. Mehr als oben zum Monatsbeleg geschrieben gibt es dazu nicht. Ergänzungen zur Nachvollziehbarkeit sehe ich immer als sinnvoll, aber in diesem Fall nicht als vorgegeben.

Die Frage ist ja auch, wie es zu so einem Szenario kommen kann. Wenn eine Kasse ausfällt, gibt es beispielsweise die folgenden zwei Möglichkeiten (ich beziehe mich dabei hauptsächlich auf physisch vorhandene Kassen, bei Webkassen sind die Verhältnisse ein wenig anders):

- sie können das DEP wiederherstellen, die Kasse wiederherstellen und dort weiterarbeiten, wo sie aufgehört haben. Da könnte es sein, dass ein Monatsbeleg automatisch generiert wird, wenn dazwischen ein Monatswechsel war. Diesen Fall der Wiederherstellung halte ich für sehr mühsam, weil er technisch und organisatorisch schwierig zu handeln ist (beispielsweise müssten sie verhindern, dass trotz neuer Kasse kein Startbeleg erzeugt werden kann)

- oder die Kasse ist verlustig (Hardware-Defekt, Diebstahl, ...), dann müssen sie eine neue Kasse - wohl auch mit neuer Kassen-ID - installieren. Dabei kommt es auch zu keinem Monatsbeleg, sondern zu einem Startbeleg und es fängt sowieso alles neu an.

Wie auch immer - ein Zusammenhang von nacherfassten Belegen zu deren tatsächlichem Datum sehe ich nicht als vorgegeben. Die Nacherfassung ist ja nachvollziehbar und hat keine negativen Auswirkungen auf die Belegverkettung und auf den Umsatzzähler.

**Comment by ErichFreitag** [comment]
@areiter: das ist schon richtig, dass die RKSV selbst nicht mehr sagt. Die "Erläuterungen zur RKSV § 17" geben dazu weiter Auskunft, konkret "der Sammelbeleg enthält 
a) sämtliche Belege
b) jeweils die Belegnummer in der "Menge" und den maschinenlesbaren Code in der "handelsüblichen Bezeichnung" (siehe oben). 

Wie man den maschinenlesbaren Code in die handelsübliche Bezeichnung bringt, könnte bei manchen Belegformen noch spannend werden, aber das ist nicht mein Thema.

Zumindest ist das der aktuelle Stand, die Erläuterung liegt ja nach wie vor als Entwurf vor.

**Comment by areiter** [comment]
@ErichFreitag Anhand der Erläuterungen stimm ich ihrem Punkt zu. Mal schaun ob sich da für die finale Version noch etwas ändert

**Comment by aunterlu** [comment]
@ErichFreitag 

Das Nacherfassen betrifft einerseits die Kassa, wenn Sie "repariert" wurde und die Daten noch vorhanden sind und andererseits die mobilen Dienste. 

Bei mobilen Diensten ist es ja nicht unbedingt vorher absehbar, wann Sie wieder in der Betriebsstätte sind. Hier ist dann ein Erstellen des Monatsbelegs VOR dem Monatsende nicht möglich. 

Ich bekam am 9.8.2015 von Herrn Prof. Posch (a-sit) folgende Auskunft bezüglich Monatsabschluss bei mobilen Diensten und Datum und Uhrzeit am Beleg:
"Der Monatsabschluss in der Registrierkassensicherheitsverordnung als der
Nullbeleg VOR dem ersten Beleg des nächsten Monats festgelegt. (Kann für
Dezember also durchaus am 10. Jänner sein, wenn es dazwischen keine
Geschäftsfälle gab)

Nacherfassen manueller Belege kann daher nur ein Erfassen mit den
ursprünglichen Zeitangaben sein, sonst wäre es kein Nacherfassen. Da die
Sequenzsicherung festgelegt ist, hat Datum und Uhrzeit in Bezug auf
Sicherheit nebengeordnete Bedeutung. Datum und Uhrzeit sind daher aus meiner
Sicht Datum und Uhrzeit des authentischen Belegs, der eben NACHERFASST wird."

Sinnvoll wäre dieses "VOR dem ersten Beleg des nächsten Monats" vorallem für die Übernahme der Monatssummen in die Buchhaltung. Für kleine Einnahmen-Ausgabenrechner wäre das eine große Vereinfachung, wenn die Monatssumme mit den Bareinnahmen in diesem Monat korrekt übereinstimmt. Anderenfalls müssten hier nacherfasste Beträge herausgerechnet und manuell im richtigen Monat (Zahlungszufluss erfolgt ja zum Zeitpunkt des manuellen Belegs) verbucht werden.

**Comment by ErichFreitag** [comment]
@aunterlu: ich bin ja - bis auf die Verpflichtung zur korrekten Datumszuordnung - inhaltlich mit ihnen.

a) Monatsbeleg/Jahresbeleg - wann: korrekt, vor dem ersten Beleg des nächsten Monats/Jahres, also auch am 10.01. des Folgemonats

b) Nacherfassen - Datum und Uhrzeit haben für die Sicherheit soweit keine Bedeutung, OK

c) Nacherfassen - wenn sie das so realisieren finde ich es absolut OK und korrekt. Sie müssen es aber meiner Meinung nach nicht so machen. Sonst wäre beispielsweise die Möglichkeit der automatischen Erstellung des Monatsbelegs ein Widerspruch dazu. Ich kann es nur technisch-rechtlich betrachten und da würde ich beide Varianten (datumsgetreue oder nicht-datumsgetreue Nacherfassung) als OK beurteilen. Die datumsgetreue Nacherfassung plus erst dann auszulösendem Monatsbeleg ist halt auch für die User ein klein wenig komplexer

d) ich bin auch E-A-Rechner (wenngleich ohne Kasse) und kann dazu nicht viel beitragen außer, dass mich Monatssummen etc. bestenfalls pro Quartal zur USt-Berechnung interessieren. Aber klar - wenn ein laufender und übereinstimmender Zusammenhang gegeben ist es immer hilfreich

**Comment by aunterlu** [comment]
@ErichFreitag 

Vielen Dank für Ihre Anwort! Es ist aufgrund der unklaren Formulierungen im Gesetz und Erlass nicht immer einfach eine richtige Interpretation zu finden. Wir machen den automatischen Monatsabschluss beim Erstellen des ersten Belegs des nächsten Monats (falls er noch nicht manuell erstellt wurde).

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
