### ISSUE TITLE
Beareinlagen und Bareinnahmen Unterschiedlicher Beleg-Nummernkreis?

### ISSUE THREAD

**Issue by poschinger** [a-sit-plus/at-registrierkassen-mustercode#79]
soweit wir verstanden haben, sind Bareinlagen (z.B. Geld, welches von der Bank abeghoben wurde und in die Kassa eingezahlt wird) nicht signierpflichtig.

Allerdings muss natürlich auch hierfür ein Beleg erstellt werden (welcher nicht im DEP ist und auch den Umsatzzähler nicht beeinflusst).

Müssen diese Belege (Auszahlungen und Bareinlagen, welche NICHT signiert werden) nun in einem eigenen Beleg-Nummernkreis liegen?

Bzw. anders gefragt: müssen sämtliche signierten Belege fortlaufende Nummern haben?

 z.b. 
NUM1 - signierter Beleg (Bareinnamhe), 
NUM2 unsignierter Beleg (Ausgabe),
NUM3 unsignierter Beleg (Bareinlage), 
NUM4 signierter Beleg (Bareinnahme)

ODER:
NUM1 - signierter Beleg (Bareinnamhe), 
ANDERER_NUMMERNKREIS_1 unsignierter Beleg (Ausgabe),
ANDERER_NUMMERNKREIS_2 unsignierter Beleg (Bareinlage), 
NUM2 signierter Beleg (Bareinnahme)

**Comment by ErichFreitag** [comment]
Derzeitiger Wissensstand:
a) fortlaufende Nummern - ja
b) Buchstaben in der fortlaufenden Nummer - ja
c) Eindeutigkeit muss gegeben sein
d) Bareinlagen etc. können, aber müssen nicht (extra) signiert werden

Siehe z.B. auch Auszug in der Anlage
![wko faq-arbeitskreis-kassensoftware_67](https://cloud.githubusercontent.com/assets/18228048/15421577/65369cd4-1e74-11e6-8ec2-55a3accf7844.JPG)

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
