### ISSUE TITLE
RKSV-Anlage Z12: QRCode unvollständig

### ISSUE THREAD

**Issue by argetherapie** [a-sit-plus/at-registrierkassen-mustercode#8]
RKSV §10 (3) fordert: "Trainings- und Stornobuchungen haben im maschinenlesbaren Code zusätzlich die Bezeichnung 'Trainingsbuchung' oder 'Stornobuchung' zu enthalten."
In der RKSV-Anlage Z12 sind jedoch nur die Terme 'Signierte Belegdaten' und 'Signaturwert' spezifiziert.
Somit kann nach derzeitigem Stand der RKSV der Paragraf §10 (3) nicht implementiert werden.
Herr Michael Engelbert, BMF hat dies in einem persönlichen Gespräch am Rande einer A-Trust Veranstaltung am 22. Okt 15 in Wien bestätigt.

**Comment by pteufl** [comment]
Danke für den Hinweis, wird noch geklärt. Im Allgemeinen werden Punkte, die in Verordnung (vor allem technischen) Interpretationsspielraum haben mit dem BMF abgestimmt und hier in den FAQs behandelt (z.B: Runden beim Umsatzzähler). Wir sind aber gerade am Aufarbeiten dieser FAQs. Diese werden demnächst ergänzt.

**Comment by argetherapie** [comment]
Zitat Update V 0.4 - FAQ: "Statt dem Verschlüsselten Umsatzzähler wird im maschinenlesbaren Code der BASE64-Wert der Zeichenkette "TRAIN" gespeichert (entspricht "VFJBSU4")."
+ Das löst das Problem 'Trainingsbuchung'.
- Die Lösung ist für 'Stornobuchung' nicht möglich, da bei einem Storno der Umsatzzähler nicht disponibel ist.
- Zudem fordert die Verordnung 'Trainingsbuchung' und nicht 'TRAIN'.

**Comment by pteufl** [comment]
Technisch ist die Erkennung von Stornos/Trainings jetzt so recht einfach möglich (Storno wirkt ja einfach "negativ" auf Umsatzzähler.

In Bezug auf die Verordnung ist das natürlich ein Punkt. In Rücksprache mit BMF: Klärung bis nächste Woche. Infos - sobald verfügbar - werden hier bekannt gegeben bzw. im Readme (Hinweis dazu wird jetzt hinzugefügt).

Danke für das Feedback.

**Comment by pteufl** [comment]
Hinweis nun auch im README auf der Front-Page.

**Comment by giemes** [comment]
Gibt es schon Feedback vom BMF wie Stornos umzusetzen sind?

**Comment by pteufl** [comment]
Die im Muster-Code angegeben Informationen (siehe auch Wiki) sind mit dem BMF abgestimmt und gültig. Dazu gehört auch die Storno-Regelung.

**Comment by giemes** [comment]
Was noch unklar ist: wenn ich jetzt "STO" (analog zur Trainingsbuchung) reinschreib statt den Umsatz und intern im System aber den Umsatzzähler verringere: dann hab ich bei der nächsten Echten-Buchung den geringeren Umsatzzähler + Umsatz > dh: die der Stornobuchung folgende Buchung wird verkettet mit dem echten Umsatzzähler (der jetzt geringer ist als bei der letzten Echt-Buchung)

Beispiel:
* letzter Beleg - Umsatz 100; alter Umsatzzähler 900; neuer Umsatzzähler: 1000; Umsatzzähler in QR-Code: 1000
* Stornobeleg: -10eur > neuer Umsatzzähler: 990; Umsatzzähler in QRCode: STO
* neuer Beleg, alter Umsatzzähler: 990; neuer Umsatz 5; neuer Umsatzzähler 995 =  Umsatzzähler in QR-Code von 995;

Jetzt macht hier eigentlich der Stornobeleg den immer fortlaufenden und rückverfolgbaren Umsatzzähler (Zwischenstand) "kaputt":
Die Kette in den QR-Codes wäre: ... 900 -> 1000 -> ? -> 995 ...
Oder was verstehen wir da nicht richtig? Oder is das "Ok" weil Storno dazwischen?

**Comment by pteufl** [comment]
Das ist kein Problem. Im DEP ist ja der Verlauf ersichtlich und kann auch leicht nachvollzogen werden (genau so wie von Ihnen beschrieben).
Ist die Frage damit beantwortet?

**Comment by giemes** [comment]
Ja - vielen Dank!
Wir dachten nur der immer richtig fortlaufende Umsatzzähler ist eines der "manipuulationssicheren Bestandteile der RKSV" und das da noch etwas kommt.
VIELEN DANK - das hilft sehr :+1:

**Comment by pteufl** [comment]
gerne!
die manipulationssicherheit ist noch immer gegeben.
Die Belege sind ja miteinander verkettet. Da im DEP ja auch die Nicht-Storno Belege vorher/nachher zur Verfügung stehen ist der Stand des Umsatzzählers nachvollziehbar.
