### ISSUE TITLE
Tagesabschluss bei sehr wenigen Buchungen

### ISSUE THREAD

**Issue by poschinger** [a-sit-plus/at-registrierkassen-mustercode#80]
Unser Kunde hat nur alle paar Tage Geldeingänge (z.b. zwischendurch mal 4-5Tage gar keinen Bareingang).
Muss nun laut RKV in Zukunft trotzdem täglich ein Tagesabschluss manuell durchgeführt werden?
Laut RKV habe ich gelesen, dass dies eigentlich nicht mehr nötig ist, sofern die Kassa die RKV erfüllt. Was bedeutet dies nun genau bezügl Tagesabschluss?
Wäre ein automatisierter Tagesabschluss auch denkbar?

**Comment by ErichFreitag** [comment]
Die RKSV stellt keine Anforderungen an einen Tagesabschluss.

Unabhängig davon können Sie dennoch einen Tagesabschluss durchführen - mit oder ohne Signierung.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
