### ISSUE TITLE
DEP - Speicherung in Datenbank

### ISSUE THREAD

**Issue by poschinger** [a-sit-plus/at-registrierkassen-mustercode#81]
Unser System führt mehrere eigenständige Kassen in einem zentralen Webbasierten Kassensystem.

Ist es nun laut DEP erforderlich, dass pro Kassa eine eigene Datenbank-Tabelle erstellt wird, oder wäre es auch möglich eine Tabelle mit Verweis auf die jeweilge Kassa intern zu verwenden?

**Comment by asitplus-pteufl** [comment]
Die Implementierungsdetails liegen in Ihrer Verantwortung, es muss natürlich garantiert sein, dass die DEPs für jede Kasse getrennt exportiert werden können, und dass die Belegverkettung auf den korrekten vorigen Beleg zeigt.
