### ISSUE TITLE
Kopie Beleg -> QR, OCR erforderlich?

### ISSUE THREAD

**Issue by zal1** [a-sit-plus/at-registrierkassen-mustercode#83]
Guten Tag,

ist es erforderlich, lt. Gesetz, auf einer Belegkopie auch den QR/OCR-Code zu drucken oder reicht es wenn dieser auf dem "Orginal" gedruckt wird?

Danke.
lg
Alex

**Comment by ErichFreitag** [comment]
@zal1: laut welchem Gesetz? 

Die RKSV kennt den Begriff einer Belegkopie nicht. Es ist daher nicht unbedingt eine Frage, die hier aus technisch-rechtlicher Sicht der RKSV beantwortet werden kann (?).

In der BAO (§132a Abs 6) gibt es den Begriff der Durchschrift/Zweitschrift. Im Sinne dieses Begriffs und in Analogie zur Papierwelt von Belegen würde ich auch eine Belegkopie - mit Ausnahme eines deutlichen Hinweises auf eine Kopie - ident gestalten.

**Comment by asitplus-pteufl** [comment]
Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.
 
Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer **asitplus-pteufl** getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
