### ISSUE TITLE
Assignment of certificates

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#84]
Is a fix assignment between cashbox-id and certificate required, or can a cash-register get one from a pool of previously registered certificates (e.g. in case of an RKS-card, identified by the serial-number of the card) ?

**Comment by asitplus-pteufl** [comment]
There is no fixed assignment, a cash-register can use an arbitrary signature device that has been registered (failover, load balancing). also the "detailed document" states that the DEP export does not need to include the signature certificates/chains (they are optional) (it could get complicated when changes occur quite often...). the demo code reflects that behavior
