### ISSUE TITLE
cryptographicMaterialContainer

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#85]
Wird die Datei 'cryptographicMaterialContainer.json' zusammen mit dem DEP-Export nur für das Prüf-Tool benötigt oder müssen auch später im laufenden Betrieb immer beide Dateien ausgeliefert werden ?
Wenn ja, reicht es wenn nur der verwendete AES-Key enthalten ist ?

**Comment by asitplus-pteufl** [comment]
Nein, nur für das Prüftool.
Im "Echtbetrieb" ist nur der DEP-Export relevant.

**Comment by woko1754** [comment]
Wird der verwendete AES-Key für die Prüfung durch Finanzbehörde nicht benötigt ?

**Comment by asitplus-pteufl** [comment]
Der AES-Schlüssel und das Zertifikat (bzw. die Seriennummer davon) bzw. die Kasse selbst muss ja über FinOnline im Vorfeld registriert werden.
