### ISSUE TITLE
Datenerfassungsprotokoll - handelsübliche Bezeichnung

### ISSUE THREAD

**Issue by rikogithub** [a-sit-plus/at-registrierkassen-mustercode#86]
Ich habe 2 Fragen:
1. Für die handelsübliche Bezeichnung sind ja nach §132a BAO allgemeine Sammelbegriffe nicht zulässig.
Was gibt man hier fürs DEP an wenn auf der Barrechnung zB. 3 Positionen sind wie
- Bauschutt 160 kg
- Nassmüllkübel 2 Stk
- Grünschnittsack 10 Stk

Am einfachsten wäre als Bezeichnung "BARUMSATZ" mit Menge 1.
Die genauen Bezeichnungen sind in den Lieferscheindatensätzen auf Positionsebene enthalten. Aber im DEP habe ich nur einen Eintrag, und hier passt weder die Summe der Positionen für die Menge noch die Materialbezeichnung.

2.
Darf man für den Sammelbeleg Eintrag im DEP unter der Handelsüblichen Bezeichnung einfach "Sammelbeleg" reinschreiben.
Definiert ist ja " der maschinenlesbare Code des
jeweiligen Barumsatzes" ... 

> Für den Sammelbeleg sind die Belegdaten gemäß § 132a Abs. 3 BAO maßgeblich, wobei sämtliche
> Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“
> versehen wurden, in den Sammelbeleg aufzunehmen und dabei je Beleg, als Menge die fortlaufende
> Nummer des jeweiligen Barumsatzes, als handelsübliche Bezeichnung der maschinenlesbare Code des jeweiligen Barumsatzes und als Betrag der Barzahlung „Null (0)“ einzutragen sind.
> Der Sammelbeleg ist als Grundaufzeichnungen zumindest sieben Jahre aufzubewahren (§ 132 BAO).
> 

mfG. Richard

**Comment by asitplus-pteufl** [comment]
Wir können diese Frage im Rahmen dieses Projekts leider nicht beantworten. Bitte den folgenden Hinweis beachten:

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.
