### ISSUE TITLE
Prüfung von Belegen

### ISSUE THREAD

**Issue by michaelkorb** [a-sit-plus/at-registrierkassen-mustercode#87]
Auch wenn das evtl. wieder eine teils rechtliche Frage sein könnte: Gibt es Neuigkeiten bezüglich der Prüfung von Belegen insbesonders des Startbelegs?

**Comment by asitplus-pteufl** [comment]
Melde mich bis 15.06. mit einer Antwort.

**Comment by asitplus-pteufl** [comment]
Vom BMF war zu erfahren, dass es mehrere Varianten für die Belegprüfung geben wird:

Web-Service Schnittstelle Finanzonline für Kassen: https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/softwarehersteller-funktionen.html#heading__2

Prüfapplikation (mobile App) für den Unternehmer (Ab Juli 2016)

Weitere Informationen dazu sind vom BMF mittels überarbeitetem Erlass zur Einzelaufzeichungs-, Registrierkassen- und Belegerteilungspflicht auf der Homepage des BMF voraussichtlich bis Juli 2016 geplant.
