### ISSUE TITLE
Prüftool im Echtbetrieb

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#88]
Wir würden gerne das Prüfttool auch später im Echtbetrieb zur Kontrolle einsetzen. Wir würden dazu parallel zum DEP eine Datenbanktabelle zur Verwaltung der verwendeten Zertifikate pflegen.

Wie findet die Verknüfung zwischen DEP-Eintrag und dem verwendeten Zertifikat statt ?

Muss dazu im DEP die Seriennummer des Zertifikats gespeichert werden oder kann auch eine selbst vergebene Nummer (z.B UUID) verwendet werden ?

**Comment by asitplus-pteufl** [comment]
Mit Seriennummer und ZDA ID besteht eine eindeutige Zuordnung.
Bitte beachten, dass das Prüftool noch nicht final ist, es wird hier noch größere Erweiterungen geben.
