### ISSUE TITLE
NULL-Beleg bei Signaturausfall 2.2.3

### ISSUE THREAD

**Issue by senton82** [a-sit-plus/at-registrierkassen-mustercode#89]
Ich beziehe mich auf Abschnitt 2.2.3 des FAQ-Dokuments.

Dort ist in der Prozessbeschreibung zu lesen, dass ein NULL-Beleg erstellt wird, nachdem der Ausfall einer Signatureinheit wieder behoben wurde.

Ich nehme an, dieser Vorgang (und somit das manuelle Erstellen eines NULL-Beleges) ist nur notwendig, wenn die Signatureinheit länger als 24h außer Betrieb war UND dem FA somit gemeldet wurde.

Ich danke im Voraus für die Klarstellung.

LG,
Stefan

**Comment by ErichFreitag** [comment]
Siehe RKSV § 17 (4) Ausfall der Signaturerstellungseinheit:
"Nach Wiederinbetriebnahme der Signaturerstellungseinheit ist zusätzlich über die Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“ zu versehen waren, ein signierter Sammelbeleg mit Betrag Null (0) zu erstellen und im Datenerfassungsprotokoll zu speichern".

sowie die aktuelle RKSV Erläuterung zu § 17 - Sammelbeleg:
"Für den Sammelbeleg sind die Belegdaten gemäß § 132a Abs. 3 BAO maßgeblich, wobei sämtliche Belege, die während des jeweiligen Ausfalles mit dem Hinweis „Sicherheitseinrichtung ausgefallen“
versehen wurden, in den Sammelbeleg aufzunehmen und dabei je Beleg, als Menge die fortlaufende Nummer des jeweiligen Barumsatzes, als handelsübliche Bezeichnung der maschinenlesbare Code des jeweiligen Barumsatzes und als Betrag der Barzahlung „Null (0)“ einzutragen sind".

Also: immer zu erstellen, unabhängig von der Dauer und unabhängig von einer Meldung. Auf Grund des Inhalts des Sammelbelegs wird es auch nicht manuell möglich sein.

Die 24 h kommen sonst auch nirgends vor - die Erläuterungen zur RKSV beziehen sich auf 48 h Ausfall (wenn auch in diesem Fall nicht relevant).

**Comment by 01af** [comment]
Hallo Erich, 

Die aktuelle **RKSV Erläuterung**, dabei handelt es sich um dieses Dokument?
https://www.bmf.gv.at/steuern/EB_RKSV.pdf
Oder ist bereits eine aktuellere Fassung verfügbar? Danke dir!

**Comment by ErichFreitag** [comment]
Das ist die derzeit aktuelle Fassung, eine neue Version ist aktuell für Mitte Juni angekündigt.

**Comment by asitplus-pteufl** [comment]
technisch: gilt für jeden Ausfall gleich (state-transfer von beleg mit ausgefallenem beleg auf null-beleg mit funktionierender sig-einrichtung (sammelbeleg) danach wieder normaler beleg)
abläufe sind in den test-cases berücksichtigt, technische abläufe werden in der nächsten version des herstellerdokuments berücksichtigt

**Comment by senton82** [comment]
Danke soweit für die Antworten - ganz klar ist mir die Sache leider noch nicht.

Signiereinrichtung:
Festzustellen, ob die Signiereinrichtung funktioniert oder nicht (ich denke hier an die Verwendung einer Smartcard oder der online-Schnittstelle) kann ich nur beim eigentlichen Signiervorgang eines aktuellen Beleges - da müsste ich aber dann (geht doch alleine schon auf Grund der Verkettung nicht) noch den NULL-Beleg einschieben. 

Sammelbeleg:
Nur um das richtig zu verstehen - ich muss also in meinem Kassa-System einen Verkaufsbeleg erzeugen, welcher pro nicht-signiertem Vorgängerbeleg eine Belegzeile enthält, in der als Menge die Belegnummer (was wenn ich formatierte Belegnummer in der Form AT1-0001 verwende) des jeweiligen nicht signierten Beleges und als Text/Beschreibung der QR/OCR-Code dieses Beleges aufgebracht wird - das ganze bei 0% Steuer mit einem Gesamtbetrag NULL(0)?

Was bringt es einen solchen Beleg zu erstellen, nachdem die Signierung weder den Text noch die Menge in Betracht zieht?

Ich danke im Voraus für eure Hilfe!

LG,
Stefan

**Comment by ErichFreitag** [comment]
Zur Feststellung der Funktion: korrekt, das wird wohl sinnvoll nur festgestellt werden können, wenn ein Beleg zu signieren ist.

Konsequenz:
- bei Ausfall der Sicherheitseinrichtung Meldung am Beleg und im maschinenlesbaren Code anbringen und den 48-Stunden-Timer starten
- bei Wiederfunktion der Sicherheitseinrichtung VOR dem neuen Beleg einen Sammelbeleg erstellen

Eine Konsequenz daraus ist, dass die Kassensoftware vor jeder Belegerstellung wissen muss, ob die Sicherheitseinrichtung wieder verfügbar ist oder nicht. Die Verkettung ist dann zumindest indirekt vorhanden, weil ja die Belegreihenfolge rekonstruierbar ist.

Wie das umgesetzt wird ist von der Architektur abhängig - beispielsweise ob die Kasse einen Dienst verwendet, der diese Fälle handelt oder ob die Kasse alle Anforderungen autonom implementiert. Siehe dazu informativ auch https://github.com/a-sit-plus/at-registrierkassen-mustercode/issues/69.

In der Realität wird wohl die Kassensoftware oder der Dienst während der Ausfallszeit die Belege sammeln und bei Wiederverfügbarkeit einen Sammelbeleg generieren. Dieser ist ja "nur" gemäß BAO aufzubewahren, muss also nicht ausgedruckt werden und wird entsprechend der BAO irgendwo abrufbar zu speichern sein.

Hinzu kommt die Meldung an FinanzOnline nach derzeit 48 Stunden Ausfall plus der Meldung der Wiederverfügbarkeit - das ganze Ausfalls-Szenario braucht also sowieso ein eigenes Handling.

Zum Sammelbeleg: ja, so lautet derzeit die Erläuterung. Zum "was es bringt" kann ich - außer der oben beschriebenen "indirekten Belegverkettung" - nichts verbindliches beitragen.

**Comment by senton82** [comment]
Danke für dein anschauliches Beispiel.

Hier muss ich wohl mit A-Trust sprechen, was via APDU und dem Einsatz von Smartcards die richtige Vorgehensweise zum verlässlichen Überprüfen des Vorhandenseins der Signatureinheit ist. Ich hatte eigentlich gehofft die Smartcard einmalig bei Programmstart zu initialisieren und dann nur mehr zu signieren (und mit einem Ausfall bei entsprechender Warnung zu leben). Es stellt sich eben die Frage was geschieht, wenn jemand wahllos den USB-Dongle aus/einsteckt (oder ein Wackelkontakt dafür sorgt).

Danke für die Bestätigung bzgl. Sammelbeleg.

LG,
Stefan

**Comment by ErichFreitag** [comment]
Bitte gerne. Das war jetzt die technisch-rechtliche Seite. Organisatorisch ist zusätzlich zu überlegen

- wie wird der Kassenbenutzer darauf hingewiesen? Er/sie wird kaum jeden Beleg prüfen, ob "Sicherheitseinrichtung ausgefallen" draufsteht. Er/sie braucht aber einen Hinweis, um vielleicht ein Servicedesk zu kontaktieren oder zumindest zu überprüfen, ob alles eingesteckt ist

- wie wird der Kassenbenutzer geschult? Was soll er/sie sagen, wenn ein Kunde frägt "was heißt denn hier "Sicherheitseinrichtung ausgefallen""

**Comment by senton82** [comment]
Ja, die Schulungen werden noch eine ganz andere Geschichte :-)

Danke - nochmal allen Beteiligten für die detaillierte Ausführung!

**Comment by asitplus-pteufl** [comment]
zusätzliche anmerkung, die technischen aspekte dieser und ähnlicher themen werden in Detailfragendokument 1.2 behandelt (release termin kann ich noch nicht nennen, muss erst mit BMF abgestimmt werden)

**Comment by norbert2** [comment]
Leider doch noch Fragen zum Sammelbeleg nach Signaturausfall:

In einigen Beiträgen wird auf 
RKSV § 17 (4) Ausfall der Signaturerstellungseinheit
 und "aktuelle RKSV Erläuterung zu § 17 - Sammelbeleg:" verwiesen.
Hat da wer Links dazu?

Ich habe offenbar bezüglich Sammelbeleg was überlesen, wie der genau zu gestalten ist.
Grundsätzlich habe ich es geschafft, dass ein DEP mit  Ausfall der SE und eine anschließende Wiederinbetriebnahme mit Nullerbeleg  vom Prüftool  als korrekt angesehen wird. Soweit so  gut.
Beim Durchforsten der Beiträge bin ich aber nun doch ins Grübeln gekommen. Mein Nullerbleg enthält eben KEINE Daten von Belegen, die mit "SE ausgefallen" signiert wurden.
In den Beiträgen steht, dass am Beleg die Belege-Nr. und Signaturen jener Belege aufscheinen müssen, die mit "SE-ausgefallen" signiert wurden.
Dieser Beleg muss anscheinend eh nicht ausgedruckt werden.
Im meinem Erfassungsprotokoll, in dem jede Zeile gespeichert wird (also NICHT das DEP) werden jene Belege gekennzeichnet, die mit ausgefallener SE signiert wurden. Somit also nachvollziehbar und kontrollierbar.
Hätte da bitte wer eine Klarstellung für mich oder eben Links zum Nachlesen von Erläuterungen bzw. Detials  zum Erlass?

**Comment by ErichFreitag** [comment]
@norbert2 - bitte ggf. neues Issue eröffnen.

Die Links finden zum Erlass etc. finden sie beispielsweise gesammelt unter  https://www.wko.at/Content.Node/branchen/oe/sparte_iuc/Unternehmensberatung-und-Informationstechnologie/IT_Dienstleistung/Rahmenbedingungen/Registrierkassenpflicht.html. 

Eine Zusammenfassung aller rechtlich relevanten Themen gibt es unter http://www.pqrst.at/PDFs/PQRST_RKSV_Rechtliche_Anforderungen.pdf. Die Erläuterungen würde ich nur mehr dort verwenden, wo der Erlass keine Auskunft gibt.
