### ISSUE TITLE
Umsatzzähler und Gutscheine

### ISSUE THREAD

**Issue by lebail** [a-sit-plus/at-registrierkassen-mustercode#9]
Sowohl der Bar-Verkauf eines (z.B. 50-€-)Gutscheines als auch dessen Einlösung unterliegen der RKSV.

Da der Gutscheinwert aber wohl nicht *zweimal* zum Umsatzzähler addiert werden soll, stellt sich die Frage, ob der Umsatzzähler beim *Verkauf* des Gutscheines oder bei dessen *Einlösung* (die ja ebenfalls als Bar-Transaktion gilt) um den Gutscheinwert erhöht werden soll.

Beim A-Trust-Workshop am 22.10. gab es ein Gespräch zu diesem Thema mit Herrn Engelbert und mehreren Teilnehmern, dieses behandelte aber vor allem die USt.-mäßige Behandlung der genannten Geschäftsfälle. Der Umsatzzähler blieb dabei auf der Strecke ...

**Comment by DFeckter** [comment]
Bitte können Sie die Sachlage genauer erläutern. 

Grundsätzlich wird der Verkauf eines Gutscheines zum Umsatzzähler addiert. (z.B. +10 Euro)
Jetzt findet ein Verkauf eines Artikels (50 Euro) und die Einlösung des Gutscheines (-10 Euro) statt.
Daher wird der Umsatzzähler um 40 Euro erhöht.

Wo liegt hier jetzt genau das Problem?

**Comment by lebail** [comment]
Vielen Dank für die Antwort.

Mir war nicht im Vorhinein klar, dass bei Einlösung des Gutscheines der Umsatzzähler nur um den bar aufgezahlten Betrag erhöht werden soll (und nicht um den Gutscheinwert) - denn bisher entstand bei mir der Eindruck, dass ein Gutschein wie Bargeld zu behandeln wäre.

Da der Verkauf eines Wertgutscheines rechtlich nicht als Umsatz gilt, hielt ich auch eine andere Vorgangsweise für möglich: Beim Gutscheinverkauf würde der Umsatzzähler *nicht* erhöht, bei dessen Einlösung dafür aber um den *gesamten* Warenwert (im obigen Beispiel 50 €).

**Comment by DFeckter** [comment]
So ganz ist die Aussage nicht korrekt. Zum Umsatz zählt der Gutschein schon mit, nur liegt kein "steuerbarer" Umsatz vor. (also 0%).
In Österreich wird das so definiert, das beim Kauf eines Gutscheines noch keine Leistung vollbracht wird, sondern erst beim Einlösen. In Deutschland wird es so definiert, dass man beim Kauf eines Gutscheines nicht weiß welche Leistung vollbracht wird. (7% oder 19%)

Es müssen für die RKSV der Umsatz in die einzelnen Steuersätze eingeteilt werden und der Umsatzzähler summiert sich aus allen Umsätzen, wie ich das herauslesen kann. (Bitte korrigieren Sie mich wenn dies nicht der Fall ist)

**Comment by lebail** [comment]
Bei der Beschreibung des Umsatzzählers ist in der RKSV immer von der "Summierung der *Barumsätze*" die Rede. Beim der Auftrennung nach Steuersätzen heißt es aber, dass der "Betrag der *Barzahlung*" aufzutrennen sei. Jetzt stellt sich die Frage, ob zwischen *Barumsatz* und *Barzahlung* ein Unterschied besteht.

Leider bin ich weder Jurist noch Finanzexperte, sondern nur Softwareentwickler ...

**Comment by argetherapie** [comment]
Der "Verkauf" eines Gutscheines scheint prinzipiell nicht zum RKSV-Umsatz hinzuzählbar.
Quelle Dr. Markus Knasmüller, BMD:
https://www.xing.com/communities/groups/registrierkassenpflicht-oesterreich-aaa2-1078578
Auszug aus einer pdf von Dr. Knasmüller:
![gutschein-rksv](https://cloud.githubusercontent.com/assets/15307771/10753337/a5de436c-7c90-11e5-9dc6-cdaa6755da79.png)
Am Rande einer Veranstaltung in Wien hat Herr Michael Engelbert, BMF die Gutschein-Frage auch so beantwortet.

**Comment by lebail** [comment]
Vielen Dank - auch für den Link!

Auch wenn der Gutschein"verkauf" nicht "registrierkassenpflichtig" ist, wird man dafür wohl dennoch einen Beleg ausstellen müssen - und dies, so vorhanden, mit der Registrierkasse tun.

Jetzt stellt sich die Frage, ob im Feld "Betrag der Barzahlung 0% USt." der Gutscheinwert erscheinen soll (beim Gutschein"verkauf" positiv, bei der Einlösung mit negativem Vorzeichen), oder ob da 0,00 stehen soll.

**Comment by DFeckter** [comment]
Danke für die Antwort.

Genau das selbe hätte ich jetzt auch geschrieben. Für was muss dann die MWST 0% aufgeführt werden?

Aber genau das ist der Finanz "sch***egal", weil MWST 0% interessiert die nicht. Bekommens ja kein Geld dafür.

Nächste Frage: in den Umsatzzähler laufen die Summen Brutto oder Netto hinein?

Danke bin auch nur ein Softwareentwickler...

**Comment by lebail** [comment]
RKSV: "Betrag der Barzahlung getrennt nach Steuersätzen".
Das bedeutet in meinen Augen *brutto*, denn die Barzahlung erfolgt nun einmal brutto.

Das führt übrigens zu netten Rundungsdifferenzen, wenn man eine UStG-konforme Rechnung mit integriertem Barzahlungsbeleg erstellt. Denn für die Rechnung muss man die Nettobeträge summieren und die USt. aufschlagen, für den Zahlungsbeleg hingegen die Bruttobeträge nach USt.-Satz getrennt angeben. Abhilfe: USt. für jeden Rechnungsposten einzeln ausweisen (nach Rundung auf 2 Dezimalstellen) und erst dann summieren.

**Comment by argetherapie** [comment]
@DFeckter: "für was MWST 0%"? Es gibt UST-freie Branchen, zB Ärzte, Physiotherapeuten, etc..
@lebail: Ich würde/werde den "Verkauf" von Gutscheinen aus dem RKSV völlig raus halten; Und beim Einlösen ist er wie Bargeld zu behandeln.
--
Allgemein warte ist mit der Implementierung solcher Details zu, bis das BMF wirklich weiß, was es von uns will.. ;-)

**Comment by pteufl** [comment]
Es wird bezüglich runden, Behandlung von Storno/Trainingsbuchungen demnächst hier weitere Erläuterungen geben.
Allgemein zu den Issues: Für Fragen bezüglich rechtlichen Aspekten zur Verordnung etc. bitte die HP des BMFs beachten. Technische Themen (vor allem in Bezug auf Interpretationsspielraum) werden hier im FAQ-Abschnitt behandelt. Der ist im Moment noch recht klein wird aber in den nächsten Tagen erweitert.
Ich schließe dieses "Issue" damit.
