### ISSUE TITLE
Base32

### ISSUE THREAD

**Issue by mario78** [a-sit-plus/at-registrierkassen-mustercode#90]
Hallo,

in der Detailspezifikation 1. Standrad steht das Base32, Base64, und Base64-url aus dem rfc 4648 entnommen ist.
wenn ich das aber überprüfe komm ich drauf das die Base32-Codierung aber aus rfc-3548 ist. 

hier ein Beispiel aus den Testdaten:
QRCode:   
"_R1-AT0_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-570_2016-03-11T04:24:17_0,00_0,00_0,00_0,00_0,00_SatTFjFrhnk=_U:ATU12345678-K0_cg8hNU5ihto=_REMmVM7A9j6zrdnVmy2q4RVJDfVboqnusab0Pjynxi0+ng2BT9a3KhlDJNY5F+fmmDARcmyU/wyDM2Ug60Zo6w==",

OCRCode   
"_R1-AT0_CASHBOX-DEMO-1_CASHBOX-DEMO-1-Receipt-ID-570_2016-03-11T04:24:17_0,00_0,00_0,00_0,00_0,00_JGVVGFRRNODHS===_U:ATU12345678-K0_OIHSCNKOMKDNU===_IRBSMVGOYD3D5M5N3HKZWLNK4EKUSDPVLORKT3VRU32D4PFHYYWT5HQNQFH5NNZKDFBSJVRZC7T6NGBQCFZGZFH7BSBTGZJA5NDGR2Y=",

Signatur (Hash) vorhergehender Beleges, aus dem QRCode : cg8hNU5ihto=
Signatur (Hash) base32 codiert, aus dem OCR code: OIHSCNKOMKDNU===

Der Wert "cg8hNU5ihto=" wird Base64 decodiert,
dies ist anschließend ein byte-array mit 8 elementen: 72 0F 21 35 4E 62 86 DA

0x0072 als Bitdarstellung entspricht 0111 0010
Davon die ersten 5 bits sind 01110
als integer 14

nach base32 (rfc-3548) als O codiert
nach base32 (rfc-4648) als E codiert

Der gesamte Wert in Bit Darstellung ist 
01110010 00001111 00100001 00110101 01001110 01100010 10000110 11011010
In 5 Blöcke aufgeteilt, und ergänzt: 
01110 01000 00111 10010 00010 01101 01010 01110 01100 01010 00011 01101 10100 - - -
Wieder als integer codiert: 14 8 7 18 2 13 10 14 12 10 3 13 20 - - -

So ergibt sich nun:
Base32 (rfc 3548): OIHSCNKOMKDNU===
Base32 (rfc 4648): E87I2DAECA3DK===

Gleiches kann man mit den Beispielen aus den Detailfragen nachvollziehen.
Muss ich nun der Detailspezifikation folgen, oder kann ich weiter mit rfc-3546 arbeiten?
Oder hab ich irgendwo einen Denfehler?

mfg Mario

**Comment by asitplus-pteufl** [comment]
Müssen wir im Detail anschauen, damit Sie weiterkommen: Die Mustercode-Version ist definitiv korrekt (kann sein dass das falsche RFC zitiert wird). wird geklärt.

**Comment by asitplus-tzefferer** [comment]
Im Gegensatz zum obsoleten RFC 3548 [1] definiert der aktuelle RFC 4648 [2] zwei verschiedene Base32-Encodings. Das in Abschnitt 6 von RFC 4648 definierte Encoding entspricht dabei jenem von RFC 3548. Zusätzlich ist in Abschnitt 7 das sogenannte "Base 32 Encoding with Extended Hex Alphabet" definiert.

In Ihrem Beispiel verwenden Sie offensichtlich letzteres. Die Spezifikation sieht jedoch die Verwendung des "herkömmlichen" Base32-Encodings aus RFC 4648 Abschnitt 6 (welches jenem aus RFC3548 entspricht) vor.

[1] https://tools.ietf.org/html/rfc3548
[2] https://tools.ietf.org/html/rfc4648
