### ISSUE TITLE
Beispiel "Verschlüsselung Umsatzzähler"

### ISSUE THREAD

**Issue by AndreErb** [a-sit-plus/at-registrierkassen-mustercode#91]
Wäre es möglich ein komplettes Beispiel für die Ein-/Ausgabewerte einer **Verschlüsselung des Umsatzzählers** zu bekommen um dies mit dem entsprechenden Ergebnis der eigenen Implementierung vergleichen zu können? Weder in der Dokumentation noch im Beispielcode/Testfälle konnte ich ein direkt ablesbares Beispiel mit Ergebnis finden.
Beispiel:
- Kassen-ID: ``CASHBOX-DEMO-1``
- Belegnr: ``CASHBOX-DEMO-1-Receipt-ID-1``
- Base64AESKey: ``WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU=``

=> Verschlüsselter Wert in Base64: ???

 Danke im Voraus!

**Comment by silence87** [comment]
Registrierkasse Umsatzzähler Verschlüsselung (AES/ICM): http://labs.a-trust.at/developer/ShowSource.aspx?id=126

**Comment by AndreErb** [comment]
@silence87 Danke für den Link. Leider hilft er nicht für meine Frage nicht weiter, da dort keine Ergebnisse direkt ablesbar sind. Für einen Vergleich müssten wir den dortigen Code ausführen, wofür wir wiederum die Anbindung von A-Trust benötigen würden (welche wir nicht einsetzen).
Ich suche auch weniger nach Code als nach einem Ergebnis mit dem wir vergleichen können.

Für einfaches Beispiel **mit Ergebnis** (wie ganz oben aufgeführt) wäre ich also weiterhin sehr dankbar.

**Comment by 01af** [comment]
Ein Beispiel:
KassenID: "CashBox01"
Belegnr: "00000000"
Umsatz: 0
AES-Key (base64 encoded): "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU="
Verschlüsselter Umsatzzähler (8 byte, base64 encoded):  l/swzun6050=

**Comment by wpichler** [comment]
Kannst du da noch mehr Informationen dazu geben - zum debuggen...

- Wie sieht dein Initialisierungsvektor mit diesen Daten aus 
u'CashBox0100000000' - ergibt als Hash ?
- Wie sieht dein kodiertes Byte Array des Umsatzzählers aus ?

**Comment by wpichler** [comment]
l/swzun6050= - auf den Wert komme ich übrigens auch - gerade noch nachgeprüft - sieht also schon mal nicht so schlecht aus würde ich sagen...

**Comment by 01af** [comment]
Hallo Wolfgang,

gern, hier ein anderes Beispiel:
KassenID: "CashBox01"
Belegnr: "00000001" 
Umsatz: 55,09
AES-Key (base64 encoded): "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU="

IV (ersten 16 byte):  3e 04 75 88 e2 0f 53 f9  2b bd f4 a9 c0 12 40 0d
Umsatz als Byte Array: 00 00 00 00 00 00 15 85
Ergebnis: "ByW5rsidWYI="

**Comment by wpichler** [comment]
Yep - sieht bei mir auch so aus - und ein dritter Wert noch zum Testen - mit den Selben Daten - umsatzzähler bei 1079,59 ergibt bei mir: WO2eoWfLI3U=

Wir könnten auch noch die Verkettungswerte vergleichen - am Besten vielleicht die ganze Kette als Beispiel irgendwo dokumentieren

**Comment by wpichler** [comment]
Ich habe mit den Daten eine Wiki Seite gemacht:
https://github.com/a-sit-plus/at-registrierkassen-mustercode/wiki/Beispiel-Daten-für-Entwicklungszwecke

**Comment by AndreErb** [comment]
@01af und @wpichler: Super! Danke für eure Beispiele und die Einträge im Wiki.
Ich glaube das kann vielen helfen (gilt zumindest für mich ;-))

Ich kann die oben und im Wiki aufgeführten [Beispiele und Ergebnisse](https://github.com/a-sit-plus/at-registrierkassen-mustercode/wiki/Beispiel-Daten-für-Entwicklungszwecke) bestätigen.

Umgesetzt habe ich es unter ``.NET`` im ``CFB``-Modus für die AES-Verschlüsselung.
Allerdings musste ich die Byte-Repräsentation des Umsatzzählers (long) bei Verwendung der .NET-Klasse ``BitConverter`` anschließend invertieren um von LittleEndian auf BigEndian und damit zu identischen Ergebnissen zu kommen.

BigEndian für den Umsatzzähler ist hoffentlich wirklich korrekt?

**Comment by asitplus-pteufl** [comment]
Ich möchte noch einen allgemeinen Hinweis geben:
Der Muster-Code und das Prüftool wurden mit Version 0.6 so ausgelegt, dass definierte Testfälle vorhanden sind. In Version 0.7 wird auch noch überprüft werden ob alle Testfälle abgedeckt wurden.

Bitte unbedingt den Abschnitt Testfälle im README lesen. Sie können die Testfälle von https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases beziehen. In den Testfällen finden Sie Instruktionen die Sie für Ihre Kasse verwenden können (AES Schlüssel, Belegtypen etc.). Wenn Sie die Ergebnisse als DEP Export exportieren, können Sie einfach mit dem Prüftool überprüfen ob die Ergebnisse Ihrer Kasse korrekt sind.

Es wurden daher keine zusätzlichen Beispiele angegeben. Was allerdings noch fehlt ist die Behandlung kürzerer Umsatzzähler im Muster-Code und im Prüftool (für nächste Version eingeplant)

Alle weiteren Details zu den Testfällen finden Sie in Abschnitt  6 im Detaildokument (https://github.com/a-sit-plus/at-registrierkassen-mustercode/releases)

**Comment by hcusto** [comment]
Hi @AndreErb did you manage to create Sales counter encription / decription in .Net? In mine (C#)  implementation everything works ok when sales couunter = 0, but for all other values I get a slightly wrong result. For example: 
Base64AesKey: "WQRtiiya3hYh/Uz44Bv3x8ETl1nrH6nCdErn69g5/lU="
KassenID: "CASHBOX-DEMO-1"
Belegnr: "CASHBOX-DEMO-1-Receipt-ID-6" 
Umsatz: 50501 (in eurocents)

Result from ValidationTool

k8wUAJDJ+Ro=

Result from my .net C# Implementation. 

k8wUAJDJPF8=

Any suggestions?

**Comment by asitplus-pteufl** [comment]
@hcusto are you using the current version 1.0.0 of the validation tool?

**Comment by asitplus-pteufl** [comment]
suggestion: could you create a chain of receipts and export them to the RKSV-DEP structure, and then verify them with the validation tool?
why? the tool will calculate the correct turnover counter for this chain according to the public tax-set entries in the machine readable code and compare the calculated turnover counter with the encrypted one? If you do this the tool will give you the detailed turnover values as output. This might indicate if you have a slight miscalculation error or something more fundamental (wrong encoding, encryption etc). 
You should also do this for negative turnover counter values...

**Comment by hcusto** [comment]
@asitplus-pteufl I did just that. I first generated data with "java -jar regkassen-demo-1.0.0.jar -n 20 -g -s"  command. Validated that and everything was ok. After that I used generated TESTSUITE_TEST_SZENARIO_1.json, imported all the data, and processed it through my implementation. And generated data in the same format as regkassen-demo I generated dep-export.json,  cryptographicMaterialContainer.json and qr-code-rep.json. After I run my dep-export.json through valdiation tool 1.0.0 , everything was ok when TotalCounter was 0. But as soon as TotalCounter is greater than 0, I get Fail test wit error https://gist.github.com/hcusto/e1d6fdff02f1f9ddd60f3f9bafcff509 

After that I compared everything and difference was in Encrypted Turnover Value (which I explain in post above). 

Here is working example with the same data.

https://dotnetfiddle.net/8FT29H

**Comment by areiter** [comment]
Please refer to the details of the encryption process in the specification.

Currently in your code in method `encryptECB` the parameter  `turnoverCounter` is not even involved in the encryption process.
Just look at the documents how to "simulate" CTR mode with ECB mode.
You are missing some XOR operation, that is also the reason why it works with a turnover value of "0"

**Comment by hcusto** [comment]
Thanks, 
I was actually trying to prepare project that could be easily tested, and while doing so, I tested couple of ECB methods I was using before.  

The problem I had was the same that @AndreErb had, I wasn't converting turnoverCounter byte array to BigEndinan. Now everything is working as expceted.  Thanks all.

**Comment by asitplus-pteufl** [comment]
one more hint (as mentioned above), make sure to test the behaviour for negative turn over counter values ...

**Comment by FleiTec** [comment]
Hab grad wie ein Depp gesucht! Achtung bei 

> wpichler  commented on Jun 10 2016 
Yep - sieht bei mir auch so aus - und ein dritter Wert noch zum Testen - mit den Selben Daten - umsatzzähler bei 1079,59 ergibt bei mir: WO2eoWfLI3U=

Hier ist Belegnummer: 00000002
