### ISSUE TITLE
Option -k ignored by verification jar

### ISSUE THREAD

**Issue by dfens** [a-sit-plus/at-registrierkassen-mustercode#93]
Command

```
java -jar regkassen-verification-depformat-0.5.jar -i=CashBoxDemoOutput2016-06-10T09-53-59/dep-export.txt -k=CashBoxDemoOutput2016-06-10T09-53-59/aesKeyBase64.txt 
```

however content of aesKeyBase64.txt is

```
abcd
```

whatever I put into aeskeybase file - it is ignored and verification app does not print any error at all. Always getting:

```
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
```

I checked code of jar and there is a small bug in logic of arguments:
```
String inputAESKeyFile = cmd.getOptionValue("k");
            if (inputFileString == null) {
                System.out.println("no AES key file given, cannot check turnover counters");
            }
```

it should check for `inputAESKeyFile == null` however it is not the problem here.

So question is: is even Umsatzzähler value verified by verification jar?

**Comment by 01af** [comment]
Hi dfens, 
you are using an older version! 
Try version 0.6. 
Instead of option -k you will have to use -c to pass a cryptographicMaterialContainer.json.

**Comment by dfens** [comment]
Thanks, you are right :) 0.6 works like a charm

**Comment by dfens** [comment]
@01af this raises kind of question:
- why is format of 0.5 so much different than 0.6?

I tought that this dep-export.json + aeskeybase.txt are expected outcome and this is DEP report. So there must be some strict specification somewhere of those files but as I see it changed between versions.

Or rather this project is kind of specification by itself and all valid dep reports should be aligned to newest version of validator?

**Comment by 01af** [comment]
@dfens 
To my understanding, only the DEP Export as JSON structure is demanded by RKSV.

The cryptographicMaterialContainer.json is not defined in RKSV, and just used in the ASIT  "mustercode" to store and retrieve the required cryptographic data in a convenient way. 

But to be on the safe side, maybe reopen and ask @asitplus-pteufl if this is actually true.

**Comment by dfens** [comment]
Thank you, 
problem is that aeskeybase will be required to verify turnover so pure dep-export.json without it may not make sense.

**Comment by 01af** [comment]
@dfens 
Yes, that is correct.  However , to my understanding the data is shared in a different way.
Each cash register has to be registered at the ministry of finance (BMF).
This procedure includes telling them the (see RKSV §16):
* Certificate Serial Number
* Type of secure signature-creation device
* Cashbox ID
* AES key for the encrypted turnover counter

**Comment by dfens** [comment]
Yes, that answers my question. Thank you again

**Comment by asitplus-pteufl** [comment]
just a short summary, so that you have an official technical answer:
for production use only the dep-export format is required. the additional files are only required by the verification tool for signature verification and turnover counter decryption.

As mentioned by @01af the other information needs to be registered with the BMF.
