### ISSUE TITLE
DEP - optionale Daten und Prüfung 

### ISSUE THREAD

**Issue by senton82** [a-sit-plus/at-registrierkassen-mustercode#94]
Den Richtlinien für RKSV ist zu entnehmen, dass im DEP sowohl das Zertifikat als auch die Zertifizierungsstelle als optionale Daten für jeden Beleg mitgespeichert werden können.

In meiner Implementierung würde ich es nun vernachlässigen diese Daten unnötigerweise reduntant abzuspeicher, da die Verbindnung zwischen Signaturerstellungseinheit und Beleg duch die in der Payload signierten Seriennummer gegeben ist.

Sehe ich es Richtig, das es somit bei einer eventuellen Überprüfung durch die Finanz ausreicht, die für eine Kasse verwendeten Zertifikate und die Zertifizierungsstelle präsentieren zu können, damit diese in den CM-Container zur Validierung kopiert werden können?

LG,
Stefan

**Comment by asitplus-pteufl** [comment]
Wie gesagt, es reicht vollkommen aus, wenn keine Zertifikate im DEP gespeichert werden.

**Comment by senton82** [comment]
Danke!
