### ISSUE TITLE
Test-App

### ISSUE THREAD

**Issue by woko1754** [a-sit-plus/at-registrierkassen-mustercode#95]
Wird es eine App zum Prüfen des QR-Codes geben, und wenn ja, wann und wo wäre diese erhältlich ?

**Comment by asitplus-pteufl** [comment]
Die Antwort kann in zwei Richtungen gehen:

Aus Herstellersicht:

In dem Fall verweise ich Sie an die Prüftools auf dieser Seite, die auch noch weiterentwickelt werden.

Aus Unternehmersicht verweise ich auf folgende Antwort des BMFs:

Vom BMF war zu erfahren, dass es mehrere Varianten für die Belegprüfung geben wird:

Web-Service Schnittstelle Finanzonline für Kassen: https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/softwarehersteller-funktionen.html#heading__2

Prüfapplikation (mobile App) für den Unternehmer (Ab Juli 2016)

Weitere Informationen dazu sind vom BMF mittels überarbeitetem Erlass zur Einzelaufzeichungs-, Registrierkassen- und Belegerteilungspflicht auf der Homepage des BMF voraussichtlich bis Juli 2016 geplant.

**Comment by michaelkorb** [comment]
Die Variante Webservice wäre toll, da man damit auch die Meldungen erledigen kann. Leider ist der Webservice noch nicht verfügbar. Gibt es da neue Erkenntnisse bzw. Ansprechpartner beim BMF?

**Comment by silence87** [comment]
Ich habe vorher bemerkt, dass der Link zum WSDL im PDF den HTTP-Fehler 405 Method not allowed zurückgibt. Folgt man allerdings dem Link zum WSDL, wie es im Link vom Post von Herrn Teufl zu finden ist, scheint es zu funktionieren. 
Also zumindest den Verweis kann ich mal ordnungsgemäß aufrufen, weiter war ich noch nicht.

**Comment by michaelkorb** [comment]
Welchen Link von Herrn Teufel meinen Sie?

**Comment by michaelkorb** [comment]
OK jetzt hab ich mir auch alle Dateien heruntergeladen und konnt damit den Dienstverweis verwenden.
Nun bin ich gespannt, ob der Service bereits existiert. Wahrscheinlich gibt es auch ein 405.
Lt. BMF-Hotline verzögert sich das ganze bis Ende September.

**Comment by asitplus-pteufl** [comment]
A-SIT Plus kann dazu keine Aussagen machen, bitte das BMF direkt kontaktieren.

**Comment by michaelkorb** [comment]
@ silence87: Mittlerweile hab ich den Webservice am laufen. Zumindest für die Anmeldung (Session). Der eigentliche Webservice ist am angegebenen Endpunkt nicht vorhanden. Prinzipiell ist das aber eine feine Sache, wenn es denn mal läuft.
