### ISSUE TITLE
Dokument Detailfragen v1.1 - Typo in Beispiel zur Aufbereitung OCR-Code

### ISSUE THREAD

**Issue by asitplus-tzefferer** [a-sit-plus/at-registrierkassen-mustercode#96]
Dokument "FESTLEGUNGEN DES BMF ZU DETAILFRAGEN DER REGISTRIERKASSENSICHERHEITSVERORDNUNG (RKSV)", Version 1.1, Seite 48:

Im Beispiel zur Aufbereitung des OCR-Codes wurde der Wert "Stand-Umsatz-Zaehler-AES256-ICM" aus dem beispielhaften maschinenlesbaren Code unvollständig extrahiert. Hier fehlt am Ende der Padding-Character "=".

**Comment by asitplus-pteufl** [comment]
Wurde in 1.2 behoben. Diese Release wird in Kürze freigegeben.
