### ISSUE TITLE
Prüfwerkzeug in Verbindung mit A-Trust Mobile 

### ISSUE THREAD

**Issue by poschinger** [a-sit-plus/at-registrierkassen-mustercode#97]
bitte löschen - Fehler gefunden ...

**Comment by poschinger** [comment]
folgender Output wird derzeit gegeben:

ÜBERPRÜFUNG: "Format: Anzahl Elemente": ERFOLGREICH
ÜBERPRÜFUNG: "Format: RK-Suite": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Datum/Uhrzeit Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Normal": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt1": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Ermaessigt2": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Besonders": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Satz-Null": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Zeichen - Verkettung voriger Beleg": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Umsatzzähler": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Signatur": ERFOLGREICH
ÜBERPRÜFUNG: "Format: Base64 Dekodierung/Kodierung - Verkettung voriger Beleg":
ERFOLGREICH
ÜBERPRÜFUNG: "Normale Buchung": Es handelt sich um eine normale Buchung (keine T
rainingsbuchung). (INFORMATION)
ÜBERPRÜFUNG: "Signatur kryptographisch": FEHLERHAFT
DETAILS: Kryptographische Gültigkeit der Signatur nicht gegeben. Es scheint aber
 nicht der definierte Fall der ausgefallenen Sicherheitseinrichtung zuzutreffen:
 Dekodierter Signaturwert: 0D☻ ►UèveXW^ñ◄i.◄_8ú▼ÇXÙËÐ+<♫??7~?☺µ☻ ¶°XS▲ÂÈ‼béÔê▬ê♠
☺çé­Åö?ðe4sh↑:k¿þ

ÜBERPRÜFUNG: "Gültigkeit der kryptographischen Kette": ERFOLGREICH
ÜBERPRÜFUNG: "Verschlüsselter Umsatzzähler": ERFOLGREICH
++++++++++++++++++++++++++++++

**Comment by A-Trust** [comment]
Um eventuell weiteren Benutzern der a.sign RK Online zu helfen, es gibt einen Demo Client welcher unter http://labs.a-trust.at/developer/ShowSource.aspx?id=128 verfügbar ist. 

Wir haben heute eine aktualisierte Variante des Clients zur Verfügung gestellt, in welcher ein durchgängies Beispiel enthalten ist. Zu diesem kann das DEP Protokoll und der Cryptographic-Material-Container exportiert werden und diese Dateien mit dem Prüftool (welches hier verfügbar ist) geprüft werden.
