### ISSUE TITLE
Registrierkassen-Webservice

### ISSUE THREAD

**Issue by SEHellFire** [a-sit-plus/at-registrierkassen-mustercode#99]
Voraussetzungen für den Registrierkassen-Webservice sind:

Der Übermittler muss FinanzOnline Teilnehmer sein.
· Der Teilnehmer muss in der Benutzerverwaltung einen Benutzer für 'Webservices'
anlegen.
· Das Webservice muss mit diesem Benutzer verwendet werden.

Und wie bitte soll ich als deutscher Kassenhersteller nun diesen WebService programmieren und testen? Gibt es entsprechende Test-Zugänge zu FinanzOnline und wenn ja, wie und wo bekommt man den Zugang? Und wenn nein - wer stellt mir seinen Privaten Zugang zu FinanzOnline zur Verfügung?!

**Comment by asitplus-pteufl** [comment]
Ich kann die Frage im Rahmen dieses Projekts leider nicht beantworten:

Dieses Projekt dient zur Behandlung technischer Sachverhalte der RKSV. Wir bitten daher um Verständnis, dass rechtliche/organisatorische Themen im Allgemeinen nicht beantwortet werden können. Für die Beantwortung solcher Fragen bitten wir Sie die Informationen des BMFs heranzuziehen (siehe https://www.bmf.gv.at/top-themen/Registrierkassen.html). Sollte Ihr Anliegen dort nicht behandelt sein, steht Ihnen unter https://www.bmf.gv.at/kontakt.html eine Möglichkeit zur Verfügung, Ihre rechtliche oder organisatorische Frage schriftlich im BMF einzubringen. Nutzen Sie dazu die Option “Sonstige Anfrage” und fügen Sie Ihrem Anliegen den deutlichen Hinweis hinzu, dass es sich um ein Thema im Bereich Registrierkasse handelt.

Ein weiterer Hinweis bezüglich den “Issues” in diesem Projekt: Offizielle – mit dem BMF abgestimmte – Aussagen werden nur vom Benutzer asitplus-pteufl getätigt. Für die Korrektheit der Aussagen anderer Benutzer kann keine Garantie übernommen werden.

**Comment by ErichFreitag** [comment]
@SEHellFire: ich kann dazu nur ergänzen:
- der FinanzOnline-Teilnehmer wird ja wohl das Unternehmen sein, welches die Kassen betreibt, also werden sie wohl auch diesen Zugang verwenden können/müssen
- die Schnittstelle hat einen Test-Modus

Alle anderen diesbezüglichen Fragen kann wohl nur das BMF beantworten.

**Comment by SEHellFire** [comment]
Ja,
inzwischen habe ich einen Telefonischen Kontakt zur UBit-Arbeitsgruppe Registrierkassen. Das Problem mit "Ausländischen" Softwareherstellern ist dort bekannt und diese Woche Thema im Arbeitskreis. Das Ergebnis werde ich wohl im Laufe der nächsten Woche erfahren und hier dann auch mitteilen.

**Comment by SEHellFire** [comment]
Es gab zu dem Thema inzwischen eine Rückantwort vom BMF.

Das WebService ist demnach erst Ende August benutzbar und bis dahin wird es dann auch Testzugänge geben.

Hier die Antwort:
--------------------
Sehr geehrter Herr Matz!

Unter

https://www.bmf.gv.at/egovernment/fon/fuer-softwarehersteller/informationen-fuer-softwarehersteller.html

werden ab August 2016 Testzugänge für Kassenhersteller zum Webservice zur Verfügung gestellt. 

Einen FinanzOnline Zugang bekommen Sie als nicht österreichischer Antragssteller nur, wenn Sie die Zugangsdaten persönlich in einem österreichischen Finanzamt übernehmen, oder einen in Österreich ansässigen Steuerberater beauftragen. Allerdings brauchen Sie dafür auch ein österreischisches Steuerkonto, was bei Ihnen als Kassenhersteller nicht der Fall sein wird. Insofern ersuchen wir Sie bis August um Geduld.

Mit freundlichen Grüßen
Ihre Finanzverwaltung

**Comment by SEHellFire** [comment]
Nach wie vor sind nirgendwo Informationen über die angedachten Testzugänge zu finden.

Auch das WKO-Forum, in dem ja Fragen gestellt werden sollen, ist nicht vom Ausland aus verfügbar. Eine Registrierung im WKO-Forum ist nur für WKO-Mitglieder möglich.

**Comment by asitplus-pteufl** [comment]
Ich werde die Anfrage an das BMF weiterleiten, möchte aber auch darauf hinweisen, dass dies hier der falsche Ort für die Anfrage ist, da dieser Teil nicht Fokus dieses Projekts ist. 

Bitte die Kontaktinfos aus dem README nutzen (BMF, WKO) etc.

**Comment by SchmidLukas** [comment]
Hallo,

Wir sind ein Niederländisches Softwarehaus und würden für den FinanzOnline Webservice ebenfalls einen Testzugang benötigen. Wir können aber selbst heute, 5 Jahre später, keine Informationen finden auf entsprechender Seite. Gibt es hier eventuell neue Informationen?

Beste Grüße
